### ISSUE TITLE
Intellij Idea Keybindings clipboardPasteAction not found

### ISSUE THREAD

**Issue by NickBolles** [coder/code-server#1105]
- `code-server` version: 
```
code-server --version
v10.15.1
```
- OS Version: docker
- Extension: [Intellij Idea Keybindings](https://github.com/kasecato/vscode-intellij-idea-keybindings)

## Description

When pasting in the editor I get a `"editor.action.clipboardPasteAction' not found` toast notification and pasting fails. But copying works successfully. 

I can also copy and paste just fine in the terminal.

Issue on the extension repo: https://github.com/kasecato/vscode-intellij-idea-keybindings/issues/163 

## Steps to Reproduce

1. 
1.

**Comment by NickBolles** [comment]
For anyone else finding this, I just overrode this keybinding with the following in my keybindings.json file
```
  // Remove incompatible paste action
  {
    "key": "ctrl+v",
    "command": "-editor.action.clipboardPasteAction",
    "when": "editorTextFocus && !editorReadonly"
  },
```

**Comment by danger89** [comment]
Uh.. yup something is wrong. I'm using v2 of code-server.

![image](https://user-images.githubusercontent.com/628926/68033142-6b42be00-fcbf-11e9-94b9-131950c742ec.png)

**Comment by code-asher** [comment]
You might be running into this: https://github.com/cdr/code-server/issues/1106

If so, the best solution is to use HTTPS. There's a workaround for pasting but I'm not sure there's one for copying (it might work to just unbind it).

**Comment by danger89** [comment]
I'm using HTTPS. But I'm using Nginx reverse proxy in between.

**Comment by code-asher** [comment]
> **EDIT:** Lets put it differently, I do not need the HTTPS from code-server. I can use plain communication between Nginx and the localhost:8080, and my separate Nginx reverse proxy server is taking care of the SSL stuff (which is running on port 443, publicly available).

That sounds good; I use the same setup. As long as the browser itself is seeing an HTTPS all is well. But I realized I missed some information about Firefox so I elaborated here: https://github.com/cdr/code-server/issues/1106#issuecomment-548911682

**Comment by bgold0** [comment]
Should note that pasting works fine when nothing is selected. It's only when things are selected that you get this error.

**Comment by NickBolles** [comment]
> Should note that pasting works fine when nothing is selected. It's only when things are selected that you get this error.

My initial issue was happening whether or not I had anything selected. That issue is resolved (by removing the command in the intellij extension). Maybe we should create a new issue for any other root causes.

**Comment by nhooyr** [comment]
Upstream issue.

**Comment by nhooyr** [comment]
Not really an upstream issue, we should just patch it, it'd be really easy afaik.

**Comment by nhooyr** [comment]
Only for chromium based browsers and Firefox though, safari doesn't support the clipboard API we'd need.

**Comment by nhooyr** [comment]
Or actually, I wonder what they do for the terminal in Safari.

**Comment by nhooyr** [comment]
Yea I'm actually confused how the terminal supports copying since it's rendering to a canvas so I can't select any text and so `document.execCommand("copy")` wouldn't work.

**Comment by nhooyr** [comment]
Figured it out. See https://github.com/xtermjs/xterm.js/blob/7f598a36753f4d950ee63dc91bd6a92290f7e037/src/browser/Clipboard.ts

They have a DOM element they populate right before a selection occurs to ensure the DOM is in sync with what's actually being selected.

**Comment by nhooyr** [comment]
Oh, nvm, check this out: https://developer.mozilla.org/en-US/docs/Web/API/Element/copy_event

That's what they're using. Not sure what the above is about then.

**Comment by nhooyr** [comment]
Mhmm, same with pastes: https://github.com/xtermjs/xterm.js/blob/7f598a36753f4d950ee63dc91bd6a92290f7e037/src/browser/Clipboard.ts#L45

**Comment by hjfreyer** [comment]
FYI, I'm running into this when trying to use an extension that explicitly calls `editor.action.clipboardPasteAction`.

**Comment by jsjoeio** [comment]
Sorry to hear that @hjfreyer - do you mind providing your OS information and reproduction steps? You can see an example in the bug-report issue template [here](https://github.com/cdr/code-server/issues/new?assignees=&labels=&template=bug-report.md&title=)

**Comment by hjfreyer** [comment]
Repro steps are in https://github.com/yzhang-gh/vscode-markdown/issues/917.

## OS/Web Information

- Web Browser: Chrome
- Local OS: Chrome OS 89.0.4389.82 (Official Build) (64-bit)
- Remote OS: Debian (not exactly, but close enough)
- Remote Architecture: amd64
- `code-server --version`: 

```
[2021-03-22T17:01:17.182Z] info  Using config file ~/.config/code-server/config.yaml
3.5.0 de41646fc402b968ca6d555fdf2da7de9554d28a
```

**Comment by hacker1024** [comment]
This is still relevant.

**Comment by code-asher** [comment]
We are closing out old issues but let me know if this is still an issue.  That said, it is probably not something we can fix, likely it is an issue in VS Code core.
