### ISSUE TITLE
Chrome Debugger and Firefox Debugger

### ISSUE THREAD

**Issue by sh7dm** [coder/code-server#1419]
I can't run https://github.com/microsoft/vscode-chrome-debug nor https://github.com/firefox-devtools/vscode-firefox-debug on `code-server`, since they require browser window to open. My question is: can I force them to run with e.g. x11 forwarding or debug port forwarding? Almost any solution is acceptable!

**Comment by sh7dm** [comment]
A solution has been found by me:
As follows from [this source fragment](https://github.com/microsoft/vscode/blob/8c4c01fb800017fe36657ede98d594cef9405922/src/vs/workbench/services/extensionManagement/common/extensionEnablementService.ts#L135-L159), I changed `ui` to `workspace` in `package.json` of extension I copied from local install. This works well! But I want to find a more simple & less hacky solution for that. Thanks in advance!

**Comment by kylecarbs** [comment]
Interesting, they work as expected after that?

**Comment by sh7dm** [comment]
They work well, I tested them locally, but you can give them a remote-forwarded port if it's real remote development. `ssh -f -n -R 6000:localhost:6000 user@host` as I remember for Firefox with debug-port opened. Alternatively, x11 forwarding can be used.

**Comment by sh7dm** [comment]
I think code-server should disable incompatible exts by default, but giving user the ability to enable them from UI, of course taking the risk, with no warranty about how extensions will behave.

**Comment by kylecarbs** [comment]
I agree. We'll definitely fix :)

**Comment by sh7dm** [comment]
Hmm, I tested this with a real remote setup (client laptop + server PC in LAN) and Firefox Debugger fails printing weird errors to `Log (Window)`. Server: Ubuntu 19.10, client: Win 10, Browser: FF. Probably this extension is incompatible with remote, but maybe it's not? Will capture the error in a moment.

**Comment by sh7dm** [comment]
Sorry for long wait.
![image](https://user-images.githubusercontent.com/19504461/77431675-14648f00-6dee-11ea-8526-ef617d651261.png)

**Comment by kylecarbs** [comment]
Hm, I'm pretty confused. Are you proxying the FF debug port?

**Comment by sh7dm** [comment]
Yes, it's remote-forwarding. SSH client is Putty. I have also tried just accessing client's port from server, since I'm connecting via LAN. It does connect, but throws those errors. Probably I should open a ticket to Firefox Debugger asking for official server support, shouldn't I?

**Comment by sh7dm** [comment]
Same with Ubuntu 19.10 & OpenSSH on client. The OpenSSH command is:
`ssh user@192.168.X.Y -p S -R 6000:localhost:6000 -L P:localhost:P -L 8080:localhost:8080`
`192.168.X.Y` is server IP
`S` is SSH port there, not 22
`P` is `code-server` port, not 8080
8080 is an example app I try to debug.

**Comment by sh7dm** [comment]
Also, neither with Windows nor Ubuntu, Firefox didn't show the confirmation for connection, so probably there may be an issue with smth else.

**Comment by kylecarbs** [comment]
Weird issue. I couldn't see a reason why forwarding your debug port wouldn't work. Have you made any new discoveries with this?

**Comment by sh7dm** [comment]
Sadly, no. Maybe source lines from logs can tell us smth?

**Comment by leojonathanoh** [comment]
any chance websockets work for remote debugging? In my setup i have no ssh access to the server, so i can't use ssh port-forwarding.

**Comment by jsjoeio** [comment]
Good question! Any ideas @code-asher ?

**Comment by code-asher** [comment]
Out of the box I don't think so but I think we can probably add
something to tunnel ports through a web socket.

**Comment by leojonathanoh** [comment]
I was writing some client side javascript for the browser and couldn't test it in vscode. While I could use the browser debugging I would have to switch back and forth, at least that's my use case. There would probably be lot more use cases than just this :)

**Comment by leojonathanoh** [comment]
im thinking this will probably be easier to solve if firefox / chrome ran on the server (much like code-server!) and the client instance was doing remote debugging against that server instance. But i'm not sure if that exists at all.

**Comment by sergeycherepanov** [comment]
JFY I use the https://github.com/jpillora/chisel for forwarding, but the native extension does not work without small patches.
