### ISSUE TITLE
Set environment variable VSCODE_PROXY_URI

### ISSUE THREAD

**Issue by benz0li** [coder/code-server#1510]
With the implementation of the [HTTP proxy](https://github.com/cdr/code-server/pull/1453) it would be great to have an environment variable `VSCODE_HTTP_REFERER` available to build custon URLs for proxied webview requests.

This feature helps solving https://github.com/Ikuyadeu/vscode-R/issues/275. The existence of such an environment variable also allows to differentiate a local (VS Code) installation from a server (code-server) installation.

Other server-based IDEs set an environment variable based on the HTTP referer when the client session is initialized. See https://github.com/rstudio/rstudio/blob/aa266ded96123f654e5f3163cde39697744eee89/src/cpp/session/SessionClientInit.cpp#L170 for example.

Could you implement something similar in code-server? Or is the information on the HTTP referer already available somewhere else?

**Comment by kylecarbs** [comment]
Neat. I don't think we have this ATM.

Thoughts @code-asher ?

**Comment by code-asher** [comment]
I experimented with replacing `127.0.0.1:<port>` with` /proxy/<port>` before writing out the webview HTML which worked for the PlatformIO extension but then it tried to make a websocket connection against the root (`/wsrpc`) instead of being relative (`/path/<port>/wsrpc`) which obviously won't work.

So the environment variable sounds like a reasonable way to solve this. Either that or require that extensions be aware that they might be behind a proxied base path and make connections accordingly. There might be other cases I haven't considered though and the environment variable seems like the most flexible.

**Comment by code-asher** [comment]
We should also make this environment variable available to the terminal, see https://github.com/cdr/code-server/issues/1939.

**Comment by benz0li** [comment]
@code-asher Any timeframe on this issue? Does the name tend towards `VSCODE_HTTP_REFERER` or [`CODE_SERVER_HTTP_REFERER`](https://github.com/cdr/code-server/issues/1939#issuecomment-668158611)?

The project collaborators at [Ikuyadeu/vscode-R](https://github.com/Ikuyadeu/vscode-R) might give another go at https://github.com/Ikuyadeu/vscode-R/issues/275 while working on https://github.com/Ikuyadeu/vscode-R/issues/358.

**Comment by code-asher** [comment]
We don't have this on the roadmap at the moment but it seems pretty
trivial to implement so I think we could reasonably have it for 3.11.0.

**Comment by code-asher** [comment]
Oh right the name. I think `CODE_SERVER_HTTP_REFERER` makes sense.

**Comment by benz0li** [comment]
> Oh right the name. I think `CODE_SERVER_HTTP_REFERER` makes sense.

@code-asher Keeping in mind other derivatives of VS Code (i.e. [VSCodium](https://github.com/VSCodium/vscodium) and [Eclipse Theia](https://github.com/eclipse-theia/theia)) it would make sense to tend towards `VSCODE_HTTP_REFERER`.  
👉 The name of their ancestor; a common name to implement the functionality for [Ikuyadeu/vscode-R](https://github.com/Ikuyadeu/vscode-R) in all of VS Code derivatives - if their collaborators decide to do so.

Agreed?

**Comment by benz0li** [comment]
Alternaively `HTTP_REFERER`; neutral, not mentioning a product name.

**Comment by code-asher** [comment]
That makes perfect sense to me! My vote would be for `HTTP_REFERER` I think but I'm good with either one.

**Comment by benz0li** [comment]
Please use `VSCODE_HTTP_REFERER` then, as there are already other environment variables in code-server prefixed with `VSCODE_` referencing to its ancestor; e.g. `VSCODE_GIT_IPC_HANDLE`, `VSCODE_GIT_ASKPASS_NODE`, etc.

Thank you!

**Comment by code-asher** [comment]
Should we be using the actual `referer` header here (or host actually I suppose)? Or do we want the proxy path? If it needs to be general for other editors I'm thinking they might not all have `/proxy` or might do it differently so maybe we need something like `VSCODE_PROXY_URI` or something like that, perhaps with `{port}` in it.

Then if the user has sub-domain proxies enabled we could set it to `{port}.mydomain.com` and if they don't we could set it to `mydomain.com/proxy/{port}`. And if the environment variable already exists we wouldn't override it so users could provide their own proxy through Caddy, NGINX, etc.

Otherwise we might need to use `CODE_SERVER_HTTP_REFERER` so extensions can tell the difference between editors and select the URL appropriately.

**Comment by benz0li** [comment]
@code-asher The actual `referer` is sufficient.

**Comment by code-asher** [comment]
It does, it's just less stable because not all applications handle the base path properly so I'm biased against it haha :stuck_out_tongue: In this case it's probably fine though.

Does Theia support `/proxy` as well?

**Comment by benz0li** [comment]
I don't think Theia supports `/proxy`: https://github.com/eclipse-theia/theia/discussions/8821.

**Comment by code-asher** [comment]
Gotcha, do we need to consider that they (or some other editor) might choose a different path than code-server if they do implement it? (In which case I imagine extensions need a way to distinguish between editors.)

**Comment by benz0li** [comment]
For the time being, you don't have to take this into account.

**Comment by benz0li** [comment]
And if the user has sub-domain proxies enabled: Not setting `VSCODE_PROXY_PATH` at all.  

From the viewpoint of the extension:

1.  If `VSCODE_PROXY_PATH` is set, use that proxy path.
2. If `VSCODE_PROXY_PATH` is unset, use the sub-domain proxy.

**Comment by benz0li** [comment]
Having said the above, I realise that `VSCODE_PROXY_URI` is the better solution.

> [...] if the user has sub-domain proxies enabled we could set it to `{port}.mydomain.com` and if they don't we could set it to `mydomain.com/proxy/{port}`. And if the environment variable already exists we wouldn't override it so users could provide their own proxy through Caddy, NGINX, etc.

Go ahead with this solution.

**Comment by benz0li** [comment]
@code-asher Having said the above, I realise that `VSCODE_PROXY_URI` is the better solution.

> [...] if the user has sub-domain proxies enabled we could set it to `{port}.mydomain.com` and if they don't we could set it to `mydomain.com/proxy/{port}`. And if the environment variable already exists we wouldn't override it so users could provide their own proxy through Caddy, NGINX, etc.

Go ahead with this solution.

**Comment by code-asher** [comment]
Sounds good! I'll knock this out tomorrow so let me know if anything changes in the meantime.

**Comment by benz0li** [comment]
@code-asher I'm running code-server via JupyterHub as part of a JupyterLab image. There is a deployment at https://vscode-r.jupyter.b-data.ch for which your GitHub account has been whitelisted.

**Comment by code-asher** [comment]
I appreciate it!

**Comment by benz0li** [comment]
@jsjoeio Whitelisted your GitHub account for https://vscode-r.jupyter.b-data.ch, too.

This setup has become my web-based Data Science development platform of choice.

**Comment by jsjoeio** [comment]
Wow! I'm really impressed with this platform/setup. Might be interesting to have you chat about it at Coffee and Coder with @bpmct

**Comment by benz0li** [comment]
> Wow! I'm really impressed with this platform/setup. Might be interesting to have you chat about it at Coffee and Coder with @bpmct

I've whitelisted @bpmct for https://vscode-r.jupyter.b-data.ch, too.

**Comment by benz0li** [comment]
The setup is based on https://gitlab.b-data.ch/docker/deployments/jupyter and currently running
*  JupyterHub v1.4.1
*  JupyterLab v3.0.16 including
    *  code-server v3.10.2 (aka VS Code v1.56.1)
    *  Extensions: R v1.6.8 and R LSP Client v0.1.14, ...
    * ...

👉 Full specification of the JupyterLab image at https://gitlab.b-data.ch/jupyterlab/r/r-ver/-/blob/master/r-ver/latest.Dockerfile; plus `libxt-dev` installed in addition.

I’m happy to further customize the Docker image, i.e. adding any Linux package you need for testing/development/etc*.
ℹ️ JupyterLab (code-server) runs in a docker container; docker volume for `$HOME`; no `sudo` rights

**Comment by benz0li** [comment]
Installed packages according to https://github.com/cdr/code-server/blob/main/docs/CONTRIBUTING.md#requirements

**Comment by benz0li** [comment]
@jsjoeio Should one be able to develop extensions with code-server?

I followed https://github.com/Ikuyadeu/vscode-R/wiki/Contributing and `/opt/code-server/extensions/ikuyadeu.r-1.6.8/out/extension` gets activated instead of the modified version of vscode-R (in this case `~/projects/ikuyadeu/vscode-R/out/extension`).

**Comment by jsjoeio** [comment]
Hmm...it looks like there was [an issue](https://github.com/cdr/code-server/issues/667) in the past but I haven't tried ever so I can't say. 

I'm also not familiar with vscode-R.

If you follow [this Hello World guide](https://code.visualstudio.com/api/get-started/your-first-extension) and it doesn't work with code-server, then there is probably a bug (and you can open a separate bug report for us to look into).

**Comment by benz0li** [comment]
Opened separate bug: https://github.com/cdr/code-server/issues/3661

**Comment by jsjoeio** [comment]
Awesome. You rock! Thank you!

**Comment by benz0li** [comment]
FYI https://vscode-r.jupyter.b-data.ch has been updated:

*  JupyterHub v1.4.2
*  JupyterLab v3.1.12 including
    *  code-server v3.12.0 (aka VS Code v1.60.0)
    *  Extensions: R v2.2.0
    * ...

**Comment by jsjoeio** [comment]
Just a heads-up - we've had a bunch of other priorities come up and haven't been able to get to this yet (but we will soon)

**Comment by benz0li** [comment]
@code-asher This sets `mydomain.com/proxy/{{port}}` instead of `mydomain.com/proxy/{port}`. 
ℹ️ Tested with the [latest release artefacts](https://github.com/coder/code-server/actions/runs/1655552758).

Why the double brackets?

**Comment by code-asher** [comment]
Ahh I did not realize this was already implemented in vscode-R!

I used double braces to match VS Code's own templating scheme they use with webview URIs.  I will go ahead and move back to one.
