### ISSUE TITLE
C++: Tasks not detected by debugger

### ISSUE THREAD

**Issue by ahshabbir** [coder/code-server#1616]
When running the debugger for an active C++ file, the debugger throws an error saying that it cannot find the build task associated with the debug configuration. This is strange because the same launch.json and tasks.json work properly in a native copy of vscode, although the native copy is at a slightly higher commit (ff... vs fd...). I searched through the vscode issues directory and I couldn't find anything pertaining to 'c++ debug', so I figured the issue was in code server. Below are the links to the pastebins of the tasks/launch.json, exthost log, and stdout. Please let me know if you need anything else.

**tasks/launch**
https://pastebin.com/5nZ36twb
**stdout**
https://pastebin.com/aVE1aDPJ
**exthost.log**
https://pastebin.com/dvaT5FnN

**Comment by frol** [comment]
I am experiencing the same issue

**Comment by nhooyr** [comment]
@ahshabbir Can you try the latest release?

**Comment by ahshabbir** [comment]
I've tried the latest release, the editor seems to hand after you press the play button. Looking at my task manager I noticed that 'cpptools', an executable that is apart of the C++ extension for vs code, was the hanging process. Because this executable is in the extensions folder, I'm starting to think that this is now an issue with the C++ plugin. I'll look through the logs later and see if I find anything new.

**Comment by nhooyr** [comment]
@ahshabbir Try local VS Code to see if it works.

**Comment by ahshabbir** [comment]
Local VS Code still works, although I'm on a lower version (1.45 vs 1.46 on code-server). The problem now is that the editor hangs when you initiate the debug session.

**Comment by nhooyr** [comment]
@ahshabbir Try upgrading to the latest release, it downgrades to 1.45.1.

**Comment by ahshabbir** [comment]
The issue persists with 3.3.1

**Comment by jsjoeio** [comment]
Follow the repro steps here: https://github.com/cdr/code-server/issues/3643

**Comment by XLJ-CN** [comment]
> Follow the repro steps here: #3643

 Will this problem be solved in the next version?

**Comment by jsjoeio** [comment]
> Will this problem be solved in the next version?

No, this is in the Backlog. All things in the [3.11 milestone](https://github.com/cdr/code-server/milestone/26) will be in the next version. You can read about our workflow [here](https://github.com/cdr/code-server/blob/main/docs/MAINTAINING.md#workflow).

If this is priority for you, I can move it to On Deck and we can take a look in the next version cycle?

**Comment by XLJ-CN** [comment]
> > Will this problem be solved in the next version?
> 
> No, this is in the Backlog. All things in the [3.11 milestone](https://github.com/cdr/code-server/milestone/26) will be in the next version. You can read about our workflow [here](https://github.com/cdr/code-server/blob/main/docs/MAINTAINING.md#workflow).
> 
> If this is priority for you, I can move it to On Deck and we can take a look in the next version cycle?

Yes! This function is very important to me，thank you!
