### ISSUE TITLE
Browser back button weird behaviour

### ISSUE THREAD

**Issue by avelino** [coder/code-server#174]
- `code-server` version: master branch
- OS Version: macOS

## Description

I use **Magic Trackpad 2** to move mouse point and swipe to right returning to previous page 

## Steps to Reproduce

1. open new tab
1. open `code-server` in new tab

![Screen Shot 2019-03-09 at 6 02 18 PM](https://user-images.githubusercontent.com/31996/54077343-a823f580-4295-11e9-9995-f11bbf98f2a0.png)

**Comment by tiffany352** [comment]
I have a mouse that has hardware forward/back buttons and I have muscle memory for using them to switch between files in VS code. It would be great if code-server could map those bindings, as well!

**Comment by kylecarbs** [comment]
Should prompt now :confetti_ball:

**Comment by CSchlipp** [comment]
I'd like to reopen this issue. 
The latest version shows exactly the same behavior as described in this bug report. 
Mouse-Back button navigates to a previous browser page in Chrome. The browser only prompts for confirmation if there are unsaved changes in the **currently opened** file. Unsaved changes in other editor tabs do not open a prompt.

Ideally, the back button should have the same function as in VS Code, namely to navigate to the previous file within this codespace workspace.

Versions:
Version: 1.43.2
Commit: 28e91ba70cd70fa9adf3f2e3e3b87631b5667ecf
Date: 2020-04-14T22:51:57.043Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36

**Comment by mahmoudajawad** [comment]
I can confirm that back button does navigate to previous page without any warning.

personally I believe navigation buttons should not interfere with code-server functionalities, that is not having any effect on code-server, either by triggering browser history functionality nor editor previous file functionality.

**Comment by CSchlipp** [comment]
@kylecarbs Would you be so kind to please reopen this issue?

**Comment by code-asher** [comment]
At some point I stopped getting prompts as well. My changes are still there though when I come back to the editor. I wonder if VS Code opted to start doing that instead of the prompt.

When I use code-server as a PWA sometimes back/forward switches between files (as they should) and sometimes they cause page navigation. It's a bit strange and probably worth investigating.

**Comment by avelino** [comment]
When:
- I open a blank page (new browser tab)
- I type the address of the http server (ex: 127.0.0.1:5050) that runs my code-server


the browser enables the _"back button"_ to return to the blank page

**Comment by nhooyr** [comment]
We should figure out the exact behaviour and document it as an FAQ entry.

**Comment by nhooyr** [comment]
Can reproduce though, I randomly get the prompts as well on Chrome.

In Safari however I get them 100% of the time lol.

**Comment by nhooyr** [comment]
Looks like the pattern is if you just edit the file and leave, no prompt but if you save the file explicitly once, then it prompts you.

**Comment by nhooyr** [comment]
Nvm, just seems completely random lol.

**Comment by CSchlipp** [comment]
One thing I can reproduce all the time is that on two subsequent back-operations, if the first one shows a warning that gets cancelled, the second one does an immediate redirect without a warning.

If I had to guess, I'd put my money on a wrongly stored application state for the back-button warning.

However, as stated above, the back-button should always be intercepted to either go to the last opened files in code-server, or - if the stack is empty - call the last URL in browser history. (Technically speaking, the same behaviour might be accomplished using JS by pushing all changes of the currently opened file to the browser history?)

**Comment by CSchlipp** [comment]
Issue still valid for code-server v4.3.0

**Comment by code-asher** [comment]
I seem to get a prompt reliably if I have edits, but either way this is an upstream bug so we should try reproducing in Codespaces and report at https://github.com/microsoft/vscode
