### ISSUE TITLE
Can't load LaTeX Workshop extension

### ISSUE THREAD

**Issue by maresb** [coder/code-server#1828]
I am trying to run the [LaTeX Workshop extension (james-yu.latex-workshop)](https://github.com/James-Yu/LaTeX-Workshop). I have tried with extension versions 8.7.2, 8.10.0 and 8.11.0, all with the same results. I get the error `command 'latex-workshop.view' not found` when I click the "View LaTeX PDF File" icon, and nothing else happens.

Digging deeper, enabling source map support, the Output termninal "Log (Remote Extension Host)" shows the following error message.
```
[2020-06-24 00:09:19.066] [exthost] [error] Activating extension James-Yu.latex-workshop failed due to an error:
[2020-06-24 00:09:19.067] [exthost] [error] Error: Cannot find module '/home/jovyan/.local/share/code-server/extensions/james-yu.latex-workshop-8.10.0/out/src/main.js'
```
The `out/` subdirectory does not exist.

My interpretation is that `out/` is supposed to contain build targets which are somehow not being built. Indeed, [the extension's GitHub](https://github.com/James-Yu/LaTeX-Workshop/tree/master/src) contains `/src/main.ts` but no `/out/`. I don't know any TypeScript, so does this make sense? Any idea how to fix it?

- Web Browser: Firefox
- Local OS: Ubuntu 20.04
- Remote OS: locally-running [jupyter/tensorflow-notebook](https://github.com/jupyter/docker-stacks) Docker container
- Remote Architecture: x86_64
- `code-server --version`: 3.4.1 48f7c2724827e526eeaa6c2c151c520f48a61259

Note: I am able to manually install the `.vsix`.

**Comment by nao20010128nao** [comment]
Temporary fix: extract `/extension/out/` inside VSIX, as it contains a valid `out/` directory.

**Comment by maresb** [comment]
@nao20010128nao, sorry I don't understand. Where is `/extension/out/` and what would be the full command?

**Comment by nao20010128nao** [comment]
@maresb Because VSIX file is actually ZIP file, you can extract it using ZIP utilities like `unzip` command.

**Comment by nhooyr** [comment]
cc @cmoog

**Comment by bersbersbers** [comment]
I had the same problem when trying to build LaTeX-Workshop myself for the first time (in local VS Code):

```
npm install vsce
git checkout https://github.com/James-Yu/LaTeX-Workshop
cd LaTeX-Workshop
vsce package
code --install-extension latex-workshop-*.vsix
```

While it installed successfully, it did not load. What I was missing, after the `git checkout`, was to open `LaTeX-Workshop` in VS Code, F1, ">Run Build Task". Did that, repackaged and installed, and got it working.

Hope this helps anyone.

**Comment by tidux** [comment]
The extension now installs and provides syntax highlighting but none of the other functionality works.  Tested with code-server v3.8.0.

**Comment by wieluk** [comment]
I installed via vsix in coder-server 3.9.0
The pdf view doesn't work like explained in other issues.
Building does Work

And highlighting doesn't work anyone a clue how to fix it or why it might not hightlight anything?

**Comment by HannesGitH** [comment]
for those facing the same issue, run
```
curl -fsSL https://gist.githubusercontent.com/HannesGitH/bf70790accef0773821fd6b83b335292/raw/installing-latexworkshop-for_code-server__quickfix.sh | sh 
```
on your remote host for a quick fix

**Comment by bersbersbers** [comment]
@HannesGitH your scripts loads `_out` from the v3.9.0 asset into an v8.15.0 install. Is that intended?

**Comment by HannesGitH** [comment]
> @HannesGitH your scripts loads `out` from the v3.9.0 asset into an v8.15.0 install. Is that intended?

eeehh probably not :D it was late in the evening and my own project was at v3.9.0, so i just confused it sorry
it worked though..
but imma fix it in a minute

but thanks for pointing it out

**Comment by HannesGitH** [comment]
@bersbersbers it wasn't, thanks for pointing it out 👍 <sub> (it was late and i accidentaly put the version of code-server there :D , it worked though ) </sub> 

**fixed it** , the fetched version is now the one currently installed

**Comment by HannesGitH** [comment]
ok sadly it seems like my workaround script wont work with 8.18. onward..  (at least in my setup afaik)
havent looked into why yet, just reverted to an older version

**Comment by tidux** [comment]
I can confirm this issue still exists on code-server 3.12.

**Comment by ykazakov** [comment]
Just to report: LaTeX Workshop v8.23.0 works fine under code-server 4.0.1.
<img width="883" alt="Screenshot 2022-01-14 at 09 12 21" src="https://user-images.githubusercontent.com/2140361/149473871-1ff83ef9-db43-4e64-a003-ec224a8b68cb.png">

Both code-server and texlive are installed over homebrew on MacOS 12.1.

Note that the pdf previewer is running on a separate port than code-server, so in order to make it work remotely (e.g., from docker or ssh), one has to forward this port as well. See #2206. However, it is possible to use another previewer: just search for "pdf" in extensions. "Papyrus PDF Preview" and "Office Viewer" are working for me fine, except that some icons are not displayed. In this case, of course, forward and inverse search will not work. I wish the built-in previewer had worked in the same way.

**Comment by jsjoeio** [comment]
Hooray! Thank you for reporting @ykazakov 🎉

**Comment by sylvaticus** [comment]
Hello, it works on me too (code-server: v4.20.1, Code: 1.85.2) without any hack but the PDF view doesn't refresh, I need to close the PDF tab and reopen it (refresh all viewers also doesn't work)
