### ISSUE TITLE
UI scaling

### ISSUE THREAD

**Issue by djdisodo** [coder/code-server#2009]
there is users using this on mobile device
most of mobile browsers doesn't support scaling(in PC Ctrl+mWheel)

so it's nearly impossible to change ui size
(for firefox about:config -> layout.css.devPixelsPerPx; systemwide)

can we add some feature to scale ui size?

**Comment by nhooyr** [comment]
> most of mobile browsers doesn't support scaling

Which browsers? Any browser that doesn't has an accessibility issue.

iOS devices at least do support scaling.

**Comment by sr229** [comment]
UI scaling is more of a browser side  issue, you can just zoom out if needed since VS Code supports scaling by default.

**Comment by djdisodo** [comment]
@nhooyr 
i didn't know about ios
@sr229 
pinch to zoom works
but how can i do when i want to make it smaller

like the screenshot here
normal: https://ibb.co/dDdpHpc
smaller: https://ibb.co/3zXFgNw

the ui size option in vscode seems not working here

**Comment by sr229** [comment]
> @nhooyr
> i didn't know about ios
> @sr229
> pinch to zoom works
> but how can i do when i want to make it smaller
> 
> like the screenshot here
> normal: https://ibb.co/dDdpHpc
> smaller: https://ibb.co/3zXFgNw
> 
> the ui size option in vscode seems not working here

That's bound to a Electron API call IIRC, hence why it doesn't work.

**Comment by djdisodo** [comment]
though it is browser issue, i thnk it could be processed server side

**Comment by nhooyr** [comment]
Unfortunately I don't have an android device so I can't comment further.

cc @code-asher might know.

**Comment by djdisodo** [comment]
i'll test this (adding header) at home

https://stackoverflow.com/questions/9510359/set-size-of-html-page-and-browser-window

**Comment by djdisodo** [comment]
i'll test this (adding header) at home

https://stackoverflow.com/questions/9510359/set-size-of-html-page-and-browser-window

**Comment by djdisodo** [comment]
adding this to header will just gonna work
https://pastebin.com/fkaAPk4h

**Comment by code-asher** [comment]
On Firefox for Android at least there are options to scale according to the overall system but nothing to scale an individual website smaller.

As @sr229 mentioned the scaling in VS Code is Electron-based which is why it's missing but we could re-implement it with the CSS @djdisodo posted.

**Comment by bpmct** [comment]
I use code-server a lot, when I resize code-server with browser scaling, it will also resize other windows on the host. Being able to resize inside code-server would be huge

**Comment by jsjoeio** [comment]
I wonder if this is an issue upstream. We'll have to investigate but from a quick check, seems like it works as expected on [vscode.dev](https://vscode.dev/)

![2021-11-22 12 58 06](https://user-images.githubusercontent.com/3806031/142926779-d55236b4-a45c-4ad1-8f94-8092c5121cd2.gif)

**Comment by bpmct** [comment]
Being able to leverage code-server's "zoom in+out" feature instead of the browser would be awesome.

Since the browser zoom carries over across all paths on the domain, https://mydomain.com/about and https://mydomain.com/code-server would have the same scaling which is not ideal.

Currently, the only option specific to code-server is the font, which does not carry over to the terminal or sidebar.

**Comment by and-pete** [comment]
> Since the browser zoom carries over across all paths on the domain, https://mydomain.com/about and https://mydomain.com/code-server would have the same scaling which is not ideal.
> 

Does the browser zoom setting carry across sub-domains also? If not, I might take the interim step of reconfiguring my code-servers to be at https://code-server.mydomain.com/ instead of https://mydomain.com/code-server

**Comment by WaelShaikh** [comment]
+1

I am facing the same issue on my phone. Adding an option to change UI scaling, either via an option in the editor or by modifying a config file before launch would be useful.

**Comment by navanshu** [comment]
UI scaling without using the browser zoom is necessary, especially for people who work on small screens.

**Comment by Asher219** [comment]
> UI scaling without using the browser zoom is necessary, especially for people who work on small screens. 
> VScode stores it in user preferences under `"window.zoomLevel": 1`
>

**Comment by Asher219** [comment]
> UI scaling without using the browser zoom is necessary, especially for people who work on small screens. 
> VScode stores it in user preferences under `"window.zoomLevel": 1`
> 

>Please show me how to do that

**Comment by zeeyado** [comment]
`window.zoomLevel` seems disabled in code-server?

Are there any functioning workarounds for Android?

**Comment by code-asher** [comment]
I think this will need to be addressed upstream in VS Code core rather than patched here, which they hopefully will since mobile support seems to be one of the things they are working on.

**Comment by Asher219** [comment]
Well noted
Thanks for the heads up.
________________________________
