### ISSUE TITLE
Add option for disabling file downloads

### ISSUE THREAD

**Issue by code-asher** [coder/code-server#2426]
Being able to easily download might be an issue in some situations. See some comments on https://github.com/cdr/code-server/issues/1386.

Maybe it also makes sense to prevent the HTTP server from serving these files as well so you can't just `curl` them.

**Comment by JammSpread** [comment]
If I'm correct we just have to patch [this](https://github.com/microsoft/vscode/blob/master/src/vs/workbench/contrib/files/browser/fileActions.contribution.ts) with if statements on lines [228](https://github.com/microsoft/vscode/blob/master/src/vs/workbench/contrib/files/browser/fileActions.contribution.ts#L228) and [488](https://github.com/microsoft/vscode/blob/master/src/vs/workbench/contrib/files/browser/fileActions.contribution.ts#L488)?

**Comment by code-asher** [comment]
That looks right to me! We may also want to put an modify the HTTP
static endpoint that lets you access files outside the code-server
directory.

**Comment by bpmct** [comment]
I confirmed two sections mentioned above will disable the download option :) 

I was also able to modify the static endpoint, I believe we'll want to use something similar to [this check](https://github.com/cdr/code-server/blob/v3.8.0/src/node/routes/index.ts#L144-L148) to ensure the user can't `curl` or visit the page for these static files. For curl in particular, we can do 

```
if (req.headers["user-agent"] && req.headers["user-agent"].includes("curl")) {
    throw new HttpError("Unauthorized", HttpCode.Unauthorized)
}
```

but I assume there is probably a better way to whitelist requests from code-server? Any ideas what headers we should be looking for?

Also, I've added the flag `--disable-download` in the CLI but am unsure how to check for that in [fileActions.contribution.ts](https://github.com/microsoft/vscode/blob/master/src/vs/workbench/contrib/files/browser/fileActions.contribution.ts).

**Comment by lsc196** [comment]
How to ban downloading files now？

**Comment by JammSpread** [comment]
> but am unsure how to check for that in fileActions.contribution.ts.

Instead of a flag we could easily use an environment variable, however I think it would be nice to be able to have a cli flag. Or maybe even both.

**Comment by JammSpread** [comment]
> Also, I've added the flag --disable-download in the CLI but am unsure how to check for that in fileActions.contribution.ts.

You could easily use a environment variable instead of a CLI flag. However a CLI flag would be nice as well. 😄

**Comment by JammSpread** [comment]
> Also, I've added the flag `--disable-download` in the CLI but am unsure how to check for that in [fileActions.contribution.ts](https://github.com/microsoft/vscode/blob/master/src/vs/workbench/contrib/files/browser/fileActions.contribution.ts).

I think you might be able to check for `--disable-download` by passing the flag as an environment variable.

**Comment by bpmct** [comment]
Yeah, I'd love to do it as both (code-server handles most options like this), but I haven't been able to find an example of it implemented somewhere like `fileActions`

**Comment by code-asher** [comment]
We'll need to add the option to the the Args interface in ipc.d.ts.
That'll let us use `options.args["disable-download"]` in
`lib/vscode/src/vs/server/node/server.ts`.

In that file we can add the disable download option to the workbench web
configuration (including to the interface) so it gets to the browser in
the same way as the home indicator option.

From there I think it'd make the most sense to use a context key to
enable/disable the download options.

We can add and export a context key in
`lib/vscode/src/vs/workbench/browser/contextkeys.ts`. We should be able
access the value of the flag we passed via the workbench web
configuration with `environmentService.options["disable-download"]`.

**Comment by metalshanked** [comment]
Will there be an option to disable file uploads as well ?  Example:- To disable people uploading their own .vsix file and installing them manually.

**Comment by jsjoeio** [comment]
I think we could definitely consider it! 

If it's a global thing, like download scenario, then it might be possible to implement here as well.

> To disable people uploading their own .vsix file and installing them manually.

For that specific use case, we could potentially add that.

It might help if you could expand on your use case (then we can see if it fits in this issue or should be a separate issue).

**Comment by metalshanked** [comment]
> I think we could definitely consider it!
> 
> If it's a global thing, like download scenario, then it might be possible to implement here as well.
> 
> > To disable people uploading their own .vsix file and installing them manually.
> 
> For that specific use case, we could potentially add that.
> 
> It might help if you could expand on your use case (then we can see if it fits in this issue or should be a separate issue).

Thanks @jsjoeio.  Yes, a global disable upload option would be awesome. The use case is similar to the original requester's disable download request. For security related use cases, where we want to disable certain users from uploading files to the code-server (running on Docker)

**Comment by jsjoeio** [comment]
Ahh okay. Thank you for elaborating! Sounds very similar in which case we can keep here in this issue :)

**Comment by jsjoeio** [comment]
Thanks to @iamdineshkumar for linking this:

https://github.com/microsoft/vscode/blob/6fa3243d3facbbf8b87222bcf4e81c5eddf5d47f/src/vs/workbench/contrib/files/browser/fileActions.contribution.ts#L472

**Comment by jsjoeio** [comment]
Seems like all we need to do is:
1. create new context key like: `ContextKeyExpr.and(IsWebContext, HasDownloadFileEnabled)`
2. write expression that returns true by default, or false if CLI flag `--disable-file-downloads` or something

Might be worth looking into writing e2e tests.

Without CLI flag, should show Download File in menu.
WIth CLI flag, should not show Download File in menu.
