### ISSUE TITLE
Using --link enables local privilege escalation

### ISSUE THREAD

**Issue by oxy** [coder/code-server#2484]
`code-server --link` by default binds to a random high port on localhost - suppose you run code-server in `user1`, any other user on the same server could simply scan for open ports on localhost, attempt to connect to code server and then obtain privileges of `user1` - read files, execute code, etc.

This could pose an unintended security risk on a multi-tenant system - any process that can access `localhost` can obtain the privileges of the user account that is running `code-server`, which may include sudo (or even passwordless sudo) depending on the user's configuration.

**Comment by code-asher** [comment]
Closing since `--link` was shut down.
