### ISSUE TITLE
vscode extension development debug can't hit breakpoint

### ISSUE THREAD

**Issue by chouzz** [coder/code-server#2546]
Hello！code-server is really cool!

But I find that code-server seems can't debug vscode extension. 

I install code-server with docker. And I use [hello-wrold sample](https://github.com/microsoft/vscode-extension-samples/tree/master/helloworld-sample) from github. It seems code-server can open an extension development host, but can not hit breakpiont. 

So can code-server really debug vscode extension? Or I miss something?

- Web Browser:
- Local OS: win10
- Remote OS: code-server-docker
- Remote Architecture: x64
- `code-server --version`: v3.7.4

**Comment by code-asher** [comment]
code-server doesn't support debugging extensions yet but it's something
I'd like to add.

**Comment by UmarSpa** [comment]
looking forward to this extension

**Comment by benz0li** [comment]
@chouzz Please retest. Using code-server 4.0.1 I could work through the whole [Hello World guide](https://code.visualstudio.com/api/get-started/your-first-extension) without problems.

See also https://github.com/coder/code-server/issues/3661#issuecomment-1007236101.

**Comment by chouzz** [comment]
It works for me now! Thanks!

**Comment by benz0li** [comment]
@chouzz I have closed https://github.com/coder/code-server/issues/3661. You may close this issue, too.

**Comment by jsjoeio** [comment]
Hooray!!! Thank you @chouzz and @benz0li for confirming
