### ISSUE TITLE
Provide Mirror

### ISSUE THREAD

**Issue by kaaax0815** [coder/code-server#2582]
Github Download is extremely slow, I tried to download the Release and i get like 5kbits.
Upload the Files somewhere else too, so I dont have to wait like an hour for 90mb

**Comment by kaaax0815** [comment]
Through googling i found a Chinese website, that can provide a url, that you can download releases fast

**Comment by nhooyr** [comment]
Yea GitHub can be slow sometimes. Perhaps a google cloud storage bucket is a good idea as well.

**Comment by kaaax0815** [comment]
Still relevant

**Comment by jeremyj563** [comment]
My employer blocks headless downloads from `raw.githubusercontent.com` so a mirror would be much appreciated!
