### ISSUE TITLE
Proxy over WebRTC

### ISSUE THREAD

**Issue by huynhtrankhanh** [coder/code-server#2605]
I notice that the proxy feature proxies the connection through an intermediary server so latency is not the best. Using WebRTC would be better because WebRTC attempts to make a P2P connection between the client and the server whenever possible. AFAICT Chrome Remote Desktop uses WebRTC and it is decently smooth.

**Comment by oxy** [comment]
I'm not sure if WebRTC is a good fit for what we do at all - We don't actually use a "remote desktop" style setup for code-server; all rendering is done _in_ the browser, and then editor/terminal commands are just sent over the wire, which is why typing in, say, the editor window should not have much latency.

Using something P2P may also defeat the point of a proxy in the first place in case you can't make a direct connection to the server.

**Comment by huynhtrankhanh** [comment]
WebRTC can transmit arbitrary data. [Visual Studio Live Share](https://code.visualstudio.com/blogs/2017/11/15/live-share) also uses WebRTC.
> may also defeat the point of a proxy in the first place in case you can't make a direct connection to the server

WebRTC can circumvent NAT. Most devices are behind NAT and that makes direct connections difficult but not impossible. You can't connect to an arbitrary TCP port but if you use WebRTC both computers will attempt to do some "UDP hole punching" magic and establish a direct connection.

**Comment by huynhtrankhanh** [comment]
As for the latency part, code-server is _orders of magnitude_ less responsive than both Chrome Remote Desktop and Live Share.

**Comment by nhooyr** [comment]
We debated this intensely internally! We actually implemented WebRTC at one point but the problem ended up being that only the persistent connection can go through WebRTC. All of code-server's HTTP requests would still need a proxy.

So we ended up distributing the coder cloud proxy instead and concluded the WebRTC complexity was probably not worth it. I'm surprised you find the code-server latency so bad. Most user actions should occur client side. What's the ping to your server? And how long does `time curl -fsSL <coder-cloud-url>/healthz` take?

cc @sreya @code-asher

**Comment by nhooyr** [comment]
We also considered implementing a chromium extension or some CLI to allow passing all requests through WebRTC but with the global distribution of coder cloud, it didn't seem worth it but happy to reconsider based on your situation.

**Comment by kaaax0815** [comment]
As for Latency, its wrong, that code-server Code Editor has Latency, I have a normal PC, I have bad Internet and a bad Server, but I didn't find any lag so far. The SSH Terminal is way worse.

**Comment by huynhtrankhanh** [comment]
```
$ time curl -fsSl [redacted]/healthz
________________________________________________________
Executed in    2,01 secs   fish           external 
   usr time   65,25 millis    0,00 micros   65,25 millis 
   sys time   17,17 millis  859,00 micros   16,31 millis 
```

```
$ ping [redacted]
64 bytes from [redacted] ([redacted]): icmp_seq=1 ttl=57 time=23.4 ms
64 bytes from [redacted] ([redacted]): icmp_seq=2 ttl=57 time=23.8 ms
64 bytes from [redacted] ([redacted]): icmp_seq=3 ttl=57 time=23.3 ms
64 bytes from [redacted] ([redacted]): icmp_seq=4 ttl=57 time=22.7 ms
64 bytes from [redacted] ([redacted]): icmp_seq=5 ttl=57 time=22.0 ms
64 bytes from [redacted] ([redacted]): icmp_seq=6 ttl=57 time=25.5 ms
64 bytes from [redacted] ([redacted]): icmp_seq=7 ttl=57 time=22.2 ms
```
