### ISSUE TITLE
code-server --install-extension ms-python.python@<version> always installs the latest version

### ISSUE THREAD

**Issue by ddurham2** [coder/code-server#2626]
- Web Browser: None
- Local OS: n/a
- Remote OS: within docker container
- Remote Architecture:  (from docker) Linux 1b4f61ce602c 5.4.0-60-generic #67-Ubuntu SMP Tue Jan 5 18:31:36 UTC 2021 x86_64 GNU/Linux
- `code-server --version`: "3.8.0 c4610f7829701aadb045d450013b84491c30580d"  and "3.7.2 a0db6723c1ef22b40d7ac0df5ac1bb9a92e4fe46"

This is not a problem with 3.7.1

When running ...
> $ code-server --install-extension ms-python.python@**2020.5.86806**
> Installing extensions...
> Installing extension 'ms-python.python' **v2021.1.502429796**...
> Extension 'ms-python.python' v2021.1.502429796 was successfully installed.

Notice that it installed a version different than what was requested.  It seems to always install the latest, no matter what valid version I request.

Also, this happens... (just putting a different valid version now)
> coder@1b4f61ce602c:~$ code-server --install-extension ms-python.python@**2020.12.424452561**
> Installing extensions...
> Extension 'ms-python.python@**2020.12.424452561**' is already installed.

... which it isn't.  See...

> coder@1b4f61ce602c:~$ code-server --list-extensions --show-versions
> ms-python.python@2021.1.502429796
> ms-toolsai.jupyter@2020.12.1

Please let me know if this is an upstream problem I need to file, and where.

Thanks!

**Comment by jsjoeio** [comment]
Sorry for the late reply @ddurham2 - thanks for the detailed issue! I've added this to our Triage bucket and hope we can investigate soon!

**Comment by tseader** [comment]
Observations as relating to the version pinning:

I ran into the same issue as I was attempting to pin the `ms-python.python` extension version to the known-working version indicated in #2341 as [this post](https://github.com/cdr/code-server/issues/2626?_pjax=%23js-repo-pjax-container#issue-792715862) does .  

However, after poking around a bit, I observed that version-pinning works if and only if that version is available at the target repository. 

## Here's the pertinent snippet in my Dockerfile I am executing that works:
```docker
RUN code-server --version && \
    code-server --install-extension ms-python.python@2021.2.625869727 && \
    code-server --list-extensions --show-versions
```

Resulting output: 
![image](https://user-images.githubusercontent.com/19822395/110366532-03fff100-800c-11eb-8143-054b086d6f1e.png)


I also found at the time of this writing that at [VS-Code's marketplace](https://marketplace.visualstudio.com/items?itemName=ms-python.python), and [Open-VSX marketplace](https://open-vsx.org/extension/ms-python/python), the version I wish I could pin to get around the broken Python extension #2341 doesn't show up on a drop-down list...

### VS-Code Marketplace
![image](https://user-images.githubusercontent.com/19822395/110367242-0a429d00-800d-11eb-85aa-8bcb194d02c6.png)


### Open-VSX Marketplace
![image](https://user-images.githubusercontent.com/19822395/110367200-fd25ae00-800c-11eb-8279-60565de371cf.png)


I'm not sure where the code-server GUI looks to pull versioning, but didn't seem available via web-browser interface.

**Comment by ddurham2** [comment]
@jsjoeio Thanks for the info. I do hope this gets fixed soon as my other work arounds are starting to fail.  

As for installing the vsxi manually, is there a way to do that from the cli?  (I'm in a Dockerfile here)  I tried giving code-server --install-extension /path/to/file.vsxi but it saying it can't find the extension.  The usage statement says I should be able to give it a vsxi file.  

I'm wondering if installing via vsxi file path broke for the same reason that the '@version' syntax broke (my original problem)?

Also, if I were to give it a vsxi file (like ms-python) which requires a dependency (like how ms-python also now depends on jupiter), should installing the vsxi from the cli automatically install dependencies?

**Comment by tseader** [comment]
@ddurham2  - This is what I'm doing to install via `vsix` file, hope it helps!

```yaml
RUN curl -# -L -o /tmp/ms-python-release.vsix "https://github.com/microsoft/vscode-python/releases/download/2020.5.86806/ms-python-release.vsix" && \
    code-server --version && \ 
    # Below line doesn't work due to a bug that always installs latest version... working around this with vsix file install
    #code-server --install-extension ms-python.python@2020.5.86806 && \
    code-server --install-extension /tmp/ms-python-release.vsix && \
    code-server --list-extensions --show-versions

COPY user_settings.yaml /home/coder/.local/share/code-server/User/settings.json
```

**Comment by mateuszkitlas** [comment]
I tried to workaround this with installing a manually downloaded version of this extension (or any other - this issue seems to affect all extensions) from this address: 
```
url = f'https://extensions.coder.com/api/publishers/{ext.publisher}/vsextensions/{ext.name}/{ext.version}/vspackage'
```
but sadly, I get the newest version as well. This is kinda important for me to be able to download the right extensions version. Are there any updates on this issue?

**Comment by jsjoeio** [comment]
@mateuszkitlas have you tried manually installing it from Open VSX? See [docs](https://github.com/cdr/code-server/blob/main/docs/FAQ.md#installing-an-extension-manually).
