### ISSUE TITLE
Unable to connect with --link

### ISSUE THREAD

**Issue by SamHep0803** [coder/code-server#2734]
- Web Browser: Safari
- Local OS: iPadOS 14.3
- Remote OS: Ubuntu 20.04
- Remote Architecture: x86_64
- `code-server --version`: 3.9.0 fc6d123da59a4e5a675ac8e080f66e032ba01a1b

When running `code-server --link`, the process starts successfully however when you go to the link given in the server output, the error `Error connecting to your code-server instance` shows up when you go to the site.

Initially, no error gets thrown in the terminal however after around 1 hour, 
`[2021-02-16T09:59:22.641Z] info 2021/02/16 09:59:22 [ERR] yamux: Failed to read header: failed to get reader: failed to read frame header: EOF`
`[2021-02-16T09:59:22.645Z] info 2021-02-16 09:59:22.644 [WARN] <proxy.go:48> code-server proxy exited {"error": "accept tcp [::]:36221: use of closed network connection"}
`
is logged.

Thanks, Sam.

**Comment by SamHep0803** [comment]
Downgrading the version 3.8.0 did not help resolve the issue, I have a feeling this may be an issue on cdr's end. I have tried getting this to work in both GCP and DigitalOcean to no avail.

**Comment by oxy** [comment]
Tried to repro this but could not - do you have any additional steps that could help in reproducing it?

**Comment by SamHep0803** [comment]
Honestly not really, it's a very strange issue. 

I installed `code-server` with the install script, as is the recommended way in the docs and that was basically it. I have to mention that it was working 2 days ago but now it's not.

**Comment by SamHep0803** [comment]
I have tried deleting the `~/.config/coder-cloud` folder and restarting the server and that hasn't worked either.

**Comment by SamHep0803** [comment]
Update: after turning on my VPN, I seem to be able to connect to the server now, however I don't see why I would need to do that.

**Comment by code-asher** [comment]
Did it give you an error ID? We can use that to investigate further.

**Comment by parslov** [comment]
I have the same problem

- brand new AWS instance
- AWS free tier 
- Ubuntu 20.04
- Installed with code-server with this (from https://github.com/cdr/code-server): curl -fsSL https://code-server.dev/install.sh | sh
- Opened HTTP, HTTPS, Custom TCP (pot 8080), and SSH in inbound rules
- Started code-server with: code-server --link
- ...and then opened Safari on my mac and entered the https-address shown 
- ...and then get: 'Error connecting to your code-server instance'

Any ideas?

**Comment by SamHep0803** [comment]
A temporary fix is to use a VPN and set the region to the region of where
your server is currently located, however that's just my advice and you
should wait for what the devs have to say.

**Comment by code-asher** [comment]
@parslov Did it give you an error ID? Does it persist if you visit the the https address a second time?

**Comment by parslov** [comment]
I did not get an error id. Today I went through the same process on Google Cloud, using Ubuntu 16 and opening for HTTP and HTTPS. Same result.

**Comment by code-asher** [comment]
OK, thanks! I'll see what we can turn up.

**Comment by SamHep0803** [comment]
Note, I have never gotten an ID from when this error has popped up.

**Comment by code-asher** [comment]
Makes sense, turns out I was wrong about the error ID. We don't log connection errors since they don't provide any information (just things like `connection reset by peer`).

**Comment by SamHep0803** [comment]
Has there been any update on this situation?

**Comment by SamHep0803** [comment]
Just wondering if theres been any further development on this issue?

**Comment by code-asher** [comment]
We haven't since the connection errors don't provide any extra details on our end. I think what we'll have to do is try to replicate it ourselves and go from there.

**Comment by jsjoeio** [comment]
@SamHep0803 I can take a look at this seeing that it's iPad. 

Do you mind providing reproduction steps? I have my own setup on iPad but ideally I try to mimic yours as closely as possible.

**Comment by SamHep0803** [comment]
Well, it's not an iPad issue specifically, i've had the same issue on different machines. I've tried it on a PC, mac and my iPad. The only steps that I took was to startup code server with the --link flag, nothing else, no config or anything.

**Comment by jsjoeio** [comment]
Oh, I see. Hmm.. That's so strange then. I just used `--link` the other day with no issues (on mac).

The only way we'll be able to help with this is if we can successfully reproduce it ourselves. Any tips/suggestions you have there would be helpful!

**Comment by SamHep0803** [comment]
It seemed to stop working after I got my first "Reconnecting..." pop up after I didn't close my tab before going to sleep, after that i refreshed the page and I got that error, I managed to get around it for a while by using a vpn until I did the same thing and it stopped working again, turned off my vpn, started working, but I don't think that's a good solution and it's not really "fixed"

**Comment by jsjoeio** [comment]
Yeah, I agree with you, I wouldn't consider that fixed.

Well like I said, if you can provide reproduction steps, then I'd be happy to look into fixing this! Otherwise, we don't have a good strategy for diagnosing and fixing this 😢

**Comment by SamHep0803** [comment]
The only reproduction steps I can give is starting code-server with the --link flag, that's all, no other changes were made. It's not specific to host machine, I've tried it on both GCP and DigitalOcean, not guest specific, tried on different platforms and OS's. I have a feeling it's an issue with cdr's servers and not with code-server

**Comment by code-asher** [comment]
We could spin it up on GCP and see what happens. If a VPN fixes it maybe it's related to location somehow.

**Comment by jsjoeio** [comment]
> I have a feeling it's an issue with cdr's servers and not with code-server

Ah got it. Yeah, I agree with Asher. We'll make a note to try on GCP then.

@SamHep0803 if you're comfortable sharing, what location are you trying this from (city/state/country)? And when using a VPN, what location were you using? That may help.

**Comment by SamHep0803** [comment]
UAE, VPN server was set to London, UK

**Comment by parslov** [comment]
Any update on this?

**Comment by jsjoeio** [comment]
Nothing so far @parslov - are you able to share any logs or anything you're seeing? We'll add this to an upcoming milestone and investigate.

**Comment by jsjoeio** [comment]
Hi all.

I finally found some time to investigate this. I was able to semi-reproduce this.

## Reproduction Steps
1. Download VPN for macOS: [TunnelBear](https://www.tunnelbear.com/)
2. Run `code-server --link`
3. Enable VPN using Cyprus (the country)
4. Open code-server using link (i.e. https://<you-link>.cdr.co/) in browser

### Expected

It loads code-server in the browser

### Actual

It doesn't or it shows this screen:

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/3806031/113611255-2123e180-9603-11eb-848f-7b6165ebd646.png">

### Screenshots

https://user-images.githubusercontent.com/3806031/113611312-300a9400-9603-11eb-9403-cac0a2f71242.mov

### Logs
```shell
➜  ~ code-server --link
[2021-04-05T18:30:32.198Z] info  code-server 3.9.2 109d2ce3247869eaeab67aa7e5423503ec9eb859
[2021-04-05T18:30:32.198Z] info  Using user-data-dir ~/.local/share/code-server
[2021-04-05T18:30:32.209Z] info  Using config file ~/.config/code-server/config.yaml
[2021-04-05T18:30:32.209Z] info  HTTP server listening on http://127.0.0.1:54718 (randomized by --link)
[2021-04-05T18:30:32.209Z] info    - Authentication is disabled (disabled by --link)
[2021-04-05T18:30:32.209Z] info    - Not serving HTTPS (disabled by --link)
[2021-04-05T18:30:32.654Z] info  Proxying code-server to Coder Cloud, you can access your IDE at https://joes_mbp-jsjoeio.cdr.co
[2021-04-05T18:31:04.179Z] info  2021/04/05 11:31:04 [ERR] yamux: Failed to read header: failed to get reader: failed to read frame header: read tcp 192.168.86.108:54723->104.26.1.18:443: read: no route to host
[2021-04-05T18:31:04.180Z] info  Connection to Coder-Cloud disrupted, re-establishing connection: proxy code-server: accept stream: failed to get reader: failed to read frame header: read tcp 192.168.86.108:54723->104.26.1.18:443: read: no route to host
[2021-04-05T18:31:04.180Z] info  2021-04-05 18:31:04.179 [WARN]	<proxy.go:48>	code-server proxy exited	{"error": "accept tcp [::]:54722: use of closed network connection"}
```

## Workaround

> ...use a VPN and set the region to the region of where your server is currently located
Per @SamHep0803's comment, this works for me as well. 

## Next Steps

I'll follow up with the developer who created this and see if they know how to fix this.

**Comment by jsjoeio** [comment]
Spoke to the developer working on this before. We're going to aim to get this fixed before May 1st. 

Until then the workaround is to use a VPN and set the region of where your server is located.

**Comment by SamHep0803** [comment]
Hi, has there been any update on this issue?

**Comment by parslov** [comment]
I managed to finally get it working by running a server on Oracle Cloud in Germany using the —link option. I am accessing the server from Denmark. Not sure if Germany and Denmark are in the same ‘region’. I did not have to use VPN but of course set up the server side to accept traffic on the relevant ports.

**Comment by jsjoeio** [comment]
Hi @SamHep0803! So I spoke to the developer working on this. He had another priority come up and wasn't able to finish it last week. It's in progress but I don't have an ETA on when it will be done. Feel free to ping this issue again in two weeks!

**Comment by Jack-Sibley** [comment]
Looks like this is still happening. Any updates?

**Comment by jsjoeio** [comment]
Unfortunately, no updates. I reached out to the developer but haven't heard back yet.

**Comment by SamHep0803** [comment]
Been more then a month now, still no update?

**Comment by jsjoeio** [comment]
Apologies. We're a small team (code-server). I'll ping them again and see if I can get any update.

Worst case: they come back and say we won't be able to fix it.

Best case: they say they can and I can share more information.

Other scenario: if I could collect data and say, "this is affecting X number of users in the code-server community and we should prioritize" then that might help. 

Give this message a 👍 if you're experiencing this issue still.

**Comment by jsjoeio** [comment]
Okay I got a response. 

I spoke to the developer. We're working on some networking changes in the enterprise product going from WebSockets to WebRTC. Eventually those changes will make their way into coder-cloud (powers `--link` + code-server) in which case, will solve this issue. I don't have an ETA but will share updates on this thread as I have them

**Comment by SamHep0803** [comment]
That's great news! Good to finally see some progress on this issue.

Thanks a lot for your efforts and hopefully we can have this issue resolved
in the near future.

**Comment by jsjoeio** [comment]
I hope so too and thank you for understanding.

**Comment by Arbsahoy** [comment]
This is nice there is a good chain here. Learning how to github / programming because of you guys... so thanks for having a great product and am looking forward to the correction. 

It appears for me that it times out, if I haven't done anything in the system I feel like cdr.co just terminates the connection. (It's free so, hey... i get it.) But these are the similar errors I am getting. 

As the project develops more will --link be intergrated? I'd be willing to pay some monies to get it running. I love being able to go to a webpage and keep coding.

**Comment by jsjoeio** [comment]
> It appears for me that it times out, if I haven't done anything in the system I feel like cdr.co just terminates the connection. (It's free so, hey... i get it.) But these are the similar errors I am getting.

Hmm...that's unusual. Do you mind telling us a bit about your setup?
- where are you accessing your code-server instance from? (OS, architecture, etc.)
- are you using a VPN?
- screenshots or videos 

> As the project develops more will --link be intergrated? I'd be willing to pay some monies to get it running. I love being able to go to a webpage and keep coding.

Hopefully, but don't want to make any promises. We are having internal discussions about improving and better integrating and promoting --link.

> I'd be willing to pay some monies to get it running. I love being able to go to a webpage and keep coding.

If you ever want to chat more about that, feel free to shoot me an email joe@coder.com — we do have some things in the pipeline so otherwise you'll have to keep an eye out!

**Comment by facundomedica** [comment]
Went from Italy to Portugal, it worked in Italy but now it doesn't work here in Lisbon. I'm running it off the Frankfurt region in GCP. Restarting or rebooting don't solve the issue.

**Comment by code-asher** [comment]
It looks like the link project has been shelved, possibly indefinitely.  I am not sure how far the rewrite got but it seems not far enough before the plug was pulled.

I think the only thing we can recommend now is to set up a domain and a reverse proxy, possibly Caddy since it handles certificates for you.
