### ISSUE TITLE
[dev]: research automating the release process

### ISSUE THREAD

**Issue by jsjoeio** [coder/code-server#2817]
## Problem

Right now, the release process is rather tedious and manual. See steps [here](https://github.com/cdr/code-server/tree/main/ci#publishing-a-release).

We would like to solve this and make it easier and faster for maintainers to release code-server.

## Solutions

- "prep release" script -> makes changes before release is ready
- [`release-it`](https://github.com/release-it/release-it) (H/T to @vapurrmaid for the suggestion!)
- [`semantic-release`](https://github.com/semantic-release/semantic-release)

**Comment by vapurrmaid** [comment]
Happy to help somewhere along the lines if needed!

**Comment by jsjoeio** [comment]
Maybe we can combine it with changelogs following [these guidelines](https://keepachangelog.com/en/1.0.0/)

**Comment by jsjoeio** [comment]
## Raw Notes

@code-asher and I were talking about some ideas for improving this. 

1. open PR to update `CHANGELOG` and run pre-release script to update versions in text and stuff
2. after that's merged, create GitHub release. on [`created`](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release)

Hmm.. not sure if this could work: 

> Note: Workflows are not triggered for the created, edited, or deleted activity types for draft releases. When you create your release through the GitHub browser UI, your release may automatically be saved as a draft.

**Comment by jsjoeio** [comment]
A couple things to look at: 
- https://github.com/thomaseizinger/github-action-gitflow-release-workflow/blob/dev/.github/workflows/draft-new-release.yml
- https://trstringer.com/github-actions-create-release-upload-artifacts/
- https://github.com/marketplace/actions/release-drafter

**Comment by jsjoeio** [comment]
Latest discussion:

1. update changelog if we have been forgetting to do it as we go
2. tag a commit
3. release is made and uploaded to a draft pr
4. publish the release after testing it
5. automatic prs are sent to aur, brew, and code-server
6. we approve and merge the aur and code-server prs

**Comment by code-asher** [comment]
Still could use work, but I think at the moment the status quo is reasonable enough with the roughly monthly releases.

**Comment by jsjoeio** [comment]
agreed!
