### ISSUE TITLE
add additional release image that uses ubuntu instead of debian

### ISSUE THREAD

**Issue by aflextr** [coder/code-server#2849]
hi, I noticed that some plugins are not working with Debian and some are running poorly, but it works fine on ubuntu 18.04 machines. Can you change the Docker image with ubuntu?

**Comment by jsjoeio** [comment]
Thanks for opening the issue @aflextr! Assuming we're talking about the release image [here](https://github.com/cdr/code-server/blob/main/ci/release-image/Dockerfile#L1)

Hmm...sorry to hear there are issues with plugins(by this, do you mean VS Code extensions?). 

I'll defer to @code-asher on this one.

**Comment by aflextr** [comment]
@jsjoeio Oh yes, there was also a docker hub image. I have observed that some of the vscode plugins do not work and some are very slow and some do not work at all.

**Comment by jsjoeio** [comment]
Got it! Two things that would help us:
- providing reproduction steps (so we can feel the pain you're feeling and investigate)
- can you try seeing if these errors happen with no extensions?

**Comment by aflextr** [comment]
JAVA Extensions:

UBUNTU :
![error1](https://user-images.githubusercontent.com/53778891/110518099-bfb04600-811c-11eb-8f67-7085e70ecb83.png)

DEBİAN :

![error2](https://user-images.githubusercontent.com/53778891/110519892-e66f7c00-811e-11eb-9a51-f855cb8004a3.png)

Debian with python : 

![python](https://user-images.githubusercontent.com/53778891/110519951-f4250180-811e-11eb-9aa3-a1b4ff5f27ea.png)


Java always stays like this and after a while an error message comes from the notification menu.

**Comment by aflextr** [comment]
@jsjoeio  First of all, I installed a code-server on both machines. one is a docker-based debian, and the other is an ubuntu running on docker. While installing docker with Debian, I installed scripts in ubuntu. I followed the same paths on both operating systems when installing the plug-in: 
 and the plug-ins were installed on both machines without any problems. and a java file should be created and a setup screen should appear. In this process, I downloaded the file and typed its location with the required parameters. The commands I process are: "wget ​​(java link),
tar -xvzf (java link)
"
and after completing these processes, I refreshed the page. I opened the java file and plugins like autocomplete started working on my ubuntu machine! but even if I do the same on debian, java doesn't work.

![Screenshot_1](https://user-images.githubusercontent.com/53778891/110525667-eb83f980-8125-11eb-8708-6756927f6492.png)
![Screenshot_2](https://user-images.githubusercontent.com/53778891/110525674-ecb52680-8125-11eb-86b0-7ae6f1eca11f.png)
![Screenshot_3](https://user-images.githubusercontent.com/53778891/110525675-ed4dbd00-8125-11eb-8f0a-b1d514b372d1.png)
![Screenshot_4](https://user-images.githubusercontent.com/53778891/110525676-ede65380-8125-11eb-8aeb-daf784d12c4a.png)
![Screenshot_5](https://user-images.githubusercontent.com/53778891/110525678-ee7eea00-8125-11eb-9057-c56a88b1be14.png)
![Screenshot_6](https://user-images.githubusercontent.com/53778891/110525682-ee7eea00-8125-11eb-9c7c-debb45629546.png)

**Comment by jsjoeio** [comment]
Awesome! That's super helpful. We'll see what we can do about this.

**Comment by bpmct** [comment]
It's worth knowing that this image is used quite heavily (we have about 50M docker pulls). We should consider perhaps adding a separate image ([or separate tag, like we do for Coder](https://hub.docker.com/r/codercom/enterprise-base/tags?page=1&ordering=last_updated)) for the Ubuntu image.

This adds additional overhead, but may avoid breaking CIs and apps that may deploy code-server with the :latest tag.

**Comment by jsjoeio** [comment]
> We should consider perhaps adding a separate image

Good call @bpmct - i'll update the title to reflect that.

**Comment by jawnsy** [comment]
As a general approach, I think we should be using separate images (not separate tags) because there's only one special `latest` tag, and the different image variants aren't that similar (e.g. an image built `FROM debian` doesn't have that much in common with one built `FROM ubuntu`)

Something to note as well is that Debian is in the [final stages of their release process for Debian 11 (`bullseye`)](https://release.debian.org/bullseye/freeze_policy.html), and hence there will be an updated version available in the near future. We could test this and build an image based on the `testing` tag.

**Comment by jawnsy** [comment]
Reopening since I think this is still applicable
