### ISSUE TITLE
Incorrect TS Typings In Service Worker

### ISSUE THREAD

**Issue by vapurrmaid** [coder/code-server#2858]
## Context

At the time of this writing, our service worker is very simple:

```ts
/* eslint-disable @typescript-eslint/no-explicit-any */

self.addEventListener("install", () => {
  console.log("[Service Worker] installed")
})

self.addEventListener("activate", (event: any) => {
  event.waitUntil((self as any).clients.claim())
  console.log("[Service Worker] activated")
})

self.addEventListener("fetch", () => {
  // Without this event handler we won't be recognized as a PWA.
})
```

However, with #2760 and any future/related efforts, the service worker will be growing in complexity and scope, as offline cached responses will be added. 

## Problem

Our service worker uses the same `tsconfig` as the rest of the project, and uses the `any` typing. What this amounts to are the following:

- Perceived access to APIs that do not exist in the context of a service worker (`lib.d.ts`)
- Lack of type safety on service worker, web worker global scope

## Ideal Solution

Use a root, extendable `tsconfig` and separate `tsconfig` for the separate areas of the application - service worker, browser and node

## Quick Solution

- Use triple slash directives to remove `lib.d.ts` and add in the missing references

## See Also

- https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html
- https://github.com/microsoft/TypeScript/blob/master/lib/lib.webworker.d.ts

**Comment by vapurrmaid** [comment]
@jsjoeio - I'll promise this one for the first milestone in June (see #2760 )

**Comment by jsjoeio** [comment]
Moving to v3.9.5 since we're planning to cut v3.9.4 sooner than June.
