### ISSUE TITLE
Remove tests and test data from release package

### ISSUE THREAD

**Issue by jawnsy** [coder/code-server#3092]
The release package includes various text fixtures, including things like TLS private keys, which some container scanning tools (erroneously) flag as problematic. While this is a limitation of the various container scanning tools, it would be easier for us to avoid the problem entirely, while also allowing us to reduce the size of the release archive, by removing tests from our release package.

For example, our release has various .pem and .key files:

![image](https://user-images.githubusercontent.com/52710/114279760-17c3bc00-99eb-11eb-8f74-950143cdf7ec.png)

Is there some straightforward way to avoid installing tests along with our various dependencies in the release package?

**Comment by code-asher** [comment]
I think the only ways are:
1. Submit PRs upstream to exclude test directories
2. Remove them in a postinstall script
