### ISSUE TITLE
Issue when Deleting / Uploading Large Files (<50MB)

### ISSUE THREAD

**Issue by metalshanked** [coder/code-server#3097]
## OS/Web Information

- Web Browser: Chrome [Version 89.0.4389.82 (Official Build) (x86_64)]
- Local OS: Debian (Code Server Docker)
- Remote OS: MacOS (Big Sur)
- Remote Architecture: Darwin x64
- `code-server --version`: 3.9.3 and 3.9.1

## Steps to Reproduce

1. Select a Large File (Tried with a 44.8MB file)
2. Right Click and Click "Delete Permanently"
3. Code Server starts Deleting but the process never finishes and file does not get deleted

## Expected

Selected Files should get deleted

## Actual

Code Server starts Deleting but the process never finishes and no files get deleted
Smaller files seem to work fine.
Same issue happens for Upload of these large files.

## Screenshot

![image](https://user-images.githubusercontent.com/57646596/114313802-e1e70c00-9aac-11eb-998d-a18582d518d7.png)

![image](https://user-images.githubusercontent.com/57646596/114313548-c7606300-9aab-11eb-861b-dadd7cc5d764.png)

![image](https://user-images.githubusercontent.com/57646596/114337692-6e71e880-9b06-11eb-9b4e-f77749d7fe67.png)

## Notes

This issue can be reproduced in VS Code: Yes/No - No

**Comment by jsjoeio** [comment]
I feel like we've had issues with this before.

Running code-server locally on my macOS and accessing in Chrome, **I was not able to reproduce**.

## Steps followed

1. `brew install code-server` (3.9.3)
2. create a large file: `mkfile -n 50m temp_50mb_file`
3. Delete permanently from code-server

## Screenshot

https://user-images.githubusercontent.com/3806031/114440132-a0269600-9b7e-11eb-9a8d-593b873744c9.mov

## Next steps

- [ ] Try reproducing using code-server in remote Linux environment


_Adding this to On Deck which means we'll take a look in an upcoming milestone/sprint_

**Comment by metalshanked** [comment]
Thanks, it seems to be very strange and i am not able to figure out if the issue is with my setup or code-server.
1. I noticed that large files such as ".csv" text files do get uploaded without issue
2. The setup is MacOS Chrome Browser --> F5 LoadBalancer --> Nginx Ingress (K8s)--> Pod having Docker Container running code-server
Whenever the issue happens i see the below in the Ingress logs
recv() failed (104: Connection reset by peer) while proxying upgraded connection

**Comment by jsjoeio** [comment]
Thanks for the additional information. We may be able to create a test environment and try to reproduce this with a similar setup to yours (cc @bpmct any tips here for using Vultur?).

@code-asher may have insight too

**Comment by code-asher** [comment]
I haven't had the opportunity to debug but this seems related: https://github.com/cdr/code-server/issues/2803

**Comment by muxiangqiu** [comment]
Increase the constants related to Ack time in ipc.net.ts -> ProtocolConstants in the vscode project. Can solve the problems encountered above

```typescript
export const enum ProtocolConstants {
	HeaderLength = 13,
	/**
	 * Send an Acknowledge message at most 2 seconds later...
	 */
	AcknowledgeTime = 20000, // 2 seconds
	/**
	 * If there is a message that has been unacknowledged for 10 seconds, consider the connection closed...
	 */
	AcknowledgeTimeoutTime = 200000, // 20 seconds
	/**
	 * Send at least a message every 5s for keep alive reasons.
	 */
	KeepAliveTime = 500000, // 5 seconds
	/**
	 * If there is no message received for 10 seconds, consider the connection closed...
	 */
	KeepAliveTimeoutTime = 200000, // 20 seconds
	/**
	 * If there is no reconnection within this time-frame, consider the connection permanently closed...
	 */
	ReconnectionGraceTime = 3 * 60 * 60 * 1000, // 3hrs
	/**
	 * Maximal grace time between the first and the last reconnection...
	 */
	ReconnectionShortGraceTime = 5 * 60 * 1000, // 5min
}
```
