### ISSUE TITLE
Changing keyboard shortcuts does not change Keyboard Shortcuts UI immediately

### ISSUE THREAD

**Issue by hglyou** [coder/code-server#3105]
## OS/Web Information

- Web Browser: Chrome
- Local OS: Linux
- Remote OS:
- Remote Architecture:
- `code-server --version`: 3.8.0

## Steps to Reproduce

1. File >> Keyboard Shortcuts
2. Change any KeyBinding 
3. Keybinding is changed but the ui component does not change immediately 

## Expected

UI component should reflect changes in Keybinding. Users might think they cannot change KeyBindings 

## Notes

This issue can be reproduced in VS Code: Yes/No

**Comment by jsjoeio** [comment]
I was able to reproduce this running code-server 3.9.3 on macOS + Chrome. I didn't see any logs (in the terminal or browser) that indicate an error. I'll have to see if this happens in Codespaces as well.

## Screenshot

https://user-images.githubusercontent.com/3806031/114442288-41aee700-9b81-11eb-82e7-ac77d903ed4c.mov

**Comment by bdefore** [comment]
For me, it's not only that the UI doesn't update but that I need to reload the browser tab containing Code Server before the shortcut is active. I'm on 3.9.1.

**Comment by jsjoeio** [comment]
@bdefore good to know. I think I had to reload the tab as well for changes to take affect. Hopefully we can get to the bottom of this.

**Comment by worldofgeese** [comment]
Make it fresh
