### ISSUE TITLE
Upgrade parcel-bundler

### ISSUE THREAD

**Issue by jawnsy** [coder/code-server#3162]
We get a warning during the build related to a new major version of parcel, and should consider upgrading so that we can continue receiving updates/security support:

> warning parcel-bundler@1.12.5: Parcel v1 is no longer maintained. Please migrate to v2, which is published under the 'parcel' package. See https://v2.parceljs.org/getting-started/migration for details.

**Comment by oxy** [comment]
Parcel v2 is still in beta right now - see https://www.npmjs.com/package/parcel - and my initial attempts to get it working have it crashing with some error; currently working on debugging it.

**Comment by code-asher** [comment]
Just gonna throw this out here and see if it sticks but code-server's frontend is really quite barebones; we could compile the JavaScript with `tsc` and copy some files around and get rid of the bundler altogether. Honestly I don't think we gain that much from it. Not only that but after working for a long time mine stops compiling and I have to restart the whole process.
