### ISSUE TITLE
Migrate to Yarn v2 to resolve duplicate dependency issues

### ISSUE THREAD

**Issue by jawnsy** [coder/code-server#3164]
In #3161, @scinos suggested we use [`yarn-deduplicate`](https://github.com/atlassian/yarn-deduplicate) to fix duplicate dependencies in our lockfile ([link to comment](https://github.com/cdr/code-server/pull/3161#issuecomment-822477132)). The yarn-deduplicate project README says:

> This package only works with Yarn v1. Yarn v2 supports package deduplication natively!

So it seems like we could consider migrating to v2 as an alternative way to avoid this problem. The yarn documentation mentions that it's [intended to be installed on a per-project basis](https://yarnpkg.com/getting-started/install) (rather than globally) so we should be able to progressively upgrade our projects. There is also a [migration guide](https://yarnpkg.com/getting-started/migration#step-by-step) that provides step-by-step instructions.

**Comment by oxy** [comment]
Another important note that I didn't add above; npm v7 currently doesn't have an alternative to yarn's `resolutions` functionality - they're planning to add it in a future 7.x release - https://github.com/npm/rfcs/pull/129 - but there's nothing yet.

**Comment by jawnsy** [comment]
Removed stale label as I think this still applies
