### ISSUE TITLE
Multiple undocumented flags (e.g. --builtin-extensions-dir)

### ISSUE THREAD

**Issue by Micket** [coder/code-server#3212]
I found some flags that I wanted to use e.g.
https://github.com/cdr/code-server/blob/d31439ec34572b6829902ea1863931071fe1fc55/src/node/cli.ts#L155
but it turned out that they aren't documented anywhere I can find.

There seems to be a bunch of flags like this which don't seem to be documented anywhere (nothing from `code-server --help`) 

I've tried to look around, but, apart from the source code and an old PR where it was introduced, I find no reference to these features.

Edit: Turns out i probably wanted to use `extra-extensions-dir` or `extra-builtin-extensions-dir` instead. Either, documentation would be nice.

**Comment by code-asher** [comment]
Definitely fair, there are some bugs with those flags which I'd like to fix before making them more public. Tracking: https://github.com/cdr/code-server/issues/1157
