### ISSUE TITLE
Web based ssh to code-server

### ISSUE THREAD

**Issue by nooobcoder** [coder/code-server#3256]
Let me be very brief and clear, I have used `coder` and liked the feature of the ssh terminal in the pop out browser window. I found a similar docker image that can be bind with the docker image of code-server too. 
[](https://github.com/butlerx/wetty)
Check this out @jsjoeio @code-asher @bpmct  this might be a good thing for code-server. I know vscode provides integrated terminal but still, why not? Why not a browser based ssh console.

I am using this docker image and has been running fine. 

> The simplest deployment is,
> `docker run --name code-server-terminal -d -p 7878:3000 wettyoss/wetty --ssh-host=192.168.bla.bla`

Also, @code-asher this might be a solution to issues like, as this would be opened on a separate window and `code-server` window _can be reloaded independently_
#1832 #2276

I think this is a good feature request and can be implemented in the upcoming versions of code-server.
**Also, the ctrl+c to copy and ctrl+v to paste hotkeys work absolutely just like google cloud shell. I am loving this wetty very much.**
Thank You.
Here is a screenshot of it.
![image](https://user-images.githubusercontent.com/50350828/116527497-5b2d8e00-a8f8-11eb-8421-aaa0c57dd307.png)

**Comment by code-asher** [comment]
Interesting idea! I'm down for this. If we implement it I think I'd like to see it share the same backend as VS Code's terminals although that could be tricky.

**Comment by nooobcoder** [comment]
> Interesting idea! I'm down for this. If we implement it I think I'd like to see it share the same backend as VS Code's terminals although that could be tricky.

share the same backend as VS Code's terminals although
What does it mean @code-asher  I didn't get it

Also would this feature be rejected?

**Comment by code-asher** [comment]
> Also would this feature be rejected?

No, I think it's a good idea. <3

By the same backend I mean using xterm.js and connecting to the terminal service in VS Code. That way we don't have to add any new dependencies or code. Plus I think it would be cool if you could pop out terminals from VS Code and pop them back in.

But I'm not sure if that's possible so maybe using something like wetty is a better idea.

**Comment by nooobcoder** [comment]
@code-asher this issue should be a thing in next major updates! Web based ssh window exists in coder and should also be in code-server.

**Comment by code-asher** [comment]
I think it will be hard to find the time to implement this but we should
keep it in mind.
