### ISSUE TITLE
Green/blue status bar jumps to top on ipad pwa

### ISSUE THREAD

**Issue by illispi** [coder/code-server#3264]
## OS/Web Information

- Web Browser: safari pwa
- Local OS: ipados 14.5
- Remote OS: ubuntu 20.04
- Remote Architecture: x86
- `code-server --version`: 3.9.3

## Steps to Reproduce

1. Click on sidebar items like explorer or debugging when using ipad pwa
2.
3.

## Expected

Show selected side bar item.

## Actual

Bottom green/blue status bar jumps to very top sometimes and rest of the code editor disappears. 

You can restore view by clicking change keyboard layout on status bar.

## Logs

I can try to do logs later, if required.

**Comment by jsjoeio** [comment]
Thanks for filing this issue! No worries on the logs (browser logs would be hard to get, but if you have any server logs that could help `code-server --log debug`).

Is it possible for you to post a [screen recording](https://support.apple.com/guide/ipad/take-a-screenshot-or-screen-recording-ipad08a40f3b/ipados) so we can see this error happening?

**Comment by illispi** [comment]
https://user-images.githubusercontent.com/44943503/116634187-10e1f680-a964-11eb-8134-d4429851a787.MP4

I tried that command but it didnt really show anything and i didnt find find appropriate file on user-data-dir?

**Comment by jsjoeio** [comment]
Woah, that is a weird bug. I'll try to replicate it when I took a look.

No worries on the logs. Thanks for trying!

**Comment by GitMurf** [comment]
@jsjoeio @illispi any update on this? I am experiencing the EXACT same issue on my new ipad pro 11inch with ipad os 15 and I just installed code-server a few days ago for the first time so I am on the most recent version.

On mobile safari in a tab everything works fine. But if I use share sheet in safari tab to "Add to the Home Screen" so that it adds a "PWA" version of the "app" with an icon to the home screen, then I get the same behavior here. I don't even have to do anything specific... it will just usually happen after 30-60 seconds of using vs code.

**Comment by GitMurf** [comment]
I have a feeling that this issue is somewhat related: https://github.com/cdr/code-server/issues/3543

**Comment by jsjoeio** [comment]
Hmm...that is very strange. Do you mind posting a video? @GitMurf 

Also, are you accessing your code-server instance over HTTPS?

Unfortunately I am not experiencing this on my iPad so I'm not sure what the issue could be.

**Comment by GitMurf** [comment]
Hi @jsjoeio thanks for the quick response! My video basically is exactly like @illispi video above.

I am just using http. Doing it via my local network so I changed my bind-addr to be 192.168....:8081 for the local IP of my code-server machine.

Then I simply go to http://192.168...:8081 in safari. Safari tab works fine but then when create PWA by share sheeting it to the home screen then it has the issue documented in this thread when using the PWA app. Safari using tabs still works fine.

My config yaml settings file looks exactly like this except with my own password and with the localhost IP changed to my 192....:8081 as I described above.

![image](https://user-images.githubusercontent.com/64155612/135911707-21c1219c-332d-4c14-9e1e-fe9abc78d2a8.png)

Does that make sense? Any other info you want/need?

**Comment by jsjoeio** [comment]
@GitMurf thanks for the info! Hmm... I don't know what could be causing this sadly. I am surprised it's working without HTTPS. Usually it doesn't!

I don't know how we can help here unfortunately 😢 I just tested locally and can't reproduce.

1. [Update Dockerfile](https://github.com/jsjoeio/code-server-railway-ipad/blob/main/Dockerfile) to use latest version of code-server
2. Deploy on [Railway](https://railway.app/)
3. Open in Safari on iPad (running iPadOS 14.7)
4. Add to Home Screen
5. Open up
6. Search for file

https://user-images.githubusercontent.com/3806031/135926305-738f20ae-2a38-4ddb-97b7-3212dba85210.MP4
