### ISSUE TITLE
[dev]: update-vscode.sh should checkout package.json and update yarn.lock

### ISSUE THREAD

**Issue by jsjoeio** [coder/code-server#3359]
>  I think I mentioned this before but I wonder if we should modify the VS Code PR script to checkout the package.json and yarn.lock, then remove the dependencies we don't want and regenerate the lock.

— @code-asher

Relevant code: https://github.com/cdr/code-server/blob/main/ci/dev/update-vscode.sh

**Comment by code-asher** [comment]
We should also automatically move ripgrep to dependencies as part of this: https://github.com/cdr/code-server/pull/3383
