### ISSUE TITLE
Display language doesn't persist in code-server v3.11.0 running in Docker container when installing from CLI

### ISSUE THREAD

**Issue by aleleba** [coder/code-server#3372]
## OS/Web Information

- Web Browser:
- Local OS:
- Remote OS:
- Remote Architecture:
- `code-server --version`:
Version 3.11.0 of Code-Server

## Steps to Reproduce

1. Add file "argv.json" to "/home/coder/.local/share/code-server/User/"
2. Reload window
3. Languague change
4. Code of argv.json:
```
{
    "locale": "es"
}
```

## Expected

Change Languague Display

## Actual

Not Change Language Display

## Notes

This issue can be reproduced in VS Code: Yes/No

**Comment by jsjoeio** [comment]
I was able to successfully reproduce this on macOS + Chrome and code-server 3.10.0

![image](https://user-images.githubusercontent.com/3806031/118044275-4fe05680-b32b-11eb-946d-358f054fa4ad.png)

**Comment by jsjoeio** [comment]
However, you can change the display language if you do the following:
1. Open Command Palette
2. Search for "Configure Display Language"
3. Click "Install additional Languages"
4. Select language pack
5. Reload

## Screenshot
![image](https://user-images.githubusercontent.com/3806031/118044658-caa97180-b32b-11eb-8c96-3c754634085a.png)

And, if you restart code-server the language pack is installed and we set the locale in `argsv.json` so it persists!

![image](https://user-images.githubusercontent.com/3806031/118044884-10fed080-b32c-11eb-98aa-a8d95c48a82a.png)


@aleleba can you please double-check that you have the language pack extension installed?

**Comment by aleleba** [comment]
Yes I can confirm that I install the language pack. Currently I install the Spanish Language package directly with a command in my Dockerfile.

What happens in the previous versions of code-server is that when entering for the first time it already opened the Spanish language by default.

I just tried uninstalling and installing the package again, restarted the window and changed the language.

In the same way, I would like the language to be preloaded as before, so that if the Docker container falls, it takes the language configuration at once.

I am attaching the docker docker command I use in the Dockerfile:

```
RUN code-server --extensions-dir ~/.local/share/code-server/extensions/ --install-extension ms-ceintl.vscode-language-pack-es
```

I really appreciate the follow-up and the help.

**Comment by jsjoeio** [comment]
Ah okay, thank you for all the details. So here's a screenshot of my running that command locally (not using Docker):
![image](https://user-images.githubusercontent.com/3806031/118175415-ed4b9100-b3e4-11eb-94d0-9da1422cfd7f.png)

Hmm...now this is interesting... When I look inside `/Users/jp/.local/share/code-server/User`, I see an `argsv.json` and `argv.json` 🤔

![image](https://user-images.githubusercontent.com/3806031/118175862-811d5d00-b3e5-11eb-9103-dfeececaf471.png)


I'll keep both and restart code-server.

It's in Spanish, as expected.
![image](https://user-images.githubusercontent.com/3806031/118175674-461b2980-b3e5-11eb-9d38-50af62996b1b.png)

According to [VS Code's docs](https://code.visualstudio.com/docs/getstarted/locales), `argv.json` is the expected filename to keep the locale. 

Let's delete the `argsv.json`, restart code-server and see what happens. Still in Spanish so that wasn't an issue. (probably a typo from me)

![image](https://user-images.githubusercontent.com/3806031/118175971-a9a55700-b3e5-11eb-835d-c6acf9d9bfdc.png)

Well, I'm a bit stumped. It feels like this is specific to how code-server is loading/running in your Docker environment. Maybe @code-asher has some insight.

**Comment by aleleba** [comment]
I started to see the changes from version 3.9.3 to version 3.10.0, to see if I can help to find the error and I could observe this change: https://github.com/cdr/code-server/pull/ 3250 / files

I think instead of placing:

```
yarn gulp compile-build compile-extensions-build
```

You have to place:

```
yarn gulp compile-build && yarn gulp compile-extensions-build
```

To stand in a line.

I don't use yarn and I'm not an expert in bash, so I don't really know if that is the case.

I hope to help a little

**Comment by jsjoeio** [comment]
Maybe @oxy might have some insight too.

**Comment by code-asher** [comment]
I was able to replicate with:

```
$ rm ~/.local/share/code-server -r
$ code-server --install-extension ms-ceintl.vscode-language-pack-es
$ echo '{"locale":"es"}' > ~/.local/share/code-server/User/argv.json
$ code-server # Browse to localhost:8080
```

Strangely, I don't get the option to select `es` from the command palette either even though the extension is installed.

If I uninstall the extension and re-install then refresh everything works.

I think there is some language bundle generation that happens somewhere that isn't running when doing things in the CLI but is running when doing things through the UI.

**Comment by aleleba** [comment]
I just noticed another weird behavior in code-server.

When deactivating an extension and reloading the window, this extension is not deactivated.

I think this bug may be linked to that behavior.

**Comment by humbinal** [comment]
```
$ code-server --install-extension ms-ceintl.vscode-language-pack-es
$ ll ~/.local/share/code-server/
total 4
drwxr-xr-x 2 root root 59 May 28 22:28 CachedExtensionVSIXs
drwxr-xr-x 2 root root 66 May 28 22:27 coder-logs
drwxr-xr-x 3 root root 59 May 28 22:28 extensions
drwxr-xr-x 3 root root 29 May 28 22:27 logs
-rw-r--r-- 1 root root 36 May 28 22:27 machineid
drwxr-xr-x 2 root root  6 May 28 22:27 User
```
no languagepacks.json found, It's what causes it not to work !!!

when install language pack manually by UI，the `languagepacks.json` file auto generated at `~/.local/share/code-server/` , and language pack works.

generate `languagepacks.json` file when exec `code-server --install-extension ...`  will works, but I don't know how to realize...

**Comment by ifduyue** [comment]
Same here, languagepacks.json is missing after installing language pack in command line.

**Comment by aleleba** [comment]
I would like to follow up on this error. I would like to know what I can do to help solve it, I really like code-server, but I had to stay in version 3.9.3, where these errors do not occur, how can I help to solve this problem. A pleasure to greet the entire team.

**Comment by jsjoeio** [comment]
Thanks for offering to help @aleleba! 

> I think there is some language bundle generation that happens somewhere that isn't running when doing things in the CLI but is running when doing things through the UI.

I think this would be the first place to start. Use the latest version of code-server and see if you can confirm this theory (i.e. can this issue be reproduced when doing things via the CLI and also through the UI?)

**Comment by aleleba** [comment]
I confirm this theory, when I installed the language from CLI no languagepacks.json found and when doing from IU it works

**Comment by jsjoeio** [comment]
Nice work! 🎉

Okay since this only happens with the CLI, my guess is we need to investigate there. Maybe we can write a function that checks if the extension to download is a language and if it is, add the languagepacks.json.

Let's double-check with @code-asher though first

**Comment by code-asher** [comment]
I'm not sure; we just shell straight out to VS Code to handle the
installation so it's odd that it doesn't work.

I suppose we should first check what desktop VS Code does. Install an
extension then (without launching VS Code!) see if the file exists.

If it does, that's weird and I'm not sure how to debug that but we'll
cross that bridge if we come to it.

If it doesn't, then launch VS Code and see if it appears then. If it
does then we migh be missing something that is supposed to create the
missing file on startup/launch (much like we create missing directories,
etc). If this is the case then we'll probably want to look into how
desktop VS Code does it and copy/import that.

**Comment by dgadelha** [comment]
@jsjoeio, do think you can add that to [4.0.3 milestone](https://github.com/coder/code-server/milestone/36)?

The function you mentioned already exists in VS Code API, it's [`LocalizationsService.postInstallExtension()`](https://github.com/coder/vscode/blob/5f069ef211aa08b23864032532b1161309ce03c7/src/vs/platform/localizations/node/localizations.ts#L58-L63), which then calls [`LanguagePacksCache.update()`](https://github.com/coder/vscode/blob/5f069ef211aa08b23864032532b1161309ce03c7/src/vs/platform/localizations/node/localizations.ts#L105-L109), who manipulates `languagepacks.json`.

For what I've seen, seems that `LocalizationsService` isn't registered on CLI mode when installing on extension, that'd explain why [`postInstallExtension` isn't called](https://github.com/coder/vscode/blob/5f069ef211aa08b23864032532b1161309ce03c7/src/vs/platform/localizations/node/localizations.ts#L41-L44).

**Comment by jsjoeio** [comment]
@dgadelha unfortunately not since I'm at max bandwidth for that sprint, but I can add it as a high priority item.

PRs are also welcome. Thanks for posting those notes! That will definitely speed things up when we get to this.

**Comment by alanhg** [comment]
which old version is ok? Or was it an existing BUG all along?

**Comment by code-asher** [comment]
I think it never worked.

**Comment by jsjoeio** [comment]
@aleleba can you try reproducing this with the latest version of code-server?

**Comment by aleleba** [comment]
Yes I already try and the behavior  is the same.

**Comment by jsjoeio** [comment]
Thank you! If you want to dig in, I'd start here: https://github.com/coder/code-server/issues/3372#issuecomment-1029340034

**Comment by code-asher** [comment]
I tried this with desktop VS Code (`--install-extension`, edit `argv.json`, then launch) and it did not change my language so this seems to be an upstream issue.

**Comment by Anyexyz** [comment]
> 我确认了这个理论，当我从 CLI 安装语言时没有找到 languagepacks.json，而从 IU 安装时它可以工作



> I was able to replicate with:
> 
> ```
> $ rm ~/.local/share/code-server -r
> $ code-server --install-extension ms-ceintl.vscode-language-pack-es
> $ echo '{"locale":"es"}' > ~/.local/share/code-server/User/argv.json
> $ code-server # Browse to localhost:8080
> ```
> 
> Strangely, I don't get the option to select `es` from the command palette either even though the extension is installed.
> 
> If I uninstall the extension and re-install then refresh everything works.
> 
> I think there is some language bundle generation that happens somewhere that isn't running when doing things in the CLI but is running when doing things through the UI.



> I was able to replicate with:
> 
> ```
> $ rm ~/.local/share/code-server -r
> $ code-server --install-extension ms-ceintl.vscode-language-pack-es
> $ echo '{"locale":"es"}' > ~/.local/share/code-server/User/argv.json
> $ code-server # Browse to localhost:8080
> ```
> 
> Strangely, I don't get the option to select `es` from the command palette either even though the extension is installed.
> 
> If I uninstall the extension and re-install then refresh everything works.
> 
> I think there is some language bundle generation that happens somewhere that isn't running when doing things in the CLI but is running when doing things through the UI.


Thank you for your suggestion! Based on your idea, I wrote a Bash script to automatically generate the `languagepacks.json` file.  
You can check it here:  
- [[Dockerfile](https://cnb.cool/Anyexyz/DevEnv/default-dev-env/-/blob/main/Dockerfile)](https://cnb.cool/Anyexyz/DevEnv/default-dev-env/-/blob/main/Dockerfile)  
- [[create_languagepacks](https://cnb.cool/Anyexyz/DevEnv/default-dev-env/-/blob/main/create_languagepacks)](https://cnb.cool/Anyexyz/DevEnv/default-dev-env/-/blob/main/create_languagepacks)

With this setup, the `languagepacks.json` file will be automatically generated after installing **a single** language pack, making it easier to switch languages.
