### ISSUE TITLE
Issue running command code-server

### ISSUE THREAD

**Issue by omxpro** [coder/code-server#3401]
My name@localhost:~$ code-server
internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module '/usr/lib/code-server'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
Myname@localhost:~$

**Comment by omxpro** [comment]
I tried re installing still didn't work

**Comment by jsjoeio** [comment]
Hi @omxpro - can you please update your issue description and fill out the bug report template? That will help us help you faster! Thank you.

**Comment by code-asher** [comment]
How did you install code-server? It looks like `/usr/lib/code-server` is missing.

**Comment by omxpro** [comment]
Of course I did install code server in /bin folder

**Comment by omxpro** [comment]
Wait I need to move my entire dir? How can I do that in ubuntu 18.04 LTS, and ill check the getting started script (I used your curl script)

**Comment by code-asher** [comment]
If you used our install script then you shouldn't have to do anything! It will install code-server using a `.deb` file which will put everything where it needs to be.

**Comment by code-asher** [comment]
If you used our install script but `/usr/lib/code-server` is missing could you try running it again?

**Comment by omxpro** [comment]
I don't use code server anymore
