### ISSUE TITLE
Fix settings sync login and "loading" text

### ISSUE THREAD

**Issue by code-asher** [coder/code-server#3418]
Currently if you hover over the account login when you aren't logged in it just says "loading".

<img src="https://user-images.githubusercontent.com/45609798/118843429-abf92c80-b88f-11eb-88eb-ef9f89a29c0a.png" width="200" />

This is what it should look like instead:

<img src="https://user-images.githubusercontent.com/45609798/118841566-0b563d00-b88e-11eb-9b2d-d1da0c073f64.png" width="300" />

Pressing "turn on settings sync" then takes you through the login process. It allows you to sign in with Microsoft and GitHub although I'm not sure we'll be able to support both or only GitHub.

----

If you are already logged in (to GitHub) supposedly syncing works and the icon works fine too but we should verify this.

----

Previous issues: https://github.com/cdr/code-server/issues/2587 https://github.com/cdr/code-server/issues/2913

**Comment by code-asher** [comment]
Interestingly if you have the GitHub pull request extension installed the icon works but there is still no sync.

After poking around it seems that settings sync is intentionally not included in the OSS.

So I think this means we will need to instead modify "loading" to say "there are no extensions that provide auth" or something like that.

And then at a later date perhaps we can look into implementing sync.

**Comment by johnsonw** [comment]
> After poking around it seems that settings sync is intentionally not included in the OSS.
Any particular reason? My VS Code local install shows it here:
![image](https://user-images.githubusercontent.com/1100657/127437364-d54fc15a-63df-48c1-83a0-6321624ee6b3.png)

But when I go to the remote container it's missing as you said:
![image](https://user-images.githubusercontent.com/1100657/127437419-a39ba277-4393-437a-bfa6-8bb942c3cc62.png)

Just wondering why this would be intentional?

**Comment by code-asher** [comment]
I can make guesses but I don't know for sure why it's not available for
OSS builds. Here is the comment from one of the VS Code devs but there
is no further explanation:
https://github.com/microsoft/vscode/issues/105310#issuecomment-693262654

**Comment by AlexRex** [comment]
Do we know if this will be included in the OSS build?

**Comment by tsndr** [comment]
I'm still having this issue.

**Comment by emielvangoor** [comment]
> 

Same here...

**Comment by corngk** [comment]
> > 
> 
> Same here...

me too.

**Comment by emielvangoor** [comment]
> > > 
> > 
> > 
> > Same here...
> 
> I use WSL2 Ubuntu. I install git on the WSL Ubuntu from terminal, then the problem solved.

i'm using Mac OS Monterey. I've moved away from code-server, i ever managed to fix this unfortunately.

**Comment by norbertjoni** [comment]
same issue from chromebook

**Comment by Sharpz7** [comment]
@jsjoeio It worked for me for ages and suddenly broke (i.e worked in march broke on the 21st June). This issue doesn't seem to cover that context?

**Comment by Sharpz7** [comment]
By "context" I mean that I created my issue because my sign-in *was*
working, and then suddenly broke randomly on the 21st of June, with no
updates. I don't think this issue is the same as that one?

The 21st is also when my GitHub copilot stopped working, and I feel like
that must be related, as you need GitHub login details for it to work.

Maybe we can discuss this further somewhere?

Thanks :))

**Comment by Sharpz7** [comment]
Sorry, after more extensive testing it seems that Copilot had a login system change on the same day as this started, so is just a co-incidence. I apoligize ;)

**Comment by jsjoeio** [comment]
Ahhhh interesting! Thanks for confirming. No worries! 😄

**Comment by nmcc1212** [comment]
if settings sync isn't possible, how come https://github.dev has it

**Comment by code-asher** [comment]
I assume github.dev is owned by GitHub (Microsoft) in which case 
settings sync will work for them since they are not using the OSS 
version of Code.

**Comment by bitdruid** [comment]
if you may have noticed all microsoft extensions are missing in the oss version. thats why i uninstalled it after short testing about a year ago as i'm using a lot of them and setting-sync would be useless if half of my extensions are missing.

there is currently no workaround as long as there is no version like ,,bin-server"

**Comment by sunerpy** [comment]
same issue
When I pressed "turn on settings sync" ,there is nothing happened...
I run code-server with docker, any ideas to help me login?

**Comment by dnslin** [comment]
docker latest 
So how do we solve this problem

**Comment by cpatrickalves** [comment]
Any update about this? 
I am running code-server on Kubernetes. 

![image](https://github.com/coder/code-server/assets/22003608/f0150752-017e-4435-92d7-69002bec678b)

**Comment by code-asher** [comment]
It looks like upstream changed "loading" to "no accounts requested yet..." so I think we can consider that portion of the issue resolved.

And for the settings sync portion we have another issue tracking that (https://github.com/coder/code-server/issues/2195) so I will close this issue.
