### ISSUE TITLE
Hash password with bcrypt and store in config.yaml

### ISSUE THREAD

**Issue by jsjoeio** [coder/code-server#3432]
## Problem

As a user, I would like to be able to hash my password using the same `bcrypt` algorithm used by code-server.

However, the `bcrypt` and `bcrypt.js` algorithms are different so you can't in the same way you can with `sha256`. 

## Solution

Add a CLI option to set password (which we hash for User using `bcrypt`)

`code-server --config password=<password>` -> hashes and stores in `config.yaml`

(open to other ideas for this though^)

Todos
- [ ] update docs
- [ ] add backwards-compatiblity for those still hashing with sha256
- [ ] let user provide password via stdin to avoid having the plaintext password in their shell history

**Comment by rabidpug** [comment]
would be good if the user could provide password via stdin to avoid having the plaintext password in their shell history.

**Comment by jsjoeio** [comment]
Didn't even think to consider that - great point @rabidpug 👍

**Comment by quentincaffeino** [comment]
> would be good if the user could provide password via stdin to avoid having the plaintext password in their shell history.

Put a space before your command, this way it won't be stored in history.

**Comment by code-asher** [comment]
Merging with https://github.com/coder/code-server/issues/3432
