### ISSUE TITLE
[iPadOS] Copy-paste to terminal is not working on iPad

### ISSUE THREAD

**Issue by alexey1966** [coder/code-server#3491]
code-server: v3.10.2
 VS Code: v1.56.1
Commit: 387b12ef4ca404ffd39d84834e1f0776e9e3c005
Date: 2021-05-21T23:13:00Z
Browser: Mozilla/5.0 (iPad; CPU OS 14_4_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Mobile/15E148 Safari/604.1

Copy-paste to and from terminal is not working on iPad.
For pasting you need to push on Paste pop-up.

**Comment by jsjoeio** [comment]
@alexey1966 can you please redo your issue description and fill out the bug report? That way we can look into this.

Thanks!

**Comment by bpmct** [comment]
I am noticing this as well. Here is a video to reproduce, using iPadOS 15. Occurs when using the keyboard shortcut CMD+V to paste

https://user-images.githubusercontent.com/22407953/134998692-6aa7580b-4795-4170-a96e-a44fb0197c51.mp4

I can create another issue with the template, if helpful.

**Comment by jsjoeio** [comment]
@bpmct does this only happen you're multitasking (dual screen)?

**Comment by bpmct** [comment]
Also occurs when swiping from screen to screen.

**Comment by slimdevl** [comment]
I have this issue and a few other weird key binding issues on an ipad pro (2020) + magic keyboard (folio)

Sometimes a window refresh (ctrl+r) resolves it... sometimes I have to close the browser (safari) and reopen it to clear the issue.

What I notice is:
1. copy and paste is routed to the terminal (if I have more than one open)  instead of pasting to the open editor window. (ctrl+r fixes this generally)
2. enter key starts only activating the find modal - but then I can get enter if I hold shift+enter.
3. enter key stops working all together while in the editor... I have to detact the screen from the folio to clear this issue. (I think it is an apple issue - but not sure)

Ping me if you'd like any videos of this behavior. Or any other debugging info. BTW - thanks for the awesome project! I love it 👍🏻

**Comment by jsjoeio** [comment]
@slimdevl thanks for the details! Videos would be super useful. I'll have to try my ipad pro and see if I get the same behavior. I assume this is on 4.0.1, yeah?

**Comment by slimdevl** [comment]
Yes, it is 4.0.1. I will capture a video today (hopefully) to share with
you.

**Comment by miohtama** [comment]
Just to bump this issue - iPad + Safari still cannot properly paste in the terminal.

- Pressing CMD+V on a physical iPad keyboard opens the text edit menu on screen with “Paste” option instead of pasting the text

**Comment by code-asher** [comment]
A comment upstream suggests unbinding `cmd+v` might make it work (since it will use native paste that way): https://github.com/microsoft/vscode/issues/85254#issuecomment-626065078

Not sure though...if you can reproduce on vscode.dev or Codespaces I recommend you report it upstream.

**Comment by marksfink** [comment]
I'm having this issue.  Fwiw, pasting in the terminal works fine (as far as I can tell).  Copying in the terminal is the issue.  If I copy something from anywhere else, say in the editor, it will paste into the terminal just fine (using Cmd-V).  When I then try to copy something in the terminal (using Cmd-C or Copy in the menu), then hit Cmd-V to paste it, it continues to paste what was already in the clipboard from the editor.  Iow, the clipboard was not updated with the Cmd-C selection in the terminal.

I can use Cmd-F which opens the search bar and populates it with the selected text and then Cmd-C on that.  That works as a workaround.  But I cannot Cmd-C anything in the terminal itself.

I enabled Copy on Selection in Terminal settings.  When I first go into a terminal, I can select something and it goes to the clipboard and I can paste it.  But it only works once.  After that one time, it does not work again (until I kill and launch a new terminal).

I have modified keyboard shortcuts (I removed Cmd-C as the shortcut for copying in the terminal).  This has no effect.  And I modified Terminal settings like Commands to Skip Shell making sure terminal copy and paste are skipped and also making sure they are not skipped -- behavior is the same either way.

I have tried Safari, Chrome and Firefox on the iPad and all behave exactly the same -- that is, copy does not work in the terminal.

If I access Github Codespaces from my iPad, copy-paste work fine.  Also, if I use a remote tunnel with vscode.dev, and use my iPad, copy-paste work fine.

Also I accessed code-server from a Windows machine using Firefox, and copy-paste worked fine.  So it appears to be an iPad issue.

Hope this helps.

**Comment by code-asher** [comment]
Interesting, Codespaces works but not code-server?  Is the version of code-server you are using bundle the same version of VS Code that Codespaces currently does?  We use the same web version of VS Code that Codespaces does so it does seem strange if it is only broken in code-server.

**Comment by marksfink** [comment]
I'm using the latest Docker container image to test it.  codercom/code-server. It's at 4.93.1.

**Comment by code-asher** [comment]
Hm, so the same version of VS Code currently used in Codespaces then.  I am not sure what we could have changed to break it on iOS.  You are using https, right?  I think they use the clipboard API so it requires a secure context.  Unfortunately I do not have an iPad to reproduce, but if someone is able to figure out what we broke, PRs are very welcome. We may want to test with `code serve-web` to see if we can reproduce directly with VS Code.
