### ISSUE TITLE
Add support for development on Windows

### ISSUE THREAD

**Issue by code-asher** [coder/code-server#3501]
- [ ] Use cross-env
- [ ] Spawns in `watch.ts` don't work for some reason.
- [ ] May want to port the build scripts to JS for portability (this could also make them easier to unit test if we decide to do that).

See this discussion for more information: https://github.com/cdr/code-server/discussions/3488

**Comment by jsjoeio** [comment]
Related: https://github.com/cdr/code-server/discussions/3554#discussioncomment-833737
