### ISSUE TITLE
Revert code-ql-action/upload-sarif

### ISSUE THREAD

**Issue by jsjoeio** [coder/code-server#3517]
Revert https://github.com/cdr/code-server/issues/3459

We have a short term workaround thanks to @adityasharad 

> Short term workaround: please try removing the TAR file /release-images/code-server-amd64-3.10.2.tar (and others like it) from the workspace before running the upload step.

UPDATE: a PR has been merged https://github.com/github/codeql-action/pull/550

So we should be able to re-enable without using the workaround.

**Comment by edoardopirovano** [comment]
Note that my PR has been merged in the `main` branch of the CodeQL action while [your workflow](https://github.com/cdr/code-server/blob/main/.github/workflows/codeql-analysis.yml) is using `@v1`. So, it will be a little bit longer before the fix reaches you (we usually release to `v1` every week or two).

**Comment by jsjoeio** [comment]
Ah...good to know. Thanks for pointing that out @edoardopirovano 👍🏼

**Comment by jsjoeio** [comment]
Looks like there is a new release out, so I think this is fine to upgrade: https://github.com/github/codeql-action/releases/tag/codeql-bundle-20210622

**Comment by edoardopirovano** [comment]
> Looks like there is a new release out, so I think this is fine to upgrade: https://github.com/github/codeql-action/releases/tag/codeql-bundle-20210622

Almost! The CodeQL Action that your workflow is running still hasn't been bumped to use the latest version, that should happen once this PR is merged later today:

https://github.com/github/codeql-action/pull/585

Once that's merged you should be all good to go ahead with this 🙂

**Comment by jsjoeio** [comment]
Ahh... Got it. Guess the release notification was a false alarm! 

Thanks for the heads-up and linking the PR 😄

**Comment by jsjoeio** [comment]
The GitHub Action side is fixed but now it seems like there's an issue on the trivy side (see https://github.com/aquasecurity/trivy/issues/1080). 

I looked into reverting this in #3727 but it seems like it's more work than it's worth at this time. I will revisit later (hoping that the upstream trivy issue is fixed).

If this gets revisited, and the upstream issue isn't fixed, we can look into uploading the Docker image per PR to the GitHub Container Registry. Some resources:
- https://github.com/redhat-actions/push-to-registry
- https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions
- https://geoffhudik.com/tech/2020/09/29/trying-github-container-registry-using-github-actions/
