### ISSUE TITLE
Remove Android backspace issue after next vscode update

### ISSUE THREAD

**Issue by jsjoeio** [coder/code-server#3539]
@huszkacs fixed the Android backspace issue upstream here: https://github.com/microsoft/vscode/pull/124288

Once the May 2021 milestone, or the next vscode release is out, we can update in code-server and then update the docs 🎉

**Comment by huszkacs** [comment]
@jsjoeio I am not sure, if the latest vscode has this change or not?

**Comment by jsjoeio** [comment]
Good question! Based on [this commit](https://github.com/microsoft/vscode/commit/a8a57c3fc67e65d1d42e205a0182cbb781504df3), I think it was introduced in 1.57.0 🤔

And code-server 3.12.0 currently uses 1.60.0 so it _should_ be there but I haven't verified.
