### ISSUE TITLE
Issue warning to folks using old sha256 hashed password

### ISSUE THREAD

**Issue by jsjoeio** [coder/code-server#3560]
@jawnsy had a great idea:
> I'm not sure where in the code to put it, but it would be nice to issue a warning if someone is using the plain text/cookie/sha256 methods to tell them that their authentication method is insecure, and to consider upgrading to argon2.

See: https://github.com/cdr/code-server/pull/3422#discussion_r646013152

Will look at after: https://github.com/cdr/code-server/pull/3422

**Comment by finzzz** [comment]
I've tried to use argon2 but apparently it needs salt. But when I use salt, code-server cannot verify it.

**Comment by jsjoeio** [comment]
Hmm...that doesn't seem right. Can you provide steps to reproduce?

**Comment by finzzz** [comment]
Sorry my bad, I tried to use 
```
echo "password" | argon2 passphrase -e
```
instead of
```
echo -n "password" | argon2 passphrase -e
```
But probably will help if someone encounters similar issue.

**Comment by jsjoeio** [comment]
You have to use `argon2-cli` because that's what code-server uses under the hood. I don't think `argon2` will work because it uses a different hashing algorithm compared to `argon2` the npm package (unless it changed and it does work, but that would be new to me).

## Video

Here's how you can do it: 

https://user-images.githubusercontent.com/3806031/128934017-639e121c-30d6-418c-b2c6-17466bd2b7b7.mov

**Comment by finzzz** [comment]
I don't know what's under the hood, but it works with argon2.

**Comment by jsjoeio** [comment]
Ah, interesting! Maybe I was using it wrong before but hey, glad that works then 🙌

**Comment by antofthy** [comment]
I for one would love to be able to figure out (or retrieve) the session token!  Either from the password, or from the code-server configuration files.   So far no luck in matching up anything!

**Comment by jsjoeio** [comment]
So the user declares the password in the code-server config file. The password is then hashed and sent back in the response to the client and stored as a cookie. Here is the logic: https://github.com/coder/code-server/blob/main/src/node/routes/login.ts#L87

**Comment by antofthy** [comment]
Though I declare the password in an environment variable ($PASSWORD) in a docker instance.
But after some experiments I validated the URL encoded value of the 'key' cookie, to the given password.
As such if the cookie can be preset set for that website, I should be able to auto-initialise the login for a already authenticated user.

One small step... leading to another.

**Comment by jsjoeio** [comment]
@antofthy well keep an eye on any argon2 issues. If it does change, we should be able to add backwards-compatibility. You'll know though from the release notes

**Comment by code-asher** [comment]
Merging with https://github.com/coder/code-server/issues/3546
