### ISSUE TITLE
How to user code-server with https and signed certificate?

### ISSUE THREAD

**Issue by andreas128** [coder/code-server#3564]
Thanks for forking vscode! This project helps us a lot on our cluster. Can you please help us with the following problem?

By default code-server uses a http connection, which is not encrypted.

```
code-server
```

To enable an https (encrypted) connection one needs to add the `--cert` flag. However this will give an error in the browser about an unsecure connection.

```
code-server --cert
```

To obtain an https connection that the browser trusts, one needs to execute the following command.

```
code-server --cert <Please Help>
```

**Comment by kaaax0815** [comment]
It is recommended to use a Reverse Proxy like Caddy or Nginx
There is also Documentation about this in [guide.md](https://github.com/cdr/code-server/blob/main/docs/guide.md#self-signed-certificate)
And also this in `--help`
```
--cert                 Path to certificate. A self signed certificate is generated if none is provided.
--cert-host            Hostname to use when generating a self signed certificate.
--cert-key             Path to certificate key when using non-generated cert.
```

**Comment by jsjoeio** [comment]
I think @kaaax0815 has the best answer here 🙌

I don't know the details of your setup, but `--link` can also help with TLS. Check out [this video](https://www.youtube.com/watch?v=MdIEiZpg5vQ)
