### ISSUE TITLE
Replacing hashing password scheme with something more robust

### ISSUE THREAD

**Issue by jsjoeio** [coder/code-server#3576]
> While hashing is a major step forward, the problem with this approach is that it still allows attackers who have access to the hash to just submit it as-is and gain access to code-server - effectively not very different from storing it in plaintext.

> We should definitely look into replacing this with something more robust so that password hashing isn't just a placebo.

As security expert @oxy points out, our current approach for hashing the password and storing it in a cookie is more like a placebo-effect than a real security approach.

https://github.com/cdr/code-server/pull/3422#discussion_r647773585

Related:
- https://github.com/cdr/code-server/pull/3422
- https://github.com/cdr/code-server/issues/3560

**Comment by oxy** [comment]
One possible route forward is to generate a token when code-server is started, and then return that token if authentication was successful - this means that you'd need to re-auth if you restart code-server, but I think its an acceptable middle ground between security and ease-of-use.

**Comment by jsjoeio** [comment]
> this means that you'd need to re-auth if you restart code-server, but I think its an acceptable middle ground between security and ease-of-use

Agreed! I like the sound of that approach.

**Comment by Livven** [comment]
If I understand correctly the password hash is directly set as a cookie, instead of using some kind of session token, which is why a leak of the password hash on the server would allow attackers to authenticate with the password hash without knowing the original password, right?

In that case what you could do is to store `sha256(argon2(password))` on the server and set `argon2(password)` as a cookie. This way, if an attacker steals `sha256(argon2(password))` from the server, they would still not be able to authenticate.

Note that a simple `sha256` is adequate here since `argon2` already takes care of the key stretching.

As a bonus, you could even offload `argon2` computation to the client as [server relief](https://news.ycombinator.com/item?id=22022865), thanks to the additional `sha256` on the server.

**Comment by jsjoeio** [comment]
> If I understand correctly the password hash is directly set as a cookie, instead of using some kind of session token, which is why a leak of the password hash on the server would allow attackers to authenticate with the password hash without knowing the original password, right?

Exactly!

> In that case what you could do is to store sha256(argon2(password)) on the server and set argon2(password) as a cookie. This way, if an attacker steals sha256(argon2(password)) from the server, they would still not be able to authenticate.

Wow, this seems very straightforward to implement (and test too). Thanks so much for the suggestion and the tips! 🙌 Really appreciate it.

**Comment by antofthy** [comment]
We create a random password for each session, so using it as a session token is not really an issue.?

What I do find interesting is that how conrol panel could pre-set the cookie for the authenticated user, to match the password that code-server (running in a docker service) is given.  As such I am actually interested in exploting this to make it easier for the users without uncompromising security!    Or maybe somehow pre-set (or read) what the session token currently is from the running code-server service.

**Comment by jsjoeio** [comment]
Note to self: we may actually move away from argon2. It requires native binaries and has caused a lot of problems with Termux, Raspberry Pi and other devices/environments.

**Comment by jsjoeio** [comment]
We've also talked about moving to a session token which I believe VS Code has built-in support for.

**Comment by jsjoeio** [comment]
node-rs now publishes an argon2 package. Might help here: https://github.com/napi-rs/node-rs/tree/main/packages/argon2

**Comment by code-asher** [comment]
Merging with https://github.com/coder/code-server/issues/3546
