### ISSUE TITLE
throw error and blank screen when wrapped/embedded in iframe

### ISSUE THREAD

**Issue by futurist** [coder/code-server#3653]
## OS/Web Information

- Web Browser: Chrome
- Local OS: MacOS 10.15.5
- Remote OS: Debian 9
- Remote Architecture: K8S
- `code-server --version`: 3.8.1

## Steps to Reproduce

1. Code-Server Client page wrapped in an iframe
2. From parent page, setTimeout(gotoCodeServerUrl_in_iframe, 5000)
3. Switch into another Tab, wait for 5 secs
4. Back to see whether the page appear: got throw error in browser console and a blank screen

## Expected

Wrap in iframe should avoid errors

## Actual

Throw Error + Blank Screen

## Logs

The console log shows:

#### - First Error:

```
Uncaught TypeError: Cannot read property 'layout' of undefined
    at L.layout (layout.ts:1362)
    at web.main.ts:127
log.ts:197   ERR Cannot read property 'setViewVisible' of undefined: TypeError: Cannot read property 'setViewVisible' of undefined
    at L.onFullscreenChanged (https://hostname/static/41ad0c0c4c14df78e1bfa3a44d8b633ed2fc26e5/usr/lib/code-server/lib/vscode/out/vs/workbench/workbench.web.api.js:6696:596)
```

#### - Second Error:

```
ERR Failed to execute 'lock' on 'Keyboard': lock() must be called from a top-level browsing context.: Error: Failed to execute 'lock' on 'Keyboard': lock() must be called from a top-level browsing context.
    at https://hostname/static/41ad0c0c4c14df78e1bfa3a44d8b633ed2fc26e5/usr/lib/code-server/lib/vscode/out/vs/workbench/workbench.web.api.js:4401:938
```

## Screenshot

![image](https://user-images.githubusercontent.com/159167/122862380-9d50da00-d353-11eb-890a-5831a6b1ed8c.png)

## Notes

This issue can be reproduced in VS Code: No

**Comment by jsjoeio** [comment]
Hmm there may be some specific requirements when wrapping code-server in an iframe 🤔 I think @code-asher has worked with this in the past and may have some insight.

**Comment by code-asher** [comment]
I don't think we have any specific requirements. We run code-server
3.10.2 in an iframe without any issues.

I see you're using 3.8.1; does the problem persist with 3.10.2?

**Comment by futurist** [comment]
Tested in code-server `3.10.2`, also see a blank screen in the case, but the error thrown changed. Screenshot as below:

![image](https://user-images.githubusercontent.com/159167/123387945-e363a300-d5ca-11eb-8581-48a53f86257d.png)

**Comment by code-asher** [comment]
I was not able to reproduce.  I assume it is happening to you? 
What version of code-server and Chrome?

```
<iframe src="about:blank" width="100%" height="100%"></iframe> 
<script>setTimeout(() => document.querySelector("iframe").src = "http://localhost:8080", 5000)</script>
```

I used code-server 4.12.0 and Chromium 112.0.5615.165.
