### ISSUE TITLE
restored terminal from browser reload may append 2R0;276;0c some times

### ISSUE THREAD

**Issue by futurist** [coder/code-server#3657]
## OS/Web Information

- Web Browser: Chrome
- Local OS: MacOS 10.15
- Remote OS: Debian9
- Remote Architecture: x64
- `code-server --version`: 3.10.2

## Steps to Reproduce

1. Open Terminal
2. Run some random commands
3. Reload Tab, wait for terminal restore
4. The restored terminal may append `2R0;276;0c` some times.

## Expected

Terminal should keep as is when restored after a reload

## Actual

Sometimes there's some chars appeared in terminal.

## Screenshot

![image](https://user-images.githubusercontent.com/159167/123058275-3b6b9f80-d43b-11eb-83e7-6ebc4fa992dd.png)

## Notes

This issue can be reproduced in VS Code:No

**Comment by futurist** [comment]
Also observed that the chars will be appended continually in many terminals(even it's not in front focus) for every time tab refreshing, as below image:

![image](https://user-images.githubusercontent.com/159167/123069776-b33ec780-d445-11eb-923a-471868607372.png)

**Comment by futurist** [comment]
When using `dash` as shell, the extra chars will be below:

![image](https://user-images.githubusercontent.com/159167/123198357-8939e380-d4df-11eb-830e-879473638ccf.png)

**Comment by vapurrmaid** [comment]
Bump, I've noticed this (within the Coder product)

**Comment by icy-fish** [comment]
Just facing the same issue with code-server version 3.10.2, envirionment infomation on my side list below:

## OS/Web Information
- Web Browser: Chrome
- Local OS: Windows 10
- Remote OS: SUSE Linux Enterprise Server 12 SP5(Docker container)
- Remote Architecture: x64
- code-server --version: 3.10.2
## Steps to Reproduce
1. Open Terminal(tried bash, zsh)
2. Run any commands with output
3. Leave it alone for a while(about 10 minutes)
4. Reload window, wait for terminal restore
5. The restored terminal may append 2R0;276;0c some times.

This issue also happends on other code-server instances with different shell configs and environment variables, so I don't think it's a env specified issue.

**Comment by icy-fish** [comment]
Hi @vapurrmaid , it's there any suggestion for this issue? I found something relevant which points out that some extra may need be done with xterm.js:
- https://github.com/sagemathinc/cocalc/issues/1269
- https://github.com/sagemathinc/cocalc/issues/3277

But I'm not sure what code-server can do on this scenario, could you please take a look and confirm, thanks.

**Comment by scottmudge** [comment]
Any solutions to this? Not a super problematic issue to go up a line and erase the previous command, but it's quite annoying.

**Comment by scottmudge** [comment]
code-server: 3.10.2
vs code: 1.56.1

Unfortunately I am just a user of this deployment and do not admin rights to upgrade or deploy different services. Was hoping there might be a way to correct the issue from a configuration/user-space side of things.

**Comment by jsjoeio** [comment]
Hmm...that's pretty old. You might be able to play with terminal GPU rendering or something in the VS Code settings. I'm not sure what else would work unfortunately 😢

**Comment by jerch** [comment]
This happens, if the recorded terminal data contains requests, which the terminal will respond to (here DA2).

To fix that - replay first on the new terminal, then connect to the PTY. This way the responses get not sent again to the PTY.

**Comment by sunmingmei** [comment]
> This happens, if the recorded terminal data contains requests, which the terminal will respond to (here DA2).
> 
> To fix that - replay first on the new terminal, then connect to the PTY. This way the responses get not sent again to the PTY.

Have you solved it? How to do it? Looking forward to your reply

**Comment by jerch** [comment]
No I have not solved it, as I dont had the issue. I've posted here, because we got a similar question in the xterm.js repo.

**Comment by code-asher** [comment]
We are closing out old issues, but let me know if this is still an issue.  It seems unlikely to be in code-server though, all the replay logic is in VS Code core.
