### ISSUE TITLE
Not possible to develop VS Code Extensions in code-server

### ISSUE THREAD

**Issue by benz0li** [coder/code-server#3661]
## OS/Web Information

- Web Browser: Firefox 89.0.2 (64-bit)
- Local OS: macOS 10.14.6 (Mojave)
- Remote OS: [Debian buster](https://hub.docker.com/_/debian)
- Remote Architecture: 64-bit
- `code-server --version`: 3.10.2 387b12ef4ca404ffd39d84834e1f0776e9e3c005

## Steps to Reproduce

Follow the [Hello World guide](https://code.visualstudio.com/api/get-started/your-first-extension).

ℹ️ Node.js packages `yo` and `generator-code` are already installed.

## Expected

**Hello World** command being available at step

> Run the **Hello World** command from the Command Palette (`⇧⌘P`) in the new window:

## Actual

The **Hello World** command is not available.

## Logs

On demand only.
👉 Issue may be reproduced any time by @code-asher, @jsjoeio or @bpmct at https://vscode-r.jupyter.b-data.ch.

## Screenshot

None.

## Notes

This issue can be reproduced in VS Code: No

**Comment by code-asher** [comment]
Ah yeah there's some stuff around this we still need to implement.

Related: https://github.com/cdr/code-server/issues/2546

**Comment by benz0li** [comment]
Keeping the stale bot happy...

**Comment by code-asher** [comment]
We should definitely revisit this with 4.0 since it is based on
upstream's server and I think might actually have most if not all the
work done required to debug extensions.

**Comment by benz0li** [comment]
Retested with code-server v4.0.1 at https://vscode-r.jupyter.b-data.ch. I worked through the whole [Hello World guide](https://code.visualstudio.com/api/get-started/your-first-extension) without problems.

@code-asher It seems that developing VS Code Extensions in code-server is now possible. If you can confirm, you may close this issue.

## OS/Web Information

- Web Browser: Safari 14.1.2
- Local OS: macOS 10.14.6 (Mojave)
- Remote OS: [Debian buster](https://hub.docker.com/_/debian)
- Remote Architecture: 64-bit
- `code-server --version`: 4.0.1 735c6da829535969ff7193c79379299e4a1cb9bc

**Comment by benz0li** [comment]
Confirmed by https://github.com/coder/code-server/issues/2546

**Comment by code-asher** [comment]
This is awesome news.  Thank you for testing!
