### ISSUE TITLE
Opening large log files causes the IDE to stop responding

### ISSUE THREAD

**Issue by reaseno** [coder/code-server#3673]
Opening large log files (850MB is enough) causes the IDE to stop responding to some interactions. This includes the terminal or opening new files. Waited over 5 minutes, but IDE did not recover.

A workaround is to log out via the IDE menu. But sometimes the IDE tries to open the log file after log in again. Then it helps to either reset the IDE or to delete the log file from outside and log out again.

## OS/Web Information

- Web Browser: Vivaldi
- Local OS: Win10
- Remote OS: Linux (PHP docker container)
- Remote Architecture: 6 vCPU's, 24 GB RAM
- `code-server --version`: v3.10.0

## Steps to Reproduce

1. create big log/text file
2. open file
3. try to open other files

## Expected

Opening within 10sek and/or warning message because of big file loading only first xxMB.

## Actual

IDE tries to load all.

## Notes

Tried to load same file in visual studio code, which opens it within 10 sec.

This issue can be reproduced in VS Code: No

**Comment by jsjoeio** [comment]
Duplicate of https://github.com/cdr/code-server/issues/3097 and https://github.com/cdr/code-server/issues/2803

Please make sure to search for issues before opening new ones :) Thank you!

**Comment by reaseno** [comment]
I did. All the mentioned ones are different to mine.

#3097 is about Deleting / Uploading files <50MB which is a problem I don't have.
#2803 Is also about Uploading large files and a crash which I don't have.

For me it's about opening a large file on the server where the IDE is also running, within that IDE. So data and IDE are in the same place.

**Comment by jsjoeio** [comment]
Ah, my apologies. I am assuming it's the same underlying issue for all three, but maybe not. I'll reopen. Sorry for the confusion on my part and thank you for elaborating!
