### ISSUE TITLE
user-data-dir config does not expand ~ alias as user home

### ISSUE THREAD

**Issue by bdefore** [coder/code-server#3682]
## OS/Web Information

- Web Browser: Chrome
- Local OS: ChromeOS
- Remote OS: Manjaro
- Remote Architecture: Linux
- `code-server --version`: 3.10.2 387b12ef4ca404ffd39d84834e1f0776e9e3c005

## Steps to Reproduce

I'm trying to follow https://github.com/cdr/code-server/blob/main/docs/FAQ.md#how-can-i-reuse-my-vs-code-configuration. The instructions indicate that `~` can be used within the value. I am trying to point at my local `~/.config/Code` for shared settings.

Create in `~/.config/code-server/config.yaml`:

```
bind-addr: 0.0.0.0:8443
auth: password
password: REDACTED
cert: false
user-data-dir: ~/.config/Code
```

I am then running code-server via `systemctl start code-server@myusername.service`

## Expected

Code-server should run with shared settings of my ~/.config/Code directory

## Actual

When opening in client, a blank screen is shown.

If the `user-data-dir` in config.yml is instead replaced with the absolute path: `/home/myusername/.config/Code` it loads properly.

I cannot alternatively get this to work with `$HOME`.

This would be useful for code-server configs to be cross compatible between MacOS and Linux (where /home and /Users is often th differentiation).

## Logs

Note the 'Using user-data-dir' line where it does not appear to expand `~` as expected:

```
Jun 28 09:06:28 d4bequiet code-server[31942]: [2021-06-28T13:06:28.307Z] info  code-server 3.10.2 387b12ef4ca404ffd39d84834e1f0776e9e3c005
Jun 28 09:06:28 d4bequiet code-server[31942]: [2021-06-28T13:06:28.308Z] info  Using user-data-dir /~/.config/Code
Jun 28 09:06:28 d4bequiet code-server[31942]: [2021-06-28T13:06:28.316Z] info  Using config file ~/.config/code-server/config.yaml
Jun 28 09:06:28 d4bequiet code-server[31942]: [2021-06-28T13:06:28.316Z] info  HTTP server listening on http://0.0.0.0:8443
Jun 28 09:06:28 d4bequiet code-server[31942]: [2021-06-28T13:06:28.316Z] info    - Authentication is enabled
Jun 28 09:06:28 d4bequiet code-server[31942]: [2021-06-28T13:06:28.316Z] info      - Using password from ~/.config/code-server/config.yaml
Jun 28 09:06:28 d4bequiet code-server[31942]: [2021-06-28T13:06:28.316Z] info    - Not serving HTTPS
Jun 28 09:06:31 d4bequiet code-server[31942]: [2021-06-28T13:06:31.978Z] error vscode is not running Error: vscode is not running
Jun 28 09:06:31 d4bequiet code-server[31942]:     at VscodeProvider.send (/usr/lib/code-server/out/node/vscode.js:206:19)
Jun 28 09:06:31 d4bequiet code-server[31942]:     at VscodeProvider.<anonymous> (/usr/lib/code-server/out/node/vscode.js:198:30)
Jun 28 09:06:31 d4bequiet code-server[31942]:     at step (/usr/lib/code-server/out/node/vscode.js:63:23)
Jun 28 09:06:31 d4bequiet code-server[31942]:     at Object.next (/usr/lib/code-server/out/node/vscode.js:44:53)
Jun 28 09:06:31 d4bequiet code-server[31942]:     at fulfilled (/usr/lib/code-server/out/node/vscode.js:35:58)
Jun 28 09:06:31 d4bequiet code-server[31942]:     at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by jsjoeio** [comment]
Looking into this. 

### using an absolute path via command line

`code-server --user-data-dir /Users/jp/dev/repros/test-cs-settings` works as expected. 

![image](https://user-images.githubusercontent.com/3806031/123688453-ddf29c80-d806-11eb-8eb5-7aeb53e80d02.png)

### using path with $HOME via command line

(don't forget the quotes)
`code-server --user-data-dir "$HOME/dev/repros/test-cs-settings"` works as expected. 

![image](https://user-images.githubusercontent.com/3806031/123689594-3aa28700-d808-11eb-8e5e-4de2b75a6db3.png)

### using an absolute path via config file

```yaml
bind-addr: 127.0.0.1:8080
auth: password
password: <redacted>
cert: false
user-data-dir: /Users/jp/dev/repros/test-cs-settings
```

works as expected. 

![image](https://user-images.githubusercontent.com/3806031/123689877-98cf6a00-d808-11eb-956d-f1bf2b050287.png)

### using path with $HOME via config file

```yaml
bind-addr: 127.0.0.1:8080
auth: password
password: <redacted>
cert: false
user-data-dir: "$HOME/dev/repros/test-cs-settings"
```

does not work

![image](https://user-images.githubusercontent.com/3806031/123690411-3165ea00-d809-11eb-8ba2-38cfaae072e9.png)


@code-asher can you confirm this a bug? I would naturally expect this to work so I think it's a bug, but you would know better.

**Comment by jsjoeio** [comment]
Thanks for filing this bug @bdefore! I think this is a bug. I'll let the others weigh in but otherwise, I've added it to "On Deck" which means it will get worked on for an upcoming version.

**Comment by bdefore** [comment]
@jsjoeio appreciate your command line repro steps here, i should have done the same.

**Comment by jsjoeio** [comment]
No harm, no foul! Your issue was thorough enough (which doesn't always happen) so thank you for helping us get to the bottom of this so quickly.

**Comment by code-asher** [comment]
The shell expands tilde and environment variables but there's nothing in
the Node code that does the same.

Maybe we can call out to the shell so it can handle the expansions since
there will be many edge cases.

**Comment by bdefore** [comment]
keepalive
