### ISSUE TITLE
Getting “command ‘markdown.showPreviewToSide’ not found” error on iPad

### ISSUE THREAD

**Issue by jsjoeio** [coder/code-server#3686]
### Discussed in https://github.com/cdr/code-server/discussions/3671

<div type='discussions-op-text'>

<sup>Originally posted by **tim-rohrer** June 24, 2021</sup>
I’m running `code-server` in a Docker container. I’m getting the subject error when I connect from iPad (it worked once, but then wouldn’t work any more) and try to do a markdown preview. I’ve also tried using the preview extension with the same result.

I’ve updated the server to the latest version, but no luck. 

![IMG_0139](https://user-images.githubusercontent.com/7756865/123341609-7d641680-d50b-11eb-885d-cdcf5806841c.jpeg)

Is anyone getting a preview to work? What are some things I can try next?

Thanks.

</div>

**Comment by jsjoeio** [comment]
Interesting 🤔 I'm seeing a similar error on my iPad.

https://user-images.githubusercontent.com/3806031/123674972-125e5c80-d7f7-11eb-9a91-d2f70d230f2a.MP4

![IMG_0260](https://user-images.githubusercontent.com/3806031/123674991-18543d80-d7f7-11eb-8a39-af766c018125.PNG)

I'm not sure why this is happening. I'm going to convert this to an issue for tracking

**Comment by jsjoeio** [comment]
@tim-rohrer

As for next steps, here's what you could do:
- see if you can reproduce this on GitHub Codespaces. If you can, then it's an upstream issue and should be filed under microsoft/vscode

**Comment by tim-rohrer** [comment]
I’ve requested to join the beta.

**Comment by faisal-ijaz** [comment]
I also have this issue. Is there anything I can test or check?

**Comment by jsjoeio** [comment]
> I also have this issue. Is there anything I can test or check?

Thanks for asking! Do you have access to Codespaces? Or actually, can you test this by:
1. opening GitHub repo in Safari on iPad
2. Hit "." to open on github.dev
3. Command Palette > Open Markdown Preview to the Side

And maybe record a video and let us know what happens? If the error occurs, then we can file upstream

**Comment by tim-rohrer** [comment]
More recently, I’ve had limited use of my iPad to access a personal instance of `code-server` without experiencing this issue. I’ve been waiting to close this until I use the setup more.

@faisal-ijaz, I deployed `code-server` through a Docker container on a VPS, and am using the latest iPadOS.
