### ISSUE TITLE
Upgrade to 1.58

### ISSUE THREAD

**Issue by balajib-b** [coder/code-server#3775]
Upgrade to 1.58.2 - June 2021 release

**Comment by jsjoeio** [comment]
I spoke to @code-asher about this. We think we can upgrade straight to 1.59 (https://github.com/cdr/code-server/issues/3917).

**Comment by Explosion-Scratch** [comment]
> I spoke to @code-asher about this. We think we can upgrade straight to 1.59 (#3917).

Or 1.63 lol

**Comment by jsjoeio** [comment]
This will be resolved in the next release!

**Comment by jsjoeio** [comment]
> Awesome! Which version will VSCode be upgraded to by the way? (1.58 or 1.63?)

1.63 🎉
