### ISSUE TITLE
merge deploy-code-server examples into the code-server repo instead

### ISSUE THREAD

**Issue by bpmct** [coder/code-server#3807]
- [ ] move docs to code-server docs 
- [ ] create "app repos" for Heroku, Railway and other providers if needed (Heroku needs an app.json and Dockerfile in the root of the repo, Railway "forks" for the user)
- [ ] CI for special deploy image
- [ ] archive deploy-code-server repo

**Comment by jsjoeio** [comment]
This is a fantastic idea! Especially now that we have the docs hosted on Coder, I think it would be really nice to see these in the code-server docs. Let us know how we can help!

**Comment by bpmct** [comment]
going to focus on this next week. got sidetracked with some --link stuff

**Comment by jsjoeio** [comment]
@bpmct is this still something we want to do or no? I'll let you decide!

**Comment by bpmct** [comment]
I think we should archive for now :)
