### ISSUE TITLE
3.11 - Terminal not properly visible on iPad

### ISSUE THREAD

**Issue by asheswook** [coder/code-server#3824]
## OS/Web Information

- Web Browser: Safari 15
- Local OS: iPadOS 15 dev2
- Remote OS: Ubuntu 20.04.2 LTS
- Remote Architecture: Linux
- `code-server --version`: 3.11.0 4e8cd09ef0412dfc7b148b7639a692e20e4fd6dd

## Explanation
Terminal does not display normally. It only shows the color. Sometimes, when I refresh the web, it appears well. The setting values for VSCode are all default. Even if the screen doesn't appear, its process is going well. It's just that I can't see it. Also, Debug console works well.

## Screenshot
![C81484A8-6913-436A-BC60-43EBB8E6A573](https://user-images.githubusercontent.com/25760310/126360231-83cd9897-1e34-4e9e-a301-0551441bd347.jpeg)
![308860AC-AC93-4160-96E3-8A23F3370283](https://user-images.githubusercontent.com/25760310/126360248-ba1658f2-efa2-4e53-94eb-abbde0d192e1.jpeg)
![C4468FC1-75E3-4DD7-AF7B-1D92A41E9EF9](https://user-images.githubusercontent.com/25760310/126360249-82732efa-d14b-4d76-b91a-161ac0971f0f.jpeg)

**Comment by jsjoeio** [comment]
Hmm I have yet to run this on my iPad so I will have to check.

> Terminal does not display normally

Hard to tell from the photo exactly. How should it look?

**Comment by asheswook** [comment]
The letters printed on the terminal should be visible like this:
![20D6E72B-974D-442F-947F-34FF4E09A6FC](https://user-images.githubusercontent.com/25760310/126424687-79a0faf9-2529-4c0d-8908-6a165079cc3f.jpeg)

**Comment by asheswook** [comment]
https://user-images.githubusercontent.com/25760310/126425196-5e0cbe84-3d71-4169-a42b-f76b43e7929c.mov

**Comment by asheswook** [comment]
What I want is, unlike the second console, like the first console in the video, all consoles print content well.

**Comment by dhguswns23** [comment]
Same here. My workaround is to change default shell profile (in my case, bash to sh) then revert that change. But it is tiresome.

**Comment by jsjoeio** [comment]
Thanks for the screenshots! (the video won't play :( )

Good to know. We will look into this soon!

**Comment by AjRic07** [comment]
After long tinkering around, i found a solution. Type in "Terminal" in the settings tab, scroll down until you see gpu acceleration and turn it off. Didn't have a problem with the terminal not displaying since.

**Comment by jsjoeio** [comment]
Awesome to hear there's a solution! Thank you @AjRic07 for posting that!

**Comment by bpmct** [comment]
A video of the workaround. Thanks @AjRic07 for discovering this:

https://user-images.githubusercontent.com/22407953/135088697-fe0d55df-c072-4203-91bc-983d040aaade.mp4

**Comment by ykazakov** [comment]
I have the same problem in Safari 15.0 under MacOS 11.6. 
The workaround for disabling GPU acceleration works as well.
