### ISSUE TITLE
Terminal characters replaced when going back with cursor

### ISSUE THREAD

**Issue by iFrozenPhoenix** [coder/code-server#3828]
## OS/Web Information

- Web Browser: Microsoft Edge Version 91.0.864.70
- Local OS: Windows 10 20.04
- Remote OS: Debian 10
- Remote Architecture: x86
- `code-server --version`: 3.10.2 387b12ef4ca404ffd39d84834e1f0776e9e3c005

## Steps to Reproduce

1. Type a command (a litte bit longer) and execute
2. Arrow up to use last command from bash history
3. Go back with the cursor (using left arrow key; holding it)
4. Sometimes the terminal is overwritten as seen

It's also possible to reconstruct the issue while writing a long command and then going back to the start to change something.

Issue is reproduceable for me on different systems,

## Expected

The terminal does not replace characters, just from going back to the beginning of the command.

## Actual

The terminal line changes and replaces character (Just visually, if the command is executed, the text is still the same)

It seems that it has something to do with rendering, because if the browser is zoomed in and out the text is reset to the correct output.
## Screenshot

![image](https://user-images.githubusercontent.com/36128722/126461826-012c37cb-c7a8-4455-8629-e19beb256d0f.png)

## Notes

This issue can be reproduced in VS Code: No

**Comment by iFrozenPhoenix** [comment]
Could this problem eventually be caused by the setting "Local echo latency threshold"?
After deactivating it (Setting to -1) the problem does not seem to appear again.

**Comment by jsjoeio** [comment]
We'll have to look closer into this. Thanks for the thorough bug report!

> Local echo latency threshold

Hmm... I'm not familiar with this setting. Where is this? Inside your VSCode Settings?

**Comment by iFrozenPhoenix** [comment]
It's in the terminal settings.
The corresponding variable value is terminal.integrated.localEchoLatencyThreshold

![image](https://user-images.githubusercontent.com/36128722/126543216-8ca2717c-150a-4b34-b7d1-369f486eeb8f.png)

**Comment by jsjoeio** [comment]
Interesting...I don't think we would have changed that in code-server but there's a chance we did for some reason, or it was a mistake. At least now we know what to look into. Thanks for the screenshot and pointing that out!
