### ISSUE TITLE
Add support for Window Controls Overlay

### ISSUE THREAD

**Issue by mmischitelli** [coder/code-server#3884]
Ciao,
it would be nice to have support for window controls overlay: https://web.dev/window-controls-overlay/

When installing the webapp with MS Edge, for example, it would be possible to hide the title bar above the menu bar, thus making almost indistinguishable from the real vscode installed locally on your computer.

**Comment by jsjoeio** [comment]
Ooo, this is a great idea. Thanks for the link too. Doesn't look like it could be terribly difficult to implement either. 

Looks like this is still in beta or under development though?

![image](https://user-images.githubusercontent.com/3806031/127897196-37f1d24d-614d-4db0-8a37-e4cf73ecb24e.png)

![image](https://user-images.githubusercontent.com/3806031/127897147-ff423842-ea5e-41ac-8fa6-34bb51af44a5.png)

**Comment by mmischitelli** [comment]
From what I was able to understand, official support is going live with the Edge version 93 (next one). It's already possible to enable it via flags.

**Comment by reillyeon** [comment]
The Window Controls Overlay feature is being enabled by default in Chrome 104. Please consider re-opening this issue.

**Comment by reillyeon** [comment]
I think you need to remove the stale tag to prevent the bot from closing the issue again.

**Comment by danieltl** [comment]
Any plan with this in near feature?

With the latest release with v4.17.0 (Code 1.82), [Command Center now on by default](https://code.visualstudio.com/updates/v1_82#_command-center-now-on-by-default).

And with the chrome PWA apps installed, it will show the command center as belows.
![image](https://github.com/coder/code-server/assets/11782220/1a7f23ca-1f8b-4520-bb36-98bd8c5e2e2f)

Just thought if those upper two layer (title bar, command center) can be merged into one, it would be wonderful.

**Comment by code-asher** [comment]
No plans at the moment, but happy to accept a PR tackling this.
