### ISSUE TITLE
Extension details takes a long time to load when using code-server --link

### ISSUE THREAD

**Issue by facundomedica** [coder/code-server#3889]
## OS/Web Information

- Web Browser: Brave Browser or Safari
- Local OS: MacOs Big Sur
- Remote OS: Ubuntu 20.04.2 LTS (running on GCP with around 80ms of ping to the server)
- Remote Architecture: x86_64
- `code-server --version`: `3.11.0 4e8cd09ef0412dfc7b148b7639a692e20e4fd6dd`

## Steps to Reproduce

1. Go to extensions and search for an extension
2. Click on any extension
3. Wait

## Expected

The extension should load in a sensible amount of time.

## Actual

Takes around 7s every time you click an extension.

## Logs

Screenshot from the network tab:
<img width="489" alt="Screen Shot 2021-08-01 at 20 47 30" src="https://user-images.githubusercontent.com/14063057/127782137-21660270-a31d-4330-868d-52827b877145.png">

Screenshot from browser's console:
<img width="1028" alt="Screen Shot 2021-08-01 at 21 04 33" src="https://user-images.githubusercontent.com/14063057/127782484-750f5275-4653-4d3d-ba96-6480a33659b4.png">

Running `code-server --link -vvv` didn't produce any helpful logs while clicking around in the extensions tab.

## Notes

When restarting the server sometimes it shows a blank screen for quite some minutes until it shows anything.

Sometimes I get:

```
Error while parsing the 'sandbox' attribute: 'allow-downloads' is an invalid sandbox flag.
```

This issue can be reproduced in VS Code: No

Extensions load in under 0.5s-ish in VS Code.

**Comment by jsjoeio** [comment]
Hmm 🤔 I wonder if this is related to an issue we introduced with the service worker registration in 3.11.

Running `code-server --link` locally on my macOS, I didn't experience much latency (for obvious reasons I guess). 

Where is your GCP server running in comparison to where you are access your code-server instance?

**Comment by facundomedica** [comment]
(Sorry for the messy writing, I was taking notes here while testing 😅)
I've read about those issues so I downgraded to 3.9.3, but made no difference.
I'm located in Sicily (southern Italy) and the server is running in Frankfurt (europe-west-3). According to gcping.com there's around 81ms of ping to the region which is more or less what I get if I ping the server from the terminal.

Running it locally in my MacOS also has the same delay, which would indicate a network issue on my side? But everything in the code editor works blazingly fast (and outside of the editor too, like web browsing, downloading stuff, watching youtube). Is this something I can measure?

**If I run version 3.9.3 with Docker WITHOUT --link, the extensions' details load up right away.**
**If I run version 3.11.0 with Docker WITHOUT --link, the extensions' details do NOT load, like never.**

Here's a short video of the issue running it locally on my Macbook with --link (3.11 this time, couldn't get it to install an older version, even with the install.sh --version flag). >15s to load is not something I'm used to in this network connection, to be clear

Other notes:

On GCP: `Detected an acceptable latency of 5ms`
On local: `Detected an acceptable latency of 76ms`

https://user-images.githubusercontent.com/14063057/127902848-e73f2e6d-8aba-4032-b171-81b5c003bb47.mov

**Comment by facundomedica** [comment]
As a side note, the preview function of a couple of Markdown extensions that I've tried are super slow too. Might be related? So it's all a webview issue?

**Comment by jsjoeio** [comment]
Thanks for the detailed notes! Super helpful. Hmm... I've been noticing webview issues in 3.11 too. Wonder if it's related. cc @code-asher in case he has any ideas

**Comment by code-asher** [comment]
The details not loading could certainly be the recent issues we've been debugging. I am not sure about the delay though. I think the extension details are loaded by the browser by querying the marketplace directly so they shouldn't depend on server latency. It's possible that accessing our marketplace is slow (https://extensions.coder.com/).

**Comment by code-asher** [comment]
Although if the markdown preview is also slow that could indicate something else since that doesn't touch the marketplace of course.

**Comment by facundomedica** [comment]
@code-asher lmk if I can do any extra testing there, happy to help 😄 I'm using it as my daily code editor for work, I don't have a real need for it other than that I think it's super cool 😆

**Comment by code-asher** [comment]
Thanks for the help! <3

If the difference is between 3.9.3 and 3.11.0 it might be on account of
the service worker so that's likely where we should start looking.
Previously the requests would have been made via HTTP but now they are
made through the web socket.

**Comment by facundomedica** [comment]
I've updated to 3.12 and there's no improvement 😢

**Comment by jsjoeio** [comment]
Thanks for the report! Tackling other things right now but hoping to get to it soon!
