### ISSUE TITLE
Project Manager for Java Not Working/Appearing in Explorer

### ISSUE THREAD

**Issue by xCJPECKOVERx** [coder/code-server#3897]
On a new install of CodeServer, the Java Project Manager view does not appear. I've tested on both official docker release and the LinuxServer release.
I've ensured the JDK is available and set up using the "java.home" setting and have tested both versions 11 and 14, just to be sure.

## OS/Web Information

- Web Browser: Chrome
- Local OS: Windows 10
- Remote OS: Linux(Unraid) - Docker
- Remote Architecture: x64
- `code-server --version`: 3.11.0 4e8cd09ef0412dfc7b148b7639a692e20e4fd6dd

## Steps to Reproduce

1. Deploy new docker container
2. Copy a Java installation to a known location available to the container, and configure the java path in CodeServer
2. Install Java Extension Pack
3. Install Spring Initializr Java Support
4. Create new project using initializr
5. Open the main java file

## Expected

Java Project Explorer should appear in the side bar and list the java project (this happens on vanilla VS Code)

## Actual

Java welcome page comes up, but the Java Project Explorer does not appear

## Notes

This issue can be reproduced in VS Code: No

**Comment by xCJPECKOVERx** [comment]
I think the only prerequisite is making sure the Java sdk is available and that Code Server knows about it (via the "java.home" setting or $JAVA_HOME environment variable).

Using the Spring Initializr extension is just a quick way to bootstrap a runnable Java project. I started with "Spring Initializr: Create a Maven Project..." then just used the defaults for each step.

**Comment by balajib-b** [comment]
@xCJPECKOVERx the java project usign spring initializer will ask you to choose many options before creating projects. Hope you have done it well.
The new project should get opened on a new window as per my machines (i use code server on 4 remote machines with different linux flavours). i suspect that your browser is not allowing pop-up new window, requesting you to check the same.

**Comment by xCJPECKOVERx** [comment]
@balajib-b I checked and have disabled popups, but the Java Project Manager is still missing. When I create the project using Initializr, I've used the defaults for everything except the Java version: Maven, 2.5.3, Java, com.example, demo, jar, 16, 0 dependencies, default location.
Upon completion I receive the popup for adding the project to the workspace, however the Java Projects collapse is not visible in the Explorer.

To note, I am still able to run the project. The issue is just that the Project Manager for Java extension seems to not be running.

**Comment by sohamindellient** [comment]
I am having this same issue, is there an update on this?

**Comment by xCJPECKOVERx** [comment]
I haven't used CS in some time, but just checked back and the Java Project Manager showed up after a reinstall of the plugin. No clue what triggered it to begin working now...
It's possible it requires a projects folder with no other project types in it besides java? For example, I just tested creating a new project inside a 'Java Projects' folder, opened that folder in the workspace, and it works correctly now.
According to docker I'm on v3.12 of CS.

Sorry I can't be of more help, since I'm not sure what changed to make the Project Manager start working.

**Comment by sohamindellient** [comment]
I tried reinstalling the extension and installing a previous version both didn't work. Could try to retrace your steps?
