### ISSUE TITLE
Way to "close" terminal session with "close folder"

### ISSUE THREAD

**Issue by geiseri** [coder/code-server#3947]
## OS/Web Information

- code-server: v3.11.1
- VS Code: v1.57.1
- Commit: c680aae973d83583e4a73dc0c422f44021f0140e
- Date: 2021-08-06T18:33:37Z
- Browser: Mozilla/5.0 (X11; CrOS x86_64 13982.69.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.130 - Safari/537.36

## Steps to Reproduce

1. Open folder from the menu
2. Mess around with files, terminals stuff...
3. Close folder from the menu

## Expected

All state is cleared from the project.  Terminal ptys released, extensions unloaded, etc.

## Actual

"Session" is still running:
![image](https://user-images.githubusercontent.com/2265693/128875082-54e14470-630e-4d09-bb14-bef01ff6a98e.png)

## Notes

It used to be that state was lost on close, so the current behavior is orders of magnitude more usable.  I think I am seeing a strangeness related to PR #2723.  Code server is a bit different from VS Code in that there is a difference between the window being closed, and the folder is closed.  Since it's a server it could be the browser crashed.  Would it be possible to tease those apart?  That being said, if that is too invasive I can live with needing to close the shell manually vs having my terminal lost when Amtrak's wifi flakes out. =)

This issue can be reproduced in VS Code: No

**Comment by jsjoeio** [comment]
cc @code-asher who is more familiar with this part of code-server

**Comment by code-asher** [comment]
Ahhhh yeah when we close the folder it makes sense to me that we should
close the associated terminal sessions.

When we get the close request we should hit up the terminal provider and
ask it to close its sessions for the workspace/folder that was just
closed.
