### ISSUE TITLE
Create folder when adding folder to workspace

### ISSUE THREAD

**Issue by DeadlySurgeon** [coder/code-server#3968]
When in a workspace, and you right click and select "Add Folder to Workspace", the drop down to select a folder has no way to create folders, so you have to create it first outside of code-server, usually by using the terminal. While it really isn't too much of an issue to drop down into a terminal and just run `mkdir <path>`, it would be nice to have some kind of way to create folders as you're adding them, as does regular VSCode since it opens up a File Browser Dialog native to the OS. Maybe a file browser component should be created and added to help with navigation and file management, or the existing "Add Folder to Workspace" just needs to be tweeked?

**Comment by jsjoeio** [comment]
Hmm...to make sure we fully understand what you mean, do you mind posting a video showing it working in VS Code and also a video showing how it currently works in code-server? That would help a lot.

**Comment by DeadlySurgeon** [comment]
I can later this week, yeah.

**Comment by DeadlySurgeon** [comment]
![image](https://user-images.githubusercontent.com/60354262/134366673-7c3e66af-7834-4a74-909a-d4a1f6b9fb53.png)

I know I said later this week, but life hit me like a truck. 

So with my instance, I don't have the folder `~/rust`. When I type out `/home/surgeon/rust` and press enter, instead of creating this directory, it will complain that it doesn't exist. To create this directory on the remote instance, I'll need to go into a terminal to run `mkdir` on it. What if it instead had a dialog that said something on the lines of `The path ${path} doesn't exist, would you like to create it [ yes | no ]`, and if possible, where `${path}` is the parts of the directory that exist would be in green while the parts that don't would be in red so you know what folders it would be creating:

<details>
  <summary>Color Example</summary>

(obviously there would be a button or something in place of `[ yes | no ]`

![image](https://user-images.githubusercontent.com/60354262/134368839-8f09eb5d-7031-47df-9038-15beb52951d6.png)

</details>

**Comment by jsjoeio** [comment]
OH! Okay, now I understand what you mean. That would be great!

I'm going to add this to the Backlog.
