### ISSUE TITLE
Proxy domain label's type should be checked, or may cause too many redirects

### ISSUE THREAD

**Issue by codinggirl** [coder/code-server#3982]
## OS/Web Information

- Web Browser: Chrome 92.0.4515.131
- Local OS: Window 10 
- Remote OS: Debian 10
- Remote Architecture: AMD64
- `code-server --version`: 3.11.1 c680aae973d83583e4a73dc0c422f44021f0140e

## Steps to Reproduce

1. edit `~/.config/code-server/config.yaml`, add line `proxy-domain: rosa.webdash.fun`
2. visit code-server with domain `code.rosa.webdash.fun`, and port access domain `3000.rosa.webdash.fun`
3. after login,  `code.rosa.webdash.fun` maybe redirect too many times, according web server config.

## Expected

visit `code.rosa.webdash.fun`, show a normal editor.
visit `<port>.rosa.webdash.fun` like `3000.rosa.webdash.fun` proxy to a backend port.

I expected to use same level sub domains to visit both port-proxied service and editor.

## Actual

visit `<port>.rosa.webdash.fun`, work as expected.

vist `code.rosa.webdash.fun`,
- located to `https://code.rosa.webdash.fun/:code/`,
- then located to `https://code.rosa.webdash.fun/:code/:code`,
- then located to `https://code.rosa.webdash.fun/:code/:code/:code`,
- ...

## Logs

omitted, see notes.

## Screenshot

omitted, see notes.

## Notes

This issue can be reproduced in VS Code: No

This issue is not ralated with vanilla VS Code.

I need use subdomain as both proxy domain and code-server's home domain. After reading the source code, the code-server do NOT check the port is a number or not, just proxy it to back-end lib `node-http-proxy`.

Sadly, `node-http-proxy` use a buggy and deprecated function `require('url').parse` to parse the url, so requested url `https://code.rosa.webdash.fun`, will proxy to `http://0.0.0.0:code/`, it's a bad/illegal url, but will parse to:

```
Url {
  protocol: 'http:',
  slashes: true,
  auth: null,
  host: '0.0.0.0',
  port: null,
  hostname: '0.0.0.0',        
  hash: null,
  search: null,
  query: null,
  pathname: '/:code',
  path: '/:code',
  href: 'http://0.0.0.0/:code'
}
```

If upstream server is configured redirect from http to https, the web browser will follow again and again.

Conclusion:
- `<PORT-NUMBER>.<PROXY-DOMAIN>` or `<NOT-A-NUMBER>.<PROXY-DOMAIN> used, it's better check if the first label is a number or not, if it's a number and in the port range (1-65535)，proxy it, or use as a normal editor route.
- If the `code-server` consider a proxy domain should be used as proxy only, and should use another domain for editor access, please update the docs, illustrate this.

**Comment by jsjoeio** [comment]
Wow! Thank you for digging into the source code and providing your notes. I am not as familiar with our proxy, but it seems like two things could come out of this:
- fix this in the proxy
- update docs to illustrate this

cc @code-asher

**Comment by code-asher** [comment]
I think checking if the port is valid before trying to proxy is a good
move. I am not sure if we should just skip the proxy in this case or
show an error page with something like "code is not a valid port
number". I think we will want the latter because in the future we may
want to allow users to add string-based aliases for ports.
