### ISSUE TITLE
Apply exponential backoff to code-server reconnection

### ISSUE THREAD

**Issue by jawnsy** [coder/code-server#3985]
# Current behavior

When code-server loses the connection to the server, it attempts to re-connect at 30 second intervals repeatedly until the connection succeeds. If there is a large-scale event causing an outage while clients have code-server open, then this can cause repeated spikes in traffic on the server.

## Steps to reproduce

1. Open VSCode via master.cdr.dev
1. Rebuild your environment while VSCode is open

While the environment is rebuilding, we just see this message every 30 seconds, counting down to zero and then restarting back at 30 seconds:

![image](https://user-images.githubusercontent.com/52710/129453205-aa9b3fdf-82e7-4d19-a41f-446655fd22cf.png)

# Proposed solution

We should consider applying a [randomized exponential backoff](https://en.wikipedia.org/wiki/Exponential_backoff#Example_exponential_backoff_algorithm) scheme (e.g. try to reconnect in 10 seconds, then 20 seconds, then 40 seconds) to avoid coordinated events of large-scale deployments (hundreds or thousands of clients) hammering the server by attempting to reconnect at approximately the same time. This also allows us to begin with much smaller intervals to begin with (e.g. 5 seconds) making the reconnection much faster in the common case of a transient network issue.

**Comment by jsjoeio** [comment]
Seems like a valid point! Though I would imagine this behavior is from VS Code and not specific to code-server - though I hope @code-asher will correct me if that's wrong.

**Comment by code-asher** [comment]
Yup it is from VS Code, maybe it's something we could patch upstream!

But we've patched this connection logic locally before (those changes
have since been removed since they were added upstream) so it wouldn't
be a first haha.
