### ISSUE TITLE
ERR_SOCKET_NOT_CONNECTED

### ISSUE THREAD

**Issue by Nefcanto** [coder/code-server#4021]
## OS/Web Information

- Web Browser: Google Chrome | 92.0.4515.131 (Official Build) (64-bit)
- Local OS: Ubuntu 20.04 focal LTS
- Remote OS: docker, ubuntu:latest
- Remote Architecture: x64
- `code-server --version`: I used your installation script. I don't know

## Steps to Reproduce

1. Create this `Dockerfile`
```
FROM ubuntu:latest

RUN apt update && apt install curl -y

RUN curl -fsSL https://code-server.dev/install.sh | sh
```
2. Then create this `docker-compose.yml` file
```
version: "3.9"
services: 
  code-server:
    image: code-server:latest
    ports: 
      - 8080:8080
    command: code-server
```
3. Then run it using `docker-compose up`

Then go to `localhost:8080` or `127.0.0.1:8080` and you see this error:

> This site can’t be reachedThe webpage at http://localhost:8080/ might be temporarily down or it may have moved permanently to a new web address.
ERR_SOCKET_NOT_CONNECTED

## Expected

After running `code-server` and exposing its port to the host OS, we should be able to load VS Code inside browser using `localhost:8080`

## Actual

When I go to `localhost:8080` or `127.0.0.1:8080` I see this error:

> This site can’t be reachedThe webpage at http://localhost:8080/ might be temporarily down or it may have moved permanently to a new web address.
ERR_SOCKET_NOT_CONNECTED

## Logs

I changed the `command` in my `docker-compose.yml` to `code-server --log trace` and `code-server --log debug`, but these files are empty inside docker container:

`~/.local/share/code-server/coder-logs/code-server-stderr.log`
`~/.local/share/code-server/coder-logs/code-server-stdout.log`

However, by using `--log trace` I get this log when running `docker-compose up`:

> Recreating codeserver_code-server_1 ... done
Attaching to codeserver_code-server_1
code-server_1  | [2021-08-24T06:14:00.127Z] info  Wrote default config file to ~/.config/code-server/config.yaml
code-server_1  | [2021-08-24T06:14:00.615Z] trace child:25 got message {"message":{"type":"handshake","args":{"_":[],"bind-addr":"127.0.0.1:8080","auth":"password","password":"0531f1e72305a827d5d1b395","config":"/root/.config/code-server/config.yaml","log":"trace","user-data-dir":"/root/.local/share/code-server","extensions-dir":"/root/.local/share/code-server/extensions","verbose":true,"host":"127.0.0.1","port":8080,"proxy-domain":[],"usingEnvPassword":false,"usingEnvHashedPassword":false}}}
code-server_1  | [2021-08-24T06:14:00.618Z] info  code-server 3.11.1 c680aae973d83583e4a73dc0c422f44021f0140e
code-server_1  | [2021-08-24T06:14:00.618Z] info  Using user-data-dir ~/.local/share/code-server
code-server_1  | [2021-08-24T06:14:00.619Z] trace Using extensions-dir ~/.local/share/code-server/extensions
code-server_1  | [2021-08-24T06:14:00.637Z] info  Using config file ~/.config/code-server/config.yaml
code-server_1  | [2021-08-24T06:14:00.637Z] info  HTTP server listening on http://127.0.0.1:8080 
code-server_1  | [2021-08-24T06:14:00.637Z] info    - Authentication is enabled
code-server_1  | [2021-08-24T06:14:00.638Z] info      - Using password from ~/.config/code-server/config.yaml
code-server_1  | [2021-08-24T06:14:00.638Z] info    - Not serving HTTPS 

## Screenshot

VS Code is not launched, thus no screenshot.

## Notes

This issue can be reproduced in VS Code: No

**Comment by jsjoeio** [comment]
Hmm 🤔 I'm not sure on this one. cc @code-asher
