### ISSUE TITLE
Patch VS Code to persist terminals indefinitely

### ISSUE THREAD

**Issue by jsjoeio** [coder/code-server#4086]
> I think terminals are shut down once the connection is closed after a short period of time. Something like 60 seconds. We could patch VS Code to persist them indefinitely.

—@code-asher 

> Yes! I think that is the issue, I can test it but I am pretty sure it is 60 seconds before the timeout. If you could do that it would be great! I really appreciate it!

—@alexaptib

Inspired by Discussion: https://github.com/cdr/code-server/discussions/4081

**Comment by andrewsali** [comment]
This would be really great to run long-running computations via code-server.

**Comment by code-asher** [comment]
In the meantime a workaround would be to use something like screen or tmux.

**Comment by alexaptib** [comment]
Yeah, that it what I have been doing, but it requieres my laptop to be turned on and connected to the internet at all times, so it isn't so practical for leaving code running on the code-server independently from a computer. It would be great to be able to leave the code running on coder-server without my computer being needed as well.
