### ISSUE TITLE
markdown preview is not working

### ISSUE THREAD

**Issue by lixiepeng** [coder/code-server#4101]
```
/webview/main.js:115 Uncaught (in promise) Error: Service Workers are not enabled in browser. Webviews will not work.
/webview/main.js:115 Uncaught (in promise) TypeError: Cannot read property 'addEventListener' of undefined
```

**Comment by jsjoeio** [comment]
Possibly related to https://github.com/cdr/code-server/issues/3826

**Comment by spouradrix** [comment]
If that can help somebody, I noticed that although it doesn't work on Firefox (linux), it works on my Ipad.

**Comment by jgsun** [comment]
Dear all,

do we have any update?

**Comment by spouradrix** [comment]
Hey I think I tracked down the issue somehow. I have code-server behind a Nginx reverse proxy and I needed to had this to my server block:

`proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
`
Now it works perfectly on my tablet and laptop.

**Comment by jsjoeio** [comment]
Nice work @spouradrix! I'll see if we can investigate this on our side in the upcoming release.

**Comment by joole** [comment]
I found 3.10 - the latest version that all has the same problem,
If you use 127.0.0.1 to access code-server page all the webview ok which like tabnine, platformio,eg
If you use real-ip like 192.168.x.x to access code-server page, all the webview is blanked screen

**Comment by jsjoeio** [comment]
@joole I don't think real-ips use https, do they? That means the service workers won't work which explains the blank webviews
