### ISSUE TITLE
Token based access like jupyterlab

### ISSUE THREAD

**Issue by csniper-patrick** [coder/code-server#4102]
Is it possible to add a token based access method like jupyter, so that we can access the IDE directly by putting a long access token on the as a parameter in the url? 
ie. Opening a code-server listening at port 3000, and somehow we set a token. let say abc123456
and then maybe https://code-server.somewhere.com:3000/?token=abc123456 will bring you directly to the IDE instead of the password page.

Thanks a lot!

**Comment by jsjoeio** [comment]
@code-asher thoughts on this? Maybe something that would use our plugin API? See here: https://github.com/cdr/code-server/discussions/4072

**Comment by code-asher** [comment]
Yeah, this seems like a great candidate for the plugin API.
