### ISSUE TITLE
Status bar bug in chrome-android

### ISSUE THREAD

**Issue by amiria703** [coder/code-server#4133]
## OS/Web Information

- Web Browser: Google Chrome 93.0.4577.62 (Official Build) (32-bit)
- Local OS: Google Android 11 (Termux)
- Remote OS: Google Android 11
- Remote Architecture: arm32
- `code-server --version`: 3.11.1 acb5de66b71a3f8f1cc065df4633ecd3f9788d46

## Steps to Reproduce

1.Open code-server in termux
2.Open link in chrome and add it to home screen
3.Open it through the shortcut

## Expected

Work

## Actual

Status bar plays and goes hidden and then come back
So, cannot close tabs or simply type something
## Screenshot

![ezgif com-gif-maker](https://user-images.githubusercontent.com/54179379/132822056-b2857f99-d012-48fb-9180-e4c292b9474b.gif)

## Notes

This issue can be reproduced in VS Code: No

**Comment by jsjoeio** [comment]
I just tested this on my Pixel 2 and ran into another issue where I could log in but the screen was blank. This was on 3.9.3. 

## Video

https://user-images.githubusercontent.com/3806031/132893055-1f15e797-54f8-48f2-8461-64a81311f246.mp4

I'm currently upgrading to 3.11.1 so I can test that after.

**Comment by jsjoeio** [comment]
Argh. I downloaded 3.11.1 and I'm getting the 500 error.

Apologies. I'm going to have to dedicate some time looking more into this in the next version milestone.

![Screenshot_20210913-110414](https://user-images.githubusercontent.com/3806031/133134370-6fefa880-9aba-4a58-a19c-2fc0c0b6ff4e.png)

**Comment by amiria703** [comment]
@jsjoeio Any updates?

**Comment by jsjoeio** [comment]
No, no update unfortunately. This is lower priority and haven't had time to investigate. In the meantime, you might be interested in checking out [this PR](https://github.com/cdr/code-server/pull/4536). A community member added docs for getting code-server to work on Android 100% of the time (supposedly)

**Comment by amiria703** [comment]
Thanks for your reply! ❤️
Maybe, I should investigate it whenever I have free time

**Comment by jsjoeio** [comment]
> Maybe, I should investigate it whenever I have free time
That would be super helpful ♥️

> By the way, I'll test and report everything happens
You rock! Thank you for offering to help with that!
