### ISSUE TITLE
Bug feedback

### ISSUE THREAD

**Issue by XRSec** [coder/code-server#4140]
I've pointed out the problem on [my blog. ](https://blog.zygd.site/Online%20Config%20VS%20Code.html#Bug)

### [PWA](https://developer.mozilla.org/en-US/docs/Web/Progressive_wen_apps) online Configure PWA softwareization for code

- Maybe it's my configuration problem
- Bash is called in the code interface, and the ESC key cannot be input in vim
- There is an intermittent cache problem in `PWA` application mode. The display is abnormal and there is no content
- The plug-in `PHP debug` cannot be used correctly in `php5.6`

![image](https://user-images.githubusercontent.com/73819467/132954975-b45244ec-58ed-4946-8cb4-d1d8a01d748c.png)

**Comment by jsjoeio** [comment]
Hi @XRSec - do you mind opening a [proper bug report](https://github.com/cdr/code-server/issues/new?assignees=&labels=&template=bug-report.md&title=) for the PWA issue so that we can reproduce and troubleshoot?

Thanks so much!
