### ISSUE TITLE
armv7l builds for --link

### ISSUE THREAD

**Issue by immjs** [coder/code-server#4143]
## OS/Web Information

- Web Browser:(irrelevant)
- Local OS:(irrelevant)
- Remote OS:Raspbian (Debian 10)
- Remote Architecture:armv7l
- `code-server --version`:3.11.1

## Steps to Reproduce

1.install code-server
2.run `code-server --link`

## Expected

Give me a link which links my machine to cdr.co's servers.

## Actual

404 when trying to download the file that makes it happen

## Logs

```
[2021-09-11T20:49:35.234Z] info  code-server 3.11.1 acb5de66b71a3f8f1cc065df4633ecd3f9788d46
[2021-09-11T20:49:35.246Z] info  Using user-data-dir ~/.local/share/code-server
[2021-09-11T20:49:35.357Z] info  Using config file ~/.config/code-server/config.yaml
[2021-09-11T20:49:35.358Z] info  HTTP server listening on http://127.0.0.1:40505 (randomized by --link)
[2021-09-11T20:49:35.359Z] info    - Authentication is disabled (disabled by --link)
[2021-09-11T20:49:35.360Z] info    - Not serving HTTPS (disabled by --link)
[2021-09-11T20:49:35.363Z] debug running agent with bind,--code-server-addr=127.0.0.1:40505,
[2021-09-11T20:49:35.411Z] error spawn /home/pi/.nvm/versions/node/v14.17.6/lib/node_modules/code-server/lib/coder-cloud-agent ENOENT
[2021-09-11T20:49:35.417Z] debug child:4758 disposing {}
```

## Notes

It would look like a deliberate move but i don't see the purpose.

This issue can be reproduced in VS Code: Yes/**No**

**Comment by jsjoeio** [comment]
I just tested locally and cannot reproduce.

![image](https://user-images.githubusercontent.com/3806031/133126301-36ecca90-8842-4095-ac1c-92d57d22fc81.png)

![image](https://user-images.githubusercontent.com/3806031/133126214-03cdb06c-709b-40a3-94f9-26c759b74096.png)

`--link` is actually in the middle of a big refactor though and we're going to be beta testing some new features. If you're interested, let us know!

cc @kylecarbs

**Comment by informathemusic** [comment]
Oh alright. although ive only installed it so recently..

**Comment by jsjoeio** [comment]
@bpmct might be able to help you!

**Comment by bpmct** [comment]
The problem is the current --link agent is not built for the Raspberry Pi. 

We are working on a new version of Link and will make sure we make armv7l builds. We aim on sharing this by Friday and will be sure to let you know :)

In the meantime, you could try and [build the binary yourself](https://github.com/cdr/cloud-agent) and put it in `/home/pi/.nvm/versions/node/v14.17.6/lib/node_modules/code-server/lib/coder-cloud-agent`

**Comment by informathemusic** [comment]
This sounds good, tyvm!

**Comment by informathemusic** [comment]
Although now, `go build` builds without a version number. Now I get
```
[2021-09-15T06:16:24.384Z] info  Failed to login: unable to login: Agent version () is incompatible. Version v0.2.1 or later is required. Try updating to the latest release at https://github.com/cdr/code-server/releases
```

**Comment by bpmct** [comment]
Ah! I can't remember if you have to specify v0.2.1 or 0.2.1, but you'll need to build with this flag.

```sh
go build -ldflags "-X go.coder.com/cloud-agent/internal/version.Version=v0.2.1"
# or
go build -ldflags "-X go.coder.com/cloud-agent/internal/version.Version=0.2.1"
```

This is how it is built for releases: https://github.com/cdr/cloud-agent/blob/master/.github/workflows/release.yaml#L28

**Comment by informathemusic** [comment]
This works alright now, thank you! Im facing a new ossue now, should I open a new one? It just gives me the latency but doesnt give me a link

**Comment by informathemusic** [comment]
> Ah! I can't remember if you have to specify v0.2.1 or 0.2.1, but you'll need to build with this flag:
> 
> ```sh
> go build -ldflags "-X go.coder.com/cloud-agent/internal/version.Version=v0.2.1"
> # or
> go build -ldflags "-X go.coder.com/cloud-agent/internal/version.Version=0.2.1"
> ```
> 
> This is how it is built for releases: https://github.com/cdr/cloud-agent/blob/master/.github/workflows/release.yaml#L28

@bpmct It's with the `v` btw

**Comment by jsjoeio** [comment]
> Im facing a new ossue now, should I open a new one? It just gives me the latency but doesnt give me a link

cc @bpmct @kylecarbs  any ideas?

**Comment by informathemusic** [comment]
Oh, update, it didnt give it enough of a chance: Ot tried to read a json but failed coz the header was EOF

**Comment by informathemusic** [comment]
Oh, update, it didnt give it enough of a chance: It tried to read a json but failed coz the header was EOF

**Comment by bpmct** [comment]
Ah cool. We will have a new release soon which will resolve these networking issues

**Comment by 1tszyau** [comment]
I am running into the same issue with installing by the script (which install code-server using brew). The brew version that brew installed is 3.12.0.

**Comment by bpmct** [comment]
I think this is likely because postinstall script is not running, which will be fixed for the next release. (#4231) Could you try manually running these lines in your terminal?

https://github.com/cdr/code-server/blob/main/ci/build/npm-postinstall.sh#L59-L64%5C

**Comment by 1tszyau** [comment]
Thank you so much for replying me.
I have to apologise as I am very new to shell code, and don't really understand how all these magic works (and not works).

I tried to install after uninstalling code-server using "brew install code-server"
After that, I just copy and paste what you have highlighted in the postinstall script.

Here is the response:
```
curl: (22) The requested URL returned error: 404 
Failed to download cloud agent; --link will not work
```

Hope this information is helpful.

<img width="726" alt="image" src="https://user-images.githubusercontent.com/58001628/135120492-4bb352ab-5fea-4697-abd1-ad0cbe06167f.png">

**Comment by bpmct** [comment]
@1tszyau You did that right. What is the output of `uname | tr '[:upper:]' '[:lower:]'`

**Comment by 1tszyau** [comment]
I paste your code into a install-link.sh, and use:
```
chmod +x install-link.sh
sudo ./install-link.sh
```

Here is the response:
```
curl: (23) Failed writing body (0 != 1406)
Failed to download cloud agent; --link will not work
```

![image](https://user-images.githubusercontent.com/58001628/135127229-c4fedaf1-c9c6-4e19-bf85-fc7711bbc5a8.png)

**Comment by bpmct** [comment]
@1tszyau I would recommend using another method to connect to Coder for now, as we still have a lot to do with the new version: https://coder.com/docs/code-server/v3.12.0/guide#using-lets-encrypt-with-caddy
