### ISSUE TITLE
iPad pro editor lose focus after swipping back from safari browser

### ISSUE THREAD

**Issue by fuchanglin** [coder/code-server#4182]
## OS/Web Information

- Web Browser: Safari PWA mode
- Local OS: iPad OS 15 with magic keyboard
- Remote OS: Centos 8
- Remote Architecture: amd64
- `code-server --version`: 3.12.0

## Steps to Reproduce

1. Edit code in Safari PWA
2. Swipe out to safari browser, view some article, select some word
3. Swipe back to editor
4. Sometime, it will lose focus, after re-focus, can not type Enter, tab, up/down/left/right arrow, a-z works fine.

## Expected

When swipe back, the editor should still work

## Actual

Very annoying, in order to bring Enter back, it seems I need to 1. restart Safari browser and the PWA app 
Or 2. detach iPad from magic keyboard, type Enter using the on-screen keyboard

## Notes

This issue can be reproduced in VS Code: Yes/No

**Comment by jsjoeio** [comment]
Sorry to hear this is happening! I will have to see if I can reproduce on my iPad. Thanks for your patience!

**Comment by spouradrix** [comment]
@fuchanglin By the way, you can regain focus of the code-server window by clicking on the search box. Sometimes this fix does not work but it mostly does.

**Comment by bpmct** [comment]
Was able to reproduce this in split view

**Comment by Tonyhaenn** [comment]
I’ve noticed that if I tap into the terminal, and then into the editor window, I’m able to start editing again.
IPad Pro / ipad os 15
Code-server 3.12

**Comment by fuchanglin** [comment]
> I’ve noticed that if I tap into the terminal, and then into the editor window, I’m able to start editing again. IPad Pro / ipad os 15 Code-server 3.12

Sometime it works, sometime we will lost all the focus and cannot type Enter.

**Comment by ivanpenchev** [comment]
Something similar happens to me on iPad PRO with or without PWA and with an external keyboard. While I'm editing something, if I switch to another app on the iPad, when I get back to the code-server view, the caret is still visible in the editor but in fact it behaves like the editor has lost focus thus the keyboard is not working. Taps or clicks throughout the code, changes the position of the caret but the keyboard remains non-functional.

Touching anything else on the interface and back into the editor makes it regain focus and the keyboard is back to working.

**Comment by thanhj** [comment]
Any update on this topic, I am still facing this issue today 2024.06.
I am running vscodeclient as a safari home app, every time i switch back from safari, I can not type anything on the vscode and have to touch/click the screen several times.

**Comment by code-asher** [comment]
No update from our end.  This is probably an upstream issue (https://github.com/microsoft/vscode); if you can reproduce in https://vscode.dev or GitHub Codespaces it would be worth submitting an issue there.

They do have a bunch of issues around the iPad but I am not sure this is one of them yet: https://github.com/microsoft/vscode/issues/85254
