### ISSUE TITLE
code-server Snap

### ISSUE THREAD

**Issue by bpmct** [coder/code-server#4201]
code-server snap for [Snapcraft](https://snapstats.org/)

Options:
1. link to [unofficial](https://snapstats.org/snaps/code-server) one in docs
2. host an official snap
3. do nothing

@jmgiaever - do you have any interest in merging [your snap](https://snapstats.org/snaps/code-server) to an official one? I understand you're using it with Home Assistant, so we wouldn't want to do that if it breaks functionality for you :)

**Comment by jmgiaever** [comment]
Hi @bpmct,

Sure, but for now it's an super-early release. I just started, with this first release, tonight. Going to push it to various devices now to test it.

I feel that it's not mature enough for public. Need to figure out some specifics regards to daemonize it vs execute it as a user, desktop vs server etc.

This snap will be maintained independent of Home Assistant (ref the disclaimer of the description). But have to admit that I found this as a use-case to configure HA, and therefor it also fell under the home-assistant-snap organization here at Github.

Suggest that we keep this topic for a while until I've sorted out the details. :)
