### ISSUE TITLE
cursor jump around when tabnine open

### ISSUE THREAD

**Issue by nico1988** [coder/code-server#4202]
## OS/Web Information

- Web Browser: 93.0.4577.82
- Local OS: Windows 10 OS Version 2009 (Build 22000.194)
- Remote OS: linux
- Remote Architecture: Debian GNU/Linux 10 (buster)
- `code-server --version`: v3.11.0

## Steps to Reproduce

1. with tabnine installed in code-server
2. write some code
3. the cursor just jumps around but not in the right place
4. everything is fine when I wrote code in vs code with tabnine

**Comment by jsjoeio** [comment]
Hi there! Thanks for this. Do you mind filling out the entire bug report? Any logs or a video showing this behavior would be helpful
