### ISSUE TITLE
Update docs for running code-server on Raspberry Pi

### ISSUE THREAD

**Issue by jsjoeio** [coder/code-server#4220]
In the past month, we've had a lot of discussions opened related to running code-server on Raspberry Pi. Since I have one at home, I can test this experience and report any bugs.

Related:
- https://github.com/cdr/code-server/discussions/4078
- https://github.com/cdr/code-server/discussions/3981
- https://github.com/cdr/code-server/discussions/3932
- https://github.com/cdr/code-server/discussions/4154

**Comment by aguileraGit** [comment]
For what it's worth, I was able to install code-server on a RPi. I wasn't able to install just using npm. I had to install yarn. It also took forever to finish (15 minutes?) with no signs of life.

**Comment by jsjoeio** [comment]
@aguileraGit good to know. Thank you for reporting! Do you think we can close this now?

**Comment by aguileraGit** [comment]
I think it would be valuable to update the [RPi instructions](https://coder.com/docs/code-server/latest/install#raspberry-pi) with:
- Yarn is required.
- a comment that the installation hangs for 10-15 minutes.

I'm not sure if different pi's (3/zero/4) are supported. I believe some had different architectures. I can tell you it works on the 4. Maybe something else to add?

**Comment by jsjoeio** [comment]
I think that sounds great! I'll add both of those points. Thank you!

**Comment by code-asher** [comment]
Closing for now since I have no way of testing or writing these docs, but if someone wants to contribute they are very welcome!
