### ISSUE TITLE
Upgrading @types/node from 14.17.6 to 14.17.19 causes build failure

### ISSUE THREAD

**Issue by jawnsy** [coder/code-server#4256]
It seems that wsRouter.ts is using undocumented methods, which were removed in 14.17.19.

## Steps to Reproduce

1. Clone the main branch
2. Apply the following change to package.json:
   ```Diff
    --- a/package.json
    +++ b/package.json
    @@ -42,7 +42,7 @@
        "@types/express": "^4.17.8",
        "@types/http-proxy": "^1.17.4",
        "@types/js-yaml": "^4.0.0",
    -    "@types/node": "^14.17.1",
    +    "@types/node": "14.17.19",
        "@types/pem": "^1.9.5",
        "@types/proxy-from-env": "^1.0.1",
        "@types/safe-compare": "^1.1.0",
   ```
3. Run `yarn install` to update dependencies
4. Run `yarn run tsc --noEmit --skipLibCheck`

## Expected

No errors, we should be using public APIs only

## Actual

We get several errors about missing fields (these do not appear in the official [Node.js documentation for IncomingMessage](https://nodejs.org/api/http.html#http_class_http_incomingmessage) so they are likely internal APIs):

```
$ yarn run tsc --noEmit --skipLibCheck
yarn run v1.22.5
$ /home/coder/projects/code-server-nofork/node_modules/.bin/tsc --noEmit --skipLibCheck
src/node/wsRouter.ts:11:9 - error TS2339: Property 'ws' does not exist on type 'IncomingMessage'.

11     req.ws = socket
           ~~

src/node/wsRouter.ts:12:9 - error TS2339: Property 'head' does not exist on type 'IncomingMessage'.

12     req.head = head
           ~~~~

src/node/wsRouter.ts:13:9 - error TS2339: Property '_ws_handled' does not exist on type 'IncomingMessage'.

13     req._ws_handled = false
           ~~~~~~~~~~~

src/node/wsRouter.ts:17:16 - error TS2339: Property '_ws_handled' does not exist on type 'IncomingMessage'.

17       if (!req._ws_handled) {
                  ~~~~~~~~~~~


Found 4 errors.

error Command failed with exit code 1.
```

## Notes

This issue can be reproduced in VS Code: I haven't tried, I'm not sure if this code belongs to code-server or VSCode. I imagine the former, based on the path.

**Comment by jsjoeio** [comment]
Whoops! That's unusual. Thanks for documenting this! Hopefully it's an easy fix (famous last words 😂)

**Comment by DevXiaolan** [comment]
So? why close this issue ? Is it fixed ? It came to me

**Comment by jsjoeio** [comment]
We're on [Node 16 now](https://github.com/coder/code-server/blob/main/package.json#L47). What version of code-server are you using?
