### ISSUE TITLE
Do not pollute global environment for builds

### ISSUE THREAD

**Issue by jawnsy** [coder/code-server#4257]
Some of the build scripts run programs on the PATH: https://github.com/cdr/code-server/blob/edb3b41800407c967e15c6151822b9a3a352098b/ci/dev/lint.sh#L7-L10

The disadvantage of this approach is that the version available on PATH may not match the version specified in package.json. This feature request proposes that we change our command invocations from a pattern like:

```
  eslint --max-warnings=0 --fix $(git ls-files "*.ts" "*.tsx" "*.js" | grep -v "vendor/modules/code-oss-dev" | grep -v "lib/vscode")
  stylelint $(git ls-files "*.css" | grep -v "vendor/modules/code-oss-dev" | grep -v "lib/vscode")
  tsc --noEmit --skipLibCheck
```

To one that runs the commands through yarn, like so:

```
  yarn run eslint --max-warnings=0 --fix $(git ls-files "*.ts" "*.tsx" "*.js" | grep -v "vendor/modules/code-oss-dev" | grep -v "lib/vscode")
  yarn run stylelint $(git ls-files "*.css" | grep -v "vendor/modules/code-oss-dev" | grep -v "lib/vscode")
  yarn run tsc --noEmit --skipLibCheck
```

Doing this ensures that we run the version of commands specified in package.json, regardless of what may (or may not) be installed in the system PATH. This also means that we don't have to modify the PATH variable or install things into the developer's PATH.

**Comment by jsjoeio** [comment]
This is a fantastic idea!
