### ISSUE TITLE
Provide nightly builds for testing

### ISSUE THREAD

**Issue by jawnsy** [coder/code-server#4264]
# Background

We currently provide a variety of release builds that users can install with install.sh, as well as a package published to npm so that users can install from source code. These are updated when we create a release, which means that users may have to wait until the next release to see whether a bug fix addressed their issue.

Reducing the cycle time for feedback means that we can iterate more rapidly on code-server, and one way to achieve that is to publish nightly builds, so that users can see whether we have resolved their issues.

# Proposal

* Publish a `code-server-next` or `code-server-latest` package that users can install via npm
* Publish nightly builds of our usual build artifacts, like a Debian/Ubuntu package, etc (we may want to limit these to the last 30 or 90 days to reduce storage costs)

**Comment by jsjoeio** [comment]
Yes! We need this yesterday. cc @bpmct @code-asher since I've chatted with y'all about this before.

**Comment by jsjoeio** [comment]
## Homebrew

One of the pieces of this puzzle is supporting nightlies on Homebrew. While `homebrew/core` doesn't support beta/development versions, we can maintain our own tap (grain-lang does this [here](https://github.com/grain-lang/homebrew-tap)).

### UX

As a user, not a lot would change.
- to install code-server's stable release, `brew install code-server`
- to install the nightly release, `brew tap cdr/code-server-nightly` (example)

### Notes

> the forumla can get complex if you need to build from source

> Formula are the "build from source" option, and Cask are the "prepackaged"  option

> Yeah, you can see that in our `url` config, we derive the github tag and then download our tool

## Resources

- https://docs.brew.sh/Versions#acceptable-versioned-formulae
- https://github.com/grain-lang/homebrew-tap
- https://github.com/Homebrew/discussions/discussions/2217

**Comment by jsjoeio** [comment]
Not stale
