### ISSUE TITLE
can't start the release: error Please specify at least one file or folder

### ISSUE THREAD

**Issue by KawaiiNotHawaii** [coder/code-server#4270]
I am configuring code-server on a server. I used to configured and ran it correctly but I want to update to a newer version now.

## OS/Web Information

- Remote OS:Ubuntu 16.04.6 LTS (GNU/Linux 4.4.0-142-generic x86_64)
- `code-server --version`: 3.12.0

## Steps to Reproduce

1. download the latest 3.12.0 release xxxx.amd64.tar.gz file and extract it as a folder
2. cd the folder and run './bin/code-server --host "0.0.0.0" --port 9999'

## Expected
It should start running.
I used to start an outdated release 3.1.1 (code-server-linux-x86_64.tar.gz) in the same way and it works fine.

## Actual
error Please specify at least one file or folder

## Notes
I run postinstall.sh and it says yarn is not install. But I run 3.1.1 without yarn. And installing yarn requires root permission and I don't want to bother the root users indeed.

**Comment by jsjoeio** [comment]
> download the latest 3.12.0 release xxxx.amd64.tar.gz file and extract it as a folder

Any particular reason you're downloading the release manually instead of using the install script?

I'm not 100% by maybe that would get around having to install yarn.

**Comment by jsjoeio** [comment]
@forkbabu can you open a new bug report? that'll help us help you faster. thank you!
