### ISSUE TITLE
Make extension limitations easier to find in docs

### ISSUE THREAD

**Issue by jsjoeio** [coder/code-server#4282]
There's some confusion about why some extension aren't found when you search and that's because people don't always realize the extension marketplace is different than the one in VS Code.

See here: https://github.com/cdr/code-server/issues/4271#issuecomment-930620789

**Comment by code-asher** [comment]
Huh weird, I thought we used to have a notice in the sidebar that explained the difference; maybe we lost it along the way.

**Comment by jsjoeio** [comment]
Not stale
