### ISSUE TITLE
Jupyter notebook instances are often impossible to terminate

### ISSUE THREAD

**Issue by JulesGM** [coder/code-server#4283]
## OS/Web Information
OS/Web Information
Web Browser: Chrome Version 93.0.4577.82 (Official Build) (x86_64)
Local OS: MacOS 11.5.2
Remote OS: Operating System: Ubuntu 18.04.5 LTS, Kernel: Linux 5.4.0-62-generic
Remote Architecture: x86_64
code-server --version: 3.12.0 4cd55f9
Particularities: python & multi-GPU work for deep learning (AI)

## Description
I'm using the Jupyter extension from the VSX extension store. This is one of the main reasons for me to use code-server, ie as a replacement for jupyter lab. However, a lot of the times, there is no way to interrupt the kernel. Pressing "interrupt" is just ignored a large fraction of the time. I have some cells that can take a full day to run. It forces me to kill the whole server, which is really not ideal.

**Comment by JulesGM** [comment]
Kernel management (meaning starting, stopping, saving cells) is very far from as stable as on Jupyter lab, it's basically unusable for me right now. Which is really a shame, because code-server is really great otherwise.

**Comment by jsjoeio** [comment]
> is very far from as stable as on Jupyter lab, it's basically unusable for me right now. Which is really a shame, because code-server is really great otherwise.

That's really unfortunate to hear and we definitely want to improve this for you.

Do you mind updating your description to match the bug report template? I don't use Python or Jupyter Lab so I'm not really familiar with how it works. The clearer the instructions are, the better and faster we can troubleshoot this for you!
