### ISSUE TITLE
Node 16 Support To Code-Server

### ISSUE THREAD

**Issue by FlameQuard** [coder/code-server#4286]
We wanted nodejs16 support to Code-Server in termux

**Comment by jawnsy** [comment]
Tagging related issues: #4258 #4225

Upstream vscode does not support Node.js 14, as I understand it, so that makes it difficult for us to guarantee reliable support for it.

One of the commenters mentioned that it's possible to install Node.js 14 on termux - have you tried that? Binary builds of code-server (which include an appropriate Node.js runtime) for a wider variety of ARM processors might help for this issue as well.

**Comment by YgtOz** [comment]
You can install `nodejs-lts` on Termux, which is a 14.x version of nodejs. That will let you set up `code-server`.

**Comment by rudimediaz** [comment]
> You can install `nodejs-lts` on Termux, which is a 14.x version of nodejs. That will let you set up `code-server`.

node js lts now is v16

**Comment by Knayder** [comment]
Any update on that? I've been trying to install nodejs 14 on Tremux for many hours now with no success :(

**Comment by jsjoeio** [comment]
None so far :( We'll let you know when we have any updates here. We're focusing on getting the next release but we can take a look in the next sprint!

**Comment by arHSM** [comment]
> Any update on that? I've been trying to install nodejs 14 on Tremux for many hours now with no success :(

One way is to use `proot-distro` I've has some issues with directly installing **code-server** on termux but after installing ubuntu with `proot-distro` and following this **[guide](https://computingforgeeks.com/install-node-js-14-on-ubuntu-debian-linux/)** to install **nodejs 14.x** on it I was able to setup `code-server` pretty easily by running `curl -fsSL https://code-server.dev/install.sh | sh` and `proot-distro` also mounts your **/storage** so you can just run `termux-setup-storage` outside of the **proot-distro** and allow termux access to your storage after that you can just start code server by `code-server`

**Comment by im-coder-lg** [comment]
> Any update on that? I've been trying to install nodejs 14 on Tremux for many hours now with no success :(

About this, you could add Node 14 by getting+unzipping the tar zip, and moving it to `/usr/bin`. Then you can get code-server 3.10.2 and use it.

**Comment by jsjoeio** [comment]
@im-coder-lg have you had any luck with `nvm`? I installed it in Termux but now I'm getting this error:

```shell
~/downloads/release $ nvm use 14
Now using node v14.18.3 (npm v6.14.15)
~/downloads/release $ node -v
bash: /data/data/com.termux/files/home/.nvm/versions/node/v14.18.3/bin/node: No such file or directory
```

I'll have to see if I can figure out how to fix this

**Comment by im-coder-lg** [comment]
I had luck on my Raspberry Pi, it worked flawlessly. Did you use the real `nvm` by `nvm-sh`?

**Comment by jsjoeio** [comment]
Yup, that's the one I was using. Maybe I installed it wrong or am missing something in my `PATH` on Termux. Not sure. Oh well. Next time I'm in there I'll try again

**Comment by im-coder-lg** [comment]
[I ended up with the same NVM error on Termux.](https://github.com/coder/code-server/issues/4286#issuecomment-1013376937) Hope it's fixed soon.

**Comment by arHSM** [comment]
> [I ended up with the same NVM error on Termux.](https://github.com/coder/code-server/issues/4286#issuecomment-1013376937)

As stated on the NVM guide for Alpine linux
> downloaded binary to run correctly - you'll likely see "...does not exist" errors if you try that.

*https://github.com/nvm-sh/nvm#installing-nvm-on-alpine-linux*
I doubt this can be compatibility issue with the environment termux runs, this is why i suggested using proot.

**Comment by jsjoeio** [comment]
Ah, totally missed that! Thanks for the links @arHSM! 

> There is a -s flag for nvm install which requests nvm download Node source and compile it locally.

I guess I'll have to try this next time

**Comment by filiptronicek** [comment]
Maybe worth mentioning https://github.com/microsoft/vscode/pull/137241 here, as they track some issues about this there.

**Comment by jsjoeio** [comment]
Oh awesome! Thanks @filiptronicek! 🙌 Glad to hear it's in progress at least.

**Comment by jsjoeio** [comment]
Closing in favor of https://github.com/coder/code-server/issues/4894

**Comment by jawnsy** [comment]
@jsjoeio Ah, my bad, sorry about the duplicate! I should've searched first

**Comment by jsjoeio** [comment]
@jawnsy no apologies needed - yours has more information and details on how to solve it :)
