### ISSUE TITLE
Install Vim plugin on 3.12.0 GUI report an incompatible error but could be installed on CLI or 3.11.1

### ISSUE THREAD

**Issue by Oyami-Srk** [coder/code-server#4313]
## OS/Web Information

- Web Browser: Chrome 94.0.4606.54
- Local OS: Arch Linux 5.14.8-arch1-1 
- Remote OS: Arch Linux 5.14.8-arch1-1 
- Remote Architecture: x86_64
- `code-server --version`: 3.12.0 4cd55f94c0a72f05c18cea070e10b969996614d2

## Steps to Reproduce

1. Clean Install code-server (or remove ` ~/.local/share/code-server/extensions/vscodevim.vim-1.21.8`)
2. Install VscodeVim Plugin from extension page on web browser.
3. Report an error "Can't install 'vscodevim.vim' extension because it is not compatible with the current version of VS Code (version 1.60.0)."

## Expected
Extension installed like previous version.

## Actual
Fake alert of incompatible version.

## Logs

Just an alert without any log even in verbose mode.

## Screenshot

![](https://i.imgur.com/VH56lgF.png)
## Notes

This issue can be reproduced in VS Code: No

Note: It could be installed if I downgrade code-server to 3.11.1 and fully operational after I upgrade to 3.12.0, so I think it just a fake alert.
Add Note: I tried `code-server --install-extension vscodevim.vim` and it perfectly work:
```
Installing extensions...
Installing extension 'vscodevim.vim'...
Extension 'vscodevim.vim' v1.21.8 was successfully installed.
```
It may be a frontend mistake.

**Comment by jsjoeio** [comment]
Hmm...this looks oddly similar to [this issue](https://github.com/cdr/code-server/issues/4235#issuecomment-929533066). I think we have a bug in the VS Code + extension version compatibility check. I thought it was only with the CLI but this looks like the opposite - with the UI. Thanks for filing!

**Comment by jimzenn** [comment]
I am seeing the same issue. Can confirm that it cannot be install via GUI but can be installed via CLI.

**Comment by tidux** [comment]
bump

**Comment by jsjoeio** [comment]
@tidux does this happen on the latest version? I'm using the Vim plugin just fine

**Comment by tidux** [comment]
This actually does work on the latest version now that I tried with a fresh install.

**Comment by jsjoeio** [comment]
Hooray! Gonna close for now.
