### ISSUE TITLE
Fix upgrade code-server.service in install script

### ISSUE THREAD

**Issue by jsjoeio** [coder/code-server#4323]
> Oh just saw this does not use our install script. In that case use -U instead of -i. But we do need to also fix our install script.

Fix install script for upgrading when using the code-server.service

Originally reported here: https://github.com/cdr/code-server/discussions/4316#discussioncomment-1444271

**Comment by jsjoeio** [comment]
Not stale

**Comment by code-asher** [comment]
Fixed a while back, turns out you can just always use `-U` and it will install if not yet installed.
