### ISSUE TITLE
Termux: if install via install script, use yarn

### ISSUE THREAD

**Issue by YgtOz** [coder/code-server#4332]
## OS/Web Information

- Web Browser: N/A
- Local OS: Android 11
- Remote OS: Android 11 (Termux 0.117)
- Remote Architecture: aarch64 (I believe; `file ~/.../node` worked fine)
- `code-server --version`: 3.12.0

## Steps to Reproduce

1. Use the given curl command in the `README.md` file to download and install `code-server` on most recent version of Termux from F-Droid.
2. Attempt to start code-server by navigating to the directory of the `code-server` executable and executing the command `./code-server`.

## Expected

Code-server starts in the background.

## Actual

Program immediately quits with error `./code-server: 36: exec: /data/data/com.termux/files/home/.local/lib/code-server-3.12.0/lib/node: not found`

## Logs

(Seemingly no logs were generated, at least by code-server itself.)

## Screenshot

https://ibb.co/9Nb1Jtg

## Notes
The issue does not occur on either of the two versions of code-server I tried via `yarn` installation. One was the most recent version, and the other one was, I believe, around `3.11`; since the `yarn` versions have the problem that they claim to be incompatible with the Jupyter extension (which has been documented elsewhere, and I believe will be fixed in the next release), I thought I would give the standalone install a try.

This issue can be reproduced in VS Code: No 
(Regular VSCode is not available on Termux)

**Comment by jsjoeio** [comment]
I _think_ this is intentional? Or rather, it's expected. It sounds like you already know that we suggest using `yarn` to install via Termux, but maybe, we should detect that you're running the install script in Termux and automatically use `yarn`.

Is that what you're saying?

**Comment by YgtOz** [comment]
I found out about the `yarn` method through Termux's own documentation as I recall, I did not think this was expected behavior and thought that the install script method was also supported for Termux. But that is likely my own error. If Termux support was never intended for the install script, I suppose there is nothing else to be said. Perhaps this could be clarified somewhere (or the script automated to use `yarn` instead on Termux, as you said).

**Comment by jsjoeio** [comment]
Well, I agree, the `install` script should handle this case.

> Perhaps this could be clarified somewhere

It is documented [here](https://coder.com/docs/code-server/v3.12.0/termux#install) but clearly we're lacking somewhere else. Is there another place you suggest we add it?
