### ISSUE TITLE
Syntax Highlighting not working

### ISSUE THREAD

**Issue by Greeenman999** [coder/code-server#4345]
### Discussed in https://github.com/cdr/code-server/discussions/4344

<sup>Originally posted by **Greeenman999** October 12, 2021</sup>
Web Browser: Google Chrome 94.0.4606.81 (Official Build) (arm64)
Local OS: Mac Os Big Sur 11.3.2
Remote OS: Debian 10
Remote Architecture: amd
code-server --version: 3.12.0 b37ff28

I upgraded code-server and then there was no syntax highlighting anymore.
When I'm accessing directly over the ip adress and port, then its working.
On Firefox it's also working, but on Chrome it doesnt work.

Sometimes this error occures:
<img width="665" alt="Bildschirmfoto_2021-10-12_um_10 27 37" src="https://user-images.githubusercontent.com/81023792/136977582-691b308b-2d20-4289-b1ef-26f7db5f4690.png">
<img width="529" alt="Bildschirmfoto 2021-10-12 um 16 43 52" src="https://user-images.githubusercontent.com/81023792/136978000-6cc71d3d-cbd5-4860-b07e-e7eecb0dadbe.png">

The complete code is not highlighted and gray:
<img width="1438" alt="Bildschirmfoto_2021-10-12_um_10 19 32" src="https://user-images.githubusercontent.com/81023792/136977703-c6b52352-85c1-4e6f-ab9d-97939f18b1c7.png">

Anyone else having this issue?

**Comment by Greeenman999** [comment]
As I said above, on Firefox or when I'm connecting over the ip adress, then it's working, but in Chrome not...

**Comment by matthewthechickenman** [comment]
```
ERR WebAssembly.instantiate(): Wasm code generation disallowed by embedder: CompileError: WebAssembly.instantiate(): Wasm code generation disallowed by embedder
``` 
I'm getting a similar error. It works over IP (in Chrome) but then other features break too.

**Comment by IvanProgramming** [comment]
Also has a same issue. It worked perfectly in Mobile chrome, but now there is no syntax highlighting in my browser.

**Comment by 3735943886** [comment]
Same issue here.
No syntax coloring on Microsoft Edge/Windows 11
![codeserver](https://user-images.githubusercontent.com/9522390/165019601-c5fac6d6-99c7-476f-baae-0b369018a852.png)
.

**Comment by GiantLameChips** [comment]
I am getting this error in MS edge 100.0.1185.50 

But when I switch the profile guest mode it works fine must be a setting I changed somewhere in edge 
```
ERR WebAssembly is not defined: ReferenceError: WebAssembly is not defined
    at z (https://example.com/static/node_modules/vscode-oniguruma/release/main.js:1:7821)
    at Object.n [as default] (https://example.com/static/node_modules/vscode-oniguruma/release/main.js:1:6044)
    at https://example.com/static/node_modules/vscode-oniguruma/release/main.js:1:4636
    at Object.n.loadWASM (https://example.com/static/node_modules/vscode-oniguruma/release/main.js:1:4868)
    at k._doGetVSCodeOniguruma (https://example.com/static/out/vs/workbench/workbench.web.main.js:2381:51442)
```

**Comment by jsjoeio** [comment]
Interesting! 🤔 It says Edge supports WebAssembly [here](https://developer.mozilla.org/en-US/docs/WebAssembly#browser_compatibility).

Can you try [this](https://github.com/microsoft/vscode/issues/137704#issuecomment-976946258)?

**Comment by GiantLameChips** [comment]
> Interesting! 🤔 It says Edge supports WebAssembly [here](https://developer.mozilla.org/en-US/docs/WebAssembly#browser_compatibility).
> 
> Can you try [this](https://github.com/microsoft/vscode/issues/137704#issuecomment-976946258)?

thanks that works

**Comment by ij5** [comment]
I had same problem, but I fixed this issue with changing nginx config files.
You can remove line that contains `add_header Content-Security-Policy` in nginx.conf.

**Comment by leryn1122** [comment]
> I had same problem, but I fixed this issue with changing nginx config files. You can remove line that contains `add_header Content-Security-Policy` in nginx.conf.

@ij5 I don't encourage to remove CSP when using nginx reverse proxy. I added CSP header in nginx configs according to [WASM CSP issue](https://github.com/WebAssembly/content-security-policy/issues/7). It works on Chrome v110.*

```
add_header Content-Security-Policy "default-src 'self' 'wasm-unsafe-eval' http: https: ws: wss: data: blob: 'unsafe-inline'; frame-ancestors 'self';" always;
```
