### ISSUE TITLE
failed to install code-server by script

### ISSUE THREAD

**Issue by alexcdever** [coder/code-server#4350]
## OS/Web Information

- Web Browser: N/A
- Local OS: Ubuntu 20.04.3 LTS
- Remote OS: N/A
- Remote Architecture: N/A
- `code-server --version`: 3.12.0
- shell: zsh installed by omz

## Steps to Reproduce

1. open terminal
2. execute `curl -fsSLV https://code-server.dev/install.sh | sh`

## Expected

this command will download the installation script and execute it

## Actual

thrown error:
```
➜  ~ curl -fsSLV https://code-server.dev/install.sh | sh
sh: 1: Syntax error: "(" unexpected
```

## Logs

```
➜  ~ curl -fsSLV https://code-server.dev/install.sh | sh
sh: 1: Syntax error: "(" unexpected
```

## Screenshot

![image](https://user-images.githubusercontent.com/14200813/137187295-2d424742-af04-4d40-a044-442989f41369.png)

## Notes

This issue can be reproduced in VS Code: No

**Comment by code-asher** [comment]
`-V` makes cURL output version info instead of fetching the URL so removing it should fix this.
