### ISSUE TITLE
Extention not compatible with current version

### ISSUE THREAD

**Issue by mrfoxie** [coder/code-server#4361]
## OS/Web Information

- Web Browser: Brave
- Local OS: Android 11
- Remote Architecture: aarch64
- `code-server --version`: `3.12.0 4cd55f94c0a72f05c18cea070e10b969996614d2`

## Error
when I try to install any extension in code-server it's give me error
```
[2021-10-16T03:59:31.503Z] info  code-server 3.12.0 4cd55f94c0a72f05c18cea070e10b969996614d2
[2021-10-16T03:59:31.506Z] info  Using user-data-dir ~/.local/share/code-server
[2021-10-16T03:59:31.528Z] info  Using config file ~/.config/code-server/config.yaml
[2021-10-16T03:59:31.528Z] info  HTTP server listening on http://127.0.0.1:8080
[2021-10-16T03:59:31.529Z] info    - Authentication is enabled
[2021-10-16T03:59:31.529Z] info      - Using password from ~/.config/code-server/config.yaml
[2021-10-16T03:59:31.529Z] info    - Not serving HTTPS
[main 2021-10-16T04:01:16.288Z] RequestStore#acceptReply was called without receiving a matching request 16
[main 2021-10-16T04:01:16.416Z] RequestStore#acceptReply was called without receiving a matching request 17
[main 2021-10-16T04:01:16.503Z] RequestStore#acceptReply was called without receiving a matching request 18
[main 2021-10-16T04:01:16.903Z] RequestStore#acceptReply was called without receiving a matching request 19
[main 2021-10-16T04:01:16.908Z] RequestStore#acceptReply was called without receiving a matching request 20
[main 2021-10-16T04:01:18.432Z] RequestStore#acceptReply was called without receiving a matching request 21
[main 2021-10-16T04:01:18.439Z] RequestStore#acceptReply was called without receiving a matching request 22
[main 2021-10-16T04:01:18.447Z] RequestStore#acceptReply was called without receiving a matching request 23
[main 2021-10-16T04:01:18.452Z] RequestStore#acceptReply was called without receiving a matching request 24
[main 2021-10-16T04:01:18.456Z] RequestStore#acceptReply was called without receiving a matching request 25
[main 2021-10-16T04:02:15.185Z] Can't install 'rusnasonov.vscode-hugo' extension because it is not compatible with the current version of VS Code (version 1.60.0).
[main 2021-10-16T04:02:45.363Z] Can't install 'vscode-icons-team.vscode-icons' extension because it is not compatible with the current version of VS Code (version 1.60.0).
[main 2021-10-16T04:07:58.637Z] Can't install 'vscode-icons-team.vscode-icons' extension because it is not compatible with the current version of VS Code (version 1.60.0).
```
## Screenshot

![Screenshot_20211016-093249_Brave](https://user-images.githubusercontent.com/25217451/137573297-0f1265d7-0de6-40f9-8868-4104bbcc26c4.png)

**Comment by Justxd22** [comment]
I just got this error after updating code-server to latest, 
Failed extension : [ms-python ](https://marketplace.visualstudio.com/items?itemName=ms-python.python)
Fixed by downloading the vsix file from [here](https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-python/vsextensions/python/2021.10.1365161279/vspackage) and installing manually using install from vsix option complained about ms-toolsai.jupyter extension missing but works fine

**Comment by ashvinnihalani** [comment]
Also want to point out that code server is usually a version or two behind the official release. Use something like vsixhub.com which lists old versions of extensions and the code versions you need to run them.

**Comment by RoyGalaxy** [comment]
I am also facing this issue from over a month but still there is no update which solves the problem.Team code-server kindly do something on this.

**Comment by jsjoeio** [comment]
Sorry folks! I've added the high-priority label and moved it to an upcoming sprint. There is a chance this is fixed when 4.0.0 comes out so keep your eyes peeled.

**Comment by benz0li** [comment]
Works now. Tested with code-server 4.0.1 and vscode-icons-team.vscode-icons@11.8.0 (latest)

**Comment by jsjoeio** [comment]
@benz0li you are on it! That has to be your 4/5 issue you've helped test & close. Thank you so much!

**Comment by Justxd22** [comment]
Thanks!
