### ISSUE TITLE
install.sh does not support derivatives. 

### ISSUE THREAD

**Issue by AussieEevee** [coder/code-server#4389]
I'm running Linux Mint 20.2, an Ubuntu derivative. 

Yet if I run install.sh on Linux Mint, it claims that the package manager is unsupported and gets the standalone version instead.

**Comment by im-coder-lg** [comment]
Have you tried downloading the `.deb` package? I am asking this because the installer script downloads the package to a temporary directory, downloads it using `apt` or `dpkg` and deletes the directory.

**Comment by AussieEevee** [comment]
I'm referring to the install script itself. From what I can tell, it's supposed to identify which distro you are on and use the correct package and only fall back to direct installation if it can determine which package is correct... which is what it seems to be doing on Mint, despite .deb being correct.

**Comment by im-coder-lg** [comment]
Can you run the script again and post the logs here with Neofetch(`sudo apt install neofetch` if not found then `sudo apt update` and follow the last command)?
