### ISSUE TITLE
Allow access to Proposed APIs from installed extensions by default

### ISSUE THREAD

**Issue by toddewilliams** [coder/code-server#4397]
VS Code restricts access to a series of important APIs under the heading of "proposed". A large number of these are APIs are stable and no longer experimental but are designed to never come out of "proposed" status for purely control and commercialization reasons. 

Our extension, [CodeTogether](https://codetogether.com), requires access to these "proposed" APIs to provide services like exposing Terminals to CodeTogether participants. Microsoft whitelists their own extensions as part of the VS Code installation, of course.

It would be great if code-server could just disable limiting access to proposed APIs, removing the arbitrary limit on what extensions can access, that was drawn by Microsoft for competitive purposes. Additionally, it is simply not ideal to require a server-style VS Code deployment to require the entire server process to be restarted to allow access to these APIs. 

If removing the proposed API restrictions can't be done (or can't be done quickly), then I'd like to request that you add genuitecllc.codetogether to the existing whitelist for code-server as this would also be greatly beneficial.

**Comment by dbush-clickup** [comment]
I'm seeing this issue with 2022.0.4 version (again? still?)

FWIW, my setup is VS Code on windows and developing in WSLg.

**Comment by jsjoeio** [comment]
@dbush-clickup do you mind posting basic repo steps?

**Comment by dbush-clickup** [comment]
> @dbush-clickup do you mind posting basic repo steps?

1) Install CodeTogether on VS Code Windows.
2) When prompted for "CodeTogether requires access to VS Code Proposed APIs..." click "Enable"
3) Shut down VS Code
4) Reload VS Code
5) goto  2)

I don't even have to have a project loaded so does not seem specific to WSL at all.

**Comment by code-asher** [comment]
Closing as I believe we always enable the proposed API now, but if there is a bug with this let me know.
