### ISSUE TITLE
The extension "hediet.vscode-drawio" doesn't work

### ISSUE THREAD

**Issue by SlavikCA** [coder/code-server#4400]
## OS/Web Information

- Web Browser: Chrome
- Local OS: Windows 10
- `code-server --version`: 3.12.0 running in Docker

## Steps to Reproduce

1. install the extension hediet.vscode-drawio
2. create empty file test.drawio.svg
3. open the file

## Expected

drawio diagram editor displayed

## Actual

no diagram editor displayed

## Logs

Error in browser console:

> mainThreadExtensionService.ts:95 Activating extension 'hediet.vscode-drawio' failed: Cannot find module '/home/coder/.local/share/code-server/extensions/hediet.vscode-drawio-999.0.0-alpha/dist/extension/index'
> Require stack:
> - /usr/lib/code-server/vendor/modules/code-oss-dev/out/vs/loader.js
> - /usr/lib/code-server/vendor/modules/code-oss-dev/out/bootstrap-amd.js
> - /usr/lib/code-server/vendor/modules/code-oss-dev/out/bootstrap-fork.js.

Looking at the files:

> ls -hl .local/share/code-server/CachedExtensionVSIXs/
> total 112M
> -rw-r--r-- 1 slavik users 1.9M Oct 20 23:10 donjayamanne.githistory-0.6.18
> -rw-r--r-- 1 slavik users  32M Oct 20 22:54 felixfbecker.php-intellisense-2.3.14
> -rw-r--r-- 1 slavik users  77M Oct 25 23:16 hediet.vscode-drawio-999.0.0-alpha
> -rw-r--r-- 1 slavik users 1.1M Oct 20 23:18 mhutchie.git-graph-1.30.0

This issue can be reproduced in VS Code: No

the same extension is working fine in the desktop VS Code

I'm not sure, if this is code-server issue or the extension issue. Let me know, if I need to resubmit in the extension repo.

**Comment by dxkrs** [comment]
the promble had fix? I meet the same promble

**Comment by code-asher** [comment]
Latest code-server uses Open VSX now so it should be working now.  If
you are having trouble feel free to open a new issue with details!

**Comment by dxkrs** [comment]
@code-asher Yes, I am meeting the trouble now. I don't know if it's the promble of extension or the code-server. I have submit [an issue](https://github.com/hediet/vscode-drawio/issues/323) to the extension repository.

**Comment by code-asher** [comment]
For what it is worth I tried on code-server v4.4.0 and installed the
extension from the Open VSX marketplace (the second one since one is
insiders) but it works for me.

**Comment by dxkrs** [comment]
> For what it is worth I tried on code-server v4.4.0 and installed the extension from the Open VSX marketplace (the second one since the first one is insiders) but it works for me.

Are you install same to me ?(install by the code-server by the docker image `linuxserver/code-server`, and do the nginx proxy)

**Comment by code-asher** [comment]
I am running code-server v4.4.0 using our official image:

```
  docker run -p 8080:8080 codercom/code-server --auth none
```

Then browsing to `localhost:8080` (so no reverse proxy).  I did also
test with a reverse proxy (not NGINX though) which also worked.

Are able to reproduce the issue using the official Docker image (or
running directly)?

**Comment by dxkrs** [comment]
emm..... I am using the image `linuxserver/code-server:latest` online. I try to use the 'codercom/code-server:latest` in local and online, it doesn't work too !
I will try to the image `codercom/code-server:4.4.0` later (download this old tag very slow)

**Comment by dxkrs** [comment]
I find something news! I try to use the host `localhost` or  a https domian with a real cert in my local environment(virtual machine), it is work for any images, I cant see and use the draw io in my code-sever!
However, I deploy it on my remote machine like local,(same network ports, images, https) , it still not work! I can't see the draw io console, even I no use the  reverse proxy with nginx.
I think this problem may be related to the `service worker`, beacuse of it only work on https request or localhost domain, but I don't know the reason that my remote machine still not work for it.

**Comment by dxkrs** [comment]
Finally, I solve my promble 😂 ...... my remote machine's bandwidth is too low -- 1Mbps !!!  Now I can see and use it after I up  to 5Mbps temporarily.
I try to reproduce this problem in local , throught using the chrome dev tools -> network -> fast 3G.
Is it real that `service worker` is unfriendly for low bandwidth network ? 😂 😂 😂

**Comment by code-asher** [comment]
Wait, that was with Firefox but with Chrome I think I reproduced.  In my case the extension host keeps reconnecting.  I think it takes so long to connect that it times out.

**Comment by code-asher** [comment]
Let us continue this in https://github.com/coder/code-server/issues/2407
