### ISSUE TITLE
Allow for GitHub Copilot

### ISSUE THREAD

**Issue by Sharpz7** [coder/code-server#4413]
I tried installing the extension, but it fails to work when I press Ctrl+Enter saying:

```
command 'github.copilot.generate' not found
```

I have tried reinstalling multiple times, signing out of accounts etc. I am in the beta test also.

I'm assuming it just isn't supported on remote vscode yet, but would be interested to hear if anyone had got it working

**Comment by jsjoeio** [comment]
I am not 100% it can work with code-server but check [this thread](https://github.com/cdr/code-server/discussions/4363) and [this answer](https://github.com/cdr/code-server/discussions/4363#discussioncomment-1490151).
