### ISSUE TITLE
Setup always fails because of network instability. Can there be breakpoint continuation function

### ISSUE THREAD

**Issue by fjqingyou** [coder/code-server#4457]
i 'm sorry. My English is not good. So the following content comes from online translation

Because it's not the code server itself. So I don't think it's necessary to press the template

Setup always fails because of network instability. Can there be breakpoint continuation function?

If the local part is downloaded successfully, can the download step be skipped automatically

log
``` log
root@iZ2zednfbgdn5vlwxa6yacZ:~# curl -fsSL https://code-server.dev/install.sh | sh
Ubuntu 18.04.6 LTS
Installing v3.12.0 of the amd64 deb package from GitHub.

+ mkdir -p ~/.cache/code-server
+ curl -#fL -o ~/.cache/code-server/code-server_3.12.0_amd64.deb.incomplete -C - https://github.com/cdr/code-server/releases/download/v3.12.0/code-server_3.12.0_amd64.deb
-=O=-                                              #     #    #    #
curl: (7) Failed to connect to github.com port 443: Connection timed out
root@iZ2zednfbgdn5vlwxa6yacZ:~# curl -fsSL https://code-server.dev/install.sh | sh
Ubuntu 18.04.6 LTS
Installing v3.12.0 of the amd64 deb package from GitHub.

+ mkdir -p ~/.cache/code-server
+ curl -#fL -o ~/.cache/code-server/code-server_3.12.0_amd64.deb.incomplete -C - https://github.com/cdr/code-server/releases/download/v3.12.0/code-server_3.12.0_amd64.deb
######################################################################## 100.0%#=#=-#  #                                ####                                                                       6.7%
curl: (56) OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 104
root@iZ2zednfbgdn5vlwxa6yacZ:~# curl -fsSL https://code-server.dev/install.sh | sh
curl: (56) Unexpected EOF
root@iZ2zednfbgdn5vlwxa6yacZ:~# curl -fsSL https://code-server.dev/install.sh | sh
curl: (56) Unexpected EOF
root@iZ2zednfbgdn5vlwxa6yacZ:~# curl -fsSL https://code-server.dev/install.sh | sh
curl: (28) Operation timed out after 300135 milliseconds with 0 out of 0 bytes received
root@iZ2zednfbgdn5vlwxa6yacZ:~# curl -fsSL https://code-server.dev/install.sh | sh

Ubuntu 18.04.6 LTS
Installing v3.12.0 of the amd64 deb package from GitHub.

+ mkdir -p ~/.cache/code-server
+ curl -#fL -o ~/.cache/code-server/code-server_3.12.0_amd64.deb.incomplete -C - https://github.com/cdr/code-server/releases/download/v3.12.0/code-server_3.12.0_amd64.deb
######################################################################## 100.0%
curl: (56) Unexpected EOF
root@iZ2zednfbgdn5vlwxa6yacZ:~#
```

**Comment by jsjoeio** [comment]
Hmm...I don't think we can support this without a lot of refactoring 🤔. @code-asher thoughts?

**Comment by code-asher** [comment]
Once the deb is downloaded the install script will not try to download
it again (unless there is a new version).

The install script does resume the download when it is ran again so if
it is ran enough times it should eventually complete assuming it is not
failing to connect entirely.  Maybe we can automate retrying or add a
--retry flag.

**Comment by 546669204** [comment]
@fjqingyou  Use for China
```
curl -fsSL https://raw.fastgit.org/cdr/code-server/main/install.sh | sed 's/github.com/hub.fastgit.org/g' | sh 
```

**Comment by fjqingyou** [comment]
> @fjqingyou Use for China
> 
> ```
> curl -fsSL https://raw.fastgit.org/cdr/code-server/main/install.sh | sed 's/github.com/hub.fastgit.org/g' | sh 
> ```
root@iZuf6hm5k8qkewj1rreq0qZ:~# curl -fsSL https://raw.fastgit.org/cdr/code-server/main/install.sh | sed 's/github.com/hub.fastgit.org/g' | sh 
curl: (22) The requested URL returned error: 502 
root@iZuf6hm5k8qkewj1rreq0qZ:~# clear

root@iZuf6hm5k8qkewj1rreq0qZ:~# curl -fsSL https://raw.fastgit.org/cdr/code-server/main/install.sh | sed 's/github.com/hub.fastgit.org/g' | sh 
Ubuntu 18.04.6 LTS
Installing v4.0.1 of the amd64 deb package from GitHub.

+ mkdir -p ~/.cache/code-server
+ curl -#fL -o ~/.cache/code-server/code-server_4.0.1_amd64.deb.incomplete -C - https://hub.fastgit.org/coder/code-server/releases/download/v4.0.1/code-server_4.0.1_amd64.deb
#########                                                                 13.3%##O#- #                                                                       
curl: (56) Unexpected EOF
root@iZuf6hm5k8qkewj1rreq0qZ:~# curl -fsSL https://raw.fastgit.org/cdr/code-server/main/install.sh | sed 's/github.com/hub.fastgit.org/g' | sh 
Ubuntu 18.04.6 LTS
Installing v4.0.1 of the amd64 deb package from GitHub.

+ mkdir -p ~/.cache/code-server
+ curl -#fL -o ~/.cache/code-server/code-server_4.0.1_amd64.deb.incomplete -C - https://hub.fastgit.org/coder/code-server/releases/download/v4.0.1/code-server_4.0.1_amd64.deb
###########################                                               37.5%
curl: (56) Unexpected EOF
root@iZuf6hm5k8qkewj1rreq0qZ:~# curl -fsSL https://raw.fastgit.org/cdr/code-server/main/install.sh | sed 's/github.com/hub.fastgit.org/g' | sh 
curl: (22) The requested URL returned error: 429 
root@iZuf6hm5k8qkewj1rreq0qZ:~# curl -fsSL https://raw.fastgit.org/cdr/code-server/main/install.sh | sed 's/github.com/hub.fastgit.org/g' | sh 
curl: (22) The requested URL returned error: 502 
root@iZuf6hm5k8qkewj1rreq0qZ:~#

**Comment by fjqingyou** [comment]
> @fjqingyou Use for China
> 
> ```
> curl -fsSL https://raw.fastgit.org/cdr/code-server/main/install.sh | sed 's/github.com/hub.fastgit.org/g' | sh 
> ```

```
root@iZuf6hm5k8qkewj1rreq0qZ:~# curl -fsSL https://raw.fastgit.org/cdr/code-server/main/install.sh | sed 's/github.com/hub.fastgit.org/g' | sh 
curl: (22) The requested URL returned error: 502 
root@iZuf6hm5k8qkewj1rreq0qZ:~# clear

root@iZuf6hm5k8qkewj1rreq0qZ:~# curl -fsSL https://raw.fastgit.org/cdr/code-server/main/install.sh | sed 's/github.com/hub.fastgit.org/g' | sh 
Ubuntu 18.04.6 LTS
Installing v4.0.1 of the amd64 deb package from GitHub.

+ mkdir -p ~/.cache/code-server
+ curl -#fL -o ~/.cache/code-server/code-server_4.0.1_amd64.deb.incomplete -C - https://hub.fastgit.org/coder/code-server/releases/download/v4.0.1/code-server_4.0.1_amd64.deb
#########                                                                 13.3%##O#- #                                                                       
curl: (56) Unexpected EOF
root@iZuf6hm5k8qkewj1rreq0qZ:~# curl -fsSL https://raw.fastgit.org/cdr/code-server/main/install.sh | sed 's/github.com/hub.fastgit.org/g' | sh 
Ubuntu 18.04.6 LTS
Installing v4.0.1 of the amd64 deb package from GitHub.

+ mkdir -p ~/.cache/code-server
+ curl -#fL -o ~/.cache/code-server/code-server_4.0.1_amd64.deb.incomplete -C - https://hub.fastgit.org/coder/code-server/releases/download/v4.0.1/code-server_4.0.1_amd64.deb
###########################                                               37.5%
curl: (56) Unexpected EOF
root@iZuf6hm5k8qkewj1rreq0qZ:~# curl -fsSL https://raw.fastgit.org/cdr/code-server/main/install.sh | sed 's/github.com/hub.fastgit.org/g' | sh 
curl: (22) The requested URL returned error: 429 
root@iZuf6hm5k8qkewj1rreq0qZ:~# curl -fsSL https://raw.fastgit.org/cdr/code-server/main/install.sh | sed 's/github.com/hub.fastgit.org/g' | sh 
curl: (22) The requested URL returned error: 502 
root@iZuf6hm5k8qkewj1rreq0qZ:~# 
```

**Comment by code-asher** [comment]
Closing since we do resume interrupted downloads and we do cache downloads.
