### ISSUE TITLE
Resource files in termux

### ISSUE THREAD

**Issue by essential-existence** [coder/code-server#4458]
OS: Android 10
Google chrome: 94.0.4606.85
termux: 0.117
node.js: 14 and 17
code-server: 3.12.0

Bug:
Some pictures do not load in android chrome:
`/data/data/com.termux/files/home/.config/yarn/global/node_modules/code-server/vendor/modules/code-oss-dev/out/vs/workbench/contrib/welcome/gettingStarted/common/media/dark.png`, `/data/data/com.termux/files/home/.config/yarn/global/node_modules/code-server/vendor/modules/code-oss-dev/out/vs/workbench/contrib/welcome/gettingStarted/common/media/light.png`...

**Comment by jsjoeio** [comment]
Hmm...how are you accessing code-server on Termux in the browser?

Can you post a recording or a screenshot?

**Comment by jsjoeio** [comment]
@essential-existence great! Thanks! Is it possible to get access to the browser logs somehow? That would help

**Comment by essential-existence** [comment]
Unfortunately, that's all I have. This problem is not difficult to reproduce, you only need termux and a smartphone.
And this problem seems insignificant, it just spoils the appearance. Thanks!

**Comment by jsjoeio** [comment]
Haha okay well we'll take a look when we get a chance! Thank you!

**Comment by im-coder-lg** [comment]
I kinda think this affects every device as well as PCs. Feel like I noticed this on both code-server and Gitpod.
