### ISSUE TITLE
Enable dragging files to the trash

### ISSUE THREAD

**Issue by jsjoeio** [coder/code-server#4486]
See Discussion: https://github.com/cdr/code-server/discussions/4469#discussioncomment-1621597

**Comment by emanueleperuffo** [comment]
I'm not sure that dragging is the right word for code-server given that it's a browser app. Other than that awesome! It would be great to have this functionality.

**Comment by emanueleperuffo** [comment]
Can you drag files from the browser to the trash I mean. What I meant in the discussion linked is to be able to leverage something like trash-cli or gio or something similar to enable the "move to trash" context menu action. Now we only have "delete permanently".

**Comment by jsjoeio** [comment]
> Can you drag files from the browser to the trash I mean

Based on my understanding, that's what this feature request is so hopefully 🤞

> something similar to enable the "move to trash" context menu action

Ah, my bad, maybe I misunderstood. I was thinking you wanted to be able to drag items from the File Explorer into the OS's trash like this:

## Video

https://user-images.githubusercontent.com/3806031/141210503-66971810-8531-4c06-8678-eaca47f0b027.mov

(Also, sorry I didn't realize you were the same person who posted this Discussion - it's been a long day 😂😅)

Maybe we can do both though!

- enable dragging files to trash
- add "move to trash" in context menu action
