### ISSUE TITLE
Fix download server not allowing resumption of interrupted download

### ISSUE THREAD

**Issue by eedrxs** [coder/code-server#4498]
The download server disallows resumption of downloads after brief network interruption or poor network generally. This makes it extremely difficult for people in places with poor network to download the packages. I've trying and trying, it's the same thing: the download ceases because of poor network, you try to resume and it fails (Chrome says 'Failed - Needs authorization'). I've tried with different browsers it's still the same thing.

**Comment by jsjoeio** [comment]
@theBardBoy can you please either explain exactly what you're doing or open a bug report issue with repro steps? That'll help us help you faster
