### ISSUE TITLE
Add support to use hased-password in a different file

### ISSUE THREAD

**Issue by anhdle14** [coder/code-server#4510]
Hoping code-server can use the same technique like `jupyter server` ([reference](https://jupyter-notebook.readthedocs.io/en/stable/public_server.html#automatic-password-setup)). Basically:

- New `code-server password` command to prompt for password and save it to `~/.config/code-server/password.json`.
- Remove `hased-password:` key from `~/.config/code-server/config.yaml`.

This will help end users to commit the `config.yaml` file to dotfiles git repository without leaking credentials.

**Comment by jsjoeio** [comment]
> Remove hased-password: key from ~/.config/code-server/config.yaml.

This would be a breaking change. 

> This will help end users to commit the config.yaml file to dotfiles git repository without leaking credentials.

But I can see the value of this.

**Comment by ashvinnihalani** [comment]
If backwords compatible issue couldn't you just have the hashed-password-file key in the config file that takes precedence over the hashed-password key. That way you don't break compat and can still have this feature.

**Comment by jsjoeio** [comment]
@ashvinnihalani I suppose that would solve that - fantastic suggestion ♥️
