### ISSUE TITLE
nodejs mismatch between the two install methods

### ISSUE THREAD

**Issue by heggland** [coder/code-server#4512]
different nodejs versions when I install with curl/npm methods.
I'm just testing on raspberry, which has nodejs version v.12.22.5. 
The curl installer just straight up wouldnt work, maybe since its a raspberry I dunno.. It says one need atleast node v12 or newer.
The npm install way says node v14 is required.

**curl -fsSL https://code-server.dev/install.sh | sh**
```
curl -fsSL https://code-server.dev/install.sh | sh
Raspbian GNU/Linux 11 (bullseye)
No standalone releases for armv7l.
Falling back to installation from npm.
Installing latest from npm.

Please install npm or yarn to install code-server!
You will need at least node v12 and a few C dependencies.
See the docs https://coder.com/docs/code-server/latest/install#yarn-npm
```

**npm i code-server**
```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'code-server@3.12.0',
npm WARN EBADENGINE   required: { node: '= 14' },
npm WARN EBADENGINE   current: { node: 'v12.22.5', npm: '7.5.2' }
npm WARN EBADENGINE }
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated grpc@1.24.11: This library will not receive further updates other than security fixes. We recommend using @grpc/grpc-js instead.
npm ERR! code 1
npm ERR! path /home/pi/vscode/node_modules/code-server
npm ERR! command failed
npm ERR! command sh -c bash ./postinstall.sh
npm ERR! ERROR: code-server currently requires node v14.
npm ERR! ./postinstall.sh: line 38: FORCE_NODE_VERSION: unbound variable

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2021-11-15T19_59_25_083Z-debug.log
```

**Comment by jsjoeio** [comment]
This is very strange indeed 🤔

The first error message is hard-coded [here](https://github.com/cdr/code-server/blob/main/install.sh#L434-L436).

I think to get past this, you can run with the flag `--ignore-engines` for the `npm/yarn` way. And also, this should be installed globally so we recommend `yarn global add code-server` or `npm i -g code-server`.

**Comment by jsjoeio** [comment]
The v14 comes from our package.json `engines` field [here](https://github.com/cdr/code-server/blob/main/package.json#L117-L119). They should definitely be consistent though.

**Comment by im-coder-lg** [comment]
@heggland do you have Node 14? If you do, try this: `sudo npm i -g code-server @3.10.2`. The reason I recommend you to use the old version is this: #4422

**Comment by martadinata666** [comment]
This also happend with newer nodejs, currently testing with node16

```
Step 4/10 : RUN     node --version &&         npm install -g code-server@"$CODE_RELEASE"
 ---> Running in 62f111952767
v16.13.0
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'code-server@3.12.0',
npm WARN EBADENGINE   required: { node: '= 14' },
npm WARN EBADENGINE   current: { node: 'v16.13.0', npm: '8.1.0' }
npm WARN EBADENGINE }
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated grpc@1.24.11: This library will not receive further updates other than security fixes. We recommend using @grpc/grpc-js instead.
npm notice 
npm notice New patch version of npm available! 8.1.0 -> 8.1.4
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.1.4>
npm notice Run `npm install -g npm@8.1.4` to update!
npm notice 
npm ERR! code 1
npm ERR! path /usr/lib/node_modules/code-server
npm ERR! command failed
npm ERR! command sh -c bash ./postinstall.sh
npm ERR! ERROR: code-server currently requires node v14.
npm ERR! ./postinstall.sh: line 38: FORCE_NODE_VERSION: unbound variable

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/debian/.npm/_logs/2021-11-28T11_05_50_258Z-debug.log
```

**Comment by im-coder-lg** [comment]
Node 14 only works as of now. Until the upstream VSCode supports it, we can't.

**Comment by javix64** [comment]
Regarding this issue... i have installed in my raspberry 4, the node v14.18.2. but is not working anyway
![image](https://user-images.githubusercontent.com/58471170/153031586-2e2627ea-13cb-4429-815c-55fc8235b617.png)

Should i use the version code-server@3.12.0??

**Comment by jsjoeio** [comment]
> upsi... i have discovered that i have node in version 14, but nodejs in version 16... i need to fix it

Ah got it. Let us know if this resolves the issue!

**Comment by javix64** [comment]
Ok. i couldn't installed via npm, no latest version and no 3.12.0 version.
So i have tried via sh script, but when i'm trying to run it it's retrieving this error:
![image](https://user-images.githubusercontent.com/58471170/153051702-ac6413c0-b7c3-4603-a2fa-6a26a4a79134.png)
There are many issues opened with this weird 'argon', because maybe my system is:
Distributor ID:	Debian
Description:	Debian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye
aarch64

---
whatever finally i could installed via sh script with the flag --version 3.12.0:
`curl -fsSL https://code-server.dev/install.sh | sh -s -- --version 3.12.0`
so that was my weird solution... almost i can use it :)

**Comment by martadinata666** [comment]
I just use the nodesource repo, https://github.com/nodesource/distributions/blob/master/README.md
As it like all in one so no version mismatch, as NVM is ok but sometimes forgot using it. Well just use what suit you.

**Comment by code-asher** [comment]
Closing as this does not appear to be a bug in the code-server repo.
