### ISSUE TITLE
Old extension versions are not cleaned up

### ISSUE THREAD

**Issue by matttbe** [coder/code-server#4525]
## OS/Web Information

- Web Browser: Chromium
- Local OS: Ubuntu 22.04
- Remote OS: Ubuntu 22.04
- Remote Architecture: amd64
- `code-server --version`: 3.12.0 4cd55f94c0a72f05c18cea070e10b969996614d2

## Steps to Reproduce

1. Install extensions
2. Wait a few months to get many updates
3. Check the content (and size) of `~/.local/share/code-server/extensions/`

## Expected

Only one version per extension

## Actual

Plenty of versions, e.g.:

```bash
$ du -hs ~/.local/share/code-server/extensions/ms-python* | sort -h
59M     ~/.local/share/code-server/extensions/ms-python.python-2021.10.1365161279
60M     ~/.local/share/code-server/extensions/ms-python.python-2019.4.12954
73M     ~/.local/share/code-server/extensions/ms-python.python-2021.1.502429796
73M     ~/.local/share/code-server/extensions/ms-python.python-2021.2.582707922
73M     ~/.local/share/code-server/extensions/ms-python.python-2021.2.625869727
73M     ~/.local/share/code-server/extensions/ms-python.python-2021.2.633441544
73M     ~/.local/share/code-server/extensions/ms-python.python-2021.5.840043038
77M     ~/.local/share/code-server/extensions/ms-python.python-2021.8.1159798656
83M     ~/.local/share/code-server/extensions/ms-python.python-2021.3.680753044
83M     ~/.local/share/code-server/extensions/ms-python.python-2021.4.765268190
85M     ~/.local/share/code-server/extensions/ms-python.python-2019.6.24221
110M    ~/.local/share/code-server/extensions/ms-python.python-2019.9.34911
129M    ~/.local/share/code-server/extensions/ms-python.python-2020.2.63072
147M    ~/.local/share/code-server/extensions/ms-python.python-2020.6.91350
161M    ~/.local/share/code-server/extensions/ms-python.python-2019.11.50794
196M    ~/.local/share/code-server/extensions/ms-python.python-2019.10.44104
197M    ~/.local/share/code-server/extensions/ms-python.python-2020.1.58038
```

## Notes

Apparently, vscode should clean old extension when it is restarted: https://github.com/microsoft/vscode/issues/132896
A restart of code-server doesn't do that.

PS: thank you for working and maintaining this nice project!

**Comment by jsjoeio** [comment]
Hmm...has code-server ever done this? @code-asher I wonder if need to implement it in our fork.

**Comment by code-asher** [comment]
I am not sure if we were doing this before!  It sounds like there is
probably some cleanup routine somewhere we should be calling.

**Comment by matttbe** [comment]
I no longer see duplicated entries. I guess this is fixed, right?

**Comment by jsjoeio** [comment]
@matttbe must have been fixed upstream - thanks for confirming!
