### ISSUE TITLE
Broken link on code-server install docs

### ISSUE THREAD

**Issue by NyleCohen** [coder/code-server#4545]
On the [code-server](https://coder.com/docs/code-server/latest/install#installsh) docs website, the "install script" hyperlink goes to [this 404](https://coder.com/docs/code-server/latest/install.sh). This link should either be fixed or be changed to the [install.sh script on github.](https://github.com/cdr/code-server/blob/main/install.sh)

**Comment by jsjoeio** [comment]
Whoops! Looks like we need to fix that. Thanks for reporting!

**Comment by im-coder-lg** [comment]
I hit the 404. Maybe I have to check this. I will post DevTools Console logs here soon.

**Comment by im-coder-lg** [comment]
Over [here](https://coder.com/docs/code-server/latest/install#installsh):
```console
Failed to load resource: net::ERR_FILE_NOT_FOUND
dc.ads.linkedin.com/:1 Failed to load resource: net::ERR_BLOCKED_BY_RESPONSE.NotSameOriginAfterDefaultedToSameOriginByCoep
install#installsh:1 Access to fetch at 'https://s-install.avcdn.net/aos/assets/prod/translations/Locale-en-US.json' from origin 'https://coder.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
s-install.avcdn.net/aos/assets/prod/translations/Locale-en-US.json:1 Failed to load resource: net::ERR_FAILED
VM196:1 _recent_lead_source cookie set: "Inbound Link"
/_next/data/yfJ74FBiREKmUMA0T1qLO/docs/code-server/latest/install.sh.json:1 Failed to load resource: the server responded with a status of 404 ()
```
We hit a CORS problem. I experienced this but don't know where, when and how.
Using the point-on-the-component trick, I found this:
![image](https://user-images.githubusercontent.com/76845820/143383559-5f537c6b-384f-41d1-9bc5-5993e823eb77.png)
Can't we add `https://code-server.dev/install.sh` which shows the raw code? I think that file moved directories so this is happening.

**Comment by im-coder-lg** [comment]
We should do what @NyleCohen said. I think that would work better but also, we need to make the redirect open in a new tab.

**Comment by jsjoeio** [comment]
Nice debugging @im-coder-lg!

Yes, I agree. We'll need to fix this like @NyleCohen suggested

**Comment by csharpdf** [comment]
I'm installing it with npm on a raspberry pi and I'm getting the same problem, a 404 error <del>(in addition to a bunch of warnings lol)</del> after making a request to what I believe is https://code-server.dev/install.sh
