### ISSUE TITLE
Remote component sometimes loses session with the frontend needing a full reload

### ISSUE THREAD

**Issue by lorenz** [coder/code-server#4591]
## OS/Web Information

- Web Browser: Chromium 96
- Local OS: Ubuntu
- Remote OS: Based on official container
- Remote Architecture: amd64
- `code-server --version`: 3.12.0

## Steps to Reproduce
Unknown, happens relatively rarely. Seems to happen only when the local machine goes to standby.

## Expected
code-server should reconnect to its previous session or at least open a new one.

## Actual
`Error: Connection error: Unable to reconnect; session no longer exists (b1b1f5d7-c257-4243-b73c-348edbe8d28f)` and the indicator in the bottom right spins forever on `Reconnecting to ...`. This is only recoverable by a full reload.

## Logs

These were not collected with debug logging level as this is hard to reproduce and thus the logs are from a regular working instance. This is from a window of two days around the error.
```
2021-12-06T03:13:40.777346828Z [IPC Library: Pty Host]  INFO Persistent process "4": Replaying 17128 chars and 1 size events
2021-12-06T21:12:43.347945700Z [IPC Library: Pty Host]  INFO Persistent process "71": Replaying 183 chars and 1 size events
2021-12-07T14:57:15.077819509Z [IPC Library: Pty Host]  INFO Persistent process "71": Replaying 12437 chars and 1 size events
```

## Notes

The server side was not restarted and didn't crash so I don't know why the session has gone away.

This issue can be reproduced in VS Code: Unknown, official VSCode doesn't have the affected functionality. I don't know if Codespaces is affected.

**Comment by jsjoeio** [comment]
Hmm...do you mind adding some steps to reproduce? I'm not sure how much we can help without being able to effectively reproduce this :(

**Comment by lorenz** [comment]
If I could reproduce it myself I would, but I currently can't. It happened maybe 3 times in total and always on sessions that were open for a very long time.

**Comment by jsjoeio** [comment]
Ah bummer. Okay well we can leave this open in the meantime and try and take a look in the future.
