### ISSUE TITLE
playwright does not support FreeBSD as a platform.

### ISSUE THREAD

**Issue by khng300** [coder/code-server#4596]
## OS/Web Information

- Web Browser: Firefox 95.0
- Local OS: FreeBSD 13.0
- Remote OS: macOS 12.0.1
- Remote Architecture: amd64
- `code-server --version`: N/A

## Steps to Reproduce

1. cd code-server
2. # Fix argon2 dependency to 0.28.2 to build.
3. yarn global add $PWD

## Expected

It should build.

## Actual

--- stderr ---
```
error /usr/home/khng/.config/yarn/global/node_modules/code-server/test/node_modules/playwright: Command failed.
Exit code: 1
Command: node install.js
Arguments:
Directory: /usr/home/khng/.config/yarn/global/node_modules/code-server/test/node_modules/playwright
Output:
/usr/home/khng/.config/yarn/global/node_modules/code-server/test/node_modules/playwright/lib/utils/registry.js:233
            throw new Error('Unsupported platform: ' + process.platform);
```

## Notes

This issue can be reproduced in VS Code: Yes/No

**Comment by jsjoeio** [comment]
@khng300 do you mind adding more notes to your bug report? Are you trying to contribute to code-server or just use it locally?

**Comment by khng300** [comment]
> @khng300 do you mind adding more notes to your bug report? Are you trying to contribute to code-server or just use it locally?

I am trying to run code-servee locally, but seems like the dependency playwright does not like the platform. I saw it being under test/.

**Comment by jsjoeio** [comment]
@khng300 hmm... how are you installing and running code-server locally? Can you post repro steps?

**Comment by khng300** [comment]
> @khng300 hmm... how are you installing and running code-server locally? Can you post repro steps?

```sh
$ git clone https://github.com/cdr/code-server
$ node -v
v14.18.1
$ yarn global add $PWD
yarn global v1.22.17
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "/home/khng/Workspace/code-server > @coder/logger@1.1.16" has unmet peer dependency "@google-cloud/logging@^4.5.2".
[4/4] Building fresh packages...
[1/3] ⠄ argon2
[-/3] ⠄ waiting...
error /home/khng/.config/yarn/global/node_modules/argon2: Command failed.
$ sed -i '' -e 's/"argon2": ".*"/"argon2": "0.28.2"/g' package.json 
$ yarn global add $PWD
yarn global v1.22.17
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "/home/khng/Workspace/code-server > @coder/logger@1.1.16" has unmet peer dependency "@google-cloud/logging@^4.5.2".
[4/4] Building fresh packages...
[3/3] ⠠ code-server
[-/3] ⠠ waiting...
error /home/khng/.config/yarn/global/node_modules/code-server: Command failed.
Exit code: 1
Command: ./ci/dev/postinstall.sh
Arguments:
Directory: /home/khng/.config/yarn/global/node_modules/code-server
Output:
Installing code-server test dependencies...
yarn install v1.22.17
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > ts-jest@27.0.7" has unmet peer dependency "typescript@>=3.8 <5.0".
[4/4] Building fresh packages...
error /usr/home/khng/.config/yarn/global/node_modules/code-server/test/node_modules/playwright: Command failed.
Exit code: 1
Command: node install.js
Arguments:
Directory: /usr/home/khng/.config/yarn/global/node_modules/code-server/test/node_modules/playwright
Output:
/usr/home/khng/.config/yarn/global/node_modules/code-server/test/node_modules/playwright-core/lib/utils/registry.js:180
    if (process.platform === 'linux') cacheDirectory = process.env.XDG_CACHE_HOME || _path.default.join(os.homedir(), '.cache');else if (process.platform === 'darwin') cacheDirectory = _path.default.join(os.homedir(), 'Library', 'Caches');else if (process.platform === 'win32') cacheDirectory = process.env.LOCALAPPDATA || _path.default.join(os.homedir(), 'AppData', 'Local');else throw new Error('Unsupported platform: ' + process.platform);
                                                                                                                                                                                                                                                                                                                                                                                             ^

Error: Unsupported platform: freebsd
    at /usr/home/khng/.config/yarn/global/node_modules/code-server/test/node_modules/playwright-core/lib/utils/registry.js:180:388
    at Object.<anonymous> (/usr/home/khng/.config/yarn/global/node_modules/code-server/test/node_modules/playwright-core/lib/utils/registry.js:194:3)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/usr/home/khng/.config/yarn/global/node_modules/code-server/test/node_modules/playwright/install.js:17:49)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
```

**Comment by jsjoeio** [comment]
Thank you! Now I'm a little confused. You're cloning it but then you're running `yarn global add` 🤔

What is your end goal? To run code-server locally or contribute?

If you want to use code-server, you should follow the docs and use the [install script](https://coder.com/docs/code-server/latest/install#installsh).

If you're trying to contribute, then we can look into this further.

**Comment by khng300** [comment]
> Thank you! Now I'm a little confused. You're cloning it but then you're running `yarn global add` 🤔
> 
> What is your end goal? To run code-server locally or contribute?
> 
> If you want to use code-server, you should follow the docs and use the [install script](https://coder.com/docs/code-server/latest/install#installsh).
> 
> If you're trying to contribute, then we can look into this further.

That is simple to explain: I just want to run code-server locally. I am doing so to run the current snapshot from the main branch.
Inside the install.sh I found that it boils down to a simple `yarn global add code-server`: https://github.com/cdr/code-server/blob/main/install.sh#L420
However that wouldn't succeed either. It fails due to node-argon2 was messing up their code, so the first thing to attempt going further is to use 0.28.2 of node-argon2 which reverted the broken commit.

**Comment by jsjoeio** [comment]
> I am doing so to run the current snapshot from the main branch

In this case, it sounds similar to contributing. Assuming you followed [the docs](https://coder.com/docs/code-server/latest/CONTRIBUTING#linux-specific-requirements), let's see if we can figure out what's wrong.

> so the first thing to attempt was to try 0.28.2 of node-argon2 which reverted the broken commit.

Ah, I see. Is this bug Linux specific? I'm surprised @code-asher isn't running into this as he is on Linux. 

Hmm...I really regret adding node-argon2. It's causing a lot of trouble. We are looking into replacing it potentially [here](https://github.com/cdr/code-server/issues/4422).

**Comment by khng300** [comment]
> > I am doing so to run the current snapshot from the main branch
> 
> In this case, it sounds similar to contributing. Assuming you followed [the docs](https://coder.com/docs/code-server/latest/CONTRIBUTING#linux-specific-requirements), let's see if we can figure out what's wrong.
> 
> > so the first thing to attempt was to try 0.28.2 of node-argon2 which reverted the broken commit.
> 
> Ah, I see. Is this bug Linux specific? I'm surprised @code-asher isn't running into this as he is on Linux.
> 
> Hmm...I really regret adding node-argon2. It's causing a lot of trouble. We are looking into replacing it potentially [here](https://github.com/cdr/code-server/issues/4422).

My guess for that problem was that node-argon2 was only trying to enforce C++17 on Linux only.

**Comment by jsjoeio** [comment]
> My guess for that problem was that node-argon2 was only trying to enforce C++17 on Linux only. Here is the fix for this part: ranisalt/node-argon2#332

Oh wow! You submitted a patch upstream - that is awesome! 🙌 I hope that resolves it.

**Comment by khng300** [comment]
> > My guess for that problem was that node-argon2 was only trying to enforce C++17 on Linux only. Here is the fix for this part: [ranisalt/node-argon2#332](https://github.com/ranisalt/node-argon2/pull/332)
> 
> Oh wow! You submitted a patch upstream - that is awesome! 🙌 I hope that resolves it.

That is only one of the problem, another one is actually mentioned above. I do want to know if it is safe to skip the test/ module as a temporary workarond.

**Comment by jsjoeio** [comment]
> That is only one of the problem, another one is actually mentioned above. I do want to know if it is safe to skip the test/ module as a temporary workarond.

Yes! Any testing modules can be safely skipped :)

**Comment by jsjoeio** [comment]
node-rs now publishes an argon2 package. Might help here: https://github.com/napi-rs/node-rs/tree/main/packages/argon2
