### ISSUE TITLE
Patch configuring the display language 

### ISSUE THREAD

**Issue by jsjoeio** [coder/code-server#4598]
Previously, we supported the ability to [configure the Display Language](https://code.visualstudio.com/docs/getstarted/locales). As a result of switching to VS Code's upstream server, we have lost this feature with the 4.0.0 upgrade.

## Does it work upstream?

Apparently, no. If you go to vscode.dev and try to install a language pack, you get the following error messages:
![image](https://user-images.githubusercontent.com/3806031/145483615-a5079202-61d5-4ea1-bb6c-021f6d6f976d.png)

Same with Codespaces
![image](https://user-images.githubusercontent.com/3806031/145483858-62f782c7-9de0-49f5-b314-c1e994667f7d.png)

## How did it work before in code-server?

I believe we had to patch it to get it to work. We can investigate readding the patch, or even submitting a patch upstream to get this functionality both in code-server and vscode.dev/Codespaces

**Comment by jsjoeio** [comment]
Didn't mean to close this!

**Comment by jsjoeio** [comment]
We used to patch this before. @code-asher patched this previously and will push up his patch. That's a good place to look. It will be on his fork here.

**Comment by code-asher** [comment]
Linked above, note that you need to make a full build to test.

**Comment by jsjoeio** [comment]
Fixed via https://github.com/coder/vscode/pull/34
