### ISSUE TITLE
Builtin extensions always require reload

### ISSUE THREAD

**Issue by jsjoeio** [coder/code-server#4600]
@bpmct found an issue with the extensions panel while testing the [4.0.0 release](https://github.com/cdr/code-server/pull/4597#issuecomment-990381354).

## Steps to Reproduce

1. run code-server with 0 extensions installed
```shell
# create an empty directory
# that way we don't have to uninstall all extensions
mkdir empty-dir
code-server --extensions-dir empty-dir
```
2. open extensions panel

### Expected

See list of Popular Extensions
![image](https://user-images.githubusercontent.com/3806031/145621583-f0a38617-3eb6-4278-a158-5e3c307b8895.png)

### Actual (v3.12.0)

Works as expected.

![image](https://user-images.githubusercontent.com/3806031/145621583-f0a38617-3eb6-4278-a158-5e3c307b8895.png)

### Actual (v4.0.0)

Works as expected (running in dev mode with `yarn watch`)

![image](https://user-images.githubusercontent.com/3806031/145623101-88c142c3-a909-4815-851e-504ab4093ff1.png)

### Actual (vscode.dev)

Works as expected.

![image](https://user-images.githubusercontent.com/3806031/145621746-e3edd231-286b-4a9c-b792-aa057ad24029.png)

### Actual (Codespaces)

🐛 Does not show Popular Extensions

![image](https://user-images.githubusercontent.com/3806031/145622265-ff9e2966-5591-4a5c-9938-83bfb44af53a.png)

### Actual (VS Code)

Works as expected.

![image](https://user-images.githubusercontent.com/3806031/145621897-1c3fd124-0ab5-4f6b-b5f4-ae02774a74ce.png)

**Comment by jsjoeio** [comment]
We don't think this is an issue but will retest after 4.0.0 is out.

**Comment by benz0li** [comment]
### Actual (https://vscode-r.jupyter.b-data.ch, v4.0.0)

Shows popular extensions. Says 'Reload Required' for _included_ extension; pre-installed extensions* not affected.

*Pre-installed using `code-server --extensions-dir /opt/code-server/vendor/modules/code-oss-dev/extensions --install-extension ms-python.python` for example.

![popular-extensions](https://user-images.githubusercontent.com/20233085/145862346-68171ef5-439d-4af6-a035-2ee653f7bbb9.png)

**Comment by jsjoeio** [comment]
Fixed via https://github.com/coder/vscode/pull/32
