### ISSUE TITLE
Use getopt for parsing command-line arguments

### ISSUE THREAD

**Issue by jawnsy** [coder/code-server#4615]
We wrote our own argument-parsing code: https://github.com/cdr/code-server/blob/385be36dea427a3311fba440fb7e06fda66e864d/install.sh#L155-L162

It would be better to switch to `getopt` to simplify this, so that we don't our own custom code, and so that we support all the constructs that people expect (no value allowed, mandatory value, optional value)

**Comment by Liltreks** [comment]
Derek Allegra
