### ISSUE TITLE
Unable to open in existing instance outside of code-server

### ISSUE THREAD

**Issue by code-asher** [coder/code-server#4620]

**Comment by jsjoeio** [comment]
Can you elaborate on this?

**Comment by code-asher** [comment]
Opening a file in a running instance of code-server only works inside VS Code's own terminal and not outside in an external terminal like it used to:

```
$ code-server -r /path/to/file
[2021-12-16T17:30:07.975Z] error got error from VS Code {"error":{"errno":"ENOENT","code":"ENOENT","syscall":"connect","address":"/run/user/1000/vscode-ipc-11493680-caf5-47f6-9318-e6a6838123ac.sock"}}
```

**Comment by code-asher** [comment]
The problem is that we no longer store the socket path so code-server is not able to get the latest socket.

I think the move will be either to delegate this functionality to VS Code by calling its CLI instead of hitting the socket directly.

**Comment by jsjoeio** [comment]
Fixed via https://github.com/coder/vscode/pull/33
