### ISSUE TITLE
Absolute/Relative Path Handling

### ISSUE THREAD

**Issue by w0otness** [coder/code-server#4623]
## OS/Web Information

- Web Browser: Chrome
- Local OS: Windows 10
- Remote OS: Amazon Linux 2
- Remote Architecture: EC2 Cloud9
- `code-server --version`: 4.0.0

## Steps to Reproduce

1. Have [sample ](https://gist.github.com/w0otness/cfe5347472e9e900ce18398923dc8781) typescript project open.
2. Run `npm i`.
3. Open bug.ts from tree explorer (as you normally would).
4. Note that typescript does not display error on line 2, but displays 1 problem in the problem window.
5. Double clicking the problem opens the file in a new editor tab, but the breadcrumb displays the absolute path, and the correct lines are highlighted as error.

## Expected
Consistent handling of absolute/relative paths to match local VS Code.

## Actual
Absolute paths are used where relative should be.

## Notes

It doesn't matter whether you use the VS Code version of typescript or the workspace version, the behaviour is the same.

This issue can be reproduced in VS Code: No
Step 5 just focuses the same editor window instead of a opening new one.

This also seems to effect Yarn 2 PnP, as the ZipFS can mount a zip as a folder correctly, but the `yarn dlx @yarnpkg/sdks vscode` Typescript server never finds the modules, I suspect it's due to the absolute/relative path handling.

This issue existed prior to 4.0.0 also.

**Comment by jsjoeio** [comment]
Do you know if this exists in 3.12.0?

**Comment by w0otness** [comment]
Yes it does.

**Comment by jsjoeio** [comment]
Hmm...I'm not sure if this is reproducing for me (macOS + Brave + 4.0.0). I see the problem in the Problems tab and when I click it, it shows the error and it says `[2, 0]` so I think it's pointing to the right line (and showing on the right line). Am I missing something?

## Video

https://user-images.githubusercontent.com/3806031/146601167-d37909a9-b759-4aa8-90a3-92d00f4bd681.mov

**Comment by jsjoeio** [comment]
> Yes it does.

Thanks for confirming! Our current priority is to focus on 4.0.0-specific issues. I'm going to move it to the next milestone.

**Comment by w0otness** [comment]
Actually, You did capture it! At 6 seconds with bug.ts open, the line 2
isnt squiggled, and the breadcrumb only says bug.ts (relative path, if it
was in src it would only show src>bug.ts). Then at 7 seconds when you click
the problem, it replaces the relative path window with the abolute path
window, and you can see the breadcrumb change to display absolute path from
root dir eg />users>etc>etc.

**Comment by jsjoeio** [comment]
Okay there's a lot happening here so I guess that's why I missed it 😅

### Problem 1: TS error squiggle is missing

> At 6 seconds with bug.ts open, the line 2 isnt squiggled

I see this! I wonder if it could be one of my VS Code Settings? 🤔

### Problem 2: relative path window is replaced with absolute path window

> Then at 7 seconds when you click
the problem, it replaces the relative path window with the abolute path
window, and you can see the breadcrumb change to display absolute path from
root dir eg />users>etc>etc.

I see this now too! I thought that was normal lol

Did I capture these two problems accurately?

**Comment by w0otness** [comment]
In essence yes you got the surface issues, though the squiggle is from
Typescript server, and won't be caused by settings.

I think the underlying cause is that local vscode uses relative paths when
running typescript server, but the code-server implementation gives it
absolute paths, so the relative opened file doesnt register to Typescript
server instance as the file it needs to draw squiggles on, also cause the
problem list to open using the absolute path.

We need to drill down how local vscode differentiates relative vs absolute
paths in general, as it seems it treats the same
file opened by either way as 2 different files, which is having these
secondary effects in Typescript, and extensions.

The Yarn2+Typescript depends on ZipFs extension, I've tested and the
extension correctly mounts zip folders in code-server by itself.

However, the custom typescript wrapper Yarn 2 uses to have the typescript
binary access node_module from the zips throws typescript errors of "cant
find modules", the same error you would get from a standard typescript
setup if you deleted a dependency in your node_modules folder.

This may affect other extensions which depend on path implementations to be
a certain way.

**Comment by w0otness** [comment]
I have just installed version 4.0.1, and can confirm the original reason for this issue may be resolved.

When opening bug.ts, and clicking the problem line, the correct "relative" path editor tab is focussed, and not opened in a new editor tab with an "absolute" path.

If we can have some others confirm, then we can close this issue, and I will open a new issue to examine why Yarn PnP Editor SDK (https://yarnpkg.com/getting-started/editor-sdks) doesn't work.

**Comment by w0otness** [comment]
Just confirmed that the Yarn PnP Editor SDK issue is a Yarn issue something with v3.1.0 that seems to be resolved in 3.1.1. Coretools is still installing 3.1.0 by default and requires manual updating to 3.1.1 at which point code-server (and local vscode) picks up the correct typescript server.

**Comment by jsjoeio** [comment]
Confirmed it appears to be fixed for me as well! Thank you for checking and following up. I'm going to close this.

## Screenshot
![image](https://user-images.githubusercontent.com/3806031/148605423-af71d0ef-2738-4a39-a10c-03a63a8f4cdd.png)
