### ISSUE TITLE
upgrade to prelease version 4.0.0 fails with vscode.html not found

### ISSUE THREAD

**Issue by lethargosapatheia** [coder/code-server#4639]
## OS/Web Information

- Web Browser: Firefox 95.0
- Local OS: Mac OS Monterey 12.1
- Remote OS: Ubuntu 20.04.3
- Remote Architecture: amd64
- `code-server --version`: 4.0.0

## Steps to Reproduce

1. downloading deb pkg from https://github.com/cdr/code-server/releases/download/v4.0.0/code-server_4.0.0_amd64.deb
2. upgrading from 3.12.0 to 4.0.0 by issuing:
```
dpkg -i code-server_4.0.0_amd64.deb
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'code-server' instead of '/tmp/code-server_4.0.0_amd64.deb'
The following packages will be upgraded:
  code-server
1 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
Need to get 0 B/221 MB of archives.
After this operation, 246 MB of additional disk space will be used.
Get:1 /tmp/code-server_4.0.0_amd64.deb code-server amd64 4.0.0 [221 MB]
(Reading database ... 88122 files and directories currently installed.)
Preparing to unpack .../code-server_4.0.0_amd64.deb ...
Unpacking code-server (4.0.0) over (3.12.0) ...
Setting up code-server (4.0.0) ...
```

## Expected
To work as normally, just like on 3.12.0

## Actual
when accessing code-server over the web: I get:
```sh
ENOENT: no such file or directory, open '/usr/lib/code-server/src/browser/pages/vscode.html'
```

These are the only files that I can see here:
```
ls /usr/lib/code-server/src/browser/pages
error.css  error.html  global.css  login.css  login.html
```
## Logs

Once this is done, replicate the issue you're having then collect logging
information from the following places:

    1. The most recent files from ~/.local/share/code-server/coder-logs.
Unfortunately there's no output in the log files, despite running the process with `--log debug` as seen in ps aux:
```
/usr/lib/code-server/lib/node /usr/lib/code-server --log debug
```
```
~/.local/share/code-server/coder-logs# tail -f *
==> code-server-stderr.log <==

==> code-server-stdout.log <==
```
    2. The browser console.
    Most probably irrelevant, but:
```
Layout was forced before the page was fully loaded. If stylesheets are not yet loaded this may cause a flash of unstyled content.
```
    3. The browser network tab.
    Just the 404 not found error.

## Screenshot
<img width="865" alt="vs_code_404" src="https://user-images.githubusercontent.com/22618815/146400903-1d67e9be-b2ad-4882-9e3a-2a117c8ce8bb.png">

Looking forward to any suggestions :)

**Comment by jsjoeio** [comment]
Nice debugging and thank you for the detailed notes! 

> /usr/lib/code-server/src/browser/pages/vscode.html

That's right. We removed this.

I'm trying to think what could be causing this? 🤔 Is it cached? Is it something else? (Upgrading to 4.0.0 didn't succeed)

Any ideas @code-asher?

**Comment by lethargosapatheia** [comment]
@jsjoeio Thanks for pointing this out. I didn't know vscode.htlm existed in the previous version. I copied the one from 3.12.0 and placed it in the same path with version 4.0.0 and it works :) (funnily enough)

**Comment by jsjoeio** [comment]
Ha! No way. Well shoot I'm glad the fix was that easy. Go team :D

**Comment by code-asher** [comment]
Did you restart code-server after upgrading?

**Comment by lethargosapatheia** [comment]
Sorry for being misleading earlier. Copying vscode.html didn't actually work. It only displayed the initial login page. After entering the password I get a blank page. Several other files are missing vscode.browserfied.js, workbench.js :)

@code-asher: yes, I did.

**Comment by lethargosapatheia** [comment]
@code-asher Sorry, I'm dumb. I hadn't actually, I thought I did.
So the error must have come from the fact that the previous version was still trying to access the what is now removed vscode.html - what you were probably inferring :)
After restarting, it seems to be working correctly.

**Comment by TobiaszCudnik** [comment]
> Did you restart code-server after upgrading?

The AUR package should auto restart via sysd (but it doesnt). Just FYI.
