### ISSUE TITLE
Maintainers are on vacation! 🎄🏖️

### ISSUE THREAD

**Issue by jsjoeio** [coder/code-server#4649]
As mentioned in [this Discussion comment](https://github.com/coder/code-server/discussions/4603#discussioncomment-1837875), we will be on vacation for part of the coming weeks. This means we'll be slow to respond to issues and discussions.

## Week of December 20th

- @jsjoeio out for whole week
- @code-asher in for 2-3 days

## Week of December 27th

- @jsjoeio out for whole week
- @code-asher out for whole week

## Week of January 3rd

- @jsjoeio in for whole week
- @code-asher in for whole week

**Comment by benz0li** [comment]
🎄

**Comment by im-coder-lg** [comment]
Happy holidays!
