### ISSUE TITLE
An unexpected error occurred that requires a reload of this page. The workbench failed to connect to the server (Error: Time limit reached)

### ISSUE THREAD

**Issue by cedvict** [coder/code-server#4654]
Hi there! 👋

I have some issues after deploy code server on kubernetes accessible through a subpath.

## OS/Web Information

- Web Browser: Chrome
- Local OS: Centos
- Remote OS:
- Remote Architecture:
- `code-server --version`: 3.11.1

## Steps to Reproduce

1. Deploy Code-server on kubernetes
2. In Ingress set a subpath to access to code-server
3.

## Actual

![image](https://user-images.githubusercontent.com/8941921/146912279-808b5214-8847-4f9b-9644-7209bb044a52.png)

![image](https://user-images.githubusercontent.com/8941921/146912418-51f21ca7-fba3-4a80-a8c7-dccfd0ba16ac.png)

## Notes

This issue can be reproduced in VS Code: Yes/No

**Comment by cedvict** [comment]
Please Can we specify a specific port for websocket. We have a security constraint which disables port 80 or the code server tries to establish a socket with port 80

**Comment by jsjoeio** [comment]
> Please Can we specify a specific port for websocket.

I don't know if that's possible right now 🤔 cc @code-asher 

cc @bpmct - you might find this interesting

**Comment by code-asher** [comment]
The websocket URL is not possible to configure at the moment but it is
supported in the code.

If port 80 is disabled code-server should not be loading at all should
it?  code-server uses the same port for the websocket that is used to
serve the HTML.
