### ISSUE TITLE
The "default" shell

### ISSUE THREAD

**Issue by aghasemi** [coder/code-server#4661]
Hi,

The default shell of my VPS is bash when I SSH into it. It is also confirmed by ` echo $SHELL`.

However, the new terminal menu item in the code server opens sh, and there $SHELL is sh too. 

I tried `chsh` and it also says my default shell is `/bin/bash`, but the code server doesn't recognise it :-/

Is there something else I need to do? It is Ubuntu 20.04.

Thanks a lot
Best

**Comment by kensiy** [comment]
press ctrl+shift+p
enter Terminal: Select Default Profile

**Comment by aghasemi** [comment]
Great. Thanks.
