### ISSUE TITLE
[4.0.0] Invalid date in extension details page

### ISSUE THREAD

**Issue by rhld16** [coder/code-server#4666]
## OS/Web Information

- Web Browser: Edge
- Local OS: Windows 10
- Remote OS: Ubuntu 20.04
- Remote Architecture: amd64
- `code-server --version`: 4.0.0

## Steps to Reproduce

1. View any extension details page
2. Inspect either `Released on` or `Last updated`  values

## Expected

Displays correct date for both entries

## Actual

Both dates appear as `Invalid date`

## Screenshot

![image](https://user-images.githubusercontent.com/24809571/147601006-2f340f2f-6f0c-48dc-a95a-e5d9649e31a1.png)

## Notes

This issue can be reproduced in VS Code: No

**Comment by jsjoeio** [comment]
Woah, that's weird. Maybe something changed around how the date is parsed into a string from a `Date` (if I had to guess). Thanks for the report!

**Comment by jsjoeio** [comment]
@code-asher I think this can be fixed after the release. Thoughts?

**Comment by code-asher** [comment]
Agreed.  I wonder if this is an issue with Open VSX sending something
unexpected.

**Comment by rhld16** [comment]
This bug seems to have been fixed in the meantime
