### ISSUE TITLE
expand/collapse button doesn't work on mobile device

### ISSUE THREAD

**Issue by Buntu0001** [coder/code-server#4671]
## OS/Web Information

- Web Browser: iOS Safari, Chrome
- Local OS: iPadOS 15.1
- Remote OS: Ubuntu 20.04 x64
- Remote Architecture: amd64
- `code-server --version`: 3.12.0

## Steps to Reproduce

1. enter to workspace
2. click or touch expand/collapse button
3. not work :(

## Expected

when i click expand/colllapse button, tab should expand/collapse

## Actual

expand/collapse button (outline, workspace etc...) not work when i clicked

## Logs

Probably not needed in this case but if required I can provide them.

## Screenshot

https://user-images.githubusercontent.com/57615703/147843460-add9853a-07f7-467c-a606-533b0dbd58bd.MP4

## Notes

This issue can be reproduced in VS Code: No

**Comment by jsjoeio** [comment]
Thank you for the video! Can you reproduce this on vscode.dev?

**Comment by Buntu0001** [comment]
yes

**Comment by jsjoeio** [comment]
@Buntu0001 ah okay then that means it's an upstream issue.
