### ISSUE TITLE
Existing and new jupyter notebooks not loading in 3.12.0, 4.0.0-pre-release, or 4.0.1

### ISSUE THREAD

**Issue by vprzybylo** [coder/code-server#4689]
Amazing work! I am thoroughly enjoying remote dev using code-server; thanks for the hard work!
This commentary is similar to #4395.

## OS/Web Information

- Web Browser: Chome/Safari
- Local OS: MacOS
- Remote OS: Linux
- Remote Architecture: x86_64
- `code-server --version`: 3.12, 4.0.0, and 4.0.1 tested

## Issue
Existing jupyter notebooks and new notebooks aren't appearing to execute.  I see the jupyter menu for execution of cells and outline but the page never loads (loading bar keeps panning back and forth).  
 
## Steps to Reproduce

1. I am using [this dockerfile](https://github.com/vprzybylo/cocpit/blob/dev/docker_builds/Dockerfile_codercom) and [this docker-compose.yml](https://github.com/vprzybylo/cocpit/blob/dev/docker_builds/docker-compose.yml)
2. My containers are then spun up using `UID_GID="$(id -u):$(id -g)" docker-compose -f /raid/data/docker_builds/docker-compose.yml up --build` in a slurm script.
3. I navigate to a chrome or safari browser on the host server on port 8443 and try to open a notebook, but it just hangs.

<img width="876" alt="Screen Shot 2022-01-05 at 3 15 01 PM" src="https://user-images.githubusercontent.com/32338353/148285714-5af5f8cb-117f-429c-9b71-e845a39b2bf3.png">

## Logs
There are no errors in my logs and I see an active runtime status for jupyter (ms-toolsai.jupyter-2021.11.1001552333) and python (ms-python.python-2021.12.1559732655).

## Notes

I have tried including --install-extension ms-python.python and jupyter in the dockerfile and removing it and installing it through the extension marketplace but that does not make a difference. I also have tried installing from .vsix but had compatibility issues.  Lastly, I included "enabledApiProposals" list to the jupyter extension package.json and reinitialized code-server but the changes were not picked up.

**Comment by jsjoeio** [comment]
Thanks for the thorough report @vprzybylo! I have tested it on v4.0.1 on macOS with Brave and I cannot reproduce. Here is more info about the setup I'm testing:
- code-server v4.0.1
- Python (extension) v2021.12.1559732655 with Python 3.7.9
- Jupyter v2021.11.1001552333

In my `settings.json`, I also have this set:
```json
  "workbench.editorAssociations": {
    "*.ipynb": "jupyter.notebook.ipynb"
  },
```

## Video

This is what happens with an existing notebook.

https://user-images.githubusercontent.com/3806031/148299072-30f4f0bc-a989-4cea-bbba-ae949d91dc06.mov

And this is from a new notebook:
![image](https://user-images.githubusercontent.com/3806031/148299306-a08dfb6c-b59a-463f-9112-9c062a5c7747.png)


v4.0.1 also uses Open VSX by default so if you search for it in the Extensions panel, it should install the latest versions. Can you try that or try adjusting your `settings.json` and let us know if that works?

**Comment by benz0li** [comment]
Most probably the same problem as https://github.com/coder/code-server/issues/3782#issuecomment-997335327:

> *  http://127.0.0.1:8080/vscode/ does not work
> *  http://127.0.0.1:8080/vscode/?folder=%2Fhome%2Fjovyan works perfect.

@vprzybylo Meaning, one must explicitly open a folder (File > Open Folder...) before opening a Jupyter notebook.

**Comment by CNorato** [comment]
I think I have a similar issue.
My codeserver URL is `http://ipaddress/codeserver/?folder=/home/ubuntu/CodePlace/Code_Python` and the codeserver version is `v4.0.1`.
When I was in `~/CodePlace/Code_Python/` and try to open a notebook file, I got these errors.
![console_logs1](https://user-images.githubusercontent.com/33372866/148369655-6e9892b0-1d6c-4869-973e-8125b4310049.png)
And when I went into `~/CodePlace/Code_Python/NotebookTest` and open the notebook file, I got the previous errors and a new error.
![console_logs2](https://user-images.githubusercontent.com/33372866/148369866-64132886-3990-40f8-8472-cdf7520b566b.png)

**Comment by benz0li** [comment]
@CNorato Do you access code-server in private/incognito mode?  
👉 If so: Try disabling private/incognito mode or make an exception for your IP address/domain.

Service workers do not work in private/incognito mode.

**Comment by CNorato** [comment]
@benz0li Thank you for your advice. I have tried to disable all the private/incognito options, but it still doesn't work.
I think maybe is the problem of HTTP. However, I can't change to HTTPS for now due to some reasons. If I have time to solve the problem I will reply to this issue ASAP.

**Comment by vprzybylo** [comment]
Hi all, thanks for the help!  I have updated my settings.json, gone to file -> open folder before opening a notebook, and am not in an incognito window.  Open VSX is not appearing in the extension panel for me - thoughts?  Perhaps opening through an insecure domain is causing the issue (see warning in screenshot)? I've also noticed that when browsing an extension, I don't see any text under details, which could be related.   Perhaps I should talk with my admins regarding an SSL certificate following #1627.
<img width="1907" alt="Screen Shot 2022-01-06 at 10 53 07 AM" src="https://user-images.githubusercontent.com/32338353/148414888-47f7dcae-2a34-4074-95ea-1ddde3846af4.png">

**Comment by fritterhoff** [comment]
> @benz0li Thank you for your advice. I have tried to disable all the private/incognito options, but it still doesn't work. I think maybe is the problem of HTTP. However, I can't change to HTTPS for now due to some reasons. If I have time to solve the problem I will reply to this issue ASAP.


> Hi all, thanks for the help! I have updated my settings.json, gone to file -> open folder before opening a notebook, and am not in an incognito window. Open VSX is not appearing in the extension panel for me - thoughts? Perhaps opening through an insecure domain is causing the issue (see warning in screenshot)? I've also noticed that when browsing an extension, I don't see any text under details, which could be related. Perhaps I should talk with my admins regarding an SSL certificate following #1627. <img alt="Screen Shot 2022-01-06 at 10 53 07 AM" width="1907" src="https://user-images.githubusercontent.com/32338353/148414888-47f7dcae-2a34-4074-95ea-1ddde3846af4.png">

@vprzybylo as already mentioned in your screenshot, in both cases this issue is caused because the lack of `https://`. several features *only* work using `https://`

**Comment by vprzybylo** [comment]
Thanks for the response! Closing this issue; I will work on getting an SSL certificate.

**Comment by pppppppan** [comment]
> I think I have a similar issue. My codeserver URL is `http://ipaddress/codeserver/?folder=/home/ubuntu/CodePlace/Code_Python` and the codeserver version is `v4.0.1`. When I was in `~/CodePlace/Code_Python/` and try to open a notebook file, I got these errors. ![console_logs1](https://user-images.githubusercontent.com/33372866/148369655-6e9892b0-1d6c-4869-973e-8125b4310049.png) And when I went into `~/CodePlace/Code_Python/NotebookTest` and open the notebook file, I got the previous errors and a new error. ![console_logs2](https://user-images.githubusercontent.com/33372866/148369866-64132886-3990-40f8-8472-cdf7520b566b.png)

hi ,i have same issue.
Did you solve it?

**Comment by CNorato** [comment]
> 

yes, `https://` did work.

**Comment by jsjoeio** [comment]
@sheljoy can you open a new bug report?

**Comment by hanson-young** [comment]
thank god! https:// did work.

**Comment by Andreilinch** [comment]
thank you a lot, https fix the problem with jupyter cells visibility
