### ISSUE TITLE
Tabnine extension specific configs page not loading

### ISSUE THREAD

**Issue by mtb0x1** [coder/code-server#4690]
## OS/Web Information

- Web Browser: firefox 95.0.2
- Local OS:  windows 10
- Remote OS: windows 10+wsl2
- Remote Architecture: docker using wsl2 backend
- `code-server --version`: 3.12.0 4cd55f94c0a72f05c18cea070e10b969996614d2

## Steps to Reproduce

1. Install tabnine extension
2. Add port mapping in docker -p 5555:5555
3. Access tabnine internal setup configuration page by clicking 'tabnine' in the bottom bar in code-server

## Expected

Access to tabnine internal setup configuration page

## Actual

Browser couldn't load page :

"The connection was reset

The connection to the server was reset while the page was loading .... etc"

## Logs

root@eb5b6e1eb57c:/# code-server --log debug
[2022-01-05T22:07:43.707Z] info  code-server 3.12.0 4cd55f94c0a72f05c18cea070e10b969996614d2
[2022-01-05T22:07:43.708Z] info  Using user-data-dir ~/.local/share/code-server
[2022-01-05T22:07:43.723Z] info  Using config file ~/.config/code-server/config.yaml
[2022-01-05T22:07:43.723Z] info  HTTP server listening on http://127.0.0.1:8080
[2022-01-05T22:07:43.723Z] info    - Authentication is enabled
[2022-01-05T22:07:43.723Z] info      - Using password from ~/.config/code-server/config.yaml
[2022-01-05T22:07:43.723Z] info    - Not serving HTTPS

## Screenshot

![image](https://user-images.githubusercontent.com/39337159/148296645-84709ad3-1714-4821-9281-f8f1857b9b32.png)

**Comment by jsjoeio** [comment]
Can you test this on the latest release (4.0.1) and let us know if the issue persists?

**Comment by dmitriypavlov** [comment]
Same here, issue persists on 4.0.1 and always been.

**Comment by jsjoeio** [comment]
Hmm...I'm running 4.0.1 locally on macOS + Brave and cannot reproduce this.

## Video

https://user-images.githubusercontent.com/3806031/148603158-9a19fa3c-dd87-4bc0-85fd-9ed9cbb2803e.mov

Are there any messages in the browser console or server logs? Are you accessing via HTTPS?

**Comment by smartyfeed** [comment]
Doesn't work for me aswell.
code-server: v4.0.1
VS Code: v1.63.0
Local OS: tested on Windows 10 and iPadOS 15.3
Remote OS: Debian 11.2.0
![image](https://user-images.githubusercontent.com/20574885/148720343-0a6ef787-de8b-488f-842f-6524d0261eaa.png)

**Comment by chesal** [comment]
> Hmm...I'm running 4.0.1 locally on macOS + Brave and cannot reproduce this.
> ## Video
> Screen.Recording.2022-01-07.at.1.28.00.PM.mov
> 
> Are there any messages in the browser console or server logs? Are you accessing via HTTPS?

HTTP only

**Comment by jsjoeio** [comment]
> HTTP only

That's probably your issue then. Can you check the browser console to see if there are any errors?

**Comment by smartyfeed** [comment]
I am accessing code-server via HTTPS and the issue persists. @jsjoeio

**Comment by jsjoeio** [comment]
@smartyfeed can you provide steps to reproduce? I tried earlier and didn't have any luck. What does your setup look like? And are there any browser logs you can share?

**Comment by godsey** [comment]
I have this problem. I run on a hosted VM.  If I want to use TabNine I have to ssh into the host and access code-server via http://127.0.0.1:8080/
ssh -L 8080:127.0.0.1:8080 -L 5555:127.0.0.1:5555 user@devhost
