### ISSUE TITLE
Document cookie, PASSWORD and HASHED_PASSWORD environment variables

### ISSUE THREAD

**Issue by jsjoeio** [coder/code-server#4691]
## Steps to Reproduce

1. `echo -n "thisismypassword" | npx argon2-cli -e`
2. `HASHED_PASSWORD="<hash>" code-server`
3. Try logging in

## Expected

It should work

## Actual

Incorrect password

Reported here https://github.com/coder/code-server/discussions/4684

**Comment by ykazakov** [comment]
Same problem here with the only difference that we use the `key` cookie to (automatically) authenticate the users as [mentioned here](https://github.com/coder/code-server/issues/1189#issuecomment-556092920).

B.t.w., I searched the [docks](https://coder.com/docs/code-server/v4.0.1) and neither the environment variables `PASSWORD` or `HASHED_PASSWORD`, nor the authentication cookie `key` are mentioned anywhere. The environmental variables are mentioned in `code-server --help` but not the cookie. Should these things be documented or are they subject to changes?

**Comment by ykazakov** [comment]
Oh, looks like the authentication cookie was renamed (again) in #4548 to `code-server-session`.
Setting the hashed password using the new cookie works as before. Tested for 4.0.0 and 4.0.1. I still wish this method had been documented.

**Comment by jsjoeio** [comment]
> Should these things be documented or are they subject to changes?

I checked as well and don't see them. Very strange. I thought we had docs on this but I guess not. Thanks for raising this! 

> Oh, looks like the authentication cookie was renamed (again) in #4548 to code-server-session.
Setting the hashed password using the new cookie works as before. Tested for 4.0.0 and 4.0.1. I still wish this method had been documented.

Ah, I forgot that happened. Yes, you shouldn't have to go digging to find this. Thank you for testing! Where would you expect to find this information in the docs?

**Comment by gerardo-junior** [comment]
+1 on https://docs.linuxserver.io/images/docker-code-server
