### ISSUE TITLE
Cannot reconnect. Please reload the window.

### ISSUE THREAD

**Issue by kexirong** [coder/code-server#4693]
## OS/Web Information

- Web Browser: Google Chrome 97.0.4692.71
- Local OS: windows 11
- Remote OS: centos 8
- Remote Architecture: amd64
- `code-server --version`: 4.0.1
 
same of #1884

```
 INFO [Service Worker] registered
log.ts:301  INFO [remote-connection][ExtensionHost][1a408…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
log.ts:301  INFO [remote-connection][ExtensionHost][1a408…][reconnect] resolving connection...
log.ts:301  INFO [remote-connection][ExtensionHost][1a408…][reconnect] connecting to 10.1.1.182:443...
log.ts:301  INFO [remote-connection][ExtensionHost][1a408…][reconnect] reconnected!
log.ts:301  INFO [remote-connection][ExtensionHost][1a408…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
log.ts:301  INFO [remote-connection][ExtensionHost][1a408…][reconnect] resolving connection...
log.ts:301  INFO [remote-connection][ExtensionHost][1a408…][reconnect] connecting to 10.1.1.182:443...
log.ts:301  INFO [remote-connection][ExtensionHost][1a408…][reconnect] reconnected!
log.ts:313   ERR Error received from starting extension host (kind: Remote)
log.ts:313   ERR The remote extenion host took longer than 60s to send its ready message.
log.ts:301  INFO [remote-connection][ExtensionHost][1a408…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
log.ts:301  INFO [remote-connection][ExtensionHost][1a408…][reconnect] resolving connection...
log.ts:301  INFO [remote-connection][ExtensionHost][1a408…][reconnect] connecting to 10.1.1.182:443...
log.ts:313   ERR [remote-connection][ExtensionHost][1a408…][reconnect][10.1.1.182:443] received error control message when negotiating connection. Error:
log.ts:313   ERR Error: Connection error: Unknown reconnection token (seen before)
    at W (remoteAgentConnection.ts:732:17)
    at remoteAgentConnection.ts:327:17
    at l.fire (event.ts:577:16)
    at u.fire (ipc.net.ts:511:19)
    at r._receiveMessage (ipc.net.ts:873:27)
    at ipc.net.ts:818:73
    at l.fire (event.ts:577:16)
    at d.acceptChunk (ipc.net.ts:284:21)
    at ipc.net.ts:245:51
    at browserSocketFactory.ts:197:39
log.ts:313   ERR [remote-connection][ExtensionHost][1a408…][reconnect] A permanent error occurred in the reconnecting loop! Will give up now! Error:
log.ts:313   ERR Error: Connection error: Unknown reconnection token (seen before)
    at W (remoteAgentConnection.ts:732:17)
    at remoteAgentConnection.ts:327:17
    at l.fire (event.ts:577:16)
    at u.fire (ipc.net.ts:511:19)
    at r._receiveMessage (ipc.net.ts:873:27)
    at ipc.net.ts:818:73
    at l.fire (event.ts:577:16)
    at d.acceptChunk (ipc.net.ts:284:21)
    at ipc.net.ts:245:51
    at browserSocketFactory.ts:197:39
abstractExtensionService.ts:644 Extension host (Remote) terminated unexpectedly. Code: 0, Signal: null
```

## Steps to Reproduce

1. edit `config.yaml` and add this:
```yaml
bind-addr: 127.0.0.1:8080
auth: password
password: "12345"
cert: true
```
2. run code-server: `code-server`

### Expected

code-server can be accessed via HTTPS and all expected features work.

### Actual

Browser complains about about SSL certificate says "Cannot reconnect"

### Screenshot

<img width="1884" alt="image" src="https://user-images.githubusercontent.com/3806031/153073621-220933a6-f530-449b-a9be-92dcd237a76a.png">

**Comment by dmitriypavlov** [comment]
I have the same situation.
Additionally it seems like some extensions can't load their settings and don't work.

**Comment by tenpaiyomi** [comment]
Receiving the same issue here as well, completely fresh install.  I've noticed a few things, similar to the above, which makes me believe this is the extension host again.

1, the reconnecting loop happens exactly 3 times.
2, Between the 2nd and 3rd reconnect loop, I'm getting the following error message in the console logs

```
The connection to wss://192.168.1.5:8500/?type=ExtensionHost&reconnectionToken=6661fa0b-34b7-457a-8498-104b5f0249be&reconnection=true&skipWebSocketFrames=false was interrupted while the page was loading.
```

3, After the 2nd reconnect, before the 3rd, I get the following errors:

```
Error received from starting extension host (kind: Remote)
The remote extenion host took longer than 60s to send its ready message.
```

**Comment by tenpaiyomi** [comment]
Additionally, reverting to 3.12.0, I do not exhibit the above behavior.

**Comment by aleleba** [comment]
It happens to me too.

**Comment by jsjoeio** [comment]
Can someone please provide reproduction steps? I'm running 4.0.1 on macOS with Brave and do not see this.

**Comment by tenpaiyomi** [comment]
@jsjoeio for me it was just installing the image, starting it up and loading up the UI.  Latest Firefox, Win 10.

**Comment by jsjoeio** [comment]
I'm running from source directly on macOS + Brave and can't reproduce this :( 

![image](https://user-images.githubusercontent.com/3806031/148616568-a02c1b86-78f5-4b07-b809-284e22439034.png)

@code-asher any ideas?

**Comment by onepunchdan** [comment]
For me, this behavior occurs on a fresh install when specifying a cert in config.yaml. Extensions successfully load with `cert: false` and I no longer get the "Cannot reconnect. Please reload the window." popup.

**Comment by JtMotoX** [comment]
@onepunchdan good catch!

I upgraded to 4.0.1 and now none of my extensions loaded and after about 5 seconds I receive the error and same console logs that the OP mentioned.

I commented out my cert configs in my config.yaml and reloaded and now it loads fine with all my extensions and no errors (except for the untrusted connection error).

@jsjoeio maybe this will be enough info for you to replicate the issue?

**Comment by tenpaiyomi** [comment]
Counter point, I have never touched the `config.yml` file when experiencing this issue.  I went and checked mine to be sure and it is, I presume, default:

```
bind-addr: 127.0.0.1:8080
auth: password
password: <redacted>
cert: false
```

**Comment by ochen1** [comment]
> Additionally, reverting to 3.12.0, I do not exhibit the above behavior.

I can confirm, `3.12.0` does not exhibit the same behavior. No errors after downgrading.

**Comment by JtMotoX** [comment]
I was able to downgrade my Ubuntu install which is working fine now.
```bash
> curl -fsSL https://code-server.dev/install.sh | sh -s -- --version 3.12.0
Ubuntu 20.04.3 LTS
Installing v3.12.0 of the amd64 deb package from GitHub.
```

How do I downgrade my macOS install?  Even though I pass the version, it tries to install the latest.
```bash
> curl -fsSL https://code-server.dev/install.sh | sh -s -- --version 3.12.0
macOS v11.6.2
Installing latest from Homebrew.
```

**Comment by vincentchu37** [comment]
Can confirm same behavior using the `codercom/code-server:4.0.1` docker image on docker. `codercom/code-server:3.12.0` works as intended.

```
vincent@3:~/code/.config/code-server$ cat config.yaml 
bind-addr: 127.0.0.1:5443
auth: password
password: redacted
cert: true
proxy-domain: code.quickbrownfoxes.org
```

**Comment by JtMotoX** [comment]
This can be replicated & tested on any system (tested on macOS, Windows, and Linux) with the docker command below.

Log in with **https** on port 8080 with the password "temp" and bypass the untrusted cert warning.  Just sit back and watch the Console logs and after about 2 minutes you will get the connection error.  Even when I pass a valid trusted cert, I still get the reconnection errors.

If you remove the ```--cert``` flag and log in with **http**, I do not get any reconnection errors.

```bash
docker run --rm --name code-server --entrypoint "/usr/bin/entrypoint.sh" -p 0.0.0.0:8080:8080 -e PASSWORD="temp" codercom/code-server:latest --bind-addr 0.0.0.0:8080 --auth "password" --cert
```

**Comment by jsjoeio** [comment]
@code-asher any ideas on this?

**Comment by jsjoeio** [comment]
> How do I downgrade my macOS install? Even though I pass the version, it tries to install the latest.

@JtMotoX Looks like it installed with Homebrew. AFAIK, Homebrew does not keep track of old formula so you can't downgrade using Homebrew. You should be able to `brew remove code-server` and then download a standalone release to downgrade versions. See [these docs](https://coder.com/docs/code-server/latest/install#standalone-releases)

**Comment by code-asher** [comment]
If I recall correctly there were some siginficant removals around code
designed to handle the `cert` case so it is possible this is another
case of code removed that should not have been.

**Comment by danopia** [comment]
So the current status of 4.x is that it doesn't work with existing TLS certificates? Given that numerous features (clipboard, webview, etc) only work when loaded from HTTPS this seems like a pretty important issue..

I had trouble getting Chrome to properly take the self-signed certs so instead, I was able to get my session working again by putting code-server on a different HTTP port and then running a [Caddy](https://caddyserver.com/v2) instance in front:

```caddyfile
$ cat ~/.local/share/code-server/Caddyfile
my-code-server.danopia.net:8080

reverse_proxy localhost:8079
tls cert.pem cert-key.pem
```

This reverse proxy situation seems to work properly without triggering "Cannot reconnect" message

**Comment by JtMotoX** [comment]
> I had trouble getting Chrome to properly take the self-signed certs so instead, I was able to get my session working again by putting code-server on a different HTTP port and then running a [Caddy](https://caddyserver.com/v2) instance in front

I thought about doing this with a docker nginx reverse proxy sitting in front of it but it just seemed easier to rollback to 3.x until this issue gets resolved.

**Comment by Hugovidafe** [comment]
Even with the extensions activated, I try to open the list of accounts and it keeps loading, until several seconds pass and the same error appears. I think the problem is there.

**Comment by JtMotoX** [comment]
Still have the same issue with the newly released v4.0.2.

**Comment by jsjoeio** [comment]
@JtMotoX thank you for confirming! We'll hopefully get to this soon.

**Comment by hecnavsanz** [comment]
Hi, I've been working during months w/ 4.0.1 ('ms-python.python', 'redhat.java' and 'kelvin.vscode-sshfs' extensions) deploying many different environments w/o any issues using "curl -fsSL https://code-server.dev/install.sh | sh" and systemctl and the following "$HOME/.config/code-server/config.yaml" file:

```
bind-addr: <server_ip>:443
auth: none
cert: true
```

 after upgrading to 4.0.2 I'm getting the same error "Cannot reconnect. Please reload the window." in the web browser.

I started manually Code-Server w/ "code-server --verbose" and this is the log output:

```
[13:49:02] Started scanning user extensions
[13:49:02] Scanned user extensions: 0
[2022-01-29T13:49:18.050Z] debug 5 active connections
[2022-01-29T13:49:18.050Z] trace heartbeat
[13:49:19] [192.168.56.1][ae561d21][ExtensionHostConnection] - startParams language: en
[13:49:19] [192.168.56.1][ae561d21][ExtensionHostConnection] - startParams env: {"VSCODE_PROXY_URI":"https://192.168.56.10/proxy/{port}"}
[13:49:19] [192.168.56.1][ae561d21][ExtensionHostConnection] The client has reconnected.
[13:49:40] [192.168.56.1][ae561d21][ExtensionHostConnection] - startParams language: en
[13:49:40] [192.168.56.1][ae561d21][ExtensionHostConnection] - startParams env: {"VSCODE_PROXY_URI":"https://192.168.56.10/proxy/{port}"}
[13:49:40] [192.168.56.1][ae561d21][ExtensionHostConnection] The client has reconnected.
[13:50:00] [192.168.56.1][ae561d21][ExtensionHostConnection] - startParams language: en
[13:50:00] [192.168.56.1][ae561d21][ExtensionHostConnection] - startParams env: {"VSCODE_PROXY_URI":"https://192.168.56.10/proxy/{port}"}
[13:50:00] [192.168.56.1][ae561d21][ExtensionHostConnection] The client has reconnected.
[13:50:00] [192.168.56.1][ae561d21][ExtensionHostConnection] <10989> Extension Host Process exited with code: 0, signal: null.
[2022-01-29T13:50:18.051Z] debug 8 active connections
[2022-01-29T13:50:18.051Z] trace heartbeat
[13:50:20] [192.168.56.1][ae561d21][ExtensionHostConnection] - startParams language: en
[13:50:20] [192.168.56.1][ae561d21][ExtensionHostConnection] - startParams env: {"VSCODE_PROXY_URI":"https://192.168.56.10/proxy/{port}"}
[13:50:20] [192.168.56.1][ae561d21][ExtensionHostConnection] Unknown reconnection token (seen before).
[13:50:20] [192.168.56.1][165be397][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[2022-01-29T13:51:18.052Z] debug 7 active connections
[2022-01-29T13:51:18.053Z] trace heartbeat
```

and even I'm trying to rollback now to install Code-Server w/ the old version 4.0.1 in a totally new env and I don't know why now I'm having the same problem too as of 4.0.2 when it wasn't in the past ... it's supposed that the 4.0.1 code has not been modified, isn't it?

Thanx again.

**Comment by jsjoeio** [comment]
@kexirong thanks for the notes! I'm not 100% what the issue is. We'll need to take a closer look.

**Comment by tomsherrod** [comment]
code-server: v4.0.2
 VS Code: v1.63.0
Commit: 5cdfe74686aa73e023f8354a9a6014eb30caa7dd
Date: 2022-01-27T22:22:39Z
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36 Edg/96.0.1054.43

Upgraded from 3.11 and now getting the "Cannot reconnect. Please reload window." so often, it's unusable.
Going to try a downgrade.

**Comment by invictus2010** [comment]
Just to clarify...this is making code-server unusable for everyone right?

Is there a certain browser it does work with? I work off of my macOS Chrome and my iPad (Safari) and getting this issue in both places.

**Comment by vincentchu37** [comment]
> Just to clarify...this is making code-server unusable for everyone right?
> 
> Is there a certain browser it does work with? I work off of my macOS Chrome and my iPad (Safari) and getting this issue in both places.

Stick with 3.12.0 until they release 4.0.3 where a patch for this issue is slated

**Comment by hecnavsanz** [comment]
> Just to clarify...this is making code-server unusable for everyone right?
> 
> Is there a certain browser it does work with? I work off of my macOS Chrome and my iPad (Safari) and getting this issue in both places.

for me a fresh 4.0.2 (SSL) installation is not working with "$HOME/.config/code-server/config.yaml" file:

```
bind-addr: <server_ip>:443
auth: none
cert: true
```

in any browser in Windows and MacOS.
But more strange is that a fresh installation of 4.0.1 "curl -fsSL https://code-server.dev/install.sh | sh -s -- --version=4.0.1" also is not working now too when it was before 4.0.2 was released.

As a workaround, I disabled SSL in 4.0.2 to use nginx as front-end with "$HOME/.config/code-server/config.yaml" file:

bind-addr: 127.0.0.1:8080
auth: password
password: <my_password>
cert: false
 
and it's working.

**Comment by jsjoeio** [comment]
I'm looking into this now. I was able to reproduce locally and updated the original issue with steps and a screenshot.

I need to continue investigating. I'll update this comment with my notes.

Things to look into:
- Where does the cert logic happen and is it working as expected? If not, add tests.
- Where is the error? Is it an invalid certificate, something with our routing or something else?
