### ISSUE TITLE
Changing the keyboard layout doesn't stick

### ISSUE THREAD

**Issue by drmrbrewer** [coder/code-server#4694]
Am using latest code-server v4.0.1, but this also happened in v3.12.0.

I am referring to changing the keyboard layout via the button in the bottom-right of the editor:

![image](https://user-images.githubusercontent.com/9009792/148364717-0f0b6ab1-3a27-4d51-8c8f-8d30679e8d37.png)

Changing it from `Layout: US` to something else doesn't seem to have any effect... it remains as `Layout: US` and does so even after re-loading the window.  Well, it's inconsistent because I managed to change it to Hungarian (but then it didn't change to anything else)... but even after changing to Hungarian, when the window was reloaded it was back to US.

**Comment by jsjoeio** [comment]
@drmrbrewer thanks for the report! I'm guessing this is easy to reproduce then (just changing there?).

Are there any server or browser logs?

**Comment by drmrbrewer** [comment]
@jsjoeio well it's easy for me to reproduce :)  I see nothing at all in either the server (docker) logs or the browser logs when I change the layout setting... not even when it does actually seem to change in the button itself (e.g. to French).  But when I close/open the browser again, it's back to US.

**Comment by jsjoeio** [comment]
Haha thanks for checking! Let me test now.

Hmm...you're right. Nothing. I wonder why that could be 🤔 I wonder if it's related to the logic we added to change the display language? Eh probably unrelated.

Any ideas @code-asher?

## Video

https://user-images.githubusercontent.com/3806031/148606851-7259aa8f-b8d0-470a-b262-c7286533b58e.mov

**Comment by drmrbrewer** [comment]
Note that, in your video clip, the layout stated at the bottom right (where you click) does change to "Spanish" when you first change it from "US", even if it doesn't seem to have any effect, but doesn't change when you then change it to "Russian" (it stays reading "Spanish").  So it seems to be broken on a couple of levels... (a) the indication doesn't (always) change; and (b) it doesn't seem to have any effect regardless of what the indication says.

**Comment by fritterhoff** [comment]
> (b) it doesn't seem to have any effect regardless of what the indication says.

I also recognized that and well, I don't have any problem with that as long it uses the default system layout (everything else would prop. confuse)

**Comment by jsjoeio** [comment]
> (a) the indication doesn't (always) change; and (b) it doesn't seem to have any effect regardless of what the indication says.

I didn't even notice - excellent observation!

**Comment by code-asher** [comment]
From what I can remember I think this has never worked although I
remember seeing some changes in VS Code to support it so maybe it is
something wrong on our end.

**Comment by Write** [comment]
Do you guys have any working workaround this ?

**Comment by jsjoeio** [comment]
Unfortunately, I don't :(

**Comment by Dids** [comment]
It's been a few months, but I'm assuming there hasn't been any progress with this?

**Comment by fritterhoff** [comment]
I still assume this only an optical bug? I'm unsure what affect an other language selection should cause ... 🤔

**Comment by Write** [comment]
Well, unfortunately not just visual bug? I have to refresh multiple time to get the correct language from within my settings.. Le 14 juil. 2022 à 11:34, Florian Ritterhoff - notifications(a)github.com ***@***.***> a écrit :﻿
I still assume this only an optical bug? I'm unsure what affect an other language selection should cause ... 🤔

**Comment by fritterhoff** [comment]
But what's the effect after changing the indicator? Does your real keyboard layout change? So if I press a y the y appears regardless of the configured layout.

**Comment by Write** [comment]
Yes, after the indicator is changed my keyboard is finally in AZERTY and my keyboard shortcuts working correctly.
Otherwise when it stay EN / US the keyboard is in QWERTY and all keyboard shortcuts are affected too.

**Comment by code-asher** [comment]
I tried this out on Codespaces and had similar problems so it 
appears to be an issue upstream.

What I observed:

- Switching layout worked (visual indicator updated and keyboard 
  shortcuts worked)
- Refreshing switched me back to the default US layout
- Switching layout stopped working (visual indicator does not 
  update and keyboard shortcuts use the wrong keys)
- If I delete `keyboard.layout` from my settings then switch the 
  layout it works again (until the next refresh).

https://github.com/microsoft/vscode/issues/135960

One workaround is to set `Keyboard: Dispatch` to `keycode` instead 
of using layouts.

**Comment by jsjoeio** [comment]
Since this is upstream, we'll close this and suggest you subscribe there.

**Comment by alka79** [comment]
Hello. 
The above link point to oping an issue, and  search brings back to this thread.
I still face exactly that same issue in Home Assistant Code Server add-on. Current version is 5.15 
Was this ever fixed ? 
Is there a workaround ?
Thank you

**Comment by code-asher** [comment]
@alka79 Does it work as expected for you in Codespaces?  If not I recommend following the link and opening an issue in the upstream VS Code repository, since the bug is probably there and not here.

**Comment by code-asher** [comment]
Codespaces can be accessed here: https://github.com/codespaces

I believe it is available for anyone with a GitHub account.  It is helpful to try reproducing there so we can see if the issue is native to VS Code or if it is a problem with code-server.  code-server just wraps VS Code web (which is what Codespaces is), so often the problems are actually upstream.

**Comment by alka79** [comment]
Thanks for the link. I struggled in codespaces and found something.
Add a setting.json file with the follwing :

`
{
  "keyboard.layout": "0000040C"
}
`

That makes it for french keybd layout.
set to `autodetect` constantly brings back to US layout. 
I found the above code by try and guess. Code for US keybd would be "00000409"

Now I'll try to do the same in HomeAssistant add on.

**Comment by KaKi87** [comment]
Hi,

I'm experiencing the same issue.

What to do ?

> Add a setting.json file with the follwing : `{ "keyboard.layout": "0000040C" }`

Where do I have to add that file ?

Thanks

**Comment by alka79** [comment]
> Where do I have to add that file ?
open the Studio COde Server integration in HA, click on explorer and you should see the HA folders under CONFIG.
The file settings.json should be added in the .vscode folder


![Image 107](https://github.com/coder/code-server/assets/66568594/b11eccb9-23a1-48e6-bcc5-0a4ca1152215)

If the folder .vscode is not visible it may be that it is part of the excluded files/folders. To check that, go to VSCode Settings and search "Files: Exclude" in both "User Settings" and "Workspace Settings". Delete the files/folders needed to appear.

**Comment by KaKi87** [comment]
No, I'm experiencing this issue on Chromium-based browsers.

**Comment by agarcia-ruiz** [comment]
I've been experiencing a mix of issues with code-server in LibreWolf and tried different browsers, this is what I found:

- With Firefox 137.0, the layout label on the lower right corner always resets to US after reloading, and it also reads US when you choose "Auto Detect", even if the actual layout used or detected is not US, but the correct one. The manually set layout can be checked in settings.json ("keyboard.layout"), but the label on the lower right corner may get it wrong.
- With LibreWolf 138.0.4-1, same problems as with Firefox, plus some keys were not identified/detected as unknown, this I've found is because of LibreWolf "ResistFingerprinting", so in a safe profile for coding you can disable that and then it behaves as in Firefox.
- With ungoogled-chromium 135.0.7049.84 the correct layout is detected and correct label is displayed. Haven't tried other chromium browsers though.

So it might be down to privacy-related settings of each browser to prevent fingerprinting based on the keyboard layout? Anyway, hope this info is useful.

**Comment by KaKi87** [comment]
Please someone look into this and fix the US defaultism :sob:

**Comment by wischi-chr** [comment]
For anyone ending up here because of a google search. If you don't need to switch between layouts you can "pin" it with the following workaround: [[Gist] Pin keyboard layout for code-server/vscode](https://gist.github.com/wischi-chr/dc76a8990033ee2c28c9905bd988b7a7)

**Comment by KaKi87** [comment]
Thank you !

**Comment by mike-lischke** [comment]
In addition to the steps provided by @wischi-chr, I also had to change the first object like so:

```
	"layout": {
		"id": "com.apple.keylayout.US",
		"lang": "de",
		"localizedName": "Deutsch",
		"isUSStandard": false,
		"isUserKeyboardLayout": true
	},
```

to make it work. Reloading the browser page is enough. No need to restart HA.
