### ISSUE TITLE
package.json request 404

### ISSUE THREAD

**Issue by OliverwengFiltered** [coder/code-server#4698]
after upgrading to version 4.0.1, I started seeing this 404 error.

does anyone know anything about the new package.json request, which throws 404 ?

it seems it's being called from app/ui.js

![Screen Shot 2022-01-06 at 6 20 59 PM](https://user-images.githubusercontent.com/28814939/148466168-cb07932c-b5b7-4661-9334-70efa46a26bd.png)
![Screen Shot 2022-01-06 at 6 20 51 PM](https://user-images.githubusercontent.com/28814939/148466171-9fceec6d-f57b-408e-a2cf-fd62a35a2df4.png)

**Comment by jsjoeio** [comment]
Is that from an extension you have install by chance? We're not using LogRocket so I don't think that's coming from code-server. Can you look at the request route in the Network tab and share that?

**Comment by OliverwengFiltered** [comment]
this is not from logrocket file, it's from app/ui.js file.

but seems only reproducible when you first time open a new vm which has the code server just installed.

**Comment by jsjoeio** [comment]
Are you using any browser extensions?

>  Can you look at the request route in the Network tab and share that?

Can you try this?

**Comment by OliverwengFiltered** [comment]
Hi @jsjoeio 
I can't seem to reproduce, I'm closing this one now, thanks
