### ISSUE TITLE
Saving a file takes 3-4 seconds and while saving the file gets broken

### ISSUE THREAD

**Issue by progettoautomazione** [coder/code-server#4701]
I have noticed a very annoying thing, not sure if you experience the same/you have a fix for this: whenever I save a file, if the file is like 3000-5000 rows it takes 3-4 seconds to save. Not big deal, I can wait. The big deal is that I noticed that in this timeframe, the file is corrupted. This means that if I use my application, while the saving is in progress, the application is broken. Example of the error I see in my app when I refresh the page while the file is saving: https://nimb.ws/TBlZIc
I used to adopt AWS Cloud9 as web-based IDE editor and this was not happening. I would say its kind of a big deal, so maybe there is an easy fix that I am not seeing. Any advice?
Thanks

**Comment by jsjoeio** [comment]
@progettoautomazione can you please open a bug report issue and add repro steps? Then we'll be able to look into this and help you. Thanks! I'll close this and we can track in the new bug report.
