### ISSUE TITLE
While saving a file, the file itself gets broken

### ISSUE THREAD

**Issue by progettoautomazione** [coder/code-server#4706]
Whenever I save a file, if the file is like 3000-5000 rows it takes 3-4 seconds to save. Not big deal, I can wait. The big deal is that I noticed that in this timeframe, the file is corrupted. This means that if I use my application, while the saving is in progress, the application is broken. Example of the error I see in my app when I refresh the page while the file is saving: https://nimb.ws/TBlZIc

## OS/Web Information

- Web Browser: any
- Local OS: any
- Remote OS: Ubuntu 18
- Remote Architecture: AWS EC2 Instance
- `code-server --version`: 3.11

## Steps to Reproduce

1. I recorded a loom: https://www.loom.com/share/f1680518bb0c44318e2673579e61ff8a
2. Basically as you can see, while the file is getting saved, the webapp breaks, because the file gets corrupted. When the saving is completed, of course the file is no longer broken and so the app is back live

## Expected

While saving, I expect the file not to get broken, otherwise the webapp will be broken wile saving, and that might represent a problem

## Actual

While saving the file, the file itself gets broken, breaking the application.

This issue can be reproduced in VS Code: Yes

**Comment by jsjoeio** [comment]
Thank you for the Loom! I'm a bit confused though. This seems to be an issue with the progestnow web app, not code-server?

**Comment by progettoautomazione** [comment]
> Thank you for the Loom! I'm a bit confused though. This seems to be an issue with the progestnow web app, not code-server?

Hi @jsjoeio hemmm no, as you can see, the error is there onli WHILE VSCode is saving the change. When the saving is finished, I refresh again the page, and it works fine again.

**Comment by jsjoeio** [comment]
I guess I'm confused on what this progestnow page is. It's your app your building or something?

Can you provide a repo or something to reproduce this? Can you also provide browser/server logs?

**Comment by jsjoeio** [comment]
And can you check if this happens with 4.0.1?
