### ISSUE TITLE
No green play button beside a Go test

### ISSUE THREAD

**Issue by soulmachine** [coder/code-server#4709]
## OS/Web Information

- Web Browser: Chrome
- Local OS: macOS
- Remote OS: Ubuntu
- Remote Architecture: x86-64
- `code-server --version`: 4.0.1 735c6da829535969ff7193c79379299e4a1cb9bc

## Steps to Reproduce

1. Install the [golang.Go](https://marketplace.visualstudio.com/items?itemName=golang.Go) extension
2. Open a go project
3. Open a `*_test.go` file containing some tests

## Expected

The should be a green play button beside the test, and users can run this specific test by just clicking it.

## Actual

The is no green play button

## Screenshot

![WechatIMG469](https://user-images.githubusercontent.com/620768/148674805-2ac1c925-fa5f-4463-be1c-dccd46fbfbde.jpg)

## Notes

This issue can be reproduced in VS Code: Yes

**Comment by jsjoeio** [comment]
Can you share your VS Code `settings.json`? I wonder if you have the column hidden (I do in mine).

> This issue can be reproduced in VS Code: Yes

If this can be reproduced in VS Code, can you please file a bug upstream?

**Comment by soulmachine** [comment]
I'm using this docker image https://github.com/soulmachine/docker-images/tree/master/code-server-go

Here is the `settings.json` https://github.com/soulmachine/docker-images/blob/master/code-server-go/settings.json

**Comment by jsjoeio** [comment]
Does this issue happen in VS Code or Codespaces?

**Comment by soulmachine** [comment]
The green button is normal in vscode of my macbook

**Comment by jsjoeio** [comment]
Hmm...okay we'll have to investigate then.

**Comment by tusharranjan719** [comment]
Same problem.. any updates?

**Comment by jsjoeio** [comment]
Nothing so far, but we welcome any help!

**Comment by code-asher** [comment]
I tested the latest version and see the play button.  Closing for now but let me know if this is still a problem.
