### ISSUE TITLE
login and logout can't redirect to subpath behind reverse proxy

### ISSUE THREAD

**Issue by curiosity2** [coder/code-server#4712]
## OS/Web Information

- Web Browser: Chrome
- Local OS: Win10
- Remote OS: Ubuntu 18
- Remote Architecture: x64
- `code-server --version`: 4.0.1

## Steps to Reproduce

1. config Nginx 
2. proxy xxx.com/vscode to 127.0.0.1:5002
3. start code-server on port 5002

## Expected

login: xxx.com/vscode -> xxx.com/vscode/login -> xxx.com/vscode
logout: xxx.com/vscode/logout -> xxx.com/vscode -> xxx.com/vscode/login

## Actual

login: xxx.com/vscode -> xxx.com/login -> xxx.com/vscode
logout: xxx.com/logout -> xxx.com -> xxx.com/login

## Logs

login:
![inlog](https://user-images.githubusercontent.com/11660784/148728782-4241a9ea-e031-4b15-b6a4-acc70fe2cb21.JPG)
logout:
![outlog](https://user-images.githubusercontent.com/11660784/148728249-7b3c96e3-a01f-465a-bf65-8ad938f3d77e.JPG)

## Screenshot

login:
![in1](https://user-images.githubusercontent.com/11660784/148728303-fa78c972-b330-46fa-9500-bb9329bfcf9d.JPG)
![in2](https://user-images.githubusercontent.com/11660784/148728291-3c50d9ba-a47a-428b-b8fb-e82b99319dae.JPG)
![incss1](https://user-images.githubusercontent.com/11660784/148728297-590f0dc0-54fc-46f6-8ba7-081493106183.JPG)
![incss2](https://user-images.githubusercontent.com/11660784/148728301-0fc135d4-57ee-4660-8ec0-5500a88c94e0.JPG)

logout:
![out1](https://user-images.githubusercontent.com/11660784/148734074-cf1b9869-ecfc-4c0d-a216-4e2016c398c0.JPG)
![out2](https://user-images.githubusercontent.com/11660784/148734069-c247e6bb-3636-4f63-8615-08b84dc12d35.JPG)
![out3](https://user-images.githubusercontent.com/11660784/148734073-db27434b-421d-4e86-93d6-8c9946e06778.JPG)

## Notes

This issue can be reproduced in VS Code: No

**Comment by jsjoeio** [comment]
@code-asher I could have sworn we tested this with Caddy and it worked fine 🤔

Here's the Caddy file I tested with:
```Caddy
http://localhost:8082/vscode/* {
  uri strip_prefix /vscode
  reverse_proxy 127.0.0.1:8080
}
```

**Comment by code-asher** [comment]
What does the NGINX config look like?

**Comment by curiosity2** [comment]
> @code-asher I could have sworn we tested this with Caddy and it worked fine 🤔
> 
> Here's the Caddy file I tested with:
> 
> ```
> http://localhost:8082/vscode/* {
>   uri strip_prefix /vscode
>   reverse_proxy 127.0.0.1:8080
> }
> ```

I haven't used Caddy, I'll try.

**Comment by curiosity2** [comment]
> What does the NGINX config look like?

Hi, Here is my config
```
server {
        listen       443 ssl;
        server_name  apps.***.ml;
        ssl_certificate     /etc/nginx/ssl/apps.***.ml/apps.***.ml.cer;
        ssl_certificate_key  /etc/nginx/ssl/apps.***.ml/apps.***.ml.key;

        location /vscode/ {
            proxy_pass          http://127.0.0.1:5002;

            proxy_set_header    Host            $host;
            proxy_set_header    X-Real-IP       $remote_addr;
            proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_hide_header   X-Powered-By;

            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }
```

**Comment by code-asher** [comment]
I think `proxy_pass http://127.0.0.1:5002/;` should do it (notice the trailing slash).

code-server expects the reverse proxy to rewrite the path and the way you do that in NGINX is by appending a trailing slash to the proxy pass value.
