### ISSUE TITLE
without-browser-env-var variable is not sent to vscode server

### ISSUE THREAD

**Issue by migolo** [coder/code-server#4721]
without-browser-env-var is not specified, so tools like create-react-app attempts to start a browser at the vscode defined path and crashes

Sorry for the incomplete data, I will try to edit the issue with the logs and paths appended later

## OS/Web Information

- Web Browser: Any (Chrome)
- Local OS: Mac OSX
- Remote OS: Ubuntu
- Remote Architecture: amd64
- `code-server --version`: 4.0.1

## Steps to Reproduce

1. Run npm start on integrated terminal for code-server 
2. Crashes immediately trying to look at browser.sh from vscode
3.

## Expected

npm start should start, not crash.

## Actual

Crashes 

## Notes
This is the line that gets appended to the browser env so react crashes (as there should not be a browser env file) https://github.com/microsoft/vscode/blob/6249dab4fe849d0ad11500fabd28ddc204ef12da/src/vs/server/extensionHostConnection.ts#L60

code-server version 3.12.0 doesn't crash

This issue can be reproduced in VS Code: No

**Comment by migolo** [comment]
You can see me reproducing the issue, 
https://user-images.githubusercontent.com/207846/149213757-43c72cc6-976b-4557-9c35-0354c2f033c3.mov

`Starting the development server...

node:events:368
      throw er; // Unhandled 'error' event
      ^

Error: spawn /usr/lib/code-server/vendor/modules/code-oss-dev/bin/helpers/browser.sh ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
    at onErrorNT (node:internal/child_process:477:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (node:internal/child_process:288:12)
    at onErrorNT (node:internal/child_process:477:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn /usr/lib/code-server/vendor/modules/code-oss-dev/bin/helpers/browser.sh',
  path: '/usr/lib/code-server/vendor/modules/code-oss-dev/bin/helpers/browser.sh',
  spawnargs: [ 'http://localhost:3000/app' ]
}`

**Comment by jsjoeio** [comment]
Thanks for the video! It looks like you're using custom environment variables when running your React app. What does `.env.development` have in it?

![image](https://user-images.githubusercontent.com/3806031/149215047-5f9ed145-f8e0-415c-be21-f146e029867f.png)

What happens if you add `BROWSER=false` that `.env` file?

**Comment by migolo** [comment]
Adding the `BROWSER=false` to the env variable works!

**Comment by migolo** [comment]
So, yeah for the moment I can use that as a workaround, but, probably would be helpful to know why the $BROWSER env is populated?
```
$ echo $BROWSER
/usr/lib/code-server/vendor/modules/code-oss-dev/bin/helpers/browser.sh
```

**Comment by jsjoeio** [comment]
Weird that I don't see that...but this is locally on my macOS where code-server is installed with Homebrew.

![image](https://user-images.githubusercontent.com/3806031/149373329-09f9f5b8-b358-48d7-982a-6ddefe43350d.png)

@code-asher any ideas?

**Comment by migolo** [comment]
Oh! It's not on the usual terminal, is inside the vscode terminal, if I ssh into the remote host `$BROWSER` env is not set

**Comment by jsjoeio** [comment]
@code-asher do you have any thoughts on this?

**Comment by code-asher** [comment]
I think it is supposed to open in your current browser via the VS Code
API (if you look at browser.sh it is calling the VS Code CLI).

We must not be including the browser.sh script as part of our bundle
(see the ENOENT) so adding it should sort the issue.

**Comment by migolo** [comment]
Is there a way to add in the configuration the ability to send `without-browser-env-var` flag so $BROWSER flag is not set?

**Comment by code-asher** [comment]
We could add that flag although maybe we should implement
https://github.com/coder/code-server/issues/1528 which will allow
passing any VS Code flag.
