### ISSUE TITLE
Web socket fails to connect through Apache

### ISSUE THREAD

**Issue by lplassman** [coder/code-server#4723]
## OS/Web Information

- Web Browser: Chrome
- Local OS: MacOS 12.2
- Remote OS: Ubuntu 20.04 LTS
- Remote Architecture: amd64
- `code-server --version`: 4.0.1

## Logs

code-server --log debug
[2022-01-11T03:38:43.612Z] info  code-server 4.0.1 735c6da829535969ff7193c79379299e4a1cb9bc
[2022-01-11T03:38:43.613Z] info  Using user-data-dir ~/.local/share/code-server
[2022-01-11T03:38:43.628Z] info  Using config file ~/.config/code-server/config.yaml
[2022-01-11T03:38:43.628Z] info  HTTP server listening on http://0.0.0.0:8080/ 
[2022-01-11T03:38:43.628Z] info    - Authentication is enabled
[2022-01-11T03:38:43.628Z] info      - Using password from ~/.config/code-server/config.yaml
[2022-01-11T03:38:43.628Z] info    - Not serving HTTPS 
[22:38:51] Extension host agent started.
[22:38:51] [Theme Service] Scanning for theme extension...
[22:38:51] [Theme Service] theme-abyss
[22:38:51] [Theme Service] theme-defaults
[22:38:51] [Theme Service] theme-kimbie-dark
[22:38:51] [Theme Service] theme-monokai
[22:38:51] [Theme Service] theme-monokai-dimmed
[22:38:51] [Theme Service] theme-quietlight
[22:38:51] [Theme Service] theme-red
[22:38:51] [Theme Service] theme-solarized-dark
[22:38:51] [Theme Service] theme-solarized-light
[22:38:51] [Theme Service] theme-tomorrow-night-blue
[22:38:51] [Theme Service] Attempting to find user's active theme: Default Dark+
[2022-01-11T03:38:54.949Z] debug got latest version {"latest":"4.0.1"}
[2022-01-11T03:38:54.949Z] debug comparing versions {"current":"4.0.1","latest":"4.0.1"}
[2022-01-11T03:39:51.007Z] debug 0 active connections

## Screenshot
![139257954-98741db0-07d2-47f0-a529-fbe57cdd1188](https://user-images.githubusercontent.com/40614799/148878463-b1c84c04-35c4-4990-bfb2-ebd1a013aee0.png)
<img width="1440" alt="Screen Shot 2022-01-10 at 10 47 35 PM" src="https://user-images.githubusercontent.com/40614799/148878490-56346c97-dad7-443e-8093-1d982656e8c8.png">
<img width="1440" alt="Screen Shot 2022-01-10 at 10 48 36 PM" src="https://user-images.githubusercontent.com/40614799/148878499-1ccb6079-82a5-4a03-876b-9ebbb18a7867.png">

## Notes
I currently only experience this error on code-server 4.0.1. code-server 3.12.0 works without issue. 
I am currently using apache2 with a reverse proxy. The current config for the apache2 virtual host is below:

<Location "/">
    ProxyPass http://127.0.0.1:8080/
    ProxyPassReverse http://127.0.0.1:8080/
    ProxyPassReverse /
    RewriteEngine on
    RewriteCond %{HTTP:Upgrade} websocket [NC]
    RewriteCond %{HTTP:Connection} upgrade [NC]
    RewriteRule ^/?(.*) "ws://127.0.0.1:8080/" [P,L]
</Location>

I also made sure all the websockets modules are loaded in apache2 and working without problems. No errors occur on the Apache web server. Any suggestions on how to get this working with Apache2?

This issue can be reproduced in VS Code: No

**Comment by JimmyNi** [comment]
Same issue here. Using apache2 with reverse proxy. Only occur with 4.0.1, code-server 3.12.0 works fine for me.

**Comment by jsjoeio** [comment]
@code-asher any ideas?

**Comment by code-asher** [comment]
If the exact same config works with 3.12 that does seem like it could be
an issue with 4.0 but I have no idea how; so far all the 1006 errors I
have seen have been caused by misconfiguration.

I am not very familiar with Apache but maybe this comment has a clue:

https://github.com/coder/code-server/discussions/2104#discussioncomment-360665

**Comment by wilcdr** [comment]
I have a similar issue with 4.0.1.  I'm using code-server with the docker image packaged by the linuxserver.io folks (https://github.com/linuxserver/docker-code-server), but I'm using it without any proxy in front.  So it's just straight listening with code-server.  It used to work fine before going to 4.0.  Below is the log in dev-tools together with the expanded callstack.

![image](https://user-images.githubusercontent.com/32535288/149439623-f3026d81-2065-4d73-b9f6-04372c7db62c.png)
![image](https://user-images.githubusercontent.com/32535288/149439661-bdde9e0d-3a36-4304-83c6-34449a43d432.png)
![image](https://user-images.githubusercontent.com/32535288/149439690-4627eeb9-2c7a-4f7d-bdf7-fbfa23d343b3.png)
![image](https://user-images.githubusercontent.com/32535288/149439724-b7e0984d-3095-42b0-8f95-b52f39660e5b.png)

In my case, everything will work fine until about 60 secs later when the above error disconnects me and it will give me a "Cannot reconnect.  Please reload the window" popup.

Any idea?  I can open up a separate PR if we don't think it's related.

Thanks!

**Comment by konni** [comment]
Same issue here using apache2 with reverse proxy

**Comment by jamieshaw** [comment]
Ditto.

3.12.0 works fine.  4.0.1 returns 1006.
apache2 reverse proxy.

**Comment by dmitriypavlov** [comment]
Same issue.

**Comment by gmiscione** [comment]
Same issue, 3.12.0 works fine and 4.0.1 fails with this error. I'm using apache2 as a reverse proxy.

**Comment by code-asher** [comment]
Sounds like we need to spin up Apache and try to reproduce.

**Comment by dokastho** [comment]
I found a fix on nginx #4763 not sure if there’s an Apache analog for those settings

**Comment by siklosi** [comment]
I'm guessing that line from release log "**Web socket compression** has been made the default (when supported). This means
the --enable flag will no longer take permessage-deflate as an option" is causing problem. I tried finding analog to "proxy_set_header Accept-Encoding gzip" nginx but I have not yet figured way to make it work.

**Comment by KaKi87** [comment]
> not sure if there’s an Apache analog for those settings

Me neither.

> the `--enable` flag will no longer take `permessage-deflate`

I cannot find any documentation on said flag, how does it work ?
Would there be a `--disable` flag too, which would allow apache users to upgrade to 4.x ?

**Comment by code-asher** [comment]
There is no way to disable compression support.  It is only used if the
browser tells the server that it supports compression.

I am not sure issues with compression could cause a 1006 but you could
could try stripping `permessage-deflate` from the
`Sec-WebSocket-Extensions` header to see if that does anything (this
header is how the browser informs the server it supports compression)

**Comment by code-asher** [comment]
Confirming I was able to reproduce:

```
$ sudo apt install apache2
$ sudo a2enmod rewrite proxy proxy_http proxy_wstunnel
$ sudo vim /etc/apache2/sites-available/000-default.conf # See below
$ sudo apache2
$ code-server --version
4.0.1 735c6da829535969ff7193c79379299e4a1cb9bc
$ code-server --port 8080
```

```
<VirtualHost *:80>
  ProxyPass / http://localhost:8080/
  RewriteEngine on
  RewriteCond %{HTTP:Upgrade} websocket [NC]
  RewriteCond %{HTTP:Connection} upgrade [NC]
  RewriteRule ^/?(.*) "ws://localhost:8080/$1" [P,L]
</VirtualHost>
```

1. Open `localhost` in browser
2. Get 1006 errors

Then to confirm it is a 4.0.1 issue I killed code-server with `C-c` and installed 3.12.0 with yarn:

```
$ yarn global add code-server@3.12.0
$ ~/.yarn/bin/code-server --version # .yarn/bin is not in my path
3.12.0 4cd55f94c0a72f05c18cea070e10b969996614d2
$ ~/.yarn/bin/code-server --port 8080
```

1. Open `localhost` in browser
2. Everything works

**Comment by spenceradolph** [comment]
I'm also seeing this bug, with NGINX (using nginx proxy manager). I'm currently trying to fix with https://github.com/coder/code-server/issues/4763 but I'm not having any luck.

**Comment by KaKi87** [comment]
So, will there be a way to disable compression ?

**Comment by spenceradolph** [comment]
Update! The problem was resolved when I tried it from an outside network. So it may have something to do with local routing / proxying differences. Unsure if this is directly related, but my websocket 1006 has been resolved. If I'm local and want to test through the domain I have it on, I'll have to figure out something else.

Websocket 1006 error occurred under these conditions.

- [nginxproxymanager](https://nginxproxymanager.com/) to code-server (all in docker-compose) for my subdomain.
- also exposed code-server to local machine
- localhost:8080 to code-server works perfectly
- code.mydomain.com gives 1006 error (tried from same host)
- code.mydomain.com works perfectly (tried from host outside network)

**Comment by KaKi87** [comment]
I'm hosting `code-server` in a dedicated server so I'm definitely in a different network.

**Comment by jsjoeio** [comment]
Thanks for the comments all! We've recognized this is affecting a lot of people. Instead of commenting, please give the initial issue description a "thumbs-up". Thanks!

**Comment by predkambrij** [comment]
FYI: I also see some content security policy complaints in console log. There are also some 1006 errors, that are resolved in newer versions https://github.com/microsoft/vscode-remote-release/issues/6031
Although code server works without apache reverse proxy (http, not https), that's not really clever to run though the internet :)

**Comment by khanakia** [comment]
I am having the same issue with `code-server 4.2.0` and `Server version: Apache/2.4.18 (Ubuntu)`

**Comment by piit79** [comment]
Yes, same here. Was hoping 4.2.0 would fix the issue but alas.

Is there no workaround at all? My Code Server in Home Assistant has been unusable for many weeks now :(

**Comment by SCratORS** [comment]
> Is there no workaround at all?
Use http://*youre_local_ip_server*:8123/
When used from a local network address - Code Server is work.

**Comment by KaKi87** [comment]
Well, since this issue is Apache-specific, not using Apache "workarounds" the issue, but that's not a really usable answer.

**Comment by jamieshaw** [comment]
> Well, since this issue is Apache-specific, not using Apache obviously "works around" the issue, but that's not a really usable answer.

Especially as most, if not all, are using Apache as a reverse proxy. Assuming this is configured, like myself, for remote access jumping through a single web host externally…

😅

**Comment by krazos** [comment]
This was the push I needed to migrate my reverse proxy server from Apache to NGINX, which had been on my long term to do list for years. 

I set up NGINX Proxy Manager via Docker Compose, and recreating my proxy hosts was much less painful than I had feared. NGINX reverse proxy works flawlessly with my code server instance (4.X), which is installed as a Home Assistant add-on. 

Of course this won't be an option for everyone, but if migrating is feasible for you, I would recommend looking into it.

**Comment by KaKi87** [comment]
I have 35 enabled apache configurations and am not going to migrate to nginx for this.

However, I am stuck to version 3.x until this bug is solved.

**Comment by leuit** [comment]
For those affected, what version of Apache are you running?

I was able to resolve the issue by updating apache2 to `Apache/2.4.53` — however, I believe any version `>= Apache/2.4.47` *may* work. 

I was experiencing websocket 1006 errors on `Apache/2.4.41`

Apache's mod_proxy_wstunnel documentation mention this:

> Since httpd 2.4.47, [mod_proxy_http](https://httpd.apache.org/docs/2.4/mod/mod_proxy_http.html) can handle WebSocket upgrading and tunneling in accordance to RFC 7230, this directive controls whether [mod_proxy_wstunnel](https://httpd.apache.org/docs/2.4/mod/mod_proxy_wstunnel.html) should hand over to [mod_proxy_http](https://httpd.apache.org/docs/2.4/mod/mod_proxy_http.html) to this, which is the case by default.
> 
> Setting to Off lets [mod_proxy_wstunnel](https://httpd.apache.org/docs/2.4/mod/mod_proxy_wstunnel.html) handle WebSocket requests as in httpd 2.4.46 and earlier.

The grammar is a bit off, but I just assumed Apache was handling the websocket proxy incorrectly and I updated apache.

Hope this helps!

**Comment by gmiscione** [comment]
Thanks @leuit, upgrading to Apache/2.4.53 solved the issue

**Comment by lplassman** [comment]
Closing this since the issue seems fixed

**Comment by SCratORS** [comment]
@leuit  Thanks!

**Comment by KaKi87** [comment]
I am running Debian (10), not Ubuntu.

**Comment by leuit** [comment]
@KaKi87
> I am running Debian (10), not Ubuntu.

Try using this to add the repository:
`curl -sSL https://packages.sury.org/apache2/README.txt | sudo bash -x`

Then proceed with upgrading apache2.

Disclaimer: I'm not familiar with Debian. I'm suggesting this based on this [guide](https://www.linuxcapable.com/how-to-install-or-upgrade-apache-to-latest-version-on-debian-11-bullseye/)

**Comment by KaKi87** [comment]
I successfully upgraded both `apache2` and `code-server`, thanks !

**Comment by ihowell** [comment]
I am using Apache2 version 2.4.53 and cannot use the workaround from @leuit , as disabling `mod_proxy_http` breaks other services I run on my server. Is there another fix?

**Comment by KaKi87** [comment]
You don't need to disable that. Once upgraded, it just works.

**Comment by ihowell** [comment]
@KaKi87 Well, it isn't working for me, and neither is v3.12. I am however, running code-server on a separate machine than the apache server and just trying to forward the site. This is the current config I'm using:
```
<VirtualHost *:80>
	     ServerName vscode.mydomain.com
	     UseCanonicalName on
	     Redirect / https://vscode.mydomain.com
</VirtualHost>

<VirtualHost *:443>
	     ServerName vscode.mydomain.com
	     
	     # setup the proxy
	     ProxyRequests off
	     <Proxy *>
	     	    Order deny,allow
		    Allow from all
	     </Proxy>

	     ProxyErrorOverride On

	     Header set Connection "Upgrade"
	     RequestHeader setifempty Connection "Upgrade"
	     Header set Upgrade "websocket"
	     RequestHeader setifempty Upgrade "websocket"

	     ProxyPass / http://192.168.50.60:8081/
	     ProxyPassReverse / http://192.168.50.60:8081/

	     <Location />
	     	       Order allow,deny
		       Allow from all
	     </Location>

	     SSLEngine on
	     Include /etc/letsencrypt/options-ssl-apache.conf
	     ErrorLog "/var/log/apache2/error.vscode.mydomain.dev.log"
	     SSLCertificateFile /etc/letsencrypt/live/mydomain/fullchain.pem
     	     SSLCertificateKeyFile /etc/letsencrypt/live/mydomain/privkey.pem
</VirtualHost>
```

And on the other machine I'm using `code-server --bind-addr 0.0.0.0:8081` to start it.

**Comment by leuit** [comment]
@ihowell 

Are you receiving the same error as OP? Is it not upgrading the websocket connection properly?

You say you're running code-server on a separate machine from apache; can you directly access code-server via the port it's listening on? Depending on the error you're receiving, I think it may just be a communication issue.

**Comment by ihowell** [comment]
I am receiving the same 1006 error as op, however I don't know how to tell if the websocket is being upgraded properly. I can access code-server from http://192.168.50.60:8081 in my browser and everything works fine. I just followed instructions and upgraded my server to Apache2 version 2.4.53, but it still isn't working.

**Comment by leuit** [comment]
@ihowell Wonderful! I was going to suggest changing the apache config next; glad you got it resolved!

**Comment by KaKi87** [comment]
Here's my working config using `apache2` v2.4.52 & `code-server` v4.3.0, using `ProxyPass` (and `RewriteEngine` only for WebSocket).

```
<VirtualHost *:80>
    ServerName code.kaki87.net
    RewriteEngine On
    RewriteCond %{HTTPS} off
    RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI}
</VirtualHost>

<VirtualHost *:443>
    ServerName code.kaki87.net
    ProxyRequests Off
    ProxyPass / http://localhost:3090/
    ProxyPassReverse / http://localhost:3090/
    RewriteEngine On
    RewriteCond %{HTTP:Upgrade} =websocket [NC]
    RewriteRule /(.*) ws://localhost:3090/$1 [P,L]
    SSLCertificateFile /home/kaki/.acme.sh/kaki87.net/fullchain.cer
    SSLCertificateKeyFile /home/kaki/.acme.sh/kaki87.net/kaki87.net.key
</VirtualHost>
```

I always try to make those as light as possible.
I don't think proxying to the local host or to another host on the local network changes anything.
Also, @ihowell, when making future reports about something that *isn't working*, please document the unexpected behavior as much as you can, because it is as important as documenting your configuration. :)

**Comment by Drealine** [comment]
Upgrade Apache2 to 2.4.52 also solved the issue for me without change anythingelse in apache configuration.

**Comment by maverjk** [comment]
> 

Hi @ihowell can you please share your solution? I have your same issue running last Apache version (2.4.6)

**Comment by datakid** [comment]
Upgrading apache2 worked for me.

**Comment by ZhengHui-Z** [comment]
This issue has not been resolved in version 4.

**Comment by mashroomxl** [comment]
try nginx config as follows:
```nginx
location ~ ${your frontend url pattern} {
    # add it if your url is dynamic
    resolver {your DNS server}
    
    # trick here, consult here for Nginx official doc
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection upgrade;
    # trick here, if absent, the server will block the websocket request if the origin is NOT equal to the host
    proxy_set_header Origin http://${your backend host}/;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    
    proxy_set_header Accept-Encoding gzip;
    proxy_cookie_domain ${your backend host} ${your frontend host};
    
    proxy_pass ${your backend url pattern};
}
```
config above working for me. my scene：

- code-server: 4.18.0, running in an container of Kubernetes
- nginx:1.9.7, running in an container of another Kubernetes.

**Comment by lilithebowman** [comment]
As of Apache `2.4.58` I'm still having this issue. 😒 
```
lilithe@lilithebowman:~$ apache2 -v
Server version: Apache/2.4.58 (Ubuntu)
Server built:   2025-04-03T14:36:49
```

```
Status
404
Not Found
VersionHTTP/1.1
Transferred215 B (0 B size)
DNS ResolutionSystem

	
Connection
	Upgrade
Content-Encoding
	br
Content-Type
	text/plain
Date
	Thu, 24 Apr 2025 16:22:10 GMT
Server
	Apache/2.4.58 (Ubuntu)
Transfer-Encoding
	chunked
Vary
	Accept-Encoding
	
Accept
	*/*
Accept-Encoding
	gzip, deflate, br, zstd
Accept-Language
	en-US,en;q=0.5
Cache-Control
	no-cache
Connection
	keep-alive, Upgrade
Cookie
	code-server-session=%24argon2id%24v%3D19%24m%3D65536%2Ct%3D3%2Cp%3D4%24mBGJVPPISLtELQT8KxmJcQ%24aZdISVoXpjpHH89DwmOOTlcTQ%2Bq257Nnfb2iiXvlPP0
Host
	<my site HOST>
Origin
	<my site URL>
Pragma
	no-cache
Sec-Fetch-Dest
	empty
Sec-Fetch-Mode
	websocket
Sec-Fetch-Site
	same-origin
Sec-WebSocket-Extensions
	permessage-deflate
Sec-WebSocket-Key
	CPDPULLXB/3igjyaVRePmw==
Sec-WebSocket-Version
	13
Upgrade
	websocket
User-Agent
	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:137.0) Gecko/20100101 Firefox/137.0
```

**Comment by KaKi87** [comment]
> As of Apache `2.4.58` I'm still having this issue. 😒

Share your config.

**Comment by lilithebowman** [comment]
> > As of Apache `2.4.58` I'm still having this issue. 😒
> 
> Share your config.

Sure thing! Sorry I was just cleaning up my `/etc/apache2/sites-available/` because it's been there for years with a few unnecessary site configs and things LetsEncrypt made that don't need to be there. Now that it's cleanly whittled down to the configs I need for my sites, I can begin to debug this.

Okay false alarm. Here is my fixed config!

`cat /etc/apache2/sites-available/code-server.conf `
```
<VirtualHost *:443>
        ServerName code.lilithebowman.com

        <Proxy *>
                Allow from all
                Allow from localhost
        </Proxy>

        Header add Connection "Upgrade"
        RequestHeader set Connection "Upgrade"


        RewriteEngine On RewriteCond %{HTTP:Upgrade} =websocket [NC]
        RewriteRule /(.*) ws://127.0.0.1:1024/$1 [P,L]
        RewriteCond %{HTTP:Upgrade} !=websocket [NC]
        RewriteRule /(.*) http://127.0.0.1:1024/$1 [P,L]
        ProxyRequests off ProxyPass / http://127.0.0.1:1024/ nocanon retry=10 
        ProxyPassReverse / http://127.0.0.1:1024/ retry=10

        ProxyPass /api/websocket ws://127.0.0.1:8123/api/websocket
        ProxyPassReverse /api/websocket ws://127.0.0.1:8123/api/websocket
        #Header add Connection "Upgrade"
        #RequestHeader set Connection "Upgrade"

        Include /etc/letsencrypt/options-ssl-apache.conf
        SSLCertificateFile /etc/letsencrypt/live/code.lilithebowman.com/fullchain.pem
        SSLCertificateKeyFile /etc/letsencrypt/live/code.lilithebowman.com/privkey.pem
</VirtualHost>
```
