### ISSUE TITLE
github auth faild

### ISSUE THREAD

**Issue by eng-dibo** [coder/code-server#4729]
I generated an SSH key to authenticate `gitLens` extension to my github account. it was working but suddenly I to a forbidden error

![image](https://user-images.githubusercontent.com/57308531/149098603-78d5b5c7-8195-4da8-89d7-7036d04bd565.png)

**Comment by jsjoeio** [comment]
@eng-dibo Can you please fill out a proper bug report? That'll help us help you faster! Thanks!
