### ISSUE TITLE
How to pass display(GUI code) through code-server docker edition?

### ISSUE THREAD

**Issue by tydaytygx** [coder/code-server#4731]
### Discussed in https://github.com/coder/code-server/discussions/4730

<div type='discussions-op-text'>

<sup>Originally posted by **tydaytygx** January 12, 2022</sup>
For example I want to use turtle **GUI** with Python3
```python
from turtle import *
```
Could I use browser to show the GUI display?
I got python3-tk installed but it shows the error like this
```log
_tkinter.TclError: no display name and no $DISPLAY environment variable
```
</div>

**Comment by jsjoeio** [comment]
I think this makes sense to discuss in that original Discussion. Let's move there.
