### ISSUE TITLE
How to run LiveServer or preview HTML w/Javascritp

### ISSUE THREAD

**Issue by CalvoUTN** [coder/code-server#4755]
Hi! I'm trying to learn Javascript and I'm following a course in Udemy. I set up a code-server in Docker in my server and I access it through my domain in code.domain.com.

What I'm trying to do is to access a .html file I've done following the guide showing a simple `alert("Hello World")` but I haven't been able to do it. I can "expose" the port 5500 using Live Server plugin, but I'm not able to actually use it. 

Is there any guide on how to use this for web development and preview your code?

This is what I get when I go to code.domain.com/proxy/5500

![image](https://user-images.githubusercontent.com/49721926/149642410-02244401-66b4-4d11-8a0e-ce484a3ca4c1.png)

But if I click the folder I get a 404 error.

**Comment by CalvoUTN** [comment]
So I realized that I when I click the file the part "/port/5500/" is stripped and thus I get the 404 code. I can get to the file manually tho. 

I still get these problems:
- Javascript is not being executed.
- How can easily access these files without having to write the full address?

**Comment by CalvoUTN** [comment]
So I got to solve this issue thanks to someone on the LinuxServer.io Discord (@aptalca there). I'll write the solution in case someone is having the same problems and doesn't find an easy guide.

You'll want to access your live server from https://port.code-server.domain.com. I'l suppose that you are using SWAG for your reverse proxy, as it's what I'm using, although it shouldn't be too different with other program. 

1) You'll create a new CNAME entry in your DNS server (like CloudFlare) pointing to 5500.code-server.domain.com (in case you are using http verification) or *.code-server.domain.com (if you are using DNS verification).

2) In your docker-compose for SWAG you'll add the environmental variable:
 `   - EXTRA_DOMAINS=5500.code-server.domain.com`

3) You'll use the proxy setting in the code-server docker-compose like this:
`      - PROXY_DOMAIN=code-server.domain.com`

4) You'll install the plugin Live Server and click "Go Live".

Now you are able to navigate to 5500.code-server.domain.com and see all the files in your workplace. Javascript is working correctly.

Sorry for opening this issue as it seems I might have been able to solve it by myself, but without the help in the Discord channel I wouldn't have figured it out.

Thanks a lot for this piece of software!

**Comment by ArthurBussiere** [comment]
Thank you, it helps me a lot!
