### ISSUE TITLE
not giving a tunnel link of vscode

### ISSUE THREAD

**Issue by lsndeionw** [coder/code-server#4756]
![Screenshot (30)](https://user-images.githubusercontent.com/97796736/149651360-9e5639f3-2e2d-475b-8c5b-82098f9f5a46.png)
<!--

### when i run ! code-server --bind-addr 127.0.0.1:8040  & lt --port 8040   in kaggle ,,  it doesnot give me link for vscode 

but it works on google colab..

**Comment by lsndeionw** [comment]
when i run ! code-server --bind-addr 127.0.0.1:8040  & lt --port 8040   in kaggle ,,  it doesnot give me link for vscode 

but it works on google colab..

**Comment by jsjoeio** [comment]
@lsndeionw can you please open a bug report using our template and fill out everything? that'll help us help you faster! thanks!
