### ISSUE TITLE
$PATH got overwritten in docker

### ISSUE THREAD

**Issue by chunjiw** [coder/code-server#4758]
## OS/Web Information

- Web Browser: Chrome
- Local OS: Arch Linux (Endeavour OS)
- Remote OS: Debian
- Remote Architecture: x86_64
- `code-server --version`: 4.0.1

## Steps to Reproduce

1. Add code-server to julia docker
```
FROM julia:latest
# RUN curl -fOL https://github.com/cdr/code-server/releases/download/v3.12.0/code-server_3.12.0_amd64.deb; \
#    dpkg -i code-server_3.12.0_amd64.deb;\
#    rm code-server_3.12.0_amd64.deb;
RUN curl -fOL https://github.com/coder/code-server/releases/download/v4.0.1/code-server_4.0.1_amd64.deb; \
    dpkg -i code-server_4.0.1_amd64.deb;\
    rm code-server_4.0.1_amd64.deb;
```
2. Start the docker
3. Log in code server
4. run `echo $PATH`

## Expected

Output is the same in Julia docker `/usr/local/julia/bin:...`

## Actual

`/usr/local/julia/bin` is missing from `PATH`. Instead, there is a code-server related path.

This issue can be reproduced in VS Code: No

**Comment by jsjoeio** [comment]
Did this happen in 3.12.0?

**Comment by chunjiw** [comment]
No, I've been using 3.12.0 with no problem

**Comment by code-asher** [comment]
Perhaps the same as https://github.com/coder/code-server/issues/4699

**Comment by chunjiw** [comment]
Yes, I think its same as #4699. Somehow I failed to notice #4699 before creating this issue..

**Comment by jsjoeio** [comment]
@chunjiw no worries! I also failed to realize this was a duplicate. Let's consolidate then and track in #4699
