### ISSUE TITLE
 without  "?folder=" in url, "Open in Integrated Terminal" does not work

### ISSUE THREAD

**Issue by oruharo** [coder/code-server#4760]
## OS/Web Information

- Web Browser: Google Chrome    /  97.0.4692.71（Official Build） （x86_64）
- Local OS:  Mac OS Monterey  12.1
- Remote OS:  ubuntu container on amazonlinux2 
- Remote Architecture:  Amazon EKS ( Kubernetes)
- `code-server --version`: 4.0.1 735c6da829535969ff7193c79379299e4a1cb9bc

## Steps to Reproduce

1. Open code-server without specifying a folder in the URL. 
2. Select "Open in Integrated Terminal" from EXPLORER.

## Expected
Display prompt on the terminal.

## Actual
the prompt is not displayed on the terminal.

## Screenshot

https://user-images.githubusercontent.com/9918931/149809513-34963907-3fe9-4db5-a1bf-10cd85a79834.mov

## Logs

[OUTPUT] -> [Log(Window)]

[2022-01-18 08:11:32.462] [window] [error] No terminal backend registered for remote authority 'remote': Error: No terminal backend registered for remote authority 'remote'
    at k.createProcess (https://xxxxxxxx.com/static/out/vs/workbench/workbench.web.api.js:1726:14088)
    at ki._createProcess (https://xxxxxxxx.com/static/out/vs/workbench/workbench.web.api.js:2752:98504)
    at https://xxxxxxxx.com/static/out/vs/workbench/workbench.web.api.js:2752:80658

**Comment by jsjoeio** [comment]
Hmm...it took a second but it did load

## Video

https://user-images.githubusercontent.com/3806031/149992990-fc0676a2-80ec-4031-b378-b450abdf8086.mov

That error message you share though is interesting 🤔

@code-asher can you reproduce?

**Comment by w0otness** [comment]
I can't get step 1 to reproduce, when I attempt to open with `?folder=` it automatically puts in there the last folder I visited.

**Comment by oruharo** [comment]
Thank you.
I tried it on docker. It has been reproduced.

```
{
rm -rf $HOME/code-server4_0_1
mkdir -p $HOME/code-server4_0_1
cd $HOME/code-server4_0_1
docker run -it --name code-server4_0_1 -p 127.0.0.1:8081:8080 \
  -v "$PWD/.config:/home/coder/.config" \
  -v "$PWD:/home/coder/project" \
  -u "coder:coder" \
  -e "DOCKER_USER=coder" \
  codercom/code-server:4.0.1
}
```

https://user-images.githubusercontent.com/9918931/150031798-e78ba667-c199-4600-8ab4-d014499f2d23.mov

**Comment by oruharo** [comment]
> it automatically puts in there the last folder I visited.

Create a new code server instance before step1.
Or remove  ~/.local/share/code-server/coder.json before step1.

**Comment by oruharo** [comment]
Another problem occurs under the same conditions.
"EXPLORER" does not detect any changes in the folder.

https://user-images.githubusercontent.com/9918931/150035957-3c2ce675-e95a-44f9-82f3-cc16f1e14ef2.mov

**Comment by lwmacct** [comment]
I am also concerned about this issue

**Comment by oruharo** [comment]
> v4.1.0
> The workspace or folder passed on the CLI will now use the same redirect
> method that the last opened workspace or folder uses. This means if you use
> something like code-server /path/to/dir you will now get a query parameter
> added (like so: my-domain.tld?folder=/path/to/dir), making it easier to edit
> by hand and making it consistent with the last opened and menu open behaviors.

It seems that this change has fixed it ! 
Thank you !!

**Comment by jsjoeio** [comment]
Hooray! Thanks for confirming. Going to close this for now.
