### ISSUE TITLE
Can't login the github and tabnine

### ISSUE THREAD

**Issue by linjiahao962889027** [coder/code-server#4762]
## OS/Web Information

- Web Browser: Edge-97.0.1072.62
- Local OS: Window10/11
- Remote OS: WSL-2 (Windows11 Ubuntu-20.04 LTS) ( Container Ubuntu-20.04 LTS)
- Remote Architecture: nginx proxy
- `code-server --version`: 4.0.1

## Steps to Reproduce

1.  Click login github
2.  Click continue in the page of login github
3.  Callback to the code-server
4.  Without response when click login tabnine
5.  Can't open the page of tabnine

## Expected

Login github success

## Actual

Reject the forbid page, and the url of callback is 404;

## Screenshot

![image](https://user-images.githubusercontent.com/46292984/150064864-c6df035a-42d3-4203-82eb-e1b432a073d2.png)
![image](https://user-images.githubusercontent.com/46292984/150065661-dc1f0731-126d-4801-9e94-a97286b8f8fa.png)
![image](https://user-images.githubusercontent.com/46292984/150065791-3a974f48-f748-4bcd-9b4d-3b998f8915be.png)
![image](https://user-images.githubusercontent.com/46292984/150065931-6cc8cb30-714d-4179-a023-cbfcc38d3352.png)
![image](https://user-images.githubusercontent.com/46292984/150066239-deaadca1-cb65-4ca7-a022-fd212371f46d.png)

## Notes

This issue can be reproduced in VS Code: No

**Comment by kimgiftww** [comment]
have been facing the same issue since upgraded to 4.0.1. Will see if downgrading helps...

**Comment by kimgiftww** [comment]
> have been facing the same issue since upgraded to 4.0.1. Will see if downgrading helps...

After downgraded to 3.12.0 and set the ssl working ( https://coder.com/docs/code-server/latest/guide#using-lets-encrypt-with-nginx ) , I am able to login to github from code-server again.

**Comment by hcoohb** [comment]
I cannot seem to be able to login either
```
code-server: v4.0.1
 VS Code: v1.63.0
Commit: 735c6da829535969ff7193c79379299e4a1cb9bc
Date: 2022-01-05T17:51:28Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.137 Safari/537.36
```

**Comment by Alex4386** [comment]
I can reproduce this issue on code-server with:
* Client: Firefox Developer Edition (on Ubuntu 18.04 system)
* Server: code-server 4.0.1 (installed on Ubuntu 20.04 system)

I remember that there was a JavaScript Error on the browser console when Forbidden dialog is shown.
Frankly, the specific client is only one that shows "Forbidden" error during GitHub login.

I can't attach my log at the moment. But I hope this information can help the troubleshooting process.

**Comment by ksylvan** [comment]
Any updates on Getting Web VSCode and TabNine working together? I’ve tried port-forwarding 5555 on localhost to the remote server’s port 5555 with some limited success.

**Comment by jsjoeio** [comment]
We were working with their team on this. Let me find out!

**Comment by ksylvan** [comment]
For TabNine, after port-forwarding 5555 from the remote to localhost, I'm seeing these kinds of JavaScript errors when visiting the TabNine hub at localhost:5555:

```
react-dom.production.min.js:216 TypeError: Cannot read properties of undefined (reading 'includes')
    at e.value (useFeatureFlags.ts:23:30)
    at settings.ts:113:19
    at jue (AddtionalSettings.tsx:26:7)
    at aa (react-dom.production.min.js:157:137)
    at Uo (react-dom.production.min.js:267:460)
    at Os (react-dom.production.min.js:250:347)
    at ks (react-dom.production.min.js:250:278)
    at ws (react-dom.production.min.js:250:138)
    at ys (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115

Uncaught TypeError: Cannot read properties of undefined (reading 'includes')
    at e.value (useFeatureFlags.ts:23:30)
    at settings.ts:113:19
    at jue (AddtionalSettings.tsx:26:7)
    at aa (react-dom.production.min.js:157:137)
    at Uo (react-dom.production.min.js:267:460)
    at Os (react-dom.production.min.js:250:347)
    at ks (react-dom.production.min.js:250:278)
    at ws (react-dom.production.min.js:250:138)
    at ys (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
```

See https://github.com/codota/TabNine/issues/305

**Comment by ksylvan** [comment]
> We were working with their team on this. Let me find out.

Any news on this?

**Comment by jsjoeio** [comment]
I think next steps is for me to work on https://github.com/coder/code-server/issues/1936#issuecomment-1247072800

I'm hoping to start on it today. Feel free to subscribe to that issue for updates. Also, let me know if you're interested in helping!

**Comment by ksylvan** [comment]
In case this helps, I was able to render the TabNine hub page in a separate browser tab by the tedious procedure listed here:

https://github.com/ksylvan/remote-coding/blob/main/README.md#a-note-on-using-tabnine-and-vscode-web

**Comment by code-asher** [comment]
I missed this issue but this was eventually fixed a while back.
