### ISSUE TITLE
[iPadOS] Can't copy/paste a whole line in editor

### ISSUE THREAD

**Issue by ManiaciaChao** [coder/code-server#4766]
## OS/Web Information

```
code-server: v4.0.1
VS Code: v1.63.0
Commit: 735c6da829535969ff7193c79379299e4a1cb9bc
Date: 2022-01-05T17:51:28Z (1 wk ago)
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.3 Safari/605.1.15
Remote OS: Debian 7 & Ubuntu 20.04 amd64
```

## Steps to Reproduce

1. Open an file.
2. Copy/cut/paste a line from editor with shortcut `cmd+c/x/v` or from right-click menu.

## Expected

It should apply on the whole line.

## Actual

Nothing happens. Copy/cut/paste will only work for selected text, not the line.

## Screenshot

https://user-images.githubusercontent.com/13493748/150166142-4f918300-6a4d-4199-85cf-d9b8eb08586c.mp4

## Notes

This issue can be reproduced in VS Code: No

**Comment by ManiaciaChao** [comment]
Can be reproduced both in Safari and PWA.

**Comment by jsjoeio** [comment]
Thanks @ManiaciaChao - can you try the workaround suggested by @dokastho?

Also can you reproduce this in vscode.dev?

**Comment by ManiaciaChao** [comment]
> Thanks @ManiaciaChao - can you try the workaround suggested by @dokastho?
> 
> Also can you reproduce this in vscode.dev?

Unfortunately, That workaround doesn't work on my machine. 

However, I found it an upstream issue with `vscode` or `monaco-editor`, which can be reproduced both on [monaco-editor](https://microsoft.github.io/monaco-editor/) or [vscode.dev](vscode.dev).

Just close this issue for now :) I will open an issue at `vscode`'s repo and try to make a PR in the next following days.

**Comment by jsjoeio** [comment]
@ManiaciaChao nice finds! Sounds good. Thank you so much for checking and following up :)
