### ISSUE TITLE
[Bug]: Login GitHub

### ISSUE THREAD

**Issue by Stanixia** [coder/code-server#4795]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Version 1.34.81 Chromium: 97.0.4692.99 (Build officiel) (64 bits)
- Local OS: Windows 10
- Remote OS: Docker (codercom/code-server:latest)
- Remote Architecture: 
- `code-server --version`: 4.0.1

### Steps to Reproduce

1. git push -u origin main 

### Expected

Have github authentication message

### Actual

Error committing github

### Screenshot/Video

![image](https://user-images.githubusercontent.com/5864038/151211743-7ac5ad2c-7b30-469b-aae3-caaae70f55be.png)
![image](https://user-images.githubusercontent.com/5864038/151211707-29f7074d-3cdd-47da-880b-c6904553e13a.png)
![image](https://user-images.githubusercontent.com/5864038/151211723-ca587132-c770-4abf-a701-b992ea1b8963.png)

### Does this issue happen in VS Code?

- [X] I cannot reproduce this in VS Code.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by jsjoeio** [comment]
Argh. I can't reproduce locally on macOS + Brave but obviously that's because I've already authenticated with Git. We've had this in the past and I know @code-asher has fixed it. 

![image](https://user-images.githubusercontent.com/3806031/151249397-95dad44d-b524-4af9-8974-e3ef20ae02df.png)

What happens if you open the Command Palette > "Publish to GitHub" > enter your PAT? Does that work?

**Comment by Stanixia** [comment]
Hi,

It's ok if I use git remote add origin and PAT 

I use Brave and Windows or MacOs but my setup is a Ubuntu 20.04 in a VPS and Docker container in my VPS 
I also use Nginx Proxy Manager for external with a SSL 

It's possible the proxy doesn't work with github callback ?

**Comment by jsjoeio** [comment]
> It's ok if I use git remote add origin and PAT

awesome!

> It's possible the proxy doesn't work with github callback ?

Possibly 🤔 I wish I knew how to reset my Git auth locally so I could actually try to reproduce. There's a possibility it's broken and not related to your proxy

**Comment by True-cc** [comment]
Happens on MacOS BigSur (11.4) and Arch Linux, both with firefox and vivaldi

**Comment by jsjoeio** [comment]
Thanks @True-cc! 

> What happens if you open the Command Palette > "Publish to GitHub" > enter your PAT? Does that work?

For now you can use this workaround^

**Comment by Stanixia** [comment]
![image](https://user-images.githubusercontent.com/5864038/151828720-653cb4fb-b947-48c8-b516-a06a3d2dc5f3.png)

Settings Sync

**Comment by jsjoeio** [comment]
@ricreis394 can you share a video?

**Comment by ricreis394** [comment]
> @ricreis394 can you share a video?

sure, here it goes
![Animation](https://user-images.githubusercontent.com/11768109/153956135-2d61fd31-155c-4e5f-9b9e-4c5937e97bfb.gif)

**Comment by jsjoeio** [comment]
@ricreis394 Ah that's a different flow than the one I'm referring to. Mine asks for a PAT inside code-server 🤔 I wonder if it's cause I'm using the PWA. I have no idea

<img width="1904" alt="image" src="https://user-images.githubusercontent.com/3806031/153958834-ffd03490-107f-4ed3-b2d0-13b9b7602633.png">

What happens if you hit cancel?

**Comment by ricreis394** [comment]
> What happens if you hit cancel?

It just cancels. Won't do anything
I'm using code behind a reverse proxy (nginx), at first I thought that could be the problem, but nope. The gif I sent it from direct IP connection, no redirections

The strange thing is, before version 4, I was logged in on github, don't know why it logged out...

**Comment by jsjoeio** [comment]
@ricreis394 hmm...I mean we had a big upgrade for VS Code in 4 so maybe it reset there? I'm not sure.

I don't know when I'll be able to look into this cause I can't easily reproduce :( But I'll add it to the high priority list.

**Comment by jsjoeio** [comment]
Heads-up: for anyone else experiencing this, please give a thumbs-up on the issue description! That will help me see how many people are affected by this and prioritize properly.

**Comment by ricreis394** [comment]
@jsjoeio anything I can do to help debug the issue?

**Comment by chrisdburr** [comment]
Not sure if this helps, but I can push to GH using username and PAT after cancelling the default login option. However, it asks for the PAT each time I try to push a commit.

Information:

OS: Debian Bullseye
Code-Server: Docker Container (Latest) 
Browser: iPad (Safari)

**Comment by jsjoeio** [comment]
> @jsjoeio anything I can do to help debug the issue?

Hmm...you were very helpful with the video! I wish there was a way to reproduce it consistently. One thing you could do is grab the authorization URL that opens in the browser (be sure to remove the auth token from the URL) and share it here?

I know we've patched that in the past so I'm guessing we lost that patch. cc @code-asher 

> However, it asks for the PAT each time I try to push a commit.

Thank you @chrisdburr! That is usually a separate error that means your credential helper isn't caching your credentials. [This](https://www.freecodecamp.org/news/how-to-fix-git-always-asking-for-user-credentials/) has helped me in the past.

**Comment by code-asher** [comment]
You are probably right about it being lost.  I will need to be in this code soon for other reasons so I will take a look.

**Comment by ricreis394** [comment]
> Hmm...you were very helpful with the video! I wish there was a way to reproduce it consistently. One thing you could do is grab the authorization URL that opens in the browser (be sure to remove the auth token from the URL) and share it here?

@jsjoeio 

`https://vscode-auth.github.com/authorize/?callbackUri=http://10.10.1.246:8443/callback%253Fvscode-requestId%253D<hiddenRequestId>%2526vscode-scheme%253Dcode-oss%2526vscode-authority%253Dvscode.github-authentication%2526vscode-path%253D%25252Fdid-authenticate&scope=repo%20workflow&state=<hiddenState>&responseType=code&authServer=https://github.com`

Not sure what to hide, so I hidden the requestId and the State

**Comment by steilerDev** [comment]
Based on the reports, this might be due to our setup. I'm experiencing the same issue with my docker (`codercom/code-server:latest`) + nginx-proxy (with lets-encrypt support).

This issue happens on all browsers I tried (latest Chrome/Safari/Brave on macOS + Safari on iPad).

The workaround in #1883 still works. (Unfortunately the Github Login seems to be stored locally in the browser, so using inkognito mode should give you a 'clean' instance to reproduce @jsjoeio)

In my opinion storing and using a PAT on the server would be the best way, so I won't need to re-authenticate when using a new client. (But I'm new to this project, so I have no idea if this is even remotely possible :D )

**Comment by cnfatal** [comment]
May an oauth app be used to have a "valid" callbackUri: [creating-an-oauth-app](https://docs.github.com/en/developers/apps/building-oauth-apps/creating-an-oauth-app)

The desktop version vscode using [GitHub for VSCode](https://github.com/settings/connections/applications/01ab8ac9400c4e429b23) to complete oauth.

But It still not working now

**Comment by ricreis394** [comment]
Used the below method and worked as a temporary workaround

1. CTRL + Shift + P ▶️ Publish to Github
2. Will show a window asking permission to allow signin, press `Allow`
3. Extract the `state` from the url opened and insert that in this url `https://vscode-auth.github.com/authorize/?callbackUri=vscode://vscode.github-authentication/did-authenticate&scope=repo,workflow&state=<insert-state-from-code-server-here>&responseType=code`
4. open the new url in the browser, and allow sign in, after submitting it will generate a new url/code. Copy that generated url that will be something like this: `vscode://vscode.github-authentication/did-authenticate?code=<code>&state=<state>`
5. go to code-server and click on "Signing in to GitHub" on the taskbar. It then will ask for the URI and paste the url
6. And boom, you're logged in!

Credits: https://github.com/coder/code-server/issues/1883#issuecomment-712595418

**Comment by steilerDev** [comment]
Build a little script using the method above to get the URL.

```
#!/bin/bash

read -p "VSCode GH Auth URL:" URL

STATE=$(echo $URL | awk -F'[=&]' '{print $6}')

NEW_URL="https://vscode-auth.github.com/authorize/?callbackUri=vscode://vscode.github-authentication/did-authenticate&scope=repo,workflow,read:user,user:email&state=${STATE}&responseType=code"

clear
echo 
echo "1. Access URL below & grant access"
echo
echo $NEW_URL
echo
echo "2. Don't use 'Open with VSCode...'"
echo "3. Copy the token."
echo "4. Switch back to VS code."
echo "5. Click Signing in to github.com... in the status bar."
echo "6. Paste the token and hit enter."
```

**Comment by True-cc** [comment]
If nothing else works, maybe having that within code-server could be the best solution?

**Comment by liuqian1996** [comment]
me too, same enviroment with u

**Comment by jsjoeio** [comment]
Thank you @ricreis394 for the solution and @steilerDev for the killer script 🔥

Hoping this is a quick fix on our end. We had yesterday off but we're back this week. Thanks for the patience!

**Comment by jsjoeio** [comment]
A fix will be available in the next release!

**Comment by liuqian1996** [comment]
> Reference in new iss

Thank you
