### ISSUE TITLE
[Bug]: Fix links in package.json

### ISSUE THREAD

**Issue by jsjoeio** [coder/code-server#4802]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

N/A

### Steps to Reproduce

1. go to https://www.npmjs.com/package/code-server

### Expected

Links on side should point to `/coder/code-server`

### Actual

![Uploading image.png…]()

### Does this issue happen in VS Code?

- [X] I cannot reproduce this in VS Code.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

Mentioned by @im-coder-lg

**Comment by im-coder-lg** [comment]
Do you want me to fix it?

**Comment by jsjoeio** [comment]
@im-coder-lg sure!

**Comment by im-coder-lg** [comment]
Screenshot since the one on the first comment didn't get uploaded properly: ![image](https://user-images.githubusercontent.com/3806031/151070922-a4d1bcb2-51ed-4496-9da0-7ad9b6a8ade3.png)
