### ISSUE TITLE
release: 4.1.0

### ISSUE THREAD

**Issue by code-asher** [coder/code-server#4803]
## Checklist

- [x] Assign to next release manager
- [ ] Close previous release milestone
- [x] Create next release milestone
- [x] Associate issue with next release milestone

**Comment by benz0li** [comment]
Thank you for this great release and resolving https://github.com/coder/code-server/issues/4804. The following does not seem to be necessary any more with v4.1.0 (https://github.com/coder/code-server/issues/4777#issuecomment-1023511535):

> [...] one must explicitly open a folder (File > Open Folder...) before opening a Jupyter notebook.
