### ISSUE TITLE
[Bug]: Open Directory with # doesn't work.

### ISSUE THREAD

**Issue by SelfMadeSystem** [coder/code-server#4807]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Firefox & Vivaldi
- Local OS: macOS & Arch Linux
- Remote OS: Arch Linux
- Remote Architecture: x64
- `code-server --version`: 4.0.2 5cdfe74686aa73e023f8354a9a6014eb30caa7dd

### Steps to Reproduce

1. Create 2 directories: one named C, other named C# 
2. Open C# with code-server

### Expected

It opens the C# directory like it should. Works fine with local vscode

### Actual

Opens C directory instead.

### Does this issue happen in VS Code?

- [X] I cannot reproduce this in VS Code.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

I do have code-server under a nginx at `https://example.com/vscode/`, but that shouldn't matter.
I installed code-server from the AUR, but that shouldn't matter either.

I didn't test with any other special characters.

**Comment by jsjoeio** [comment]
What an odd bug. How did you find that?!

Thanks for reporting. I was able to reproduce it locally.

## Video

https://user-images.githubusercontent.com/3806031/151868856-8b174b0c-9472-4640-aa84-d936318334ff.mov

**Comment by True-cc** [comment]
> How did you find that?!
Using my dumass way of organising projects that I made too long ago lol. I'm actually using code-server on my personal computer so I can connect to it at school to do code stuff when I'm bored

Thx for fixing bug.

**Comment by code-asher** [comment]
Looks like at some point this got fixed upstream.
