### ISSUE TITLE
[Chore]: update vscode to 1.64

### ISSUE THREAD

**Issue by jsjoeio** [coder/code-server#4822]
https://code.visualstudio.com/updates/v1_64

**Comment by benz0li** [comment]
https://code.visualstudio.com/updates/v1_65 is out.

**Comment by jsjoeio** [comment]
Yes! We saw that. We couldn't finish the 1.64 upgrade in time with the last release (though we could cut another release mid-March if folks wanted). We're in the process of changing the architecture to a patch which will allow us to stay up to date with VS Code much faster.

**Comment by benz0li** [comment]
> [...] (though we could cut another release mid-March if folks wanted). [...]

I don't mind if you skip v1.64 and go straight to v1.65 as the base for the next release. I'd suggest you use v1.64 for extended testing of your patch system, then.

**Comment by jsjoeio** [comment]
> I don't mind if you skip v1.64 and go straight to v1.65

Since we're almost done we'll upgrade to 1.64 regardless. But ideally we have the patch work done and then can upgrade v1.65.
