### ISSUE TITLE
[Bug]: (install.sh) Cannot install preferred version via yarn

### ISSUE THREAD

**Issue by jvadair** [coder/code-server#4832]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Firefox
- Local OS: Kubuntu
- Remote OS: Raspberry Pi OS
- Remote Architecture: armv7l
- `code-server --version`: (not applicable)

### Steps to Reproduce

1. download the install.sh script
2. `sh install.sh --version 3.11.1`

### Expected

Version 3.11.1 should be installed

### Actual

The latest version is installed

### Logs

`yarn global add code-server@3.11.1` does not result in any errors.
When installed via this method, the correct version is installed.

### Screenshot/Video

![Screenshot_20220205_125447](https://user-images.githubusercontent.com/58600250/152653332-15d0343d-ba99-44f0-a417-e90a9e483163.png)
![Screenshot_20220205_125518](https://user-images.githubusercontent.com/58600250/152653338-123b7c08-534b-4e4c-afeb-56f9c2191fa7.png)
![Screenshot_20220205_120935](https://user-images.githubusercontent.com/58600250/152653343-7ed7f078-874f-49e2-bfa9-c6473c1990cb.png)

### Does this issue happen in VS Code?

- [X] I cannot reproduce this in VS Code.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

I am installing this version because I believe it is the version I had before upgrading. The latest version does not work for me, since it throws this error every time I open it:

"The workbench failed to connect to the server (Error: WebSocket close with status code 1006)"

I know that #4443 addresses this issue, but the solutions provided are only for nginx, and I use Apache.

**Comment by ZandercraftGames** [comment]
I too am having a similar issue with the latest version and the 1006 error. It would be nice to get a solution that works with Apache to solve this issue. For now I'm deferring the update.

**Comment by jvadair** [comment]
> I too am having a similar issue with the latest version and the 1006 error. It would be nice to get a solution that works with Apache to solve this issue. For now I'm deferring the update.

What is the latest working version for you? I would like to stay as up-to-date as possible.

**Comment by ZandercraftGames** [comment]
> What is the latest working version for you? I would like to stay as up-to-date as possible.

I updated to 3.11.0, but it introduces an error of `Unable to write to Folder Settings because no resource is provided.`. Doesn't seem to functionally change anything at first glance, but I know they claim to have fixed it in subsequent versions. Just don't have those versions working. I might try going through all the minor version updates to see how far I can push it.

**Comment by jvadair** [comment]
> I might try going through all the minor version updates to see how far I can push it
I've upgraded to 3.12.0 now, and I'm not seeing any issues. It would seem the next releases are 4.x, so I won't be upgrading any further for now.

**Comment by jsjoeio** [comment]
I took a look at our install script. It looks like it always defaults to latest, and doesn't use `--version` even when passed. See here:
- https://github.com/coder/code-server/blob/main/install.sh#L431
- https://github.com/coder/code-server/blob/main/install.sh#L441

Thanks for catching this!

Apologies for the errors y'all. The team was 4 last year this time. Now I'm the only one full-time. Hoping I can get the 1006 error and others resolved so y'all can upgrade. In the meantime, thanks for the patience!
