### ISSUE TITLE
[Docs]: Slack link in Readme

### ISSUE THREAD

**Issue by f0x52** [coder/code-server#4843]
The join us on Slack badge links to https://coder.co/join-community, it should probably be https://coder.com/community

**Comment by jsjoeio** [comment]
Oops! Thanks for catching!

**Comment by bpmct** [comment]
Ah, this must have happened when we bulk-renamed `cdr` to `coder`. https://cdr.co/join-community is, in fact, a valid URL. 

https://coder.com/community is more comprehensive and offers more resources, though :)
