### ISSUE TITLE
[Feat]: print MOTD from terminal

### ISSUE THREAD

**Issue by 66545shiwo** [coder/code-server#4852]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### OS/Web Information

- Web Browser:  Chrome
- Local OS: Windows7
- Remote OS: Linux7
- Remote Architecture: x86
- `code-server --version`: 3.10.1

### Steps to Reproduce

1. open code-server in my browser
2. open a new terminal

### Expected

i expect that the bash prints my customed MOTD(Message of The Day) 

### Actual

the new bash doesn't print my MOTD(Message of The Day in  /etc/motd) 

### Logs

no logs

### Does this issue happen in VS Code?

- [X] I cannot reproduce this in VS Code.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

the new bash terminal  also couldn't print  messages  like "Last login: Fri Feb 11 10:14:59 2022 from " ,  I don't know what the reason is .
 i want to inform the users some messages  by MOTD

**Comment by jsjoeio** [comment]
I don't think this was ever supported by code-server, unless I'm mistaken?

Does it work in VS Code? I couldn't find much online.

I found a couple things online:
- https://stackoverflow.com/questions/68636037/write-message-of-the-day-by-images-used-by-vscode-remote-development
- https://gitlab.cern.ch/atlas/athena/-/merge_requests/45600
- https://marketplace.visualstudio.com/items?itemName=dotnsf.manholeofthisday

**Comment by 66545shiwo** [comment]
@jsjoeio Thank you for your reply !  
 Message Of The Day (MOTD) will work on any Linux distribution. When you first log in to a terminal on a  Linux system, you are usually greeted by that system’s message of the day(MOTD).  The message is set  in /etc/motd file. MOTD is showed  when I log in to the teminal by Security CRT.  But , code-server's terminal doesn't show my customed MOTD.  
Also , it's not this plugin [manholeofthisday](https://marketplace.visualstudio.com/items?itemName=dotnsf.manholeofthisday)
It works by adding `cat /etc/motd` command to bashrc ,but i think motd is an automatic behavior , it should be triggered automatically.

**Comment by jsjoeio** [comment]
@66545shiwo good to know!

Does this work in vanilla VS Code?

**Comment by 66545shiwo** [comment]
It also doesn't work in VS Code.
I used the remote ssh plugin , and then opened a terminal.  It didn't show my MOTD.

**Comment by jsjoeio** [comment]
@66545shiwo no I meant without using the remote ssh plugin or anything, does this work in VS Code?

As in, is this a feature supported by VS Code?

**Comment by 66545shiwo** [comment]
@jsjoeio 
motd is a linux's feature , and my local operating system is Windows , so i don't know how to test it on my local VS Code.

**Comment by jsjoeio** [comment]
@66545shiwo Hmm...I'm not sure either then. I don't think this is supported by VS Code. And it wasn't supported by code-server ever (AFAIK). Therefore, I don't think it's a bug. I will change this to a feature and add to the backlog.

**Comment by code-asher** [comment]
Marking as an upstream issue, for anyone looking to implement this it should probably go into https://github.com/microsoft/vscode rather than maintaining a patch here.
