### ISSUE TITLE
[Bug]: I can't use the physical keyboard to type Chinese normally on my Android device

### ISSUE THREAD

**Issue by xianyu-one** [coder/code-server#4854]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome
- Local OS: Android 11
- Remote OS: Debian11
- Remote Architecture: x86
- `code-server --version`: 4.0.1
- Device: Lenovo Tab P11 Pro (TB-J706F)

### Steps to Reproduce

1. open my dev folder
2. open README.md
3. Use Chinese input method

### Expected

Usually, the Chinese input method can select the correct characters by numbers:
https://pic.imgdb.cn/item/620669062ab3f51d91a33bc4.jpg
I can type multiple keyboard letters in a row
The characters are written to the file only if I select the correct text via number or enter selection or spacebar

### Actual

In fact, when I use the Chinese input method to type, it will be like this
https://pic.imgdb.cn/item/620669dc2ab3f51d91a40906.jpg

### Does this issue happen in VS Code?

- [x] I cannot reproduce this in VS Code.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by jsjoeio** [comment]
Can you reproduce this in vscode.dev?

**Comment by xianyu-one** [comment]
> Can you reproduce this in [vscode.dev](https://vscode.dev/)?

I can't reproduce in vscode.dev. This problem doesn't appear when I use vscode.dev for file editing.

So I looked at my dns settings (cloudflare) and turned off the proxy (CDN).

but it doesn't work.

Is this problem caused by my Nginx configuration file settings incorrectly?
Below is my config file content:
```
server {
  set $forward_scheme http;
  set $server         "172.17.0.1";
  set $port           8080;

  listen 80;
listen [::]:80;

listen 443 ssl http2;
listen [::]:443 ssl http2;

  server_name example.com;

  # Let's Encrypt SSL
  include conf.d/include/letsencrypt-acme-challenge.conf;
  include conf.d/include/ssl-ciphers.conf;
  ssl_certificate /etc/letsencrypt/live/npm-2/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/npm-2/privkey.pem;

    # Force SSL
    include conf.d/include/force-ssl.conf;

proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $http_connection;
proxy_http_version 1.1;


  access_log /data/logs/proxy-host-3_access.log proxy;
  error_log /data/logs/proxy-host-3_error.log warn;

  location / {

    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $http_connection;
    proxy_http_version 1.1;
    

    # Proxy!
    include conf.d/include/proxy.conf;
  }


  # Custom
  include /data/nginx/custom/server_proxy[.]conf;
}

```

**Comment by jsjoeio** [comment]
> I can't reproduce in vscode.dev. This problem doesn't appear when I use vscode.dev for file editing.

Thanks for checking! Probably just code-server then but not sure why. You don't have Codespaces, do you? Might be worth trying to reproduce there too.

I don't know exactly what I should look for but on my macOS, I can try reproducing.

Which keyboard do I use?

<img width="780" alt="image" src="https://user-images.githubusercontent.com/3806031/153944575-33bde7d4-5614-49dc-8fe0-269bb590a24c.png">

<img width="780" alt="image" src="https://user-images.githubusercontent.com/3806031/153944620-327868bb-4fe1-4767-8368-a44a4a52171f.png">

**Comment by xianyu-one** [comment]
> > I can't reproduce in vscode.dev. This problem doesn't appear when I use vscode.dev for file editing.
> 
> Thanks for checking! Probably just code-server then but not sure why. You don't have Codespaces, do you? Might be worth trying to reproduce there too.
> 
> I don't know exactly what I should look for but on my macOS, I can try reproducing.
> 
> Which keyboard do I use?
> 
> <img alt="image" width="780" src="https://user-images.githubusercontent.com/3806031/153944575-33bde7d4-5614-49dc-8fe0-269bb590a24c.png">
> 
> <img alt="image" width="780" src="https://user-images.githubusercontent.com/3806031/153944620-327868bb-4fe1-4767-8368-a44a4a52171f.png">

thank you for your reply !

If you want to try to reproduce on Mac, you can try "Pinyin - Simplified"

But this issue only occurs on Android devices.

I also use Mac or Windows for my work, and they work perfectly, did not encounter this problem.
So I don't think this situation can be reproduced in Mac OS. If you have an Android device, I think you can reproduce the problem.

I have also tried different keyboard app on Android devices, but none of them work properly, so I think there may be a bug in the code server or Android. So while submitting an issue here, I also tried to report this issue to Lenovo and Google.

Thank you again for your reply and assistance!

**Comment by xianyu-one** [comment]
> Hmm....
> 
> If it's only Android devices, I wonder if it's specific to code-server or something upstream thinking
> 
> Does this happen with any other application on Android? Can you reproduce it online with [xterm](https://xtermjs.org/)?
> 
> What about CodeSandbox or [Monaco Editor Playground](https://microsoft.github.io/monaco-editor/playground.html)?
> 
> And just to clarify, is code-server actually installed on the Android or are you accessing it on the Android remotely?

I'm accessing it on the Android remotely.

i installed code-server on my VPS.

I try to reproduce it using Monaco Editor Playground, but Monaco Editor Playground works fine.

**Comment by jsjoeio** [comment]
Thanks for clarifying! Okay then this sounds specific to code-server. I don't know when I'll be able to get this but I will add it to our "On Deck" milestone.

Anyone else coming to this, please give a thumbs-up on the original description. That way we can see how many people are affected by this.

**Comment by lwd-temp** [comment]
This is just a guess: maybe the browser or the input method is not working properly?
I don't have a physical keyboard and just tried with my Redmi phone. Everything works properly with it's default soft keyboard(MIUI's Sogou Chinese IME) and Chrome downloaded in Play Store.
Hope this will be helpful. There are possibilities that Android may treat soft and physical keyboards differently.

**Comment by code-asher** [comment]
There seem to be a few issues with mobile keyboards but I believe they are working on them upstream.
