### ISSUE TITLE
[RFC]: Remove support for old Kubernetes versions

### ISSUE THREAD

**Issue by jawnsy** [coder/code-server#4859]
## What is your suggestion?

This RFC proposes that code-server drop support for old versions of Kubernetes:

1. The latest **two** minor releases will be fully supported, and failures to install code-server to that version will be considered a high-priority bug (this is currently 1.23 and 1.22)
2. The oldest **third** minor release will be supported on a best-effort basis (this is currently 1.21), and failures to install code-server to that version will be considered a medium-priority bug
3. Older releases (e.g. 1.20) will not be supported, and while pull requests will be considered, the code-server maintainers may choose to reject them

We will have automated tests using kind that cover all three releases (1.23, 1.22, 1.21)

Our [current Helm chart](https://github.com/coder/code-server/blob/main/ci/helm-chart/Chart.yaml) does not check the version of Kubernetes, so we cannot reliably use newer features without adding special checks, such as this:

https://github.com/coder/code-server/blob/102478bdea61bb8374bd1e05e50581a05268ad38/ci/helm-chart/templates/ingress.yaml#L4-L10

## Why do you want this feature?

These kinds of version checks are tedious and trying to support various older Kubernetes versions indefinitely dramatically expands our test matrix. The upstream Kubernetes project itself supports the last three releases (as of writing, that is 1.23, 1.22, 1.21), and attempting to support older releases will hold us back from making use of modern Kubernetes features in our Helm Chart.

## Are there any workarounds to get this functionality today?

Yes, users can produce their own Helm chart and customize everything as they wish, but then they are also responsible for maintaining that chart.

## Are you interested in submitting a PR for this?

Yes - this will comprise of various PRs that increment the Kubernetes requirement encoded in the Helm chart, and add tests using kind to ensure that deployment still works correctly

**Comment by jawnsy** [comment]
@Matthew-Beckett @wrmilling @im-coder-lg @jlandowner Since you submitted changes for our Helm chart in the past, I'd be interested to hear your thoughts on this proposal.

**Comment by Matthew-Beckett** [comment]
I am completely in favor of this and agree that adding complex semver comparisons is ultimately not worth it. 

Though I will say, it might be an idea to push some old chart versions to the chart repo when it's ready for people on "old clusters to use with overridden image versions?

**Comment by im-coder-lg** [comment]
> Since you submitted changes for our Helm chart in the past, I'd be interested to hear your thoughts on this proposal.

I don't remember doing that, but I guess I'll approve. The reason people use the latest versions is because they have bug fixes, new features, etc. I like this idea.

**Comment by wrmilling** [comment]
I believe keeping the chart up to date in terms of relevant k8s feature support and possibly finding some prioritization for #2302 would be helpful overall, definitely. I have the current chart hosted from my own [helm repo](https://github.com/wrmilling/wrmilling-charts/tree/master/charts/code-server), but that's not really a sustainable solution.

**Comment by jlandowner** [comment]
I also agree. 

By the way, be careful to use `kubeVersion`. I do not agree with the idea updating the value in every release to represent support k8s version. it prevents installation to older clusters but means shutout some users and reduces reachability. It is good to keep the oldest version in which all contained k8s resources are available(for example `>= 1.19.0-0`)
