### ISSUE TITLE
[Feat]: Open folder in new tab

### ISSUE THREAD

**Issue by KaKi87** [coder/code-server#4861]
## What is your suggestion?
Add the ability to open a (non-recent) folder in a new tab, e.g. using Ctrl + click like in *Open recent*

## Why do you want this feature?
To be able to keep the current folder open while opening another one.

## Are there any workarounds to get this functionality today?
Open terminal, `cd` into directory, `pwd`, mouse over command output, click "Open folder in new window"

## Are you interested in submitting a PR for this?
No, but thanks in advance to anyone contributing to this request.

**Comment by code-asher** [comment]
While we could maintain a patch for this, it would be much better to do it upstream in https://github.com/microsoft/vscode

**Comment by KaKi87** [comment]
As if there was any realistic chance of getting this implemented there 😅

**Comment by code-asher** [comment]
I think this is quite realistic, being able to open a folder in Codespaces is probably something they would be happy about.

**Comment by KaKi87** [comment]
A PR for a feature of similarly low priority has been submitted 5 years ago, upvoted by 31 people, yet still not merged.

**Comment by code-asher** [comment]
That is frustrating, sorry to hear that.  Is it this one?  https://github.com/microsoft/vscode/pull/77363  I added a vote as well, although it probably will not help.

**Comment by KaKi87** [comment]
Yeah.

So, I'm not interested in more frustration.

**Comment by code-asher** [comment]
I tried this extension: https://open-vsx.org/extension/chrisdias/vscode-opennewinstance

But it did not work.  But, it does show it should be possible for someone to implement this as an extension.
