### ISSUE TITLE
[Bug]: Docker container stopped unexpectedly

### ISSUE THREAD

**Issue by ItzMiracleOwO** [coder/code-server#4865]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Opera
- Local OS: Windows 11 Pro
- Remote OS: DSM 6.2.4
- Remote Architecture: ARM
- `code-server --version`: 4.0.2 5cdfe74686aa73e023f8354a9a6014eb30caa7dd

### Steps to Reproduce

IT CRASH UNEXPECTEDLY

### Expected

I didnt expect it to crash :/

### Actual

Well it crashed

### Logs

Logs before crash
![image](https://user-images.githubusercontent.com/76854136/153805363-ce2717c2-926c-453f-abab-4f3cb63d42d3.png)

### Screenshot/Video

-

### Does this issue happen in VS Code?

- [X] I cannot reproduce this in VS Code.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

-

**Comment by jsjoeio** [comment]
Unfortunately without steps to reproduce, we can't help you with this :( If you can share repro steps or logs, then you can reopen and we can help.

**Comment by ItzMiracleOwO** [comment]
@jsjoeio theres no steps
it crash unexpectedly
i was in the middle of compiling a maven project
`mvn clean package`
and it crash somehow

**Comment by jsjoeio** [comment]
@ItzMiracleOwO argh I wish I could help :( If there are no steps and it's unexpected, then they're not much I can go off. 

It sounds like it could be specific to maven then? I'm not a Java developer, but if you provide steps that lead up to the crash, I can try locally

**Comment by ItzMiracleOwO** [comment]
Hi 
Seems that i found why the server crash
Every time I connect to the server via SMB, the server crashes

**Comment by jsjoeio** [comment]
@ItzMiracleOwO do you mind moving our convo to a Discussion? I don't know what SMB but hopefully we can figure out the issue together

**Comment by ItzMiracleOwO** [comment]
> @ItzMiracleOwO do you mind moving our convo to a Discussion? I don't know what SMB but hopefully we can figure out the issue together

sorry for late reply
Sure yes!!
