### ISSUE TITLE
[Bug]: "Use Insiders Edition" appears in menu and causes code-server to fail

### ISSUE THREAD

**Issue by colemickens** [coder/code-server#4870]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: firefox
- Local OS: nixos
- Remote OS: nixos
- Remote Architecture: nixos systemd service
- `code-server --version`: 4.01

### Steps to Reproduce

1. Use the VSCode gear menu in bottom left
2. Choose "use insiders"
3. Fail

Now code-server doesn't load at all. How do I undo this horrible mistake? :)

Thanks!

### Expected

I should probably be blocked from activating this.

### Actual

I was able to shoot myself in the foot. :(

### Does this issue happen in VS Code?

- [X] I cannot reproduce this in VS Code.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by colemickens** [comment]
Well, I waited a while, came here to file the bug and now when I switch back it seems to have loaded.

Am I right to assume that this isn't the "Dev" build but rather just enables unstable features/ext-apis?

**Comment by jsjoeio** [comment]
@colemickens Very strange! I didn't even realize that was an option. We should definitely disable that. Sorry it caused you some trouble!

> Am I right to assume that this isn't the "Dev" build but rather just enables unstable features/ext-apis?

I would describe it as "Stable" and may enable some ext-apis? But maybe @code-asher has a better description. We may enable some unstable features but I'm not 100% sure.

**Comment by colemickens** [comment]
Sorry, I just realized my last message wasn't very clear - the button I hit said it needed to clear browser cache - I think when I thought it was broken it was just firefox/cache/network slowness. When I filed the Issue and switched back to code-server, it had just finished loading.

Interestingly, now when I try it in a Chrome installed-app window, it just instantly reloads and doesn't seem to have any effect (the "switch to insiders" entry is still present and I can't tell *anything* has changed).

I'm not sure there's a huge need to fix, but disabling it might prevent my silly confusion for others. :)

**Comment by code-asher** [comment]
I could be wrong but I think insiders is just the latest build of VS
Code.  I am not sure what that button is supposed to do; maybe it tries
to install the insiders version?  But this likely would not work with
code-server.

**Comment by code-asher** [comment]
Disabling it seems like the right move unless we start providing our own insider releases.

**Comment by code-asher** [comment]
I checked and this no longer exists.
