### ISSUE TITLE
[Feat]: override github auth login method / callback location

### ISSUE THREAD

**Issue by colemickens** [coder/code-server#4876]
## What is your suggestion?

I access code-server via a VPN. When attempting to login to GitHub, it incorrectly assumes that it can POST back to the code-server URL, which obviously GitHub can't access.

GitHub is fairly standard OAuth, there should be other ways to complete the flow that don't require POSTing directly to code-server. Whether thats device auth, manual code authorization, etc.

## Why do you want this feature?

To make GitHub scenarios workable in private code-server instances.

## Are there any workarounds to get this functionality today?

Possibly? Probably? I'm just not sure what they are.

## Are you interested in submitting a PR for this?

No, and I suspect this is a feature request for the vscode-github extension, but also, something is telling VSCode about the code-server URL, and maybe that could be modified so that the github extension does a different auth mechanism? Not sure.

**Comment by colemickens** [comment]
Oh I do not like this vscode-auth stuff at all. It should really support falling back to Device Auth Flow so that this entire process isn't needed.

**Comment by colemickens** [comment]
Octokit supports it: https://github.com/octokit/authentication-strategies.js#device-authentication

But then again Octokit supports (by default) PATs...

I hope this can be considered or would be merged if someone else authored it.

**Comment by colemickens** [comment]
Related open issue on the extension: https://github.com/microsoft/vscode-pull-request-github/issues/3325

**Comment by colemickens** [comment]
Looks like I'm wrong, not sure if this change has hit code-server yet: https://github.com/microsoft/vscode/pull/139255

**Comment by colemickens** [comment]
Looks like this landed in VS Coce 1.64.0 so it should land here in code-server soon.

**Comment by jsjoeio** [comment]
Nice find!! Yeah, I'm planning to work on https://github.com/coder/code-server/issues/4822 soon so hopefully this just works out the box. Let's wait till I do that and release 4.0.3 then maybe you can help me test?

**Comment by colemickens** [comment]
Sweet, yeah, I'll probably check back in closer to the weekend.

**Comment by code-asher** [comment]
The callback appears to be gone now; instead they ask that you paste a token.
