### ISSUE TITLE
[Feat]: Build with Node 16

### ISSUE THREAD

**Issue by jawnsy** [coder/code-server#4894]
## What is your suggestion?

Upstream VSCode now appears to be building with Node.js version 16. We should consider doing the same when we update our fork to the latest code.

https://github.com/microsoft/vscode/blob/39cc1e1c42b2e53e83b1846c2857ca194848cc1d/.github/workflows/ci.yml#L24-L26

## Why do you want this feature?

Node v14 is now a maintenance LTS release, and will be EOL 2023-04-30. Switching to v16 gives us an additional year of support, since Node v16 LTS has an EOL of 2024-04-30.

## Are there any workarounds to get this functionality today?

Users can build with Node v16 manually, I suppose.

## Are you interested in submitting a PR for this?

Sure! I'm not sure what needs to be updated, though, aside from CI. Do we need to update the fork (https://github.com/coder/vscode/) as well?

**Comment by jsjoeio** [comment]
> Sure! I'm not sure what needs to be updated, though, aside from CI. Do we need to update the fork (https://github.com/coder/vscode/) as well?

Probably! And then I think we need to update the `package.json` in code-server here:

https://github.com/coder/code-server/blob/main/package.json#L121

And update this: https://github.com/coder/code-server/blob/main/.node-version

And then we'll need to update the docs if they mention v14

**Comment by ghalibansari** [comment]
Guys this discussion is being mad by last 4 months and still not resolved,  please update to node 16.😇

**Comment by martadinata666** [comment]
When technically we cant use node16, but the release can run node16, as far i can tell it work pretty well.

**Comment by ghalibansari** [comment]
@jsjoeio @jawnsy  any time line for node 16 support, I use Samsung Dex primarily to code, but due to this is an issue I have to borrow my brother slow laptop to code plz update it, since waiting from eternity. thanks

**Comment by jsjoeio** [comment]
@ghalibansari not sure yet since we have other priorities. You'll either see an update here or see this moved to an upcoming milestone.  

side note: jawnsy is no longer helping out with the project so please don't tag them.

**Comment by ghalibansari** [comment]
@jsjoeio understood, thanks.
this helped me.

`FORCE_NODE_VERSION=16 yarn global add code-server`

**Comment by thx2001r** [comment]
@ghalibansari same here!  If you are using typescript/javascript and seeing errors with code-server 4.2.0 (#5019), try using node 4.1.0 until this is resolved:

`FORCE_NODE_VERSION=16 yarn global add code-server@4.1.0 --ignore-engines`

I'm also using DeX on a S21 with just Termux and this is all it takes to currently get code-server up and running from a fresh Termux install:

`pkg update -y && pkg upgrade -y`

`pkg install -y binutils python nodejs-lts yarn`

`FORCE_NODE_VERSION=16 yarn global add code-server@4.1.0 --ignore-engines`

**Comment by BufuWinner** [comment]
> @jsjoeio understood, thanks.
> this helped me.
> 
> `FORCE_NODE_VERSION=16 yarn global add code-server`
> 

Does it work well for you? In my case it helped with the installation, while breaking extensions, making code-server cool but not so useful... Am I the only one facing this issue?

**Comment by ghalibansari** [comment]
> > @jsjoeio understood, thanks.
> > this helped me.
> > `FORCE_NODE_VERSION=16 yarn global add code-server`
> 
> Does it work well for you? In my case it helped with the installation, while breaking extensions, making code-server cool but not so useful... Am I the only one facing this issue?

yes if face any issue use , `FORCE_NODE_VERSION=16 yarn global add code-server@4.1.0`

**Comment by BufuWinner** [comment]
> yes if you face any issue use, `FORCE_NODE_VERSION=16 yarn global add code-server@4.1.0 --ignore-engines`

The issue persists anyway. I can install code-server but not extensions.
This is the output:
```code-server --install-extension ms-python.python

Installing extensions...
Installing extension 'ms-python.python'...
(node:32224) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
Unable to delete the existing folder '/data/data/com.termux/files/home/.local/share/code-server/extensions/ms-python.python-2021.12.1559732655' while installing the extension 'ms-python.python'. Please delete the folder manually and try again
Failed Installing Extensions: ms-python.python```

I can assure you, there is no folder in the directory whatsoever. Maybe it is not related to the node version, but it seems like it. I've also tried other ways to install extensions, but without success.

**Comment by thx2001r** [comment]
Best way I've found so far is instructions on Coder:

https://coder.com/docs/code-server/latest/termux

Make sure to install Node v14.  I am using code-server 4.1.0 as there are issues for me with javascript/typescript and v4.2.0.  All extensions working perfectly for me:

https://youtu.be/Stu8eSALLw8

**Comment by jsjoeio** [comment]
This was done in https://github.com/coder/code-server/milestone/39
