### ISSUE TITLE
[Bug]: Terminal doesn't show after getting hidden. Only happened on firefox. 

### ISSUE THREAD

**Issue by yokowasis** [coder/code-server#4895]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Firefox
- Local OS: 10
- Remote OS: Cloudlinux
- Remote Architecture: x64
- `code-server --version`: 4.0.1 735c6da829535969ff7193c79379299e4a1cb9bc

### Steps to Reproduce

1. open code-server
2. open terminal using ``ctrl+` ``
3. press `` ctrl+` `` multiple times

### Expected

The terminal should be shown and hidden, back and forth.

### Actual

The terminal goes showing, and then hidden, and then never shown again. 

This happened only on firefox, chrome works fine. 

### Does this issue happen in VS Code?

- [X] I cannot reproduce this in VS Code.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by jsjoeio** [comment]
Do you know which command that corresponds to? I must have overridden it.

<img width="1904" alt="image" src="https://user-images.githubusercontent.com/3806031/155218547-2ef82448-b6e6-4b45-addd-cf2e8f315229.png">

I wonder what could be happening in Firefox 🤔 I've had some VS Code keybindings conflict with global Firefox shortcuts (like the one to open the Command Palette).

Does this bug still happen if you change the keybinding to something else?

**Comment by yokowasis** [comment]
Command : View: Toggle Terminal
Keybinding : ctrl + `
When : terminal.active
Source : default

**Comment by yokowasis** [comment]
> I wonder what could be happening in Firefox 🤔 I've had some VS Code keybindings conflict with global Firefox shortcuts (like the one to open the Command Palette).
> 
> Does this bug still happen if you change the keybinding to something else?

This have nothing to do with keybinding, the same bug happened when using the command from View > Terminal

**Comment by jsjoeio** [comment]
Can you reproduce this in VS Code? For me, it does. 

When I hit the same "View: Toggle Terminal" multiple times, nothing happens.

## Video

https://user-images.githubusercontent.com/3806031/157730418-12d964b7-4932-486a-ba7f-b7a727d7fd44.mov

**Comment by yokowasis** [comment]
> Can you reproduce this in VS Code? For me, it does.
> 
> When I hit the same "View: Toggle Terminal" multiple times, nothing happens.
> 
> ## Video
>  Screen.Recording.2022-03-10.at.11.27.25.AM.mov

Exactly, the right behaviour would be the terminal would be toggled between shown and hidden. sometimes it would be hidden and wouldn't be shown. sometimes it would be shown and woudn't be hidden.

**Comment by jsjoeio** [comment]
> Exactly, the right behaviour would be the terminal would be toggled between shown and hidden. sometimes it would be hidden and wouldn't be shown. sometimes it would be shown and woudn't be hidden.

Yup! I understand that. This video is **VS Code** and the behavior is the exact same there as it is here. 

> In desktop vscode and chrome, it works as expected. each time I run the command, the terminal would be toggled.

Can you post a video?

**Comment by yokowasis** [comment]
Desktop VSCode Behaviour
https://user-images.githubusercontent.com/1374064/158011604-124e3952-f544-44f3-8f30-ca5449960df1.mp4

code-server behaviour (only on firefox)
https://user-images.githubusercontent.com/1374064/158011720-518adc3a-52d7-4776-b74c-dbacb87bc092.mp4

**Comment by jsjoeio** [comment]
I was able to reproduce it locally on macOS + Firefox + code-server 4.10.0

**Comment by code-asher** [comment]
Reproduced in Codespaces.
