### ISSUE TITLE
[Bug]: "Extension 'actboy168.tasks' not found." with codercom/code-server:4.0.2

### ISSUE THREAD

**Issue by SunsetMkt** [coder/code-server#4899]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Microsoft Edge
- Local OS: Windows
- Remote OS: Railway.app 's Container/Docker
- Remote Architecture: amd64
- `code-server --version`: 4.0.2

### Steps to Reproduce

1.  Deploy code-server with coder/deploy-code-server in railway.app & set RCLONE_DATA
2.  Log shows "Extension 'actboy168.tasks' not found." while "Applying VS Code tasks for rclone"
3. rclone tasks bar showed in 3.x.x versions won't show now.

### Expected

No "Extension 'actboy168.tasks' not found." & rclone tasks bar shows

### Actual

Log shows "Extension 'actboy168.tasks' not found." while "Applying VS Code tasks for rclone"
rclone tasks bar showed in 3.x.x versions won't show now.

### Logs

```
[deploy-code-server] Copying rclone config...
[deploy-code-server] Applying VS Code tasks for rclone
Installing extensions...
Extension 'actboy168.tasks' not found.
Make sure you use the full extension ID, including the publisher, e.g.: ms-dotnettools.csharp
Failed Installing Extensions: actboy168.tasks
(The logs following contains my private file names.)
```

### Does this issue happen in VS Code?

- [X] I cannot reproduce this in VS Code.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

"actboy168.tasks"(https://marketplace.visualstudio.com/items?itemName=actboy168.tasks) can't be found in the default marketplace(open-vsx.org) in 4.0.2.
But it's available on GitHub (https://github.com/actboy168/vscode-tasks) (MIT License).

Maybe we can make the extension package self-hosted?

**Comment by jsjoeio** [comment]
@bpmct do you mind taking a look at this?

**Comment by dead8309** [comment]
I'm on code-server v4.3.0 running on heroku , I was having that same issue with 
`Extension 'actboy168.tasks' not found.`
**The way you can fix it is by downloading [actboy168.tasks-0.9.0.vsix](https://marketplace.visualstudio.com/items/actboy168.tasks/license) and installing it manually.**

### Download the extension and put that file in deploy-container/

### edit Dockerfile and add this line
`COPY deploy-container/actboy168.tasks-0.9.0.vsix .local/share/code-server/User/actboy168.tasks-0.9.0.vsix`

### edit entrypoint.sh file in /deploy-container
Replace
`code-server --install-extension actboy168.tasks&`
### By
`code-server --install-extension /home/coder/.local/share/code-server/User/actboy168.tasks-0.9.0.vsix&`

### Done! it should work now.
![Screenshot_20220425-014334_Chrome](https://user-images.githubusercontent.com/68665948/164994835-1df7f2ef-a615-4b1f-8701-f0a4f2fac68e.png)
![Screenshot_20220425-014257_Chrome](https://user-images.githubusercontent.com/68665948/164994837-23dc8869-db74-4da9-8d2c-6026b0ab8360.png)

**Comment by code-asher** [comment]
Just writing to confirm that you can install the extension manually, or someone will need to ask the extension author to submit their extension to Open VSX.
