### ISSUE TITLE
[Bug]: VS Code Terminal is blank until I change the view to "Show Tabs"

### ISSUE THREAD

**Issue by BluDood** [coder/code-server#4912]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Safari
- Local OS: iPadOS 15.1
- Remote OS: Ubuntu
- Remote Architecture: amd64
- `code-server --version`: 3.10.2

### Steps to Reproduce

1. Open code-server on Safari
2. Press CMD+J to open terminal

### Expected

The terminal window should show its output

### Actual

The output is completely invisible, but is being written to the screen (the cursor moves as I type)

### Logs

Nothing relevant

### Screenshot/Video

![IMG_0162](https://user-images.githubusercontent.com/70075053/155747544-4fcb0d2c-582f-444c-9c88-271a402155f3.jpeg)

### Does this issue happen in VS Code?

- [X] I cannot reproduce this in VS Code.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by BluDood** [comment]
I'm using deploy-code-server with heroku, that's the latest version. Maybe there is a way to update it? I'll look into it, it is a Docker image after all

**Comment by BluDood** [comment]
It works now! Sorry for not trying to update first.

**Comment by jsjoeio** [comment]
@BluDood Hooray! Thanks for checking so quickly. Glad it works now!
