### ISSUE TITLE
[Testing]: write e2e test for GitHub auth patch

### ISSUE THREAD

**Issue by jsjoeio** [coder/code-server#4914]
May need to talk to @code-asher about this but I'd like to write an e2e in test so https://github.com/coder/code-server/issues/4795 doesn't happen again.

## Related
- https://github.com/coder/vscode/pull/47

**Comment by jsjoeio** [comment]
## Notes

e2e tests shouldn't rely on network connections since we want our tests to be deterministic and not fail due to network errors. Therefore my thinking for an e2e test for this is to do something like this:
1. launch code-server
2. Command Palette > Publish to GitHub
3. Select Allow
4. Assert URL opened includes `auth.code-server.dev``

@code-asher What are your thoughts? Both on this e2e idea and my hypothetical approach.

Or is there a way I could unit test this instead?

My end goal is to prevent regressions and less about how we get there.

**Comment by code-asher** [comment]
Hmm unit test seems tricky to me, unless perhaps we can add the test on
the Code side (I assume they have unit tests).

The proposed steps I think are sufficient to prove that we have properly
patched the relay server.  I think we may want to also assert that the
right redirect URL is in a query param.
