### ISSUE TITLE
[Bug]: code-server is not working on node version 17.6

### ISSUE THREAD

**Issue by sungreong** [coder/code-server#4936]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

tab : galaxy tab8
npm : 8.5.1
node: 17.6.0

### Steps to Reproduce

1. pkg update -y
2. pkg install -y python nodejs yarn git
3. yarn global add code-server

### Expected

yarm global add code-server

### Actual

yarm global add code-server

ERROR: code-server currently requires node v14

### Does this issue happen in VS Code?

- [X] I cannot reproduce this in VS Code.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by Adrean-Danilo** [comment]
To install code-server in a terminal from android you can follow these steps...
https://coder.com/docs/code-server/latest/termux

**Comment by jsjoeio** [comment]
This is expected. We don't support Node versions higher than 14. Please follow https://github.com/coder/code-server/issues/4894 to know when we add support for 16.
