### ISSUE TITLE
[Bug]: There is no way to close the post-auth window for github on PWA

### ISSUE THREAD

**Issue by polographer** [coder/code-server#4956]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: iOS PWA (Safari)
- Local OS: iOS 15.3.1
- Remote OS: Raspbian 
- Remote Architecture: Linux penpen 5.10.92-v7+ #1514 SMP Mon Jan 17 17:36:39 GMT 2022 armv7l GNU/Linux
- `code-server --version`: 4.1.0 9e620e90f53fb91338a2ba1aaa2e556d42ae52d5 with Code 1.63.0

### Steps to Reproduce

1. Open code server on a PWA / iPad
2. Try to authenticate with a GitHub extension like "GitHub pull requests"
3. after accepting you will not be able to close the window

### Expected

the window should close itself or have a close button

### Actual

you need to kill the PWA, I have not find a way to close the window (entering random keys on the keyboard)

### Screenshot/Video

https://share.icloud.com/photos/05aiA_siif4Py9rbnQ4bU5cOg

### Does this issue happen in VS Code?

- [X] I cannot reproduce this in VS Code.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

I have the PWD configured to be server by directly from code-server (I'm not using nginx)

**Comment by jsjoeio** [comment]
Will it close if you hit `cmd + w`? 

I also don't know if we have control over this page 🤔

Does this reproduce with vscode.dev?

**Comment by polographer** [comment]
cmd+w = nope, it wont work
vscode.dev = nope, the widnow auto-closes

https://share.icloud.com/photos/0c6s-B2-AVPmeb5p5es0HrafA

**Comment by jsjoeio** [comment]
Hooray! Thanks for the video too :) Definitely a code-server bug. cc @code-asher you might find this interesting.

Guessing there's some callback logic that closes the window if on mobile like `isiPad` or something (or we could add that)

**Comment by code-asher** [comment]
Interesting, almost seems like they are running a different version of that callback page than the one in their source code.  For example theirs has "Loading..." and I am not seeing that anywhere in the HTML.

 We can add some code around here to close the page I think https://github.com/coder/vscode/blob/a13f6e1434ad6ab820eef0ecca5b923b3e275667/src/vs/code/browser/workbench/callback.html#L64

**Comment by code-asher** [comment]
This appears to be gone now; instead they ask you to paste a token.
