### ISSUE TITLE
[Bug]: Jupyter notebook blank page while accessing via nginx using a domain

### ISSUE THREAD

**Issue by Abdullah1224** [coder/code-server#4976]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Safari
- Local OS: macOS
- Remote OS: CentOS
- Remote Architecture: 64-bit
- `code-server --version`: 4.1.0

### Steps to Reproduce

1. Install code-server
2. Setup nginx 
3. Access code-server via nginx using a domain

### Expected

when I deploy code-server on localhost or access code-server behind a proxy everything should work.

### Actual

I am trying to run code-server to develop some jupyter notebooks, when I deploy code-server on localhost everything works as expected, however when I access code-server behind a proxy I get blank screen when I open jupyter notebook files.

### Screenshot/Video

this is the proxy setting:
![image](https://user-images.githubusercontent.com/46467560/157633598-ccf774b7-add9-40a9-acd0-1116b9cf3f8c.png)

this is when deploying on localhost:
![image](https://user-images.githubusercontent.com/46467560/157633700-e4d768b7-3224-400a-bd22-3c3106d6c68b.png)

this is when accessing it through nginx:
![image](https://user-images.githubusercontent.com/46467560/157633762-b4dda842-cc4d-40f8-8cad-3552c9584b84.png)

### Does this issue happen in VS Code?

- [X] I cannot reproduce this in VS Code.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by jsjoeio** [comment]
> this is the proxy setting:

can you post this as text?

> I am using HTTPS.

You checked this box but it says "Not Secure" in your last screenshot 🤔

Can you please post the browser logs?

**Comment by Abdullah1224** [comment]
server {
	listen		443 ssl http2;
	listen		[::]:443 ssl http2;
	server_name	Node-7;
       root		/usr/share/nginx/html;
	ssl_certificate /etc/ssl/certs/nginx-selfsigned.crt;
	ssl_certificate_key /etc/ssl/private/nginx-selfsigned.key;
	ssl_dhparam /etc/ssl/certs/dhparam.pem;
	ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
	ssl_prefer_server_ciphers on;
	ssl_ecdh_curve secp384r1;
	ssl_session_tickets off;
	ssl_stapling on;
	ssl_stapling_verify on;
	add_header X-Frame-Options DENY;
	add_header X-Content-Type-Options nosniff;
	
	include /etc/nginx/default.d/*.conf;
	location /vscode/ {
  	  rewrite /vscode/(,*)/$1 break;
	  proxy_pass http://localhost:8080/;
	  proxy_redirect off;
	  proxy_set_header Host $host;
	  proxy_set_header Origin "";
	  proxy_set_header Upgrade $http_upgrade;
	  proxy_set_header Connection upgrade;
	  proxy_set_header Accept-Encoding gzip;

	}
	error_page 404 /404.html;
		location = /40x.html {
		}

	error_page 500 502 503 504 /50x.html;
		location = /50x.html{
		}
}

**Comment by Abdullah1224** [comment]
Web Browser: Safari
Web Browser: Google Chrome*
I apologize for the mistake

![image](https://user-images.githubusercontent.com/46467560/157938410-e932fb55-ae9b-42e4-a300-26d3f99b4d8b.png)

**Comment by jsjoeio** [comment]
No worries!

Can you please post the browser logs?

**Comment by Abdullah1224** [comment]
![image](https://user-images.githubusercontent.com/46467560/157950180-4b90ec4d-5284-473e-903d-fd84ea857666.png)

**Comment by jsjoeio** [comment]
@Abdullah1224 it looks like it might have been cut off. Is there anyway you can copy all of it as text and post it?

**Comment by Abdullah1224** [comment]
ERR Error while creating IndexedDB DOMException: The requested version (2) is less than the existing version (3).

INFO Using in-memory user data provider

ERR [Service Worker] registration DOMException: Failed to register a ServiceWorker for scope ('https://node-7/vscode/') with script ('https://node-7/vscode/service-worker.js'): An SSL certificate error occurred when fetching the script.

Refused to display 'https://node-7/' in a frame because it set 'X-Frame-Options' to 'deny'.

crbug/1173575, non-JS module files deprecated.
(anonymous) @ (index):6774

Extension Host] Git installation not found.
I @ console.ts:137

Refused to display 'https://node-7/' in a frame because it set 'X-Frame-Options' to 'deny'.

crbug/1173575, non-JS module files deprecated.
(anonymous) @ (index):6774

ERR [Extension Host] (node:22112) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

console.ts:137 [Extension Host] (node:22112) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
I @ console.ts:137


Refused to display 'https://node-7/' in a frame because it set 'X-Frame-Options' to 'deny'.

crbug/1173575, non-JS module files deprecated.
(anonymous) @ (index):6774


The Web Worker Extension Host did not start in 60s, that might be a problem.
(anonymous) @ webWorkerExtensionHost.ts:184

**Comment by jsjoeio** [comment]
> Refused to display 'https://node-7/' in a frame because it set 'X-Frame-Options' to 'deny'.

Guessing this is the issue. That does not look like a valid URL to me? More info on [X-Frame-Options](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options).

Any ideas on how we can help them debug this @code-asher ?

**Comment by benz0li** [comment]
@Abdullah1224 Try setting `X-Frame-Options SAMEORIGIN` instead of `X-Frame-Options DENY` in your `nginx.conf`.

**Comment by aghasemi** [comment]
Hi. I can confirm that version 4.2.0 can correctly create a Jupyter notebook.

**Comment by jsjoeio** [comment]
@aghasemi can't tell you how much we appreciate you following up 🙌🏼 That saves us a ton of time. Cheers!
