### ISSUE TITLE
[Bug]: Unable to connect code-server

### ISSUE THREAD

**Issue by inoshell** [coder/code-server#4980]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Edge
- Local OS: Windows 11
- Remote OS: Ubuntu 18.04
- Remote Architecture: amd64
- `code-server --version`: 4.1.0 9e620e90f53fb91338a2ba1aaa2e556d42ae52d5 with Code 1.63.0

### Steps to Reproduce

1. Install code-server
2. Open code-server and open port 80 port with ufw add 80
3. Configure config file
4. Try to connect

### Expected

I should connect and start to use

### Actual

I've always gotten "ERR_CONNECTION_REFUSED".

### Logs

root@ubuntu:~# code-server --verbose
[2022-03-10T18:09:57.699Z] trace child:1605 got message {"message":{"type":"handshake","args":{"bind-addr":"127.0.0.1:80","auth":"password","password":"I**DELETEDPASSWORD**","config":"/root/.config/code-server/config.yaml","verbose":true,"user-data-dir":"/root/.local/share/code-server","extensions-dir":"/root/.local/share/code-server/extensions","log":"trace","host":"127.0.0.1","port":80,"proxy-domain":[],"_":[],"usingEnvPassword":false,"usingEnvHashedPassword":false}}}
[2022-03-10T18:09:57.706Z] info  code-server 4.1.0 9e620e90f53fb91338a2ba1aaa2e556d42ae52d5
[2022-03-10T18:09:57.706Z] info  Using user-data-dir ~/.local/share/code-server
[2022-03-10T18:09:57.707Z] trace Using extensions-dir ~/.local/share/code-server/extensions
[2022-03-10T18:09:57.755Z] info  Using config file ~/.config/code-server/config.yaml
[2022-03-10T18:09:57.756Z] info  HTTP server listening on http://127.0.0.1/
[2022-03-10T18:09:57.756Z] info    - Authentication is enabled
[2022-03-10T18:09:57.756Z] info      - Using password from ~/.config/code-server/config.yaml
[2022-03-10T18:09:57.756Z] info    - Not serving HTTPS

### Does this issue happen in VS Code?

- [X] I cannot reproduce this in VS Code.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

I had this problem with my old service provider too.
I'm not using HTTPS btw.

**Comment by jsjoeio** [comment]
> I've always gotten "ERR_CONNECTION_REFUSED".

Is this because you're using port 80? Is that a restricted port or something? 

I'm not sure how to help with this. Pinging @code-asher

**Comment by code-asher** [comment]
Could you describe how you are installing and accessing code-server?  Docker, remote server, reverse proxy with your own domain, etc?

**Comment by inoaa79** [comment]
> > I've always gotten "ERR_CONNECTION_REFUSED".
> 
> Is this because you're using port 80? Is that a restricted port or something?
> 
> I'm not sure how to help with this. Pinging @code-asher
Here is the video about 80 port:  https://www.youtube.com/watch?v=yskPxZ02NP8

> Could you describe how you are installing and accessing code-server? Docker, remote server, reverse proxy with your own domain, etc?

I'm trying to access my code-server with my virtual private server. 
Also, I tried to connect with the tor network. Nothing changed.

**Comment by inoaa79** [comment]
> Could you describe how you are installing and accessing code-server? Docker, remote server, reverse proxy with your own domain, etc?

I'm gonna make a video about how did I install code-server.

**Comment by inoaa79** [comment]
Here is it : https://www.youtube.com/watch?v=F9OhgO6CiLI

**Comment by jsjoeio** [comment]
Hmm...seems like the port isn't being forwarded?

**Comment by inoaa79** [comment]
> Hmm...seems like the port isn't being forwarded? What happens if you forward it with localtunnel or ngrok?

It works with ngrok. I'm gonna try with VSCode tunnel.

**Comment by inoaa79** [comment]
It also works with VSCode tunnel. I need to talk with my ISP I think. I'll reply if the source of the problem is ISP.

**Comment by inoaa79** [comment]
There is something on my mind. Why does the code-server not work on any port while the application I opened with Node.JS and express is running?

**Comment by jsjoeio** [comment]
> There is something on my mind. Why does the code-server not work on any port _while the application I opened with Node.JS and express is running_?

I'm not sure I understand the last part of the question. 

code-server does support a `--port` flag or `PORT` environment variable, so theoretically you could use any port. I think machines have limitations for which ports you can run on (@code-asher might be able to elaborate).

**Comment by code-asher** [comment]
Thank you for the video!

If you are accessing the IP directly you will need to listen on 0.0.0.0 since 127.0.0.1/localhost is accessible only from inside the machine.

```
code-server --host 0.0.0.0
```

Alternatively you could set up a reverse proxy that proxies to port 8080.

**Comment by code-asher** [comment]
Oh wait we do have instructions for directly exposing under the self-signed section, it just uses the config instead of command line options.  We do not have a section for directly exposing without TLS but I am not sure we want to recommend that.
