### ISSUE TITLE
[Bug]: mouse clicks ignored in several regions, not least in status bar

### ISSUE THREAD

**Issue by thediveo** [coder/code-server#4985]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome 99.0.4844.58
- Local OS: Android 12 on Samsung Galaxy Tab S7+
- Remote OS: Linux Ubuntu 21.10
- Remote Architecture: ARM 64bit, Raspberry Pi 4B/8G
- `code-server --version`: 4.1.0 9e620e90f53fb91338a2ba1aaa2e556d42ae52d5 with Code 1.63.0

### Steps to Reproduce

1. open code-server in Chrome browser on Android. 
2. if the status bar is not shown, show it.
3. open some arbitrary workspace with a git repository.
4. either:
   a. hover the mouse cursor over the current git branch name in the status bar and wait for the pop-up to appear, then click on the branch name.
   b. or finger-tap the git branch name in the status bar.
   c. mouse click or finger tap any other status bar element.

### Expected

a popup with a selector for git branch names should appear.

### Actual

nothing; the status bar does not react to any finger taps or mouse clicks. 

### Does this issue happen in VS Code?

- [X] I cannot reproduce this in VS Code.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

NO, I cannot use HTTPS on the installed vscode-server which I access via port forwarding through an SSH session. As the mouse and finger taps in other parts of the UI correctly register but this beta(!) bug report form enforces the above tick box I don't see from the explanation for the tick box how this could be relevant or alternatively, from the documentation, why this is needed for the SSH forwarding case?

**Comment by TheDiveO** [comment]
sine touch also doesn't work at all in the status bar, maybe that's related to the issue seen on iOS browsers too, and might have been fixed very recently? https://github.com/microsoft/vscode/issues/125686#issuecomment-1047133404

**Comment by jsjoeio** [comment]
> NO, I cannot use HTTPS on the installed vscode-server which I access via port forwarding through an SSH session.

Most of the issues we get are due to folks serving code-server over HTTP so we added this to prevent those types of issues.

Thanks for all the details! I'm not sure when we'll be able to look into this but if it is an upstream issue like you linked then we may have to wait until it's fixed there.

**Comment by code-asher** [comment]
We should try to reproduce in Codespaces and r eport upstream, I think it is unlikely to be in code-server.  We can reopen if that is not the case.
