### ISSUE TITLE
[Bug]: code-server 4.1.0 change github auth URL, breaking github copilot support. 

### ISSUE THREAD

**Issue by yokowasis** [coder/code-server#4998]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Firefox
- Local OS: Windows
- Remote OS: Ubuntu
- Remote Architecture: amd64
- `code-server --version`: 4.1.0

### Steps to Reproduce

1. open code server
2. install copilot
3. auth with github

### Expected

https://user-images.githubusercontent.com/1374064/159104514-87a2b51e-3096-4838-a393-f345d4310b1f.mp4

This is the video of code-server v4.0.2

Old auth url works fine by extracting the state, and put it into 
```
https://vscode-auth.github.com/authorize/?callbackUri=vscode://vscode.github-authentication/did-authenticate&scope=repo&state=${state}&responseType=code
```

as stated in #4363 

### Actual

New version of auth page comes up, github copilot can't find token, assuming I don't have access to github copilot. 

### Screenshot/Video

https://user-images.githubusercontent.com/1374064/159104447-e7666ae7-24b3-4069-9912-1e81843dcd1d.mp4

### Does this issue happen in VS Code?

- [X] I cannot reproduce this in VS Code.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

It looks like new version contain new url for authing with github. I would prefer to use old auth url (4.0.2) since it works fine with github copilot and others.

**Comment by jsjoeio** [comment]
I think due to licensing reasons, Copilot cannot be used with code-server. I can't find it on [Open VSX](https://open-vsx.org/?search=copilot&category=&sortBy=relevance&sortOrder=desc).

Is there another extension that I can use to reproduce this?

**Comment by yokowasis** [comment]
> I think due to licensing reasons, Copilot cannot be used with code-server. I can't find it on [Open VSX](https://open-vsx.org/?search=copilot&category=&sortBy=relevance&sortOrder=desc).
> 
> Is there another extension that I can use to reproduce this?

Actually it can. And a lot of people including me can make it work, by installing the extension manually (on code-server v4.0.2). You can always download copilot from the microsoft marketplace and install it manually. 

Can't we make an option for code-server to use old auth url instead of the new one ?

**Comment by yokowasis** [comment]
code-server 4.2.0 use a new kind of auth (8 alphanumeric). copilot can auth fine, with the new code-server 4.2.0.
