### ISSUE TITLE
[Bug]: Unable to install extension on raspberry pi

### ISSUE THREAD

**Issue by mrfoxie** [coder/code-server#5002]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Brave
- Local OS: Windows 11
- Remote OS: Raspberry Pi 4 Debian 11
- Remote Architecture: aarch64
- `code-server --version`: `4.1.0 9e620e90f53fb91338a2ba1aaa2e556d42ae52d5 with Code 1.63.0`

### Steps to Reproduce

1. opened coder-server in brave browser in windows 11
2. open the extension and search for python(or any other extension)
3. click on install
4. Error occurred

### Expected

When I try to install any kind of extension or theme it gives me an error telling me to install it manually 

### Actual

Python(or any extension) should get installed when clicked on installed

### Logs

While installing from extensions
```
[2022-03-20 15:48:25.772] [window] [error] ["Error: getaddrinfo ENOTFOUND open-vsx.org","    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:26)"]
[2022-03-20 15:48:25.788] [window] [error] getaddrinfo ENOTFOUND open-vsx.org: Error: getaddrinfo ENOTFOUND open-vsx.org
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:26)
```
While installing from local extensions
```
[2022-03-20 15:57:21.532] [window] [error] Unable to install extension 'ms-python.python' as it is not compatible with VS Code '1.63.0'.: Error: Unable to install extension 'ms-python.python' as it is not compatible with VS Code '1.63.0'.
    at K.install (/usr/lib/code-server/vendor/modules/code-oss-dev/out/vs/server/remoteExtensionHostAgent.js:150:149607)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

### Screenshot/Video

![brave_D5kNBXVXva](https://user-images.githubusercontent.com/25217451/159157942-46df33ba-ee3f-456f-8a08-924c69257f4a.png)

### Does this issue happen in VS Code?

- [X] I cannot reproduce this in VS Code.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

I'm not using HTTPS while accessing code-server

**Comment by mrfoxie** [comment]
Also, forget to mention to either remove or permanently hide the account icon from the code-server because it's always loading. if the developers are working then, I would like to suggest hiding the icon till it's been completed or adding a beta version for bug testing🤷‍♂️🤷‍♂️👍👍

**Comment by bestpredicts** [comment]
same probleam

**Comment by jsjoeio** [comment]
Are you using a VPN that's blocking open-vsx.org by chance?

> I'm not using HTTPS while accessing code-server

I don't think you can download extensions without using HTTPS or localhost 🤔

**Comment by mrfoxie** [comment]
it was working fine first but suddenly after new update it wasn't working and I'm not using any kind of VPN

**Comment by jsjoeio** [comment]
Does this still happen on 4.2.0?

**Comment by mrfoxie** [comment]
> Does this still happen on 4.2.0?

nope now it's working perfectly fine in 4.2.0 👍🏻

**Comment by jsjoeio** [comment]
Hooray! Thanks for confirming so quickly

**Comment by mrfoxie** [comment]
> Hooray! Thanks for confirming so quickly

I'm happy that extensions are working properly but you know pwa it's still not working and also account so still I'm waiting for that to be fixed in the new build

**Comment by jsjoeio** [comment]
> you know pwa it's still not working

@mrfoxie really? It should be. I'm running 4.2.0 on macOS via Homebrew and it works for me:

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/3806031/160499253-a68d3b07-3b7d-4398-a5f8-e4e3f2ec6e8d.png">

Any ideas on what might be wrong?

**Comment by mrfoxie** [comment]
> > you know pwa it's still not working
> 
> @mrfoxie really? It should be. I'm running 4.2.0 on macOS via Homebrew and it works for me:
> 
> <img alt="image" width="1792" src="https://user-images.githubusercontent.com/3806031/160499253-a68d3b07-3b7d-4398-a5f8-e4e3f2ec6e8d.png">
> 
> Any ideas on what might be wrong?

let me uninstall and reinstall it again
