### ISSUE TITLE
[Bug]: Cannot install PWA using Samsung Internet

### ISSUE THREAD

**Issue by Daniele122898** [coder/code-server#5005]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Samsung Internet
- Local OS: Android 12 with Samsung UI
- Remote OS: ubuntu 20.04 LTS
- Remote Architecture: x86-64bit
- `code-server --version`:  4.1.0 9e620e90f53fb91338a2ba1aaa2e556d42ae52d5 with Code 1.63.0

### Steps to Reproduce

1. Open Code server in Samsung internet 
2. Try to install PWA

### Expected

It should install the PWA. It works in Google Chrome but does not work in Samsung Internet.

### Actual

 It fails to install PWA with notification from Samsung internet

### Does this issue happen in VS Code?

- [X] I cannot reproduce this in VS Code.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

The reason why this is important is that samsung internet is the only browser on android that supports right click. All other android browsers do not support it, including google chrome. So when i install code-server as a pwa using chrome, i cannot right click anything unless i long press which then often selects text instead of right clicking which renders the pwa useless. 

It's important to mention that code-server runns perfectly in the samsung browser but i just cant install it as PWA which kinda limits the keyboard shortcuts which also makes it a little annoying to use. 
I've gotten the Samsung tab S8 Ultra to use as my laptop replacement and having code-server as a PWA would greatly help.

**Comment by jsjoeio** [comment]
Ah okay. I don't have a Samsung. Do you know if I can test/reproduce this on a mac?

**Comment by Daniele122898** [comment]
I think it should work with any android device since you can download the browser in the play store (its called "Samsung Internet Browser"). So you could emulate it maybe using android studio or whatever alternative the mac has. I'm unsure how distribution works on the play store so i have no idea if a tablet downloads a different apk but i assume not.

**Comment by thx2001r** [comment]
@Daniele122898 and @jsjoeio I was not able to reproduce on my Samsung S21.  [See video](https://youtu.be/6Moflj7dGIU)

@Daniele122898 was your home screen layout locked?  That would give a warning in Samsung Internet.

I am also running:

- code-server v4.1.0 with Code 1.63.0
- On Debian v11.3 aarch64 on Termux
- Samsung Internet v 16.2.5.4
- Android v12
- Android security patch level April 1, 2022
- Google Play system update March 1, 2022
- One UI v4.1

**Comment by Daniele122898** [comment]
@thx2001r I don't think its locked since i was able to install other PWAs. It also gave no warning just "failed to install code-server".

Also im not running my instance locally but on my home server if that changes anything im unsure. But it works in chrome so i assume that shouldn't be an issue.

Other PWAs work on samsung internet its the only one i cannot get to work. Are there any logs somewhere?

**Comment by thx2001r** [comment]
@Daniele122898 I don't know how you can get logs out of a mobile browser but.  Since PWA is a web technology it may be possible to observe the issue in the console of DevTools of a computer connected to your mobile device

**Comment by Daniele122898** [comment]
I've updated code-server to 4.3.0 now as it released recently and it now allows to be installed on samsung browser. I have no idea who or what fixed it but it works now.

**Comment by jsjoeio** [comment]
>  have no idea who or what fixed it but it works now.

Very strange...Maybe something upstream? Best kind of fix though! Thanks for coming back and closing the issue!

**Comment by Matthommes** [comment]
I have very similar issue. I'm trying to install a PWA I created. It works on chrome but not on Samsung internet browser. Am I doing something wrong?

**Comment by code-asher** [comment]
Do other PWAs install with the Samsung browser?  If so maybe there is something we need to add to the manifest...not sure what it could be though.
