### ISSUE TITLE
[Bug]: Activating extension 'vscode.typescript-language-features' failed: Could not find bundled tsserver.js

### ISSUE THREAD

**Issue by encanto-oss** [coder/code-server#5019]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: google chrome
- Local OS: ubuntu 
- Remote OS: ubuntu
- Remote Architecture: amd64
- `code-server --version`: 1.64.2

### Steps to Reproduce

1. yo code to create a new vscode plugin
2. Start debug the extension
3. vscode in new window shows
```
Activating extension 'vscode.typescript-language-features' failed: Could not find bundled tsserver.js
```
```
VS Code's tsserver was deleted by another application such as a misbehaving virus detection tool. Please reinstall VS Code
Source: Typescript and Javascript Language Features (Extension)
```

### Expected

should not happen

### Actual

3. vscode in new window shows
```
Activating extension 'vscode.typescript-language-features' failed: Could not find bundled tsserver.js
```
```
VS Code's tsserver was deleted by another application such as a misbehaving virus detection tool. Please reinstall VS Code
Source: Typescript and Javascript Language Features (Extension)
```

### Does this issue happen in VS Code?

- [X] I cannot reproduce this in VS Code.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

I had tried to go into /usr/lib/code-server and run yarn, but no luck, where is tsserver.js?

**Comment by WuXeR** [comment]
I have the same issue

**Comment by jsjoeio** [comment]
I cannot reproduce on macOS

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/3806031/159767685-7c0460ba-b546-4c39-b6de-91490d67e0ca.png">

> where is tsserver.js

Could be this file 🤔 but not 100% sure:
https://github.com/microsoft/vscode/blob/main/extensions/typescript-language-features/src/tsServer/server.ts

> VS Code's tsserver was deleted by another application such as a misbehaving virus detection tool. Please reinstall VS Code
Source: Typescript and Javascript Language Features (Extension)

Do you have a firewall or virus tool installed? And did you try reinstalling the extension like it suggests?

**Comment by jsjoeio** [comment]
More info here maybe: https://github.com/Microsoft/vscode/issues/72721

**Comment by gghub77** [comment]
This was missing /usr/lib/code-server/lib/vscode/extensions/node_modules/typescript/lib , it affected vscode.typescript-language-features looking for tsserver.js and html-language-features looking for typescript.js . I took the typescript dir from another install and no more errors

**Comment by jsjoeio** [comment]
@code-asher does this ring a bell? It seems very odd that we would be missing one file.

Otherwise I can look into it. I couldn't reproduce though.

**Comment by matt-teix** [comment]
Also have this issue after updating this morning

**Comment by Inky1003** [comment]
Also had the issue updating It now. 4.1.0 seems to work fine. Using userLAnd, Ubuntu and install.sh

**Comment by gghub77** [comment]
> node_modules/typescript

The whole typescript dir wasn't there for me under node_modules

**Comment by jsjoeio** [comment]
Wow...I wonder if it's Linux only then 🤔

For anyone else having this issue, please give a 👍🏼 to the first comment so we can gauge how many people are affected by this.

**Comment by WuXeR** [comment]
I can add that I am also running it on linux, the issue appeared when updating to 4.2.0.

**Comment by bdefore** [comment]
I'm also experiencing this following a yay update to 4.2.0 with code-server self-hosting on Manjaro. My case is more general than the original submitter - my steps to reproduce don't involve creating a plugin, just to open my browser to code-server.

**Comment by chientrm** [comment]
Thing work fine with code-server 4.1.0. However, I can only login Github Copilot with code-server 4.2.0.

**Comment by h4ck4life** [comment]
I'm affected as well after updated to 4.2.0 . 

4.1.0 has no issue.

Ubuntu 20.04

**Comment by ArtCore7** [comment]
Same Issue with 4.2.0 on: 

Debian GNU/Linux 11 (bullseye)

**Comment by ppedrotti** [comment]
I also have the issue with 4.2.0 on Debian 11, downgrading to 4.1.0 solved the issue. Installed using npm.

**Comment by pottiera** [comment]
Same issue on macOS 12.3

**Comment by yokowasis** [comment]
> This was missing /usr/lib/code-server/lib/vscode/extensions/node_modules/typescript/lib , it affected vscode.typescript-language-features looking for tsserver.js and html-language-features looking for typescript.js . I took the typescript dir from another install and no more errors

Can you upload the folder here, and where to put it ?

**Comment by aghasemi** [comment]
Same issue here. Happened after upgrading to 4.2.0 and I don't want to downgrade because of Jupyter notebooks :D

**Comment by cxy930123** [comment]
Put `typescript` package at `/usr/lib/code-server/lib/vscode/extensions/node_modules/typescript`

```
$ npm i typescript
$ sudo mkdir /usr/lib/code-server/lib/vscode/extensions/node_modules
$ sudo cp -r node_modules/typescript/ /usr/lib/code-server/lib/vscode/extensions/node_modules/
```

**Comment by yokowasis** [comment]
> Put `typescript` package at `/usr/lib/code-server/lib/vscode/extensions/node_modules/typescript`
> 
> ```
> $ npm i typescript
> $ sudo mkdir /usr/lib/code-server/lib/vscode/extensions/node_modules
> $ sudo cp -r node_modules/typescript/ /usr/lib/code-server/lib/vscode/extensions/node_modules/
> ```

Thanks. I can confirm this is working.

**Comment by Alirezaja1384** [comment]
> Put `typescript` package at `/usr/lib/code-server/lib/vscode/extensions/node_modules/typescript`
> 
> ```
> $ npm i typescript
> $ sudo mkdir /usr/lib/code-server/lib/vscode/extensions/node_modules
> $ sudo cp -r node_modules/typescript/ /usr/lib/code-server/lib/vscode/extensions/node_modules/
> ```

Thanks. i can confirm it works too.
It seems (at least in my case) there's no 'node_modules' in '/usr/lib/code-server/lib/vscode/extensions' directory.
Personally, I use this:
`
/usr/lib/code-server/lib/vscode/extensions
sudo npm init -y
sudo npm i typescript
`

**Comment by drmrbrewer** [comment]
I had the same problem (Ubuntu) and the solution from @Alirezaja1384 works for me (thanks)... didn't try the one from @yokowasis but probably it does the same thing?  Also in my case there was no `node_modules` in `/usr/lib/code-server/lib/vscode/extensions` before running the `npm` fix but there is after (with just `typescript` inside).

**Comment by M4TH76** [comment]
For the linuxserver/code-server/ docker container users here the fix:

log in the container console and type:
```
cd /app/code-server/lib/vscode/extensions
npm init -y
npm i typescript
```
reload your browser

**Comment by jsjoeio** [comment]
@code-asher any ideas on this? Did we forget something in one of our patches?

**Comment by ZauberNerd** [comment]
@jsjoeio do you plan on releasing a fix version for this or do we need to downgrade to 4.1.0 / wait for 4.3.0?

**Comment by jsjoeio** [comment]
@ZauberNerd yes, this fix will be in the next release!

**Comment by eng-dibo** [comment]
same here
