### ISSUE TITLE
[Docs]: Link docs in GitHub README

### ISSUE THREAD

**Issue by swetepete** [coder/code-server#5020]
## What is your suggestion?

mention Mac as a valid installation platform

## How will this improve the docs?

People use it on Mac but the docs only say Linux

**Comment by jsjoeio** [comment]
This is mentioned right here: https://coder.com/docs/code-server/latest/install#macos

**Comment by jsjoeio** [comment]
But if you have suggestions to improve it, let us know and I will reopen!

**Comment by swetepete** [comment]
I often go straight to the GitHub for a tool and I still haven’t seen anything mentioned about it on the GitHub page. It says “requirements, Linux” in the README. I also didn’t find the docs clearly linked in the README. The homepage but not a direct link to the docs. I think this would make the GitHub a lot clearer. Thanks

**Comment by jsjoeio** [comment]
>  I also didn’t find the docs clearly linked in the README. The homepage but not a direct link to the docs. I think this would make the GitHub a lot clearer. Thanks

That is very odd...Maybe we used to and it got removed? Great feedback though. Gonna reopen this and change the title. Thank you!
