### ISSUE TITLE
[Bug]: No 4.2.0 Tag on docker hub

### ISSUE THREAD

**Issue by lsascha** [coder/code-server#5022]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome
- Local OS: Windows
- Remote OS: Ubuntu
- Remote Architecture: amd64
- Kubernetes: v1.22.2 K3s
- `code-server --version`: 4.2.0

### Steps to Reproduce

1. Fetch `codercom/code-server:4.2.0` using docker / kubernetes

### Expected

successful fetching of docker image tag 4.2.0

### Actual

Error at image fetching.

### Logs

Failed to pull image "codercom/code-server:4.2.0": rpc error: code = NotFound desc = failed to pull and unpack image "docker.io/codercom/code-server:4.2.0": failed to resolve reference "docker.io/codercom/code-server:4.2.0": docker.io/codercom/code-server:4.2.0: not found

### Does this issue happen in VS Code?

- [X] I cannot reproduce this in VS Code.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

Checking the Tags on https://hub.docker.com/r/codercom/code-server/tags
it seems only the `:latest` tag was published, but not the `:4.2.0` tag.

**Comment by jsjoeio** [comment]
Just verified. I do not see 4.2.0

<img width="1904" alt="image" src="https://user-images.githubusercontent.com/3806031/159802915-49a64807-155c-47c8-a39c-6f18abea6024.png">

I wonder if it's because it failed and we ran it manually 🤔 cc @code-asher

**Comment by jsjoeio** [comment]
4.1.0 pushed both `latest` and `4.1.0`: https://github.com/coder/code-server/runs/5414802224?check_suite_focus=true#step:6:1329

4.2.0 failed so we had to run manually and it only published `latest`: https://github.com/coder/code-server/runs/5652871738?check_suite_focus=true#step:8:1308

**Comment by jsjoeio** [comment]
Ahh...i think it's because I deleted the  `source ./ci/lib.sh` in [this PR](https://github.com/coder/code-server/pull/4995/files#diff-b4e05f2c3c05f38c0cecb65dd28e31249fa6eea4eed17b864f26de60321ce8bf) and if there is no `VERSION` we can't publish the version tag: https://github.com/coder/code-server/blob/main/ci/release-image/docker-bake.hcl#L17

**Comment by benz0li** [comment]
Maybe related: Installation from [code-server-4.2.0-linux-amd64.tar.gz](https://github.com/coder/code-server/releases/download/v4.2.0/code-server-4.2.0-linux-amd64.tar.gz) -> Help > About reports `code-server: vUnknown`.

<img width="520" alt="version" src="https://user-images.githubusercontent.com/20233085/159648746-7ce9f2f0-68ba-4fe0-87be-35916fe02d89.png">

See also https://github.com/coder/code-server/pull/5014#issuecomment-1076026582.

**Comment by jsjoeio** [comment]
EDIT: GitHub Actions is [having issues:](https://www.githubstatus.com/)

> Investigating - We are experiencing delays in Actions start times and Webhook delivery. Our team is actively working on mitigating the issue.

Although the fix is merged, I can't dispatch the action to push new tags until GA is working. I'll close when it's pushed and verified.
