### ISSUE TITLE
[Bug]: No source map files in code-server v4.2.0

### ISSUE THREAD

**Issue by benz0li** [coder/code-server#5026]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Safari 15.4
- Local OS: macOS 12.3 (Monterey)
- Remote OS: [Debian bullseye](https://hub.docker.com/_/debian)
- Remote Architecture: amd64
- `code-server --version`: 4.2.0 693b1fac04524bb0e0cfbb93afc85702263329bb with Code 1.64.2

### Steps to Reproduce

1. open code-server

### Expected

No errors except `Unrecognized Content-Security-Policy directive 'worker-src'`.

### Actual

<img width="1318" alt="console-errors" src="https://user-images.githubusercontent.com/20233085/159807047-8dd10b79-beea-4155-b330-592faec961a7.png">

### Does this issue happen in VS Code?

- [X] I cannot reproduce this in VS Code.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by benz0li** [comment]
I have noticed, that the Assets for v4.2.0 are ~90 MB smaller than the ones for v4.1.0.

ℹ️ There are no _source map_ files although being pointed to in the JS files (e.g. in `lib/vscode/out/vs/loader.js`).

**Comment by jsjoeio** [comment]
cc @code-asher

**Comment by jsjoeio** [comment]
> Definitely not intentional. I bet it is due to the switch to using Code's packaging task instead of cobbling it together ourselves. They might be removing the source maps because they host them elsewhere. So we might have to patch that removal out.

https://github.com/coder/code-server/pull/5014#issuecomment-1076891923
