### ISSUE TITLE
[Bug]: code-server version not respected when installing extensions using CLI

### ISSUE THREAD

**Issue by benz0li** [coder/code-server#5031]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Safari 15.4
- Local OS: macOS 12.3 (Monterey)
- Remote OS: [Debian bullseye](https://hub.docker.com/_/debian)
- Remote Architecture: amd64
- `code-server --version`: 4.2.0 693b1fac04524bb0e0cfbb93afc85702263329bb with Code 1.64.2

### Steps to Reproduce

1.  Open code-server
2.  Install extension Jupyter
3.  Check version

### Expected

`2022.2.1010641114`

### Actual

`2022.3.1000901801`

### Does this issue happen in VS Code?

- [X] I cannot reproduce this in VS Code.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by benz0li** [comment]
Most probably related to https://github.com/eclipse/openvsx/issues/436.

**Comment by benz0li** [comment]
Further references:

*  https://github.com/eclipse/openvsx/pull/421
*  https://github.com/eclipse/openvsx/pull/419
*  https://github.com/eclipse/openvsx/pull/410
    *  https://github.com/eclipse/openvsx/issues/423

**Comment by jsjoeio** [comment]
Oh wow, nice find! Subscribing to the eclipse issue you opened.

**Comment by benz0li** [comment]
For the time being, it is best to _pin_ the version of this extension, e.g. `code-server --install-extension ms-toolsai.jupyter@2022.2.1010641114`.  
ℹ️ See https://github.com/open-vsx/publish-extensions/issues/569#issuecomment-1081180840 ff.

Not an issue of code-server.

**Comment by benz0li** [comment]
It seems to be a problem of coce-server.

Executing

```bash
code-server --install-extension ms-toolsai.jupyter
```

results in

```
Installing extensions...
Installing extension 'ms-toolsai.jupyter'...
Extension 'ms-toolsai.jupyter' v2022.3.1000901801 was successfully installed.
```

But v2022.3.1000901801 of ms-toolsai.jupyter is neither compatible with code-server 4.2.0 (Code 1.64.2) nor code-server 4.3.0 (Code 1.65.2):

```bash
curl https://open-vsx.org/api/-/query -H 'accept: application/json' -H 'content-type: application/json' -d '{"extensionId":"ms-toolsai.jupyter","extensionVersion":"2022.3.1000901801"}' | jq . 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2510    0  2435  100    75   1464     45  0:00:01  0:00:01 --:--:--  1511
```
```json
{
  "extensions": [
    {
      "namespaceUrl": "https://open-vsx.org/api/ms-toolsai",
      "reviewsUrl": "https://open-vsx.org/api/ms-toolsai/jupyter/reviews",
      "files": {
        "download": "https://open-vsx.org/api/ms-toolsai/jupyter/2022.3.1000901801/file/ms-toolsai.jupyter-2022.3.1000901801.vsix",
        "manifest": "https://open-vsx.org/api/ms-toolsai/jupyter/2022.3.1000901801/file/package.json",
        "readme": "https://open-vsx.org/api/ms-toolsai/jupyter/2022.3.1000901801/file/README.md",
        "changelog": "https://open-vsx.org/api/ms-toolsai/jupyter/2022.3.1000901801/file/CHANGELOG.md",
        "license": "https://open-vsx.org/api/ms-toolsai/jupyter/2022.3.1000901801/file/LICENSE.txt",
        "icon": "https://open-vsx.org/api/ms-toolsai/jupyter/2022.3.1000901801/file/icon.png"
      },
      "name": "jupyter",
      "namespace": "ms-toolsai",
      "version": "2022.3.1000901801",
      "publishedBy": {
        "loginName": "open-vsx",
        "fullName": "Open VSX",
        "avatarUrl": "https://avatars0.githubusercontent.com/u/61870837?v=4",
        "homepage": "https://github.com/open-vsx",
        "provider": "github"
      },
      "verified": false,
      "unrelatedPublisher": true,
      "namespaceAccess": "restricted",
      "allVersions": {
        "latest": "https://open-vsx.org/api/ms-toolsai/jupyter/latest",
        "2022.3.1000901801": "https://open-vsx.org/api/ms-toolsai/jupyter/2022.3.1000901801"
      },
      "averageRating": 5,
      "downloadCount": 140513,
      "reviewCount": 1,
      "versionAlias": [
        "latest"
      ],
      "timestamp": "2022-03-29T20:55:43.309137Z",
      "preview": false,
      "displayName": "Jupyter",
      "description": "Jupyter notebook support, interactive programming and computing that supports Intellisense, debugging and more.",
      "engines": {
        "vscode": "^1.66.0"
      },
      "categories": [
        "Programming Languages",
        "Other",
        "Extension Packs",
        "Data Science",
        "Machine Learning",
        "Notebooks",
        "Visualization"
      ],
      "extensionKind": [
        "workspace"
      ],
      "tags": [
        "__ext_jl",
        "debuggers",
        "ipynb",
        "julia",
        "jupyter",
        "keybindings",
        "multi-root ready",
        "notebook",
        "notebookKernelJupyterNotebook",
        "python",
        "raw"
      ],
      "license": "MIT",
      "homepage": "https://github.com/Microsoft/vscode-jupyter",
      "repository": "https://github.com/Microsoft/vscode-jupyter.git",
      "bugs": "https://github.com/Microsoft/vscode-jupyter/issues",
      "galleryColor": "#ffffff",
      "galleryTheme": "light",
      "qna": "https://github.com/microsoft/vscode-jupyter/discussions",
      "dependencies": [],
      "bundledExtensions": [
        {
          "url": "https://open-vsx.org/api/ms-toolsai/jupyter-keymap",
          "namespace": "ms-toolsai",
          "extension": "jupyter-keymap"
        },
        {
          "url": "https://open-vsx.org/api/ms-toolsai/jupyter-renderers",
          "namespace": "ms-toolsai",
          "extension": "jupyter-renderers"
        }
      ]
    }
  ]
}
```
👉 v2022.3.1000901801 of ms-toolsai.jupyter is only compatible with Code 1.66.0 and later.

**Comment by benz0li** [comment]
FYI @fritterhoff

**Comment by jsjoeio** [comment]
@benz0li thank you for the detailed notes/logs! So the extension installs even when it shouldn't. Does it show up in the Extensions panel and does it work?

**Comment by benz0li** [comment]
> Does it show up in the Extensions panel and does it work?

Yes, it shows up in the extension panel:

<img width="1280" alt="code-server_jupyter-extension" src="https://user-images.githubusercontent.com/20233085/163664563-54341d19-b237-42fe-9572-1afc8c2ddd63.png">

No it doesn't work properly. E.g. not listing available kernels:

<img width="600" alt="r-select-kernel_jupyter-2022 3 1000901801-python-2022 4 1" src="https://user-images.githubusercontent.com/20233085/163664803-82b188f2-b07a-49e0-9745-237183d89cdd.png">

Whereas ms-toolsai.jupyter 2022.2.1010641114 does:

<img width="600" alt="r-select-kernel_jupyter-2022 2 1010641114-python-2022 2 1924087327" src="https://user-images.githubusercontent.com/20233085/163664831-78b62169-079b-47a1-be16-ba567702f13d.png">

**Comment by benz0li** [comment]
Please add this issue to the [May 2022](https://github.com/coder/code-server/milestone/41) milestone.

**Comment by benz0li** [comment]
[code-server v4.4.0] Installation using the extension panel: Although showing incompatible versions for Python (2022.6.0) and Jupyter (2022.5.1001290443), the latest compatible versions are installed:

https://user-images.githubusercontent.com/20233085/167286380-52b213db-a033-4bcf-ab26-d2114c3ca69d.mp4

[Screen-Recording_2022-05-08_log.txt](https://github.com/coder/code-server/files/8646539/Screen-Recording_2022-05-08_log.txt)

ℹ️ This behaviour is also true for code-server v4.3.0; I was just too lazy to follow through in https://github.com/coder/code-server/issues/5031#issuecomment-1100589326...

The issue when using `code-server --install-extension` remains, though.

**Comment by jsjoeio** [comment]
Ahh...just re-read the issue. So when installing extensions via the  CLI, it doesn't check if code-server (i.e. Code) is compatible in terms of version. Seems like we could probably reproduce this with a test 🤔 

i.e. here is where we do "integration" tests: https://github.com/coder/code-server/blob/main/ci/build/test-standalone-release.sh#L17

We might be able to add another one there.

**Comment by benz0li** [comment]
@jsjoeio Can I help in any way?

**Comment by jsjoeio** [comment]
That would be awesome! I don't know which part you're interested in, but here's how I was thinking of approaching it:

1. write "integration test [here](https://github.com/coder/code-server/blob/main/ci/build/test-standalone-release.sh#L29) to reproduce bug
2. investigate why bug exists which means digging into how VS Code installs them via their CLI

**Comment by benz0li** [comment]
If considered an issue, this is upstream ([microsoft/vscode](https://github.com/microsoft/vscode)). On a Machine (arch: `amd64`/`x86_64`) running docker:

```bash
docker run --rm -ti debian:bullseye
```

Within the container:

```bash
apt update \
  && apt install -y --no-install-recommends \
    ca-certificates \
    gnupg \
    libasound2 \
    libgbm1 \
    libgtk-3-0 \
    libnss3 \
    libsecret-1-0 \
    libxkbfile1 \
    libxshmfence1 \
    libxss1 \
    wget \
  && wget https://update.code.visualstudio.com/1.65.2/linux-deb-x64/stable \
   -O code_1.65.2-1646927742_amd64.deb \
  && dpkg -i code_1.65.2-1646927742_amd64.deb
```

```bash
useradd -ms /bin/bash coder \
  && su - coder
```

Executing

```bash
code --install-extension ms-toolsai.jupyter
```

results in

```bash
Installing extensions...
Installing extension 'ms-toolsai.jupyter'...
(node:4414) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `code --trace-deprecation ...` to show where the warning was created)
Extension 'ms-toolsai.jupyter' v2022.5.1001601848 was successfully installed.
```

👉 v2022.5.1001601848 of ms-toolsai.jupyter is  definitively not compatible with Code 1.65.2.

**Comment by benz0li** [comment]
I'm going to check at https://github.com/microsoft/vscode/issues if someone already filed an issue.

**Comment by benz0li** [comment]
Cross reference: https://github.com/microsoft/vscode/issues/153201

**Comment by jsjoeio** [comment]
Woohoo! I just subscribed to that issue.

**Comment by benz0li** [comment]
Neither code-server nor VS Code do install incompatible extension versions.

It is a printing issue in the CLI, though: https://github.com/microsoft/vscode/issues/153201#issuecomment-1196584150
