### ISSUE TITLE
[Bug]: Version unknown in about section

### ISSUE THREAD

**Issue by lethargosapatheia** [coder/code-server#5033]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Firefox 98.0.2
- Local OS: Mac OS Monterey
- Remote OS: Ubuntu 20.04
- Remote Architecture: amd64
- `code-server --version`: 4.2.0

### Steps to Reproduce

Hamburger Menu - Help - About

### Expected

That the current version is displayed.

### Actual

```
code-server: vUnknown
Code: 1.64.2
Commit: Unknown
Date: 2022-03-22T20:16:06.512Z (2 days ago)
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:98.0) Gecko/20100101 Firefox/98.0
```

### Logs

I cannot find any relevant logs for this issue (maybe you could direct me)

### Does this issue happen in VS Code?

- [X] I cannot reproduce this in VS Code.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by jsjoeio** [comment]
Duplicate of https://github.com/coder/code-server/issues/5027

**Comment by lethargosapatheia** [comment]
Sorry, I did search for a similar issue, but I guess not thoroughly enough. Thanks for pointing it out.

**Comment by jsjoeio** [comment]
No worries at all! Better to report than to not to - thank you :D
