### ISSUE TITLE
[Feat]: Is it support `go to definition` in ipynb file?

### ISSUE THREAD

**Issue by h3z** [coder/code-server#5037]
## What is your suggestion?
I just don't know is it a bug or just not support "go to definition" feature in Jupyter file.

Everything is good in `.py ` file. But not work in `.ipynb` file.

I use Mac's chrome to visit `127.0.0.1:8080` which port-forward by `ssh -L 8080:localhost:8080 root@the-host-installed-codeserver`

**Comment by h3z** [comment]
fixed by download [Pylance VSIX](https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance) and install it manually.

But why it not auto installed when I install the python?

**Comment by ttu-nguyen** [comment]
@h3z Hi, I've encountered the same problem. download and install manually pylance fixed the problem in `.ipynb` but now has the same problem in `.py` file. Do you encounter the same problem? Could you please tell me which version of python you've used?
