### ISSUE TITLE
[Bug]: Unable to reproduce last opened file in Firefox privacy mode 

### ISSUE THREAD

**Issue by GeniusLe** [coder/code-server#5043]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser:Firefox 98
- Local OS:Windows 10
- Remote OS:Centos
- Remote Architecture:amd64
- `code-server --version`:4.2.0

### Steps to Reproduce

1.open dir
2.open file
3.refresh your browser 

### Expected

Reproduce all files that were open before I refreshed the browser 

### Actual

Welcome screen opened 

### Logs

null

### Screenshot/Video

null

### Does this issue happen in VS Code?

- [X] I cannot reproduce this in VS Code.

### Are you accessing code-server over HTTPS?

- [x] I am using HTTPS.

### Notes

**I'm guessing it happened because some version after 3.4 you changed the code of vscode which caused it to record the last opened saved file somewhere in the browser, but this is not desirable because you There's no guarantee you're always using the same client, it should be saved in the server, not the client, in previous versions it worked fine, I guess this change is a very unfortunate one, it loses portability isn't it? We should keep all data on the server so we can access it anytime to keep our development environment consistent forever.** 

A digression: in edge, if you enable https without configuring a certificate and use ip to access the web page, an error will occur that the view is loaded abnormally, and the color display in the code edit box is unavailable. I don't know if you care about this error, but I think I should tell you that through the tool I found that there was a certificate error when loading the two js, so this happened, it was initiated by a js,changing this may solve the error

**Comment by jsjoeio** [comment]
I believe it's stored in `localStorage` which is why it wouldn't work across different browsers 🤔 But I think that's how it's handled in VS Code so I believe you'd have to change it in VS Code itself. @code-asher can correct me if that's wrong.

> in edge, if you enable https without configuring a certificate and use ip to access the web page, an error will occur that the view is loaded abnormally

I don't think we can do much about this. Most of code-server/VS Code uses service workers for main features so we need HTTPS or a secure context in order for the browser to enable service workers. We don't have control of this.

**Comment by code-asher** [comment]
It is still opening the last directory/workspace, just not the files inside it right?  @jsjoeio is right about it being stored in the browser.  I looked into patching this to use the file system but it appeared non-trivial and we generally try to stay in line with upstream.  We could submit the issue upstream with a reproduction on vscode.dev.

**Comment by code-asher** [comment]
However if someone does come up with a minimal patch that fixes this we would definitely be happy to merge it!

**Comment by GeniusLe** [comment]
> It is still opening the last directory/workspace, just not the files inside it right? @jsjoeio is right about those being stored in the browser. I looked into patching this to use the remote file system but it appeared non-trivial and we generally try to stay in line with upstream. We could submit the issue upstream with a reproduction on vscode.dev.

Yes, it behaves like that, very much hope this problem can be solved well

**Comment by GeniusLe** [comment]
> I believe it's stored in `localStorage` which is why it wouldn't work across different browsers 🤔 But I think that's how it's handled in VS Code so I believe you'd have to change it in VS Code itself. @code-asher can correct me if that's wrong.
> 
> > in edge, if you enable https without configuring a certificate and use ip to access the web page, an error will occur that the view is loaded abnormally
> 
> I don't think we can do much about this. Most of code-server/VS Code uses service workers for main features so we need HTTPS or a secure context in order for the browser to enable service workers. We don't have control of this.

https is just a digression, I just found the problem while doing coverage testing and it can be ignored.

**Comment by GeniusLe** [comment]
thank dedication :)

**Comment by jsjoeio** [comment]
> Yes, it behaves like that, very much hope this problem can be solved well

Do you want to open an issue upstream in vscode?

**Comment by GeniusLe** [comment]
> > Yes, it behaves like that, very much hope this problem can be solved well
> 
> Do you want to open an issue upstream in vscode?

This decision is up to you, I am a loyal codeserver user. :)

**Comment by jsjoeio** [comment]
> This decision is up to you, I am a loyal codeserver user. :)

Hahaha well, if you do it, and we fix in vscode, then we can upgrade and get it in code-server so it'll help everyone :) We'd love for you to open it there since that could help both the vscode and the code-server community!

**Comment by benz0li** [comment]
Related to https://github.com/coder/code-server/issues/4212.

**Comment by code-asher** [comment]
Close in favor of https://github.com/coder/code-server/issues/4212
