### ISSUE TITLE
[Chore]: Upgrade Code to 1.66

### ISSUE THREAD

**Issue by jsjoeio** [coder/code-server#5048]

**Comment by DevXiaolan** [comment]
:)

**Comment by DevXiaolan** [comment]
When will next version come?

**Comment by jsjoeio** [comment]
The next code-server release is [in progress](https://github.com/coder/code-server/pull/5099) and should come very soon.

The upgrade to 1.66 will come in the release after which will come by [April 27](https://github.com/coder/code-server/milestone/39)

**Comment by DevXiaolan** [comment]
> The next code-server release is [in progress](https://github.com/coder/code-server/pull/5099) and should come very soon.
> 
> The upgrade to 1.66 will come in the release after which will come by [April 27](https://github.com/coder/code-server/milestone/39)

:(

**Comment by Igorgro** [comment]
A new 1.67 version will be released after a few days

**Comment by jsjoeio** [comment]
Thanks for the heads-up! When it's out, we'll create a new issue and update code-server. We fell behind a bit but we'll catch up.

**Comment by wvffle** [comment]
When can we expect a new version with the merged PR? :)

**Comment by jsjoeio** [comment]
Planning to work on a new release to come out hoping by Friday 🤞🏼
