### ISSUE TITLE
Extension Request: Gradle Language Support

### ISSUE THREAD

**Issue by Cormanz** [coder/code-server#5064]
Extension Name: Gradle Language Support
Extension Github or homepage: https://marketplace.visualstudio.com/items?itemName=naco-siren.gradle-language

**Comment by jsjoeio** [comment]
We're no longer taken extension requests since we now use https://open-vsx.org/ by default. If it's not there, please add the extension author to add it!

**Comment by Cormanz** [comment]
Oh okay, thank you for the quick and detailed response!
