### ISSUE TITLE
[Bug]: Cannot set git.path

### ISSUE THREAD

**Issue by HarrisonQi** [coder/code-server#5083]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Edge
- Local OS: Windows
- Remote OS: CentOS
- Remote Architecture: x86_64
- `code-server --version`: 4.2.0 693b1fac04524bb0e0cfbb93afc85702263329bb with Code 1.64.2

### Steps to Reproduce

1. Open settings
2. Search 'git.path'
3. Cannot find 

### Expected

I can set the git.path

### Actual

cannot find settings and Settings.json is grey:
![image](https://user-images.githubusercontent.com/33210899/162653767-fa37afbc-0459-4eff-b799-2ee60e6d7760.png)

### Does this issue happen in VS Code?

- [X] I cannot reproduce this in VS Code.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by jsjoeio** [comment]
Uh...that is very strange 🤔 I reproduced it locally.

<img width="1018" alt="image" src="https://user-images.githubusercontent.com/3806031/162852278-862c339f-488b-44c0-9632-38c87bea7d49.png">

And I see it does show up in VS Code.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/3806031/162852312-4f5b0ae9-1ec8-4fbb-af91-5c6d9604d8dd.png">

@code-asher do you think this is similar to the issue we had with the built-in TS extension stuff?

**Comment by code-asher** [comment]
Looks like it is in the "remote" tab.

Probably the intent is that user settings are for the browser and remote
is for the remote server.
