### ISSUE TITLE
ActiveDirectory and LDAP Support

### ISSUE THREAD

**Issue by ushakov-31293** [coder/code-server#5086]
Hello,

there is some organization with already working Active Directory.

There is an idea to get some students access to the `code-server`. Required features are

1. define user as organization employee in ActiveDirectory
2. ability to filter employees to get only necessary students only.

Can someone suggest solution to the task? As I understand, there is no plugin for AD / LDAP auth.

**Comment by jsjoeio** [comment]
I think we should keep our discussion to here https://github.com/coder/code-server/discussions/5081 so I'm going to close this.
