### ISSUE TITLE
[Bug]: Unable to drag extension icons

### ISSUE THREAD

**Issue by Pixel-Null** [coder/code-server#5091]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Safari
- Local OS: iOS 15.4
- Remote OS: Ubuntu Linux 20.04
- Remote Architecture: x86_64
- `code-server --version`: 4.2.0 693b1fac04524bb0e0cfbb93afc85702263329bb with Code 1.64.2
IPad pro with magic keyboard and trackpad

### Steps to Reproduce

1. Open code-server
2. Attempt to drag to reorder or move extensions to different side panel as if on desktop
3. Disappointment

### Expected

I should be able to move to reorder or move extentions

### Actual

Nothing

### Does this issue happen in VS Code?

- [X] I cannot reproduce this in VS Code.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by jsjoeio** [comment]
Did this used to happen on code-server and we lost it?

Does this work on vscode.dev or in Codespaces?

**Comment by Pixel-Null** [comment]
Ah my apologies, I just checked and it happens in vscode.dev as well. I'm unable to check codespaces as I don't have access to enterprise resources. I'll file a bug report in the vscode github as well.

**Comment by jsjoeio** [comment]
No apologies needed - our bug report should probably say vscode.dev - thank you for checking! I'm going to mark upstream-vscode and you can file there. Thanks for the quick response!
