### ISSUE TITLE
[Bug]: cannot install from AUR due to LICENSE rename

### ISSUE THREAD

**Issue by bdefore** [coder/code-server#5107]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser:
- Local OS:
- Remote OS:
- Remote Architecture:
- `code-server --version`:

### Steps to Reproduce

1. 
2.
3.

### Expected

code-server installs

### Actual

code-server fails during build

### Does this issue happen in VS Code?

- [X] I cannot reproduce this in VS Code.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

https://aur.archlinux.org/packages/code-server#comment-861207
https://github.com/coder/code-server/pull/5070

**Comment by jsjoeio** [comment]
Very surprising that this happened. Thanks for reporting!

**Comment by jsjoeio** [comment]
@coadler [fixed this](https://github.com/coder/code-server-aur/commit/3732ffea195ccb919a72a5b82f971adc601470c0) so try installing from AUR again and it should be working!

**Comment by bdefore** [comment]
Confirmed that I can install code-server-4.3.0-1 now. Thanks.

**Comment by jsjoeio** [comment]
Thanks for confirming!
