### ISSUE TITLE
[Bug]: Top menu doesn't work on iOS after update to 4.3.0

### ISSUE THREAD

**Issue by wroteksenuto** [coder/code-server#5138]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Safari / Firefox / Edge
- Local OS: iPadOS 15.4.1 / iOS 15.4.1
- Remote OS: macOS 12.3.1
- Remote Architecture: amd64 / m1
- `code-server --version`: 4.3.0

### Steps to Reproduce

1. open code-server
2. click/touch on any item in the top menu

### Expected

Submenu (for example "file") should appear

### Actual

Nothing

### Logs

Safari console log after click:
```
undefined is not an object (evaluating 'navigator.clipboard.write')
Canceled
```
**edit**: This error log was due to HTTP connection, not related to the bug.

### Does this issue happen in VS Code?

- [X] I cannot reproduce this in VS Code.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

The problem appeared after updating to version 4.3.0.

**Comment by jsjoeio** [comment]
Can you please record your screen and share a video?

**Comment by wroteksenuto** [comment]
> Can you please record your screen and share a video?

Sure: https://www.dropbox.com/s/7bzjxwsyv4hh0io/Wideo%2028.04.2022%2C%2022%2007%2031.mov?dl=0

**Comment by jsjoeio** [comment]
Thanks! Yeah that does not seem right. What happens if you close the Getting Started/Welcome and then try?

**Comment by wroteksenuto** [comment]
Problem still occurs. During normal work I couldn't manage to make it works

**Comment by jsjoeio** [comment]
Dang it. Well thanks for trying! Does this happen in vscode.dev or Codespaces by chance?

**Comment by wroteksenuto** [comment]
Both work, however they have a different Menu UI (on the left).

vscode.dev: https://www.dropbox.com/s/1bphr8u9vzzjfbi/VSCode.dev.mp4?dl=0
Github.dev (i checked also codespaces by it just redirects to github.dev):  https://www.dropbox.com/s/cn81cqwhlgdlcyk/Github.dev.mp4?dl=0

**Comment by jsjoeio** [comment]
Okay definitely a code-server issue then - thanks for the videos and checking so quickly!

**Comment by wroteksenuto** [comment]
Small update, I just discovered how to move the menu from top to left and vice versa. So I checked github.dev again and switched the menu to the top and it didn't work either. So this is a VS problem, not a code-server problem.
