### ISSUE TITLE
[Bug]: Can't preview markdown and plantuml through web

### ISSUE THREAD

**Issue by JWleo** [coder/code-server#5139]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Google Chrome  86.0.4240.198
- Local OS: WIN10
- Remote OS: LIUNX
- Remote Architecture: CENTOS 8.2
- `code-server --version`:4.3.0

### Steps to Reproduce

1. code-server
2.
3.

### Expected

![image](https://user-images.githubusercontent.com/32316654/165670986-3417fa1f-d274-4c4c-9fad-2125a38c3d2a.png)

### Actual

![image](https://user-images.githubusercontent.com/32316654/165671034-e65ead47-17bc-4b5a-ba9c-e74c245f5d24.png)
![image](https://user-images.githubusercontent.com/32316654/165671086-da2f4da0-5983-40ae-8413-0f0c715633fa.png)
![image](https://user-images.githubusercontent.com/32316654/165671220-2b343c2b-19dc-44fa-92aa-d7f607257b20.png)

### Logs

![image](https://user-images.githubusercontent.com/32316654/165671220-2b343c2b-19dc-44fa-92aa-d7f607257b20.png)

### Does this issue happen in VS Code?

- [X] I cannot reproduce this in VS Code.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

How can i use code-server easily without setting so much things???

**Comment by ThunderingII** [comment]
This issue is same to https://github.com/coder/code-server/issues/4421

Do you know which version of codeserver doesn't has this bug？

**Comment by jsjoeio** [comment]
Did you disable service workers? I'm not sure why it's failing to register.

**Comment by JWleo** [comment]
> 

solve this. It's the prolblem of https. just make mkcert to produce *.crt and *.pfx, and download to local to terify it.

**Comment by JWleo** [comment]
> This issue is same to #4421
> 
> Do you know which version of codeserver doesn't has this bug？

NO,IT's your duty to slove your env. Maybe @jsjoeio could make it easily to use in the future version

**Comment by jsjoeio** [comment]
@ThunderingII unfortunately that's a limitation of the browsers. They only allow service workers in secure contexts (i.e. HTTPS/localhost). VS  Code needs service workers enabled for most features so there isn't much we can do.
