### ISSUE TITLE
[Bug]: code-server not installing VSIX extensions

### ISSUE THREAD

**Issue by ghost** [coder/code-server#5146]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome
- Local OS: Android
- Remote OS: (Same device)
- Remote Architecture: aarch64
- Node.JS Version: 16
- `code-server --version`: 4.3.0 09bc30027a7fbba170f907a527eaa9f7219fe739 with Code 1.65.2

### Steps to Reproduce

1. Use `code-server --install-extension some-ext.vsix`

### Expected

Have the extension installed

### Actual

The code-server gives this output:
```console
~ $ code-server --install-extension /sdcard/Download/vscode-clangd-0.1.16_vsixhub.com.vsix
Installing extensions...
(node:18486) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
Unable to delete the existing folder '/data/data/com.termux/files/home/vsext/llvm-vs-code-extensions.vscode-clangd-0.1.16' while installing the extension 'llvm-vs-code-extensions.vscode-clangd'. Please delete the folder manually and try again
Failed Installing Extensions: file:///sdcard/Download/vscode-clangd-0.1.16_vsixhub.com.vsix
```

### Logs

With --verbose:
```console
~ $ code-server --install-extension /sdcard/Download/vscode-clangd-0.1.16_vsixhub.com.vsix --verbose
[2022-05-01T17:48:53.507Z] debug Found VS Code arguments; spawning VS Code CLI
[2022-05-01T17:48:53.512Z] debug Running Code CLI
Installing extensions...
(node:20122) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
Unable to delete the existing folder '/data/data/com.termux/files/home/.local/share/code-server/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.16' while installing the extension 'llvm-vs-code-extensions.vscode-clangd'. Please delete the folder manually and try again
Failed Installing Extensions: file:///sdcard/Download/vscode-clangd-0.1.16_vsixhub.com.vsix
```

### Does this issue happen in VS Code?

- [X] I cannot reproduce this in VS Code.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

I installed code-server with this command:
`FORCE_NODE_VERSION=16 yarn global add code-server --ignore-engines`
I don't know if one of these flags or enviroment variables break the code-server

> PS: I marked `I cannot reproduce this in VS Code` because its obrigatory, but i don't have a computer to test, and no, i don't used HTTPS.

**Comment by jsjoeio** [comment]
> Unable to delete the existing folder '/data/data/com.termux/files/home/.local/share/code-server/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.16'

Does it have the right permissions?

**Comment by KKD4yv1d** [comment]
Yeah, this is `ls -lA` on `/data/data/com.termux/files/home/.local/share/code-server`
```
~/.../share/code-server $ ls -lA
total 26
drwx------ 2 u0_a301 u0_a301 3488 May  1 23:38 Machine
drwx------ 4 u0_a301 u0_a301 3488 May  1 23:38 User
drwx------ 2 u0_a301 u0_a301 3488 May  1 23:38 coder-logs
-rw------- 1 u0_a301 u0_a301   89 May  1 23:38 coder.json
drwx------ 2 u0_a301 u0_a301 3488 May  1 23:38 extensions
-rw------- 1 u0_a301 u0_a301    0 May  1 23:39 heartbeat
drwx------ 3 u0_a301 u0_a301 3488 May  1 23:38 logs
-rw------- 1 u0_a301 u0_a301   36 May  1 23:38 machineid```

**Comment by jsjoeio** [comment]
Hmm...maybe when code-server runs, it's running as a user without the right permissions? Any ideas @code-asher ?

**Comment by KKD4yv1d** [comment]
> Hmm...maybe when code-server runs, it's running as a user without the right permissions? Any ideas @code-asher ?

The `code-server` process run as the same user that i use
`$ ps aux`:
```
u0_a301  28881 73.7  2.1 11258292 82292 pts/3  R<l   1970   0:02 node /data/data/com.termux/files/usr/bin/code-server --
```
`$ whoami`:
```
u0_a301
```

**Comment by jsjoeio** [comment]
What happens if you manually remove the folder and then try installing again?

**Comment by KKD4yv1d** [comment]
> What happens if you manually remove the folder and then try installing again?

The folder doesn't even exist, I already tried giving `rm -rf` on it and it says the folder doesn't exist, but if you like to see the output, is here:
`$ rm .local/share/code-server/extensions/* -rfv ; code-server --install-extension /sdcard/Download/vscode-clangd-0.1.16_vsixhub.com.vsix`:
```
Installing extensions...
(node:10457) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
Unable to delete the existing folder '/data/data/com.termux/files/home/.local/share/code-server/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.16' while installing the extension 'llvm-vs-code-extensions.vscode-clangd'. Please delete the folder manually and try again
Failed Installing Extensions: file:///sdcard/Download/vscode-clangd-0.1.16_vsixhub.com.vsix
```

**Comment by KKD4yv1d** [comment]
I suspect of this deprecation warning of `fs.rmdir()`

**Comment by jsjoeio** [comment]
But it's just a warning, right? It shouldn't fail because of that, at least I wouldn't expect it too. @code-asher any ideas?

**Comment by KKD4yv1d** [comment]
Yeah, it's a warning of deprecation

**Comment by code-asher** [comment]
Does this happen with Node 14?  The last time I tried 16 it did not work.

**Comment by code-asher** [comment]
The next release will be upgraded to use 16 though.

**Comment by KKD4yv1d** [comment]
> Does this happen with Node 14? The last time I tried 16 it did not work.

I'll test on node 14 now

**Comment by KKD4yv1d** [comment]
This doesn't happen on Node 14, it works normally

**Comment by jsjoeio** [comment]
Then that must be it! This should be fixed in the next release.
