### ISSUE TITLE
[Docs]: How did they do it?

### ISSUE THREAD

**Issue by xx1182** [coder/code-server#5154]
## What is your suggestion?
Well, simply explaining how it has been done, it's bothering me, i know VSCODE is electron based so it's basically like running a small chromium, so even checking the source of vscode, there is css, and all the markup for the page.
But how did you do it? I tought there must be a Renderer() function and you just made a new function like StartServer() to already present stylesheet.

## How will this improve the docs?
The "product" is awesome, but some just want to know.

## Are you interested in submitting a PR for this?
Yes of course.

**Comment by jsjoeio** [comment]
This honestly might be a better question for `microsoft/vscode` since we really leverage most of their code to make code-server work.
