### ISSUE TITLE
[Chore]: upgrade Code to 1.67 

### ISSUE THREAD

**Issue by jsjoeio** [coder/code-server#5165]

**Comment by balajib-b** [comment]
#https://github.com/microsoft/vscode/tree/1.67.1 
VSCode 1.67.1 released.

**Comment by jsjoeio** [comment]
Sadly, I think it might get delayed :( I had some other priorities come up. I'll update the milestone accordingly. I still need to upgrade us to 1.67 though.

**Comment by balajib-b** [comment]
@jsjoeio 1.68 has been released now. can we jump to 1.68 directly or do we need to stick to the upgrade path strictly?

**Comment by jsjoeio** [comment]
We're low on bandwidth because the team is pushing for a big coder/coder release. I think we have to go one release at a time 🤔 but @code-asher might know better.

I'll still be doing some testing stuff because it's quick and what I'm able to contribute this month but @code-asher should be able to help with the VS Code upgrade soon.

**Comment by code-asher** [comment]
I think one at a time is smart because there will likely be fewer conflicts to deal with at a time.  I will probably try jumping straight to 1.68 and see if the conflicts are too gnarly.  If so I will do 1.67 first.

**Comment by babytomas** [comment]
> All Copilot extensions compatible with 1.66 seemed to have stopped working, so it would be great if we could get an update to 1.67 soon.

I tried to compile vscode 1.68 according to the "Version updates to Code" in the: https://coder.com/docs/code-server/latest/CONTRIBUTING , and it work's for me after manually resolving some file conflicts.

If you wanna use copilot, maybe you can try before code-server is updated.

**Comment by jsjoeio** [comment]
> I tried to compile vscode 1.68 according to the "Version updates to Code" in the: https://coder.com/docs/code-server/latest/CONTRIBUTING , and it work's for me after manually resolving some file conflicts.

That's fantastic news! Thanks for letting us know!

**Comment by turley** [comment]
FYI - if you want to use copilot now with the current version of code-server, you can do what I did:

- Download the `.vsix` here: https://marketplace.visualstudio.com/items?itemName=GitHub.copilot
- Rename the file to have a `.zip` extension and extract to a temporary location
- Change the value of `Microsoft.VisualStudio.Code.Engine` in `extension.vsixmanifest` to `^1.66.0`
- Change the value of `vscode` in `extension/package.json` (under `engines`) to also be `^1.66.0`
- Create a zip with the modified files (including the rest that wasn't modified), and rename back to a `.vsix` extension
- Install on the current version of code-server
- (optional) Feed your code to the AI and help it take over the world ;)

**Comment by jsjoeio** [comment]
@balajib-b maybe by the end of this week? We have next week off but I will try my best!
