### ISSUE TITLE
[Feat]: Dockerfile entrypoint.d

### ISSUE THREAD

**Issue by djarbz** [coder/code-server#5177]
## What is your suggestion?
Add logic to the entrypoint to load user provided entrypoint scripts.

## Why do you want this feature?
This would allow for us to setup the workspace beyond the base image without maintaining individual images per purpose.
For example, we could call to install a language or runtime dependency, or even install code-server plugins.

## Are there any workarounds to get this functionality today?
Manually run the scripts via the code-server terminal.

## Are you interested in submitting a PR for this?
Possibly.

**Comment by jsjoeio** [comment]
What are your thoughts on this @code-asher ?

**Comment by code-asher** [comment]
Is overriding the entrypoint an option?  Something like:

```
mkdir entrypoint.d
$ cat << EOF >> entrypoint.d/my-script.sh
> #!/bin/sh
> echo hello
> /usr/bin/entrypoint.sh --bind-addr 0.0.0.0:8080 .
> EOF
$ chmod +x entrypoint.d/*
$ docker run -v $PWD/entrypoint.d:/entrypoint.d --entrypoint /entrypoint.d/my-script.sh codercom/code-server:latest
```

**Comment by djarbz** [comment]
That is one way to do it, I'm slightly concerned about the following bit of code.
I'm not 100% sure on the ramifications of it and if it would need to be ran prior to my scripts or if running it afterwards is ok?
```
# We do this first to ensure sudo works below when renaming the user.
# Otherwise the current container UID may not exist in the passwd database.
eval "$(fixuid -q)"

if [ "${DOCKER_USER-}" ]; then
  USER="$DOCKER_USER"
  if [ "$DOCKER_USER" != "$(whoami)" ]; then
    echo "$DOCKER_USER ALL=(ALL) NOPASSWD:ALL" | sudo tee -a /etc/sudoers.d/nopasswd > /dev/null
    # Unfortunately we cannot change $HOME as we cannot move any bind mounts
    # nor can we bind mount $HOME into a new home as that requires a privileged container.
    sudo usermod --login "$DOCKER_USER" coder
    sudo groupmod -n "$DOCKER_USER" coder

    sudo sed -i "/coder/d" /etc/sudoers.d/nopasswd
  fi
fi
```

Currently I build a custom image that inserts the following code after this section.
```
# Allow users to have scripts run on container startup to prepare workspace.
chmod u+x $HOME/entrypoint.d/*.sh
for f in $HOME/entrypoint.d/*.sh; do
  echo "Running Entrypoint: ${f}"
  bash "${f}"
done
```

**Comment by code-asher** [comment]
I think it should generally be OK although I could imagine issues if the
user's scripts referenced a hardcoded user or if the UID was
non-standard since fixuid would not have had a chance to run yet.

So with that in mind you are probably right that adding that code into
the entrypoint.sh is the better solution.  Please feel free to submit a
PR and we can get it merged in!
