### ISSUE TITLE
[Bug]: xz: (stdin): File format not recognized

### ISSUE THREAD

**Issue by tony-jinwoo-ahn** [coder/code-server#5185]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: chrome
- Local OS: Ubuntu 18.04.4
- Remote OS: Ubuntu 18.04.4
- Remote Architecture: amd64
- `code-server --version`: v4.4.0 Latest

### Steps to Reproduce

Follow the Development workflow: https://github.com/coder/code-server/blob/main/docs/CONTRIBUTING.md#development-workflow

1. git clone https://github.com/coder/code-server.git 
2. git submodule update --init 
3. quilt push -a 
4. yarn 

### Expected

yarn install completed

### Actual

code-server/node_modules/shellcheck: Command failed.
Command: ./install.sh
```
xz: (stdin): File format not recognized
tar: Child returned status 1
```

### Logs

```
$ yarn
yarn install v1.22.18
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
[4/5] Linking dependencies...
warning " > @coder/logger@1.1.16" has unmet peer dependency "@google-cloud/logging@^4.5.2".
[5/5] Building fresh packages...
[1/3] ⠄ argon2
[2/3] ⠄ yarn
error /home/test/code-server/node_modules/shellcheck: Command failed.
Exit code: 2
Command: ./install.sh
Arguments:
Directory: /home/test/code-server/node_modules/shellcheck
Output:
xz: (stdin): File format not recognized
tar: Child returned status 1
```

### Does this issue happen in VS Code?

- [X] I cannot reproduce this in VS Code.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

```
$ bsdtar --version
bsdtar 3.2.2 - libarchive 3.2.2 zlib/1.2.11 liblzma/5.2.2 bz2lib/1.0.6 liblz4/1.7.1
```

```
$ tar --version
tar (GNU tar) 1.29
```

**Comment by jsjoeio** [comment]
Hmm...so it's failing on the `yarn` step while trying to install `shellcheck` 🤔 I'm not sure why though...

Seems similar to this: https://github.com/gunar/shellcheck/issues/18

related links:
- https://stackoverflow.com/questions/44319693/docker-build-xzstdin-file-format-not-recognized
- https://askubuntu.com/questions/874519/tar-xz-extracting-error-xz-stdin-file-format-not-recognized
- https://github.com/oclint/oclint/issues/569
- https://forum.libreelec.tv/thread/7906-fixed-compile-error-le-8-0-1-xz-stdin-file-format-not-recognized/

**Comment by jsjoeio** [comment]
Hmm... seems like `yarn watch` isn't properly building vscode for you. Just to confirm, you ran steps 1-4 in the Development Workflow?

It may take some time for VS Code to build the first time so if have a couple mins, you're still having issues, feel free to share the logs. I'm guessing you tried to access it before it was done building

**Comment by tony-jinwoo-ahn** [comment]
> Yes, I ran steps 1-4 in the Development Workflow exactly.
I would test again when I get home. 
Thank you!

**Comment by tony-jinwoo-ahn** [comment]
by the way, I'm trying to build on both ```Ubuntu 18.04 and 20.04``` now. Are they compatible?
Is it possible to build code-server on ```Windows10``` or not?

**Comment by jsjoeio** [comment]
They should be 🤔 I develop on macOS so haven't tested in a bit but should be fine.

Windows10...possibly not

**Comment by tony-jinwoo-ahn** [comment]
I've followed these steps today:
```
yarn build
yarn build:vscode
yarn release
cd release
yarn --production
node .
```

then I see:
```
...
info  HTTP server listening on http://0.0.0.0:8080/ 
info    - Authentication is disabled 
info    - Not serving HTTPS 
...
```

then I tried to connect via Firefox and Chrome. I tried:
```
http://localhost:8080/
http://0.0.0.0:8080/
```

then I see:
```
Forbidden.
```

I modified ```~/.config/code-server/config.yaml``` for many times,
I tried:
```
127.0.0.1:8080
127.0.0.1:9999
0.0.0.0:8080
0.0.0.0:9999
```

but nothing helped.

have you ever seen this kind of error?
I think there's simple way to fix it, but i can't figure it out.

**Comment by tony-jinwoo-ahn** [comment]
I tried standalone deb package, but failed.
what I did is:
```
yarn release:standalone
yarn test:standalone-release
yarn package
```
then I installed in my docker as always:
```
code-server/release-packages/code-server_4.4.0_amd64.deb
```
then I see:
```
Forbidden.
```

So I tried official release:
```
https://github.com/coder/code-server/releases/download/v4.4.0/code-server_4.4.0_amd64.deb
```
then it worked!

it's strange. I need to modify code-server and contribute some code, but I can't see my custom fresh build working.

the HEAD commit I'm currently on is:
```
commit 1e304b1e7d3b5cd0edb1aa35edbbe74cd79254c2 (HEAD -> main, origin/main, origin/HEAD)
Author: Feng Yu <F3n67u@outlook.com>
Date:   Sat May 14 00:57:50 2022 +0800

    chore(deps): upgrade typescript to v4.6 (#5202)
```

I didn't modify any code, I just git clone and build and try custom code-server, but what I see on the browser is:
```
Forbidden.
```

**Comment by tony-jinwoo-ahn** [comment]
I tried building on macOS and succeeded! 😀
I don't know why it's not working on Ubuntu 20.04

**Comment by tony-jinwoo-ahn** [comment]
could you recommend Ubuntu docker image to build custom code-server please?

**Comment by tony-jinwoo-ahn** [comment]
if you guide me official Dockerfile for Ubuntu environment, I'd follow every single steps to install exactly same packages, to build custom code-server for Ubuntu.

**Comment by tony-jinwoo-ahn** [comment]
at first, I tried building code-server on latest commit ```1e304b1e7d3b5cd0edb1aa35edbbe74cd79254c2```, but failed.

Now I've git checkout ```v4.4.0``` and now everything succeeded on Ubuntu 20.04!
the commit ```c96202528fc0daf1339a55c45951f40834b72c95 (HEAD, tag: v4.4.0)``` works fine to me.

by the way, if you guide me official Dockerfile for Ubuntu environment, it would be really helpful for the next time.
> if you guide me official Dockerfile for Ubuntu environment, I'd follow every single steps to install exactly same packages, to build custom code-server for Ubuntu.


thank you so much for this amazing project. :)

**Comment by jsjoeio** [comment]
Hooray! Sorry you had to jump through so many hoops. 

> by the way, if you guide me official Dockerfile for Ubuntu environment, it would be really helpful for the next time.

As in, a Dockerfile so that you can work on code-server in an Ubuntu environment? We used to have a Debian based one but removed it because we didn't want to officially maintain one: https://github.com/coder/code-server/pull/3134

**Comment by tony-jinwoo-ahn** [comment]
ok thank you so much!
