### ISSUE TITLE
[Feat]: Extension request

### ISSUE THREAD

**Issue by ppjuarez** [coder/code-server#5191]
## What is your suggestion?
Add the extension marlon407.code-groovy
https://marketplace.visualstudio.com/items?itemName=marlon407.code-groovy
## Why do you want this feature?
I use this framework and this is the only recommended extension by grails

**Comment by benz0li** [comment]
See https://github.com/marlon407/code-groovy/issues/31

**Comment by jsjoeio** [comment]
We use OpenVSX so you'll need to wait until it's published by the extension author. See https://github.com/coder/code-server/issues/5191#issuecomment-1123208001
