### ISSUE TITLE
[Bug]: Typescript and Javascript Language Features not activating

### ISSUE THREAD

**Issue by Mario-iGod** [coder/code-server#5193]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome
- Local OS: Windows
- Remote OS: Raspbian (Raspberry Pi OS)
- Remote Architecture: aarch64
- `code-server --version`: 4.4.0 b088ec7adf9e17bc75215f79e21498eb40da03ed with Code 1.66.2

### Steps to Reproduce

1. Run code-server without using HTTPS
2. Open code-server in chrome
3. Open any .js file
4. TS and JS Language Features not activating.

### Expected

TS and JS Language Features activating.

### Actual

TS and JS Language Features not activating.

### Logs

This is the only error I've seen when using HTTPS and `--verbose`:
```
ERR [Service Worker] registration DOMException: Failed to register a ServiceWorker for scope ('https://raspberry:4000/') with script ('https://raspberry:4000/_static/out/browser/serviceWorker.js'): An SSL certificate error occurred when fetching the script.
```
Errors when opening a workspace file (they don't show when opening a regular folder):
```
Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'initialized')
    at configurationService.ts:135:20
GET http://raspberry:4000/vscode-remote-resource?path=%2Fhome%2Fpi%2F.local%2Fshare%2Fcode-server%2Fextensions%2Fpkief.material-icon-theme-4.17.0%2Ficons%2Ffolder-root~1874217441.svg&tkn= 404 (Not Found)
GET http://raspberry:4000/vscode-remote-resource?path=%2Fhome%2Fpi%2F.local%2Fshare%2Fcode-server%2Fextensions%2Fpkief.material-icon-theme-4.17.0%2Ficons%2Fgit~1874217441.svg&tkn= 404 (Not Found)
GET http://raspberry:4000/vscode-remote-resource?path=%2Fhome%2Fpi%2F.local%2Fshare%2Fcode-server%2Fextensions%2Fpkief.material-icon-theme-4.17.0%2Ficons%2Ffolder-root-open~1874217441.svg&tkn= 404 (Not Found)
GET http://raspberry:4000/static/out/vs/base/worker/workerMain.js net::ERR_NAME_NOT_RESOLVED
```
In the console there are no errors.

### Screenshot/Video

![image](https://user-images.githubusercontent.com/54030022/167902819-36289e99-4fa2-46c8-bc95-6b31524adf47.png)

### Does this issue happen in VS Code?

- [X] I cannot reproduce this in VS Code.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

In the Logs section, the last 3 errors are from an icon theme which doesn't display some icons for some open folders for which it displays a different icon based on their name, and some other icon files like python files.
Also, I accessed code-server from my phone without using HTTPS and the icon theme and TS and JS Language Features were working fine.
When accessing code-server from my phone like as described earlier and from my PC via HTTPS I noticed that the part on the left of the status bar which shows whats loading shows the TS and JS Features, but from my PC it just doesn't appear.
I've tested accessing code-server from Edge and it works like in my phone.

**Comment by jsjoeio** [comment]
Hmm... I think accessing it via `http://raspberry:4000` is considered insecure and that's why you're getting the service worker error. I imagine the TS/JS features rely on things that only work when service workers are working so I don't think there's much we can do here.

**Comment by Mario-iGod** [comment]
Oh OK, thanks for the reply, I'll access via HTPPS then.

**Comment by jsjoeio** [comment]
Awesome! I'm going to close this for now then.
