### ISSUE TITLE
[Bug]: iPadOS Keyboard Shortcuts

### ISSUE THREAD

**Issue by MitchellPT** [coder/code-server#5197]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Safari / Chrome (all that ive tried)
- Local OS: iPad OS 15.4.1
- Remote OS: Ubuntu 21.04
- Remote Architecture: Linux
- `code-server --version`: v4.4.0

### Steps to Reproduce

1. Try F Keys
(any keys in general)

### Expected

F5 Should start program.

### Actual

No result/Does Nothing

### Does this issue happen in VS Code?

- [X] I cannot reproduce this in VS Code.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

F5 Keys are kinda weird on iPadOS. I have to click Shift+CTRL+5 in order to work (at least that is what it is in terminus), I am not sure if this is app defined or in general

Not sure whether this is a bug or a limitation with Apple and i have to create keybindings.
https://coder.com/docs/code-server/latest/ipad#workaround-for-issue-with-ctrlc-not-stopping-a-running-process-in-the-terminal

If this is the case ^ Possibly a them already being implimented?

**Comment by jsjoeio** [comment]
I think this is a limitation of keybindings on Apple devices. I've had to remap quite a few myself so I don't think there is much we can do here. If you can reproduce it on vscode.dev, you could submit an issue upstream.

**Comment by MitchellPT** [comment]
> I think this is a limitation of keybindings on Apple devices. I've had to remap quite a few myself so I don't think there is much we can do here. If you can reproduce it on vscode.dev, you could submit an issue upstream.

Ah ok. 
Would you be able to share them?
Do you mean see if they work on their and if they don't submit?

**Comment by MitchellPT** [comment]
Ah ok, I cant see because i cant run code on vscode.dev but keybinds kinda work on both, i was slightly mistaken. 
I was trying to do the windows keybinds on my iPad. Discovered they are slightly different…
Although It does say F5 for running code what does not exist?

**Comment by JWleo** [comment]
@MitchellPT ON ipad, the difference is not only about F5, but also about **_window_**-key , **_ctrl_**-key and others.
Could anyone can produce some software or otherthings to  remap the keybroad of ipad to the keybroad of windows.

**Comment by MitchellPT** [comment]
> @MitchellPT ON ipad, the difference is not only about F5, but also about **_window_**-key , **_ctrl_**-key and others.
> Could anyone can produce some software or otherthings to remap the keybroad of ipad to the keybroad of windows.
> @jsjoeio

![E0474490-C863-4CD4-AAB6-FEE54EB7F506](https://user-images.githubusercontent.com/24734120/168005910-1be59cc8-6377-4c0c-8a4d-58399e1bdb83.jpeg)
![DA26455B-EB3D-4754-8D2F-8C9C9A6508E5](https://user-images.githubusercontent.com/24734120/168005914-559de838-d501-4397-b14a-1d9cd94bbd0e.jpeg)

Windows and CTRL key seem to already show their corresponding keys. But start debug still just says F5?

**Comment by MitchellPT** [comment]
One in picture is show debug ^ but start debug is just F5**

**Comment by code-asher** [comment]
Closing as stale and an upstream issue.  Check out https://github.com/microsoft/vscode for issues around iOS keyboard shortcuts.
