### ISSUE TITLE
[Bug]: IPadOS code menu missing functionality 

### ISSUE THREAD

**Issue by P8ten** [coder/code-server#5199]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: safari, chrome, Firefox 
- Local OS: iPadOS 
- Remote OS: Raspbian GNU/Linux 11 (bullseye)
- Remote Architecture: armv7l
- `code-server --version`: 4.4.0

### Steps to Reproduce

1. 
2.
3.

### Expected

Normal menu functionality.  Select file, edit, etc, and have a drop down menu appear.

### Actual

No drop down menu appears.

### Screenshot/Video

https://user-images.githubusercontent.com/24801516/168177068-e3cfaa84-056d-4199-bb78-a61ec0acc2cd.mp4

### Does this issue happen in VS Code?

- [ ] I cannot reproduce this in VS Code.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

I can get the normal functionality when I access the remote from an android device.

**Comment by jsjoeio** [comment]
Does this issue happen on vscode.dev/Codespaces?

Are you using an external mouse/trackpad?

**Comment by P8ten** [comment]
Vscode.dev works as expected.  I am using apples’s magic keyboard attached to the IPad.  Happens when I use no keyboard as well.

**Comment by MitchellPT** [comment]
Strange, as this works perfectly fine for me... What browser is that and one iPadOS Version?

**Comment by P8ten** [comment]
The browser in the clip is safari, but I've tried Firefox and chrome to no avail.  The ipados is 15.4.1 (M1 iPad pro).  Tempted to reinstall everything, but it works on my Android device as well as Windows.

**Comment by MitchellPT** [comment]
> The browser in the clip is safari, but I've tried Firefox and chrome to no avail. The ipados is 15.4.1 (M1 iPad pro). Tempted to reinstall everything, but it works on my Android device as well as Windows.

Hmm. Are running any ad blockers?
I'm on gen 4 what is one before M1 but I don't see how that can make a difference like that...
You are also running it on ARM but neither should that make any difference... strange..

**Comment by P8ten** [comment]
No ad blocker installed.  Very strange...

**Comment by P8ten** [comment]
https://user-images.githubusercontent.com/24801516/168401584-3937d57e-15c8-438e-8f23-eab8cb8efeea.MOV

I just tried rotating my iPad to portrait mode to see if that made a difference and it worked as expected.  Even when rotating back to landscape, I was able to keep the menu functionality until I hit "Toggle menu bar" from the getting started splash.

**Comment by P8ten** [comment]
Sorry, my mistake.  I have the same issue on vscode.dev when toggling the menu.  Looks like it is on their end.

**Comment by jsjoeio** [comment]
@P8ten do you mind opening an issue in their repo?
