### ISSUE TITLE
[Bug]: Git and Debug Console is missing

### ISSUE THREAD

**Issue by tujeff** [coder/code-server#5206]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome
- Local OS: macOS
- Remote OS: Debian Bullseye
- Remote Architecture: amd64
- `code-server --version`: 4.4.0

### Steps to Reproduce

1. after upgrade to 4.4.0
2.
3.

### Expected

Should have Debug Console and Git working correctly after upgrade to 4.4.0

### Actual

After upgrading to 4.4.0, Git and Debug Console is missing.

### Screenshot/Video

<img width="1070" alt="Screen Shot 2022-05-15 at 10 18 51 PM" src="https://user-images.githubusercontent.com/67305851/168833819-dadc510d-0eec-4183-8d49-8d1322023b3e.png">

### Does this issue happen in VS Code?

- [X] I cannot reproduce this in VS Code.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by tujeff** [comment]
This is version 4.3.0, Git and Debug Console are fine here.

<img width="1020" alt="Screen Shot 2022-05-18 at 12 32 52 PM" src="https://user-images.githubusercontent.com/67305851/169147171-517650cf-a540-4a8f-90e4-97da55d2f3b0.png">

Can anyone look into this? Thanks

**Comment by jsjoeio** [comment]
Did you disable it in your settings? I see Debug Console in mine.

<img width="1712" alt="image" src="https://user-images.githubusercontent.com/3806031/169410771-5ff5b138-7ebc-474e-adeb-7f9e927f79ed.png">

Can you share your `settings.json`?

**Comment by tujeff** [comment]
<img width="1020" alt="Screen Shot 2022-05-19 at 4 01 44 PM" src="https://user-images.githubusercontent.com/67305851/169418093-caafc6c9-f57f-4fad-a8dc-122c88c3f107.png">

Again, in 4.3.0 is fine for me. but not in 4.4.0. thanks

**Comment by jsjoeio** [comment]
Can you try removing resetting your settings and removing all extensions?

**Comment by tujeff** [comment]
Yes, did that, I also did a fresh install with 4.4.0. Same results.

I did a fresh install with 4.3.0, everything looks fine though.

**Comment by jsjoeio** [comment]
Sadly, I can't reproduce. I also don't see the Git tab in VS Code so I'm not sure what we can do here. 

<img width="1136" alt="image" src="https://user-images.githubusercontent.com/3806031/169607906-60285b31-94db-439b-95e8-6736e19f0e76.png">

**Comment by tujeff** [comment]
I've found the problem. My file permissions were messed up here, caused all the errors. 

<img width="603" alt="Screen Shot 2022-05-31 at 8 24 10 AM" src="https://user-images.githubusercontent.com/67305851/171213416-072d5274-4eaa-4d2c-8f44-fda536af395b.png">

Thank you guys for all your time and hard work !!

**Comment by jsjoeio** [comment]
Hooray! Happy to hear that. Thanks for letting us know!
