### ISSUE TITLE
[Bug]: ripgrep not getting properly carried around when the remote system is FreeBSD

### ISSUE THREAD

**Issue by rowheel** [coder/code-server#5216]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Google Chrome
- Local OS: Arch Linux
- Remote OS: FreeBSD 13.1-RELEASE
- Remote Architecture: amd64
- `code-server --version`: 4.4.0 b088ec7adf9e17bc75215f79e21498eb40da03ed with Code 1.66.2

### Steps to Reproduce

1. Open code-server
2. Press Ctrl-Shift-F to type in any search keyword
3. And it gets an error like this

![image](https://user-images.githubusercontent.com/29014642/169680747-2651c2bc-a43c-4ddc-85bd-5b3c01a613e0.png)

### Expected

The ripgrep executable is expected to be present at this place.

### Actual

But actually it's not, and users have to manually symlink the system-wide installed instance of ripgrep to that place persumably like this:

```
$ ln -sf $(which rg) $(yarn global dir)/node_modules/code-server/lib/vscode/node_modules/@vscode/ripgrep/bin
```

### Does this issue happen in VS Code?

- [X] I cannot reproduce this in VS Code.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by jsjoeio** [comment]
Hmm..I've seen this before but can't recall how we fixed it. We'll need to investigate. Thank you!

**Comment by das-rob3rt** [comment]
Thanks for looking into it, @jsjoeio .

Could you please also add this workaround to [FreeBSD guide](https://coder.com/docs/code-server/latest/npm#freebsd) or [troubleshooting](https://coder.com/docs/code-server/latest/npm#troubleshooting)?

**Comment by jsjoeio** [comment]
@das-rob3rt certainly!

**Comment by code-asher** [comment]
Closing as an upstream issue, as I believe the ripgrep module would need to add support for FreeBSD?
