### ISSUE TITLE
[Bug]:  error open floder

### ISSUE THREAD

**Issue by Winter-is-comingXK** [coder/code-server#5226]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Edge
- Local OS: Windows 10
- Remote OS: ubuntu 20
- Remote Architecture: amd64
- `code-server --version`: 4.4.0

### Steps to Reproduce

1. mkdir /code/c++
2.open folder `/code/c++`

### Expected

it should open `/code/c++`

### Actual

it becomes `/code/c` and open fail

### Does this issue happen in VS Code?

- [X] I cannot reproduce this in VS Code.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by jsjoeio** [comment]
I couldn't reproduce this on macOS.

## Screenshot

<img width="1712" alt="image" src="https://user-images.githubusercontent.com/3806031/170789480-1568ecea-d374-4333-b385-e65e4ea4acbe.png">

What shell are you using?

**Comment by Winter-is-comingXK** [comment]
![1](https://user-images.githubusercontent.com/33370220/170817621-9c6554e8-1b3c-4365-bd9c-f75ed3162b95.png)
![2](https://user-images.githubusercontent.com/33370220/170817622-54da54b7-b25d-4168-90d2-154c63220f3d.png)

**Comment by Winter-is-comingXK** [comment]
> I couldn't reproduce this on macOS.
> 
> ## Screenshot
> <img alt="image" width="1712" src="https://user-images.githubusercontent.com/3806031/170789480-1568ecea-d374-4333-b385-e65e4ea4acbe.png">
> 
> What shell are you using?

here

**Comment by jsjoeio** [comment]
Unfortunately, I can't read that. What shell is that?

**Comment by zct** [comment]
I encounter the same problem with open c++ folder

**Comment by jsjoeio** [comment]
@zct does this happen in Codespaces?

**Comment by zct** [comment]
@jsjoeio  yes,  I bypass this  by rename the dir

**Comment by jsjoeio** [comment]
@zct can you open an issue upstream?
