### ISSUE TITLE
[Bug]: Initialise Repository using Source Control - Fails

### ISSUE THREAD

**Issue by GL007** [coder/code-server#5228]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome
- Local OS: Mac Catalina
- Remote OS: Ubuntu 20.40
- Remote Architecture: Linux Box on Digital Ocean amd64
- `code-server --version`: 4.4.0

### Steps to Reproduce

1. Initialise Repository the "Initialise Repository" in the "Source Control" Panel
2.
3.

### Expected

For source control to show the files

### Actual

it creates the git folder and config files etc, but does not reload and show files or the ui for git management, even when I reload the page is does not work. Git is installed, it fresh install of ubuntu and code-server.

it just shows

![Screenshot 2022-05-27 at 14 09 59](https://user-images.githubusercontent.com/20803662/170710026-b5498e8f-6eab-4ecd-bf97-e4dfd981f985.png)

I even setup a new server to check, same issue

### Does this issue happen in VS Code?

- [X] I cannot reproduce this in VS Code.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by jsjoeio** [comment]
Can you please fill out the rest of this bug report? i.e. title and steps to reproduce.

**Comment by tujeff** [comment]
I have the same problems when I upgraded to 4.4.0. The Git and Debug console are not showed at all. It was ok in 4.3.0. I even rebuild the server (Debian Bullseye 11.3 systemctl) with no data, no extensions. Same result.

<img width="1070" alt="coder-440" src="https://user-images.githubusercontent.com/67305851/170769895-4449db77-28e9-457f-ab14-f080617d52f6.png">

**Comment by GL007** [comment]
Ok updated the ticket, still no luck

**Comment by tujeff** [comment]
I've found the issue. My file permissions were messed up here, caused all the errors.

<img width="603" alt="Screen Shot 2022-05-31 at 8 24 10 AM" src="https://user-images.githubusercontent.com/67305851/171214382-4b25b6b9-e970-445b-8c08-0ff3ac991abf.png">

Thank you for your time to help me, and your hard work !!
