### ISSUE TITLE
[Insturction]: change code-server password

### ISSUE THREAD

**Issue by passerbyo** [coder/code-server#5232]
## What is your suggestion?
add question ```change code-server password```
## How will this improve the docs?
add answer ```cat ~/.config/code-server/config.yaml```
add answer ```nano ~/.config/code-server/config.yaml```
## Are you interested in submitting a PR for this?
yes

**Comment by jsjoeio** [comment]
Sure, we'd take a PR for this!

**Comment by code-asher** [comment]
Not sure if this was added afterward but we have this: https://github.com/coder/code-server/blob/6a140706642578ea8bd290254457f25d77499956/docs/FAQ.md#L332
