### ISSUE TITLE
[Bug]: /code-server-3.10.2-linux-arm64/lib/node: not found

### ISSUE THREAD

**Issue by TanveerHussain188** [coder/code-server#5247]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: chrome
- Local OS: android 6.0.1
- Remote OS: ubuntu
- Remote Architecture: do not know 
- `code-server --version`: latest 

### Steps to Reproduce

1. install ubuntu from userlink app
2.follow step to install code server
3. launch it

### Expected

vs code will open

### Actual

/code-server-3.10.2-linux-arm64/lib/node: not found 
this error happen

### Logs

please help

### Screenshot/Video

https://ibb.co/bNC8RyY
https://ibb.co/h2tD3sg

### Does this issue happen in VS Code?

- [X] I cannot reproduce this in VS Code.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

please help

**Comment by tanveer188** [comment]
> What happens if install `yarn` and try installing code-server that way?

i dont understand bro

**Comment by blockerpiyush** [comment]
Me too facing Same issue while installing it on android please help

**Comment by jsjoeio** [comment]
@blockerpiyush  can you try this? https://github.com/coder/code-server/issues/5247#issuecomment-1150469500

**Comment by Future-Outlier** [comment]
@jsjoeio , @darkshadow4274 , @T45K 
Can this be solved??
I have a PR in flyte needs this to be solved.
https://github.com/flyteorg/flytekit/pull/1993

**Comment by code-asher** [comment]
If you are running on a platform that is not supported by our GitHub releases then you will need to build code-server yourself or install from `npm`.  Either way, make sure to use the right version of Node (v18 for 4.19.0).

For Android, there is also a Termux version that can be installed.

**Comment by code-asher** [comment]
Ah wait I misread the original comment, the client is Android but the remote is Ubuntu.  If anyone is still running into the issue please feel free to comment.  Make sure to list your architecture and how you are installing code-server!
