### ISSUE TITLE
Multiple environments, IDEs, and users

### ISSUE THREAD

**Issue by bpmct** [coder/code-server#5269]
While we plan on keeping code-server scoped to the VS Code in the browser, we're building an open-source project to manage many remote workspaces.

➡️ On GitHub: [coder/coder](https://cdr.co/coder-github01)

Features:

- Develop over SSH, VS Code Remote, Jetbrains, Jupyter, and code-server
- Create templates for different types of workspaces, share with multiple users
- Onboard users. Users can create multiple workspaces
- Provision environments on VMs, Kubernetes, Docker, AWS, Windows, (anything on [Terraform](https://registry.terraform.io/browse/providers))
- Auto shutdown (or delete) workspaces when they are not in use
- Self-hosted (just like code-server)

The project is still early and feedback is welcome. Feel free to say hi [on Discord](https://discord.gg/n5V46wrbbx) and share your use cases.

**Comment by duongtuan303030** [comment]
![image](https://user-images.githubusercontent.com/80153297/173724327-394c03f6-4798-4c77-9490-7c34cb19fb74.png)

**Comment by MitchTalmadge** [comment]
@duongtuan303030 I don't understand. Can you clarify?

**Comment by duongtuan303030** [comment]
> Great project idea! I like it and I'm excited for the prospects.
> 
> @duongtuan303030 I don't understand. Can you clarify?

@MitchTalmadge code-server is just a web ide that is not platform to add it

and you can run coder in your server :/

**Comment by 81CuongVn** [comment]
oh no i'm really understand in side that great awesome but this time is not nessessary
