### ISSUE TITLE
[Bug]: Can't paste images into code-server

### ISSUE THREAD

**Issue by huangyinhaow** [coder/code-server#5272]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome 99
- Local OS: Windows 10 1804
- Remote OS: Ubuntu 22.0.4
- Remote Architecture: amd64
- `code-server --version`: 4.1.0

### Steps to Reproduce

1. Open Code-server 
2. Install hancel.markdown-image-1.1.22
3. Copy an .png image
4. Ctrl + Alt + V

### Expected

The image is copied into the code-server

### Actual

The code-server pops up a message: "There is not an image in the clipboard."

### Logs

No log.

### Screenshot/Video

![image](https://user-images.githubusercontent.com/64564727/173804858-de3e9037-7f9a-4744-aa00-73e00b4aa618.png)

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

I can't try it on Codespaces, because I do not have access permission.

**Comment by huangyinhaow** [comment]
I have tried many extensions of the same kind and they are all ineffective.

**Comment by jsjoeio** [comment]
Are there any logs in the console?

Have you tried raising an issue with the extension author?

**Comment by huangyinhaow** [comment]
> Are there any logs in the console?
> 
> Have you tried raising an issue with the extension author?

Sorry, but there is no log in the console.

**Comment by huangyinhaow** [comment]
Likely to be an extension issue.
