### ISSUE TITLE
[Bug]: systemctl fails to start the code-server when link: true

### ISSUE THREAD

**Issue by jinPrelude** [coder/code-server#5281]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrone
- Local OS: Ubuntu 20.04 LTS
- Remote OS: Windows 10
- Remote Architecture: amd64
- `code-server --version: 4.4.0
- 

### Steps to Reproduce

1. install code-server using command: `curl -fsSL https://code-server.dev/install.sh | sh -s -- --dry-run`
2. open the config.yaml /.config/code-server/config.yaml
3. add `link: True` and save the config.yaml
4. type command : `sudo systemctl enable --now code-server@$USER`
5. reboot the computer and check the service status by command: `sudo systemctl status code-server@$USER`

### Expected

The active status of the code-server@$USER service should be successfully activated

### Actual

It failed to active. This is the result:
![IMG_9784](https://user-images.githubusercontent.com/16518993/174467811-89eecf9e-5742-4b89-8a98-a2c6f86b0d9f.PNG)

### Logs

I used the command `journalctl -u code-server@$USER` to check the log, And this is what I got :
![IMG_9783](https://user-images.githubusercontent.com/16518993/174467849-ba408fd8-d6ad-485f-9f7b-831da5628c42.PNG)

It seems like systemctl stopped the code-server for some reason, but I can't find out why.

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

Thanks for any advice!

**Comment by jsjoeio** [comment]
Sadly, `--link` is deprecated meaning we won't be releasing any new features or bug fixes. This would fall under that. I wish I could help debug but I'm not sure why `systemctl` is failing. I'll close this but feel free to keep commenting on it and I can rubber-duck the issue with you!
