### ISSUE TITLE
[Feat]: Feature to reload SSL certificate when certificate gets renewed

### ISSUE THREAD

**Issue by imageschool** [coder/code-server#5282]
## What is your suggestion?
Adding a certificate reload feature for code-server

## Why do you want this feature?
My certificate gets automatically renewed every 24h in the Kubernetes cluster.
I want the code-server to automatically pick up a renewed certificate without restarting. (i.e so fix it by reloading)

## Are there any workarounds to get this functionality today?
1. file watch on cert files
2. When cert gets renewed, reload certificate on node

Possibly [this?](https://github.com/nodejs/node/issues/15115)

## Are you interested in submitting a PR for this?
Unfortunately I am not familiar with Node yet

**Comment by code-asher** [comment]
Sorry this fell through the cracks.  It is possible to reload code-server by sending it a `USR2` signal.
