### ISSUE TITLE
IOS / ish install hangs

### ISSUE THREAD

**Issue by robertwatkins** [coder/code-server#5290]
In following the steps here:
https://coder.com/docs/code-server/latest/ios

I get stuck on the installation step. It’s been sitting for over an hour, no progress, no error. I have the latest patches on an IPad Pro

```
iPad-2:~# curl -fsSL https://code-server.dev/install.sh | sh
Alpine Linux v3.14
Installing latest from npm.

sh: NPM_PATH: not found
Installing with npm.

+ npm install -g code-server --unsafe-perm

```

is there a way to provide additional insight or is there a known fix?

**Comment by jsjoeio** [comment]
Can you share more about your issue or what you're seeing?

**Comment by robertwatkins** [comment]
Thanks @jsjoeio , when I run the script 

`curl -fsSL https://code-server.dev/install.sh | sh `

It seems to run (for days if I let it). I open a second terminal session and can see node processes start and stop, but it doesn’t seem to finish. tbh, there’s not much to see because the script itself doesn’t produce any output during this time and I’m not sure if any logging is happening.


==========================
The longer story fwiw

I switched over to running this on RedHat and pointing my iPad to that instance. That approach now has me faced with a limitation of code-server not fully supporting vs code extensions, which is far outside the scope of the (fabulous) ish project. My ultimate goal was to use my iPad to build and test a plugin/extension for a ‘common’ IDE. Turns out that code-server on iPad is not the route that seems to be for me. I really am putting my own barriers in place, which makes this a challenge (don’t pay for hosting, don’t host on my employer’s AWS sandbox (even though this is ultimately for them), use my iPad, don’t use RDP, NoMachine, Only use Open Source (so I can install on an at-home server), etc.)

**Comment by jsjoeio** [comment]
Hmm...I'm trying to thing what else would could do to help you get past this. Pinging the wizard @code-asher - any ideas?

**Comment by code-asher** [comment]
The only thing that comes to mind is to try the `npm install` command directly with more flags.  Something like raising the log levels with `--dd` (verbose) or `--ddd` (silly).

```
npm install -g code-server --unsafe-perm --dd
```

**Comment by code-asher** [comment]
Might be related: https://github.com/ish-app/ish/issues/874

**Comment by code-asher** [comment]
Closing for now since I am not sure there is anything we need to change in code-server.  Happy to reopen if there is something that needs to be fixed.
