### ISSUE TITLE
[Bug]: display language switch failed in 4.5.0

### ISSUE THREAD

**Issue by tgly307** [coder/code-server#5318]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: chrome
- Local OS: windows10
- Remote OS: centOS 7
- Remote Architecture: amd64
- `code-server --version`: 4.5.0

### Steps to Reproduce

1. install language pack via UI
2. change display language by 'config display language' menu
3. restart web UI, but still show English(current), and the language is not changed.

### Expected

switch to language which selected.

### Actual

not change.

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by nosoxo** [comment]
me too

**Comment by aleleba** [comment]
me too

**Comment by coverthesea** [comment]
me too
