### ISSUE TITLE
[Bug]: code-server command isn't working in remote cli

### ISSUE THREAD

**Issue by snublueberry** [coder/code-server#5319]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome 102.0
- Local OS: raspberrypi os 64bit (aarch64)
- Remote OS: One UI 4.1 (Android 12.0)
- `code-server --version`: 4.5.0 (updated from 4.4.0)

### Steps to Reproduce

1. open code-server with systemctl/nginx and connect with https protocol
2. type command code-server [-args] (e.g. code-server --version) in remote cli (non-login bash in code-server)
3. type command code-server [-args] in remote cli (login bash in ssh remote application)

### Expected

Typed command `code-server --version` in ssh remote connection,
```
4.5.0 02b9d7ee856e31d9008d1ff24a175ff03b49010e with Code 1.68.1
```

### Actual

But typed command `code-server --version` in code-server remote cli,
```
/usr/lib/code-server/lib/vscode/bin/remote-cli/code-server: 12: /usr/lib/code-server/lib/vscode/node: not found
```
#
When I added symbolic link in that path as following,
`sudo ln -s /usr/lib/code-server/lib/node /usr/lib/code-server/lib/vscode/node`,

It works in some way (result following) but I think it's just not a good solution.

`code-server --version` (edited)

```
1.68.1
30d9c6cd9483b2cc586687151bcbcd635f373630
arm64
```

And it doesn't print errors when parameters are entered incorrectly. Instead, parameters are ignored and executed program only. In ex, when I used command `code-server --versiom` (m is incorrect), it took just `code-server` and executed it.

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [x] I am using HTTPS.

**Comment by jsjoeio** [comment]
@code-asher any ideas on this one? I'm not sure what would have changed in 4.5.0 that would have caused this.

**Comment by fritterhoff** [comment]
Same problem as here: https://github.com/coder/code-server/issues/5335

**Comment by code-asher** [comment]
Closing as a duplicate.  Thank you for the report!
