### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by GuilhermeSCLima** [coder/code-server#5320]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Mozila Firefox
- Local OS: macOS
- Remote OS: ubuntu
- Remote Architecture: amd64
- `code-server --version`: 4.5.0

### Steps to Reproduce

1. initializate code-server
2. open a project folder
3. run node index.js

### Expected

It was expected that the app run

### Actual

It dosent recognize that the node, or npm is installed

### Screenshot/Video

[Expected](https://pasteboard.co/rzZubCwuFjET.png)
[Actual](https://pasteboard.co/RkarkfvukJsI.png)

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by sent44** [comment]
Did you already try to install nodejs and npm?

**Comment by GuilhermeSCLima** [comment]
> Are you still facing this issue?

Nop, I solved it today, the only thing I needed to do was change Ubuntu version, I don't know why, but that solves the problem, thanks for the help by the way
