### ISSUE TITLE
[Docs]: Where is the code-server Dockerfile? 

### ISSUE THREAD

**Issue by BBQlee** [coder/code-server#5323]
Hi friends, do you hava Dockerfile ? I want to do an image with the “code-server-4.5.0-linux-amd64.tar.gz”, but I do not know how to do the Dockerfile, can you help me pls~

**Comment by AalmanMohd** [comment]
https://hub.docker.com/repository/docker/aalmanmohd/code-server

**Comment by HOKingson** [comment]
> Hi friends, do you hava Dockerfile ? I want to do an image with the “code-server-4.5.0-linux-amd64.tar.gz”, but I do not know how to do the Dockerfile, can you help me pls~
> 
> ## What is your suggestion?
> ## How will this improve the docs?
> ## Are you interested in submitting a PR for this?

In the [ci](https://github.com/coder/code-server/tree/main/ci)/release-image/

**Comment by code-asher** [comment]
Closing as stale but feel free to comment if you come back to this.
