### ISSUE TITLE
[Bug]: Webview error

### ISSUE THREAD

**Issue by gogobd** [coder/code-server#5338]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Brave
- Local OS: MacOS Monterey 12.4
- Remote OS: MacOS Monterey 12.4
- Remote Architecture: platform=linux/amd64
- `code-server --version`: `/root/.local/lib/code-server-4.5.0/lib/vscode/bin/remote-cli/code-server: 12: /root/.local/lib/code-server-4.5.0/lib/vscode/node: not found`

### Steps to Reproduce

1. Open code server in Brave Browser
2. Log in
3. Read the error message

### Expected

Code server should run with all features enabled

### Actual

All sorts of random problems, including broken Image display

### Logs

Error loading webview: Error: Could not register service workers: SecurityError: Failed to register a ServiceWorker for scope ('https://localhost:8080/stable-30d9c6cd9483b2cc586687151bcbcd635f373630/static/out/vs/workbench/contrib/webview/browser/pre/') with script ('https://localhost:8080/stable-30d9c6cd9483b2cc586687151bcbcd635f373630/static/out/vs/workbench/contrib/webview/browser/pre/service-worker.js?v=4&vscode-resource-base-authority=vscode-resource.vscode-cdn.net&remoteAuthority=localhost:8080'): An SSL certificate error occurred when fetching the script..

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

"This certificate is not trusted, expires ..." and it says the time of installation

**Comment by gogobd** [comment]
Maybe related to https://github.com/coder/code-server/issues/4800

**Comment by benz0li** [comment]
@gogobd Almost certainly there is something wrong with your certificates and/or setup.

@jsjoeio This is not a `code-server` bug – with the exception of `/root/.local/lib/code-server-4.5.0/lib/vscode/bin/remote-cli/code-server: 12: /root/.local/lib/code-server-4.5.0/lib/vscode/node: not found` (👉 #5335).

**Comment by benz0li** [comment]
@gogobd Have a look at [mkcert](https://github.com/FiloSottile/mkcert) for making locally-trusted development certificates.

**Comment by gogobd** [comment]
I am starting code-server with `/usr/local/bin/code-server --cert --bind-addr 0.0.0.0:8080 /app` so creating proper certificates should happen automagically...

**Comment by gogobd** [comment]
```
FROM --platform=linux/amd64 debian:bullseye-slim
  
# Install system dependencies
RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    curl \
    wget \
    git \
    screen \
    unzip \
    vim \
    procps \
    locales \
    python3-pip \
 && apt-get clean

# Python unicode issues
RUN sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && locale-gen
ENV LC_ALL=en_US.UTF-8
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US.UTF-8

# Code server
# https://github.com/coder/code-server/releases
ARG VERSION=4.5.0
RUN mkdir -p ~/.local/lib ~/.local/bin
RUN curl -sfL https://github.com/cdr/code-server/releases/download/v$VERSION/code-server-$VERSION-linux-amd64.tar.gz | tar -C ~/.local/lib -xz
RUN mv ~/.local/lib/code-server-$VERSION-linux-amd64 ~/.local/lib/code-server-$VERSION
RUN ln -s ~/.local/lib/code-server-$VERSION/bin/code-server /usr/local/bin/code-server

WORKDIR /app
ENV SHELL /bin/bash
CMD /usr/local/bin/code-server --cert --bind-addr 0.0.0.0:8080 /app
```

**Comment by benz0li** [comment]
> I am starting code-server with `/usr/local/bin/code-server --cert --bind-addr 0.0.0.0:8080 /app` so creating proper certificates should happen automagically...

```zsh
$ code-server --help
[...]
--cert                   Path to certificate. A self signed certificate is generated if none is provided.
[...]
```

ℹ️ When using self-signed certificates, its root CA needs to be added to the _trust store_.  
👉 See also https://github.com/FiloSottile/mkcert#supported-root-stores

**Comment by ericzhucode** [comment]
> Error loading webview: Error: Could not register service workers: SecurityError: Failed to register a ServiceWorker for scope
This error has nothing to do but with your certificate and the protocol(http/https) you use. Webview is based on Service Work and Service Work needs https to run（A rule determined by browser）
1.As benz0li said above, if you have used --cert param then code-server generates a self-signed cert, if you use https://ip:port to open code server at this point, since no root CA in your browser can verify this self-signed cert. You can either add this self signed cert to trust store or buy a real cert from public organizations.
2.I think your can use the following params to open your browser and the cert error should be escaped（Not secure in public network environment but easy to use if you are using code-server on your local machine）
You need to replace ip and port by yourself
`start chrome http://192.168.142.129:8080 --ignore-certificate-errors --unsafely-treat-insecure-origin-as-secure=http://192.168.142.129:8080`

**Comment by benz0li** [comment]
@gogobd Did you include the certificates generated by `mkcert localhost` in your Docker image?

**Comment by gogobd** [comment]
No, i want code server to generate its own certificates on startup.

**Comment by benz0li** [comment]
> No, i want code server to generate its own certificates on startup.

Then the root CA from `mkcert` make no difference. Because you don't use the certificates generated by `mkcert` for `localhost`.

**Comment by benz0li** [comment]
If you want to use the certificates generated by code-server, you must add the root CA from the Dockerfile to your _trust store_.

**Comment by ericzhucode** [comment]
> > No, i want code server to generate its own certificates on startup.
> 
> Then the root CA from `mkcert` make no difference. Because you don't use the certificates generated by `mkcert` for `localhost`.

Agree, I think we need to generate a cert from mkcert which can be verified by your local CA. Then you use ./code-server --cert xxx --cert-key xxx instead of using code server generated self signed cert which can't be verified by your local CA

**Comment by gogobd** [comment]
So whenever someone uses the --cert option to let code server generate certificates on startup it actually breaks a lot of features? This doesn't make much sense to me at the moment...

**Comment by gogobd** [comment]
Could I retrieve the generated root certificates from my container and include them in my hosts trust store?

**Comment by benz0li** [comment]
> So whenever someone uses the --cert option to let code server generate certificates on startup it actually breaks a lot of features? This doesn't make much sense to me at the moment...

No. This seems to be a limitation of Brave with self-signed certificates.

**Comment by benz0li** [comment]
> Could I retrieve the generated root certificates from my container and include them in my hosts trust store?

I do not know. It's better to use `mkcert` and do it the other way around.

QED

**Comment by gogobd** [comment]
I upgraded to 4.9.0 and this issue is still not solved; the certificate that is being generated on startup doesn't work in Brave.

**Comment by jsjoeio** [comment]
@gogobd are you using Ubuntu 22.04 by chance?

**Comment by gogobd** [comment]
I found a way to get Brave to work on MacOS.
I used openssl s_client -connect localhost:8080 to retrieve the auto-generated (self-signed) certificate from the running code-server instance. I created a file with the extension .crt so I could import that key into Keychain Access.app. Then I used the search function in Keychain Access and double-clicked the new certificate to select "Always trust".
This enables all features other browsers don't seem to have an issue with - images are shown, Webviews seem to work ok, Jupyter Notebooks run.

I am cross-posting this (see https://github.com/coder/code-server/issues/4800).

**Comment by benz0li** [comment]
@gogobd Please close the issue when it is resolved.

**Comment by bastienjalbert** [comment]
> I found a way to get Brave to work on MacOS. I used openssl s_client -connect localhost:8080 to retrieve the auto-generated (self-signed) certificate from the running code-server instance. I created a file with the extension .crt so I could import that key into Keychain Access.app. Then I used the search function in Keychain Access and double-clicked the new certificate to select "Always trust". This enables all features other browsers don't seem to have an issue with - images are shown, Webviews seem to work ok, Jupyter Notebooks run.
> 
> I am cross-posting this (see [#4800](https://github.com/coder/code-server/issues/4800)).

The solution worked for me, but you have to generate a certificate with subjectAltName (and your served dns), like this :
`openssl req -x509 -nodes -days 3650 -newkey rsa:4096 -sha256 -keyout /tmp/self-signed.key -out /tmp/self-signed.crt -subj '/CN=mydns:9443'  -addext "subjectAltName=DNS:mydns:9443,DNS:mydns"` otherwise Brave'll still ask for some kind of internal validation
