### ISSUE TITLE
[Bug]: prettier and some code formatting extensions works unnormal

### ISSUE THREAD

**Issue by passerbyo** [coder/code-server#5342]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser:
- Local OS:debian
- Remote OS:windows 10
- Remote Architecture:windows 10
- `code-server --version`:latest

### Steps to Reproduce

1. open code-server
2. install extension
3. use extension

### Expected

extensions work normal just like vscode exe

### Actual

There is no button to use extensions, and the extension does not work.

### Logs

no

### Screenshot/Video

no

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

no

**Comment by jsjoeio** [comment]
Can you be more specific in your repro steps or share screenshots or logs? That would help a lot!

**Comment by code-asher** [comment]
Closing as stale but feel free to comment if you come back to this.  Sounds most likely to be an extension issue, or maybe something in VS Code core.
