### ISSUE TITLE
[Bug]: "Ctrl+Click" /"Go to definition" not working/missing

### ISSUE THREAD

**Issue by jneuhauser** [coder/code-server#5345]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome Version 103.0.5060.114 (Offizieller Build) (64-Bit)
- Local OS: Windows 10 21H1
- Remote OS: Debian 11 Bullseye
- Remote Architecture: x86_64
- `code-server --version`: 4.5.0 02b9d7ee856e31d9008d1ff24a175ff03b49010e with Code 1.68.1

### Steps to Reproduce

1. open code-server
2. open a project with c/c++ source files
3. try to follow a function usage to function definition by "Ctrl+Click"/"Go to definition" not working/missing

### Expected

code should open/jump to the function definition

### Actual

nothing

### Logs

no relevant output

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by jneuhauser** [comment]
Sorry, installing https://github.com/microsoft/vscode-cpptools manually does bring back this functionality.

**Comment by wqhcug** [comment]
i meet the same problem in python , code jump not working.

**Comment by 123hicxs** [comment]
I have also encountered this problem in the Python environment. Is there any solution?

**Comment by code-asher** [comment]
I am not sure about Python, but there is some discussion here: https://github.com/coder/code-server/discussions/4348

**Comment by 123hicxs** [comment]
I found the problem yesterday, it's due to the Balance plugin, as it's not open source. You can use the right plugin instead.
