### ISSUE TITLE
Add verification code when entering password

### ISSUE THREAD

**Issue by wkmyws** [coder/code-server#5349]
## What is your suggestion?

On the login page, we can still continue to try after entering the wrong password many times. 

So it is easy to crack passwords through dictionary enumeration.

Could we enable the verification code mechanism after entering the wrong password many times?

**Comment by jsjoeio** [comment]
There is some [timeout/login attempt logic](https://github.com/coder/code-server/blob/main/test/unit/node/routes/login.test.ts#L11-L43) which I think prevents this slightly.
