### ISSUE TITLE
[Bug]: 提取扩展时出错。Server returned 502

### ISSUE THREAD

**Issue by n-WN** [coder/code-server#5372]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser:Firefox 102
- Local OS:Win11
- Remote OS:Ubuntu 22.04
- Remote Architecture:amd64
- `code-server --version`:New

### Steps to Reproduce

1. new
2.(1)Theme:aye (2)Chinese (Simplified) (简体中文) Language Pack for Visual Studio Code
3.Click the extension icon on the left to search for an extension

### Expected

chinese：显示拓展
English: Correctly display the expansion of the search, (the problem now is that nothing can be found

### Actual

提取扩展时出错。Server returned 502

### Logs

null

### Screenshot/Video

null

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

null

**Comment by benz0li** [comment]
See https://github.com/eclipse/openvsx/issues/497 and https://github.com/EclipseFdn/open-vsx.org/issues/1141

**Comment by n-WN** [comment]
> 见 [eclipse/openvsx#497 ](https://github.com/eclipse/openvsx/issues/497)和 [EclipseFdn/open-vsx.org#1141 ](https://github.com/EclipseFdn/open-vsx.org/issues/1141)

I read these two posts but it didn't solve it, and the post didn't mention how to solve it

**Comment by benz0li** [comment]
> I read these two posts but it didn't solve it, and the post didn't mention how to solve it

There is nothing you or devs @coder could do about this. It's a problem with the deployment of https://open-vsx.org which @eclipsewebmaster is currently investigating.

**Comment by benz0li** [comment]
ℹ️ code-server uses the [Open-VSX extension gallery](https://open-vsx.org/).

(https://github.com/coder/code-server/blob/main/docs/FAQ.md#why-cant-code-server-use-microsofts-extension-marketplace)

**Comment by n-WN** [comment]
Ok thanks, I will install offline first. Check it out tomorrow. Another question, can the address of this library be replaced with the extension library server used by the local VScode. It might be weird to read, I don't know English, I'm using a translator, sor

**Comment by benz0li** [comment]
> can the address of this library be replaced with the extension library server used by the local VScode

No. That's against Microsofts [Terms of Service](https://cdn.vsassets.io/v/M146_20190123.39/_content/Microsoft-Visual-Studio-Marketplace-Terms-of-Use.pdf):

> Marketplace Offerings are intended for use only with Visual Studio Products and Services, and you may only install and use Marketplace Offerings with Visual Studio Products and Services.

**Comment by n-WN** [comment]
ok，ty

**Comment by jsjoeio** [comment]
@benz0li thanks for hopping on this 🙌🏼 Looks like open-vsx was down yesterday. I'm going to close this since it's up now.
