### ISSUE TITLE
[Docs]: Requirements clearification

### ISSUE THREAD

**Issue by BelphegorPrime** [coder/code-server#5374]
## What is your suggestion?
In the requirements section of the README.md stands `TL;DR: Linux machine with WebSockets enabled, 1 GB RAM, and 2 CPUs`
But I think most machines do not have 2 CPUs. They have CPU-Cores.
## How will this improve the docs?
Clearification of requirements
## Are you interested in submitting a PR for this?
yes

**Comment by balajib-b** [comment]
@BelphegorPrime as far servers are considered, they never give you the count of virtual cores. for the full allotment and usage, cloud providers mention CPU instead of cores. Requesting you to check aws, gcloud, OCI etc.... the terminology used is correct as far as cloud industry is considered.

**Comment by BelphegorPrime** [comment]
@balajib-b is it questinable that it is cloud first? I haven`t read something that specific in the docs. So a normal user with homeserver that hosts it his self could be confused by current wording.
