### ISSUE TITLE
[Feat]: Add container lifecycle hook to helm chart

### ISSUE THREAD

**Issue by inerplat** [coder/code-server#5382]
## What is your suggestion?

Add container lifecycle hook to helm chart of code-server deployment.

## Why do you want this feature?

When the code-server is restarted in kubernetes, all data in the area where the persistent volume is not mounted is lost.

How about adding a lifecycle hook like postStart for small configuration or script codes to manage without PV?

## Are there any workarounds to get this functionality today?

Of course, I personally fork the helm chart of this project and use it.

Edit the chart as below:
https://github.com/inerplat/code-server/blob/main/ci/helm-chart/templates/deployment.yaml#L65-L75

It can inject settings via `values.yaml`:
https://github.com/inerplat/code-server/blob/main/ci/helm-chart/values.yaml#L130-L137

## Are you interested in submitting a PR for this?

Yes

**Comment by jsjoeio** [comment]
cc @bpmct any thoughts on this?

**Comment by bpmct** [comment]
This seems reasonable to accept upstream. I'm happy to test it!

**Comment by jsjoeio** [comment]
Fixed via https://github.com/coder/code-server/pull/5397
