### ISSUE TITLE
[Bug]: Selection doesn't copy to X selection (clipboard)

### ISSUE THREAD

**Issue by UnderSampled** [coder/code-server#5387]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Firefox 91.11.0esr
- Local OS: Debian 11.4 (bullseye) with KDE through Xorg
- Remote OS: (same)
- Remote Architecture: amd64
- `code-server --version`: 4.5.1 97d170331b51ee75c8e4bbdab23c755e3eeaaa8c with Code 1.68.1

### Steps to Reproduce

1. Open a document or terminal in code-server in a browser through the X Window system
2. Select some text
3. Use middle-click to paste

### Expected

In X windowing environments, middle clicking should paste the text that was selected at the location under the mouse cursor.

### Actual

Text is pasted upon middle click, however it is not the text that was selected within the code-server UI. Instead, it pastes the most recently selected text from outside the page, including from other tabs within the same browser.

**Comment by jsjoeio** [comment]
Can you reproduce this in Codespaces or github.dev?

**Comment by UnderSampled** [comment]
I just went to github.dev, it does the same thing.

**Comment by jsjoeio** [comment]
great! can you open an issue upstream then?
