### ISSUE TITLE
[Bug]: can't install raspberry pi via yarn

### ISSUE THREAD

**Issue by panacanadianpeep** [coder/code-server#5419]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome
- Local OS: Raspberry pi OS
- Remote OS:  Ipad OS
- Remote Architecture: N/A
- `code-server --version`: N/A

### Steps to Reproduce

1.  open code-server in raspberry pi
2. download using yarn message
3. Should recieve a error message

### Expected

Downloads sussefully without any issue

### Actual

Doesn't download succesfully using yarn methods or any other methods

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by jsjoeio** [comment]
Can you please provide some screenshots, videos and logs so we can help you fix this?

**Comment by panacanadianpeep** [comment]
Here are the screenshots:

![2022-08-06-124807_1024x768_scrot](https://user-images.githubusercontent.com/23111532/183245813-54e568cf-c078-4233-a332-dbc8881a697e.png)
![2022-08-06-124835_1024x768_scrot](https://user-images.githubusercontent.com/23111532/183245814-9927883e-1ba7-47a8-b6aa-4dacc2f3d6cd.png)
![2022-08-06-124838_1024x768_scrot](https://user-images.githubusercontent.com/23111532/183245815-a3dd5b89-09fb-45c6-9f47-3bc0e78ee33a.png)
![2022-08-06-124839_1024x768_scrot](https://user-images.githubusercontent.com/23111532/183245816-ce4e60dd-7bab-44ec-8063-f17b7571a88f.png)
![2022-08-06-124841_1024x768_scrot](https://user-images.githubusercontent.com/23111532/183245817-aaec1247-4203-4ea7-a1c1-a967fc6397ca.png)
![2022-08-06-124918_1024x768_scrot](https://user-images.githubusercontent.com/23111532/183245818-294619ed-984f-411f-b913-b67390f6ca4b.png)
![2022-08-06-124920_1024x768_scrot](https://user-images.githubusercontent.com/23111532/183245819-3423fcfb-c9ac-4771-b196-1d73213ec7a5.png)
![2022-08-06-124921_1024x768_scrot](https://user-images.githubusercontent.com/23111532/183245820-262d7cc3-14ab-4810-bd1b-319e64e4fb07.png)
![2022-08-06-124922_1024x768_scrot](https://user-images.githubusercontent.com/23111532/183245821-5128b0ac-8d07-465b-b53b-4f9a8f8b00c6.png)
![2022-08-06-124924_1024x768_scrot](https://user-images.githubusercontent.com/23111532/183245823-560e1156-4832-4042-aa49-ae4c81953811.png)
![2022-08-06-124933_1024x768_scrot](https://user-images.githubusercontent.com/23111532/183245824-583b253b-9ce2-4cd6-b28e-b15f09691fd1.png)
![2022-08-06-124937_1024x768_scrot](https://user-images.githubusercontent.com/23111532/183245825-1b1c68d6-8d76-4737-9ca5-2a6be8e6ca47.png)
![2022-08-06-124939_1024x768_scrot](https://user-images.githubusercontent.com/23111532/183245826-5fd04744-1040-4be5-8807-56478ed95128.png)
![2022-08-06-124940_1024x768_scrot](https://user-images.githubusercontent.com/23111532/183245829-54dbe500-f86f-4ee5-ad47-f5a4961caab7.png)
![2022-08-06-124947_1024x768_scrot](https://user-images.githubusercontent.com/23111532/183245832-6bb2ae81-5a1e-4060-9fcb-603cecafea4c.png)
![2022-08-06-124949_1024x768_scrot](https://user-images.githubusercontent.com/23111532/183245833-d910e786-5fed-4f19-85f7-c37cca846af0.png)
![2022-08-06-124951_1024x768_scrot](https://user-images.githubusercontent.com/23111532/183245836-96489ae3-0e7f-49e4-a0ee-5adc3e8c011d.png)
![2022-08-06-124952_1024x768_scrot](https://user-images.githubusercontent.com/23111532/183245838-e37b0ef3-4202-46f6-a6e8-06a63fe5decb.png)
![2022-08-06-125003_1024x768_scrot](https://user-images.githubusercontent.com/23111532/183245839-fab1b73b-2b3f-45ce-a098-4d6b8a51db81.png)

Also, how do I open the full logs on a raspberry pi? The folder which the logs are in seems to be restricted...

**Comment by jsjoeio** [comment]
Did you try downgrading to Node v16 and trying that way? 

Alternatively you can try `--ignore-engines` with the `yarn` command but code-server may not work since we don't advise using versions of Node greater than 16

**Comment by code-asher** [comment]
Closing as stale but feel free to comment if you come back to this.
