### ISSUE TITLE
[Docs]: Documentation for unix socket deployment?

### ISSUE THREAD

**Issue by vsoch** [coder/code-server#5423]
Hi! I'm not sure if this is possible because I can't find it - but I'm looking to run the container and instead of specifying a hostname/port, I want to specify a `--socket` instead (akin to how jupyter notebook does it). Is there support/documentation for this? The use case is running on remote servers that don't allow you to map ports (sockets work here!) Thank you!

**Comment by jsjoeio** [comment]
@code-asher is this possible?

**Comment by code-asher** [comment]
Run our Docker container but use a socket instead of a port?  If you put the socket in some mounted directory you will be able to access it from the host.  For example:

```
$ docker run -it --name code-server
  -v "$HOME/.config:/home/coder/.config" \
  -v "$PWD:/home/coder/project" \
  -u "$(id -u):$(id -g)" \
  -e "DOCKER_USER=$USER" \
  codercom/code-server:latest --socket /home/coder/.config/code-server.sock
$ curl --unix-socket ~/.config/code-server.sock http://localhost/healthz
{"status":"alive","lastHeartbeat":1660157136931}
```

You might want to use a separate directory instead of just putting it in `.config` like I did here though.

**Comment by vsoch** [comment]
Nice I’ll try this out and report back! It’s a personal project so apologies in advance if it takes me a little bit.

**Comment by vsoch** [comment]
Ah but one quick question - this relies on the docker --socket flag to get working? That would work for development, but ultimately I want to run on HPC with Singularity so should I look into similar functionality for that container technology? :question:

**Comment by code-asher** [comment]
The `--socket` flag here is passed to code-server, not Docker.

**Comment by vsoch** [comment]
It worked beautifully! First try! *chef's kiss* :kissing_heart: https://twitter.com/vsoch/status/1558326497563160577

Thank you!
