### ISSUE TITLE
[Feat]: Leverage "proxy-domain" in the "Ports" panel

### ISSUE THREAD

**Issue by bpmct** [coder/code-server#5458]
## What is your suggestion?

VS Code Remote, Gitpod, and Codespaces have a lovely panel to detect and access ports via "Ports." Demonstration:

https://user-images.githubusercontent.com/22407953/184697035-7a75ac07-4130-4ec2-936b-ecfb719dcc4c.mov

code-server has a lesser-known ["proxy-domain" feature](https://coder.com/docs/code-server/latest/guide#using-a-subdomain) which also allows you to access running ports running on the code-server host via a subdomain pointed to code-server (e.g. `https://8080.subdomain.coder.com`). 

What if when a user runs an app on port 3000, code-server detects it and adds to "Ports". Also, what if you clicked "localhost:3000" from the code-server terminal, it actually goes to the proper feature.

## Why do you want this feature?

Feature parity with SaaS solutions. Also, with a minor change, this would work pretty well with [Coder](https://github.com/coder/coder) once [coder/coder#1624](https://github.com/coder/coder/issues/1624) is completed.

Although code-servers proxy wouldn't be directly used, Coder's proxy be and it would "just work." Right now, however, the proxy domain expects the port to be the only part of the subdomain. (e.g `8080.the-rest` vs. `8080-other-stuff.the-rest`)

```hcl
# inside a Coder template
# see https://coder.com/docs/coder-oss/latest/templates/
resource "coder_agent" "main" {
    arch          = "amd64"
    os            = "linux"
    startup_script = <<EOF
    #!/bin/sh
    # install and start code-server
    curl -fsSL https://code-server.dev/install.sh | sh
    # set proxy-domain to the URL to access a port from a workpace inside Coder itself
    code-server --auth none --port 13337 --proxy-domain=[PORT]-main-${data.coder_workspace.me.name}-${data.coder_workspace.me.owner}.coder.example.com
    EOF
}
```

## Are there any workarounds to get this functionality today?

Navigating to the URL directly.

## Are you interested in submitting a PR for this?

I wouldn't know where to start :(

**Comment by jsjoeio** [comment]
First goal of this issue is to figure out how to get the proxy domain code from vscode working inside code-server

**Comment by jsjoeio** [comment]
Closed via https://github.com/coder/code-server/pull/5673
