### ISSUE TITLE
[Feat]: Upgrade vscode to 1.70.2

### ISSUE THREAD

**Issue by balajib-b** [coder/code-server#5470]
## What is your suggestion?
Upgrade vscode to 1.70.2

**Comment by balajib-b** [comment]
@jsjoeio @code-asher 1.70.2 is released

**Comment by bala** [comment]
@jsjoeio @code-asher [contributing guide](https://coder.com/docs/code-server/latest/CONTRIBUTING) Shall I try giving PR based on this contributing guide?

**Comment by jsjoeio** [comment]
>  can we have it along with August 2022?

I can add it in. 

> @jsjoeio @code-asher [contributing guide](https://coder.com/docs/code-server/latest/CONTRIBUTING) Shall I try giving PR based on this contributing guide?

These updates are tough because they require more context than other parts of the codebase. I wouldn't recommend it personally but up to you!

**Comment by fritterhoff** [comment]
@jsjoeio @code-asher I think porting the latest patches to 1.70.2 should be no problem. Seems like they only patched files that are note affected by the code-server patches. (https://github.com/microsoft/vscode/compare/1.70.1...1.70.2)

**Comment by jsjoeio** [comment]
Ah, I didn't consider the minor vs. patch - good points! @balajib-b totally up to you then! Go for it if you're feeling inspired - and let us know how we can help!
