### ISSUE TITLE
[Bug]: Problem opening .ipynb files (Jupyter Notebook)

### ISSUE THREAD

**Issue by c-dasq** [coder/code-server#5475]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Microsoft Edge / Chrome / Firefox / Vivaldi / Safari
- Local OS: Windows 10.0.19044.1826 / macOS Big Sur 11.6.8
- Remote OS: Raspberry Pi OS Lite (64-bit) 2022-04-04 (Kernel: 5.15 | Debian: 11 'bullseye')
- Remote Architecture: arm64
- `code-server --version`: 4.5.2

### Steps to Reproduce

1.  open code-server
2. try to open .ipynb file
3. trying to create an .ipynb file

### Expected

The file should open and be viewable

### Actual

Code-server keeps trying to open the file, or creating the file, never finishes loading on screen.

### Screenshot/Video

![image](https://user-images.githubusercontent.com/13774380/185479104-1b2317eb-9353-4582-9f50-3737ec1bb7b7.png)

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by jsjoeio** [comment]
Can you please complete the bug report template?

**Comment by wolframalpha** [comment]
same issue here

**Comment by jsjoeio** [comment]
I cannot reproduce locally. I'm testing using the the v4.6.0 release candidate

<img width="1712" alt="image" src="https://user-images.githubusercontent.com/3806031/185654881-7336b7ce-5574-4d4e-8d00-6a286f3f8302.png">


@wolframalpha do you see any logs in the console? are you using a reverse proxy?

**Comment by Emporea** [comment]
#5334 ?

**Comment by Emporea** [comment]
Will test with 4.6.0 as soon the docker image is out.

**Comment by jsjoeio** [comment]
@Emporea should be out now!

**Comment by Emporea** [comment]
I am really sorry, but this issue indeed still persists for me on 4.6.0.
4.4.0 is still the last version where this does not occur.

**Comment by Emporea** [comment]
Also happens on Firefox Android.
![Screenshot_20220819-232822_Fennec~2](https://user-images.githubusercontent.com/21969523/185710040-f5454c4f-b9b2-402c-a5b3-01cbef6c884a.png)

**Comment by jsjoeio** [comment]
@Emporea thanks for being quick to test! That is sad indeed. 

> I am using nginx reverse proxy.
> I could try to test it without a proxy tomorrow.

That would be helpful!

@code-asher are you able to reproduce?

**Comment by Emporea** [comment]
So I tested without reverse proxy and without https and now it doesn't even open on 4.4.0.
But this is probably because I used http, right?

**Comment by wolframalpha** [comment]
> I cannot reproduce locally. I'm testing using the the v4.6.0 release candidate
> 
> <img alt="image" width="1712" src="https://user-images.githubusercontent.com/3806031/185654881-7336b7ce-5574-4d4e-8d00-6a286f3f8302.png">
> 
> @wolframalpha do you see any logs in the console? are you using a reverse proxy?

The output from the log(window) shows these errors, can you please tell which specific logs you need 
<img width="1086" alt="image" src="https://user-images.githubusercontent.com/12759375/185735391-879166e8-9ab5-40cb-899b-2e92d89707b7.png">

And, yes the machine is behind a reverse proxy but can you please tell how is that related to extentions like jupyter and python(intellisense) not working as expected ?

**Comment by code-asher** [comment]
I was not able to reproduce with the `codercom/code-server:4.6.0` Docker image through Firefox (version 91.11.0esr).

@wolframalpha "Can't compute sha-256" happens when `crypto.subtle` is not available which probably means the browser does not support it.  Could you post your browser and browser version?  Thanks!

@c-dasq and @Emporea could you confirm whether you see similar errors in the browser console or the `Log (Window)` output?  (Ideally post the full output.)  Thank you!  It would also be helpful to check the network tab in the browser dev tools to see if anything is failing to load or hanging (I also recommend checking the "disable cache" box in the network tab to make sure it is not a caching issue).

https://developer.mozilla.org/en-US/docs/Web/API/Crypto/subtle

**Comment by SoutherLea** [comment]
same issue

code-server: v4.5.1
Code: 1.68.1
Commit: 30d9c6cd9483b2cc586687151bcbcd635f373630
Date: 2022-07-19T16:29:15.252Z
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36

**Comment by c-dasq** [comment]
Hi all, I was doing some tests, running code-server on two virtual machines with Debian v11.4 (clean install) and Ubuntu Server 22.04.1 (clean install), connected from Vivaldi 5.4 2753.40 (clean install) and always **without HTTPS**.

I found something curious, the bug only occurs when bind-addr is 0.0.0.0.0:8080 (whether or not to use password),

When bind-addr is 127.0.0.1.1:8080 and I use port forwarding with ssh (whether I use password or not); everything works normally:

![code-server-port-forwarding-ssh](https://user-images.githubusercontent.com/13774380/187076300-cb4533ef-788e-4d3e-8404-a7b424a51bd7.png)

Apparently I must have PIP installed on the virtual machines as well.

**Comment by benz0li** [comment]
I could not reproduce this issue at https://demo.jupyter.b-data.ch (OS: [Debian bullseye](https://hub.docker.com/_/debian), Arch: amd64, code-server: v4.6.0); with none of my custom docker images.

I could not reproduce it running my custom docker images locally (OS: [Debian bullseye](https://hub.docker.com/_/debian), Arch: arm64, code-server: v4.6.0) either.

ℹ️ Extension versions: `ms-toolsai.jupyter@2022.8.1002170547`, `ms-python.python@v2022.12.1`.

- Web Browser: Firefox 104.0 (64-bit)
- Local OS: macOS 12.5.1 (Monterey)

**Comment by benz0li** [comment]
> Hi all, I was doing some tests, running code-server on two virtual machines with Debian v11.4 (clean install) and Ubuntu Server 22.04.1 (clean install), connected from Vivaldi 5.4 2753.40 (clean install) and always **without HTTPS**.

code-server is required to be served via HTTPS to run code using service workers: [Using Service Workers - Web APIs | MDN](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers#setting_up_to_play_with_service_workers)

> I found something curious, the bug only occurs when bind-addr is 0.0.0.0.0:8080 (whether or not to use password),
> 
> When bind-addr is 127.0.0.1.1:8080 and I use port forwarding with ssh (whether I use password or not); everything works normally:

`localhost` is considered a secure origin by browsers as well.  
ℹ️ This seems to apply for `127.0.0.1`, the IP of `localhost`, too.

**Comment by Emporea** [comment]
@benz0li Sorry but i think your input is nonsense and makes me angry for sum reason. we get that you cant reproduce any of those issues we are facing.

**Comment by benz0li** [comment]
> @benz0li [...] We get that you can't reproduce any of those issues we are facing. This always feels like you don't believe me or think that I am stupid or something.

I do not think you are stupid. I do not know whether you are a n00b or not.

> I can reproduce with the instance you provided. With a fresh installed Fedora 36 and Firefox 104 without any modifications like add-ons etc.

@Emporea Please post the output from the browsers web console when you reload the page and open the Jupyter Notebook* using my deployment.
👉 [Firefox] Tools > Browser Tools > Web Developer Tools: Console || Keyboard shortcut `Ctrl+Shift+K`

*Please open `about:debugging` (> This Firefox) and `about:serviceworkers` in two separate browser tabs while doing so.  
ℹ️ There should be two Service Workers (and two Other Workers) after spinning up code-server.

**Comment by wolframalpha** [comment]
> I was not able to reproduce with the `codercom/code-server:4.6.0` Docker image through Firefox (version 91.11.0esr).
> 
> @wolframalpha "Can't compute sha-256" happens when `crypto.subtle` is not available which probably means the browser does not support it. Could you post your browser and browser version? Thanks!
> 
> @c-dasq and @Emporea could you confirm whether you see similar errors in the browser console or the `Log (Window)` output? (Ideally post the full output.) Thank you! It would also be helpful to check the network tab in the browser dev tools to see if anything is failing to load or hanging (I also recommend checking the "disable cache" box in the network tab to make sure it is not a caching issue).
> 
> https://developer.mozilla.org/en-US/docs/Web/API/Crypto/subtle

@code-asher I am using the latest version of chrome. 
There's an error in the output Log window, do you think that jupyter interface not loading might be an issue because it's not able to reach the URL?
`[2022-08-31 10:20:25.324] [window] [error] RequestService#request (browser) - error https://open-vsx.org/vscode/gallery/extensionquery {}`

![image](https://user-images.githubusercontent.com/12759375/187596686-876c1363-a207-460c-8d0a-576f08c3ee31.png)

**Comment by benz0li** [comment]
@wolframalpha In your case: Another problem is, that you are not serving code-server via HTTPS. See https://github.com/coder/code-server/issues/5475#issuecomment-1229529712.

**Comment by Antonet99** [comment]
Same issue here, under the same condition of OP. Can install every extension and every package, but the notebook seems loading forever.

**Comment by benz0li** [comment]
@c-dasq If https://github.com/coder/code-server/issues/5475#issuecomment-1229529712 seems reasonable to you and did resolve this [your] issue, please close.

**Comment by Emporea** [comment]
Interesting that you dont care about all the other people @benz0li

**Comment by benz0li** [comment]
I do care.

@Emporea Please post the output from the browser's web console when you reload the page and open the Jupyter Notebook* using my deployment.
👉 [Firefox] Tools > Browser Tools > Web Developer Tools: Console || Keyboard shortcut `Ctrl+Shift+K`

*Please open `about:debugging` (> This Firefox) and `about:serviceworkers` in two separate browser tabs while doing so.  
ℹ️ There should be two Service Workers (and two Other Workers) after spinning up code-server.

**Comment by code-asher** [comment]
There is supposed to be a popup warning on startup when using insecure contexts saying that certain functionality will not work because the browser does not allow it but we should instead make that popup appear at the point of trying to perform an action so it is more obvious why a certain feature is not working.  So instead we would make it show every time a web view fails to open, when paste fails, and other things that will fail due to insecure contexts.  In the specific case of web views it might be best to show that message right in the web view instead of a popup.

**Comment by Emporea** [comment]
@benz0li Have you changed anything with your deployment? I cant reproduce the error any more, its working with your deployment. This confuses me even more cause now it has to be my deployment. But my deployment works for you.
Gosh. Help.


Output of Console when refreshing my deployment:
```
Uncaught (in promise) Error: Unable to write file 'vscode-log:/20220831T185932/window.log' (Error: IndexedDB database 'vscode-web-db' is closed.)
    _ files.ts:1156
    writeFile fileService.ts:404
    _log fileLog.ts:106
    consume async.ts:637
    queue async.ts:628
    queue async.ts:626
    _log fileLog.ts:94
    error fileLog.ts:69
    error log.ts:435
    _log bufferLog.ts:53
    error bufferLog.ts:76
    handleUnexpectedError workbench.ts:129
    registerErrorHandler workbench.ts:87
    onUnexpectedError errors.ts:65
    A errors.ts:84
    registerErrorHandler workbench.ts:80
    registerErrorHandler workbench.ts:77
    M workbench.ts:71
    open web.main.ts:112
    s web.factory.ts:65
    <anonymous> workbench.ts:503
    <anonymous> workbench.ts:510
    _invokeFactory loader.js:1199
    complete loader.js:1209
    _onModuleComplete loader.js:1839
    _resolve loader.js:1796
    defineModule loader.js:1439
    y loader.js:1889
    <anonymous> fake:8
    <anonymous> fake:1
2 [files.ts:1156:2](https://emporea.net/stable-2062a59ca1a586d8a6e7bf483841085a94c440a4/static/out/vs/workbench/out-vscode-reh-web/vs/workbench/file:/home/runner/work/code-server/code-server/lib/vscode/src/vs/platform/files/common/files.ts)
This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. [emporea.net](https://emporea.net/?folder=/home/coder)
The web worker extension host is started in a same-origin iframe! [workbench.web.main.js:1999:23012](https://emporea.net/stable-2062a59ca1a586d8a6e7bf483841085a94c440a4/static/out/vs/workbench/workbench.web.main.js)
Feature Policy: Skipping unsupported feature name “usb”. [workbench.web.main.js:1999:23574](https://emporea.net/stable-2062a59ca1a586d8a6e7bf483841085a94c440a4/static/out/vs/workbench/workbench.web.main.js)
Feature Policy: Skipping unsupported feature name “serial”. [workbench.web.main.js:1999:23574](https://emporea.net/stable-2062a59ca1a586d8a6e7bf483841085a94c440a4/static/out/vs/workbench/workbench.web.main.js)
Feature Policy: Skipping unsupported feature name “hid”. [workbench.web.main.js:1999:23574](https://emporea.net/stable-2062a59ca1a586d8a6e7bf483841085a94c440a4/static/out/vs/workbench/workbench.web.main.js)
Feature Policy: Skipping unsupported feature name “cross-origin-isolated”. [workbench.web.main.js:1999:23574](https://emporea.net/stable-2062a59ca1a586d8a6e7bf483841085a94c440a4/static/out/vs/workbench/workbench.web.main.js)
Feature Policy: Skipping unsupported feature name “usb”. [workbench.web.main.js:1999:23730](https://emporea.net/stable-2062a59ca1a586d8a6e7bf483841085a94c440a4/static/out/vs/workbench/workbench.web.main.js)
Feature Policy: Skipping unsupported feature name “serial”. [workbench.web.main.js:1999:23730](https://emporea.net/stable-2062a59ca1a586d8a6e7bf483841085a94c440a4/static/out/vs/workbench/workbench.web.main.js)
Feature Policy: Skipping unsupported feature name “hid”. [workbench.web.main.js:1999:23730](https://emporea.net/stable-2062a59ca1a586d8a6e7bf483841085a94c440a4/static/out/vs/workbench/workbench.web.main.js)
Feature Policy: Skipping unsupported feature name “cross-origin-isolated”. [workbench.web.main.js:1999:23730](https://emporea.net/stable-2062a59ca1a586d8a6e7bf483841085a94c440a4/static/out/vs/workbench/workbench.web.main.js)
Feature Policy: Skipping unsupported feature name “usb”. [workbench.web.main.js:1999:24554](https://emporea.net/stable-2062a59ca1a586d8a6e7bf483841085a94c440a4/static/out/vs/workbench/workbench.web.main.js)
Feature Policy: Skipping unsupported feature name “serial”. [workbench.web.main.js:1999:24554](https://emporea.net/stable-2062a59ca1a586d8a6e7bf483841085a94c440a4/static/out/vs/workbench/workbench.web.main.js)
Feature Policy: Skipping unsupported feature name “hid”. [workbench.web.main.js:1999:24554](https://emporea.net/stable-2062a59ca1a586d8a6e7bf483841085a94c440a4/static/out/vs/workbench/workbench.web.main.js)
Feature Policy: Skipping unsupported feature name “cross-origin-isolated”. [workbench.web.main.js:1999:24554](https://emporea.net/stable-2062a59ca1a586d8a6e7bf483841085a94c440a4/static/out/vs/workbench/workbench.web.main.js)
 INFO [Service Worker] registered [workbench.web.main.js:602:3719](https://emporea.net/stable-2062a59ca1a586d8a6e7bf483841085a94c440a4/static/out/vs/workbench/workbench.web.main.js)
An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can remove its sandboxing. [emporea.net](https://emporea.net/?folder=/home/coder)
The character encoding of a framed document was not declared. The document may appear different if viewed without the document framing it. [webWorkerExtensionHostIframe.html](https://emporea.net/stable-2062a59ca1a586d8a6e7bf483841085a94c440a4/static/out/vs/workbench/services/extensions/worker/webWorkerExtensionHostIframe.html?&vscodeWebWorkerExtHostId=c4be9fb0-c743-45c0-9510-26eb60db3687)
```

When I then try to open a ipynb file this gets added to the console:
```
Feature Policy: Skipping unsupported feature name “cross-origin-isolated”. [webviewElement.ts:501:10](https://emporea.net/stable-2062a59ca1a586d8a6e7bf483841085a94c440a4/static/out/vs/workbench/out-vscode-reh-web/vs/workbench/file:/home/runner/work/code-server/code-server/lib/vscode/src/vs/workbench/contrib/webview/browser/webviewElement.ts)
Feature Policy: Skipping unsupported feature name “cross-origin-isolated”. [webviewElement.ts:565:9](https://emporea.net/stable-2062a59ca1a586d8a6e7bf483841085a94c440a4/static/out/vs/workbench/out-vscode-reh-web/vs/workbench/file:/home/runner/work/code-server/code-server/lib/vscode/src/vs/workbench/contrib/webview/browser/webviewElement.ts)
Feature Policy: Skipping unsupported feature name “cross-origin-isolated”. [webviewElement.ts:543:16](https://emporea.net/stable-2062a59ca1a586d8a6e7bf483841085a94c440a4/static/out/vs/workbench/out-vscode-reh-web/vs/workbench/file:/home/runner/work/code-server/code-server/lib/vscode/src/vs/workbench/contrib/webview/browser/webviewElement.ts)
An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can remove its sandboxing. [emporea.net](https://emporea.net/?folder=/home/coder)
Feature Policy: Skipping unsupported feature name “cross-origin-isolated”. [index-no-csp.html:933:13](https://emporea.net/stable-2062a59ca1a586d8a6e7bf483841085a94c440a4/static/out/vs/workbench/contrib/webview/browser/pre/index-no-csp.html?id=50a4df99-1b67-46ca-82b3-893c92d5a311&origin=50a4df99-1b67-46ca-82b3-893c92d5a311&swVersion=4&extensionId=&platform=browser&vscode-resource-base-authority=vscode-resource.vscode-cdn.net&parentOrigin=https%3A%2F%2Femporea.net&remoteAuthority=emporea.net&purpose=notebookRenderer)
Feature Policy: Skipping unsupported feature name “cross-origin-isolated”. [index-no-csp.html:942:48](https://emporea.net/stable-2062a59ca1a586d8a6e7bf483841085a94c440a4/static/out/vs/workbench/contrib/webview/browser/pre/index-no-csp.html?id=50a4df99-1b67-46ca-82b3-893c92d5a311&origin=50a4df99-1b67-46ca-82b3-893c92d5a311&swVersion=4&extensionId=&platform=browser&vscode-resource-base-authority=vscode-resource.vscode-cdn.net&parentOrigin=https%3A%2F%2Femporea.net&remoteAuthority=emporea.net&purpose=notebookRenderer)
Feature Policy: Skipping unsupported feature name “cross-origin-isolated”. [index-no-csp.html:945:18](https://emporea.net/stable-2062a59ca1a586d8a6e7bf483841085a94c440a4/static/out/vs/workbench/contrib/webview/browser/pre/index-no-csp.html?id=50a4df99-1b67-46ca-82b3-893c92d5a311&origin=50a4df99-1b67-46ca-82b3-893c92d5a311&swVersion=4&extensionId=&platform=browser&vscode-resource-base-authority=vscode-resource.vscode-cdn.net&parentOrigin=https%3A%2F%2Femporea.net&remoteAuthority=emporea.net&purpose=notebookRenderer)
```

about:serviceworkers shows this:
```
Origin: https://emporea.net

    Scope: https://emporea.net/stable-2062a59ca1a586d8a6e7bf483841085a94c440a4/static/out/vs/workbench/contrib/webview/browser/pre/
    Script Spec: https://emporea.net/stable-2062a59ca1a586d8a6e7bf483841085a94c440a4/static/out/vs/workbench/contrib/webview/browser/pre/service-worker.js?v=4&vscode-resource-base-authority=vscode-resource.vscode-cdn.net&remoteAuthority=emporea.net
    Current Worker URL: https://emporea.net/stable-2062a59ca1a586d8a6e7bf483841085a94c440a4/static/out/vs/workbench/contrib/webview/browser/pre/service-worker.js?v=4&vscode-resource-base-authority=vscode-resource.vscode-cdn.net&remoteAuthority=emporea.net
    Active Cache Name: {f1b77d62-b4f6-4250-8701-c7437280b238}
    Waiting Cache Name:
    Push Endpoint: null

Origin: https://emporea.net

    Scope: https://emporea.net/
    Script Spec: https://emporea.net/_static/out/browser/serviceWorker.js
    Current Worker URL: https://emporea.net/_static/out/browser/serviceWorker.js
    Active Cache Name: {be5d9d96-3018-457b-b82e-53953a180697}
    Waiting Cache Name:
    Push Endpoint: null
```

Both Service Workers are running and the ipynb still doesn't load on my deployment.
![image](https://user-images.githubusercontent.com/21969523/187738181-49bba434-fc8b-4a6e-8384-725a3bf6ebdb.png)


Your working deployment has about the same logs but its showing the file now constantly, while mine does not.


I am using [nginx-proxy](https://github.com/nginx-proxy/nginx-proxy) with [acme-companion](https://github.com/nginx-proxy/acme-companion) as a reverse proxy and serve https. 

Then i give the codeserver docker-compose.yml the environmental parameters `VIRTUAL_HOST=emporea.net` and `LETSENCRYPT_HOST=emporea.net`.
This should be sufficient, right? It worked until 4.4.0, so i still dont understand what happend after 4.4.0.? Can you explain?

Code-Server docker container shows this on start-up though (last line, "Not serving HTTPS")
```
[2022-08-31T16:54:12.831Z] info  Wrote default config file to ~/.config/code-server/config.yaml
[2022-08-31T16:54:13.360Z] info  code-server 4.6.0 6d3f9ca6a6df30a1bfad6f073f6fa33c0e63abdb
[2022-08-31T16:54:13.362Z] info  Using user-data-dir ~/.local/share/code-server
[2022-08-31T16:54:13.378Z] info  Using config file ~/.config/code-server/config.yaml
[2022-08-31T16:54:13.378Z] info  HTTP server listening on http://0.0.0.0:8080/ 
[2022-08-31T16:54:13.378Z] info    - Authentication is enabled
[2022-08-31T16:54:13.378Z] info      - Using password from $PASSWORD
[2022-08-31T16:54:13.378Z] info    - Not serving HTTPS 
```

If i can provide more logs or more infos about my configuration let me know.
Thanks.

**Comment by benz0li** [comment]
> @benz0li Have you changed anything with your deployment? I cant reproduce the error any more, its working with your deployment.

I update my images regularly: https://gitlab.b-data.ch/jupyterlab/python/scipy/-/commits/main  
ℹ️ No fundamental change since Aug 28, 2022 6:20pm CEST (Update code-server to v4.6.0).

> This confuses me even more cause now it has to be my deployment. But my deployment works for you. Gosh. Help.

Your deployment does not work flawlessly for me either: https://github.com/coder/code-server/issues/5334#issuecomment-1214142287

> I am using [nginx-proxy](https://github.com/nginx-proxy/nginx-proxy) with [acme-companion](https://github.com/nginx-proxy/acme-companion) as a reverse proxy and serve https.

Maybe https://github.com/coder/code-server/issues/4976#issuecomment-1070414441?

> Code-Server docker container shows this on start-up though (last line, "Not serving HTTPS")

That is OK because the reverse proxy (nginx) takes care of TLS termination.

**Comment by benz0li** [comment]
> Then i give the codeserver docker-compose.yml the environmental parameters `VIRTUAL_HOST=emporea.net` and `LETSENCRYPT_HOST=emporea.net`. This should be sufficient, right? It worked until 4.4.0, so i still dont understand what happend after 4.4.0.? Can you explain?

I do not know, but when I open https://emporea.net in Safari I get

<img width="670" alt="emporea net_https" src="https://user-images.githubusercontent.com/20233085/187746252-08b7115d-dcdd-4c28-9e68-e1e5d5c5fb32.png">

👉 @Emporea Your TLS termination does not seem to work properly.

**Comment by Emporea** [comment]
Actually i just removed the container after my testing. Thats why you get that TLS error. I can open it up again if you want to test it.

**Comment by Emporea** [comment]
Right now its working with my deployment too. I am even more confused.

**Comment by Emporea** [comment]
And now its not working again. Without me changing anything but closing the files and opening it up again multiple times.

**Comment by jsjoeio** [comment]
> I don't know why there is this inconsistency.

That is odd and very frustrating 🤔 I wonder what it could be. Anyone have any ideas?

**Comment by c-dasq** [comment]
Hi all, I was able to simulate almost all possible cases in an orderly manner, and I was unable to replicate the problem:

- Web Browser: Firefox / Chrome / Chromium-based spinoffs
- Remote OS: Raspberry Pi OS Lite / Ubuntu Server / Containers
- Local OS: Windows 10 / Windows 11 / MacOs / iPadOs/ Ubuntu / Raspberry Pi Desktop / Android

It didn't really work well in only two cases:

- Firefox on Android 9 (sorry, I don't have a newer version)
- LXC Ubuntu Server container (I'm sure it's a ProxMox problem)

I suspect that when I generated the report for this bug, I had left the bind-addr setting at 0.0.0.0:8080, I didn't realize that port forwarding via SSH wasn't working (I use tmux); or I don't know if I made some other mistake.

I want to thank you all for the support, and if no one has any more comments, I will close this case.

Thank you very much,

![code-server-jupyter-working](https://user-images.githubusercontent.com/13774380/187912739-800da152-efff-473f-a26a-58318a7d511a.png)

**Comment by Emporea** [comment]
Well mine isnt resolved. But go ahead. 💁🏻

**Comment by c-dasq** [comment]
@Emporea, no problem, I'm not going to close it.

I'll try it with Fedora and let you know.

**Comment by Emporea** [comment]
Try my installation under emporea.net with password "coder"

**Comment by c-dasq** [comment]
I installed ipykernel (using your terminal) and now everything works perfect :)

![emporea - funciona ok](https://user-images.githubusercontent.com/13774380/187923945-f8450ded-1d9a-442d-87ef-2015cd8f525d.png)

Can you do a test and let me know, please?

**Comment by c-dasq** [comment]
I also have to install pip

**Comment by Emporea** [comment]
yeah that has nothing to do with it.

**Comment by Emporea** [comment]
Its working with my desktop firefox for now. Thanks. Android doesn't work ( code-server:4.4.0 did work even with android ).
How did you install ipykernel?
Is `pip3 install ipykernel` sufficient?

**Comment by c-dasq** [comment]
Ok, for some reason, code-server couldn't find the path for Python:

![01 Python is not installed](https://user-images.githubusercontent.com/13774380/187969871-0cd959c4-f708-42ff-854c-8755ed89535c.png)

Even if I told it to do it manually (Python is indeed installed):

![02 Select Interpreter](https://user-images.githubusercontent.com/13774380/187969889-cc3af054-8289-4ba9-be98-cf38ab8bbbe1.png)

So in extensions I uninstalled it and reinstalled it:

![03 Uninstalling Python](https://user-images.githubusercontent.com/13774380/187969968-cc5952f7-87bf-446b-be99-0feb3f798b2c.png)

And now everything is back to normal:

![04 Normalidad](https://user-images.githubusercontent.com/13774380/187970033-c6333abf-0549-41b0-bd59-81d759a74c62.png)

**Comment by c-dasq** [comment]
To install ipykernel you have to go to the path where Python is (or change the path), and that's it:

/usr/bin/python3 -m ipykernel install

**Comment by c-dasq** [comment]
Thank you all very much, I am going to close this issue.
