### ISSUE TITLE
[Bug]: I cannot login to code-server, I copied the password on config.yaml but not work. Incorrect password

### ISSUE THREAD

**Issue by alvin0530** [coder/code-server#5484]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome
- Local OS: Windows 11
- Remote OS: Ubuntu 20.04
- Remote Architecture:
- `code-server --version`: 4.5.1
- Nginx set up domain

### Steps to Reproduce

1. type in my domain
2. login page
3. enter password on config.yaml file and show Incorrect password

### Expected

Login successfully

### Actual

Incorrect password

### Logs

trace child:1902 got message {"message":{"type":"handshake","args":{"bind-addr":"127.0.0.1:8080","auth":"password","password":"XXXXXXXX","config":"/root/.config/code-server/config.yaml","verbose":true,"user-data-dir":"/root/.local/share/code-server","extensions-dir":"/root/.local/share/code-server/extensions","log":"trace","host":"127.0.0.1","port":8080,"proxy-domain":[],"_":[],"usingEnvPassword":false,"usingEnvHashedPassword":false}}}

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by jsjoeio** [comment]
How are you starting code-server?

**Comment by alvin0530** [comment]
I follow the instruction below

curl -fOL https://github.com/coder/code-server/releases/download/v4.6.0/code-server_4.6.0_amd64.deb
sudo dpkg -i code-server_4.6.0_amd64.deb
sudo systemctl enable --now code-server@$USER

https://coder.com/docs/code-server/latest/guide#using-lets-encrypt-with-nginx

I'd just update code-server to 4.6.0 and restart it.

But it doesn't work.

**Comment by jsjoeio** [comment]
Can you share the contents of `config.yaml`? (make sure to redact the password)

**Comment by alvin0530** [comment]
bind-addr: 127.0.0.1:8080
auth: password
password: password
cert: false

**Comment by jsjoeio** [comment]
Thanks! Hmm...if you access directly (no nginx) does it work as expected?

**Comment by code-asher** [comment]
Closing as stale but feel free to comment if you come back to this.
