### ISSUE TITLE
[Bug]: Jupyter kernel state is lost when file is closed or browser is refreshed

### ISSUE THREAD

**Issue by jrich100** [coder/code-server#5504]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome
- Local OS: macOS
- Remote OS: Ubuntu
- Remote Architecture: amd64
- `code-server --version`: 1.70.1

### Steps to Reproduce

1. Open a .ipynb file
2. execute a cell with something like: `x = 5`
3. refresh the browser page
4. In the same .ipynb file, execute a cell with: `print(x)`

### Expected

I would expect the state of the kernel to be preserved and for `print(x)` to print 5.

Not being able to retain the state of the running kernel is a non-starter for using the notebook feature in code-server.

### Actual

the result of running `print(x)` is

NameError: name 'x' is not defined

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

I am using the following extensions:
ms-python
ms-toolsai

**Comment by jsjoeio** [comment]
Can you reproduce this on Codespaces?

I would guess this state is stored in the browser rather than the server so I don't know if there's much we can do (unconfirmed though).
