### ISSUE TITLE
[Feat]: code-server Termux tar.gz build

### ISSUE THREAD

**Issue by babaric-dev** [coder/code-server#5515]
## What is your suggestion?
Generate a tar.gz build for Termux

## Why do you want this feature?
The installation of code-server on Android requires downloading a huge load of dependencies (i.e. `build-essential`, `yarn`, etc.). It is not that convenient. So, I think a build for Termux should be added to the releases (much like the currently available `.tar.gz` build for Linux).

Please add this feature. It will make the installation 10 times easier + better.

**Comment by babaric-dev** [comment]
Is there any update on this feature request? I am looking forward to seeing that feature being implemented.

**Comment by jsjoeio** [comment]
This could be nice. I'm not sure how difficult or how we'd actually do it though. Do you have any suggestions?

**Comment by babaric-dev** [comment]
Only two of the files are compiled executables - `./lib/node` and ./lib/coder-cloud-agent`. We could just compile it for Termux.

**Comment by jsjoeio** [comment]
Is that it? That doesn't sound terribly difficult...

Only thing I'd want though is to be able to add it as part of our platform steps in `build.yaml` and run integration tests in a Termux or Termux-like environment.

@code-asher any thoughts?

**Comment by babaric-dev** [comment]
> Is that it?

That may be all, or only one part (sorry I am quite a noob, so idk).

**Comment by code-asher** [comment]
I think it is a good idea; I started looking into this briefly a 
while back but I did not get very far so I do not know how 
difficult it is to compile for Termux.

**Comment by babaric-dev** [comment]
Any updates on implementing this feature?

**Comment by jsjoeio** [comment]
I don't think we have bandwidth to look into this. The biggest question still stands:
> how difficult it is to compile for Termux.

feel free to research and share what you learn!

**Comment by babaric-dev** [comment]
Apparently, this is already available through `tur-repo`.

To install, run:
```
pkg install tur-repo
pkg install code-server
```

We may add this to the documentation.

Btw, the `code-oss` package is also available in `tur-repo` too.

**Comment by jsjoeio** [comment]
This is already in the docs: https://coder.com/docs/code-server/latest/termux#install
