### ISSUE TITLE
[Feat]: 来自中国新手用户的一个小需求

### ISSUE THREAD

**Issue by robomentor** [coder/code-server#5521]
## What is your suggestion?

在中国使用vscode可以顺利的安装扩展插件，但是在codeserver中非常的慢，甚至会超时失败，是否有什么解决办法？

## Why do you want this feature?

这是很基础的功能，非常影响使用体验！

## Are there any workarounds to get this functionality today?

暂时没有找到什么办法？

## Are you interested in submitting a PR for this?

暂时不会！

**Comment by jsjoeio** [comment]
Hi there! Do you mind editing your issue and translating to English?

**Comment by robomentor** [comment]
> Hi there! Do you mind editing your issue and translating to English?

Using vscode in China can successfully install the extension plug-in, but it is very slow in the codeserver, and even fails over time. Is there any solution?
This is a very basic function, which greatly affects the user experience!

**Comment by w72** [comment]
You can use vscode's marketplace as described in the [FAQ](https://coder.com/docs/code-server/latest/FAQ#how-do-i-use-my-own-extensions-marketplace), but it's not recommended because it violates Microsoft's terms of use.
```bash
export EXTENSIONS_GALLERY='{"serviceUrl": "https://marketplace.visualstudio.com/_apis/public/gallery"}'
```

**Comment by robomentor** [comment]
> [您可以按照FAQ](https://coder.com/docs/code-server/latest/FAQ#how-do-i-use-my-own-extensions-marketplace)中的说明使用 vscode 的市场，但不建议这样做，因为它违反了 Microsoft 的使用条款。
> 
> ```shell
> export EXTENSIONS_GALLERY='{"serviceUrl": "https://marketplace.visualstudio.com/_apis/public/gallery"}'
> ```

Thanks a lot, I will use my own mirror this way

**Comment by jsjoeio** [comment]
Awesome! I'm going to close this then. Thank you @w72!
