### ISSUE TITLE
[Chore]: upgrade Code to 1.71 

### ISSUE THREAD

**Issue by jsjoeio** [coder/code-server#5528]
https://github.com/microsoft/vscode/releases/tag/1.71.0 is out now.

**Comment by fritterhoff** [comment]
That will be pretty tough to merge. Tried to merge to main already some days ago and several patches require manual fixing.

**Comment by jsjoeio** [comment]
@fritterhoff darn it! That's unfortunate. Thanks for the heads-up! I'll give it a shot next week.

I guess to make these easier, we could try upstreaming some of these patches. Not sure if all will be accepted though.

**Comment by fritterhoff** [comment]
Well okay. It is easier than expected. We only have to patch two patches and obviously one is even already upstreamed.
I'll create a PR draft asap.
