### ISSUE TITLE
[Bug]: Unable to load resource on iPad Safari

### ISSUE THREAD

**Issue by shp7724** [coder/code-server#5532]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Safari
- Local OS: iPadOS
- Remote OS: macOS
- Remote Architecture: arm64
- `code-server --version`: 4.6.0

### Steps to Reproduce

1. open code-server
2. login

### Expected

The editor should load.

### Actual

White blank page.

### Logs

```
...
File not found: /opt/homebrew/Cellar/code-server/4.6.0/libexec/lib/vscode/out/vs/base/browser/browser.js
File not found: /opt/homebrew/Cellar/code-server/4.6.0/libexec/lib/vscode/out/vs/base/common/cancellation.js
File not found: /opt/homebrew/Cellar/code-server/4.6.0/libexec/lib/vscode/out/vs/base/common/marshalling.js
File not found: /opt/homebrew/Cellar/code-server/4.6.0/libexec/lib/vscode/out/vs/base/common/event.js
File not found: /opt/homebrew/Cellar/code-server/4.6.0/libexec/lib/vscode/out/vs/base/common/lifecycle.js
File not found: /opt/homebrew/Cellar/code-server/4.6.0/libexec/lib/vscode/out/vs/base/parts/request/browser/request.js
File not found: /opt/homebrew/Cellar/code-server/4.6.0/libexec/lib/vscode/out/vs/base/common/resources.js
File not found: /opt/homebrew/Cellar/code-server/4.6.0/libexec/lib/vscode/out/vs/base/common/uri.js
File not found: /opt/homebrew/Cellar/code-server/4.6.0/libexec/lib/vscode/out/vs/platform/product/common/product.js
File not found: /opt/homebrew/Cellar/code-server/4.6.0/libexec/lib/vscode/out/vs/base/common/network.js
File not found: /opt/homebrew/Cellar/code-server/4.6.0/libexec/lib/vscode/out/vs/platform/window/common/window.js
File not found: /opt/homebrew/Cellar/code-server/4.6.0/libexec/lib/vscode/out/vs/base/common/strings.js
File not found: /opt/homebrew/Cellar/code-server/4.6.0/libexec/lib/vscode/out/vs/base/common/path.js
```

### Screenshot/Video

<img width="1498" alt="스크린샷 2022-09-03 오전 3 01 36" src="https://user-images.githubusercontent.com/33917774/188211823-5f18b596-ce6c-4455-ae3a-ca67ce41fd5a.png">

<img width="1506" alt="스크린샷 2022-09-03 오전 3 01 48" src="https://user-images.githubusercontent.com/33917774/188211851-39420b83-ee3f-4b52-ad25-73130df13fb4.png">

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

- On macOS, everything works fine no matter which browser I use.
- I tried reinstalling code-server several times.
- If I refresh a lot of times, strangely it works sometimes. But most of the time it doesn't. I think the odds are lower on PWA mode.

**Comment by jsjoeio** [comment]
This is very strange 🤔 How are you doing this exactly?
1. install via homebrew on macOS
2. expose and access on iPad?

**Comment by shp7724** [comment]
Yes, I installed via homebrew and enabled HTTPS using `nginx` and `certbot`.

I managed to (temporalily) solve this issue by going through the *whole* installation process **_twice_**, which includes reinstalling everything(i.e. `code-server`, `nginx`, `certbot`) and reissuing ssl certificates. Reinstalling only one of them didn't solve the issue.

As far as I remember, I started seeing this issue when my ssl certificate got expired and reissued a new one. I don't see how it can be associated with this issue, though. :(

**Comment by jsjoeio** [comment]
I guess what would be helpful for me is to know how to reproduce this. Would these steps suffice?
1. install code-server on macOS via homebrew
2. run `ngrok` to expose code-server
3. open on iPad in Safari

**Comment by shp7724** [comment]
@jsjoeio It's been a quite a while, but I'm still suffering from this issue. The steps you suggested doesn't seem to be enough to reproduce it.

One thing I noticed though, is that all the failed requests are missing a cookie named `code-server-session`.

For instance, the following request succeeded with the cookie `code-server-session`:

<img width="468" alt="image" src="https://user-images.githubusercontent.com/33917774/195751418-938f06d6-7aba-4f6e-b15e-62118a4e04ab.png">

whereas this request didn't (note the entire cookie is missing here):

<img width="462" alt="image" src="https://user-images.githubusercontent.com/33917774/195751491-5cd99013-75a2-4ca5-ba67-fa2bbc912e9c.png">

I suspect this might have something to do with the internal session management mechanism of iPadOS safari.

**Comment by shp7724** [comment]
Temporarily disabling and reenabling `Prevent cross-site tracking` option in settings, everything started to work as expected.

**Comment by jsjoeio** [comment]
Nice find!!! Can we close this now?

**Comment by shp7724** [comment]
@jsjoeio 

It turned out a coincidence, I'm afraid. 😔

**Comment by jsjoeio** [comment]
Darn it :( Okay well sadly, I don't have bandwidth to dive in now but feel free to leave comments here and I can be your async rubber duck

**Comment by code-asher** [comment]
I have seen this happen on a slow network where the bundle takes a while to load.  It times out and tries to load the sources individually, which do not exist of course.

Closing but see https://github.com/coder/code-server/issues/2407
