### ISSUE TITLE
[Feat]: error if unsafe-perm not set when installing with npm

### ISSUE THREAD

**Issue by jsjoeio** [coder/code-server#5540]
## What is your suggestion?

Error if you are root and you don't pass `--unsafe-perm`

## Why do you want this feature?

Helps users understand flags needed to install code-server properly.

## Are there any workarounds to get this functionality today?

N/A

## Are you interested in submitting a PR for this?

Maybe but anyone else can do it too.

**Comment by code-asher** [comment]
We have this!
