### ISSUE TITLE
remote extension host terminated unexpectedly 3 times within the last 5 minutes

### ISSUE THREAD

**Issue by hzb-ykpcx** [coder/code-server#5555]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Safari
- Local OS: IPad OS 16
- Remote OS: Ubuntu 20.04
- Remote Architecture: x86-64
- `code-server --version`: 4.7.0

### Steps to Reproduce

1. update code-server to the latest 4.7.0 (the issue didn’t occur in my old version)
2. open code-server
3. a prompt pops up, it says remote extension host terminated unexpectedly 3 times within the last 5 minutes. then all the extensions fail.

### Expected

no errors or warnings.

### Actual

a prompt pops up says remote extension host terminated unexpectedly 3 times within the last 5 minutes, and all the extensions fail.

### Screenshot/Video

![18AA929E-61F2-40B1-A274-B932918D5B4E](https://user-images.githubusercontent.com/52552971/190311738-aa5a5a12-c20c-4a64-a164-4d8b2a8423f3.png)

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

Even with no extension installed, the issue still occurs. It happened after I updated my code-server to the latest 4.7.0.  I actually haven’t tried Github Codespaces.

**Comment by hzb-ykpcx** [comment]
I have uninstalled all the extensions and the issue still keeps coming up.

**Comment by hzb-ykpcx** [comment]
I solved it by restarting the systemctl service

**Comment by Lippiece** [comment]
> I solved it by restarting the systemctl service
@Ephemereh How did you do it?

**Comment by Ephemereh** [comment]
I did something like `systemctl restart code-server`

**Comment by vanekj** [comment]
@Ephemereh Thank you, it helped me also
