### ISSUE TITLE
[Feat]: Can't auto import when the file is not open?

### ISSUE THREAD

**Issue by Alt-er** [coder/code-server#5566]
- Web Browser: chrome latest
- Local OS: mac latest
- Remote OS:
- Remote Architecture:
- `code-server --version`: v4.4.0

![iShot_2022-09-17_13 37 15](https://user-images.githubusercontent.com/18004903/190842412-c255a9bc-c141-4f31-aaad-342d7c4415b8.gif)

**Comment by jsjoeio** [comment]
Does this happen on the latest version?

**Comment by code-asher** [comment]
Closing as stale but feel free to comment if you come back to this.
