### ISSUE TITLE
[Bug]: HASHED_PASSWORD vs SUDO_PASSWORD_HASH; Same hash string provided but only the HASHED_PASSWORD works...

### ISSUE THREAD

**Issue by CtheCondor** [coder/code-server#5570]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome
- Local OS: windows 10 
- Remote OS Debian 11:
- Remote Architecture: amd64
- local build from dockerFile.

### Steps to Reproduce

1. define both has environment fields to the same value using $$ rather than $ and no enclosing ""
2. access web portal and used initial value to login- successfully
3. run `sudo apt update` using the same value - Fails

### Expected

Should perform an apt update

### Actual

3 attempts then kicks out due to excessive password attempts

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by jsjoeio** [comment]
I don't think code-server supports `SUDO_PASSWORD_HASH`. What led you to believe it would? (I want to correct any docs we have)

**Comment by CtheCondor** [comment]
It appears I am subject to the same base issue that Issue #5127. I arrived at the Hash instructions from the [LinuxServer.io FAQ](https://github.com/linuxserver/docker-code-server#hashed-code-server-password) to the [coder/code-server Hashing instructions](https://github.com/coder/code-server/blob/main/docs/FAQ.md#can-i-store-my-password-hashed). From the linuxserver documentation; there is a sudo password hash environment variable and this jump between root projects was not caught till now when I did a "search this repo" from this screen and realized the jump much to my embarrassment now.. 

It Appears though that I am not the only one to have this issue as it is mentioned in [Discussion 4382](https://github.com/coder/code-server/discussions/4382) and [Discussion 3606](https://github.com/coder/code-server/discussions/3606)

**Comment by jsjoeio** [comment]
Ah! I see now. Sorry for the confusion! Yeah if you used `HASHED_PASSWORD` like [this](https://github.com/coder/code-server/discussions/4382#discussioncomment-1555824) then it should work as expected. I'm not sure what changes are required to also support `SUDO_PASSWORD_HASH`. Is it okay if we close this?

**Comment by CtheCondor** [comment]
Absolutely sorry about the confusion! For what it's worth I found if I used an openssl hashing algorithm; it's output worked in the sudo_hash field but not the one using the argon2-cli hashing like your code server base image uses. P.S. do you have any documentation on doing local builds from a dockerfile on your page? If not there may be some benefit of adding those details; just mentioned since this was tagged as documentation related xD

**Comment by jsjoeio** [comment]
> argon2-cli hashing like your code server base image uses

Ah darn...argon2 has been troublesome these days  😂

> P.S. do you have any documentation on doing local builds from a dockerfile on your page

I don't think so 🤔 You could look at [this](https://github.com/coder/code-server/blob/main/ci/release-image/Dockerfile). Haha fair! PRs welcome 😉 (you know better than me what you wish were in the docs)

**Comment by mriksman** [comment]
@CtheCondor as per the documentation [here](https://hub.docker.com/r/linuxserver/code-server), `SUDO_PASSWORD_HASH` is in the format `$type$salt$hashed`. 

I ran the command `sudo cat /etc/shadow` and took the results from my `pi` user.
```
pi:$5$<salt>$<password hash>:19257:0:99999:7:::
```
The `$5` indicates it is `SHA256`.

Just copy this `$5$<salt>$<password hash>`, duplicate the `$` (as you did with `PASSWORD_HASH`), and it should work.
```
- SUDO_PASSWORD_HASH=$$5$$<salt>$$<password hash>
```

**Comment by dimingnip** [comment]
This is what worked for me.  

Put password into `SUDO_PASSWORD` and run `cat /etc/shadow` in console using root.  Copy the string for the password from the output and use it in  `SUDO_PASSWORD_HASH`.

**Comment by code-asher** [comment]
Closing, to summarize these are two separate passwords with different hashing mechanisms: one for code-server's login, and one for sudo.
