### ISSUE TITLE
[Bug]: file tree width doesn't save on reload

### ISSUE THREAD

**Issue by jsjoeio** [coder/code-server#5584]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: any
- Local OS:
- Remote OS:
- Remote Architecture:
- `code-server --version`: latest

### Steps to Reproduce

1. open code-server
2. adjust width of file tree
3. reload page

### Expected

file tree width should be same width

### Actual

file tree width is not updated

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

Originally mentioned by @sharkymark in 1.34 of Coder v1.

@code-asher theories:

> Interestingly when I refresh I get the popup that confirms I want to leave the page and if I hit no and then refresh again the size is saved.  I think VS Code saves the state on a timer and when the page unloads but the latter is prevented by the browser.  But then hitting no gets back to the page and lets the save keep going.  Just a theory though

> Even if I leave it open for a while it never seems to save so could be something broken with the state flush timer so that is something to look into.  Another thing is to see if there is a way to reliably flush the state when the page unloads.

**Comment by gil-frenkel-HH** [comment]
Any progress on that?

**Comment by code-asher** [comment]
No updates, I think we should close this as an upstream issue though.  I tested and my file tree width is being restored though.
