### ISSUE TITLE
[Bug]: install.sh does not work as expected on freebsd

### ISSUE THREAD

**Issue by unknowndevQwQ** [coder/code-server#5594]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: N/A
- Local OS: N/A
- Remote OS: freebsd
- Remote Architecture: x86_64
- `code-server --version`: Not yet installed

### Steps to Reproduce

1. Run install.sh as a normal user

### Expected

It should be installed successfully or something

### Actual

```
$ ./install.sh 
FreeBSD 13.1-RELEASE-p2
Installing latest from npm.

./install.sh: NPM_PATH: not found
Installing with npm.

+ su - -c 'npm install -g code-server --unsafe-perm'
Password:
su: only root may use -c
```

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

**Comment by unknowndevQwQ** [comment]
At the same time, I noticed that install.sh does not try the doas command, which is a sudo-like command

**Comment by jsjoeio** [comment]
@code-asher - figured you might be better to answer this.
