### ISSUE TITLE
[Bug]: Statuses of activity-bar, status-bar, extension welcome pages do not persist

### ISSUE THREAD

**Issue by hefanbo** [coder/code-server#5597]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### OS/Web Information

- Web Browser: Firefox 104, Chromium 102
- Local OS: Ubuntu 20.04
- Remote OS: Ubuntu 22.04
- Remote Architecture: x86_64
- `code-server --version`: 4.7.0 7f108c61ab670ccaae4cfde5de2909c003db1ce8 with Code 1.71.0

### Steps to Reproduce

1. Some extensions (e.g. Project Manager) show welcome pages. Close them.
2. Hide some buttons in activity-bar or status-bar.
3. Clear browser's cache and refresh the page.

### Expected

1. The buttons in activity-bar and status-bar stay the same as before.
2. The welcome pages do not show again.

### Actual

1. The buttons in activity-bar and status-bar are restored to default.
2. All welcome pages show up again.

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

This happens in v4.7.0 but not in v3.11.1

**Comment by jsjoeio** [comment]
I am guessing that data is stored in the browser cache. I can't remember which version it was but I think a lot of data  got moved from the server to the client. You're sure this doesn't reproduce in Codespaces or vscode.dev?

**Comment by hefanbo** [comment]
Actually no.

Apparently vscode.dev stores all user settings in browser. And Codespaces is not available for me. But I have to check those boxes to submit the issue.

I guess we need to do some extra work to move those settings back to the server.

**Comment by jsjoeio** [comment]
Okay so I tested in Codespaces like so:
1. open Codespace
2. Right-click Status Bar > Hide Keyboard Layout
3. Refresh page. It's hidden
4. Clear cache in Brave > Refresh page.
5. Status Bar has reset

Therefore, this appears to be a bug upstream.
