### ISSUE TITLE
[Feat]: Adding remote-ssh support

### ISSUE THREAD

**Issue by Phoveran** [coder/code-server#5603]
Thanks a a lot for your contribution!
Is there any possibility to use remote-ssh in code-server? For example I want to use code-server on Server A and ssh from A to Server B, C, D, E.... and so on. The ssh files should be all on Server A (e.g. private key file).

**Comment by jsjoeio** [comment]
There has been some talk about it in the past here: https://github.com/coder/code-server/issues/1315

**Comment by Phoveran** [comment]
[#1315](https://github.com/coder/code-server/issues/1315)
