### ISSUE TITLE
[Docs]: Why is it possible to connect to code-server with SSH if I use cloudflare tunnel and ngrok?

### ISSUE THREAD

**Issue by Moius** [coder/code-server#5613]
cloudflare tunnel and ngork just provide a springboard server about ssh, what is the difference between this and using SSH to connect to code-server directly?
And there is a part of the documentation inaccurate description, in the section using cloudflare tunnel.
"Run cloudflared tunnel --url ssh://localhost:22 on the remote server" 
Here there is no hint in the remote server also to install cloudflared.
At the same time the above ~/.ssh/config document in the user settings also does not match the user name used in the following connection.

**Comment by jsjoeio** [comment]
> cloudflare tunnel and ngork just provide a springboard server about ssh, what is the difference between this and using SSH to connect to code-server directly?

Good question...I'm not as familiar with cloudeflare tunnel but i've used ngrok in the past when I want to expose my code-server and access from a separate machine. I guess those tools provide SSL out of the box? cc @code-asher 

> And there is a part of the documentation inaccurate description, in the section using cloudflare tunnel.
"Run cloudflared tunnel --url ssh://localhost:22 on the remote server"
> Here there is no hint in the remote server also to install cloudflared.
At the same time the above ~/.ssh/config document in the user settings also does not match the user name used in the following connection.

Please open a PR to update it!

**Comment by ELXIAGHT** [comment]
I only used the cloudflared tunnel to connect, and the result was that the VS code Remote SSH expansion did not use any files from the code-server. Instead, a new .vscodeserver file was created.

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ELXIAGHT** [comment]
> past



> > cloudflare 隧道和 ngork 只是提供了一个关于 ssh 的跳板服务器，这和使用 SSH 直接连接到 code-server 有什么区别？
> 
> 好问题...我对 cloudeflare 隧道不太熟悉，但我过去曾使用过 ngrok，当时我想公开我的代码服务器并从单独的机器访问。我猜这些工具提供了开箱即用的 SSL？抄送@code-asher
> 
> > 并且在使用 cloudflare 隧道的部分中，有一部分文档描述不准确。
> > “在远程服务器上运行 cloudflared tunnel --url ssh://localhost:22”
> > 这里没有提示远程服务器也安装 cloudflared。
> > 同时上面的~/.ssh/config文件中的用户设置也与后面连接中使用的用户名不匹配。
> 
> 请打开 PR 进行更新！

I only used the cloudflared tunnel to connect, and the result was that the VS code Remote SSH expansion did not use any files from the code-server. Instead, a new .vscodeserver file was created.

**Comment by ELXIAGHT** [comment]
> > cloudflare tunnel and ngork just provide a springboard server about ssh, what is the difference between this and using SSH to connect to code-server directly?
> 
> Good question...I'm not as familiar with cloudeflare tunnel but i've used ngrok in the past when I want to expose my code-server and access from a separate machine. I guess those tools provide SSL out of the box? cc @code-asher
> 
> > And there is a part of the documentation inaccurate description, in the section using cloudflare tunnel.
> > "Run cloudflared tunnel --url ssh://localhost:22 on the remote server"
> > Here there is no hint in the remote server also to install cloudflared.
> > At the same time the above ~/.ssh/config document in the user settings also does not match the user name used in the following connection.
> 
> Please open a PR to update it!

I only used the cloudflared tunnel to connect, and the result was that the VS code Remote SSH expansion did not use any files from the code-server. Instead, a new .vscodeserver file was created.

**Comment by jsjoeio** [comment]
> I only used the cloudflared tunnel to connect, and the result was that the VS code Remote SSH expansion did not use any files from the code-server. Instead, a new .vscodeserver file was created.

Interesting...AFAIK, you can't use VS Code Remote SSH with code-server so I wouldn't expect that to work unfortunately.

**Comment by ELXIAGHT** [comment]
> > I only used the cloudflared tunnel to connect, and the result was that the VS code Remote SSH expansion did not use any files from the code-server. Instead, a new .vscodeserver file was created.
> 
> Interesting...AFAIK, you can't use VS Code Remote SSH with code-server so I wouldn't expect that to work unfortunately.

The problem here is that the documentation describes "SSH into code-server on VS Code", but actually using SSH connection on VScode using the method in the article has nothing much to do with code-server, not SSH to code-server. I think this description is not accurate.

**Comment by ELXIAGHT** [comment]
Maybe the document needs another revision 😂

**Comment by jsjoeio** [comment]
Lol probably so...feel free to add more changes!

**Comment by code-asher** [comment]
Yeah that documentation is confusing to me as well.  It seems like we should just remove that section entirely because it is about VS Code remote and nothing to do with code-server as noted.

**Comment by YanivYoobic** [comment]
This is really need to be removed.
Confused me as well. It's just explaining how to SSH to machine and not related to code-server at all.

**Comment by tmchartrand** [comment]
Yes, this section is super confusing, definitely seemed to imply that the SSH connection could be used by e.g. VSCode Remote SSH, to connect to the existing code-server instance on the remote machine.
