### ISSUE TITLE
[Bug]: Error while downloading folders 

### ISSUE THREAD

**Issue by AbidFaiez** [coder/code-server#5618]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Google-chrome
- Local OS:
- Remote OS: 5.4.156-83.273.amzn2.x86_64
- Remote Architecture:
- `code-server --version`: 4.0.1

### Steps to Reproduce

1. Open code-server
2. Download a big folder
3. the Download is interrupted

### Expected

expect the folder is downloaded successfully 

### Actual

Then the download is stopped after some seconds

### Logs

 INFO [remote-connection][Management   ][76d8b…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
​  INFO [remote-connection][Management   ][76d8b…][reconnect] resolving connection...

### Screenshot/Video

![image](https://user-images.githubusercontent.com/86207030/193632056-76c18a5e-ee83-4970-9f12-8fa72cb5765a.png)

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

Why the download button doesn't zip the folder then download it directly like Theia eclipse

**Comment by AbidFaiez** [comment]
![image](https://user-images.githubusercontent.com/86207030/193941357-56c22778-b345-4126-aa7e-3d5bfb6d6378.png)
This an exemple of folder or even a zip file that size exceeded  70 mb

**Comment by jsjoeio** [comment]
@AbidFaiez thank you! What steps are you taking to download a folder? Is it using the UI, or something in the terminal or something else?

**Comment by AbidFaiez** [comment]
@jsjoeio I'm using the UI : right click on the folder or file then click on download button, then I chose the local path to store and click on ok.
Btw I just wanna know also if there is a way to download a folder as zip like the behavior in Theia eclipse

**Comment by AbidFaiez** [comment]
> > @jsjoeio I'm using the UI : right click on the folder or file then click on download button, then I chose the local path to store and click on ok.
> 
> Thank you! I only see that option on files, not folders.
> 
> <img alt="image" width="462" src="https://user-images.githubusercontent.com/3806031/194347202-676c83d5-6899-45bd-ba45-7c815b849407.png">
> 
> <img alt="image" width="431" src="https://user-images.githubusercontent.com/3806031/194347241-46487626-53c7-49fc-8499-b65781eb7b0d.png">
> 
> > Btw I just wanna know also if there is a way to download a folder as zip like the behavior in Theia eclipse
> 
> Not that I know of 🤔 You could check vscode.dev or Codespaces. If it exists there, then it's possible we have a bug in code-server.

Thank you @jsjoeio for your time , Actually the download option is present for folder or file in code-server , I tried using vscode.dev and the bug is reproduced in vscode.dev .

Regards,

**Comment by jsjoeio** [comment]
> Actually the download option is present for folder or file in code-server , I tried using vscode.dev and the bug is reproduced in vscode.dev .

great! can you raise this upstream?
