### ISSUE TITLE
[Bug]: code-server (run with docker) will always overwrite PATH variable

### ISSUE THREAD

**Issue by huweiATgithub** [coder/code-server#5621]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Remote OS: Ubunu
- Remote Architecture: amd64
- `code-server --version`: both v4.7.0 and v4.0.1 are tried

### Steps to Reproduce

1. In a machine with docker installed, run
   ```bash
   mkdir -p ~/.config
   docker run -it --name code-server -p 127.0.0.1:8080:8080 \
   -v "$HOME/.config:/home/coder/.config" \
   -v "$PWD:/home/coder/project" \
   -u "$(id -u):$(id -g)" \
   -e "DOCKER_USER=$USER"  -e "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/some/path" \
   codercom/code-server:latest
   ```
2. Login to the browser, launch terminal in vscode and print the PATH `echo $PATH`
3. Always get: 

### Expected

`/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/some/path` with some extra paths appended by code-server.

### Actual

`/usr/lib/code-server/lib/vscode/bin/remote-cli:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games`

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

Though I checked I am using HTTPS, but I actually running locally without HTTPS.
I checked it because it is a must and I think HTTPS has nothing to do with the issue.

**Comment by benz0li** [comment]
Prepending `/usr/lib/code-server/lib/vscode/bin/remote-cli` to `PATH` is not a bug but by design.

Cross references:

* https://github.com/coder/code-server/pull/5360
* https://github.com/coder/code-server/issues/5417

**Comment by huweiATgithub** [comment]
> Prepending /usr/lib/code-server/lib/vscode/bin/remote-cli to PATH is not a bug but by design.

Prepending is not the issue. My issue is that PATH has been overwritten instead of prepending.

**Comment by jsjoeio** [comment]
@code-asher do you mind taking a look at this one?

**Comment by benz0li** [comment]
@huweiATgithub What `PATH` is set in `/etc/profile`?

**Comment by huweiATgithub** [comment]
> @huweiATgithub What `PATH` is set in `/etc/profile`?

I am running from the docker:
```
docker run -it --name code-server -p 127.0.0.1:8080:8080 \
-v "$HOME/.config:/home/coder/.config" \
-u "$(id -u):$(id -g)" \
-e "DOCKER_USER=$USER"  -e "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/some/path" \
codercom/code-server
```
therefore, it should not matter what is my path in `/etc/profile`. I am passing the PATH through docker run `-e` option.

**Comment by huweiATgithub** [comment]
Let alone that I deploy code-server with docker. I have also tried that on multiple machines. So I suppose that is not an issue related to the host machines.

You may quickly execute the above docker command to see if that can be reproduced.

**Comment by huweiATgithub** [comment]
BTW, if you tried to `docker exec` into the container. The PATH variable is fine. **only terminal launch by code-server** had the issue. 

I guess before the code-server launch, it has a wrapper that modifies the PATH variable to insure code-server's launching env. The wrapper is not respecting the PATH from its env.

**Comment by benz0li** [comment]
> You may quickly execute the above docker command to see if that can be reproduced.

I can reproduce your issue.

**Comment by benz0li** [comment]
> BTW, if you tried to `docker exec` into the container. The PATH variable is fine. **only terminal launch by code-server** had the issue.

I can confirm that.

> I guess before the code-server launch, it has a wrapper that modifies the PATH variable to insure code-server's launching env. The wrapper is not respecting the PATH from its env.

I am setting `PATH` in the Dockerfile and that works fine. Check my reference deployment at https://demo.jupyter.b-data.ch.

**Comment by code-asher** [comment]
I remember looking into this briefly before (https://github.com/coder/code-server/issues/4699) but I have no idea where it happens. :disappointed:

**Comment by huweiATgithub** [comment]
> I am setting PATH in the Dockerfile and that works fine. Check my reference deployment at https://demo.jupyter.b-data.ch/.

b-data looks very fancy! integrating jupyterlab with vscode is really cool and productive.
I am not familiar with it. It seems I cannot customize in the `demo-` mode.
I created one Dockerfile,
```docker
FROM codercom/code-server
ENV PATH="/some/path:${PATH}"
```
then build it and run it with Docker using a command similar to the one posted above.

Still get path:
![image](https://user-images.githubusercontent.com/37072526/194139034-b3a0d04e-aae3-40a1-99cf-ae1fb4fc198a.png)

**Comment by huweiATgithub** [comment]
> I remember looking into this briefly before (#4699) but I have no idea where it happens. disappointed

How did I not find out the previous issue :astonished: I searched that...

**Comment by code-asher** [comment]
Oh wait I think I might know what it is!  I think VS Code sources a login shell to get `PATH`.  So basically they run something like `bash -l printenv PATH` and then set PATH to that.

There are some terminal settings like `Inherit Env` that we might want to play around with to see if we can stop it from doing that.

**Comment by code-asher** [comment]
Can confirm that disabling `Terminal › Integrated: Inherit Env` prevents the override.

**Comment by benz0li** [comment]
> I am not familiar with it. It seems I cannot customize in the `demo-` mode.

No. But see https://github.com/b-data/jupyterlab-python-docker-stack#run-container

---

Adapted to your example:

```bash
docker run -it --name jupyter-code-server \
  -u root \
  -p 8888:8888 \
  -v $PWD:/home/$USER \
  -e NB_USER=$USER \
  -e NB_UID=$(id -u) \
  -e NB_GID=$(id -g) \
  -e CHOWN_HOME=1 \
  -e CHOWN_HOME_OPTS=-R \
  -e PATH=/opt/TinyTeX/bin/linux:/opt/quarto/bin:/opt/code-server/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/some/path \
  registry.gitlab.b-data.ch/jupyterlab/python/scipy
```

ℹ️ Run the command in an empty directory so that the container populates it.

**Comment by code-asher** [comment]
> can it preserve the modified PATH? Inherit Env sounds like getting env from the env that it runs in.

Yeah it looks ilke the "inherit env" name is misleading.  It seems to mean that it spawns a login shell to get the environment rather than using the current environment (which sounds backwards from "inherit" to me :shrug: but I guess that is the name they went with).

So to summarize:
- With inherit env: gets environment by spawning a login shell and overrides current environment
- Without inherit env: uses the current environment

**Comment by huweiATgithub** [comment]
> Oh wait I think I might know what it is! I think VS Code spawns a login shell to get `PATH`. So basically they run something like `bash -lc "printenv PATH"` and then set PATH to that. **Edit:** actually it seems they source the entire environment not just `PATH` [as seen here](https://github.com/microsoft/vscode/blob/a236bed77998b6e6026813a9dd7d45d7a6f680dc/src/vs/platform/shell/node/shellEnv.ts#L136-L142) then merge it with the current environment.
> 
> There are some terminal settings like `Inherit Env` that we might want to play around with to see if we can stop it from doing that.

I checked the .bashrc and .profile. There is nothing particular done there.
The PATH is being modified in `/usr/bin/code-server` I think.

**Comment by huweiATgithub** [comment]
> With inherit env: gets environment by spawning a login shell and overrides current environment

For a login shell, I think the path set in the Dockerfile or pass from the `docker run` command should be respected.
See:
![image](https://user-images.githubusercontent.com/37072526/194147208-27d46b98-a3d6-4e0b-bf17-5618636e7de2.png)

So I think either vscode modifies the PATH or code-server modifies it.
It is more likely that the code-server modifies it as the local instance of vscode runs without this issue.

**Comment by code-asher** [comment]
I tried the same thing with `debian:11` (this is what code-server is based on) and reproduced:

```
coder@my-dev2:~/docker$ docker run --rm -e "PATH=/usr/bin:/bin:/some-path" -it debian:11 bash
root@25b75f4f2da6:/# printenv PATH
/usr/bin:/bin:/some-path
root@25b75f4f2da6:/# bash -ilc 'printenv PATH'
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

In `/etc/profile` there is this:

```
if [ "$(id -u)" -eq 0 ]; then
  PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
else
  PATH="/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games"
fi
```

So this could be the cause of the problem.

**Comment by huweiATgithub** [comment]
What about adding a release for ubuntu:focal? It also benefits those users who use ubuntu:focal more.

**Comment by code-asher** [comment]
That seems chill.  Maybe we can do the Docker tags like this:

```
latest         # debian:11 with latest code-server
bullseye       # debian:11 with latest code-server
focal          # ubuntu:focal with latest code-server
4.7.0          # debian:11 with code-server 4.7.0
4.7.0-bullseye # debian:11 with code-server 4.7.0
4.7.0-focal    # ubuntu:focal with code-server 4.7.0
```

I patterned that after the Python image but maybe in code-server's case it makes more sense to do it by OS.

```
latest       # debian:11 with latest code-server
debian       # debian:11 with latest code-server
ubuntu       # ubuntu:focal with latest code-server
4.7.0        # debian:11 with code-server 4.7.0
4.7.0-debian # debian:11 with code-server 4.7.0
4.7.0-ubuntu # ubuntu:focal with code-server 4.7.0
```

We could also do both.

**Comment by huweiATgithub** [comment]
Looks good. These are fine if documented I think.
