### ISSUE TITLE
[Bug]: cannot use extention marketplace in Ventira 13.0(22A5365d)

### ISSUE THREAD

**Issue by hanmilLee** [coder/code-server#5628]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: chrome/safari
- Local OS: Ventira 13.0 22A5365d
- Remote OS: - 
- Remote Architecture: - 
- `code-server --version`: 4.7.1 207b6ffc90cfc2a6bd2d4b64bf13bf639287f0c0 with Code 1.71.2

### Steps to Reproduce

1. open code-server
2. install extension
3.cannot use extention marketplace
![image](https://user-images.githubusercontent.com/47099020/194705640-4760f53b-73d0-4245-b4f7-6dfb9e67945a.png)

### Expected

searching extention in open-VSX

### Actual

cannot use extention marketplace
![image](https://user-images.githubusercontent.com/47099020/194705640-4760f53b-73d0-4245-b4f7-6dfb9e67945a.png)

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by minus43** [comment]
same issue in my server:(

**Comment by john-liuqiming** [comment]
same here

**Comment by jsjoeio** [comment]
Open VSX was down. Should be up now!
