### ISSUE TITLE
[Feat]: Experience without network

### ISSUE THREAD

**Issue by chenhuanguang** [coder/code-server#5656]
I have tested both in the local non network and in the local network. When I run the code server without the network, the file opened by the running vscode page does not change because of the file suffix, and the content in the file is not highlighted. Is there any solution
<img width="920" alt="image" src="https://user-images.githubusercontent.com/56351544/196107284-b6f730a9-6e90-4b44-a67e-7a900547c65b.png">

**Comment by chenhuanguang** [comment]
This is what I expected
<img width="990" alt="image" src="https://user-images.githubusercontent.com/56351544/196114628-3e9dccf4-9e22-4c4a-9a1d-c0a95880cad6.png">

**Comment by jsjoeio** [comment]
Hmm...maybe an extension you're using isn't able to work because you're offline? Are there any browser logs you can share?

**Comment by chenhuanguang** [comment]
<img width="1429" alt="image" src="https://user-images.githubusercontent.com/56351544/196332823-047f9970-acf6-4188-8a5f-f2be8331421a.png">
<img width="1420" alt="image" src="https://user-images.githubusercontent.com/56351544/196332862-5d9247cf-b757-407c-9ad8-e3a491159a0f.png">
