### ISSUE TITLE
[Feat]: Promote coder/coder in Get Started screen

### ISSUE THREAD

**Issue by ammario** [coder/code-server#5661]
Our [new project](https://github.com/coder/coder) is a natural extension of code-server and relevant to those attempting to set up code-server for their teams.

Let's add a loud callout to the Welcome Screen that says something to the effect of "Setting up code-server for a team? Check out coder/coder".

**Comment by jsjoeio** [comment]
To get to this, use Command Palette > Help: Get Started

Here's what it looks like: 

<img width="1712" alt="image" src="https://user-images.githubusercontent.com/3806031/197252800-ab8981cd-c54e-43bf-b9ba-e9425a871283.png">
