### ISSUE TITLE
[Bug]: Code server not work for POST (Apollo GraphQL)

### ISSUE THREAD

**Issue by Drilmo** [coder/code-server#5669]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome - Safari
- Local OS: MacOs IpadOS
- Remote OS: Ubuntu
- Remote Architecture: amd64
- `code-server --version`: 4.7.1

### Steps to Reproduce

1. open code-server
2. run Apollo GraphQL local with integrated terminal ( port 4001 and path /local/graphql)
3. go to url  domain/proxy/4001/local/graphql (GET work)
4. call url domain/proxy/4001/local/graphql with POST not work

### Expected

call url domain/proxy/4001/local/graphql with POST work

### Actual

Just get work

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by Drilmo** [comment]
> Can you provide a repo to reproduce this? Happy to look into it!

You can use this repo to reproduce : https://github.com/Drilmo/test

**Comment by Drilmo** [comment]
> Can you provide a repo to reproduce this? Happy to look into it!

@jsjoeio you can use this repo to reproduce : https://github.com/Drilmo/test

**Comment by jsjoeio** [comment]
Thank you!

So I cloned and ran `npm install`:

```shell
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@data-in-motion%2fauto-changelog - Not found
npm ERR! 404 
npm ERR! 404  '@data-in-motion/auto-changelog@^1.0.1' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jp/.npm/_logs/2022-10-20T17_17_29_577Z-debug-0.log
```

Decided to try [this](https://www.apollographql.com/docs/router/quickstart) and then when i access at localhost:8080/proxy/4000 I see the playground as expected:

<img width="1712" alt="image" src="https://user-images.githubusercontent.com/3806031/197016586-ae40485a-6426-4cc2-a083-831466d3bb01.png">

Then I added `router.yaml` with this:
```yaml
#
# supergraph: Configuration of the Supergraph server
#
supergraph:
  # The path for GraphQL execution
  # (Defaults to /)
  path: /graphql
```

and I was still able to access it, using localhost:8080/proxy/4000/graphql

<img width="1712" alt="image" src="https://user-images.githubusercontent.com/3806031/197017116-fe0977b9-291c-4928-b212-b51f6f343477.png">

Are you using a [relative path](https://www.apollographql.com/docs/router/configuration/overview#command-arguments)?

**Comment by Drilmo** [comment]
ho for the bug on "npm i" I have push fix (just remove dependance)

**Comment by Drilmo** [comment]
I don't use Apollo Router because I use Apollo Federation and this sample is a subgraph. it work on my local but not on local of code-server

**Comment by Drilmo** [comment]
@jsjoeio I forgot to specify 😅 I am on an EC2 AWS ubuntu but I used the ubuntu installer. Also I am using serverless framework to run lambda, as well as a DynamoDB locally.

**Comment by jsjoeio** [comment]
@Drilmo ahhh got it! What's the simplest way to run _only_ the Apollo part? That way we can isolate it and see if there's something wrong with Apollo (and so i don't have to spin up an EC2 instance 😅)

**Comment by Drilmo** [comment]
@jsjoeio, you can do this if you follow the readme on your code-server, this launch Apollo locally (with AWS).

But you need access key and secret key for aws-cli (on your code server) (it's free for local launch).

Have you access key and secret key ? (if you haven't  I can share you the necessary, but by another way than this chat for a minimum of security) 

Sorry if my English isn't perfect (I'm French)

**Comment by jsjoeio** [comment]
Is there a way to launch Apollo locally without AWS? I want to figure out where the problem is coming from.

> Sorry if my English isn't perfect (I'm French)

Oh don't worry - I didn't even notice!

**Comment by Drilmo** [comment]
> Is there a way to launch Apollo locally without AWS? I want to figure out where the problem is coming from.

@jsjoeio I just tried in standalone server mode (without serverless framework) and it works 😭 I think the problem occurs when I use the local aws part 😓

**Comment by Drilmo** [comment]
> Is there a way to launch Apollo locally without AWS? I want to figure out where the problem is coming from.

@jsjoeio I just tried in standalone server mode (without serverless framework) and it works 😭 I think the problem occurs when I use the local aws part 😓 started with serverless framework

**Comment by Drilmo** [comment]
@jsjoeio When I use serverless framework for local AWS Lambda I have this log : 
<img width="606" alt="image" src="https://user-images.githubusercontent.com/31286436/197143047-a2b52e0f-3a2a-490c-8ef4-0574e661816b.png">

And when I go to the url https://my-domain/proxy/4001/local/graphql it's work (for the GET) : 
<img width="1426" alt="Capture d’écran 2022-10-21 à 09 54 46" src="https://user-images.githubusercontent.com/31286436/197143913-b8ea4c35-8cf6-4a72-a3e8-1bb1e83232eb.png">
and I see my request in the log : 

<img width="788" alt="image" src="https://user-images.githubusercontent.com/31286436/197144308-23932c43-0a25-46eb-90d0-a90e19e3f230.png">


But when I try to use curl on bottom (POST request) of the previous screen I don't see anything on log. 

And if I click on "query your server" button, I can't contact the service with a POST request : 
<img width="522" alt="Capture d’écran 2022-10-21 à 10 01 03" src="https://user-images.githubusercontent.com/31286436/197145093-c2c3621d-e39a-47a8-8ac1-a94b85abefe2.png">

**Comment by jsjoeio** [comment]
Hmm...I wish I could be more helpful but I don't think we'll get to the bottom of this unless we can run Apollo without AWS in the equation. Based on what you've shared, I would bet there is something off about the expected path on Apollo's side. Maybe it's expecting an absolute URL instead of a relative one.

Two other ideas: what does `curl` log when you do the POST request?

Also when you're in the browser and see the red indicator, what browser logs do you see? what do you see in the network tab?

**Comment by Drilmo** [comment]
@jsjoeio do you think I can call you and share my screen for testing or anything else ?

**Comment by jsjoeio** [comment]
No, but you could record a screencast and post the video here!

**Comment by Drilmo** [comment]
@jsjoeio i have found my mistake ! I have juste an old version of Serverless-offline dependency
