### ISSUE TITLE
[Bug]: The workbench failed to connect to the server (Error: Failed to construct 'WebSocket': 

### ISSUE THREAD

**Issue by iamfaith** [coder/code-server#5675]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome
- Local OS: macOS
- Remote OS: Ubuntu
- Remote Architecture: amd64
- `code-server --version`:  1.71.2
74b1f979648cc44d385a2286793c226e611f59e7
x64

### Steps to Reproduce

1.  open code-server
2. connected with IPV6
3. Error: The workbench failed to connect to the server (Error: Failed to construct 'WebSocket': The URL 'ws://[[2409:8a55:223b:xxxxxxxxxxxxxx]]:8080/stable-74b1f979648cc44d385a2286793c226e611f59e7?reconnectionToken=58166be8-c072-4962-bfb5-dbb1d5edb8f7&reconnection=false&skipWebSocketFrames=false' is invalid.)

### Expected

The WebSocket should work and should not have duplicated brackets.

### Actual

Error: The workbench failed to connect to the server (Error: Failed to construct 'WebSocket': The URL 'ws://[[2409:8a55:223b:xxxxxxxxxxxxxx]]:8080/stable-74b1f979648cc44d385a2286793c226e611f59e7?reconnectionToken=58166be8-c072-4962-bfb5-dbb1d5edb8f7&reconnection=false&skipWebSocketFrames=false' is invalid.)

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by jsjoeio** [comment]
@code-asher any ideas on the duplicated brackets? 🤔 I'm not familair with IPV6 to be honest.

**Comment by code-asher** [comment]
A IPv6 address in the URL bar I believe will look like `http://[::1]` or `http://[::1]:8080` which then goes through this: https://github.com/microsoft/vscode/blob/74b1f979648cc44d385a2286793c226e611f59e7/src/vs/platform/remote/browser/browserSocketFactory.ts#L277

So looks like they are adding extra brackets whenever there is a `:`.

It seems to be fixed in 1.72.2 by checking if there is already a `[`: https://github.com/microsoft/vscode/blob/129500ee4c8ab7263461ffe327268ba56b9f210d/src/vs/platform/remote/browser/browserSocketFactory.ts#L277

**Comment by code-asher** [comment]
So in other words, should be fixed in our next release.

**Comment by huweiATgithub** [comment]
I also encounter this issue when using code-server with jupyter.
To reproduce:
- Run the code-server docker image, install jupyter and the vscode-jupyter extension
  ```bash
  sudo apt update && sudo apt-get install -y pip
  sudo pip install jupyter jupyterlab
  ```
- Open/create any `.ipynb` notebook.

**Comment by jsjoeio** [comment]
Hmm...any ideas on what could be causing that @code-asher?

**Comment by code-asher** [comment]
CSP could be the hash issue we are fixing in 4.8.1.

**Comment by huweiATgithub** [comment]
> CSP could be the hash issue we are fixing in 4.8.1.

I confirm that release 4.8.1 resolve the issue I described above.

**Comment by iamfaith** [comment]
> CSP could be the hash issue we are fixing in 4.8.1.

Confirmed fixed! Love u! Love code-server! I close this issue.
