### ISSUE TITLE
[Feat]: Please add "Vue 3 Snippets" extension in code server

### ISSUE THREAD

**Issue by CcRr0** [coder/code-server#5690]
## What is your suggestion?
Please add "Vue 3 Snippets" extension in code server
https://marketplace.visualstudio.com/items?itemName=hollowtree.vue-snippets
## Why do you want this feature?
I need this for my vue projects

**Comment by jsjoeio** [comment]
We use OpenVSX for our extension marketplace. If it's not there, please request the author to publish it there!
