### ISSUE TITLE
[Feat]: allow `code` cli to read from stdin as the vscode one

### ISSUE THREAD

**Issue by felipecrs** [coder/code-server#5693]
## What is your suggestion?

The `code` cli which comes with the VS Code's own server implementation (like Remote - WSL or Remote - Containers) allows the following:

```
echo 'text from stdout' | code -
```

https://user-images.githubusercontent.com/29582865/197561362-02237fd6-bc96-4670-b5c6-faf8422fa635.mp4

code-server's code cli fails with:

```console
$ echo 'text from stdout' | code -
[2022-10-24T15:13:30.253Z] error Unknown option -
```

## Why do you want this feature?

It's very useful so I can use the editor to analyze output of long-running commands like `docker logs -f`.

## Are there any workarounds to get this functionality today?

I tried but I did not find any.

## Are you interested in submitting a PR for this?

No plans.

**Comment by code-asher** [comment]
Ah the name is `code-server` in our case.  I tested `echo 'text from stdout' | code-server -` and it seems to work.

**Comment by felipecrs** [comment]
Interesting. So, why there are two CLIs then?

**Comment by code-asher** [comment]
I am not sure actually...I did not think we included any scripts
called `code`.  What do you get for `which code`?

**Comment by felipecrs** [comment]
Ops, actually it's just a symlink to code-server:

```console
ln -s /usr/local/lib/code-server/bin/code-server /usr/local/bin/code
```

This is done by the image I'm using.

And, that's very weird, see:

```console
❯ echo hi | code-server -
Reading from stdin via: /tmp/code-stdin-U2j
^C
❯ echo hi | code -
[2023-02-28T00:10:43.853Z] error Unknown option -
```

`code-server` indeed works but just `code` doesn't. I can't imagine why that's the case, so I decided to instead of using a symlink, to use a shim instead:

```sh
#!/bin/sh

exec code-server "${@}"
```

And now it works.

**Comment by felipecrs** [comment]
Maybe there is something wrong with the `code-server` CLI which makes it does not work if called from a symlink named just `code`, but I think the workaround is pretty acceptable.

**Comment by code-asher** [comment]
Ahhhhh I see, so there is the main script which launches the main 
code-server process and manages VS Code (this one is written by 
us):

```
/usr/local/lib/code-server/bin/code-server
```

And then there is the internal code-server script used in the 
integrated terminal (this one is written by Microsoft):
 
```
/usr/local/lib/code-server/lib/vscode/bin/remote-cli/code-server
```

The two scripts have some differences unfortunately.  I think 
there is an issue somewhere to delegate to Microsoft's script 
rather than try re-implementing everything since we miss things 
like this.

**Comment by code-asher** [comment]
Here it is: https://github.com/coder/code-server/issues/5414
