### ISSUE TITLE
[Docs]: How to install an extension that is not available for installation

### ISSUE THREAD

**Issue by marat2509** [coder/code-server#5694]
## What is your suggestion?
Installing an extension that is not available for installation from the extensions directory (in this case, GitHub Copilot is considered)
## How will this improve the docs?
Reduce the number of questions "How to install an extension ..., it is not searched in the extensions directory" and "Please add an extension ..., I do not know how to install it"
## Are you interested in submitting a PR for this?
Yes
___
Video guide:

https://user-images.githubusercontent.com/93652988/197567963-52808f65-7834-4620-8711-e3cea270272e.mp4

Also, instead of using the terminal, you can right-click in the workspace of the folder where the vsix file is located and select **Install Extension VSIX**:
![image](https://user-images.githubusercontent.com/93652988/197568727-74d1d23c-52d0-42a8-aea5-ccf96fbcb0f3.png)

**Comment by jsjoeio** [comment]
I think this would be a great thing to repost in our Discussions under Show and Tell!
