### ISSUE TITLE
[Bug]: Run and Debug not working

### ISSUE THREAD

**Issue by jefftuschool** [coder/code-server#5708]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome
- Local OS:  macOS
- Remote OS: Linux
- Remote Architecture:
- `code-server --version`: 4.8.0

### Steps to Reproduce

1. Open javascript or python file
2. set break point
3. Run and Debug

### Expected

Stop at break point

### Actual

Nothing happen

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

Version 4.7.1 was fine.

**Comment by ongood** [comment]
same as me

**Comment by niulinlnc** [comment]
I have the same problem, nothing happens after clicking debug or run, but in version 4.7.1 everything works fine.

**Comment by tobycm** [comment]
Can you provide logs please?

The code you're trying to debug would also be very helpful.
