### ISSUE TITLE
[Bug]: Trackpad Scrolling for Ipad with Magic Keyboard doesn't work anymore since IPadOS 16.1

### ISSUE THREAD

**Issue by CodeJunkie01** [coder/code-server#5714]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Safari / Firefox
- Local OS: IPadOS 16.1
- Remote OS: Ubuntu
- Remote Architecture: amd64
- `code-server --version`: 4.8.0

### Steps to Reproduce

1. connect to code-server via Ipad over secure connection (Firefox or Safari Browser)
2. try to scroll with the trackpad of the magic keyboard 

### Expected

vertical scrolling motion

### Actual

nothing

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

Scroll via Touch does work. I have seen that this was a problem in IPad OS versions up to 14.5.

**Comment by CodeJunkie01** [comment]
Just checked: using a mousewheel doesn't work either

**Comment by jsjoeio** [comment]
Hmm...and you can't reproduce in vscode.dev or Codespaces?

**Comment by CodeJunkie01** [comment]
Okay my bad, was sure I had already used vscode.dev on IPadOS 16 but must have been wrong. Doesn't work there either. Thanks for your time anyways!

**Comment by jsjoeio** [comment]
Can you open an issue upstream? Thank you!

**Comment by CodeJunkie01** [comment]
[This](https://github.com/microsoft/vscode/issues/164220) seems to be the corresponding issue on the vscode-repo. For anyone stumbling over this post here, a workaround for now seems to be to turn on/off/on stagemanager.
