### ISSUE TITLE
[Bug]: automatic hyperlinking broken in 4.8.0?

### ISSUE THREAD

**Issue by drmrbrewer** [coder/code-server#5716]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome
- Local OS: Windows
- Remote OS: Ubuntu 22.04
- Remote Architecture: x64
- `code-server --version`: `1.72.1` (that's the version of vscode I think?  code-server version is `4.8.0`... see screenshot below)

![image](https://user-images.githubusercontent.com/9009792/198267269-640e4a55-c459-462a-8b3a-16a28a9b5803.png)

### Steps to Reproduce

1. open code-server
2. open code file including URL in the comments
3. ctrl-click on the automatically-hyperlinked URL

### Expected

Should open the linked page in a new page of the browser.

### Actual

Nothing... except "Activating extensions..." indication in status bar at bottom:

![image](https://user-images.githubusercontent.com/9009792/198267667-e589a99b-cc75-425b-b160-85a4085d2817.png)

This indication just disappears after a short time, but nothing else happens.  Nothing in the browser console log either.

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

This was working fine before... think it broke with the update to `v4.8.0`?

It is also broken (but was working before) for hyperlinks from URLs in the terminal window.

**Comment by jsjoeio** [comment]
Can you try 4.8.1's release candidate? I'm guessing this is the same CSP error we have in 4.8.0

**Comment by drmrbrewer** [comment]
I answered this myself by trying it :)

Yes, installing as per my previous post has indeed installed the release candidate version:

![image](https://user-images.githubusercontent.com/9009792/198375839-a18bd275-8b25-49ed-b7a9-e65f56a4ad08.png)

And yes, the hyperlinking issue I reported at the top is fixed by the release candidate!

**Comment by jsjoeio** [comment]
LOL hey at least you're proactive! Thank you for confirming! I'll close for now and add to the 4.8.1 milestone.
