### ISSUE TITLE
[Bug]: Cannot attach / open JavaScript Debug Terminal

### ISSUE THREAD

**Issue by jeengbe** [coder/code-server#5726]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: 107.0.5304.62 (Official Build) beta (64-bit) (cohort: Beta) 
- Local OS: Microsoft Windows 11 (10.0.22621 Build 22621)
- Remote OS: Debian GNU/Linux 11 (bullseye)
- `code-server --version`: _the latest 4.8.0 on Docker Hub_

### Steps to Reproduce

1. open code-server with the Docker Hub Image
2. Try to open JavaScript Debug Terminal

### Expected

Good ol' debugging experience

### Actual

Nothing.
No errors, no alert, and the terminal doesn't open.

When trying to attach (Via Command Palette or Launch Configuration), the little bar appears and breakpoints are shown as attached, but code execution is never halted.

### Logs

This and further steps require more time than I currently have available. If not reproducible, ping me and I will provide them.

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

Haven't actually tried on Codespaces since I don't have that.

**Comment by jsjoeio** [comment]
This should be fixed in 4.8.1!
