### ISSUE TITLE
No working Terminal on iPad

### ISSUE THREAD

**Issue by XgamerTV** [coder/code-server#5737]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: iOS Safari, iOS Chrome
- Local OS: Windows 11
- Remote OS: iOS
- Remote Architecture:
- `code-server --version`: Newest

### Steps to Reproduce

1. Open code-server on iPad (Air 2020, Pro 2020)
2. Try to use the terminal
3. Run a File

### Expected

When trying to run a file or use the terminal nothing happens except the Word: Windows or Install s displayed (See Screenshot)
On a Browser in Windows the terminal works. 

### Actual

-

### Logs

No logs

### Screenshot/Video

![BD531D22-0E3D-4465-8495-E03B147F762C](https://user-images.githubusercontent.com/46219029/198888350-c9788d6e-8209-4f64-a356-129186203169.jpeg)

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by jsjoeio** [comment]
Hmm 🤔 So it's installed on you Windows machine, and you're accessing it via an iPad... are there any server logs that show up? And does the terminal work when accessing from your Windows machine?

**Comment by XgamerTV** [comment]
> Hmm 🤔 So it's installed on you Windows machine, and you're accessing it via an iPad... are there any server logs that show up? And does the terminal work when accessing from your Windows machine?

Yeah no logs and the Terminal works perfectly on Windows

**Comment by jsjoeio** [comment]
Hmm...so I don't have Windows 11 to test. Would you be comfortable letting me open up your instance on my iPad? I have an app that lets me see the console so I could look there. If you are, email me at joe at coder . com and I can take a look.

**Comment by XgamerTV** [comment]
So the terminally works well on your iPad with Windows 10? I have access to another Windows 10 device so I'll just check myself if it works but thanks for the offer. One question regarding the code-server in general: How do I remove tunnels? I reinstalled it with "code-server uninstall" but the tunnel(names) are still not available...

Thx in advance

**Comment by jsjoeio** [comment]
Oops, I should be more specific - I don't have _any_ Windows device personally to test on. I only have code-server installed on my mac. Okay sounds good!

Remove tunnels...Hmm...could you elaborate? Which tunnels are you referring to? Like port-forwarded tunnels?

**Comment by XgamerTV** [comment]
Ah I see but it works well with the mac and iPad right?
I guess the port-forwarded Tunnels (the ones that you create when using code-server command).
And do you actually have to port-forward anything yourself when using code-server outside of the home network?

**Comment by jsjoeio** [comment]
Yes, it does!

Well since code-server is running on my main machine, no I don't. So for instance, I'll run code-server locally on localhost:8080, open as a PWA, start my project on localhost:3000 and then open it in the browser. No forwarding needed since it's all on the same machine fortunately. 

For removing tunnels you previously forwarded using the Ports panel, you should be able to right-click and remove or delete port.

**Comment by XgamerTV** [comment]
Hi!
Sorry for the long break....I had a lot of university stuff to do.

I used the code server wrongly (only through terminal and not with the extension)!

Everything works perfectly now!

**Comment by jsjoeio** [comment]
Hooray!
