### ISSUE TITLE
[Bug]: can't change protocol in ports panel

### ISSUE THREAD

**Issue by jsjoeio** [coder/code-server#5739]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: any
- Local OS: macOS
- Remote OS: macOS
- Remote Architecture: Intel
- `code-server --version`: 4.8.1

### Steps to Reproduce

1. run code-server
2. forward a port
3. open ports panel and change protocol to HTTPS

### Expected

It should work

### Actual

It doesn't and the forwarded URL stays the same.

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

Mentioned on Discord

**Comment by code-asher** [comment]
I reproduced in Codespaces.
