### ISSUE TITLE
[Bug]: No working Terminal on FreeBSD 13.1-RELEASE-p2

### ISSUE THREAD

**Issue by ilovebsd** [coder/code-server#5741]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome
- Local OS: Windows 10
- Remote OS: FreeBSD 13.1-RELEASE-p2 Jails
- Remote Architecture: amd64
- `code-server --version`: 4.8.1

### Steps to Reproduce

1. open code-server on Chrome
2. New Notification "The connection to the terminal's pty host process is unresponsive, the terminals may stop working."
3. Repeated "Restart pty host"

### Expected

pty host must operate normally

### Actual

Terminal is not working.

### Logs

[17:00:43] ptyHost was unable to resolve shell environment Error: Unable to resolve your shell environment: Unexpected exit code from spawned shell (code 1, signal null)
    at /usr/local/lib/node_modules/code-server/lib/vscode/out/vs/server/node/server.main.js:92:2607
    at async /usr/local/lib/node_modules/code-server/lib/vscode/out/vs/server/node/server.main.js:67:23805
[IPC Library: Pty Host] The factory function of "vs/platform/terminal/node/ptyHostMain" has thrown an exception
[IPC Library: Pty Host] Error: Platform not supported
    at E (/usr/local/lib/node_modules/code-server/lib/vscode/out/vs/platform/terminal/node/ptyHostMain.js:19:811)
    at y (/usr/local/lib/node_modules/code-server/lib/vscode/out/vs/platform/terminal/node/ptyHostMain.js:19:110)
    at new E (/usr/local/lib/node_modules/code-server/lib/vscode/out/vs/platform/terminal/node/ptyHostMain.js:19:1504)
    at Object.<anonymous> (/usr/local/lib/node_modules/code-server/lib/vscode/out/vs/platform/terminal/node/ptyHostMain.js:27:17502)
    at Function.s._safeInvokeFunction (/usr/local/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:5:1337)
    at Function.s._invokeFactory (/usr/local/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:5:1522)
    at s.complete (/usr/local/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:5:1801)
    at s._onModuleComplete (/usr/local/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:6:1112)
    at s._onModuleComplete (/usr/local/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:6:1358)
    at s._onModuleComplete (/usr/local/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:6:1358)
    at s._onModuleComplete (/usr/local/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:6:1358)
    at s._onModuleComplete (/usr/local/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:6:1358)
    at s._resolve (/usr/local/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:6:510)
    at s.defineModule (/usr/local/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:5:6066)
    at n (/usr/local/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:5:10527)
    at Object.R (/usr/local/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:6:6036)
    at Function.s._safeInvokeFunction (/usr/local/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:5:1337)
    at Function.s._invokeFactory (/usr/local/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:5:1522)
    at s.complete (/usr/local/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:5:1801)
    at s._onModuleComplete (/usr/local/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:6:1112)
    at s._onModuleComplete (/usr/local/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:6:1358)
    at s._resolve (/usr/local/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:6:510)
    at s.defineModule (/usr/local/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:5:6066)
    at y (/usr/local/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:6:1825)
    at h (/usr/local/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:4:2554)
    at Object.<anonymous> (/usr/local/lib/node_modules/code-server/lib/vscode/out/vs/platform/terminal/node/ptyHostMain.nls.js:3:61)
    at e._createAndEvalScript (/usr/local/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:4:2598)
    at /usr/local/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:4:2237
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)
[IPC Library: Pty Host] Here are the modules that depend on it:
[IPC Library: Pty Host]% [ '===anonymous1===' ]
[17:00:43] [192.168.0.104][5ee7cc5d][ExtensionHostConnection] Unknown reconnection token (never seen).
[17:00:43] [192.168.0.104][eb8a76c1][ManagementConnection] Unknown reconnection token (never seen).
[IPC Library: Pty Host] Unknown channel: heartbeat
[IPC Library: Pty Host] Unknown channel: log
[IPC Library: Pty Host] Unknown channel: ptyHost
[IPC Library: Pty Host] Unknown channel: ptyHost
[IPC Library: Pty Host] Unknown channel: ptyHost
[IPC Library: Pty Host] Unknown channel: ptyHost
[IPC Library: Pty Host] Unknown channel: ptyHost
[IPC Library: Pty Host] Unknown channel: ptyHost
[IPC Library: Pty Host] Unknown channel: ptyHost

### Screenshot/Video

![bug](https://user-images.githubusercontent.com/73726122/199188211-11200363-48e4-424c-af00-0f0f4246a9b2.JPG)

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes
It works fine in other jails environments.
 - FreeBSD 13.1-RELEASE-p2
 - node14-14.18.1_1
 - npm-node14-6.14.8_1
 - code-server v4.0.2

**Comment by olegsidorkin** [comment]
The same thing happens with code-server 4.8.1/ node16 / FreeeBSD 13.

**Comment by code-asher** [comment]
>  [IPC Library: Pty Host] Error: Platform not supported

Was code-server installed via `npm`?  If so then I am not sure why `node-pty` is saying the platform is not supported.  :thinking:

**Comment by ilovebsd** [comment]
Installed in the order below
 - pkg install node16-16.16.0 npm-node16-8.19.1 pkgconf libsecret
 - curl -fsSL https://code-server.dev/install.sh | sh

**Comment by olegsidorkin** [comment]
After looking at compiled JS, i think it's here: https://github.com/microsoft/vscode/blob/9db57e76e9f16f552203585a394e50cf0f7a84a7/src/vs/platform/environment/node/userDataPath.js#L98

**Comment by ilovebsd** [comment]
I changed the default shell to bash or zsh and solved the problem by referring to the link below.

[https://github.com/coder/code-server/issues/5496#issuecomment-1240839804](url)

**Comment by olegsidorkin** [comment]
> I changed the default shell to bash or zsh and solved the problem by referring to the link below. Thank you @kawanakaiku
> 
> [#5496 (comment)](https://github.com/coder/code-server/issues/5496#issuecomment-1240839804)

Yes, this helped. Terminal started to work after patching with sed.

**Comment by ykla** [comment]
> I changed the default shell to bash or zsh and solved the problem by referring to the link below. Thank you @kawanakaiku
> 
> [#5496 (comment)](https://github.com/coder/code-server/issues/5496#issuecomment-1240839804)

It seems not work now. Hereis no `(process.platform` in `usr/local/lib/node_modules/code-server/lib/vscode/out/vs/platform/terminal/node/ptyHostMain.js`.

**Comment by ykla** [comment]
Not Work now.

**Comment by rowheel** [comment]
> Not Work now.

Didn't work indeed. However, it seems like an upstream issue so complaining coder/code-server may not work as intended.

I just fired some PRs at microsoft/node-pty and microsoft/vscode to see if they can give us a chance to give reviews and probably approve those fixes.

Hopefully that helps.

-RW

**Comment by dch** [comment]
thanks! @rowheel do you have a branch somewhere including all your fixes? If this works atm I'd like to get it into ports proper.

**Comment by katrinabryce** [comment]
> thanks! @rowheel do you have a branch somewhere including all your fixes? If this works atm I'd like to get it into ports proper.

My process for installing it is:

```
npm install -g code-server --unsafe-perm
cd /usr/local/lib/node_modules/code-server/
npm install --unsafe-perm
sed -i -e 's|switch(process.platform)|switch("linux")|' /usr/local/lib/node_modules/code-server/lib/vscode/out/vs/platform/terminal/node/ptyHostMain.js
```
The patch is based on the comment referred to further up this thread.
A lot of dependencies don't install first time round, hence the second installation round.
Works for 4.16.1. 4.17.0 isn't on npm yet.

**Comment by code-asher** [comment]
Closing for now, but if this is still a problem and there is something we can fix on code-server's end, let me know.

**Comment by 0x1eef** [comment]
I can confirm [the suggested fix](https://github.com/coder/code-server/issues/5741#issuecomment-1740769125) still works for terminal support on FreeBSD. But at the time of writing we need a couple of patches for code-server to work as expected on FreeBSD. I've incorporated all of them into [a port](https://github.com/0x1eef/myports/tree/main/freebsd/www/code-server).  I hope it might help someone else out there.

**Comment by dch** [comment]
port looks good. Can we add it to ports tree? I can commit it if you agree. dch@

**Comment by 0x1eef** [comment]
Unfortunately I don't think it is possible. It would require more work. 
See https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=256144. 

> Ok, I think (from my limited experience in this topic of npm-based ports) this port won't pass Poudriere test port, since internet access in do-install is forbidden, but is required here from npm install.
> There aren't many nodejs/npm based ports, and I am not sure what the best way is to solve this problem. A possible way is to pre-fetch and package the node_modules and serve it off for this port. Please take a look at misc/netron/Makefile, and I can possibly help you in the process.

**Comment by rowheel** [comment]
@0x1eef I know someone who added code-oss to the Ports tree and then the Pkg collection. Basically their method is to package all needed node modules in a static tarball and upload it somewhere, then download the tarball in the Makefile as part of the source code to fill the build dependency.

Check [tagattie/FreeBSD-VSCode](https://github.com/tagattie/FreeBSD-VSCode) for details. Likely that your Port will have to take a similar approach.

Hi @tagattie , if that's not too much to ask, can you kindly share how you maintained your Port? I believe @0x1eef can use some guidance.

**Comment by tagattie** [comment]
@0x1eef As already mentioned, the official FreeBSD package builders do not allow network access except for the fetch phase. So we have to prepare a tarball which contains all the necessary node modules in advance and host it somewhere. I (ab)use GitHub releases pages for this purpose.

In case of VSCode, it is a bit complicated because multiple package.json/package-lock.json are involved.
(https://github.com/tagattie/FreeBSD-VSCode/blob/master/editors/vscode/Makefile#L289)

But the basics should be applicable to any node-based ports. Hope this helps.

**Comment by ykla** [comment]
> [@0x1eef](https://github.com/0x1eef) As already mentioned, the official FreeBSD package builders do not allow network access except for the fetch phase. So we have to prepare a tarball which contains all the necessary node modules in advance and host it somewhere. I (ab)use GitHub releases pages for this purpose.

Is it possible to provide feedback to the FreeBSD Core Team requesting a modification to the Ports system build process? The number of packages that cannot be fully downloaded during the `fetch` phase will only continue to grow ( such as JavaScript/npm、Python/pip、Rust/cargo), making porting increasingly difficult. For example, a flag could be added to such Ports to indicate that they require downloading before building. If the concern is maintaining clean builds, such software could be built separately.

Under the current state of the internet, requiring completely offline builds is an impractical approach.

Off-topic: In fact, I believe the current Ports framework can no longer keep up with present-day realities. I’ve never understood why a software’s version number must be rigidly tied to its download URL—this serves no purpose other than making the work of port maintainers more frustrating. Although Gentoo's Portage originated from the BSD Ports system, I believe it's now time for BSD Ports to move closer to Gentoo's approach.

**Comment by rowheel** [comment]
@ykla While I appreciate your view, I don't believe BSD would take this pill. 

Not every applications written in modern languages like JavaScript and/or Python will declare their dependencies in decisive manner. Most likely they will use formulas like `ver ∈ (ver_min, ver_max)` as their dependency, which in return introduces the build timestamp as a new influence factor towards the software behavior.

Ultimately it all comes down to reproducibility, and reproducibility is mandatory for an industrial usage. If a checkout of Port should be built, regardless of when to build it, it must produce binaries with the exact same behavior, be it building it today or five years from now.

Therefore, dependency based on version range is unacceptable. However, if the dependency is decisive, one should be able to prepare the dependency before hand and compile everything in a totally offline environment.

I believe that's why that offline policy was made back then.

**Comment by dch** [comment]
@ykla as a project, FreeBSD is moving further and further towards reproducible
builds. All of the packages shipped from `*.freebsd.org` are tightly constrained
to *only* have access to the explicit tarballs listed in distinfo.

This provide a very significant level of trust for our downstream users, and
not something to be tampered with lightly.

We do have ports that deal with this situation, such as [www/tailwindcss3](https://cgit.freebsd.org/ports/tree/www/tailwindcss3/Makefile)
and others, requiring preparing an npm cache prior.

We can do this for code-server as well. It's not pretty, and arguably it's
not much fun to navigate the first time you go through the setup.

**Comment by 0x1eef** [comment]
Thanks a lot @tagattie !

I made some progress in [this pull request](https://github.com/0x1eef/myports/pull/10). 
It includes:

- Download the source from this github repository instead of via npm
- Download `vscode-node-modules-*.tgz` and `code-server-node-modules-*.tgz` at the fetch phase
- Both tarballs include a build I did manually and then packaged for download

The packaging part still needs to be automated. And maybe I need to rebuild the node_modules directory similar to what @tagattie is doing. I think we're headed in the right direction though.

**Comment by 0x1eef** [comment]
Hi folks!

Progress update 😄 The last effort installed code-server but it was broken, 
and there was a lot of work to do. I included these changes in 
[a new pull request](https://github.com/0x1eef/myports/pull/11). 

It installs code-server successfully, fetches all dependencies as 
tarballs (including vscode), and applies all but one patch from 
[patches/](https://github.com/coder/code-server/tree/main/patches).
The patch which failed to apply - need to investigate/fix. 

One caveat is that I'm bundling a full release of code-server as a 
tarball, and extracting it to `work/code-server-X.X.X/release`. 
That's what is eventually staged. I'm not sure this is acceptable, 
or if more could be done on the machine installing the port. I think
there's more work to do on this front. 

@dch I think we've made more progress but probably still aren't entirely there yet.
Are you interested in working together to land this change in the ports tree ?
Let me know and I can reach out by mail. Cheers

**Comment by dch** [comment]
> @dch <https://github.com/dch> I think we've made more progress but 
> probably still aren't entirely there yet.
> Are you interested in working together to land this change in the ports 
> tree ?
> Let me know and I can reach out by mail. Cheers

yes please,

**Comment by 0x1eef** [comment]
I reached out by mail :) I also packaged code-server 4.102.1 with vscode 1.102.1 earlier today. As long as FreeBSD is okay with distributing a release of code-server we should be good. Otherwise more work to do. Let's take the discussion to mail. I'm also on irc: o0x1eef / irc.libera.chat. Cheers.

**Comment by rowheel** [comment]
Hello @0x1eef 
It's been one month, have you made any progress? 
(Totally fine if nothing has been made since. Not pushing, just asking)

**Comment by 0x1eef** [comment]
Hello @rowheel 🙂 

> (Totally fine if nothing has been made since. Not pushing, just asking)

No worries. 

> It's been one month, have you made any progress?

I have been using [the port](https://github.com/0x1eef/myports/tree/main/freebsd/www/code-server) successfully for last month or so. I added documentation that explains how it works. Essentially a port maintainer would build a release tarball, and upload it to GitHub releases. Then the tarball is distributed as a port. I'm not sure if this is acceptable for FreeBSD (@dch thinks it won't be), and once dch returns from a break, we plan to work on this together, possibly so it is acceptable for FreeBSD.

**Comment by 0x1eef** [comment]
FWIW the latest version (4.106.2) is available ([commit](https://github.com/0x1eef/myports/commit/3a6100266a3268c234e8000873bca1984904e23e)) and brought with it some new build challenges. That's probably the last update from my side. I will continue to maintain the port, though, for anyone who wants to use it.

**Comment by 0x1eef** [comment]
code-server has landed in the ports tree 😄 
https://github.com/freebsd/freebsd-ports/commit/a73cae2fd8948279ab7467aa82d34fdb8cd10833
