### ISSUE TITLE
[Docs]: Add new termux installation method 

### ISSUE THREAD

**Issue by T-Dynamos** [coder/code-server#5745]
Happy to announce that code-server was added in [tur](https://github.com/termux-user-repository/tur) in https://github.com/termux-user-repository/tur/pull/137
Now it can installed without proot
```
pkg install tur-repo
pkg install code-server
```

**Comment by jsjoeio** [comment]
Wow! This is incredible! Who do we thank?

**Comment by T-Dynamos** [comment]
> Who do we thank?
@licy183

**Comment by code-asher** [comment]
Incredible, we may want to use this in the install script as well when we detect Termux.

**Comment by T-Dynamos** [comment]
Ok, I will update it on tur

**Comment by jsjoeio** [comment]
@T-Dynamos can you link the PR after? Once I see it I can evaluate how difficult it would be for us to automatically update it similar to how we do it for code-server-aur.

See here:

https://github.com/coder/code-server/blob/main/.github/workflows/publish.yaml#L70-L124

**Comment by im-coder-lg** [comment]
Or maybe just add a curl script to the build.sh file that requests for the latest version when demanded. How about that?

Hint if possible: we can use the GitHub API for this.

**Comment by licy183** [comment]
> Or maybe just add a curl script to the build.sh file that requests for the latest version when demanded. How about that?
> 
> Hint if possible: we can use the GitHub API for this.

I've enabled auto-updating downstream (https://github.com/termux-user-repository/tur/pull/145), so don't worry about that.

**Comment by yazigegeda** [comment]
![Screenshot_2022-11-20-12-46-04-85_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/63853093/202886091-e101d147-8de4-41f1-9fa9-ac5b9430d656.jpg)

I visited 127.0.0.1:8080 and successfully entered the password, but Forbidden appeared

**Comment by licy183** [comment]
I forget to apply the patches used by `code-server`. Should be fixed in termux-user-repository/tur#154.

**Comment by licy183** [comment]
I forget to apply the patches used by `code-server`. Should be fixed in termux-user-repository/tur#154.
