### ISSUE TITLE
[Docs]: C/C++ debug not working

### ISSUE THREAD

**Issue by sakthivel-axim** [coder/code-server#5764]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome
- Local OS: Ubuntu 18.04
- Remote OS: Debian
- Remote Architecture: BeagleBone (armhf)
- `code-server --version`: 4.8.1

### Steps to Reproduce

1. Download and install using `dpkg -i <package.deb>`
2. Add launch.json with type `cppdbg`
3. Able to compile and execute. But debug not working.

### Expected

Able to debug

### Actual

Throws error `Configured debug type 'cppdbg' is not supported.`

### Screenshot/Video

![image](https://user-images.githubusercontent.com/55696493/200545516-97b48283-5b10-4548-8683-efc9c39b86bd.png)

### Does this issue happen in VS Code or GitHub Codespaces?

- [ ] I cannot reproduce this in VS Code.
- [ ] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [ ] I am using HTTPS.

### Notes

Installed the .deb package in BeagleBone board. Running over HTTP.

**Comment by jsjoeio** [comment]
I think the CPP debugger is in the MSFT extension which we can't use in code-server (based off [this](https://github.com/VSCodium/vscodium/issues/750)) so I don't think there's anything we can do here sadly.

cc @code-asher are there any workarounds that you know of?

**Comment by sakthivel-axim** [comment]
Thanks, @jsjoeio. Understand that cannot use `cppdbg`. Please let me know the possibilities to use `gdb` for debugging in Debian environment.

**Comment by jsjoeio** [comment]
> Understand that cannot use cppdbg. Please let me know the possibilities to use gdb for debugging in Debian environment

None that I know of but maybe @code-asher knows

**Comment by code-asher** [comment]
The only open-source version of the Microsoft C++ extension I know of is https://open-vsx.org/extension/llvm-vs-code-extensions/vscode-clangd but I have never used it so I am not sure how/if debugging works.

**Comment by a279437145** [comment]
I can have cpp debugging working on code-server running on my Raspberry pi (Ubuntu 22.04 , arm64) , I installed https://github.com/Microsoft/vscode-cpptools (there are `armhf` builds), you may try it . (It can work even without https)

**Comment by Adaptrum-Planetad** [comment]
Thanks @a279437145 . I have tried to search for the extension on code-server but it doesn't show. Could you please share config/steps to bring up? It will be helpful.

**Comment by sakthivel-axim** [comment]
Thanks you @a279437145 .

I have tried to install but it doesn't show in extension. Could you please share config/steps to bring up? It will be helpful.

**Comment by a279437145** [comment]
yep , it's not in the openVSX extension gallery , so you cant install it directly.
I downloaded the vsix from https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools
and chose the `Download extension`option in the right , then choose the right one for you
you are on armhf ubuntu , so you should choose `Linux arm32` , like this:
![IMG_20221123_171335](https://user-images.githubusercontent.com/75509566/203509374-59e54e6f-e478-4027-b71d-29a3073129d6.jpg)

then put it on your code-server and install, the way to install exis extensions are described in the code-server docs

**Comment by sakthivel-axim** [comment]
Thanks @a279437145 . I will try to setup. Please share your `tasks.json` and `launch.json`, it helps a lot. Thanks once again.

**Comment by a279437145** [comment]
the files are here
[launch.txt](https://github.com/coder/code-server/files/10075220/launch.txt)
[tasks.txt](https://github.com/coder/code-server/files/10075222/tasks.txt)
change the attribute to .json(I can't upload json files to github directly),and please ignore the python configuration in `launch.json`
it should work like this
![Screenshot_2022-11-23-19-58-51-30_3aea4af51f236e4932235fdada7d1643](https://user-images.githubusercontent.com/75509566/203542501-cdb357e9-823c-43ba-84a9-87373286033e.jpg)
I cant use computer now so I did that on phone , the screenshot may somehow look a bit strange,regret~

**Comment by sakthivel-axim** [comment]
It's working. Thank you @a279437145.

**Comment by a279437145** [comment]
Great , you are welcome.

**Comment by sakthivel-axim** [comment]
> yep , it's not in the openVSX extension gallery , so you cant install it directly. I downloaded the vsix from https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools and chose the `Download extension`option in the right , then choose the right one for you you are on armhf ubuntu , so you should choose `Linux arm32` , like this: ![IMG_20221123_171335](https://user-images.githubusercontent.com/75509566/203509374-59e54e6f-e478-4027-b71d-29a3073129d6.jpg)
> 
> then put it on your code-server and install, the way to install exis extensions are described in the code-server docs
> 
> Also if you want i can provide my `tasks.json`and`launch.json`

Debugging is working with help of this.
