### ISSUE TITLE
Keyboard inputs glitching

### ISSUE THREAD

**Issue by DANIHEX** [coder/code-server#5780]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Opera Android
- Local OS: Android 11
- Remote OS: Ubuntu on Termux
- Remote Architecture: arm64
- `code-server --version`: 4.8.3

### Steps to Reproduce

1. Start code server
2. Open a file on code server
3. Hit Tab or Hit Enter on suggestions

### Expected

Auto complete on suggestions when hitting Enter
Insert 4 spaces when hitting tab

### Actual

Hitting Enter key closes suggestions and only inserts new line
Hitting Tab key closes keyboard and selects status bar on bottom

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

Hi, I don't know if this is happening only to me but when I press Tab key it doesn’t insert 4 spaces it selects status bar strangely or when I press Enter key it don't auto complete, it just inserts new line even if it set to auto complete in settings.
Looks like the whole keyboard is glitching or maybe code-server is reading keyboard inputs incorrectly(In settings keyboard short cuts when enabling read input, it doesn’t recognize Tab and Enter, it says “unknown”).
Is this a bug? Or how can I fix this?
Thanks!

**Comment by inkwise** [comment]
我也一样
