### ISSUE TITLE
[Feat]: add option to disable link protection for code-server

### ISSUE THREAD

**Issue by jingjinghahah** [coder/code-server#5785]
## What is your suggestion?

add option to disable link protection for code-server

<img width="586" alt="image" src="https://user-images.githubusercontent.com/45445596/202073518-5cba9715-0885-4316-84fe-5810d99a7f41.png">

**Comment by code-asher** [comment]
I think the only way we would add this is if VS Code added it but I am not seeing that they are allowing this.

This might allow preconfiguring domains though: https://github.com/microsoft/vscode/issues/82794
