### ISSUE TITLE
[Bug]: Can't serve behind proxy under path

### ISSUE THREAD

**Issue by jaimehrubiks** [coder/code-server#5789]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: All
- Local OS: All
- Remote OS: Linux
- Remote Architecture: Intel
- `code-server --version`: 20220909.27

### Steps to Reproduce

1. Install: RUN wget -O- https://aka.ms/install-vscode-server/setup.sh | sh

Or: curl -fsSL https://code-server.dev/install.sh | sh

3. Run: code-server serve-local --accept-server-license-terms --connection-token=1234 --host 0.0.0.0 --port 8080

4. Setup nginx reverse proxy:

I use kubernetes:

    nginx.ingress.kubernetes.io/rewrite-target: /$2
    path: /vscode/jaime-devenv(/|$)(.*)

but nginx would look similar to:
	
    location ~* "^/vscode/jaime-devenv(/|$)(.*)
    ...
    ... rewrite "(?i)/vscode/jaime-devenv(/|$)(.*)" /$2 break;

5. Open chrome at:

https://example.com/vscode/jaime-devenv?tkn=1234

and

https://example.com/vscode/jaime-devenv

### Expected

Page should load. Assets should be relative.

Also, this part of the documentation hints that this should be possible https://coder.com/docs/code-server/latest/guide#using-lets-encrypt-with-caddy

### Actual

Page won't load because index html will have absolute links instead of relative links.

### Screenshot/Video

<img width="467" alt="Screen Shot 2022-11-17 at 11 14 45 AM" src="https://user-images.githubusercontent.com/965036/202513084-7e8b39ee-e12c-43a3-b47c-d9072217837e.png">

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [x] I am using HTTPS.

### Notes

I apologize in advance if I missed something, but I've tried to read all the issues related to this topic and I could not solve it. I've seen that the behavior changed in a big refactor of vscode-server, in fact, it worked for me in a version from a couple years ago, but can't find it anymore. 

From my understanding, vscode-server devs prefer the relative path route than setting a base-url variable, so that is why I expected this to work out of the box.

**Comment by jaimehrubiks** [comment]
Lol can't believe I was so confused with those two. It works perfect with coder/code-server. Thanks!

**Comment by jsjoeio** [comment]
Believe me, you are not the first 😅 Hooray!
