### ISSUE TITLE
[Bug]: Can't shift Jupyter server remote to local one

### ISSUE THREAD

**Issue by ODtian** [coder/code-server#5793]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Edge
- Local OS: Windows 11 22H2
- Remote OS: Centos8
- Remote Architecture: amd64
- `code-server --version`: 4.8.3

### Steps to Reproduce

1. open an ipynb
2. shift local runtime to remote server
3. shift remote to local(None)

### Expected

when shift to local(None), use lcoal kernal

### Actual

no kernal found

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by jsjoeio** [comment]
> shift local runtime to remote server

How do I do this? Sorry I don't work with Jupyter normally.

**Comment by code-asher** [comment]
Closing as stale.
