### ISSUE TITLE
[Feat]: Confirmation required when backward/forward key is pressed

### ISSUE THREAD

**Issue by hunkus** [coder/code-server#5794]
## What is your suggestion?
Confirmation required when backward/forward key is pressed

## Why do you want this feature?
When you accidentally press backward/forward key, the working environment is blown away.

## Are there any workarounds to get this functionality today?
Nope

## Are you interested in submitting a PR for this?
Not yet.

**Comment by code-asher** [comment]
This is a browser limitation, but it can be worked around by launching as a PWA.

**Comment by code-asher** [comment]
Oh also confirmation is something that should happen if there are edits!  VS Code does not require confirmation if there are no edits, from what I can tell, but we could open an issue upstream to see if they are willing to change this.
