### ISSUE TITLE
[Bug]: Search not working

### ISSUE THREAD

**Issue by gbrian** [coder/code-server#5820]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome
- Local OS: Docker
- Remote OS: coder Docker image
- Remote Architecture: amd64
- `code-server --version`: v4.8.3
- `Code`:  1.72.1
- `Commit`:  129500ee4c8ab7263461ffe327268ba56b9f210d
- `Date`:  2022-11-07T18:19:38.940Z (3 wks ago)
- `Browser`:  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36

### Steps to Reproduce

Sorry no idea how this happened just stopped working

### Expected

Get search results

### Actual

No results at all for any kind of search

### Logs

Logs show no errors. Search does not produce any log entry

### Screenshot/Video

https://www.youtube.com/watch?v=3PA1NcCzGbU
[![IMAGE ALT TEXT](http://img.youtube.com/vi/3PA1NcCzGbU/0.jpg)](http://www.youtube.com/watch?v=3PA1NcCzGbU "Coder search issue")

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

Totally lost... I've recreated the container from scratch many times. No way...

**Comment by jsjoeio** [comment]
Are there any logs in the browser console? Is there a `.gitignore` at the root ignoring these files? Very weird.

**Comment by khanakia** [comment]
@jsjoeio It's not working for me also. I am using the `v4.8.3` version

```
  ERR vscode-remote://code.analyzify.app/home/ana/html/prod/testapp/apigql/pkg/gahandler/gahandler.go is not correctly configured as a child of its vscode-remote://code.analyzify.app/home/ana/html/prod/testapp/: Error: vscode-remote://code.analyzify.app/home/ana/html/prod/testapp/apigql/pkg/gahandler/gahandler.go is not correctly configured as a child of its vscode-remote://code.analyzify.app/home/ana/html/prod/testapp/
    at M.createAndConfigureFileMatch (https://code.analyzify.app/stable-129500ee4c8ab7263461ffe327268ba56b9f210d/static/out/vs/workbench/workbench.web.main.js:2174:12558)
    at https://code.analyzify.app/stable-129500ee4c8ab7263461ffe327268ba56b9f210d/static/out/vs/workbench/workbench.web.main.js:2174:9067
    at Array.forEach (<anonymous>)
    at M.addFileMatch (https://code.analyzify.app/stable-129500ee4c8ab7263461ffe327268ba56b9f210d/static/out/vs/workbench/workbench.web.main.js:2174:8830)
    at https://code.analyzify.app/stable-129500ee4c8ab7263461ffe327268ba56b9f210d/static/out/vs/workbench/workbench.web.main.js:2174:17698
    at c.forEach (https://code.analyzify.app/stable-129500ee4c8ab7263461ffe327268ba56b9f210d/static/out/vs/workbench/workbench.web.main.js:70:78861)
    at x.add (https://code.analyzify.app/stable-129500ee4c8ab7263461ffe327268ba56b9f210d/static/out/vs/workbench/workbench.web.main.js:2174:17630)
    at V.onSearchCompleted (https://code.analyzify.app/stable-129500ee4c8ab7263461ffe327268ba56b9f210d/static/out/vs/workbench/workbench.web.main.js:2174:22407)
    at https://code.analyzify.app/stable-129500ee4c8ab7263461ffe327268ba56b9f210d/static/out/vs/workbench/workbench.web.main.js:2174:22080
```

**Comment by jsjoeio** [comment]
> vscode-remote://

Hmm...that looks a bit off to me. You're using code-server v4.8.3? What does your setup look like? I'm on 4.8.3 and can search without problems so it may be related to your setup if I had to guess? Not sure though.

<img width="1904" alt="image" src="https://user-images.githubusercontent.com/3806031/205694308-2fc62c34-eb45-4314-89d9-d7357c6017dc.png">

**Comment by khanakia** [comment]
@jsjoeio all i did was.
Note: The server is hidden behind Caddy Server. I have setup the older versions of code-server those are working fine.
```
curl -fsSL https://code-server.dev/install.sh | sh
sudo systemctl enable --now code-server@$USER
service code-server@$USER start
```

**Comment by jsjoeio** [comment]
Can you share the install logs?

**Comment by khanakia** [comment]
Ok i made the search work i added this settings
```
{
    "security.workspace.trust.enabled": false,
    "security.workspace.trust.emptyWindow": false
}
```

**Comment by jsjoeio** [comment]
Oh interesting! I guess search is blocked unless you trust the folders 🤔 I don't know how to pass flags to that `systemctl` service but you can use this `--disable-workspace-trust` or set `disable-workspace-trust: true` in your `config.yaml` for code-server.

**Comment by khanakia** [comment]
Started getting the same issue again.
PS: I have updated the code-server to the new version `4.9.0 0502dfa1ff42ab8a43adb911f7bf21f8b09ee25f with Code 1.73.1`

**Comment by jsjoeio** [comment]
@khanakia that's strange 🤔

Yeah maybe! Did you try loading code-server without cache, maybe an Incognito window?

**Comment by khanakia** [comment]
Yes, i tried in Incognito, and also same issue.

Then i started debugging further and was able to make it work again :)

I deleted this directory`/root/.local/share/code-server/User/caches` and then restarted the code-server and it started working again.

**Comment by code-asher** [comment]
That is strange, no idea why deleting cache would fix it.

**Comment by gbrian** [comment]
> Ok i made the search work i added this setting or it could be something with browser also i was using OPERA i faced same issue in chrome but after reloading multiple times somehow it started working in Chrome but not in Opera
> 
> ```
> {
>     "security.workspace.trust.enabled": false,
>     "security.workspace.trust.emptyWindow": false
> }
> ```

### Solved!!
Worked for me after setting this (before I updated to 4.9.1) 👏 👏  thanks @khanakia @jsjoeio 

<img width="1176" alt="image" src="https://user-images.githubusercontent.com/767180/208860659-033c8841-a619-44d2-b03f-72e54f63a021.png">

**Comment by gbrian** [comment]
:( Sorry, re-opening. Issue is back and now need to figured out what happened.
I work from multiple clients as we are using coder our codxspaces, is it possible since I opened this from another client it has overriden any settings?

Thanks

**Comment by gbrian** [comment]
OMG found it 

Issue is when your "folder" query qtring parameter ends with "/" slash 
Error:

   https://my.coder-domain.com/?folder=/home/project/

Works 

   https://my.coder-domain.com/?folder=/home/project

Please note second "folder" parameter doesn't has trailing "/"

@khanakia can you please confirm this point? Thanks in advance

**Comment by khanakia** [comment]
@gbrian Yes you are right i justed it. Where there is a slash in the folder name the search does not works. After i removed the slash it started working.

Great man 👍

**Comment by gbrian** [comment]
Thanks @khanakia you show me the way. Great team work 👏

**Comment by gbrian** [comment]
🧑‍🎄 EXTRA BONUS: 
The trailing slash issue causes autocomplete to stop working as well 
> Pay attention to the file path (Is exactly the same but coder see it diffently)

With "slash" `?folder=/home/coder/gbrian/codx/`

<img width="614" alt="image" src="https://user-images.githubusercontent.com/767180/209510805-4461119e-78c8-48ab-bfd5-eca7a6419634.png">


Without "slash" `?folder=/home/coder/gbrian/codx`

<img width="614" alt="image" src="https://user-images.githubusercontent.com/767180/209510866-317f8ffb-a145-4f3e-b225-404538922f40.png">

**Comment by jsjoeio** [comment]
Wow nice sleuthing! 

cc @code-asher is this something we need to change within code-server?

**Comment by code-asher** [comment]
Wow that is strange.  I was able to reproduce in Codespaces so it 
seems to be an upstream bug.
