### ISSUE TITLE
[Bug]: cannot set `telemetry.telemetryLevel` to "off" in  `settings.json`.

### ISSUE THREAD

**Issue by MacWeber** [coder/code-server#5821]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: any
- Local OS: Linux
- Remote OS: Linux
- Remote Architecture: x64
- `code-server --version`: 4.8.3 977b853a1e162ab583aed64b1322d1515c57728c with Code 1.72.1

### Steps to Reproduce

1. Set up a DNS server and log incoming queries
2. Set Code Server to use this DNS server
3. Add the option `"telemetry.telemetryLevel": "off"` to `~/.local/share/code-server/User/settings.json`.
4. Reboot the server
5. Open Code Server in a browser
6. Watch the DNS server logs

### Expected

No HTTP  requests to any telemetry.

### Actual

At least one request to `v1.telemetry.coder.com` happens during the server startup process and every hour afterwards. It seems the first telemetry request happens after Code Server is opened in a browser, and I am not sure if it is triggered if the app is not opened in a browser.

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

The issue does not happen if launching code-server with the option `--disable-telemetry`.

Maybe this is a related issue: https://github.com/coder/code-server/issues/5306

**Comment by MacWeber** [comment]
@jsjoeio I did some tests, and I do not observe this behavior when I manually run `code-server --disable-telemetry`.
One additional piece of information: the telemetry is triggered when the user opens Code Server in the browser after the reboot. I am not sure if it is triggered automatically if the app is not opened.

**Comment by jsjoeio** [comment]
Hmm...I feel like the only way to disable is using the CLI flag. 

> One additional piece of information: the telemetry is triggered when the user opens Code Server in the browser after the reboot. I am not sure if it is triggered automatically if the app is not opened.

Is this with or without the CLI flag?

**Comment by MacWeber** [comment]
> Hmm...I feel like the only way to disable is using the CLI flag.

According to the documentation it could be set to a different telemetry level, or even disabled via the settings file. There is also a GUI option that automatically adds this option to the settings file. These methods are not working.
Ref.: https://code.visualstudio.com/docs/getstarted/telemetry#_disable-telemetry-reporting

> Is this with or without the CLI flag?
>> One additional piece of information: the telemetry is triggered when the user opens Code Server in the browser after the reboot. I am not sure if it is triggered automatically if the app is not opened.

The only way that is currently disabling the telemetry is the CLI flag. Using `settings.json` will trigger the HTTP request to the telemetry server when the user opens Code Server in their browser after a restart.

**Comment by code-asher** [comment]
I believe I have seen the same, but the issue appears to be in VS Code so we should look into fixing it there.
