### ISSUE TITLE
[Docs]: Document Standalone Release procedure

### ISSUE THREAD

**Issue by athendrix** [coder/code-server#5825]
## What is your suggestion?
Right now, the docs say:
```
We publish self-contained .tar.gz archives for every release on [GitHub](https://github.com/coder/code-server/releases). The archives bundle the node binary and node modules.

We create the standalone releases using the [npm package](https://coder.com/docs/code-server/latest/install#npm), and we then create the remaining releases using the standalone version.
```
But it doesn't describe the commands used or the process used to actually create self-contained archives from source.

## How will this improve the docs?
I'd like that information added so it's easier to build standalone releases for packaging, so we can start seeing code-server become a native package in various distributions.

## Are you interested in submitting a PR for this?
I would if I knew enough about node to do this myself, but I do not.
But I figure one of you knows the methods used to build standalone releases from source, and it'd be nice for it to be documented for the reasons above.

Thank you!

**Comment by jsjoeio** [comment]
Great suggestion! I can definitely add docs for that.
