### ISSUE TITLE
[Feat]: PR: Prepare for alignment with upstream code-oss web-modules build

### ISSUE THREAD

**Issue by lemanschik** [coder/code-server#5835]
## What is your suggestion?
My suggestion is to make your build process compatible to the new web-modules standard so you can keep your infrastructure running for incremental migration and porting your other projects over to the new patterns like your deploy project and all the other repos that you got. 

## Why do you want this feature?
I am deploying the new Web 4.0 a web without central servers as part of that we need editors without servers and work environments it builds in fact it self out of the web on any web platform it includes a new module standard to build a distributed build grid that is shared cross the world at web scale to speed up builds.

## Are there any workarounds to get this functionality today?
Yes
## Are you interested in submitting a PR for this?
Yes

## Tracking theia & coder shared issues
- [ ] https://github.com/eclipse-theia/theia/issues/11949
   - [ ] Refactor to use:  https://github.com/microsoft/vscode/commit/25cfb20ec9f1c6e8059b140e45e6610ae916fe7e

## Tracking coder issues:
- [ ] some one needs to audit the issues in here takes a week stay tuned.

## Tracking code-oss upstream
- [x] https://github.com/microsoft/vscode/issues/167505
- [x] https://github.com/microsoft/vscode/issues/168005

## Tracking Ecosystem 
- https://github.com/VSCodium/vscodium/issues/1345
- https://github.com/eclipse-theia/theia/issues/11948

**Comment by lemanschik** [comment]
@jsjoeio where do you want your discussion i am switching the builds of all code-oss dependents and also throw electron out of the stack as it is not needed to create a Chromium App anymore?

**Comment by jsjoeio** [comment]
Please open here: https://github.com/coder/code-server/discussions
