### ISSUE TITLE
[Bug]: Invalid version in about window after 4.9.0 upgrade

### ISSUE THREAD

**Issue by pavelxdd** [coder/code-server#5842]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome
- Local OS: Arch Linux
- Remote OS: Debian sid
- Remote Architecture: amd64
- `code-server --version`: 4.9.0 0502dfa1ff42ab8a43adb911f7bf21f8b09ee25f with Code 1.73.1

### Steps to Reproduce

1. Open code-server
2. Navigate to Menu->Help->About

### Expected

Expected to see `code-server: v4.9.0` in about dialog.
Expected to no see the blue icon in status bar suggesting to download code-server.

### Actual

There a `code-server: v$VERSION`

![About](https://i.imgur.com/qUZcywu.png)

Also there's a blue icon in status bar suggesting to download code-server, despite having launched with `--disable-update-check`

![Status](https://i.imgur.com/jMwAS4g.png)

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by jsjoeio** [comment]
I've upgraded to 4.9.0 via homebrew and have the same issue. 

<img width="1712" alt="image" src="https://user-images.githubusercontent.com/3806031/206253708-11e2a91f-e18d-4057-97c4-581b57f3c58e.png">

I'll look into this. Thanks for reporting!

**Comment by jsjoeio** [comment]
Fixed via https://github.com/coder/code-server/pull/5845
