### ISSUE TITLE
[Feat]: Upgrade Code to 1.74.1

### ISSUE THREAD

**Issue by jsjoeio** [coder/code-server#5846]
https://github.com/microsoft/vscode/releases/tag/1.74.0#remote-development

**Comment by balajib-b** [comment]
https://github.com/microsoft/vscode/releases/tag/1.74.1

**Comment by jsjoeio** [comment]
Planning to start on this on Monday!

**Comment by balajib-b** [comment]
https://github.com/microsoft/vscode/releases/tag/1.74.2

**Comment by jsjoeio** [comment]
😅 Running into VS Code + Jest issues right now but will get to 1.74.2 after. Thank you @balajib-b 🙌🏼

**Comment by jsjoeio** [comment]
Heads-up: we're going to wait to release until 1.75.0 is out. More context here: https://github.com/coder/code-server/discussions/5918
