### ISSUE TITLE
[Bug]: No able to collapse code

### ISSUE THREAD

**Issue by robsoncloud** [coder/code-server#5862]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Safari
- Local OS: IPadOS 16
- Remote OS: Ubuntu 21
- Remote Architecture: x64
- `code-server --version`: 1.73.1

### Steps to Reproduce

1.  Open any code and try to collapse any block of code

### Expected

I would expect to collapse the code as it is possible in vscode.dev

### Actual

Buttons to collapse the code is not present.

### Logs

N/A

### Screenshot/Video

https://user-images.githubusercontent.com/26840035/206878425-bee9c033-caa9-478d-a314-8510da725a59.MOV

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by jsjoeio** [comment]
Hmm...can you share your code-server `settings.json`?

**Comment by robk9e** [comment]
this is the content:

root@Agent:~/.local/share/code-server/User# cat settings.json 
{
    "workbench.colorTheme": "Default Dark+",
    "terminal.integrated.defaultProfile.linux": "bash",
    "redhat.telemetry.enabled": true
}

**Comment by jsjoeio** [comment]
I tested in vscode.dev and collapsing works as expected.

I tested in code-server and it works as expected - as long as you have this setting not set `"editor.folding": false` or if it's set to `true` (the default I believe).

**Comment by K-I-M-J-I-N** [comment]
I have the same problem. It doesn't works in python code(.py) only.

**Comment by code-asher** [comment]
Closing since this appears not to be related to code-server.  Let me know if I got it wrong.
