### ISSUE TITLE
[Bug]: Ctrl+W closes tab + code-server

### ISSUE THREAD

**Issue by bilogic** [coder/code-server#5864]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome
- Local OS: Windows 10
- Remote OS: Ubuntu
- Remote Architecture: md64
- `code-server --version`: 4.9.0 0502dfa1ff42ab8a43adb911f7bf21f8b09ee25f with Code 1.73.1

### Steps to Reproduce

1. Install https://open-vsx.org/extension/cweijan/vscode-mysql-client2
2. Set up and open a table tab like below
![image](https://user-images.githubusercontent.com/946010/206900424-6f6d6431-359b-4eca-af88-05fb9dca0ea3.png)
3. Clicking on `Close` will close just the tab, but pressing `ctrl+w` will close this table tab + code-server itself

### Expected

I expect `ctrl+w` to close only this tab, unsure if it is a plugin issue or code-server, but feels more like code-server

### Actual

pressing `ctrl+w` will close this table tab + code-server itself

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

# NOTE
![image](https://user-images.githubusercontent.com/946010/206900555-bf58889c-034d-4e76-a611-8f03569370ba.png)
Cannot test in GitHub codespaces due to `The 'MySQL' extension is not available in Visual Studio Code for the Web`
Table tab closed properly in desktop VS Code

**Comment by bilogic** [comment]
Another easier way to produce the problem.

![image](https://user-images.githubusercontent.com/946010/206957529-e5c43708-604f-414e-a4af-26938e9846ea.png)

1. Open a new file
2. Open any extension homepage
3. Put the extension homepage on the left and new file on the right (See screenshot)
4. Switch to extension homepage and press `ctrl+w`, the whole code-server will close

**Comment by jsjoeio** [comment]
Thank you for finding this! So I've seen this but couldn't reproduce it consistently. 

https://user-images.githubusercontent.com/3806031/207096615-e580908d-6616-4327-b02d-96ed2e5a48ee.mov

I assume you're running it as a PWA right? I can't quite put my finger on what's happening 🤔 

@code-asher any ideas? I'll have to dig into this eventually.

**Comment by bilogic** [comment]
@jsjoeio Yes, I have it installed as a PWA using Chrome on Windows 10, it is reproducible probably 9 out of 10 times. Do you need more info from me?

**Comment by jsjoeio** [comment]
@bilogic no, you've been awesome. Thank you!

**Comment by jsjoeio** [comment]
Wow! @pavelxdd thank you so much! That makes this much easier. I'll talk to @code-asher about fixing this one so we can figure out where we need to ignore the `SIGPIPE` signal (guessing the child process?) and then setting that environment variable.

**Comment by bilogic** [comment]
@pavelxdd thanks, let me try in a bit

**Comment by jsjoeio** [comment]
I could not reproduce in Codespaces.

**Comment by code-asher** [comment]
I just gave it a shot as well and could not reproduce either :cry:

**Comment by bilogic** [comment]
https://user-images.githubusercontent.com/946010/211139456-546f7e8b-a540-4c45-a19c-dec4136a8a96.mp4

Ok, I'm sure this can be reproduced very consistently now. And it is happening on https://vscode.dev too

**Comment by bilogic** [comment]
should this be reported on vscode or here?

**Comment by bilogic** [comment]
I have also reported to https://github.com/microsoft/vscode/issues/170750

**Comment by bilogic** [comment]
> Add the following lines:
> 
> ```
> [Service]
> Environment=VSCODE_HANDLES_SIGPIPE=true
> ```

This made no difference for me

**Comment by bilogic** [comment]
@jsjoeio I take it you are able to consistently reproduce it?

**Comment by code-asher** [comment]
Nice reproduction steps!  It reproduces for me consistently.  Thanks for reporting upstream.

**Comment by bilogic** [comment]
thanks :)

**Comment by jsjoeio** [comment]
Yes! It reproduced for me as well.
