### ISSUE TITLE
[Bug]: alpine error

### ISSUE THREAD

**Issue by lWolvesl** [coder/code-server#5873]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome
- Local OS: alpine
- Remote OS: alpine
- Remote Architecture: amd64
- `code-server --version`:3.9.0

### Steps to Reproduce

open code-server
install extension
run command

### Expected

when run in alpine amd64
/usr/lib/code-server/bin/code-server: exec: line 28: /usr/lib/code-server/lib/node: not found

### Actual

when run in alpine amd64
/usr/lib/code-server/bin/code-server: exec: line 28: /usr/lib/code-server/lib/node: not found

### Logs

when run in alpine amd64
/usr/lib/code-server/bin/code-server: exec: line 28: /usr/lib/code-server/lib/node: not found

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

when run in alpine amd64
/usr/lib/code-server/bin/code-server: exec: line 28: /usr/lib/code-server/lib/node: not found
replace alpine`s node can fix this error
maybe create a dedicated version to adapt alpine

**Comment by jsjoeio** [comment]
Can you try using the latest version of code-server?

**Comment by code-asher** [comment]
Closing as stale, also follow https://github.com/coder/code-server/issues/3431 for potentially adding an official Alpine release.
