### ISSUE TITLE
release 4.9.1

### ISSUE THREAD

**Issue by jsjoeio** [coder/code-server#5874]

**Comment by jsjoeio** [comment]
Tested the macOS release in Incognito in Brave and looks good. Terminal is working.

**Comment by jsjoeio** [comment]
Now I need to figure out why this error is happening on x86-64 Linux build: https://github.com/coder/code-server/actions/runs/3680549350/jobs/6226283270#step:16:18

```typescript
cannot add "release-standalone/node_modules/http-proxy-agent/dist/index.d.ts" because "release-standalone/node_modules/gtoken/build/src/index.d.ts" is already present at the same destination (/usr/lib/code-server/index.d.ts): content collision
```

**Comment by jsjoeio** [comment]
I'm going to try re-running the job and see if it was a silly fluke.

**Comment by jsjoeio** [comment]
A different error this time: 
```shell
cannot add "release-standalone/node_modules/@mapbox/node-pre-
gyp/LICENSE" because "release-
standalone/lib/vscode/node_modules/graceful-
fs/LICENSE" is already present at the same 
destination (/usr/lib/code-server/LICENSE): content collision
```

Hmm...I'm going to check GitHub Discussions. I think I saw someone post something about an `nfpm` error.

**Comment by jsjoeio** [comment]
That seems to have done it! https://github.com/coder/code-server/actions/runs/3688259509

Next step is to cut a release candidate so the community can test before we do a full release.

**Comment by balajib-b** [comment]
@jsjoeio is this 1.74 or 1.73. The release information shows 1.73.1

**Comment by jsjoeio** [comment]
1.73.1 

We still need to upgrade to 1.74

**Comment by mehulmpt** [comment]
<img width="1005" alt="CleanShot 2022-12-15 at 01 10 36@2x" src="https://user-images.githubusercontent.com/10388889/207698431-766c39c6-5d85-4c07-9e45-483d9b155a4b.png">

Test image upload for @jsjoeio

**Comment by jsjoeio** [comment]
Thank you @mehulmpt!
