### ISSUE TITLE
[Bug]: code-server ignores "workbench.tips.enabled" setting

### ISSUE THREAD

**Issue by pavelxdd** [coder/code-server#5884]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chromium
- Local OS: Arch Linux
- Remote OS: Debian sid
- Remote Architecture: amd64
- `code-server --version`: 4.9.0 0502dfa1ff42ab8a43adb911f7bf21f8b09ee25f with Code 1.73.1

### Steps to Reproduce

1. Open settings and set `"workbench.tips.enabled": false`
2. Close all opened editors

### Expected

When `"workbench.tips.enabled": false` is set, there shouldn't be any shortcut tips displayed on the screen.

![vscode](https://i.imgur.com/1LBBN1h.png)

### Actual

Code-server ignores this setting and still displays these messages:

![code-server](https://i.imgur.com/Wq7xYbV.png)

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by jsjoeio** [comment]
Interesting...I have mine enabled but I don't see the tips  🤔

We'll have to dig more into this.

**Comment by code-asher** [comment]
Verified to be working in the latest version.
