### ISSUE TITLE
[Bug]: GitHub login/auth session is lost after restart

### ISSUE THREAD

**Issue by Osiris-Team** [coder/code-server#5889]
https://github.com/coder/code-server/issues/5072
Just wanted to bring attention to the issue above. Its quite annoying since I restart my VM with coder a lot
and have to re-login/re-authorize the device every time.
So a fix would be appreciated!

**Comment by jsjoeio** [comment]
You can leave a comment on the original issue to bring it to our attention! I'll leave a comment there.
