### ISSUE TITLE
[Bug]: Installing Extensions is not possible in Kubernetes

### ISSUE THREAD

**Issue by aleleba** [coder/code-server#5897]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: All browsers
- Local OS: Mac OS, Windows
- Remote OS: Kubernetes x86
- Remote Architecture: Kubernetes x86
- `code-server --version`: 4.9.0

### Steps to Reproduce

1. open code-server
2. install extension
3. The extension is not installed

### Expected

The extension is installed

### Actual

 The extension is not installed

### Logs

2022-12-16 09:01:05.418 [error] connect ETIMEDOUT 198.41.30.195:443: Error: connect ETIMEDOUT 198.41.30.195:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)

### Screenshot/Video

![Captura de pantalla 2022-12-16 a la(s) 09 07 09](https://user-images.githubusercontent.com/28767814/208128424-bf763467-2c3e-44f8-b49d-b61d89dd8163.png)

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by jsjoeio** [comment]
Hmmm... I don't know very much about kubernetes. @code-asher any ideas here?

**Comment by aleleba** [comment]
@jsjoeio, I identify what is the issue, for some reason from my host on digitalocean can not connect to https://open-vsx.org/ but for other markeplace it worked. I think you can check there.

**Comment by jsjoeio** [comment]
Hmm... cc @code-asher any ideas?

**Comment by code-asher** [comment]
Could possibly try `curl`ing open-vsx.org from the host just to remove code-server from the equation.  I would guess either there is something set up in your cluster that blocks open-vsx.org or open-vsx.org is for some reason blocking your IP.

**Comment by code-asher** [comment]
Closing as stale but feel free to comment if you come back to this.
