### ISSUE TITLE
[Docs]: explain exposing better in docs

### ISSUE THREAD

**Issue by ajiratech2** [coder/code-server#5908]
## What is your suggestion?
- When installing code-server on MacOS. The config.yaml file will by default have the following line:
bind-addr: 127.0.0.1:8080

This means that port 8080 is bound only to the loopback address. So the local Mac machine can access the code-server via loopback IP - 127.0.0.1 on port 8080. But when other machines try to access this code server on the local network, they will use the local IP of the Mac machine and they will not be able to access it.

A simple note to change the bind-addr line in config.yaml file to following will save Users hours of troubleshooting.

bind-addr: 0.0.0.0:8080

## How will this improve the docs?
- It will save users hours in troubleshooting why code-server cannot be accessed by any other machine on the network.

## Are you interested in submitting a PR for this?
- No

**Comment by jsjoeio** [comment]
@code-asher thoughts on making this the default?

**Comment by code-asher** [comment]
This was intentional to avoid over-exposing code-server on accident.  I think secure by default is the better option but possibly we can have better documentation or output in the startup to help explain when you might need to use 0.0.0.0 instead.

**Comment by code-asher** [comment]
Our current documentation: https://github.com/coder/code-server/blob/main/docs/FAQ.md#how-should-i-expose-code-server-to-the-internet

Maybe we rename to "expose code-server externally" or something because it could be to a local network or the internet.

In the linked guide we mention things like reverse proxies and self-signed certificates with direct access (via 0.0.0.0) as a fallback.

**Comment by tobycm** [comment]
https://github.com/coder/code-server/blob/main/docs/guide.md#expose-code-server
Isn't the second paragraph already told you this?

**Comment by code-asher** [comment]
Happy to take more suggestions, but for now the docs seem sufficient to me.
