### ISSUE TITLE
[Bug]: PWA is not installable when code-server is on subpath

### ISSUE THREAD

**Issue by tobycm** [coder/code-server#5922]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome
- Local OS: Windows 10
- Remote OS: Ubuntu 22.04
- Remote Architecture: AMD64
- `code-server --version`: 129500ee4c8ab7263461ffe327268ba56b9f210d

### Steps to Reproduce

1. Open code-server
2. No PWA app will be installable

### Expected

PWA app will be installable

### Actual

PWA app isn't installable

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by jsjoeio** [comment]
How are you running it on a subpath? NGINX or Caddy maybe?

**Comment by jsjoeio** [comment]
Actually...on Coder, we serve code-server on a subpath and I'm able to install it as a PWA. See here:

## Video

https://user-images.githubusercontent.com/3806031/210392367-f2076649-067a-405e-98a5-661297b06307.mov

**Comment by tobycm** [comment]
> How are you running it on a subpath? NGINX or Caddy maybe?

I was using it with Caddy, the PWA works but Installable was not available

Basically code-server PWA is not installable, I will edit the issue

**Comment by ItzDerock** [comment]
> Actually...on Coder, we serve code-server on a subpath and I'm able to install it as a PWA. See here:
> 
> ## Video
>  Screen.Recording.2023-01-03.at.8.46.16.AM.mov

I am running coder and tried installing the PWA on my iPad running the latest iPad OS (16.2).
The PWA does not seem to install correctly, the icon is just a screenshot of the page, and the navigation/url bar remains visible.

https://user-images.githubusercontent.com/14848722/210685174-bbb0d9cb-b2cb-4683-b210-aff631b76add.MOV

**Comment by jsjoeio** [comment]
@ItzDerock once you log into the PWA, it should work as expected and the navigation bar will disappear. Can you try again?

**Comment by ItzDerock** [comment]
> @ItzDerock once you log into the PWA, it should work as expected and the navigation bar will disappear. Can you try again?

That worked, thanks!

**Comment by code-asher** [comment]
Closing as stale but if we can come up with a reproduction we can reopen.
