### ISSUE TITLE
[Bug]: Shows Forbidden while trying to access in browser after successful build

### ISSUE THREAD

**Issue by sakthivel-axim** [coder/code-server#5931]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome
- Local OS: Ubuntu 18.04
- Remote OS:
- Remote Architecture:
- `code-server --version`: 4.9.0

### Steps to Reproduce

1. I have followed the following link to build it.
https://coder.com/docs/code-server/latest/CONTRIBUTING#build

### Expected

Code server should be accessible in browser

### Actual

Throws Forbidden error

### Screenshot/Video

![image](https://user-images.githubusercontent.com/55696493/209806206-d14ba181-fc2c-4fce-ba25-0ad60b9d41f3.png)

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [ ] I am using HTTPS.

**Comment by jsjoeio** [comment]
Did you apply the patches before building?

**Comment by code-asher** [comment]
This happens if you have built code-server without applying the patches.  Check out the contributing documentation.

**Comment by Kin9L** [comment]
For the `main` branch of `code-server`, and `1.85.2` tag of `vscode`, when I used `quilt push -a` in the folder of `code-server`, the following errors occured:
![image](https://github.com/coder/code-server/assets/26398960/c9c77c44-7c02-4927-82dc-c65d30011406)
Should I use a different branch of `code-server` or `vscode`?

**Comment by code-asher** [comment]
Closing for now, but let me know if you still have issues after making sure the submodule is up to date.
