### ISSUE TITLE
[Feat]: Dual issue and Feature opportunity: Incorporating known extension ports into Docker-Compose for streamline port proxy processes

### ISSUE THREAD

**Issue by CtheCondor** [coder/code-server#5955]
## What is your suggestion?
Incorporate known ports used by extensions in docker-compose to better facilitate/streamline the proxy port process

## Why do you want this feature?
I want to build a web accessible Personal Knowledge Resource using the VSCode extension dendron however the dendron local server does not appear to work on the web based on my current usage.

## Are there any workarounds to get this functionality today?
I have not been able to get it to work however I would not be surprised if there is a workaround. 

## Are you interested in submitting a PR for this?
I do not have the programmatic experience to do so at this time.

## My Setup
1. Stock coder/code-server image running on 8443
2. Nginx Proxy Manager running on same machine in the same bridged docker network
2a. A *.domain.com lets Encrypt Certificate 
2c. A Single Proxy host connecting my pkm.domain.com to my pkm_container:8443 using the container:port syntax with standard https required flags and proxy settings based on NPM.

**Comment by jsjoeio** [comment]
Which part of Dendron doesn't work for you? I tested it locally and it seems to be working:

<img width="1712" alt="image" src="https://user-images.githubusercontent.com/3806031/211354964-1e801044-1705-4e66-b0e3-09067357e3eb.png">

**Comment by CtheCondor** [comment]
![image](https://user-images.githubusercontent.com/70120966/211373363-f8790aed-d6af-45ab-acb5-b5f4603c4193.png)

What browser are you running your code-server implementation and are you accessing it via https using a local cert or reverse proxy or is it local via http?

**Comment by jsjoeio** [comment]
Interesting...I'm use the PWA with Brave Browser, 4.9.1 and running locally on my macOS. Accessing via http but it's on the same machine so it's considered secure.

**Comment by code-asher** [comment]
Closing this out since if there are issues here, it seems likely to be with the extension.
