### ISSUE TITLE
[Bug]: The debian (armhf) package created using source doesn't work on Beaglebone

### ISSUE THREAD

**Issue by sakthivel-axim** [coder/code-server#5965]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome
- Local OS: Ubuntu 18.04
- Remote OS: Debian
- Remote Architecture: armhf
- `code-server --version`: 4.9.1

### Steps to Reproduce

I have followed the below steps to generate the armhf package,

```
$ quilt push -a
$ yarn
$ VERSION="4.9.1" yarn build
$ VERSION=4.9.1 yarn build:vscode
$ yarn release
$ yarn release:standalone
$ yarn test:integration
$ VERSION="4.9.1" yarn package armhf
```

```
$ ls release-packages/
        code-server_4.9.1_armhf.deb  code-server-4.9.1-armhf.rpm  code-server-4.9.1-linux-armhf.tar.gz
```

### Expected

It should run on Beaglebone board like the package available in [https://github.com/coder/code-server/releases](https://github.com/coder/code-server/releases)

### Actual

Installation is successful on Beaglebone and failed to execute

### Logs

```
root@beaglebone:/home/debian# dpkg -i code-server_4.9.1_armhf.deb 
Selecting previously unselected package code-server.
(Reading database ... 73119 files and directories currently installed.)
Preparing to unpack code-server_4.9.1_armhf.deb ...
Unpacking code-server (4.9.1) ...
Setting up code-server (4.9.1) ...
root@beaglebone:/home/debian# code-server --version
/usr/lib/code-server/bin/code-server: 28: exec: /usr/lib/code-server/lib/node: Exec format error
```

### Does this issue happen in VS Code or GitHub Codespaces?

- [ ] I cannot reproduce this in VS Code.
- [ ] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [ ] I am using HTTPS.

**Comment by RobertCNelson** [comment]
That is very strange, for reference, we at BeagleBoard.org did put a wrapper around, the GitHub released *.tar.gz file

https://github.com/coder/code-server/releases/download/v4.9.1/code-server-4.9.1-linux-armv7l.tar.gz

with our debian pacakge: bb-code-server - https://github.com/rcn-ee/repos/tree/master/bb-code-server

which does work, so something must be different between the generated tar files and generated locally..

Regards,

**Comment by sakthivel-axim** [comment]
This is working and details are in the following discussion https://github.com/coder/code-server/discussions/5964
