### ISSUE TITLE
[Feat]: Add --disable-remote-host CLI flag

### ISSUE THREAD

**Issue by icarusion** [coder/code-server#5970]
## What is your suggestion?
Add a `--disable-remote-host` CLI flag.
## Why do you want this feature?
In the 4.9.1(code 1.73.1), the remote host button is openning as default in the left bottom corner, but we don't want to use it in container.
## Are there any workarounds to get this functionality today?
I‘m not sure.
## Are you interested in submitting a PR for this?
Sorry I may not have this ability.

**Comment by jsjoeio** [comment]
cc @code-asher thoughts?

**Comment by code-asher** [comment]
I think this was an upstream change so it might make more sense to raise it there.

**Comment by code-asher** [comment]
Since this affects upstream remote code, I think it would be better to do it there.
