### ISSUE TITLE
[Bug]: iPad use magic keyboard can’t scroll by track pad on editing mode

### ISSUE THREAD

**Issue by ashton2914** [coder/code-server#5971]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Safari
- Local OS: iPad OS 16.2
- Remote OS: Ubuntu
- Remote Architecture: amd64
- `code-server --version`: 4.9.1

### Steps to Reproduce

1. open code-server PWA
2. open a code
3. tap anywhere else but not the code, make sure your cursor not blinking (the code editor not been selected)
4. try to scroll your code and you can find scrolling is smooth and no issue
5. but if you tap your code and the cursor start blinking
6. scroll again you can find out you can not scroll at all.

### Expected

you can scroll any window no matter what you do.

### Actual

can scroll if you are not editing code
can not scroll if you are editing code

### Screenshot/Video

https://user-images.githubusercontent.com/17692778/212355177-27f25261-3e21-456b-b1d5-fd1493f2d9cd.mp4

### Does this issue happen in VS Code or GitHub Codespaces?

- [ ] I cannot reproduce this in VS Code.
- [ ] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

btw. on windows system i use chrome and that working just fine. i wondering if this is a webkit issue made by apple?

**Comment by jsjoeio** [comment]
Can this be reproduced in vscode.dev or Codespaces?

**Comment by ashton2914** [comment]
> Can this be reproduced in vscode.dev or Codespaces?

Same on vscode.dev and codespaces, so this is my iPad set up issue or a vscode issue right? I wondering anybody else have the same issue

**Comment by ashton2914** [comment]
interesting, the code on blink is working good, no matter how, the scrolling function is working, except it sam not smooth, but it work

**Comment by kissablemt** [comment]
enable Settings -> General -> Keyboards -> Shortcuts, then two-finger scroll may work in PWA

**Comment by ashton2914** [comment]
> enable Settings -> General -> Keyboards -> Shortcuts, then two-finger scroll may work in PWA

it should be **disable**, it worked! Thank you so much, that helps me a lot!

**Comment by ashton2914** [comment]
found it still have some bug, 
1. turn off general -> keyboard -> shortcuts
2. reopen the code-server PWA app
3. **result:** can not scroll code at all
4. back to setting and turn on shortcuts
5. back to code-server PWA app
6. **result:** still can not scroll at all
7. back to setting and turn off shortcuts again
8. back to code-server PWA app
9. **result:** can scroll code smoothly

now i found a way to use it, but still not perfect, kind of driving me crazy.


https://user-images.githubusercontent.com/17692778/212552482-06973924-f88e-4ccf-a8ac-d1aadca3d6ec.mp4

**Comment by jsjoeio** [comment]
Have you tried opening a bug in upstream VS Code?
