### ISSUE TITLE
[Feat]: Remove the message on password prompt or an option to change the message

### ISSUE THREAD

**Issue by niteshk9894** [coder/code-server#5980]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

Web Browser: Chrome
Local OS: macOS
Remote OS: Ubuntu
Remote Architecture: amd64
code-server --version: 4.0.1

### Steps to Reproduce

open code-server and set password

### Expected

There should an option to change the below highlighted message or remove it. It would be helpful to add custom message.
And also telling user that your password is stored at $PASSWORD on login page doesn't help users.
 
![image](https://user-images.githubusercontent.com/86285273/213526656-3cabb065-0738-4638-b148-54ff3dcf9522.png)

### Actual

shows password message.

### Screenshot/Video

![image](https://user-images.githubusercontent.com/86285273/213526757-54fd1359-44d3-4df2-81f7-8bdc263e7fe0.png)

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by niteshk9894** [comment]
any update when and which release this will be added. It is a minor change i think.

Thanks in advance.

**Comment by code-asher** [comment]
Merging this into https://github.com/coder/code-server/issues/5857
