### ISSUE TITLE
[Feat]: Pass env vars to apps run in the terminal

### ISSUE THREAD

**Issue by mirekphd** [coder/code-server#5985]
## What is your suggestion?
Environment variables exported in the terminal should be passed to the apps when they are run (e.g. with a python interpreter) by the user (ideally also with the debugger - it is a special case, as it spawns a new shell - which it should not for user-defined env. vars to be preserved).

## Why do you want this feature?
To represent reality of a production system. To make this IDE terminal work like IDEs terminals, including Jupyter Lab, Jupyter Notebook, RStudio Server, etc. etc. where it just works fine. Linux system CLI i.e. shell not passing all env vars to the app started later in that shell is a highly unrealistic test environment, We cannot use VSC for testing containerized apps (REST APIs in general and Flask apps in particular) for that very reason...

## Are there any workarounds to get this functionality today?
Editing launch.json file, as described [here](https://stackoverflow.com/questions/62295889/how-to-set-environment-variables-in-vscode-when-running-flask-app/62321199?noredirect=1#comment132695649_62321199
) which is a nuisance, and not realistic (cannot be copied to a production environment) and sometimes even insecure (cannot be used for credentials which should not be committed to disk but are routinely passed to containerized apps using env vars).

## Are you interested in submitting a PR for this?
Unfortunately, I don't code in Java/TypeScript.

**Comment by code-asher** [comment]
Closing as stale, but also I think changes here will need to be made upstream.
