### ISSUE TITLE
[Bug]: Extensions not showing up

### ISSUE THREAD

**Issue by XXILTeun** [coder/code-server#5987]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome
- Local OS: ChromeOS
- Remote OS: Ubuntu/Docker
- Remote Architecture: arm64
- `code-server --version`:

### Steps to Reproduce

1. Open code-server
2. Want to install an extension
3. No extensions showing up

### Expected

Extensions should show up

### Actual

Extensions not showing up

### Screenshot/Video

![image](https://user-images.githubusercontent.com/105371658/214057533-de184458-6caf-4236-ae8a-17f373426839.png)

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by jsjoeio** [comment]
Can you please fill out the entire bug report?

**Comment by code-asher** [comment]
Checking the browser logs and network tab in particular might be helpful.  You should see requests to open-vsx.org.

**Comment by code-asher** [comment]
Closing as incomplete, but please feel free to edit your issue and we can re-open.
