### ISSUE TITLE
Not able to install CodeGPT in latest VS Code Server v4.9.1

### ISSUE THREAD

**Issue by vinayak-shanawad** [coder/code-server#5988]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: chrome
- Local OS: Windows
- Remote OS: Windows
- Remote Architecture: SageMaker Studio
- `code-server --version`: v4.9.1

![image](https://user-images.githubusercontent.com/37987800/214532417-ab510a90-c352-463e-9372-dc650b1486f5.png)

### Steps to Reproduce

1. Installed VS code server v4.9.1 on SageMaker Studio.
2. Tried installing "DanielSanMedium.dscodegpt" (Code GPT) in Code Server then I get the following error.

Error details: Can't install 'danielsanmedium.dscodegpt' extension because it is not compatible with the current version of code-server (version 1.73.1).

### Expected

Allow users to install Code GPT extension on VS Code Server and start asking Code GPT to return a code for a specific question.

### Actual

Tried installing "DanielSanMedium.dscodegpt" (Code GPT) in Code Server then I get the following error.

Error details: Can't install 'danielsanmedium.dscodegpt' extension because it is not compatible with the current version of code-server (version 1.73.1).

### Screenshot/Video

![image](https://user-images.githubusercontent.com/37987800/214532314-7061932c-12fa-42cf-9e19-b45d565d40b9.png)

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by benz0li** [comment]
Cross reference: https://github.com/davila7/code-gpt-docs/issues/18

**Comment by benz0li** [comment]
[My advice](https://github.com/coder/code-server/discussions/5325#discussioncomment-3227799): Keep your hands off such extensions.

https://drewdevault.com/2022/06/23/Copilot-GPL-washing.html

**Comment by vinayak-shanawad** [comment]
Hi Team, Does Code Server v1.74 support Code GPT extension?

**Comment by code-asher** [comment]
Likely this error means we have to update Code which means this 
would be fixed once 
https://github.com/coder/code-server/issues/5995 is completed.

**Comment by vinayak-shanawad** [comment]
Hello @code-asher, 

Could you please update this issue once the fix is available in VS code server v4.9.1?

Thanks

**Comment by code-asher** [comment]
4.10.0 landed yesterday with the fix.
