### ISSUE TITLE
[Bug]: Facing issue in building submodule vscode in Ubuntu ARM envrionment

### ISSUE THREAD

**Issue by gkdlight** [coder/code-server#6006]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser:
- Local OS: Ubuntu 20.04 (ARM)
- Remote OS: Ubuntu 20.04 (ARM)
- Remote Architecture: aarch64
- `code-server --version`: 4.9.1

![image](https://user-images.githubusercontent.com/61817247/217249479-b2613c36-d2dd-46d6-8219-5e3d793cd55f.png)

### Steps to Reproduce

1. $ git clone [git@github.com:coder/code-server.git](git@github.com:coder/code-server.git)
2. $ git submodule init
3. $ git submodule sync
4. $ git submodule update
5. $ git checkout v4.9.1
6. $ quilt push -a
7. $ yarn
8. $ yarn build
9. $ VERSION=4.9.1 yarn build:vscode

### Expected

Build should be successful

### Actual

Build failed

### Logs

```
$ VERSION=4.9.1 yarn build:vscode
yarn run v1.22.19
$ ./ci/build/build-vscode.sh
Updated 1 path from the index
$ node --max_old_space_size=8192 ./node_modules/gulp/bin/gulp.js vscode-reh-web-linux-x64-min
[11:21:18] Using gulpfile /var/www/code-server/lib/vscode/gulpfile.js
[11:21:18] Starting 'vscode-reh-web-linux-x64-min'...
[11:21:18] Starting clean-out-build ...
[11:21:19] Finished clean-out-build after 511 ms
[11:21:19] Starting build-web-node-paths ...
[11:21:19] Finished build-web-node-paths after 8 ms
[11:21:19] Starting compile-api-proposal-names ...
[11:21:19] Starting compilation api-proposal-names...
[11:21:19] Finished compilation api-proposal-names with 0 errors after 86 ms
[11:21:19] Finished compile-api-proposal-names after 105 ms
[11:21:19] Starting <anonymous> ...
[11:21:25] Starting compilation...
Killed
error Command failed with exit code 137.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 137.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Does this issue happen in VS Code or GitHub Codespaces?

- [ ] I cannot reproduce this in VS Code.
- [ ] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by code-asher** [comment]
Exit code 137 apparently means out of memory.  Can you increase 
memory usage and try again?  It might also make sense to monitor 
memory usage to make sure that is actually the problem.

**Comment by code-asher** [comment]
Closing as stale but feel free to comment if you come back to this.
