### ISSUE TITLE
[Feat]: Sync "Open Recent" menu

### ISSUE THREAD

**Issue by KaKi87** [coder/code-server#6007]
## What is your suggestion?

If, on the same instance, I opened a file or directory from a computer, I would like to find it in the "Open Recent" menu of other computers I'm accessing this instance from.

## Why do you want this feature?

So that I don't have to manually enter the path of every new project I started from a computer and continue on another.

## Are there any workarounds to get this functionality today?

N/A

## Are you interested in submitting a PR for this?

Nope, sorry.

---

Tanks

**Comment by code-asher** [comment]
Fixing this would require https://github.com/coder/code-server/issues/4212, which for now we have decided not to work on.
