### ISSUE TITLE
[Bug]: Can't see latest Extension versions

### ISSUE THREAD

**Issue by jrich100** [coder/code-server#6011]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome
- Local OS: MacOS
- Remote OS: Ubuntu
- `code-server --version`: 
4.9.1
Code 1.73.1
6261075646f055b99068d3688932416f2346dd3b
x64

### Steps to Reproduce

1. open ms-python extension
2. look for latest version in UI
3. look for latest version in marketplace: https://open-vsx.org/extension/ms-python/python

<img width="1415" alt="image" src="https://user-images.githubusercontent.com/10822783/217911645-f9f81131-8491-42a5-9bb4-2eb0c5571db9.png">

<img width="1415" alt="image" src="https://user-images.githubusercontent.com/10822783/217911687-420996ee-3838-4c7b-bbe2-20529ebf4895.png">

### Expected

I should be able to install the latest version of an extension if it exists in the registered marketplace.

### Actual

The Extension versions shown in code-server are behind what is available in the marketplace.

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by jrich100** [comment]
![image](https://user-images.githubusercontent.com/10822783/217921834-790403b4-0dcd-4d43-b529-891ce8c53d1a.png)

**Comment by code-asher** [comment]
Was the extension originally installed from Open VSX?  I have seen 
update issues when installing from one marketplace and then using 
another.

If it was then this is quite confusing, we may have to inspect the 
requests to see what is going on.

**Comment by jrich100** [comment]
Yes, originally installed via command line from Open VSX

**Comment by balajib-b** [comment]
@jrich100 the version you are using 1.73.1 was release by microsoft on 10th November 2022  [1.73.1](https://github.com/microsoft/vscode/releases/tag/1.73.1) and the ms-python you are able to see  [v2022.18.2] (https://github.com/microsoft/vscode-python/releases/tag/2022.18.2) 11th November 2022. 

I think the version corresponding to 1.73.1 is v2022.18.2 and it might be the compatible ms-python version released by the code owner. 

I checked with vscodium version 1.75.1 released yesterday, which uses open-vsx. it shows me the latest version 2023.2.0 for installation and usage.

So, simply using updated version of code-server will provide you with corresponding, compatible, checked and tested version to install. ideally the recommended version is latest for that particular vscode used inside code-server.

@code-asher please correct me if my observation is wrong.

**Comment by code-asher** [comment]
You must be right, the required version for 2023.2.0 is `^1.75.0` (https://github.com/microsoft/vscode-python/blob/2023.2.0/package.json#L43)

Initially I thought the caret meant any minor or patch version works but I think it actually means any minor or patch version *above* the listed version.

But I am still not sure why it was allowed to be installed via the command line.  Maybe `--force` bypasses the version check?
