### ISSUE TITLE
[Feat]: code-server --update <Version: Optional> to update an existing installation.

### ISSUE THREAD

**Issue by ucalyptus2** [coder/code-server#6025]
## What is your suggestion?
See title
## Why do you want this feature?
Ease of updation
## Are there any workarounds to get this functionality today?
i don't know
## Are you interested in submitting a PR for this?
no, it's a suggestion

**Comment by code-asher** [comment]
We used to have updating built into code-server, but we decided to rely on the installation script.

If you need to update code-server you can run `curl -fsSL https://code-server.dev/install.sh | sh` again.
