### ISSUE TITLE
[Feat]: Support WebUSB

### ISSUE THREAD

**Issue by FourLeafTec** [coder/code-server#6033]
## What is your suggestion?
Is there any plan to support WebUSB?

## Why do you want this feature?
With WebUSB support we can more easier to connect Android or Embedded devices.
For embedded developer, most only can use USB to connect his device.

## Are there any workarounds to get this functionality today?
There is some demos for WebUSB support

[arduino lights](https://webusb.github.io/arduino/demos/)
[WebADB for Android](https://bielej.org/adb/#/)

And Apis:
[WebUSB_API](https://developer.mozilla.org/en-US/docs/Web/API/WebUSB_API)

**Comment by code-asher** [comment]
This would be something best added upstream I think.

Apparently the recommended method is to create two extensions: https://github.com/microsoft/vscode/issues/161018

**Comment by code-asher** [comment]
Closing for now as something that should go upstream.
