### ISSUE TITLE
[Bug]: In Terminal, Korean cannot be represented and inputted correctly. 

### ISSUE THREAD

**Issue by hyeonsoo-kim** [coder/code-server#6053]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome
- Local OS: iPadOS 16.2
- Remote OS: Ubuntu
- Remote Architecture: amd64
- `code-server --version`: 4.10.0

### Steps to Reproduce

1. open code-server
2. open terminal
3. input korean “아리랑“, ”훈민정음“ and the other.

### Expected

Input “아리랑“ should out “아리랑”,
Input “훈민정음“ should out “훈민정음” 

### Actual

Korean characters is splited. (Code-server cannot present Korean correctly.)
For Example, If input is “아리랑“ , The result is “ㅇㅏㄹㅣㄹㅏㅇ”
“훈민정음“ results “ㅎㅜㄴㅁㅣㄴㅈㅓㅇㅇㅡㅁ”

### Screenshot/Video

https://user-images.githubusercontent.com/18733991/223440163-ef356386-7d89-46ec-bb72-55fe59ba6e14.mov

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by code-asher** [comment]
All the keyboard code is in VS Code (https://github.com/microsoft/vscode) so what we should do is reproduce in Codespaces and then use that to make an issue upstream.
