### ISSUE TITLE
[Bug]: I can't open terminal in the server

### ISSUE THREAD

**Issue by cpp-deep-learning** [coder/code-server#6055]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Firefox dev
- Local OS: Android Termux
- Remote OS: Manjaro Linux
- Remote Architecture: x86-64
- `code-server --version`: 4.10.1

### Steps to Reproduce

1. yes
2.no
3.no

### Expected

when I want open the terminal run the code but the terminal can't open with an error

### Actual

I can't open the terminal

### Logs

![image](https://user-images.githubusercontent.com/54460355/222942284-c67faa68-7896-4f68-82da-95bc5cbbc443.png)
The terminal process failed to launch: A native exception occurred during launch (Cannot find module '../build/Release/pty.node'
Require stack:
- /data/data/com.termux/files/usr/lib/code-server/lib/vscode/node_modules/node-pty/lib/unixTerminal.js
- /data/data/com.termux/files/usr/lib/code-server/lib/vscode/node_modules/node-pty/lib/index.js
- /data/data/com.termux/files/usr/lib/code-server/lib/vscode/out/bootstrap-amd.js
- /data/data/com.termux/files/usr/lib/code-server/lib/vscode/out/bootstrap-fork.js).

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [ ] I am using HTTPS.

**Comment by code-asher** [comment]
How did you install code-server?  That file seems to exist in the `linux-amd64` GitHub release.

**Comment by ZenQy** [comment]
the same. 
log: The terminal process failed to launch: A native exception occurred during launch (posix_spawn failed: No such file or directory).
platform: linux-arm64
version: 4.11.0

**Comment by code-asher** [comment]
@ZenQy how did you install code-server?  If you used nixpkgs it should work but if you used the releases from GitHub they will fail on NixOS since they need to be built specifically for NixOS.

**Comment by code-asher** [comment]
By same problem do you just mean the terminal is not working or do you also mean you get the same error message?  If you get a different error message it could be https://github.com/coder/code-server/issues/5496

**Comment by tianxiayu007** [comment]
> By same problem do you just mean the terminal is not working or do you also mean you get the same error message? If you get a different error message it could be #5496

the terminal is not working and i get the same error message as this issue described

**Comment by zongou** [comment]
termux tur-repo did not build node-pty with the dependency libandroid-spawn to provide libspawn.h, thus building node-pty fails.
here is the script i write to build code-server on alpine and termux.
```shell
#! /bin/sh
# MIT License
# Copyright (c) [2023] [zongou@outlook.com]

CODE_SERVER_DIR="${HOME}/code-server"

is_termux() { test -n "${TERMUX_VERSION}"; }
is_alpine() { test -f /etc/os-release && test "$(cat /etc/os-release | grep "^ID=" | cut -d= -f2-)"="alpine"; }

alpine_setup_build_env() {
    apk add alpine-sdk libstdc++ libc6-compat python3 yarn
}

termux_setup_build_env() {
    apt install nodejs-lts build-essential binutils libandroid-spawn python3 yarn -y
}

setup_cn_proxy() {
    # proxy for in China
    yarn config set registry https://registry.npmmirror.com
}

# build code-server
build_code_server() {
    FORCE_NODE_VERSION="$(node --version | cut -d. -f 1)" && export FORCE_NODE_VERSION
    if (mkdir -p "${CODE_SERVER_DIR}" && cd "${CODE_SERVER_DIR}" && yarn add code-server --ignore-engines); then

        # fix ptyhost dose not recognize platform android
        if is_termux; then
            find "${CODE_SERVER_DIR}" -name "ptyHostMain.js" | while IFS= read -r file; do
                sed -i 's|case"linux":h=process.env.XDG_CONFIG_HOME|case"android":case"linux":h=process.env.XDG_CONFIG_HOME|' "${file}"
            done
        fi
    else
        return 1
    fi
}

set_up_build_env() {
    if is_alpine; then
        alpine_setup_build_env || exit 1
    elif is_termux; then
        termux_setup_build_env || exit 1
    else
        echo this script is designed to build code-server on alpine and termux only!
        exit 1
    fi
    setup_cn_proxy
}

set_up_build_env
if build_code_server; then
    # test
    "${CODE_SERVER_DIR}"/node_modules/.bin/code-server --bind-addr 0.0.0.0:8080 --auth none
fi
```

**Comment by scriptscreen** [comment]
> termux tur-repo did not build node-pty with the dependency libandroid-spawn to provide libspawn.h, thus building node-pty fails.
> here is the script i wrote to build code-server on alpine and termux.
> i used proxy so it show localhost at address bar

I would try it,thanks

**Comment by tianxiayu007** [comment]
> termux tur-repo did not build node-pty with the dependency libandroid-spawn to provide libspawn.h, thus building node-pty fails. here is the script i wrote to build code-server on alpine and termux. i used proxy so it show localhost at address bar ![Clip_20230331_183732](https://user-images.githubusercontent.com/23202896/229098272-b44f8d33-790f-4ca1-907e-da7a42bbf4ac.png) ![Clip_20230331_171723](https://user-images.githubusercontent.com/23202896/229098327-071d9a2e-9c6a-4c48-9484-004abc50c2da.png)
> 
> ```shell
> #! /bin/sh
> # MIT License
> # Copyright (c) [2023] [zongou@outlook.com]
> 
> CODE_SERVER_DIR="${HOME}/code-server"
> 
> is_termux() { test -n "${TERMUX_VERSION}"; }
> is_alpine() { test -f /etc/os-release && test "$(cat /etc/os-release | grep "^ID=" | cut -d= -f2-)"="alpine"; }
> 
> alpine_setup_build_env() {
>     apk add alpine-sdk libstdc++ libc6-compat python3 yarn
> }
> 
> termux_setup_build_env() {
>     apt install nodejs-lts build-essential binutils libandroid-spawn python3 yarn -y
> }
> 
> setup_cn_proxy() {
>     # proxy for in China
>     yarn config set registry https://registry.npmmirror.com
> }
> 
> # build code-server
> build_code_server() {
>     FORCE_NODE_VERSION="$(node --version | cut -d. -f 1)" && export FORCE_NODE_VERSION
>     if (mkdir -p "${CODE_SERVER_DIR}" && cd "${CODE_SERVER_DIR}" && yarn add code-server --ignore-engines); then
> 
>         # fix ptyhost dose not recognize platform android
>         if is_termux; then
>             find "${CODE_SERVER_DIR}" -name "ptyHostMain.js" | while IFS= read -r file; do
>                 sed -i 's|case"linux":h=process.env.XDG_CONFIG_HOME|case"android":case"linux":h=process.env.XDG_CONFIG_HOME|' "${file}"
>             done
>         fi
>     else
>         return 1
>     fi
> }
> 
> set_up_build_env() {
>     if is_alpine; then
>         alpine_setup_build_env || exit 1
>     elif is_termux; then
>         termux_setup_build_env || exit 1
>     else
>         echo this script is designed to build code-server on alpine and termux only!
>         exit 1
>     fi
>     setup_cn_proxy
> }
> 
> set_up_build_env
> if build_code_server; then
>     # test
>     "${CODE_SERVER_DIR}"/node_modules/.bin/code-server --bind-addr 0.0.0.0:8080 --auth none
> fi
> ```
> 
> https://gist.github.com/zongou/51167b91032854329524646887dd82f9

it works, good job! That's amazing
