### ISSUE TITLE
[Bug]: Can’t select a whole text in code server with finger/keyboard touch pad

### ISSUE THREAD

**Issue by ChaosLights** [coder/code-server#6068]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Safari
- Local OS: iPadOS
- Remote OS: Raspberry Pi OS Lite 64
- Remote Architecture: aarch64
- `code-server --version`: 4.10.1

### Steps to Reproduce

1. Open code server
2. Try select a whole test/code by dragging with finger/keyboard touch pad
3. Can only select a word

### Expected

When I drag through a text, it should be selected

### Actual

It only select a word instead of a text

### Screenshot/Video

https://user-images.githubusercontent.com/125947865/224553484-d75ec661-c195-46bb-b3ca-37c03be2eb6c.MOV

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by code-asher** [comment]
I think this is an upstream issue https://github.com/microsoft/vscode/issues/47770
