### ISSUE TITLE
[Bug]: Debug/Run session gets lost but process stays alive when browser window is reloaded

### ISSUE THREAD

**Issue by dafi87** [coder/code-server#6081]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Firefox
- Local OS: Windows, MacOS
- Remote OS: Debian
- Remote Architecture: x86_64
- `code-server --version`: 4.10.0

### Steps to Reproduce

1. open code-server
2. open NodeJS/Typescript project (ExpressJS)
3. start debug session "Launch Program"
`{
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "console": "internalConsole",
            "internalConsoleOptions": "openOnSessionStart",
            "skipFiles": [
                "${workspaceFolder}/node_modules/**/*.js",
                "<node_internals>/**/*.js"
            ],
            "preLaunchTask": "tsc: build - tsconfig.json",
            "program": "${workspaceFolder}/src/app.ts",
            "resolveSourceMapLocations": [
                "${workspaceFolder}/**",
                "!**/node_modules/**"
            ],
            //"runtimeArgs": ["--trace-warnings"],
            "sourceMaps": true,
            "trace": true,
            "smartStep": true,
            "outFiles": [
                "${workspaceFolder}/dist/**/*.js"
            ]
        }`
4. reload browser window after a while 
5. debug/run session is lost/closed but its process is still alive and listening on ports etc.
6. can not launch new debug session since the old process is still bound to network ports

### Expected

The launched debug session should be recovered/reconnected if the window reloads for whatever reason
OR the debug session and launched process should be killed if the window reloads.

### Actual

The debug session is lost but launched process still alive in background without any indication of that. Can't be killed easily through UI. Starting a new session is not possible if the old process was using network port etc. and still holds on to that.

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [ ] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by code-asher** [comment]
This reproduces in Codespaces for me, did it not for you?  If it does we will want to report it upstream https://github.com/microsoft/vscode/issues

**Comment by dafi87** [comment]
Thank you so much for checking in on this!
I must have been in a hurry when I did the testing. Indeed, it reproduces in Codespaces for me too.

**Comment by code-asher** [comment]
So one solution for this would be to kill the process on reload but I think the better solution is to preserve the debug state.  We can track this at https://github.com/coder/code-server/issues/6173 which also is linked to an upstream issue.  Feel free to upvote the upstream issue!
