### ISSUE TITLE
Add the ability to disable proxy

### ISSUE THREAD

**Issue by heroyanglonghui** [coder/code-server#6107]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome
- Local OS:
- Remote OS:  Ubuntu
- Remote Architecture:  amd64
- `code-server --version`: 4.11.0

### Steps to Reproduce

Automatically turn on after starting the service

### Expected

Plugins can be turned on or off in the configuration file or through CLI settings

### Actual

The setting to disable the plugin is not found in the vscode configuration

I only found the switch for automatic port forwarding, so I would like to be able to set and disable the proxy plugin

<img width="1499" alt="image" src="https://user-images.githubusercontent.com/20876976/227778760-74fe9a99-7b19-427a-986d-0305f5b06e50.png">

### Does this issue happen in VS Code or GitHub Codespaces?

- [x] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by madcpt** [comment]
Good suggestion.
But you might probably consider tagging with `feature` instead of `bug` - I wouldn't call this a bug.

**Comment by code-asher** [comment]
Oh actually I guess we already have a feature request for disabling the proxy: https://github.com/coder/code-server/issues/5826

Will close this as a duplicate.
