### ISSUE TITLE
[Docs]: clarification on hashed password

### ISSUE THREAD

**Issue by j4ys0n** [coder/code-server#6114]
## What is your suggestion?
Please mention that if you're entering the hashed password in a docker-compose yaml file that the `$` need to be escaped like `$$` or else docker will interpret them as variable markers. Also mention that the password should not be contained in quotes.

## How will this improve the docs?
Hashed password will work with more run environments

## Are you interested in submitting a PR for this?
Sure

**Comment by benz0li** [comment]
That is not `code-server` specific and already described here: https://docs.docker.com/compose/compose-file/12-interpolation/

**Comment by j4ys0n** [comment]
Yes, you are correct. It would be nice to include that information as it is relevant. Just my opinion.

**Comment by code-asher** [comment]
Maybe this was added later, but we do mention this in the docs at the moment.
