### ISSUE TITLE
[Feat]: 

### ISSUE THREAD

**Issue by sajfb** [coder/code-server#6119]
## What is your suggestion?
Request for Guidance on Using Code-Server with HTTP Servers for Jupyter notebook Due to Firewall Restrictions

## Why do you want this feature?
My school's firewall restricts private SSL connections which prevents me from using the default SSL keys.

## Are there any workarounds to get this functionality today?
I have no idea. 

## Are you interested in submitting a PR for this?
Yes, if it doesn't require any IP address.

**Comment by code-asher** [comment]
A secure domain (either HTTPS or localhost) is unfortunately 
required for code-server to fully work; this is a browser 
restriction (browser do not allow things like service workers to 
run over insecure domains).

Do you have some way to tunnel into code-server from localhost? 
For example over SSH?  If not then you might be out of luck.

https://github.com/coder/code-server/blob/main/docs/guide.md#port-forwarding-via-ssh
