### ISSUE TITLE
[Bug]: White Screen in Android 

### ISSUE THREAD

**Issue by Jumbo810** [coder/code-server#6127]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### OS/Web Information

- Web Browser: Via Browser - Android System WebView Based App 
- Local OS: Android 13
- Remote OS: Kali linux
- Remote Architecture: amd64
- `code-server --version`: 4.11.0

### Steps to Reproduce

1. Install code-server latest version (v4.11.0) using dpkg.
2. Start code-server with --auth none --bind-addr 127.0.0.1:8080.
3. Open in Via Browser app.

### Expected

Just starts

### Actual

Coder-server working perfectly in linux and in chrome but in Via Browser after loading White screen shows

### Does this issue happen in VS Code or GitHub Codespaces?

- [x] I cannot reproduce this in VS Code.
- [x] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [x] I am using HTTPS.

### Notes

**Not Working in Via Browser**
**Did't work Github.dev - hanged on setting up you editor**
**Did't work Gitpod - hanged on Strating - prepairing workspace**

**Comment by code-asher** [comment]
A white screen usually means the web sockets are having trouble 
connecting.  Maybe web sockets are not supported in Android 
webviews?

**Comment by Jumbo810** [comment]
Working fine on Android 12 and below devices.

**Comment by code-asher** [comment]
Is this still a problem with the latest version?  Is it possible to test Codespaces as well?

**Comment by code-asher** [comment]
Closing for now, but if you come back to it feel free to comment and we can reopen if necessary.

If it is still a problem we will might need the console and network logs from the browser.

**Comment by foolishchow** [comment]
error maybe this
<img width="439" alt="Image" src="https://github.com/user-attachments/assets/5cca910f-d70a-4c89-9e84-0684c1710609" />

**Comment by code-asher** [comment]
@foolishchow What browser and version are you using?  Sometimes those syntax errors are due to old browsers not supporting some newer syntax VS Code is using.

It could also be serving the wrong content, if you click the `notebookWebviewPreloads.js` does it look like valid JavaScript?
