### ISSUE TITLE
[Bug]: International with dead keys not working in terminal with FireFox on Ubuntu

### ISSUE THREAD

**Issue by qistoph** [coder/code-server#6137]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: FireFox 111.0.1 (64-bit)
- Local OS: Ubuntu 22.04.2 LTS
- Remote OS: Ubuntu 22.04.2 LTS (lscr.io/linuxserver/code-server@sha256:4f03aca773e7e0f26e37574377b84918ca6b1a4642cda647c488322bf90a1710)
- Remote Architecture: x86_64
- `code-server --version`: 4.11.0 85e083580dec27ef19827ff42d3c9257d56ea7e3 with Code 1.76.1

### Steps to Reproduce

1. In Local OS enable Keyboard layout "English (US, intl., with dead keys)"
2. Open code-server in FireFox
3. Start a new terminal
4. Type `<quote>e`, `<quote><space>`

### Expected

Expected on terminal: `é` (`U+00E9`) and `'` (`U+0027`)

### Actual

Actually on terminal: `´é` (`U+00B4`,`U+00E9`) and `´'` (`U+00B4`, `U+0027`)

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

Does work as expected on Windows with Edge and Ubuntu with Chromium.

**Comment by code-asher** [comment]
All the keybindings are handled by VS Code.  We should reproduce in Codespaces and report to https://github.com/microsoft/vscode.
