### ISSUE TITLE
[Bug]: Jupyter Notebook cannot find a Python kernel

### ISSUE THREAD

**Issue by maksad** [coder/code-server#6152]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome
- Local OS: macOs
- Remote OS: Ubuntu 20.4
- Remote Architecture: amd64/Kubeflow
- `code-server --version`: [v4.12.0-rc.1](https://github.com/coder/code-server/releases/tag/v4.12.0-rc.1)

### Steps to Reproduce

1. Create a docker image with code-server installed
2. Push the docker image to ECR
3. Run the docker image using Kubeflow

### Expected

When creating a Jupyter Notebook file, it should be able to detect Python Kernels and select them.

Steps:
1. install ipykernel
2. create `temp.ipynb` file
3. open the file and click on select kernel 

![Screenshot 2023-04-18 at 11 30 55](https://user-images.githubusercontent.com/4527650/232721057-3a7f7147-edeb-40a1-80ce-2c267f15fe45.png)

This was tested with the version [v4.11.0](https://github.com/coder/code-server/releases/tag/v4.11.0)

### Actual

When using the release candidate version [v4.12.0-rc.1](https://github.com/coder/code-server/releases/tag/v4.12.0-rc.1), and clicking on "select kernel" the kernels cannot be found or selected. Even when trying to select a Python kernel with the path, it cannot still find it. 

![Screenshot 2023-04-18 at 11 32 42](https://user-images.githubusercontent.com/4527650/232721226-ca1d3811-2c26-4d31-b1b6-32f2da11a4ab.png)

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by kohlivarun5** [comment]
A new version was pushed for this to open-vsx: https://open-vsx.org/extension/ms-toolsai/jupyter

Does it work with the latest extension ?

**Comment by maksad** [comment]
@kohlivarun5 Apparently, `code-server` ([v4.12.0-rc.1](https://github.com/coder/code-server/releases/tag/v4.12.0-rc.1)) is not compatible withe the Jupyter's pre-release version (v2023.4.1001091014).  
```
Can't install pre-release version of 'ms-toolsai.jupyter' extension because 
it is not compatible with the current version of code-server (version 1.77.1).
```

ps. the same error is displayed with the `code-server v4.11.0`

**Comment by benz0li** [comment]
This is resolved. See https://github.com/coder/code-server/pull/6135#issuecomment-1517208225.

**Comment by maksad** [comment]
@benz0li thanks for the fix. I can confirm that the issue is now resolved.
