### ISSUE TITLE
[Bug]: Live preview extension does not work

### ISSUE THREAD

**Issue by Sparklingx** [coder/code-server#6156]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: edge, chrome
- Local OS: Windows 10
- Remote OS: Ubuntu 22.04 LTS
- Remote Architecture: Arm64(aarch64)
- `code-server --version`: code-server 4.11.0 85e083580dec27ef19827ff42d3c9257d56ea7e

### Steps to Reproduce

1.  Install this extension (https://open-vsx.org/extension/ms-vscode/live-server) (https://github.com/microsoft/vscode-livepreview)
2. run a simple hello world html code
3. Open the live preview extension, It will show the hello world but it will not work optimally, It will not auto refresh  and it will show error saying (Failed to load message bundle. See console for details.)

![image](https://user-images.githubusercontent.com/85538352/233705171-04dd414e-0d8f-448c-8ead-04eb2e0ecc95.png)

### Expected

It should automatically reload automatically our codes. 

### Actual

It doesnt reload automatically our codes and shows some error 

### Screenshot/Video

![image](https://user-images.githubusercontent.com/85538352/233707375-5378d3ab-9f23-473f-b8af-8b4db478d8f2.png)

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

In github codespaces it uses different version. but I do not see any error message there. This works flawlessly in vscode tho.

**Comment by code-asher** [comment]
I am not sure what causes this but I just wanted to post to say that I reproduced at least.

**Comment by Sparklingx** [comment]
> I am not sure what causes this but I just wanted to post to say that I reproduced at least.

Looks like the coder team is not sure  about the cause aswel

**Comment by code-asher** [comment]
This seems to work now.  Although, the frame appears to be blocked by CSP.  The same thing happens in Codespaces, so it does not appear to be a code-server bug at the moment.
