### ISSUE TITLE
ELFCLASS64 error

### ISSUE THREAD

**Issue by LeeTuah** [coder/code-server#6160]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Brave
- Local OS: Andriod 9
- Remote OS: Ubuntu 22.04.2 LTS
- Remote Architecture: armv81
- `code-server --version`: 4.12.0

### Steps to Reproduce

1. Install code server using tar.gz in linux-arm64 format
2. Launch code server

### Expected

code-server should launch and be accessable with browser

### Actual

Get an error message of wrong elf class

### Screenshot/Video

![Screenshot_20230422-153325_Termux](https://user-images.githubusercontent.com/77256247/233777595-3396a7eb-5951-4c48-891c-7cf3ef379a9a.jpg)

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [ ] I am using HTTPS.

**Comment by code-asher** [comment]
I am a bit out of my depth but I think that means it is running in a 32 bit environment?  Is armv81 supposed to be 64 bit?
