### ISSUE TITLE
[Bug]: proxy by nginx origin check error

### ISSUE THREAD

**Issue by 502647092** [coder/code-server#6161]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: EDGE
- Local OS: Windows
- Remote OS: Linux
- Remote Architecture: x64
- `code-server --version`: 4.12.0

### Steps to Reproduce

1. start code server by docker
2. proxy by nginx
3. open website

### Expected

.

### Actual

websocket connect error code 1006

### Logs

debug host "ide.wsc.ink:443" does not match origin "ide.wsc.ink"; 

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by 502647092** [comment]
I fix it by modify nginx config
Origin Config
```nginx
            proxy_set_header      Host                $host;
            proxy_set_header      X-Real-IP           $remote_addr;
            proxy_set_header      X-Forwarded-For     $proxy_add_x_forwarded_for;
            proxy_set_header      X-Forwarded-Host    $host:$server_port;
            proxy_set_header      X-Forwarded-Proto   $scheme;
```
Modified
```nginx
            proxy_set_header      Host                $host;
            proxy_set_header      X-Real-IP           $remote_addr;
            proxy_set_header      X-Forwarded-For     $proxy_add_x_forwarded_for;
            proxy_set_header      X-Forwarded-Host    $host;    <=== remove port
            proxy_set_header      X-Forwarded-Proto   $scheme;
```

**Comment by code-asher** [comment]
Oh interesting!  We should make special exceptions for 443 and 80.  https://github.com/coder/code-server/issues/6166

**Comment by kylefmohr** [comment]
> ```nginx
> proxy_set_header      Host                $host;
>             proxy_set_header      X-Real-IP           $remote_addr;
>             proxy_set_header      X-Forwarded-For     $proxy_add_x_forwarded_for;
>             proxy_set_header      X-Forwarded-Host    $host;    <=== remove port
>             proxy_set_header      X-Forwarded-Proto   $scheme;
> ```

Thanks for this, I was a few versions behind on code-server, and was getting this error. I had none of these set in my old nginx file, and adding them solved the issue for me.

**Comment by mashroomxl** [comment]
try nginx config as follows:
```nginx
location ~ ${your frontend url pattern} {
  resolver {your DNS server}

  proxy_http_version 1.1;
  # trick here, if absent, the server will block the websocket request! the server check if origin equal to host, shown above.
  proxy_set_header Origin http://${your backend host}/;
  proxy_set_header X-Forwarded-Host $host;
  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Proto $scheme;
  # trick here, consult https://nginx.org/en/docs/http/websocket.html for Nginx official doc
  proxy_set_header Upgrade $http_upgrade;
  proxy_set_header Connection upgrade;
  proxy_set_header Accept-Encoding gzip;

  proxy_cookie_domain ${your backend host} ${your frontend host};

  proxy_pass ${your backend url pattern};
}
```

config above working for me. my scene：

- code-server: 4.18.0, running in an container of Kubernetes
- nginx:1.9.7, running in an container of another Kubernetes.
