### ISSUE TITLE
[Bug]: 1006 websocket issue on haproxy in front of nginx

### ISSUE THREAD

**Issue by gcarrarom** [coder/code-server#6165]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Edge/Chrome
- Local OS: MacOS
- Remote OS: ubuntu - docker/kubernetes - codercom/code-server image
- Remote Architecture: amd64
- `code-server --version`: 4.11.0

### Steps to Reproduce

1. Install PFSense with HA Proxy and nginx 443 backend with SSL Offload. Ending Encryption with let's encrypt certificates
2. Install kubernetes nginx ingress controller to receive requests using 443 and let's encrypt certificates.
3. Install codeserver on the k8s cluster using the provided header annotations
4. Test codeserver using the HAProxy frontend endpoint.

### Expected

Connection should be upgraded with the 101 redirection and keep the websocket open.

### Actual

Socket gets closed with 1006 error and it keeps retrying, which leads to code-server not responding.

### Logs

  ERR CloseEvent {isTrusted: true, wasClean: false, code: 1006, reason: '', type: 'close', …}
log.ts:392  INFO [remote-connection][ExtensionHost][5af01…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
log.ts:392  INFO [remote-connection][ExtensionHost][5af01…][reconnect] resolving connection...
log.ts:392  INFO [remote-connection][ExtensionHost][5af01…][reconnect] connecting to coder.fancywhale.ca:443...
log.ts:392  INFO Creating a socket (renderer-ExtensionHost-5af01923-614e-4a83-82b7-82f66cc67cef)...
log.ts:392  INFO Creating a socket (renderer-ExtensionHost-5af01923-614e-4a83-82b7-82f66cc67cef) was successful after 16 ms.
log.ts:392  INFO [remote-connection][ExtensionHost][5af01…][reconnect] reconnected!
log.ts:392  INFO [remote-connection][ExtensionHost][5af01…][reconnect] received socket close event (wasClean: false, code: 1006, reason: ).

I am running coder/codeserver on kubernetes on the following topology: pfsense -> ha-proxy -> nginx -> coder/codeserver
When connecting directly from coder/codeserver it works fine, same from nginx. the problem starts with the ha-proxy layer. I have not found any information on how I should look into HA proxy for fixing this. Any ideas?

Thanks

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

I've tried connecting over local vscode and it doesn't throw this issues. It might be because it tries loading local extensions rather than the remote ones via websocket. So far I can only see this issue happening using the PWA or browser versions.

**Comment by code-asher** [comment]
One thing to check is that the host header is being forwarded correctly since if the host and origin do not match the web socket connection will be blocked (you can run code-server with `log --debug` to check if this is happening).

I am not familiar with haproxy so that is as far as my ideas go other than to say maybe there is websocket-specific configuration that needs to be added.

**Comment by gcarrarom** [comment]
Hey, thanks! I've tried that before and gave up on Haproxy -> Nginx -> codeserver. I've switched to nginx -> nginx -> codeserver and it is working well.

**Comment by krowvin** [comment]
## I am running a very similar setup
> I am running coder/codeserver on kubernetes on the following topology: pfsense -> ha-proxy -> nginx -> coder/codeserver  

*PFSense with HAProxy as a package pointed at Codeserver.*  

 **I was also getting Error 1006**  
```
An unexpected error occurred that requires a reload of this page.
The workbench failed to connect to the server (Error: WebSocket close with status code 1006)
```  


I have a shared frontend setup on my pfsense box for ssl termination. 

I was able to get the websockets to work though. 
Starting with this [SO post](https://stackoverflow.com/questions/58092451/x-forwarded-host-header-should-not-be-overwritten-by-the-haproxy-when-it-is-alre). 

The problem for me was that I had this set
`http-request set-header     X-Forwarded-Host %[dst];`
Under Advanced Settings > Advanced pass thru

It was overriding the X-Forwarded-Host header which @code-asher alludes to:
> One thing to check is that the host header is being forwarded correctly since if the host and origin do not match the web socket connection will be blocked  

You could comment out the X-Forward above, but I know I had it set for some reason so I ended up doing this in my Shared Frontend:
```
acl h_xfh_exists req.hdr(X-Forwarded-Host) -m found
http-request set-header X-Forwarded-Host %[req.hdr(host)] unless h_xfh_exists
```

**Comment by gcarrarom** [comment]
Great find! If I ever come back to HAProxy, I will give this a shot. Thanks for posting here for someone else in the future!

**Comment by douloveppt** [comment]
> 



> Hey, thanks! I've tried that before and gave up on Haproxy -> Nginx -> codeserver. I've switched to nginx -> nginx -> codeserver and it is working well.

hi, bro, i met the issue too, i use nginx reverse proxy code server,this is my nginx config:
```bash
location ^~ /codeserver{
    rewrite ^/codeserver(.*)$ $1 break;
    proxy_pass http://127.0.0.1:8445;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}
```


then i got the error:
`The workbench failed to connect to the server (Error: WebSocket close with status code 1006)`


NGINX error log：
`2023/06/08 15:26:20 [error] 41887#0: *876 open() "/opt/homebrew/Cellar/nginx/1.25.0/html/vs/workbench/api/worker/extensionHostWorker.nls.js.map" failed (2: No such file or directory), client: 127.0.0.1, server: localhost, request: "GET /vs/workbench/api/worker/extensionHostWorker.nls.js.map HTTP/1.1", host: "127.0.0.1:8298"
`

Can you show me your NGINX configuration?thank you very much~

**Comment by europacafe** [comment]
Hi,
I got the same 1006 error with Haproxy on pfSense. Any solution for this?
Thanks.

**Comment by code-asher** [comment]
@europacafe Have you configured `X-Forwarded-Host` as mentioned above?  If so please try running code-server with debug logging and check the server logs: https://github.com/coder/code-server/issues/6165#issuecomment-1540681516

**Comment by europacafe** [comment]
adding http-request set-header X-Forwarded-Host %[req.hdr(Host)] didn't help.

**Comment by code-asher** [comment]
Got it, let me know if you are able to gather logs.

**Comment by ulkyome** [comment]
Did you check your ssh config of the Server ?

sudo nano /etc/ssh/sshd_config
add new line/uncomment

AllowTcpForwarding yes
restart ssh-service with

sudo systemctl restart ssh
reconnect VSCode
