### ISSUE TITLE
[Bug]: language packs can't be installed

### ISSUE THREAD

**Issue by jonaskuske** [coder/code-server#6168]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome Android
- Local OS: Android 12
- Remote OS: Android 12 (termux) 
- Remote Architecture: aarch64
- `code-server --version`: 0.0.0 1da7cda39e54faa087cf129f0f85d4d4e63e81b8 with Code 1.77.3

### Steps to Reproduce

1. `code-server --install-extension ms-ceintl.vscode-language-pack-de`

### Expected

Installs language pack

### Actual

Installing extensions...
Installing extension 'ms-ceintl.vscode-language-pack-de'...                   The 'ms-ceintl.vscode-language-pack-de' extension is not available in code-server for Web.
Failed Installing Extensions: ms-ceintl.vscode-language-pack-de

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

Maybe related to the new localization api/impl in https://github.com/microsoft/vscode/issues/164438? 

(not using https but local host, which also allows service workers)

**Comment by jonaskuske** [comment]
Hmm this seems to be a broader issue, I also can't install themes (tried Night Owl). It just says "can't install for Web" for basically any extension

**Comment by code-asher** [comment]
Does the same error happen if you install through the UI instead of the command line?

I tried `code-server --install-extension ms-ceintl.vscode-language-pack-de` and `code-server --install-extension sdras.night-owl` but both worked for me.

I am using the `codercom/code-server:4.12.0` Docker image so maybe there is something odd about the Termux build?  The version being 0.0.0 is odd as well.

**Comment by jonaskuske** [comment]
Update: Installing extensions from a local .vsix works, from UI works too now (not sure why yet) and I also found a way to change language, not through the UI though. 

I can install extensions using the UI as long as they support the web runtime, which is expected I think, non-web extensions don't support the platform "android". I don't know yet if installs through the UI work only now that there was a successful install of a .vsix once, or if it has to do with the recent 4.13 update (and the corresponding termux package re-build). Will try to figure that out tomorrow.


What still doesn't work via the UI is installing & changing the language. Regular extensions can be installed, language packs can't. Installing via the .vsix works however! If you install from the external terminal, the language pack is installed and the prompt to install it doesn't show anymore, but still it does not work. If you want to change to the respective language in the UI, it prompts you to download the pack, then errors. But if you *install the .vsix via the integrated terminal*, it does work all of a sudden! 😊

**Comment by jonaskuske** [comment]
So with a bit of luck, the recent update fixed the installation of web extensions and the only thing that still needs a fix is UI installation of the locale :)

**Comment by jonaskuske** [comment]
Confirmed, installing extensions works fine now, but Language Packs have to be installed via `Extensions: Install from VSIX` or via the CLI in the integrated terminal.

**Comment by jonaskuske** [comment]
Alright, the issue is that `process.platform === 'android'` in Termux, so VS Code falls back to using the target Web. But Language Packs don't support *Web*, just win/mac/linux via target *Universal*.

I've now worked around this by overriding `process.platform` to make Android appear as Linux, and now all works fine :)

```sh
alias code-server="NODE_OPTIONS='-r $HOME/.android-as-linux.js' code-server"
```

```js
// ~/.android-as-linux.js
Object.defineProperty(process, 'platform', {
  get() { return 'linux' }
})
```

**Comment by code-asher** [comment]
Clever!
