### ISSUE TITLE
Nodejs version lts 18 [Bug]: 

### ISSUE THREAD

**Issue by thunderstorms-plus** [coder/code-server#6171]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome
- Local OS:  Android
- Remote OS: Linux
- Remote Architecture: arm64
- `code-server --version`: 4.12.0

### Steps to Reproduce

1. Install code server
2. yarn
3. yarn global add code-server

### Expected

must be set to version 18  nodejs to code-server

### Actual

actually failed to install due to current version of nodejs 18 and it should install old version 16 

### Logs

yarn global add code-server
yarn global v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
error code-server@4.12.0: The engine "node" is incompatible with this module. Expected version "16". Got "18.14.1"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.

### Screenshot/Video

![Screenshot_20230426_122815_Termux](https://user-images.githubusercontent.com/30003442/234533612-06fe0df0-8097-4a79-a8c2-2cdfa3953430.jpg)

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by code-asher** [comment]
Unfortunately we are stuck on Node 16 until VS Code updates to Node 18.

I believe you can ignore the engine requirement with `--ignore-engines` but there is no guarantee things will work.

**Comment by code-asher** [comment]
Also need to set `FORCE_NODE_VERSION` to use a different version of Node.

Looks like this is Termux so you could try installing the code-server package instead.

https://github.com/coder/code-server/blob/main/docs/termux.md#install

Otherwise you can follow the steps in the same document to install Node 16.

**Comment by thunderstorms-plus** [comment]
> Another thing, you would need to set `FORCE_NODE_VERSION` to use a different version of Node.
> 
> Looks like this is Termux so you could try installing the code-server package instead.
> 
> https://github.com/coder/code-server/blob/main/docs/termux.md#install
> 
> Otherwise you can follow the steps in the same document to install Node 16.

Ok!=)
Thanks!:)
