### ISSUE TITLE
[Bug]: Debugger/Debug Terminal does not restore on page load/reload 

### ISSUE THREAD

**Issue by flleeppyy** [coder/code-server#6173]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Many (Firefox, Chrome, Opera, Android WebView)
- Local OS: Many
- Remote OS: Ubuntu 20.04.6 LTS x86_64
- Remote Architecture: x86_64
- `code-server --version`: 
```
4.12.0 1da7cda39e54faa087cf129f0f85d4d4e63e81b8 with Code 1.77.3
```

### Steps to Reproduce

1. Open up a typescript project 
2. Open a debugger terminal
3. Run typescript project
4. Make sure running program stays on, such as a web server
5. Reload the page (Or hit Ctrl+W and have a 50/50 chance of it closing the file tab or the whole damn window, forcing you to open code-server again)
6. Debugger appears to be no longer running, but launching another debugger and running the project (for example, a webserver) says that the port is being used. 

### Expected

The debugger and the debug terminal should open back up and get you right back to where you were.

### Actual

Debugger does not restore, process is left running in the background with no way to stop it unless you manually find and kill the processes with htop (even worse if you use a dev stack like pnpm -> nodemon -> node -> ts-node)

### Logs

https://haste.fleepy.tv/amuzatulutad.yaml
Reload happens at [04:09:21] when debugger is open

### Screenshot/Video

https://user-images.githubusercontent.com/18307183/234847780-bdfcb61e-64cc-4d26-a0ff-f7d1543f1bf3.mp4

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

In the video I showed, I was not using HTTPS, but on my remote server that I do work on, it is served through HTTPS.

**Comment by code-asher** [comment]
Does this for sure not reproduce for you in Codespaces?  I tried but it reproduces for me in Codespaces.  If so we might want to raise it upstream.

**Comment by bosmart** [comment]
Happens in Codespaces for me too with Python debugger.

**Comment by code-asher** [comment]
I marked this as upstream.  I see they mentioned not restoring state is expected behavior, but it seems like it is not expected that the debugging process should stay up and occupy the port?  If that is still happening it would be worth it to raise upstream again.
