### ISSUE TITLE
[Bug]: port forwarding returns 401 error for non-browser requests

### ISSUE THREAD

**Issue by vicmortelmans** [coder/code-server#6174]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Firefox
- Local OS: Windows/Linux
- Remote OS: Ubuntu 20.04
- Remote Architecture: 
- `code-server --version`: 
code-server: v4.11.0
Code: 1.76.1
Commit: 5e805b79fcb6ba4c2d23712967df89a089da575b
Date: 2023-03-14T20:11:32.198Z (1 mo ago)
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0

### Steps to Reproduce

1.  run `index.js` with an express app and listeners for handling GET or POST requests, e.g. on port 3024; 
e.g. full url: `http://localhost:3024/interface`

2.  code-server, running on `localhost:8082` automatically sets up port forwarding;
e.g. full url: `http://localhost:8082/proxy/3024/interface`

3. nginx acts as a reverse proxy to forward any request on `https://<my-code-server-domain>/*` to code-server, running on `localhost:8082`
(I think the nginx-part may not be relevant for this problem)

### Expected

1. `curl http://localhost:3024/interface` can access the API 

2. `curl http://localhost:8082/proxy/3024/interface` can also access the API

3. `curl https://<my-code-server-domain>/proxy/3024/interface` can also access the API

### Actual

1. `curl http://localhost:3024/interface` can access the API
**=> PASS! this works**

2. `curl http://localhost:8082/proxy/3024/interface` can also access the API
**=> FAIL! return value is {"error":"Unauthorized"}**, which translates as an HTTP Error 401.

3. `curl https://<my-code-server-domain/proxy/3024/interface` can also access the API
**=> FAIL! return value is HTTP Error 401**.

Note: the request DOES pass when the request is made from the browser where the webpage is shown that is served by this app!

### Logs

--verbose logging doesn't show anything relevant while processing a request

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by code-asher** [comment]
Yeah the port forwarding is behind code-server's authentication so you have to provide a cookie with the password.  It would be nice to have the option to make a port public.

https://github.com/coder/code-server/discussions/6151#discussioncomment-5712031

**Comment by vicmortelmans** [comment]
Thanks, 

as my GET/POST request originates from the same server, I suppose I can ask it to make the request to `http://localhost:3024/interface` directly, bypassing the port forwarding.

best regards,
Vic

**Comment by code-asher** [comment]
Yup we make no exceptions for local access (otherwise users on the same machine could access other user's code-servers).

If you only need local requests then avoiding the proxy is the best solution!

**Comment by code-asher** [comment]
I will go ahead and close this in favor of https://github.com/coder/code-server/issues/6008
