### ISSUE TITLE
[Bug]: Built-in marketplace does not show all available extensions

### ISSUE THREAD

**Issue by GrantFinneman** [coder/code-server#6184]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome
- Local OS: Windows 10/11
- Remote OS: CentOS
- Remote Architecture:
- `code-server --version`: v4.11.0

### Steps to Reproduce

1. Open marketplace tab
2. search for **modern fortran**
3. 

### Expected

I expect to see the extension **modern fortran** show up and be available to install.

### Actual

The extension does not show up. Other ones with fortran in the name appear but not the one I want.

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

I've found the extension by looking on the website and have installed it manually but since the dependencies are not automatically grabbed, the manual installation isn't a good workaround.

**Comment by code-asher** [comment]
Looks like they are running into some licensing roadblocks publishing on Open VSX: https://github.com/fortran-lang/vscode-fortran-support/issues/190

I will close the issue since there is nothing we can do from our end.  Thank you for the report!
