### ISSUE TITLE
"[2023-05-03T07:39:06.690Z] error timed out" ERROR on Raspberry Pi 0 w

### ISSUE THREAD

**Issue by pyIronManCoder** [coder/code-server#6189]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser:
- Local OS:
- Remote OS: Raspbian (Raspberry Pi OS 32 bit)
- Remote Architecture: armv6l
- `code-server --version`: 4.12.0 1da7cda39e54faa087cf129f0f85d4d4e63e81b8 with Code 1.77.3

### Steps to Reproduce

1. Install code-server on raspberry pi 0 w using "yarn global add code-server"
2. After successful install run "code-server"

### Expected

It should throw an error saying '[2023-05-03T07:39:06.690Z] error timed out'.

### Actual

Code-server doesn't run.

### Logs

[2023-05-03T15:48:56.210Z] error timed out

### Screenshot/Video

![image](https://user-images.githubusercontent.com/122616133/235969401-640e531b-5963-46af-8bf5-b5f3658ee28c.png)

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by code-asher** [comment]
Do you know if this is still an issue?

**Comment by pyIronManCoder** [comment]
Sorry, but I stopped the project long ago, as it wasn't working... And I erased the sd card... But thanks for the amazing repo
