### ISSUE TITLE
[Bug]: cannot connect remotely to jupyterhub

### ISSUE THREAD

**Issue by BouarfaMahi** [coder/code-server#6193]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Brave
- Local OS: Ubuntu Server 22.04 with code server in a docker container.
- Remote OS: Ubuntu Server 22.04 with JupyterHub
- Remote Architecture: x86_64
- `code-server --version`:code-server: v4.12.0

### Steps to Reproduce

1. install jupyter extension
2. open a jupyter notebook
3. insert the remote server url 
4. https://<your-jupyterhub-url>/user/<your-jupyterhub-user-name>/?token=<your-token>

### Expected

an established connection to the remote jupyterhub environment and viewing the notebook.

### Actual
no connection in this configuration, cannot view the notebook.
the connection is established when using VSCode desktop on windows.

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [ ] I am using HTTPS.

**Comment by thevedicdeveloper** [comment]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: firefox, edge, google chrome
- Local OS: macos
- Remote OS: ubuntu-server
- Remote Architecture: arm64
- `code-server --version`:latest


### Steps to Reproduce

1. Open Visual Studio Code on one machine.
2. Create or open a file in the editor.
3. Save the file.
4. Access the same file from a different machine using a network or cloud storage.
5. Attempt to view the file content.


### Expected

I should be able to view the content of the .ipynb file from a different machine, when I accessed the vscode container using the IP address of the machine which is running the vs code container.

### Actual

I am able to see the vscode when accessed over the network, but is not able to view the content of the file.

Although I can see the cells in the outline section of the vscode (bottom left)

- When accessing the vscode from the machine which is running the vscode container --> able to see the content of the file.
![Screenshot 2023-05-18 at 12 21 11 PM](https://github.com/coder/code-server/assets/97366282/024e1e41-5a6c-40dc-aeb9-6ace7ea661ca)

- when accessing the vscode from a different machine using ip address of the machine which is running the vscode container.  ---> the file content is not visible on the editor, but we can see the content in the left side of the `outline` pannel
![Screenshot 2023-05-18 at 12 21 59 PM](https://github.com/coder/code-server/assets/97366282/e34a7baa-760d-44aa-a434-3a5c91ab0033)


### Logs

_No response_

### Screenshot/Video

_No response_

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

I have not tried in VS CODE and GitHub Codespaces.

Please let me know if I need to provide any other information

**Comment by benz0li** [comment]
You are not using HTTPS. This is required for Jupyter notebooks.  
ℹ️ Fully qualified domain name (FQDN) required, too. TLS for an IP is not sufficient.

HTTP only works for `127.0.0.1` / `localhost.`

Cross reference: https://github.com/coder/code-server/issues/5475#issuecomment-1229529712

**Comment by BouarfaMahi** [comment]
@benz0li   Many thanks it works.
