### ISSUE TITLE
[Bug]: Keybinding 'delete' does not work as expected in webview contextual menu

### ISSUE THREAD

**Issue by pablocabrera85** [coder/code-server#6197]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome
- Local OS: macOS
- Remote OS: Ubuntu
- Remote Architecture: amd64
- `code-server --version`: 4.11.0

### Steps to Reproduce

1. Install an extension that has a `delete` keybindings configured for a command used in the context menue of a webview
2. Trigger the contextual menu from the UI

### Expected

A menu option with a key binding should be rendered. This works as expected when running on desktop.
<img width="205" alt="image" src="https://github.com/coder/code-server/assets/3269977/feef9a38-421b-4718-91e0-72b07ed7a650">

### Actual

Two label are rendered side by side instead of the key configured.

<img width="258" alt="image" src="https://github.com/coder/code-server/assets/3269977/3a9ac9fb-c49a-4cb3-b44c-e2911996e29e">

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

I actually don't know if this can be reproduced in codespaces. 
When using the debugger tools, that second label does have a keybinding className, so it would seem that it is not entirely wrong the rendering.

**Comment by code-asher** [comment]
We should test this on Codespaces since it is likely an upstream issue.  Can you provide the ID of an extension that I can install to reproduce the issue?

**Comment by code-asher** [comment]
Closing as stale but feel free to comment if you come back to this.
