### ISSUE TITLE
[Feat]: Accept Multiple GITHUB_TOKEN 

### ISSUE THREAD

**Issue by rlizzo** [coder/code-server#6199]
## What is your suggestion?

I would like to be able to pass multiple tokens via the `GITHUB_TOKEN` environment variable. 

## Why do you want this feature?

GitHub tokens need to match the expected scopes for a package to authenticate to it. While the `code server` `GITHUB_TOKEN` env var allows us to inject a single token, if we have multiple packages we want to authenticate, but which require different token scopes, we can't inject multiple tokens via this method.   

## Are there any workarounds to get this functionality today?

Not that I am aware of. It would be good to create a mapping of all scopes (not just order of permissions, but inclusion of permissions) -> a single token which grants such scopes.  

## Are you interested in submitting a PR for this?

Yes.

**Comment by code-asher** [comment]
Makes sense to me, we can make `--github-auth` take a string array and delimit `GITHUB_TOKEN` with semicolons or something.

**Comment by rlizzo** [comment]
any pointers on where to get started @code-asher? I assume `src/node/cli.ts` and `patches/github-auth.diff`? any other areas i might need to pay attention to?

**Comment by code-asher** [comment]
Closing for now, as this will require patching VS Code and it probably makes more sense to make the change there directly.
