### ISSUE TITLE
[Bug]: toggle terminal shortcut issues

### ISSUE THREAD

**Issue by EmranMR** [coder/code-server#6209]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Safari
- Local OS: iPadOS 16.4.1
- Remote OS: Ubuntu 22
- Remote Architecture: 64bit
- `code-server --version`: 1.77.3

### Steps to Reproduce

1. Open code server, either use the default shortcut to **toggle the terminal** [ctrl+’] or user default [cmd+’]
2. The terminal toggles open however when you press the shortcut, it does not hide the terminal
3. This is the same case if you use the “command palette” and type “toggle terminal”

### Expected

The terminal to toggle open and close

### Actual

The terminal opens does not close

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

I do not have access to github code space and online vs code

**Comment by city945** [comment]
I'm having the same problem, does anyone have a solution?

**Comment by city945** [comment]
I added an additional shortcut to open the terminal
cmd+shit+p -> open keyboard shortcus
add new keybinding to keybindings.json
```
    {
        "key": "ctrl+cmd+`",
        "command": "runCommands",
        "args": {
            "commands":[
                "workbench.action.toggleSidebarVisibility",
                "workbench.action.toggleSidebarVisibility",
                "workbench.action.terminal.toggleTerminal",
            ]
        },
    },
```

**Comment by code-asher** [comment]
This seems likely to be an upstream bug, we should reproduce in Codespaces and report it there.
