### ISSUE TITLE
[Bug]: Issue with thunder client extension

### ISSUE THREAD

**Issue by xorbetto** [coder/code-server#6214]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Safari / Chrome
- Local OS: Mac OS/Windows
- Remote OS: Arch Linux
- Remote Architecture: amd64
- `code-server --version`:  4.12.0

### Steps to Reproduce

1.  open code-server
2. install thunder client extension
3. try to use it, error pop up in the browser console: 'blocked script execution .... because the document's frame is sandboxed and the 'allow-scripts' permission is not set'

### Expected

The extension function correctly

### Actual

The extension didn't load correctly

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by code-asher** [comment]
Seems like this was probably an extension bug that was fixed; I tried it just now and it appears to work.
