### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by jungyin** [coder/code-server#6221]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser:
- Local OS:android 12 termux
- Remote OS:android 12

### Steps to Reproduce

1.run the vscode
2.Press ctrl+s in the input area to save the file
3.Failed to save the file normally, but added an s byte in the current input area

### Expected

When writing code on my Android tablet device, some shortcut keys cannot be used (such as ctrl+s, which does not save files but appends a text s to the current location), but if used in Terminal, it can still be used normally. What should I do?

Additionally, I have found that not all shortcut keys have failed. For example, if I use ctrl+c, ctrl+v, I can still copy and paste code normally

### Actual

I hope to be able to use the code server shortcut on my Android device normally

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by code-asher** [comment]
Marking this as an upstream bug, we should reproduce in Codespaces and report upstream.
