### ISSUE TITLE
[Feat]: How to support remote ssh, or is there any alternative

### ISSUE THREAD

**Issue by liyongshun** [coder/code-server#6236]
## What is your suggestion? 
Connect to a personal machine or server
## Why do you want this feature?
Connect to a personal machine via ssh or otherwise

**Comment by code-asher** [comment]
You can also forward code-server through ssh or use native VS Code's remote SSH extensions.

If you are looking for a way to connect to a remote machine via SSH from within another code-server then that is not supported although there is an issue open for it: https://github.com/coder/code-server/issues/1315
