### ISSUE TITLE
User-forwarded ports do not use VSCODE_PROXY_URI

### ISSUE THREAD

**Issue by code-asher** [coder/code-server#6241]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

N/A

### Steps to Reproduce

1. Open ports panel
2. Add a port

### Expected

Should use VSCODE_PROXY_URI.

### Actual

In my case I get `http://localhost:8080`.

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by smerschjohann** [comment]
I cannot reproduce with the current main branch

with automatic VSCODE_PROXY_URI based on proxy-domain it works:
```VSCODE_PROXY_URI= yarn watch --auth=none --proxy-domain 'code-{{port}}.domain.tld'```

![port-forward-proxy-domain](https://github.com/coder/code-server/assets/11621401/0ff365bf-669e-44ee-9db8-fa6a160382e3)


and also if supplied manually:
```VSCODE_PROXY_URI=https://tunnel-{{port}}.domain.tld yarn watch --auth=none'```

![port-forward-proxy-uri](https://github.com/coder/code-server/assets/11621401/b377cdce-e9da-4b62-808f-dc939d743cab)

**Comment by code-asher** [comment]
Interesting!  I will try again, maybe I was running the wrong version or something.

**Comment by code-asher** [comment]
This is weird, it only happens to me if I access code-server over localhost and if I add the same port that code-server is running on.

Here is one I was running with a plain `yarn watch` (so it should use `/proxy/{{port}}` and code-server is running on port 8080:

![ports](https://github.com/coder/code-server/assets/45609798/b690d593-f723-44dc-b0de-eff03693ce9d)

Here I used `VSCODE_PROXY_URI= yarn watch --auth=none --proxy-domain 'code-{{port}}.domain.tld'` and ran code-server on port 8081:

![ports2](https://github.com/coder/code-server/assets/45609798/1c5be784-7a13-4553-aa71-d5af4a87a45c)

Since it only happens with localhost and code-server's own port I think we can just ignore it because that seems like a use case that has no purpose anyway.

**Comment by code-asher** [comment]
Actually technically those are not even that wrong because although it is not using the proxy accessing those URLs will indeed show code-server running on that port.
