### ISSUE TITLE
[Bug]: code-server can not run python file

### ISSUE THREAD

**Issue by 18392152392** [coder/code-server#6251]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser:
- Local OS:
- Remote OS:
- Remote Architecture:
- `code-server --version`:

### Steps to Reproduce

1. I download the latest code-server, version is code-server-4.13.0
2. I use ./code-server --port 5000 to start
3. I download the python extension then it toast some warnings
4. the error is as followings
5. 
![242514985-5364d383-e068-47cf-ba67-523aec0787ed](https://github.com/coder/code-server/assets/52459655/0e4c3b5b-5572-4c61-88f4-c688e5b9c42a)

6. the question is that I can not install Pylance extension，so in python file, I can not execute rename symbol and other function
7. I think it is a very very serious bug, Can you help to fix? thank you very much

### Expected

it must happen

### Actual

it actually happens

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by code-asher** [comment]
Could you post the extension host and code-server logs?

**Comment by madcpt** [comment]
Pylance is not open-source, you can try installing from VXIS though.

**Comment by code-asher** [comment]
Closing as stale but feel free to comment if you come back to this.
