### ISSUE TITLE
[Bug]: Firefox special keyboard shortcut not working

### ISSUE THREAD

**Issue by TheRolfFR** [coder/code-server#6260]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Firefox 114.0.1 (64 bits)
- Local OS: Windows 11 22H2 (OS Build 22621.1702)
- Remote OS: Ubuntu 20.04.5 LTS
- Remote Architecture: x86_64 
- `code-server --version`: v4.13.0

### Steps to Reproduce

1. Open browser and login
2. Change layout to french
3. Try to create or open terminal

### Expected

terminal panel should open

### Actual

Nothing

### Screenshot/Video

Impossible to change shortcuts with special keys like `ù` on French azerty keyboard or any punctuation key:
![image](https://github.com/coder/code-server/assets/18086786/ce2d5d70-e5d1-40f7-95cc-37dab9efb15b)

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

I can reproduce it on GitHub Codespaces, looks like its a key problem

**Comment by code-asher** [comment]
If it reproduces in Codespaces we might have better luck getting 
it fixed it upstream in https://github.com/microsoft/vscode.
