### ISSUE TITLE
[Bug]: Sometimes the output interrupts the input, causing an error

### ISSUE THREAD

**Issue by PoolarBBear** [coder/code-server#6267]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser:chrome on windows& safari on ipad
- Local OS:windows & ipados
- Remote OS:ubuntu
- Remote Architecture:amd64
- `code-server --version`:4.13.0

### Steps to Reproduce

1. install extension C/C++ and CodeLLDB
2.run

### Expected

I have written a program with the following input（I use paste）:
4 500
330106199010080419 499
110108198403100012 15000
120104195510156021 800
330106199010080419 1
4
120104195510156021
110108198403100012
330106199010080419
33010619901008041x

and the output should be:
![屏幕截图 2023-06-15 225424](https://github.com/coder/code-server/assets/59532459/cdb3adac-b603-468b-9be0-0f29bff51e04)

### Actual

sometimes the output:
![微信图片_20230615225750](https://github.com/coder/code-server/assets/59532459/118d8f38-b44d-42c1-a3e2-a8890426fde9)
I guess the input should be interrupted by the output, because the line above the number 15000 was originally reading 330106199010080419, but there was an output of 800 that interrupted the process, so we see that the line above the number 15000 ends with 800 , and cannot read 330106199010080419 completely
how can i solve this problem？？

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by code-asher** [comment]
Hard to say what the problem is without seeing the source code for 
your program but perhaps it needs some mechanism for waiting until 
the input has been fully received before generating output.  The 
latency between the client and server might cause the interleaving 
to be more pronounced than it would be locally.

**Comment by code-asher** [comment]
Closing as stale, and probably not code-server related, but happy to discuss more.
