### ISSUE TITLE
[Bug]: Middle click to close tab not working in Safari

### ISSUE THREAD

**Issue by mateuszlewko** [coder/code-server#6272]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Safari
- Local OS: macOS
- Remote OS: debian
- `code-server --version`: v4.13.0

### Steps to Reproduce

1. Open any editor tab.
2. Mouse middle click on tab to close it.

### Expected

The tab should close.

### Actual

The tab doesn't close.

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [ ] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

It works perfectly on chrome.

**Comment by code-asher** [comment]
Are you sure this does not reproduce on Codespaces?  This seems 
like something that would almost certainly be an upstream issue.

**Comment by code-asher** [comment]
A fix on the code-server end would require adding a new patch, so 
it is doable but if it is possible to fix then it would be much 
better to fix it upstream in https://github.com/microsoft/vscode.

Looks like VS Code binds to the `auxclick` event which is 
apparently not supported in Safari: https://caniuse.com/auxclick

Perhaps a fallback can be implemented by using `click` instead 
which does appear to be supported in Safari.
