### ISSUE TITLE
[Bug]: "Go live" button from live previous extension does nothing

### ISSUE THREAD

**Issue by Nagrajnagas** [coder/code-server#6273]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser:
- Local OS:                    in this not opening
- Remote OS:
- Remote Architecture:
- `code-server --version`:

### Steps to Reproduce

1. open code server
2.
3.

### Expected

opening 

### Actual

not opening 

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

not opening

[#style.css - .vscode - Visual Studio Code 2023-06-17 18-43-32.zip](https://github.com/coder/code-server/files/11779086/style.css.-.vscode.-.Visual.Studio.Code.2023-06-17.18-43-32.zip)

**Comment by neto737** [comment]
Same problem here after upgrade from 4.13.0 to 4.14.0 (I'm using latest Debian version btw)

```
INFO Resolving connection token (code.domain.tld)...
INFO Resolved connection token (code.domain.tld) after 4 ms
INFO Creating a socket (renderer-Management-4a9e614d-d191-42ae-9cad-292e80d91ff2)...
```

**Comment by code-asher** [comment]
Are there any errors in the browser console?

**Comment by Nagrajnagas** [comment]
In browser show s error msg

NAG🤴.$

**Comment by Nagrajnagas** [comment]
NAG🤴.$

**Comment by code-asher** [comment]
Could you post the error message?

**Comment by Nagrajnagas** [comment]
Yes, I can.

NAG🤴.$

**Comment by Nagrajnagas** [comment]
Live server extension shows as below image

NAG🤴.$

**Comment by code-asher** [comment]
Hmm I am not seeing an image.  Are you sure you sent one?
