### ISSUE TITLE
[Bug]: can't install 'vue.volar' extension because it is not compatible with the current version of code-server (version 1.66.2).

### ISSUE THREAD

**Issue by chudongsong** [coder/code-server#6279]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Microsoft Edge
- Local OS: window11
- Remote OS: CentOS 7.9.2009 x86_64
- Remote Architecture: amd64
- `code-server --version`: Latest version

### Steps to Reproduce

1. After installing using commands
2. Extension installation plugin "Vue Language Features (Volar)"

### Expected

According to my understanding, it may be due to the current version being too low, which prevents the extension from being installed

### Actual

can't install 'vue.volar' extension because it is not compatible with the current version of code-server (version 1.66.2).

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by code-asher** [comment]
Are you sure you are running the latest version of code-server? 
The latest version (4.14.0) packages Code 1.79.2, not 1.66.2.  You 
can run `code-server --version` or use Help > About from the menu 
to check.

**Comment by code-asher** [comment]
Closing for now, but let me know if you still have problems after updating.
