### ISSUE TITLE
[Bug]: open files and layout not saving between sessions

### ISSUE THREAD

**Issue by Abul22** [coder/code-server#6280]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome
- Local OS: Windows 10
- Remote OS: Ubuntu 20.02
- Remote Architecture: ARM64
- `code-server --version`: 4.1

### Steps to Reproduce

1. Log in to instance in incog chrome window.
2. Open a few file tabs, split the window in 2, open a terminal etc.
3. Save workspace
4.  exit
5. start new incog session, log in - see just the welcome screen, even after loading the workspace or visiting it directly via url

### Expected

Should show the files I had open and the layout the same. 

### Actual

see just the welcome screen, no open files, no terminal open, even after loading the workspace or visiting it directly via url.

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

Seems to remember the files/layout when within the same chrome session -- so is it only saving that data local rather than in a server held JSON?

**Comment by code-asher** [comment]
Right, VS Code stores that information in browser storage so going 
incognito will wipe all of that.

If I recall correctly there was some effort made to patch VS Code 
so it would store it on the remote instead (as it once used to) 
but it was non-trivial.  PRs to patch it are welcome though.

Another angle might be to submit an issue upstream to see if they 
have any interest in at least making this optional as it affects 
their Codespaces product as well.

**Comment by code-asher** [comment]
I will roll this up into https://github.com/coder/code-server/issues/4212 since the fix for persisting between browsers is the same as persisting between incognito sessions.
