### ISSUE TITLE
[Bug]: Provisioning  the remote JupyterHub server URL  in a docker container

### ISSUE THREAD

**Issue by BouarfaMahi** [coder/code-server#6284]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Steps to Reproduce

Code-server supports connecting to a remote Jupyter notebook server, and we can use that to connect to our JupyterHub with the URL https://<your-hub-url>/user/<your-hub-user-name>/?token=<your-token>. 

The issue is that I need to refresh the code-server page to choose the Kernel to use. Is there any way to provision this URL in a Docker container or where is located the code-server file system that registers this URL?

### Expected

Connecting code-server to  a remote JupyterHub instance from a browser without refreshing the web page.

### Actual

need to refresh the browser.

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by code-asher** [comment]
I am not very familiar with the Jupyter extension but I 
experimented with changing the kernel (using the kernel select 
button in the upper right corner of the notebook) and it seems to 
swap kernels without needing to refresh the page.

Am I doing the right thing or are there different steps to the 
reproduction?

**Comment by BouarfaMahi** [comment]
i  tried again with the same issue.
1. remove the remote jupyterHub url by clicking on the trash icon
2. copy past the remote url then apply enter.
3. click on the kernel select and no kernel appears.
4.  refresh the browser and the kernels are present.

**Comment by BouarfaMahi** [comment]
Thanks code-asher,  solved with
https://github.com/microsoft/vscode-jupyter/issues/13759
