### ISSUE TITLE
[Bug]: Terminal kubectl exec log spam

### ISSUE THREAD

**Issue by gcarrarom** [coder/code-server#6285]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Version 114.0.5735.133 (Official Build) (arm64)
- Local OS: Version 14.0 Beta (23A5257q)
- Remote OS: [k8s pod](https://gitlab.fancywhale.ca/fancywhale-corporation/code-server) - k3s
- Remote Architecture: amd64
- `code-server --version`: 1.79.2 695af097c7bd098fbf017ce3ac85e09bbc5dda06 x64

### Steps to Reproduce

1. Open Code-Server
2. install kubectl
3. Run `kubectl exec -it ${pod_name} -- ${executable}`

### Expected

```bash
zsh ⌁ kubectl exec -it link-7bdfd54bbd-p5gbb -- sh
Alias tip: k exec -it link-7bdfd54bbd-p5gbb -- sh
/etc/shlink # echo true
true
/etc/shlink #
```

### Actual

sh ⌁ kubectl exec -it link-7bdfd54bbd-p5gbb -- sh  
Alias tip: k exec -it link-7bdfd54bbd-p5gbb -- sh
I0623 12:49:38.615075   30597 log.go:194] (0xc0000f71e0) (0xc000147ae0) Create stream
                                                                                     I0623 12:49:38.615163   30597 log.go:194] (0xc0000f71e0) (0xc000147ae0) Stream added, broadcasting: 1
              I0623 12:49:38.617012   30597 log.go:194] (0xc0000f71e0) Reply frame received for 1
                                                                                                 I0623 12:49:38.617034   30597 log.go:194] (0xc0000f71e0) (0xc0005c0500) Create stream
          I0623 12:49:38.617041   30597 log.go:194] (0xc0000f71e0) (0xc0005c0500) Stream added, broadcasting: 3
                                                                                                               I0623 12:49:38.618121   30597 log.go:194] (0xc0000f71e0) Reply frame received for 3
                      I0623 12:49:38.618147   30597 log.go:194] (0xc0000f71e0) (0xc00069e0a0) Create stream
                                                                                                           I0623 12:49:38.618155   30597 log.go:194] (0xc0000f71e0) (0xc00069e0a0) Stream added, broadcasting: 5
                                    I0623 12:49:38.619133   30597 log.go:194] (0xc0000f71e0) Reply frame received for 5
                                                                                                                       I0623 12:49:38.619143   30597 log.go:194] (0xc0000f71e0) (0xc0007f1ea0) Create stream
                                I0623 12:49:38.619147   30597 log.go:194] (0xc0000f71e0) (0xc0007f1ea0) Stream added, broadcasting: 7
                                                                                                                                     I0623 12:49:38.620052   30597 log.go:194] (0xc0000f71e0) Reply frame received for 7
                                            I0623 12:49:38.620141   30597 log.go:194] (0xc0007f1ea0) (7) Writing data frame
                                                                                                                           I0623 12:49:38.693322   30597 log.go:194] (0xc0000f71e0) Data frame received for 5
                                 I0623 12:49:38.693348   30597 log.go:194] (0xc00069e0a0) (5) Data frame handling
                                                                                                                 I0623 12:49:38.693365   30597 log.go:194] (0xc00069e0a0) (5) Data frame sent
                 /etc/shlink # I0623 12:49:38.693650   30597 log.go:194] (0xc0000f71e0) Data frame received for 5
                                                                                                                 I0623 12:49:38.693676   30597 log.go:194] (0xc00069e0a0) (5) Data frame handling
                     I0623 12:49:38.693689   30597 log.go:194] (0xc00069e0a0) (5) Data frame sent
/etc/shlink # I0623 12:49:38.705208   30597 log.go:194] (0xc0005c0500) (3) Writing data frame
                                                                                             I0623 12:49:38.718260   30597 log.go:194] (0xc0005c0500) (3) Writing data frame
                                                                                                                                                                           I0623 12:49:41.275368   30597 log.go:194] (0xc0005c0500) (3) Writing data frame
                                                                              I0623 12:49:41.276820   30597 log.go:194] (0xc0000f71e0) Data frame received for 5
                                                                                                                                                                I0623 12:49:41.276842   30597 log.go:194] (0xc00069e0a0) (5) Data frame handling
                                                                    I0623 12:49:41.276859   30597 log.go:194] (0xc00069e0a0) (5) Data frame sent
                                                                                                                                                cI0623 12:49:41.371018   30597 log.go:194] (0xc0005c0500) (3) Writing data frame
                                                    I0623 12:49:41.372063   30597 log.go:194] (0xc0000f71e0) Data frame received for 5
                                                                                                                                      I0623 12:49:41.372086   30597 log.go:194] (0xc00069e0a0) (5) Data frame handling
                                          I0623 12:49:41.372106   30597 log.go:194] (0xc00069e0a0) (5) Data frame sent
                                                                                                                      lI0623 12:49:41.468063   30597 log.go:194] (0xc0005c0500) (3) Writing data frame
                          I0623 12:49:41.469351   30597 log.go:194] (0xc0000f71e0) Data frame received for 5
                                                                                                            I0623 12:49:41.469372   30597 log.go:194] (0xc00069e0a0) (5) Data frame handling
                I0623 12:49:41.469384   30597 log.go:194] (0xc00069e0a0) (5) Data frame sent
                                                                                            eI0623 12:49:41.527650   30597 log.go:194] (0xc0005c0500) (3) Writing data frame
                                                                                                                                                                           I
I0623 12:49:41.680068   30597 log.go:194] (0xc0000f71e0) Data frame received for 5
                                                                                  I0623 12:49:41.680075   30597 log.go:194] (0xc00069e0a0) (5) Data frame handling
                                                                                                                                                                  I0623 12:49:41.680079   30597 log.go:194] (0xc00069e0a0) (5) Data frame sent
                                                                  /etc/shlink # I0623 12:49:41.688525   30597 log.go:194] (0xc0005c0500) (3) Writing data frame
                                                                                                                                                               I0623 12:49:41.708144   30597 log.go:194] (0xc0005c0500) (3) Writing data frame

### Logs

[IPC Library: Pty Host] DEBUG CommandDetectionCapability#handlePromptStart 0 0
[IPC Library: Pty Host] DEBUG CommandDetectionCapability#handleCommandStart 6 2
[IPC Library: Pty Host] DEBUG CommandDetectionCapability#handleRightPromptStart 132
[IPC Library: Pty Host] DEBUG CommandDetectionCapability#handleRightPromptEnd 132
[IPC Library: Pty Host] DEBUG CommandDetectionCapability#handlePromptStart 0 0
[IPC Library: Pty Host] DEBUG CommandDetectionCapability#handleCommandStart 6 2
[IPC Library: Pty Host] DEBUG CommandDetectionCapability#handleRightPromptStart 139
[IPC Library: Pty Host] DEBUG CommandDetectionCapability#handleRightPromptEnd 139
[IPC Library: Pty Host] DEBUG CommandDetectionCapability#handleCommandExecuted 0 4
[IPC Library: Pty Host] DEBUG CommandDetectionCapability#setCommandLine kubectl exec -it link-7bdfd54bbd-p5gbb -- sh true
[IPC Library: Pty Host] DEBUG ChildProcessMonitor: Has child processes changed true
[2023-06-23T16:57:47.690Z] debug 2 active connections

### Screenshot/Video

![CleanShot 2023-06-23 at 12 57 22](https://github.com/coder/code-server/assets/10549675/fca8e3b8-bff8-46f5-a1e6-5cd182f85805)

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

This environment is currently running on a cluster that exposes this service using nginx. Here's the nginx extra configuration:
```yaml
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    meta.helm.sh/release-name: code
    meta.helm.sh/release-namespace: vscode
    nginx.ingress.kubernetes.io/auth-response-headers: Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid
    nginx.ingress.kubernetes.io/auth-signin: https://auth.fancywhale.ca/outpost.goauthentik.io/start?rd=$escaped_request_uri
    nginx.ingress.kubernetes.io/auth-snippet: |
      proxy_set_header X-Forwarded-Host $http_host;
    nginx.ingress.kubernetes.io/auth-url: http://ak-outpost-authentik-embedded-outpost.identity.svc.cluster.local:9000/outpost.goauthentik.io/auth/nginx
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/server-snippets: |
      location / {
        proxy_set_header Upgrade $http_upgrade;
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header Connection "upgrade";
        proxy_cache_bypass $http_upgrade;
        }
    nginx.ingress.kubernetes.io/websocket-services: code
```
Running extensions and websockets are not terminated on the nginx logs as far as I can tell: 
```log
ingress-nginx/ingress-nginx-controller-2gk2w[controller]: 10.88.108.1 - - [23/Jun/2023:17:02:47 +0000] "GET /update/check HTTP/2.0" 200 0 "https://code.fancywhale.ca/?folder=/Source/fancywhale/setup" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36" 0 0.003 [vscode-code-8080] [] 10.43.239.56:9000 0 0.003 200 516daab65c34704482cf77fe940df8b4
ingress-nginx/ingress-nginx-controller-2gk2w[controller]: 10.88.108.1 - - [23/Jun/2023:17:02:47 +0000] "GET /update/check HTTP/2.0" 304 0 "https://code.fancywhale.ca/?folder=/Source/fancywhale/setup" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36" 70 0.008 [vscode-code-8080] [] 10.42.3.134:8080 0 0.005 304 516daab65c34704482cf77fe940df8b4
ingress-nginx/ingress-nginx-controller-2gk2w[controller]: 10.88.108.1 - - [23/Jun/2023:17:02:47 +0000] "GET /stable-695af097c7bd098fbf017ce3ac85e09bbc5dda06/static/out/vs/workbench/services/extensions/worker/webWorkerExtensionHostIframe.html?&vscodeWebWorkerExtHostId=7fc0e661-bfad-43a5-aa49-5c26aaa617be HTTP/2.0" 200 0 "https://code.fancywhale.ca/?folder=/Source/fancywhale/setup" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36" 0 0.004 [vscode-code-8080] [] 10.43.239.56:9000 0 0.005 200 6d75a7f6add859fcb166abd079f002c6
ingress-nginx/ingress-nginx-controller-2gk2w[controller]: 10.88.108.1 - - [23/Jun/2023:17:02:47 +0000] "GET /stable-695af097c7bd098fbf017ce3ac85e09bbc5dda06/static/out/vs/workbench/services/extensions/worker/webWorkerExtensionHostIframe.html?&vscodeWebWorkerExtHostId=7fc0e661-bfad-43a5-aa49-5c26aaa617be HTTP/2.0" 200 1646 "https://code.fancywhale.ca/?folder=/Source/fancywhale/setup" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36" 166 0.033 [vscode-code-8080] [] 10.42.3.134:8080 1663 0.029 200 6d75a7f6add859fcb166abd079f002c6
ingress-nginx/ingress-nginx-controller-2gk2w[controller]: 10.88.108.1 - - [23/Jun/2023:17:02:47 +0000] "GET /_static/src/browser/media/templates.png HTTP/2.0" 200 0 "https://code.fancywhale.ca/?folder=/Source/fancywhale/setup" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36" 0 0.005 [vscode-code-8080] [] 10.43.239.56:9000 0 0.005 200 a9895f4248390e67e1bf1f9c6349be32
ingress-nginx/ingress-nginx-controller-2gk2w[controller]: 10.88.108.1 - - [23/Jun/2023:17:02:47 +0000] "GET /_static/src/browser/media/templates.png HTTP/2.0" 304 0 "https://code.fancywhale.ca/?folder=/Source/fancywhale/setup" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36" 64 0.007 [vscode-code-8080] [] 10.42.3.134:8080 0 0.001 304 a9895f4248390e67e1bf1f9c6349be32
ingress-nginx/ingress-nginx-controller-2gk2w[controller]: 10.88.108.1 - - [23/Jun/2023:17:02:50 +0000] "GET /_static/out/browser/serviceWorker.js HTTP/2.0" 200 0 "https://code.fancywhale.ca/_static/out/browser/serviceWorker.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36" 0 0.005 [vscode-code-8080] [] 10.43.239.56:9000 0 0.005 200 d9388f7f1a3158cbd2b806229aebd9cf
ingress-nginx/ingress-nginx-controller-2gk2w[controller]: 10.88.108.1 - - [23/Jun/2023:17:02:50 +0000] "GET /_static/out/browser/serviceWorker.js HTTP/2.0" 304 0 "https://code.fancywhale.ca/_static/out/browser/serviceWorker.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36" 176 0.008 [vscode-code-8080] [] 10.42.3.134:8080 0 0.003 304 d9388f7f1a3158cbd2b806229aebd9cf
```

No more logs are introduced while running the kubectl exec commands, which leads me to believe there's nothing wrong with the websocket connection.

THis also doesn't seem like an issue on the execution attachment on the terminal of code-server as it works just fine while attaching to the local docker running container:
```bash
zsh ⌁ docker run -it ubuntu bash                                                   
root@a338ae892be2:/# echo test 
test
root@a338ae892be2:/# 
```

**Comment by code-asher** [comment]
Those stream/frame logs do not seem to be coming from code-server. 
An online search suggests that `DEBUG` might be set resulting 
kubectl printing network logs but I have not verified myself 
whether that is true.  Try `unset DEBUG` or prefixing the exec 
with `DEBUG= ` and seeing if that helps.

**Comment by gcarrarom** [comment]
You madman! Thanks very much! So sorry for opening up this ticket, honestly hadn't thought of it.
