### ISSUE TITLE
[Bug]: Ctrl +V not paste content from clipboard after Copy file path

### ISSUE THREAD

**Issue by 502647092** [coder/code-server#6286]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: EDGE
- Local OS: Windows
- Remote OS: Docker
- Remote Architecture:
- `code-server --version`: 4.14.0

### Steps to Reproduce

1. Select file in coder-server explorer 
2. Press `Ctrl + C`
3. Copy other content
4. Press `Ctrl + V` at editor area
5. can't paste other content but paste file path
6. using the right-click menu is correct

### Expected

correct paste content

### Actual

paste file path

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by 502647092** [comment]
@code-asher upstream fix this bug but I install latest coder-server still have problem

**Comment by code-asher** [comment]
The fix has not been released yet, as far as I can tell.

Once it is released we can update it in code-server, which generally happens within the week after VS Code releases a new version.

**Comment by nlvw** [comment]
This is still happening in code-server v4.16.1 (Code 1.80.2) even though it should have been fixed in the upstream 1.80.0.

<img width="382" alt="image" src="https://github.com/coder/code-server/assets/5723368/2937e766-c202-4940-9752-7b5b52b44190">

**Comment by nlvw** [comment]
@code-asher until this is resolved do you know of a code-server version we can downgrade to in the meantime?

**Comment by nlvw** [comment]
Not sure about codespaces as I only use code-server stand alone for use with container dev environments.  I'm using Chrome on windows but code-server on linux over an ssh tunnel.

The behavior consistent.  Copy + Paste a folder or file and the clipboard will always break afterwards when copying text from the terminal in code-server or text from somewhere else (another window or program).

**Comment by code-asher** [comment]
Ahh yup I can confirm copying from the terminal or externally 
breaks for me after copying a file path as well.  Copying from the 
editor or other file paths keeps working.

It reproduces in Codespaces for me so it appears to remain an 
upstream issue.

**Comment by giovp** [comment]
FWIW with `code-server-4.20.1-linux-amd64` refreshing the page on chrome fixes this issue
