### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by 10der** [coder/code-server#6294]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome
- Local OS: Linux core-ssh 6.1.34 #1 SMP PREEMPT Thu Jun 15 16:01:53 UTC 2023 aarch64 Linux 
- Remote OS: HAOS
- Remote Architecture: ARM64
- `code-server --version`:  5.8.0

### Steps to Reproduce

```
# Morning
- platform: tod
  name: Morning
  after: sunrise
  before: "12:00"
  unique_id: morning
```

### Expected

unique_id: morning # OK

RTFM
[https://www.home-assistant.io/integrations/tod/](url)

### Actual

![image](https://github.com/coder/code-server/assets/7056498/e4bf7234-5ea4-4452-ab1b-2397affebd42)

### Screenshot/Video

![image](https://github.com/coder/code-server/assets/7056498/e4bf7234-5ea4-4452-ab1b-2397affebd42)

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by code-asher** [comment]
I imagine this functionality is provided by an extension?  It 
seems more likely to be an issue with the extension than 
code-server.

You have verified it works in local VS Code and Codespaces though? 
If so could you provide reproduction steps?

**Comment by 10der** [comment]
yep. u right. Wrong projects!
sorry!
