### ISSUE TITLE
[Bug]: Installed extensions get deleted

### ISSUE THREAD

**Issue by elferherrera** [coder/code-server#6295]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: chrome
- Local OS: Mac
- Remote OS: Ubuntu
- Remote Architecture: 
- `code-server --version`: 4.14.1

### Steps to Reproduce

1. Install extension using `code-server --install-extension <name>`
2. Stop code server
3. Restart code server. The extension is gone with this message in the log: `Marked extension as uninstalled vscodevim.vim-1.25.2`

### Expected

Extensions to be kept

### Actual

Extension gets deleted

### Logs

2023-06-29 17:49:43.082 [info] Extension host agent started.
2023-06-29 17:49:43.371 [info] Marked extension as uninstalled vscodevim.vim-1.25.2
2023-06-29 17:49:44.262 [info] [127.0.0.1][f6f8fbc0][ManagementConnection] New connection established.

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by code-asher** [comment]
I have not been able to reproduce yet.  Here is what I did: 

```
$ rm ~/.local/share/code-server -rf # Fresh slate.
$ ./code-server-4.14.1-linux-amd64/bin/code-server --auth none
# Open another terminal.
$ ./code-server-4.14.1-linux-amd64/bin/code-server install-extension vscodevim.vim
# Back to the original teminal.
# C-c to kill code-server.
$ ./code-server-4.14.1-linux-amd64/bin/code-server --auth none
```

I also tried from the integrated terminal but this worked for me 
as well.

``` 
$ rm ~/.local/share/code-server -rf
$ ./code-server-4.14.1-linux-amd64/bin/code-server --auth none
# Open localhost:8080.
$ code-server --install-extension vscodevim.vim
# Back to original terminal.
# C-c to kill code-server.. 
$ ./code-server-4.14.1-linux-amd64/bin/code-server --auth none
```

I also tried a few things like installing from the UI then again 
from the command line then restarting but it all worked.

Are there any other details you can provide that might help me 
reproduce?  For example how you are running/restarting code-server 
(docker, systemd, etc), where you are running the install command 
(integrated terminal, external).  Does it happen to extensions 
other than vscodevim.vim?  Does the problem persist with a fresh 
user data directory?

One place where this might be going wrong is in the `.obsolete` 
file in the extensions directory.  When you uninstall an extension 
the ID gets placed into that file.  Maybe it is not being removed 
for some reason and gets eternally marked as uninstalled.

**Comment by elferherrera** [comment]
I found the issue. The `extensions.json` file was being overwritten by another process before startup and that was marking some extensions as deleted

**Comment by sevetseh28** [comment]
> I found the issue. The `extensions.json` file was being overwritten by another process before startup and that was marking some extensions as deleted

hey @elferherrera  do you remember which process that was? Im having the same issue using Docker layers. Im using a base image that has already a few extensions but installing more in subsequent layers override the extensions.json file and removes the base ones.
