### ISSUE TITLE
[Bug]: Code server is running, but I can't visit

### ISSUE THREAD

**Issue by sciencekiller** [coder/code-server#6304]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: edge
- Local OS: Windows
- Remote OS: Ubuntu 
- `code-server --version`: 4.14.1

### Steps to Reproduce

Code server is running on my server(192.168.2.103), Program output says"HTTP server listening on http://127.0.0.1:8080", but when I visit 192.168.2.103:8080, I can only find a page says"192.168.2.103 Connection refused“，I already remove the firewall but it doesn't work,what should I do?

### Expected

I want to visit code server

### Actual

I can't visit it

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by code-asher** [comment]
@sciencekiller I will close the issue for now since there does not appear to be a bug but if you are still having trouble feel free to comment.
