### ISSUE TITLE
[Bug]: Codicon font does not load behind apache rev proxy.

### ISSUE THREAD

**Issue by SeeJayEmm** [coder/code-server#6305]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Firefox 114.0.2
- Local OS: Windows 10
- Remote OS: Ubuntu 22.04.2 LTS
- Remote Architecture: amd64
- `code-server --version`: 4.14.1 5c199629305a0b935b4388b7db549f77eae82b5a with Code 1.79.2

### Steps to Reproduce

1. Access code-server from behind an Apache reverse proxy.

### Expected

Codicon font should load allowing for display of the UI elements dependent on it.

### Actual

Font fails to load. UI icons are replaced with hex squares.

The font loads properly when accessed directly (bypass proxy) using the same browser.

### Logs

Browser console log (fqdn has been obfuscated).

downloadable font: bad table directory searchRange (font-family: "codicon" style:normal weight:400 stretch:100 src index:0) source: https://vscode.domain.tld/stable-695af097c7bd098fbf017ce3ac85e09bbc5dda06/static/out/vs/base/browser/ui/codicons/codicon/codicon.ttf?5d4d76ab2ce5108968ad644d591a16a6

downloadable font: bad table directory entrySelector (font-family: "codicon" style:normal weight:400 stretch:100 src index:0) source: https://vscode.domain.tld/stable-695af097c7bd098fbf017ce3ac85e09bbc5dda06/static/out/vs/base/browser/ui/codicons/codicon/codicon.ttf?5d4d76ab2ce5108968ad644d591a16a6

downloadable font: bad table directory rangeShift (font-family: "codicon" style:normal weight:400 stretch:100 src index:0) source: https://vscode.domain.tld/stable-695af097c7bd098fbf017ce3ac85e09bbc5dda06/static/out/vs/base/browser/ui/codicons/codicon/codicon.ttf?5d4d76ab2ce5108968ad644d591a16a6

downloadable font: 0GSU: invalid table offset (font-family: "codicon" style:normal weight:400 stretch:100 src index:0) source: https://vscode.domain.tld/stable-695af097c7bd098fbf017ce3ac85e09bbc5dda06/static/out/vs/base/browser/ui/codicons/codicon/codicon.ttf?5d4d76ab2ce5108968ad644d591a16a6

downloadable font: rejected by sanitizer (font-family: "codicon" style:normal weight:400 stretch:100 src index:0) source: https://vscode.domain.tld/stable-695af097c7bd098fbf017ce3ac85e09bbc5dda06/static/out/vs/base/browser/ui/codicons/codicon/codicon.ttf?5d4d76ab2ce5108968ad644d591a16a6

### Screenshot/Video

![image](https://github.com/coder/code-server/assets/788552/3c85ea04-e760-45a9-87a8-a89d855e9e2f)

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

So far all other tested functionality behind the Apache proxy is working except for this one display issue. I've hit a wall trying to figure out why the font is failing to load.

Relevant portions of my apache config:

        # Configure rev proxy.
        ProxyRequests           Off
        ProxyPass               /       https://vscode.intdomain.tld/ upgrade=websocket
        ProxyPassReverse        /       https://vscode.intdomain.tld/
        ProxyPassReverseCookieDomain    vscode.intdomain.tld      vscode.domain.tld

        ProxyPreserveHost       On
        ProxyHTMLEnable         On
        ProxyHTMLMeta           On
        ProxyHTMLExtended       On
        RequestHeader           unset   Accept-Encoding
        ProxyHTMLURLMap         https://vscode.intdomain.tld/ /

**Comment by SeeJayEmm** [comment]
To further the troubleshooting I tried putting it behind an NGINX proxy instead of apache. Same problem.

I then did the thing I should have done before submitting the report. I tried it in another browser. I opened the proxied page in Edge and it loaded the codicons just fine.

**Comment by code-asher** [comment]
I attempted to reproduce with NGINX (using the config we have in 
our docs) but the icons work for me.
 
What is going on with the two domains?  Maybe there is some 
weirdness caused by a cross-origin request from 
`https://vscode.intdomain.tld` to `https://vscode.domain.tld`?

Maybe something with the cookie?  If you look at the font 
requests in the network tab are they resolving with 401s?

Although it is strange it works in Edge if that was the case. 
Maybe Firefox has stricter cross-origin policies?

**Comment by SeeJayEmm** [comment]
I'm not clear what has changed between my initial report and today but it's working now. The icons are loading and there's no errors in the console.   The only change I'm aware of is I replaced the cert on the proxy with a wildcard.

I appreciate you taking a look and I'm sorry if I wasted your time.

**Comment by code-asher** [comment]
No worries!  I am just glad it is working.
