### ISSUE TITLE
[Bug]: Code jump (ctrl+click) slowly or not working in python project

### ISSUE THREAD

**Issue by wqhcug** [coder/code-server#6315]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: google 88.0.4324.104
- Local OS: WIN10
- Remote OS: Ubuntu 16.04
- Remote Architecture:  X86
- `code-server --version`:  
code-server: v4.8.3
Code: 1.72.1
-python：3.9

### Steps to Reproduce

1. Use ctrl+click jump to source code slowly in python project
2. Use ctrl+click slowly to source code not working in python project

### Expected

Use ctrl+click jump to source code immediately

### Actual

1. Use ctrl+click jump to source code slowly in python project
2. Use ctrl+click slowly to source code not working in python project

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by code-asher** [comment]
Does this reproduce in the latest version of code-server 
(v4.14.1)?

I launched v4.14.1, installed the Python extension, and opened a 
Python project (Django) but Ctrl+click works normally for me.  I 
am not seeing any slowness either.

**Comment by gcarrarom** [comment]
Odd, I'm also seeing the same issue as the OP. 
here's my setup:
python 3.11.4 
code-server 1.79.2
python extension v2023.12.0

For now I can tell that highlight, ctrl+click and intellisense are not working. I have the same project and versions on a local environment, working just fine on vscode 1.80.1.

I've tried downgrading the python extension to 2023.10.1, 2023.10.0 and 2023.8.0, but I have the same issues.

I've also tried creating a new project using poetry and setting up pyenv with virtual environment. Same issue when selecting the python interpreter from the environment.

I've tried setting  "python.autoComplete.extraPaths" to the site-packages of the virtual environment and reloading the code-server. Same issue.

**Comment by gcarrarom** [comment]
I Can reproduce this issue by doing the following:

1. create a new container using `docker run -p 8080:8080 codercom/code-server:4.14.1-ubuntu`
2. connecting via browser using the default generated password.
3. installing the python extension: `ms-python` v2023.12.0
4. installing python: 
  4.1. `sudo apt update` 
  4.2. `sudo apt install python3`
  4.3. `sudo apt install python3-pip`
5. install a python package. i.e.: `pip install click`
6. In the python file created, and the new python installed, try to import the installed package: `import click`
7. Try to use intellisense: 

![CleanShot 2023-07-20 at 10 38 25](https://github.com/coder/code-server/assets/10549675/0584d96b-b218-47a1-850b-757d98f89b4e)


The interesting part is that the module gets identified: 
![CleanShot 2023-07-20 at 10 39 12](https://github.com/coder/code-server/assets/10549675/6015119c-a370-4025-8082-d7fc31edb282)

Just doesn't do anything after:

![CleanShot 2023-07-20 at 10 39 28](https://github.com/coder/code-server/assets/10549675/db35ae8f-0475-4141-ab0d-457244a6525b)

Everything else works just fine: (aoo.py) - yes, that's a typo :)
```python
import click

@click.command()
def something():
    click.echo("something")

if __name__ == '__main__':
    something()
```

Can be used just fine:
```bash
coder@e27da99b72c6:~$ python3 ./aoo.py 
something
coder@e27da99b72c6:~$ 
```

**Comment by Gu-f** [comment]
Does the problem still exist?
I had the same problem, python Built-in modules and self-written modules work properly and can jump. However, third-party modules do not take effect.  
venv interpreter is in my working directory.  
I carried out the extraPaths configuration, but still couldn't auto complete and jump the third-party module normally: 
```
"python.autoComplete.extraPaths": [
        "/root/test-projcet/venv3/venv3/lib/python3.11/site-packages",
    ]
```  
Am I missing something?

**Comment by gcarrarom** [comment]
Still happening. I'll update to the new version and try again to see how it goes and report back.

**Comment by gcarrarom** [comment]
Nope, still happening on 4.15.0 (code 1.80.1). Built-in works just fine, it's just the 3rd party modules as you've stated, @Gu-f.

**Comment by code-asher** [comment]
Thank you for the reproduction @gcarrarom.  I followed the steps 
(well except I added `--auth none` so I skipped the second step).

I ran it a number of times with the steps in different order and 
sometimes it seems to break and sometimes it works but nothing 
seems to consistently reproduce it for me.  Reloading the page so 
far always fixes mine though.  Is it the same for you?

**Comment by gcarrarom** [comment]
Hey, thanks for testing it out! 

Just tried here and it won't work.  I've tried the following on Chrome, Edge and Firefox:
1. Opening up a code window
2. Installed python click
3. wrote some code
4. ran just fine - checked the interpreter version, same as the runtime on the terminal
5. reloaded multiple times - never worked.

Here are the versions of the browsers:
Edge: Version 115.0.1901.188 (Official build) (arm64)
Chrome: Version 115.0.5790.114 (Official Build) (arm64)
Firefox: Version 115.0.2 (64-bit)
Safari: Version 17.0 (19616.1.24.11.3)

Makes me wonder what could be happening. Doesn't seem to be browser related.
Although... That's my environment, let's try the one I sent you for reproducing the issue...

**Comment by gcarrarom** [comment]
Looking at the logs now, here's the one running that simple base image with only that python click file:
```bash
```

**Comment by code-asher** [comment]
I am not familiar enough with the internals to say offhand for sure whether that is related.  Nothing else stands out to me either.  Maybe there are more logs in the browser console though.

Something you might try is to load your code in local/native VS Code, VS Code remote (if you have SSH access), and in the simple base image to see if it reproduces in any of those settings to possibly rule out code-server and/or the environment.  Best case is if it reproduces in VS Code or with the remote extension because then we can raise it upstream to get more knowledgeable help.

If the code and/or environment is something you can share I will try it out to see if it reproduces for me.

**Comment by code-asher** [comment]
Closing as stale and probably an upstream issue but feel free to comment if you come back to this.
