### ISSUE TITLE
[Bug]: Error loading renderer ‘vscode.builtin-renderer’ and invalid regular expression (invalid group specifier name)

### ISSUE THREAD

**Issue by ulzee** [coder/code-server#6317]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: iOS Safari
- Local OS: iPad OS 16.3.1
- Remote OS: Ubuntu
- Remote Architecture: Ubuntu 20.04.5 LTS
- `code-server --version`: .14.1 5c199629305a0b935b4388b7db549f77eae82b5a with Code 1.79.2

### Steps to Reproduce

1. access the code server from an ipad (or possibly other iOS devices)
2. install the jupyter extension (latest atm is v2023.3.100)
3.  execute a cell in either a notebook or a cell block in a python script
4. If the cell is supposed to return a value or a printout, the error is shown instead of the result of the code execution

### Expected

The return value corresponding to the cell should be formatted and printed out

### Actual

I see the following printout:

“

Error loading renderer ‘vscode.builtin-renderer’

- Invalid regular expression: invalid group specifier name

“

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [ ] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

I encounter this with any browser I try on iPad OS. My guess is that all ios browsers use WebKit and webkit has a known issue of not supporting some regex ([eg.](https://stackoverflow.com/questions/51568821/works-in-chrome-but-breaks-in-safari-invalid-regular-expression-invalid-group)). I am not knowledgeable enough of vscode to narrow down the issue to vscode, the server, jupyter extension, or something specific to my setup.

I was wondering if anyone else is messing around with this type of setup has encountered this and is aware of a workaround? Would be great if I can see the result of executing cells. This is not an issue on something like Chrome desktop, the cells work fine there.

**Comment by code-asher** [comment]
Does this really not reproduce in Codespaces?  Seems like it would 
be an issue that affects upstream.

They have fixed this bug in the past for the Markdown extension so 
I think they would be happy to fix this one as well.

**Comment by ulzee** [comment]
Unfortunately when I try ipynbs or executable cells on some codespaces from the iPad either nothing happens or no cells load in the ipynb file (I'm also new to codespaces so maybe it can). So I can't verify whether it replicates there or not although I would also agree it probably doesn't.

![IMG_44C373EE2CC0-1](https://github.com/coder/code-server/assets/1483305/32831f65-b175-42b1-bbc2-0105b8ed91d4)

I also do recall seeing a similar regex issue with markdown [issue 141689](https://github.com/microsoft/vscode/issues/141689#issue-1116908565) . Does this mean this is an issue for the vscode repo and not related to code-server? Perhaps the invalid regex is somewhere here https://github.com/microsoft/vscode/tree/main/extensions/ipynb

**Comment by code-asher** [comment]
Yup, I think you are right.  The same fix needs to be applied there.

**Comment by Chaddai** [comment]
I have the same problem, for Python **and** for Markdown cells, I can edit them but I can't run them or render them (I'm similarly behind https, on an Azure VM). The errors are : 

For Python

> Error loading renderer 'vscode.builtin-renderer'
>
>   error loading dynamically imported module: https://vscode-remote+shell-002eclosmaire-002dinfo-002efr.vscode-resource.vscode-cdn.net/usr/lib/code-server/lib/vscode/extensions/notebook-renderers/renderer-out/index.js

and For Markdown

> Error loading renderer 'vscode.markdown-it-renderer'
> 
>    error loading dynamically imported module: https://vscode-remote+shell-002eclosmaire-002dinfo-002efr.vscode-resource.vscode-cdn.net/usr/lib/code-server/lib/vscode/extensions/markdown-language-features/notebook-out/index.js

Code-server version : 4.22.1 760d1318e98945d05133c6121f99541ca7a39bf8 with Code 1.87.2

**Comment by eddietaylor** [comment]
Is anyone ever going to fix this bug? This is the one big exception to claiming vs code is the best IDE, when my plots intermittently won't work because of this renderer.

**Comment by code-asher** [comment]
It seems like it needs to be fixed upstream, so someone who is able to reproduce the error will need to submit a PR against https://github.com/microsoft/vscode.  Recommend commenting/upvoting here: https://github.com/microsoft/vscode/issues/197473
