### ISSUE TITLE
Found incompatible module

### ISSUE THREAD

**Issue by Stu75e** [coder/code-server#6339]
Hi I'm using termux for installing app 
 But i have problem in install coder

yarn global add code-server
yarn global v1.22.19
warning package.json: No license field
[1/4] Resolving packages...
info There appears to be trouble with your network connection. Retrying...
warning code-server > proxy-agent > pac-proxy-agent > pac-resolver > degenerator > vm2@3.9.19: The library contains critical security issues and should not be used for production! The maintenance of the project has been discontinued. Consider migrating your code to isolated-vm.
[2/4] Fetching packages...
error code-server@4.14.1: The engine "node" is incompatible with this module. Expected version "16". Got "20.2.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.

I'm checking node version and yarn docs i thinking its a bug

node --version
v20.2.0

**Comment by code-asher** [comment]
code-server only supports Node 16.

But, you can run with Node 20 at your own risk with:

FORCE_NODE_VERSION=20 yarn global add code-server --ignore-engines

**Comment by Stu75e** [comment]
Node lts in ternode lts is in termux version 18, it is not possible to install coder on it

**Comment by code-asher** [comment]
Yeah it is unfortunate but we cannot update to Node 18 until VS 
Code updates (https://github.com/coder/code-server/issues/6230).

What about the code-server Termux package?  Does that work?

```
pkg install tur-repo
pkg install code-server
```

https://github.com/coder/code-server/blob/main/docs/termux.md#install

**Comment by code-asher** [comment]
Oh yeah good point.  There is also https://www.npmjs.com/package/n 
which I prefer since you do not have to source anything.
