### ISSUE TITLE
[Bug]: Figma extension does not work

### ISSUE THREAD

**Issue by somebody1234** [coder/code-server#6352]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome
- Local OS: Arch Linux
- Remote OS: Arch Linux
- Remote Architecture: amd64
- `code-server --version`: 4.15.0

### Steps to Reproduce

1. Instal Figma extension: https://marketplace.visualstudio.com/items?itemName=figma.figma-vscode-extension
2. Log in to Figma
3. Open a design

### Expected

Works

### Actual

Errors with "www.figma.com refused to connect":
> Refused to frame 'https://www.figma.com/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self' vscode-webview: vscode-file:".

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [ ] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by code-asher** [comment]
I am not able to test on code-server since using VS Code 
marketplace assets in code-server is against their terms of 
service but I experimented with it in Codespaces.

How are you logging in?  The login flow only seems to support 
desktop VS Code.

**Comment by somebody1234** [comment]
@code-asher i'm manually copy+pasting the url and using the "open url" link in the command palette

**Comment by code-asher** [comment]
> i'm manually copy+pasting the url and using the "open url" link 
> in the command palette

Ahh that is clever!

Sorry for the delayed response, my Codespaces instance ran out of 
disk space or something and I forgot to revisit this after it 
reset.

I got logged in and confirmed the issue exists on Codespaces, so 
this looks like an upstream issue.  You marked that it works for 
you on Codespaces though, could you confirm before I mark it as 
upstream?  Thank you!

**Comment by somebody1234** [comment]
@code-asher ah, my bad. yeah, tested on codespaces and it indeed doesn't work

**Comment by code-asher** [comment]
Awesome, thank you for confirming!
