### ISSUE TITLE
[Bug]: When using the command "code-server --install-extension", a failed installation returns exit code 0

### ISSUE THREAD

**Issue by SantiSuarezMS** [coder/code-server#6367]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Local OS: macOS
- Remote OS: Ubuntu
- Remote Architecture: amd64
- `code-server --version`: 4.11.0

### Steps to Reproduce

1. On the Terminal run `code-server --install-extension non.existing-extension && echo "Exit code: " "$?"`
2. Wait for the command to finish and check the output.

### Expected

At the end of the output it should read:
```
Exit code:  1
```
Or any other non 0 appropriate exit code.

### Actual

At the end of the output it reads:
```
Exit code:  1
```

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

As part of a pipeline, I have a script that install some extensions using `code-server --install-extension`, whenever one of the installed extensions fails I expect the whole script to fail, cascading to the pipeline fail so I can take action.
Instead, as it is returning 0 even when the task is failing, the build finishes with a false success.

**Comment by turbotimon** [comment]
@SantiSuarezMS don't you mean: *"**Actual**: At the end of the output it reads: `Exit code 0`"* instead of 1 ?

I consider this a bug as well, or at least bad UX, as one can not use this command in a script and react to failing. Any comments from a contributor/developer on this?

**Comment by benz0li** [comment]
I can reproduce this in GitHub Codespaces.

**Comment by turbotimon** [comment]
not exactly sure what you mean by "vscode (remot-cli)" but [ms vscode](https://github.com/microsoft/vscodecode) (v1.84.2) behaves correctly: `code --install-extension non.existing-extension` will return `1`. [vscodium](https://vscodium.com/) as well behaves correctly.

**Comment by code-asher** [comment]
Yeah in the terminal we just use the script that comes bundled with VS Code (the server/web CLI is different than the native one) so it sounds like an upstream bug.

**Comment by code-asher** [comment]
We can fix the one on our end though, the one that runs outside the terminal.  Will push that fix in a bit.

**Comment by turbotimon** [comment]
Can we please an issue on the upstream repo then? I would like to do so, but as i'm not familiar with the server/web CLI version, i'm not sure where to place and how to describe it correctly..

**Comment by code-asher** [comment]
Sorry for letting this fall through the cracks.  If someone wants to submit this upstream, I think it should be sufficient to reproduce in Codespaces (I believe the command there will be `code` though and not `code-server`) and use that information to open the issue.

**Comment by michaelbrewer** [comment]
note this does work as expected in the microsoft code-server version

**Comment by code-asher** [comment]
I tested after updating to 1.88.0 but unfortunately the problem persists.   Not sure why Microsoft's works.  :thinking:   Does it work within the integrated terminal as well, or only outside?  Codespace's is still broken too.

**Comment by code-asher** [comment]
Ah nevermind I tested, it does not work in the integrated terminal with Microsoft's either.

**Comment by code-asher** [comment]
Wait, I see why.  I can fix the exit code from the external script, but the one from the integrated terminal is still an upstream bug.

**Comment by code-asher** [comment]
I will go ahead and close this as an upstream bug.
