### ISSUE TITLE
[Bug]: Remote connection between code-server and JupyterHub drops intermittently

### ISSUE THREAD

**Issue by BouarfaMahi** [coder/code-server#6378]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

I've been experiencing an issue where the remote connection between code-server and JupyterHub stops after a varying number of hours. The disconnection is inconsistent and does not happen after a specific time, making it hard to pinpoint the exact cause.

code-server version: 4.16.1
JupyterHub version: 3.0.0
Operating System: Ubuntu 22.04
Browser : Brave 1.56.20

### Steps to Reproduce

1- Setup code-server and connect it with JupyterHub/token.
2- Work on the environment for a few hours.
3- Observe the intermittent loss of connection between the two platforms.

### Expected

The connection between code-server and JupyterHub should remain stable and not disconnect on its own without any user intervention or specific trigger.

### Actual

The remote connection drops randomly after an uncertain number of hours.

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by benz0li** [comment]
@BouarfaMahi Maybe an alternative to your setup: [JupyterLab](https://github.com/b-data/jupyterlab-julia-docker-stack) [docker](https://github.com/b-data/jupyterlab-python-docker-stack) [stacks](https://github.com/b-data/jupyterlab-r-docker-stack) including code-server.  
ℹ️ (GPU accelerated) Multi-arch (`linux/amd64`, `linux/arm64/v8`) docker images.

Demo environment: https://demo.jupyter.b-data.ch; login with GitHub account.  
ℹ️ No GPU, 2 cores, 8 GB RAM

**Comment by BouarfaMahi** [comment]
@benz0li Thank you for sharing this setup but it is not applicable to the [AI agent Farm](https://github.com/quantiota/AI-Agent-Farm)

**Comment by benz0li** [comment]
@BouarfaMahi OK. IMHO This is rather an issue with the [Jupyter extension](https://open-vsx.org/extension/ms-toolsai/jupyter) than code-server.

Cross reference: https://github.com/microsoft/vscode-jupyter/issues/13759

**Comment by BouarfaMahi** [comment]
@benz0li no this is not the same issue

**Comment by code-asher** [comment]
Do the drops coincide with reconnections to the extension host as 
well?  If so you should see messages like this in the browser 
console: 

  [ExtensionHostConnection] New connection established.

If you do see those, the problem could be from your browser to 
code-server rather than code-server to Jupyter.

**Comment by benz0li** [comment]
Cross reference: https://github.com/microsoft/vscode-jupyter/issues/14085

**Comment by BouarfaMahi** [comment]
> Do the drops coincide with reconnections to the extension host as well? If so you should see messages like this in the browser console: [ExtensionHostConnection] New connection established. If you do see those, the problem could be from your browser to code-server rather than code-server to Jupyter.

@code-asher  Thanks, i will check

**Comment by BouarfaMahi** [comment]
**Update**: After further investigation, I've found that switching my browser from Brave to Chrome seems to resolve the intermittent connection drop between code-server and JupyterHub. I have been running smoothly without any interruptions for over 24 hours since making the switch.

Thank you for your assistance
