### ISSUE TITLE
i keep getting 'incorect password when im loging into my code sever using my andriod phone.[Bug]: 

### ISSUE THREAD

**Issue by Arowz** [coder/code-server#6389]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: chrome
- Local OS: andriod
- Remote OS: ubuntu-in-termux
- Remote Architecture:
- `code-server --version`: code-server-4.16.1

### Steps to Reproduce

1. cd code server-4.16.1
2.cd bin
3.run code server
``

### Expected

opening of code server and type pasword

### Actual

incorrect password when wherever i enter password

https://github.com/coder/code-server/assets/128797724/7bbe5e90-48d9-4cf8-9a28-bb74d633b05a

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by code-asher** [comment]
Are you maybe running code-server as a different user than you 
expect?  For example if you are running it as root then ~/.config 
would be /root/.config.

**Comment by code-asher** [comment]
Let me know if you still are running into this.  The latest release will print the full path of the config file so if this was the problem it should be easier to diagnose.

**Comment by Arowz** [comment]
It's solved

**Comment by Arowz** [comment]
> Let me know if you still are running into this. The latest release will print the full path of the config file so if this was the problem it should be easier to diagnose.

I want to close this issue

**Comment by code-asher** [comment]
Perfect, thank you!
