### ISSUE TITLE
[Bug]: Folder Download Option not appearing in safari browser

### ISSUE THREAD

**Issue by puneethrai** [coder/code-server#6393]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Safari 16.5.1
- Local OS: Mac Ventura
- Remote OS: Linux 4.18.0-305.93.1.el8_4.x86_64
- Remote Architecture: x86 64 Bit
- `code-server --version`:
- 1.80.1
74f6148eb9ea00507ec113ec51c489d6ffb4b771
x64

Not able to Folder Download option in Safari Browser but is visible in Chrome browser even though I'm in same Mac OS

### Steps to Reproduce

1. Run the server and open in safari browser
2. Create a folder in viscose
3. right click on the folder 
4.No download option in Safari browser

### Expected

Download option should be appearing for folder in Safari browser

### Actual

No download option appearing in the Safari browser but on same OS with Chrome browser it is appearing

### Screenshot/Video

In Safari
<img width="339" alt="image" src="https://github.com/coder/code-server/assets/1643479/cfe6c45a-5079-4fa6-893a-1790753604a2">

In Chrome 
<img width="334" alt="image" src="https://github.com/coder/code-server/assets/1643479/079b1ebd-3b88-4a83-a629-5750f27c6b41">

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

Similar behaviour is observed In Github Codespaces and since there is no download option in VS Code can't test it.

**Comment by code-asher** [comment]
I believe downloads are disabled if the browser does not have file 
system API support so my guess is that Safari does not support the 
required APIs.

I will mark it as upstream since it reproduces in Codespaces.

**Comment by HumboldtC** [comment]
same situation in edge and firefox on Windows (code-server:1.93.1 x86)
