### ISSUE TITLE
[Bug]: global search and search by filename does not work in code-server installed from conda-forge 

### ISSUE THREAD

**Issue by zegnog** [coder/code-server#6394]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: chrome
- Local OS: windows
- Remote OS: linux
- Remote Architecture: amd64
- `code-server --version`: 4.16.1

### Steps to Reproduce

1. In a fresh conda environment, conda install -c conda-forge code-server
2. open code-server
3. open a folder with some text files
4. try to search by filename using ctrl+P, or global search using ctrl+shift+F

### Expected

Search works like in vscode or standalone code-server

### Actual

for search by filename, only previously opened files are available.
for global search, only opened files are searched through.

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

I am using conda forge to update and maintain my code-server up to the date. But I found global search and search by filename functions does not work in the version installed using conda-forge, it does work in standalone version though. 
I am not using https, but it works locally so browser does not complain.

**Comment by code-asher** [comment]
Ah I did not see this until I already commented on the other issue.  I wrote there:

From what I recall this can happen if ripgrep is missing.  I would
check the logs and see if the binary exists.  I think it should be
lib/vscode/node_modules/@vscode/ripgrep/bin/rg

**Comment by zegnog** [comment]
Thanks for the reply. I checked the path and the executable is here intact:
![image](https://github.com/coder/code-server/assets/75398383/527fdc3f-fed5-4694-8751-d2ca7dac68f3)

And I used `code-server -vvv` to produce the log as below:
[temp.txt](https://github.com/coder/code-server/files/12481923/temp.txt)

A brief check does not give me any more info about why the search break. Except there are still other ways to get more logs?

**Comment by zegnog** [comment]
Ugh, my bad, this issue is a duplicated with https://github.com/coder/code-server/issues/5322 and https://github.com/conda-forge/code-server-feedstock/issues/74 . I did not immediately connect those two together until you mentioned `rg`. The version released by conda forge now works normally after I manually replaced the installed `rg` with the on provided in standalone version.

Here close this issue in favor of https://github.com/coder/code-server/issues/5322 .
