### ISSUE TITLE
[Bug]: Cannot retrieve values stored using extension context SecretStorage 

### ISSUE THREAD

**Issue by pablocabrera85** [coder/code-server#6395]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome
- Local OS: macOS
- Remote OS: Ubuntu
- Remote Architecture: amd64
- `code-server --version`: 4.16.1

### Steps to Reproduce

1. Install the attached extension (rename .zip to .vsix)
2. Execute the hello world command. This will prompt for a value that will be stored using the `context.secrets` instance for this extension. Input any value and proceed. 
3. Reload the browser tab
4. Execute the hello world command again so that this time, we read the value and display it.
5. Instead of showing the value, you will be prompted again for a value to store.
[secrets-0.0.1.zip](https://github.com/coder/code-server/files/12429491/secrets-0.0.1.zip)

NOTE: If you prefer, you can just create an extension with the following code:
````
// The module 'vscode' contains the VS Code extensibility API
// Import the module and reference it with the alias vscode in your code below
import * as vscode from 'vscode';

// this method is called when your extension is activated
// your extension is activated the very first time the command is executed
export function activate(context: vscode.ExtensionContext) {
	
	// Use the console to output diagnostic information (console.log) and errors (console.error)
	// This line of code will only be executed once when your extension is activated
	console.log('Congratulations, your extension "secrets" is now active!');

	// The command has been defined in the package.json file
	// Now provide the implementation of the command with registerCommand
	// The commandId parameter must match the command field in package.json
	let disposable = vscode.commands.registerCommand('secrets.helloWorld', async () => {
		// The code you place here will be executed every time your command is executed
		// Display a message box to the user
			const value= await context.secrets.get('secrets.pass');
		if(value){
			vscode.window.showInformationMessage(`Retrieved ${value}`);
		}else{
			const value=await vscode.window.showInputBox({ title: 'Input secret value'});
			if(value){
				context.secrets.store('secrets.pass',value);
			}
		}
	});
	context.subscriptions.push(disposable);
}

// this method is called when your extension is deactivated
export function deactivate() {}
````

### Expected

After the reload and executing the command a second time, the persisted value should be displayed.

According to the API, the secrets should be automatically persisted. But every time the browser tab reloads, the value is not there
````
		/**
		 * A storage utility for secrets. Secrets are persisted across reloads and are independent of the
		 * current opened {@link workspace.workspaceFolders workspace}.
		 */
		readonly secrets: SecretStorage;
````

### Actual

Values are not stored between sessions/reloads

I tried the same extension in codespaces and it worked as expected

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by pablocabrera85** [comment]
Code server 4.11 does not have this issue

**Comment by code-asher** [comment]
Are you running code-server with dbus?  I think in previous 
versions it would store secrets in the browser but it switched to 
storing them server-side and the current implementation uses dbus.

Without dbus it uses an in-memory store so I wonder if a new store 
gets created every time the extension host is started (which 
happens on each page load).

Related: https://github.com/coder/code-server/issues/5072

**Comment by benz0li** [comment]
Use environment variables to provide credentials. See https://github.com/coder/code-server/issues/5072#issuecomment-1703762507 for more information.

**Comment by pablocabrera85** [comment]
@code-asher @benz0li Thanks for your replies, but the problems we are facing are not related to the github extension. We have other extensions that use the secret storage API.

We have tried also running code-server in a [plain ubuntu image](https://releases.ubuntu.com/20.04.6/ubuntu-20.04.6-desktop-amd64.iso) (not in a container), and we have the same problem with the code snippet provided.

From the dbus session logs, we can see that code-server is trying to retrieve the values from it, but we never see any event when trying to store the value.

We are using the default configuration when running code-server. Do we need to do anything in particular for the secret storage API to work?

Thanks in advance.

**Comment by code-asher** [comment]
There is nothing particular you need to do as far as I am aware. 
I think there is a bug although the mystery is why it only 
presents in code-server and not Codespaces.  We will need to dive 
into it and see what we can find.

**Comment by speriasamy0** [comment]
Facing the same issue. After upgrading to 4.16.1, page refresh is resetting the application session. I spent some time comparing codespace and my container. I didn't notice keyring or dbus configured/running in my codespace instance. Also codespace version is different from what comes with 4.16.1 which I am using.

**Comment by speriasamy0** [comment]
Attaching an archive that has a Dockerfile that bundles the example extension provided by @pablocabrera85. This has dbus and keyring configured. 

docker build . -t secrets_test:latest
docker run --rm -d --name secrets-test-container --privileged -p8080:8080 secrets_test:latest

To rule out any setup issues I've added a python program. You can invoke it by launching a terminal within the browser and type python /main.py. To invoke from outside the browser, you have to ensure you're in a dbus session and the keyring unlocked.

export $(dbus-launch) 
echo | gnome-keyring-daemon --unlock # unlock the system's keyring
python /main.py

[code-server-secrets.zip](https://github.com/coder/code-server/files/12622987/code-server-secrets.zip)

**Comment by code-asher** [comment]
Thank you for the detailed information!  The fact that it works in 
Codespaces yet dbus is not running is curious indeed.  I wonder if 
they replace keytar in Codespaces or something like that, and 
whether that is something part of the OSS or something bespoke 
they do as part of their build process.  Maybe we can just swap 
out the keytar module for something else.

**Comment by matias-mule** [comment]
Same issue here.
Is there any ETA for a fixed / workaround?

**Comment by code-asher** [comment]
I am not sure it is worth debugging this because keytar has been 
removed upstream, so I think the next release will have some new 
system.  I will definitely revisit at that point.
