### ISSUE TITLE
[Bug]: python error hint no show

### ISSUE THREAD

**Issue by JJplane** [coder/code-server#6398]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser:chrome
- Local OS:max
- Remote OS:linux
- Remote Architecture:amd64
- `code-server --version`:4.16.1

### Steps to Reproduce

1. install python extension

### Expected

![image](https://github.com/coder/code-server/assets/28783826/2697b5c4-ffbc-4a82-9c32-022bfc0083a3)

### Actual

![image](https://github.com/coder/code-server/assets/28783826/b4a254a5-a800-43bc-ba5c-4771a80e71b0)
no hint show

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by frevo** [comment]
just fyi, with all others on the edge, try install another version of pylance extension, '2023.6.40' works for me.

**Comment by benz0li** [comment]
Cross reference: https://github.com/coder/code-server/issues/6323#issuecomment-1632866136 ff

**Comment by benz0li** [comment]
@JJplane The situation regarding Pylance is not going to change.

Please close this issue.
