### ISSUE TITLE
[Bug]: Unable to open 'ipynb' in docker，I have tried my best.

### ISSUE THREAD

**Issue by ZhengHui-Z** [coder/code-server#6418]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome
- Local OS: macOS
- Remote OS: Ubuntu，Internal IP address：192.168.36.12
- Remote Architecture: amd64
- code-server --version: code-server 4.16.1 94ef3776ad7bebfb5780dfc9632e04d20d5c9a6c

### Steps to Reproduce

1. docker-compose.yml

```
version: "3"

services:
  code-server:
    container_name: code-server
    image: codercom/code-server
    ports:
      - "8080:8080"
    volumes:
      - ./project:/home/coder/project:rw
      - ./config:/home/coder/.config:rw
    environment:
      PASSWORD: 123456789
    restart: always

```
2. config.yaml
```
bind-addr: 127.0.0.1:8080
auth: password
password: cd620d9c7a15c814b845bf21
cert: /home/coder/.config/server.crt
cert-key: /home/coder/.config/server.key
```

3. generate a certificate：
```
Step1: 
$ mkcert 192.168.36.21 127.0.0.1 -
Step2: 
$ mkcert -cert-file code-server.crt -key-file code-server.key 192.168.36.21 127.0.0.1
```

### Expected

It can run Jupyter normally.

### Actual

<img width="798" alt="image" src="https://github.com/coder/code-server/assets/13689856/f662f795-a43a-4e96-a9c4-cec65388f1dc">

### Logs

``` shell
$ docker compose up
[+] Running 1/0
 ✔ Container code-server  Created                                                                                                                                                                  0.0s 
Attaching to code-server
code-server  | [2023-09-02T16:14:35.499Z] info  code-server 4.16.1 94ef3776ad7bebfb5780dfc9632e04d20d5c9a6c
code-server  | [2023-09-02T16:14:35.500Z] info  Using user-data-dir ~/.local/share/code-server
code-server  | [2023-09-02T16:14:35.517Z] info  Using config file ~/.config/code-server/config.yaml
code-server  | [2023-09-02T16:14:35.517Z] info  HTTPS server listening on https://0.0.0.0:8080/
code-server  | [2023-09-02T16:14:35.517Z] info    - Authentication is enabled
code-server  | [2023-09-02T16:14:35.517Z] info      - Using password from $PASSWORD
code-server  | [2023-09-02T16:14:35.518Z] info    - Using certificate for HTTPS: ~/.config/server.crt
code-server  | [2023-09-02T16:14:35.518Z] info  Session server listening on /home/coder/.local/share/code-server/code-server-ipc.sock
code-server  | [16:14:48] 
code-server  | 
code-server  | 
code-server  | 
code-server  | 
code-server  | [16:14:48] Extension host agent started.
code-server  | File not found: /usr/lib/code-server/lib/vscode/out/vsda.js
code-server  | File not found: /usr/lib/code-server/lib/vscode/out/vsda_bg.wasm
code-server  | [16:14:55] [<unknown>][3613b883][ManagementConnection] New connection established.
code-server  | [16:14:56] Using the in-memory credential store as the operating system's credential store could not be accessed. Please see https://aka.ms/vscode-server-keyring on how to set this up. Details: libsecret-1.so.0: cannot open shared object file: No such file or directory
code-server  | [16:14:57] [<unknown>][8e5022cc][ExtensionHostConnection] New connection established.
code-server  | [16:14:57] [<unknown>][8e5022cc][ExtensionHostConnection] <1110> Launched Extension Host Process.
code-server  | [16:16:15] [<unknown>][3613b883][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
code-server  | [16:16:15] [<unknown>][8e5022cc][ExtensionHostConnection] <1110> Extension Host Process exited with code: 0, signal: null.
code-server  | File not found: /usr/lib/code-server/lib/vscode/out/vsda.js
code-server  | File not found: /usr/lib/code-server/lib/vscode/out/vsda_bg.wasm
code-server  | [16:16:24] [<unknown>][0668898c][ManagementConnection] New connection established.
code-server  | [16:16:25] [<unknown>][843dc6f1][ExtensionHostConnection] New connection established.
code-server  | [16:16:25] [<unknown>][843dc6f1][ExtensionHostConnection] <2979> Launched Extension Host Process.


```

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by code-asher** [comment]
Your browser is rejecting the certificate.  Unfortunately some browsers require valid certificates for service workers even if you click past the allow screen, so you will either have to disable this restriction in your browser or get a valid certificate.

**Comment by ZhengHui-Z** [comment]
> Your browser is rejecting the certificate. Unfortunately some browsers require valid certificates for service workers even if you click past the allow screen, so you will either have to disable this restriction in your browser or get a valid certificate (which also means you would need a domain, or you can forward the port to localhost).

This problem can be resolved by replacing the certificate. Thank you.

**Comment by colinwke** [comment]
> > Your browser is rejecting the certificate. Unfortunately some browsers require valid certificates for service workers even if you click past the allow screen, so you will either have to disable this restriction in your browser or get a valid certificate (which also means you would need a domain, or you can forward the port to localhost).
> 
> This problem can be resolved by replacing the certificate. Thank you.

I have encountered the same problem, could you please detail the solution?
