### ISSUE TITLE
[Bug]: Failed to load resource: the server responded with a status of 404 (Not Found)

### ISSUE THREAD

**Issue by ZhengHui-Z** [coder/code-server#6421]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: 
     - Microsoft Edge 115.0.1901.200   (x86_64)
     - Google Chrome 116.0.5845.140  (x86_64)
     - Safari 16.5.2 (18615.2.9.11.10)
- Local OS: MACos 13.4.1 (c) (22F770820d)
- Remote OS: Ubuntu 12.04
- Remote Architecture: AMD64
- `code-server --version`:  4.16.1 94ef3776ad7bebfb5780dfc9632e04d20d5c9a6c

### Steps to Reproduce

1. docker-compose.yml

```
version: "3"

services:
  code-server:
    container_name: code-server
    image: codercom/code-server
    ports:
      - "8080:8080"
    volumes:
      - ./project:/home/coder/project:rw
      - ./config:/home/coder/.config:rw
    environment:
      PASSWORD: 123456789
    restart: always

```
2. Nginx

```
server {
    listen       20005 ssl;
    server_name  control.xxxxx.xxx;
    # server_tokens off;

    ssl_certificate      /etc/letsencrypt/control.xxx.xxx_nginx/control.xxxx.xxx_bundle.crt;
    ssl_certificate_key  /etc/letsencrypt/control.xxx.xxx_nginx/control.xxxx.xxx.key;

    ssl_session_cache    shared:SSL:1m;
    ssl_session_timeout  5m;
    ssl_ciphers  HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers  on;

    location / {
        proxy_pass http://127.0.0.1:8080/;
        # proxy_set_header      Host                $host;
        # proxy_set_header      X-Real-IP           $remote_addr;
        # proxy_set_header      X-Forwarded-For     $proxy_add_x_forwarded_for;
        # proxy_set_header      X-Forwarded-Host    $host;
        # proxy_set_header      X-Forwarded-Proto   $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection upgrade;
        proxy_set_header Accept-Encoding gzip;
        proxy_set_header Origin https://$host;
        proxy_set_header Host $host;
        # proxy_set_header X-Forwarded-Host $remote_addr;
        proxy_set_header X-Forwarded-For $remote_addr;
    }

}
```

### Expected

No error reported

### Actual

<img width="771" alt="image" src="https://github.com/coder/code-server/assets/13689856/27c4834d-8a2b-4f18-96e5-ed6549fc4fa4">

<img width="495" alt="image" src="https://github.com/coder/code-server/assets/13689856/3d146d7a-5eb7-4a64-a8e3-ab7395c551ce">

### Logs

code-server  | [15:10:18] RequestStore#acceptReply was called without receiving a matching request 59
code-server  | [15:10:18] RequestStore#acceptReply was called without receiving a matching request 60
code-server  | File not found: /usr/lib/code-server/lib/vscode/out/vsda.js
code-server  | File not found: /usr/lib/code-server/lib/vscode/out/vsda_bg.wasm
code-server  | [15:12:19] [172.24.0.1][f6e5d897][ManagementConnection] New connection established.
code-server  | [15:12:21] [172.24.0.1][f3f857a7][ExtensionHostConnection] New connection established.
code-server  | [15:12:21] [172.24.0.1][f3f857a7][ExtensionHostConnection] <6276> Launched Extension Host Process.
code-server  | [15:12:21] RequestStore#acceptReply was called without receiving a matching request 61
code-server  | [15:12:21] RequestStore#acceptReply was called without receiving a matching request 62

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by ircasillase** [comment]
I have a similar issue using a nginx server pointing to my code-server machine to add HTTPS, its supposed just enabling web socket support should fix it, but not work for me.

**Comment by ZhengHui-Z** [comment]
> code-server | File not found: /usr/lib/code-server/lib/vscode/out/vsda.js
> code-server | File not found: /usr/lib/code-server/lib/vscode/out/vsda_bg.wasm

 I couldn't find any relevant static resources in the server either.

```shell
code-server | File not found: /usr/lib/code-server/lib/vscode/out/vsda.js
code-server | File not found: /usr/lib/code-server/lib/vscode/out/vsda_bg.wasm
```

**Comment by code-asher** [comment]
The vsda resources do not appear to be included in the OSS build of VS Code, and they appear to be optional, so I think it is something we can safely ignore.  Are you running into a bug or is it just the 404s?

**Comment by ircasillase** [comment]
@code-asher in my case throws this error and don't let me do anything else, it just reload and throws the error again.
![image](https://github.com/coder/code-server/assets/69492374/38b2bab0-5002-4889-94dc-9318ab9bbdfd)

**Comment by code-asher** [comment]
Got it, this looks like something else.  Usually 1006 closures on web sockets are caused by incorrectly configured reverse proxies but your configuration looks OK to me.  You might try running with `--log debug` just to make sure it is not an issue with the origin (if it is then there will be a debug log saying `blocking request`), although I am not sure how it could be since your config overrides the origin to always match the host.

I will try to reproduce with your config later today.

**Comment by code-asher** [comment]
I experimented with your config although I changed NGINX to listen without TLS since I have no certificates to use, and I am accessing it via the port (http://localhost:20005) rather than a name.  It worked for me so I am not sure what is going on.

**Comment by ircasillase** [comment]
Is possible to share your configuration? to compare with mine.

**Comment by ircasillase** [comment]
In my case looks like I was missing whit two instructions: 

- proxy_set_header Origin https://$host;
- proxy_set_header Host $host;

I set it up in my nginx and the error is gone, thanks!!

**Comment by ZhengHui-Z** [comment]
> just the 404s

just the 404s

**Comment by code-asher** [comment]
@ircasillase Oh oops sorry my bad, I got confused and thought you were the issue author so I thought the above config was yours.  Glad you got it fixed!  It sounds like the origin check was the source of your problem.

@ZhengHui-Z Awesome, I think there is nothing more we can do here then.

Please keep in mind though that by setting `Origin` you bypass the security of the check.  That header is meant to be sent by the browser.  If you remove the `Origin` line and still have problems, you might need `proxy_set_header Host $http_host;` instead.

**Comment by sathio** [comment]
i stumbled on this error as well, but it seems I can't fix it: 

I tried several browsers but no luck, I've also tried without proxy and it works fine.

![image](https://github.com/coder/code-server/assets/1990816/dc5224ce-91b7-4c09-9c6e-22091d400bfe)

```
map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}

server {

    server_name ha.*******.***;

    include /etc/nginx/gz.conf;
    include /etc/nginx/common.conf;
    access_log /var/log/nginx/ha.access.log;
    error_log /var/log/nginx/ha.error.log error;
    proxy_buffering off;

    location / {
        proxy_set_header Origin https://$host;
        proxy_pass http://192.168.69.210:8123;
        proxy_set_header Host $host;
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
    }


    listen 192.168.1.121:80;
}
```

**Comment by code-asher** [comment]
Have you tried `proxy_set_header Host $http_host;` instead?

**Comment by sathio** [comment]
no, it doesn't work

**Comment by code-asher** [comment]
Oh sorry I misread your post and thought we were talking about the web socket.  Yeah `$http_host` will not do anything for the icons.

I believe the icons are provided by a font.  The default is `codicon`.  If you open the browser dev tools and reload do you see a network request like this?  Is it for sure a 404?

```
https://[url]/stable-e76afa4a2bf4667a3c9f71bf56ef34b8ad365fbe/static/out/vs/base/browser/ui/codicons/codicon/codicon.ttf?5d4d76ab2ce5108968ad644d591a16a6
```

You could check to see if you can open the URL in a separate tab.  Maybe something is preventing that request from loading.  An browser extension maybe, or something in Home Assistant. 

Also check the browser console logs and see if there are any other errors or warnings, like about content security policy or cross-origin stuff for example.

If you are using an extension that changes the icons, it might be different, so let me know if that is the case.
