### ISSUE TITLE
[Docs]: How to debug source of code server in vscode

### ISSUE THREAD

**Issue by codegzx** [coder/code-server#6428]
I read the How-to-Contribute,but i really can not find how to debug code server in vscode;
I open the source in vscode at container, and start code-server with yarn watch at vscode terminal, but I don't know how to debug it with breakpoint in my vscode;
so anyone please,help me.

**Comment by code-asher** [comment]
I never got around to attaching a debugger to code-server so I am 
not able to provide specific instructions but maybe this will 
help:

https://code.visualstudio.com/docs/nodejs/nodejs-debugging

If someone figures it out I would be happy to add the steps to the 
docs.

**Comment by codegzx** [comment]
thank you for help, I success debug code server as:
 1. open source in vscode attach in  a docker container and run it
 2. debug: Launch Chrome with default config of vscode
