### ISSUE TITLE
[Bug]: Around 10G of RAM used after opening a folder with multiple rust crate project

### ISSUE THREAD

**Issue by GopherJ** [coder/code-server#6445]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Brave
- Local OS:  IPad
- Remote OS:  Linux mint
- Remote Architecture: x86_64
- `code-server --version`:  4.16.1

### Steps to Reproduce

1.  Setup code server on a Linux mint server, use frp and cloudflare dns to reverse proxy request to this server
2. Login to code server
3. Open a  folder with many rust crates
4. RAM increased 10G while normally a rust-analyzer lap server doesn’t consume that much

### Expected

No memory leak, lsp server can be shutdown correctly after moving focus to other projects

### Actual

Memory Leak

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by GopherJ** [comment]
Also although it’s a folder with multiple rust projects, but I opened only one of them and if I open that one using viscose it doesn’t consume 10G while code-server does comsume 10GB

**Comment by skight-shen** [comment]
> Also although it’s a folder with multiple rust projects, but I opened only one of them and if I open that one using viscose it doesn’t consume 10G while code-server does comsume 10GB

Same issue. Any updates?

**Comment by code-asher** [comment]
code-server is just a wrapper around the tech Codespaces uses so it does seem surprising that the issue does not reproduce there.  We have a few patches, of course, but nothing that looks to me like it could cause this, although I could be wrong.

Is it the extension host that is consuming the 10 GB?  Or which process?

I see a few issues about memory usage on the extension repository; a few of them have some troubleshooting steps we might want to try out: https://github.com/search?q=repo%3Arust-lang%2Frust-analyzer+memory+usage&type=issues

**Comment by code-asher** [comment]
Closing as stale but feel free to comment if you come back to this.
