### ISSUE TITLE
[Bug]: code-server armhf release doesn't open the specified directory on 32-bit Android device

### ISSUE THREAD

**Issue by AnonymousM21** [coder/code-server#6457]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome
- Local OS: **Android**, `uname --operating-system`: GNU/Linux
- Remote OS: **Termux**, ubuntu installed on it **without root** via `proot`
- Remote Architecture: `uname --machine --processor`: armv8l armv8l
- `code-server --version`: 4.17.1 and below versions

### Steps to Reproduce

1. ` code-server --auth none ./style50/`

### Expected

The folder to be opened that is specified on running the command (Folder `./style50`).

On the Browser Address Bar, the adress should be: http://localhost:8080/?folder=/root/style50

### Actual

Opens the most recent used/closed folder instead of specified directory `style50`.

On the browser Address Bar, the adress opens http://localhost:8080/?folder=/root/cs50-learn/week_01 instead of http://localhost:8080/?folder=/root/style50

### Screenshot/Video

Here is the screenshot of command that I ran:

![Screenshot_20230930-085615_Termux](https://github.com/coder/code-server/assets/118679960/11830228-eb7b-4872-a5ad-9790a4b31454)

Here is the output that opens the most recent opened/closed folder instead of the specified directory `style50`

![Screenshot_20230930-085738_Kiwi Browser](https://github.com/coder/code-server/assets/118679960/fc5f4bed-e88d-4afe-a466-c6dd4039a2b9)

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [x] I am using HTTPS.

### Notes

Thank you for help,
Melaku

**Comment by code-asher** [comment]
Sorry this issue fell through the cracks.  If you want to disable the last opened behavior you can do so with `--ignore-last-opened`.

**Comment by AnonymousM21** [comment]
> Sorry this issue fell through the cracks. If you want to disable the last opened behavior you can do so with `--ignore-last-opened`.

Thanks, It works now fine by adding the flag  `--ignore-last-opened` as  `code-server --auth none --ignore-last-opened ./style50/`.

Thanks again for help! Keep it up! :)
