### ISSUE TITLE
[Bug]: ESC should not exit fullscreen

### ISSUE THREAD

**Issue by code1704** [coder/code-server#6478]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: chrome 117.0.5938.92
- Local OS: mac
- Remote OS:
- Remote Architecture:
- `code-server --version`: 1.76.1

### Steps to Reproduce

1. enter fullscreen: ctrl + shift + p > full screen
2. press keyboard ESC

### Expected

do not exit full screen. When I press ESC, I just want to close the notification message. Github codespace works well for this case. It uses long-press-esc to exit full screen.

### Actual

exit full screen

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by code-asher** [comment]
This appears to be fixed now; I tested with the latest code-server on Chromium and ESC closed my editor tabs but did not exit full screen.
