### ISSUE TITLE
[Bug]: I cant access to cisco ios router provided in demo AAP2 Networking Automation Workshop

### ISSUE THREAD

**Issue by mariRuiz98** [coder/code-server#6479]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome
- Local OS: Windows
- Remote OS: REHL
- Remote Architecture: 
- `code-server --version`:

### Steps to Reproduce

1. open code-server
2. insert command in console: ssh rtr1

### Expected

Without asking for password i should be logged in the router 1

### Actual

I cant connect with ssh to the rtr1 because i keep getting connection closed. 

### Logs

[student@ansible-1 network-workshop]$ ssh rtr1
sign_and_send_pubkey: signing failed for RSA "/home/student/.ssh/id_rsa" from agent: agent refused operation
sign_and_send_pubkey: signing failed for RSA "/home/student/.ssh/id_rsa": error in libcrypto
Connection closed by 18.119.165.55 port 22

### Screenshot/Video

![image](https://github.com/coder/code-server/assets/80226452/292e7fef-3e58-4841-afda-e2f9dc95fd96)

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

I've tried requesting new demos but the same issue happens when the device is a IOS router

**Comment by code-asher** [comment]
Is your key password-protected?  Maybe it is trying to pop open a dialog to ask for the key, which will not work in code-server.  Maybe try `ssh-add ~/.ssh/id_rsa`.

**Comment by code-asher** [comment]
Closing as stale but feel free to comment if you come back to this.
