### ISSUE TITLE
[Bug]: Keyboard shortcuts can't work on Android browsers

### ISSUE THREAD

**Issue by html5syt** [coder/code-server#6480]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### OS/Web Information

- Web Browser:Kiwi browser(base on chromium),Firefox,Via(base on Android system WebView)
- Local OS:proot Ubuntu(Termux)
- Remote OS:same up↑(use 127.0.0.1)
- Remote Architecture:aarch64(arm64)
- `code-server --version`:4.17.1

### Steps to Reproduce

1. open code-server.
2. return to desktop and open browsers.
3. open 127.0.0.1:8888
4. login
5. open"keyboard shortcuts (Ctrl+k Ctrl+s)" 
6. touch pen on left and try to change keyboard shortcuts.

### Expected

I can change it and the input will show it,such as"Ctrl+Alt+h",and I can use it normally in editor.

### Actual

When I try to change it,the input show like "Ctrl+unknown" and I can't use it normally.

I tried all of the keyboard on Android that they can input Ctrl and so on. I tried the keyboard on other website that can use keyboard shortcuts and they're work correctly.

Why I don't use physical keyboard?Because I don't have Bluetooth keyboard and I want to use vscode without physical keyboard.

### Logs

It's too big,and I will put a file under.(you maybe should change .txt.png to .txt)
[i txt png](https://github.com/coder/code-server/assets/53525043/94905a67-b127-49c3-935e-abca242d3344)

### Screenshot/Video

https://github.com/coder/code-server/assets/53525043/25530f85-082f-4ae7-8843-95f3a6497f5d

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [x] I am using HTTPS.

### Notes

***PLEASE DON'T care about "I am using HTTPS. "check box.On local address can't have HTTPS!I'm only check it to avoid check.***

**Comment by html5syt** [comment]
*I don't have schedule to use code-server in this phone on other machine.*

**Comment by zongou** [comment]
add this to your seeting.json
```json
{
    "keyboard.dispatch": "keyCode"
}
```

**Comment by Splizard** [comment]
@zongou I added this to the documentation, maybe this configuration could be enabled by default on mobile browsers? not sure on the feasibility of this, perhaps a core contributor can comment on this.

**Comment by zongou** [comment]
> @zongou I added this to the documentation, maybe this configuration could be enabled by default on mobile browsers? not sure on the feasibility of this, perhaps a core contributor can comment on this.

it is easy to change the default value, i agree that we should change the default value. PR will come soon

**Comment by code-asher** [comment]
If at all possible, see if it can be changed upstream, I think Microsoft would want Codespaces to work well on mobile browsers as well.  The fewer patches we have to maintain the better!

**Comment by html5syt** [comment]
> add this to your seeting.json
> 
> ```json
> {
>     "keyboard.dispatch": "keyCode"
> }
> ```

@zongou Thank you!Your solution work!

https://github.com/coder/code-server/assets/53525043/79b1a155-9599-44a3-8e3f-6b3e4ca095d9
