### ISSUE TITLE
[Feat]: Migrate from node to bun

### ISSUE THREAD

**Issue by L3P3** [coder/code-server#6497]
## What is your suggestion?
I just upgraded my web server with many independent services and hundreds of modules from node to [bun](https://bun.sh/) in less than an hour. It feels faster now. :wink:
Since code-server uses node.js in the backend, it might be noticeably faster when using bun, too. At least we might have a way to use bun if installed and otherwise node.js.

## Why do you want this feature?
Speedup? Fun, definitely.

## Are there any workarounds to get this functionality today?
Someone could hack around with the local installation.

## Are you interested in submitting a PR for this?
Maybe, but mainly interested in some discussion here.

**Comment by Lan-Hekary** [comment]
Great Idea!!
I am interested in this as well.
I may try to experiment with it.

**Comment by code-asher** [comment]
This would be an interesting experiment especially with benchmarks.  Though, if it was implemented it might be better done upstream in https://github.com/microsoft/vscode, that way everyone benefits.

**Comment by code-asher** [comment]
Going to mark this as upstream and out of scope for code-server, would still like to see this upstream though since building VS Code is so slow.
