### ISSUE TITLE
[Bug]: code-server crashed on google cloud after a few minutes

### ISSUE THREAD

**Issue by likkai** [coder/code-server#6518]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Microsoft edge
- Local OS: Windows
- Remote OS: Ubuntu
- Remote Architecture: amd64
- `code-server --version`: 4.18.0 d7a2b4936af1bfd80cb96f2567af68badc2325e3 with Code 1.83.1

### Steps to Reproduce

1. turn on code server with `code-server --host 0.0.0.0 --port 8080 --cert`
2. enter the webpage through `ip`:8080
3. set aside for a few minutes

### Expected

vscode should stay online and code-server wont crash

### Actual

vscode got disconnected as code-server crashed

### Logs

[log.txt](https://github.com/coder/code-server/files/13242731/log.txt)

### Screenshot/Video

ssh window will crash 
![image](https://github.com/coder/code-server/assets/76016664/fa4ed741-3a52-45c3-b163-c0e1bc379936)
vscode will show disconnect
![image](https://github.com/coder/code-server/assets/76016664/e12e89b5-3749-4c13-beee-5dcb85443029)

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over a secure context?

- [X] I am using a secure context.

### Notes

Im hosting on google cloud e2 micro which has 1 gb of ram and 1 cpu core

**Comment by code-asher** [comment]
Are you able to test with a bit more resources just to see if it still crashes?  What you have might just not be enough.  Although, honestly I would expect what you have to work just fine: https://code.visualstudio.com/docs/supporting/requirements#_hardware

So maybe we have a memory leak or something.  Do you know why it is crashing?  Any errors in the logs?

**Comment by likkai** [comment]
I think it's just I simply don't have enough resources because the official vscode server (implemented through tunnel) also crash in the same way. No errors are shown in the logs.
