### ISSUE TITLE
[Bug]: Unable to popen Github Copilot Chat window

### ISSUE THREAD

**Issue by skerit** [coder/code-server#6520]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chromium
- Local OS: Linux
- Remote OS: Linux
- Remote Architecture: AMD64
- `code-server --version`: 4.18.0 d7a2b4936af1bfd80cb96f2567af68badc2325e3 with Code 1.83.1

### Steps to Reproduce

1. open code-server
2. install copilot extension from VSIX (v1.135)
3. try to open the chat

### Expected

The inline chat window should open

### Actual

Absolutely nothing

### Logs

```
[Extension Host] rejected promise not handled within 1 second: Error: command 'workbench.panel.chat.view.copilot.focus' not found
[Extension Host] stack trace: Error: command 'workbench.panel.chat.view.copilot.focus' not found
ERR command 'workbench.panel.chat.view.copilot.focus' not found: Error: command 'workbench.panel.chat.view.copilot.focus' not found
    at y.n (/stable-d7a2b4936af1bfd80cb96f2567af68badc2325e3/static/out/vs/workbench/workbench.web.main.js:1557:12276)
    at y.executeCommand (/stable-d7a2b4936af1bfd80cb96f2567af68badc2325e3/static/out/vs/workbench/workbench.web.main.js:1557:12205)
```

### Screenshot/Video

![image](https://github.com/coder/code-server/assets/755212/447fdc32-67bf-4030-946c-f849f90dd8ae)

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over a secure context?

- [X] I am using a secure context.

**Comment by skerit** [comment]
> I encountered the same problem, but I can't even install it. How did you manage to install the chat?

I installed the latest Copilot VSIX file from the marketplace.

**Comment by benz0li** [comment]
The use of this extension is restricted to Microsoft VS Code.

**Comment by code-asher** [comment]
I have seen elsewhere that the latest Copilot requires a newer version of Code than code-server currently contains so installing an older version might work, but unfortunately we are not able to recommend this since as @benz0li mentioned using the vsix in non-VS Code products like code-server seems to be a violation of Microsoft's terms of service for their marketplace and maybe a violation of the extension license as well (I have not read that one).

**Comment by aghasemi** [comment]
Hi. Thanks for the clarification regarding CoPilot. Is there any alternative that can be used with coee-server?

**Comment by lennardv2** [comment]
I created this https://github.com/sunpix/howto-install-copilot-in-code-server

installs latest compatible:
- copilot
- copilot-chat
