### ISSUE TITLE
[Feat]: Unable to install github-copilot-chat extension in code-server

### ISSUE THREAD

**Issue by AliceSync** [coder/code-server#6523]
Dear Developers,

I have encountered an issue while using code-server. I am unable to install the github-copilot-chat extension in code-server. I have tried installing it using a vsix file, but without success. I noticed that other extensions, such as github-copilot, can be installed and used normally.

I would appreciate it if the github-copilot-chat could be made available for direct installation from the extension marketplace, or if this issue could be resolved. I believe this would be beneficial to me and other developers using code-server.

Looking forward to your response.

Thank you.

**Comment by taomanwai** [comment]
Please! It's high-value feature for code-server.

**Comment by smerschjohann** [comment]
You can edit the requirements inside of the vsix, then it works without any issues: https://github.com/coder/code-server/discussions/4363#discussioncomment-6654546

**Comment by benz0li** [comment]
> if the github-copilot-chat could be made available for direct installation from the extension marketplace

Proprietary extensions or extensions whose use is restricted to Microsoft VS Code will never make it into the [Open VSX Registry](https://open-vsx.org).

**Comment by code-asher** [comment]
If an extension is telling you that it is not compatible with the current version of code-server, as mentioned above you can edit the requirements or you can download an older version.

But yeah as far as publishing to Open VSX this would need to be done by Microsoft.  I found some discussions but they have not commented:

https://github.com/search?q=org%3Acommunity+copilot+openvsx&type=discussions

**Comment by smerschjohann** [comment]
please don't, there are other extensions, as well as github copilot works ...
