### ISSUE TITLE
[Bug]: npm install on windows fails

### ISSUE THREAD

**Issue by deostroll** [coder/code-server#6545]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: msedge
- Local OS: windows 11
- Remote OS: windows 11
- Remote Architecture: x64
- `code-server --version`: 4.19.0 (from npm; not cli)

![image](https://github.com/coder/code-server/assets/415336/534d4ac3-d98f-4aa0-ae1d-ab9ccd87b962)

### Steps to Reproduce

1. Download and install nodejs 20.x (as admin)
2. Ran `npm i -g code-server`

### Expected

npm install should have gracefully completed

### Actual

It errored saying sh is not a recognized program/command

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over a secure context?

- [X] I am using a secure context.

**Comment by code-asher** [comment]
code-server has no Windows support at the moment (PRs welcome), although maybe this can be worked around by using git bash or cygwin or something.

**Comment by code-asher** [comment]
Closing in favor of https://github.com/coder/code-server/issues/1397
