### ISSUE TITLE
Can't use the code search available via Strg+F on the "de" layout:

### ISSUE THREAD

**Issue by archef2000** [coder/code-server#6547]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Firefox/Chrome
- Local OS: Windows 11
- Remote OS: Ubuntu
- Remote Architecture: aarch64
- `code-server --version`: 4.19.0-ls182

### Steps to Reproduce

1. open code-server
2. Layout: de
3. press Strg+F

### Expected

search window popup of vs code

### Actual

search windows popup of Firefox/Chrome that can't search the whole file

### Logs

 INFO Resolving connection token (code.tld)... workbench.web.main.js:645:3383
 INFO Resolved connection token (code.tld) after 1 ms workbench.web.main.js:645:3383
 INFO Creating a socket (renderer-Management-4de760bd-2653-40ca-8abe-c511e2264e20)... workbench.web.main.js:645:3383
 INFO Creating a socket (renderer-Management-4de760bd-2653-40ca-8abe-c511e2264e20) was successful after 117 ms. workbench.web.main.js:645:3383
Laden fehlgeschlagen für das <script> mit der Quelle "https://code.tld/stable-9658969084238651b6dde258e04f4abd9b14bfd1/static/out/vsda.js". code.tld:1:1
The web worker extension host is started in a same-origin iframe! workbench.web.main.js:1405:12271
 INFO Creating a socket (renderer-ExtensionHost-53537d13-65b5-4aa2-a6b2-ae610df0c471)... workbench.web.main.js:645:3383
 INFO [Service Worker] registered workbench.web.main.js:645:3383
 INFO Creating a socket (renderer-ExtensionHost-53537d13-65b5-4aa2-a6b2-ae610df0c471) was successful after 82 ms. workbench.web.main.js:645:3383
Die Zeichenkodierung eines Dokuments im Frame wurde nicht deklariert. Das Dokument kann anders aussehen, wenn es ohne das umgebende Frame-Dokument angesehen wird. webWorkerExtensionHostIframe.html
Content-Security-Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf inline blockiert ("script-src"). sandbox eval code:15:347
Content-Security-Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf inline blockiert ("script-src"). utils.js:42:9
 INFO Updating additional builtin extensions cache workbench.web.main.js:645:3383
[Extension Host] Failed to connect to provider "Command failed with exit code 128: git symbolic-ref -q HEAD\nfatal: not a git repository (or any parent up to mount point /)\nStopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set)." workbench.web.main.js:94:453
Overwriting grammar scope name to file mapping for scope source.python.
Old grammar file: vscode-remote://code.tld/app/code-server/lib/vscode/extensions/python/syntaxes/MagicPython.tmLanguage.json.
New grammar file: vscode-remote://code.tld/config/extensions/magicstack.magicpython-1.1.1-universal/grammars/MagicPython.tmLanguage workbench.web.main.js:1930:30220
 INFO Migrating global extension storage from lonefy.vscode-js-css-html-formatter to lonefy.vscode-JS-CSS-HTML-formatter... workbench.web.main.js:645:3383
 INFO Migrated global extension storage from lonefy.vscode-js-css-html-formatter to lonefy.vscode-JS-CSS-HTML-formatter workbench.web.main.js:645:3383
 INFO Migrating workspace extension storage from lonefy.vscode-js-css-html-formatter to lonefy.vscode-JS-CSS-HTML-formatter... workbench.web.main.js:645:3383
 INFO Error while migrating workspace file storage from 'lonefy.vscode-js-css-html-formatter' to 'lonefy.vscode-JS-CSS-HTML-formatter' File to move/copy does not exist workbench.web.main.js:645:3383
 INFO Migrated workspace extension storage from lonefy.vscode-js-css-html-formatter to lonefy.vscode-JS-CSS-HTML-formatter workbench.web.main.js:645:3383
  ERR read ECONNRESET: Error: read ECONNRESET
	at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20) workbench.web.main.js:645:3592
Content-Security-Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf inline blockiert ("script-src").

### Screenshot/Video

https://github.com/coder/code-server/assets/69057532/f04bb85a-e756-49c1-8b12-65e49bf31bca

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over a secure context?

- [X] I am using a secure context.

### Notes

It is only a Problem on windows testing it on Android it is working fine

**Comment by code-asher** [comment]
I wonder if it will work if you change `keyboard.dispatch` to `keyCode` in the settings?  I think there are issues with layout mapping in the web version of VS Code.  https://github.com/microsoft/vscode/issues/23991#issuecomment-1817754940

**Comment by code-asher** [comment]
You can use the command palette but if you are having keybinding issues you might need to open settings via File > Preferences > Settings or use the gear icon in the bottom left corner.

**Comment by code-asher** [comment]
Oh and from there, I usually just search "keycode" and it is the only setting that pops up.

**Comment by archef2000** [comment]
Sorry but it can't find anything could you describe where to find it?

**Comment by code-asher** [comment]
Did you click `File` then `Preferences` then `Settings`?  Check out the VS Code documentation for more information including screenshots: https://code.visualstudio.com/docs/getstarted/settings#_settings-editor

**Comment by archef2000** [comment]
I know that but IT can't find "keycode" in the settings

**Comment by code-asher** [comment]
Weird, maybe try searching for `keyboard.dispatch`?  Here is what comes up for me:

![keycode](https://github.com/coder/code-server/assets/45609798/3097fbf8-04c7-4a14-abb2-a8c2cda9b425)

**Comment by code-asher** [comment]
Closing as stale but feel free to comment if you come back to this.
