### ISSUE TITLE
[Feat]: Get the external auth callback/redirect to the specific extension in embedded code server?

### ISSUE THREAD

**Issue by MurrayC7** [coder/code-server#6584]
Generally in local VSCode, I know an extension whose login process is like: 
1. starting with a click on the login button
2. vscode asks to open the external website with url, e.g., https://auth.xxx.xxx/xxx/auth?{params}&redirect_uri=vscode://{extension_name}&state=xxx
3. the extension starts to wait for login state/token, etc.
4. some authentication process in the browser
5. redirection back to vscode with the special uri, e.g., vscode://{extension_name}&state=xxx
6. login success.

However, in the case of embedded code server, I got stuck in step 5. 
The only clue I found is as `Failed to launch 'code-oss://{extension_name}?{params}' because the scheme does not have a registered handler` in browser DevTool. I consider `code-oss` as the schema on the Linux server instead of Windows, right?
Anyway I can do to solve this login issue?

The code server url is like `http://xxx:8889/?folder=/data/workspace`. Does simple URL schema change work?
Otherwise, do I need to develop REST APIs? or just use some forward/proxy methods?

Code-server Version:
4.19.1

Thanks!

**Comment by wangxi761** [comment]
Is there any new progress?

**Comment by code-asher** [comment]
No change, and to make a redirect work I believe it will required modifying VS Code itself, so it is probably not something we will do here in code-server.

I believe the way other extensions do this (like GitHub) is ask you to paste a code instead of being redirected back to code-server.

**Comment by code-asher** [comment]
So, I just tried the GitLens extension and it was able to do auth with a redirect in code-server so this actually appears possible now.  I would check the GitLens extension for how to do this if you need it.

**Comment by tianze0926** [comment]
I encountered the same authentication issue with Augment Code. After completing browser authentication, the `code-oss://augment.vscode-augment/auth/...` URI fails to open automatically. Here’s a workaround that worked for me:  

1. **Copy the full URI** generated in the browser after authentication (e.g., `code-oss://augment.vscode-augment/auth/...`), in my case, the hyperlink in `If you encounter any issues, try [clicking here].`.  
2. In code-server, open the **Command Palette** (`Ctrl/Cmd+Shift+P`).  
3. Run the command: `Developer: Open URL`.  
4. **Paste the URI** into the prompt and press `Enter`.  

This should complete the authentication flow successfully.
