### ISSUE TITLE
Terminal extends beyond the border and elements are off-drawn

### ISSUE THREAD

**Issue by planetoryd** [coder/code-server#6589]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Mullvad 13.0.6
- Local OS: local machine
- Remote OS: 6.6.6-200.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC
- Remote Architecture:
- `code-server --version`:4.19.1 0c98611e6b43803a9d5dba222d7023b569abfb49 with Code 1.84.2

### Steps to Reproduce

1. open terminal

### Expected

works

### Actual

broken. unusable because the bottom part can never be scrolled to. 

### Screenshot/Video

![image](https://github.com/coder/code-server/assets/68096727/df4963aa-4a74-4b42-a617-e3775c745a12)

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over a secure context?

- [X] I am using a secure context.

**Comment by planetoryd** [comment]
web console logs
[codelogs.txt](https://github.com/coder/code-server/files/13695573/codelogs.txt)

**Comment by benz0li** [comment]
@planetoryd Can you reproduce this on my *reference deployment*?: https://demo.jupyter.b-data.ch  
ℹ️ Currently running `code-server --version`: 4.19.1 0c98611e6b43803a9d5dba222d7023b569abfb49 with Code 1.84.2

Try with Mullvad but also another browser. I can't reproduce this with "common" browsers like Firefox, Edge, Safari.

---

Shell on https://demo.jupyter.b-data.ch is also Zsh; further enhanced with

* Framework: [Oh My Zsh](https://ohmyz.sh/)
* Theme: [Powerlevel10k](https://github.com/romkatv/powerlevel10k#oh-my-zsh)
* Font: [MesloLGS NF](https://github.com/romkatv/powerlevel10k#fonts)

**Comment by planetoryd** [comment]
```


403 : Forbidden

Sorry, you are not currently authorized to use this hub. Please contact the hub administrator.

```

I can't access it

**Comment by planetoryd** [comment]
I switched to librewolf. Now it's like this

![image](https://github.com/coder/code-server/assets/68096727/80d0f69e-0a2a-46f4-b8af-59c0f21cf904)

I don't like that font and it doesnt respond to my settings

**Comment by planetoryd** [comment]
![image](https://github.com/coder/code-server/assets/68096727/2eeb9985-7119-49dd-bb8f-fc7f40ca0d0e)

For anyone who comes across this problem, add 127.1 to `privacy.resistFingerprinting.exemptedDomains`

I decided to use mullvad again because librewolf somehow didn't work with wayland.
