### ISSUE TITLE
[Bug]: Docs are leading to a 404

### ISSUE THREAD

**Issue by bdsoha** [coder/code-server#6593]
All documentation related to `code-server` are responding with a 404:

> Uh-oh! You’ve hit our 404 page. 
> We couldn’t find the page that you requested. Hit back or visit our Home page.

Root URL: https://coder.com/docs/code-server/latest

**Comment by 04bondgoods** [comment]
other links are the same 
wondering what happened 
https://coder.com/docs/code-server/latest/FAQ
https://coder.com/docs/code-server/latest/CONTRIBUTING

**Comment by bdsoha** [comment]
@04bondgoods I noticed that as well, I was just linking to the root.

**Comment by bdsoha** [comment]
Seems like things are working again.
