### ISSUE TITLE
[Bug]: extensions not loading if running via reverse-proxy

### ISSUE THREAD

**Issue by NunoHiggs** [coder/code-server#6594]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome
- Local OS: Windows
- Remote OS: Linux/Docker
- Remote Architecture: amd64
- `code-server --version`: code-server: v4.19.1

### Steps to Reproduce

1. Run vscode. This is affecting both standalone or docker builds with the PROXY_DOMAIN set on both.
2. Chose and install any extensions.
3. Validate that the extensions is enabled via the webui directly on the code-base server itself.
4. Go to the reverse proxy published url. Everything works inside of vscode, except the plugins that are loaded *and* enabled but appear as inactive:

Directly on the server via http://$ip:8000:

![image](https://github.com/coder/code-server/assets/16701703/376dc3c3-3eea-4d6b-a1bd-d8618efc3fef)

Via the published URL:

![image](https://github.com/coder/code-server/assets/16701703/589f107a-286f-4414-855c-3d9acaf27dde)

My current reverse proxy config:

```
<VirtualHost *:80>
  ServerAdmin nuno@myfancydomain.net
  Servername vscode.myfancydomain.net
  Redirect / https://vscode.myfancydomain.net
  RewriteEngine On 
  RewriteCond %{REQUEST_METHOD} ^TRACE 
  RewriteRule .* - [F] 
</VirtualHost>                                  


<VirtualHost *:443>

ServerName  vscode.myfancydomain.net:443
ServerAdmin nuno@myfancydomain.net
Options +FollowSymLinks +Includes 
SSLEngine on
SSLProtocol             all -SSLv2 -SSLv3 -TLSv1 -TLSv1.1
SSLCipherSuite ALL:!ADH:!EXPORT56:RC4+RSA:+HIGH:+MEDIUM:+LOW:+SSLv2:+EXP:+eNULL

SSLCertificateKeyFile   /etc/letsencrypt/live/myfancydomain.net-0002/privkey.pem
SSLCertificateFile      /etc/letsencrypt/live/myfancydomain.net-0002/cert.pem
SSLCertificateChainFile         /etc/letsencrypt/live/myfancydomain.net-0002/chain.pem

SSLProtocol All -SSLv2 -SSLv3
SSLHonorCipherOrder On
SSLCompression Off
SSLCipherSuite EECDH+ECDSA+AESGCM:EECDH+aRSA+AESGCM:EECDH+ECDSA+SHA384:EECDH+ECDSA+SHA256:EECDH+aRSA+SHA384:EECDH+aRSA+SHA256:EECDH+aRSA+RC4:EECDH:EDH+aRSA:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:AES256-SHA256:AES128-SHA256:AES128-SHA:DHE-RSA-DES-CBC3-SHA:DES-CBC3-SHA:RC4-SHA:!aNULL:!eNULL:!ADH:!EXP:!LOW:!DES:!MD5:!PSK:!SRP:!DSS:!RC4:!ECDHE-RSA-DES-CBC3-SHA:!DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!ECDHE-RSA-DES-CBC3-SHA:!DES-CBC3-SHA

ErrorLog  "| /usr/bin/logger -thttpd_reverseproxy_vscode.myfancydomain.net -plocal6.err"
CustomLog "| /usr/bin/logger -thttpd_reverseproxy_vscode.myfancydomain.net -plocal6.notice" combined

ServerAlias vscode.net.xpto

SSLProxyEngine On
Options FollowSymLinks
ProxyRequests Off
Options FollowSymLinks
ProxyVia On
ProxyPreserveHost On
RemoteIPProxyProtocol On
RemoteIPHeader X-Forwarded-For

RewriteEngine On
RewriteCond %{HTTP:Upgrade} =websocket [NC]
RewriteRule /(.*)           ws://172.16.0.67:8444/$1 [P,L]
RewriteCond %{HTTP:Upgrade} !=websocket [NC]
RewriteRule /(.*)           http://172.16.0.67:8444/$1 [P,L]

ProxyPass        /  http://172.16.0.67:8444/ nocanon
ProxyPassReverse /  http://172.16.0.67:8444/


SSLProxyVerify      none
SSLProxyCheckPeerCN off 
SSLProxyCheckPeerName off
SSLProxyCheckPeerExpire off

# DISABED ModSec

<IfModule mod_security2.c>


</IfModule>

</VirtualHost>
```

### Expected

For the extensions to work as expected.

### Actual

No extensions appear to load or are loaded

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I tested this in native VS Code.
- [X] This does not happen in native VS Code.
- [ ] I tested this in GitHub Codespaces.
- [ ] This does not happen in GitHub Codespaces.

### Are you accessing code-server over a secure context?

- [X] I am using a secure context.

**Comment by davidliyutong** [comment]
Hi, I am running into a similar bug. The code-server works fine, but the extensions fail to load. I use a reverse proxy with a subpath (something like http://127.0.0.1:8000/coder/). Can you share how you resolved this issue?
