### ISSUE TITLE
[Bug]: vode-server jupyter output disapper

### ISSUE THREAD

**Issue by JJplane** [coder/code-server#6604]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser:chrome
- Local OS: macOS
- Remote OS: Ubuntu
- Remote Architecture: Linux hippo-033065047121.sg52 4.19.91-009.ali4000.alios7.x86_64 #1 SMP Mon Jan 25 10:47:38 CST 2021 x86_64 x86_64 x86_64 GNU/Linux
- `code-server --version`: 4.16.1 94ef3776ad7bebfb5780dfc9632e04d20d5c9a6c with Code 1.80.2

### Steps to Reproduce

1.open code-server
2.excute jupyter cell

### Expected

![image](https://github.com/coder/code-server/assets/28783826/36132e33-b8bd-44b0-af55-cabae72e97ed)
show output

### Actual

![image](https://github.com/coder/code-server/assets/28783826/ab7ca44e-56eb-4b6f-a82b-eb20e8f94d33)
noting show

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I tested this in native VS Code.
- [X] This does not happen in native VS Code.
- [X] I tested this in GitHub Codespaces.
- [X] This does not happen in GitHub Codespaces.

### Are you accessing code-server over a secure context?

- [X] I am using a secure context.

**Comment by code-asher** [comment]
Does this reproduce in the latest version of code-server?  It is working for me in v4.20.0.

**Comment by JJplane** [comment]
> Does this reproduce in the latest version of code-server? It is working for me in v4.20.0.

While how to upgrade a code-server which is working? I didn't find any information.

**Comment by code-asher** [comment]
Upgrading depends on how you installed.  For example if you used our installation script you can just run it again.

**Comment by code-asher** [comment]
Closing as stale but feel free to comment if you come back to this.
