### ISSUE TITLE
[Bug]: Ctrl+Click / Code Jump / Go To Definition Does Not Work Properly in Python/Jupyter Notebooks

### ISSUE THREAD

**Issue by rohit901** [coder/code-server#6619]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome
- Local OS: Mac
- Remote OS: Linux
- Remote Architecture: Ubuntu
- `code-server --version`: 1.85.1
0b84523121d6302fbe30eda7899ec3b81810748e
x64

### Steps to Reproduce

1. Open `settings.json`, and add this line: `"python.languageServer": "Jedi",` [following #6323]
3. Activate a specific conda environment and select it in the interpreter or select it in the jupyter notebook.
4. import some libraries in `test.py` or `test.ipynb`, for example: [in activated or selected conda environment]
```
import torch
import numpy
import diffusers
```
Hover or Ctrl+Click on some libraries like torch and numpy above work, and they open the file located in `/apps/local/anaconda2023/lib/python3.11/site-packages/<library>`

However, Hover/Ctrl+Click on `diffusers` does not work. I believe this is because my conda environment is stored in this location, and `diffusers` is available here: `/home/rohit.bharadwaj/.conda/envs/learn_diffusion/lib/python3.11/site-packages/diffusers`

How can I ensure that Jedi gets the library files from correct location?
My conda environment is called `learn_diffusion`, and when I set the python interpreter in the GUI, the location for it is shown as `./conda/envs/learn_diffusion/bin/python`
whereas location for `base` conda environment is: `/apps/local/anaconda2023/bin/python`, So JEDI seems to be using the `base` conda env location for code jump? How to change it?

### Expected

Code Jump should work properly for all libraries in current conda environment and should route to proper location.

### Actual

Hover/Ctrl+Click on `diffusers` does not work. I believe this is because my conda environment is stored in this location, and diffusers is available here: `/home/rohit.bharadwaj/.conda/envs/learn_diffusion/lib/python3.11/site-packages/diffusers`

Jedi server is looking for libraries in `/apps/local/anaconda2023/lib/python3.11/site-packages/<library>`

My conda environment is called `learn_diffusion`, and when I set the python interpreter in the GUI, the location for it is shown as `./conda/envs/learn_diffusion/bin/python`
whereas location for `base` conda environment is: `/apps/local/anaconda2023/bin/python`, So JEDI seems to be using the `base` conda env location for code jump? How to change it?

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I tested this in native VS Code.
- [X] This does not happen in native VS Code.
- [ ] I tested this in GitHub Codespaces.
- [ ] This does not happen in GitHub Codespaces.

### Are you accessing code-server over a secure context?

- [ ] I am using a secure context.

**Comment by OceanTrader1** [comment]
I am using the same code-server configuration I used in #6323 and it appears to be working as expected by navigating the correct conda environment. Confirm that you have selected the correct conda environment *within* the *\*.ipynb* file. You may need to refresh the page once or twice to load the correct settings.

<details>
<summary>Setup temporary environment...</summary>
<br>

```bash
#!/bin/bash

TEST_DIR="$HOME/Documents/github/test"

conda create -n tmp -c conda-forge python=3.10 numpy diffusers -y

if [ ! -d "$TEST_DIR" ]; then
    mkdir -p "$TEST_DIR"
fi

if [ ! -f "$TEST_DIR/test.ipynb" ]; then
    touch "$TEST_DIR/test.ipynb"
fi
```

</details>



Uploading code-server-conda-jedi.mov…

**Comment by OceanTrader1** [comment]
I am using the same code-server configuration I used in #6323 and it appears to be working as expected by navigating to the correct package within the given conda environment. Confirm that you have selected the correct conda environment *within* the *\*.ipynb* file. You may need to refresh the page once or twice to load the correct settings.

<details>
<summary>Setup temporary environment...</summary>
<br>

```bash
#!/bin/bash

TEST_DIR="$HOME/Documents/github/test"

conda create -n tmp -c conda-forge python=3.10 numpy diffusers -y

if [ ! -d "$TEST_DIR" ]; then
    mkdir -p "$TEST_DIR"
fi

if [ ! -f "$TEST_DIR/test.ipynb" ]; then
    touch "$TEST_DIR/test.ipynb"
fi
```

</details>

https://github.com/coder/code-server/assets/69881238/85400cd4-d8a1-4b1f-b8aa-64d00f6b345c

**Comment by OceanTrader1** [comment]
> is it because I'm not running in HTTPS?

Yes. It is an HTTP/S issue. I am not able to open *\*.ipynb* files at all on HTTP (blank screen area where file contents should be).

For *\*.py* files, I am having success setting the workspace environment to the conda environment using the Python Environment Manager extension


https://github.com/coder/code-server/assets/69881238/bab2a402-3f5e-4852-9350-655881c16d04

<details><summary>Python Environment Manager Extension...</summary>
<p>

```text
Name: Python Environment Manager
Id: donjayamanne.python-environment-manager
Description: View and manage Python environments & packages.
Version: 1.2.4
Publisher: donjayamanne
VS Marketplace Link: https://open-vsx.org/vscode/item?itemName=donjayamanne.python-environment-manager
```

</p>
</details>

**Comment by rohit901** [comment]
> Yes. It is an HTTP/S issue. I am not able to open _*.ipynb_ files at all on HTTP (blank screen area where file contents should be).
Regarding not being able to open *.ipynb files, I use this hack which works if you use Google Chrome.

1. Go to this link on chrome: [chrome://flags/#unsafely-treat-insecure-origin-as-secure](chrome://flags/#unsafely-treat-insecure-origin-as-secure)
2. Enable the option `Insecure origins treated as secure` in that page, and in the input text box there, type this:
`http://<ip_of_the_machine>:10000` 
3. Click outside the box, and it should ask you to reload chrome for changes to take affect.
4. Now you can open *.ipynb files in HTTP.

Since Im able to open ipynb files in HTTP, it should not be issue of me using HTTP that Jedi LSP is not working correctly right? 

Btw I will check out python environment manager extension and let you know how it goes, thanks for sharing.

**Comment by OceanTrader1** [comment]
This is a non-answer but since the focus is towards Jupyter notebooks, [Jupyter Lab]( https://jupyter.org/install) might be a potential alternative that supports user installs and runs over HTTP.

**Comment by rohit901** [comment]
> This is a non-answer but since the focus is towards Jupyter notebooks, [Jupyter Lab](https://jupyter.org/install) might be a potential alternative that supports user installs and runs over HTTP.

Thanks for sharing. I did explore jupyter lab earlier too, but it does not suit me well because I would like to use VS Code while working on my projects so I can make use of all the extensions available in VS Code which also includes Github copilot which I often use a lot to help me with my projects and easily get the boilerplate code done. 

Thus, this project (code-server) seems to be the only useful way for me to use VS Code in my remote systems which are allocated to me through SLURM system [I can not use remote SSH feature of my local VS Code to access this SLURM based machines]

**Comment by lizheray** [comment]
The following trick method works for me:

1. Click "File -> New File..." at the top left corner menu bar
2. Choose "Jupyter Notebook" to create a new blank jupyter notebook file

Then go back to your python file, the code jump works well! Amazing!

**Comment by code-asher** [comment]
Closing since it looks like there is nothing we can fix in code-server?  Let me know if I got it wrong.

**Comment by zengziru** [comment]
I have the same question, and I found when I use the method above like: 
    Click "File -> New File..." at the top left corner menu bar
    Choose "Jupyter Notebook" to create a new blank jupyter notebook file
I found the new file will be save to /opt/conda/lib....., but not the current workspace folder like:/workspace/my_user/project....
It seems like the code-server is in the system conda environment but not in the current python interpreter.
How should we solve it?

**Comment by zengziru** [comment]
> > This is a non-answer but since the focus is towards Jupyter notebooks, [Jupyter Lab](https://jupyter.org/install) might be a potential alternative that supports user installs and runs over HTTP.
> 
> Thanks for sharing. I did explore jupyter lab earlier too, but it does not suit me well because I would like to use VS Code while working on my projects so I can make use of all the extensions available in VS Code which also includes Github Copilot that I often use a lot to help me with my projects and easily get the boilerplate code done.
> 
> Thus, this project (code-server) seems to be the only useful way for me to use VS Code in my remote systems which are allocated to me through SLURM system [I can not use remote SSH feature of my local VS Code to access this SLURM based machines]

I found the solution!!! You can download the Pyright in vscode extensions market, it is the open source version for pylance。 Then you can see when you debug it can go to the right definition！

**Comment by rohit901** [comment]
Thanks for sharing, @zengziru. I'm sure it will be helpful for others who happen to come across this same issue/thread.

**Comment by benoit-cty** [comment]
Hello, for thoose coming here from a search engine, I solve my Ctrl+click  problem by updating Code Server.

Have a look to the output where a message tell me the version was outdated:
![image](https://github.com/user-attachments/assets/f27b001e-af70-46fe-b731-b0cb23144b8d)
