### ISSUE TITLE
[Bug]: Can't install Copilot-chat

### ISSUE THREAD

**Issue by KangByungwoo** [coder/code-server#6625]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: chrome
- Local OS: windows 10
- Remote OS: ubuntu
- Remote Architecture:
- `code-server --version`: 4.20.0

### Steps to Reproduce

Tried to install Copilot-chat via vsix b/c it didn't show up in extensions tab.
Error message occurred.

### Expected

Should have been able to install it.

### Actual

I can't seem to get copilot-chat working with the latest version of code-server. The extension says it is incompatible with Version 1.85.

There's a similar issue https://github.com/microsoft/vscode-copilot-release/issues/353

### Does this issue happen in VS Code or GitHub Codespaces?

- [ ] I tested this in native VS Code.
- [ ] This does not happen in native VS Code.
- [ ] I tested this in GitHub Codespaces.
- [ ] This does not happen in GitHub Codespaces.

### Are you accessing code-server over a secure context?

- [ ] I am using a secure context.

### Notes

Note added: I thought code-server is the one described in https://code.visualstudio.com/docs/remote/ssh. Will try the method explained there.

**Comment by benz0li** [comment]
The use of this extension is restricted to Microsoft VS Code.

See also https://github.com/coder/code-server/issues/6520#issuecomment-1809235131

**Comment by code-asher** [comment]
I will go ahead and close since this is not a bug with code-server.  Thanks everyone!

**Comment by tophermade** [comment]
1.16 https://marketplace.visualstudio.com/_apis/public/gallery/publishers/GitHub/vsextensions/copilot/1.160.0/vspackage
Fully functional, but predates chat. Instead has the "extensions" panel.

**Comment by Pinwheeler** [comment]
> I just solved this, you can download the visx file from the market, change the extension to zip, open it with compression software, change the vscode version in the "extension/package.json" file to "engines":{"vscode":"^1.85.0",} , Save and change back to the suffix visx, then can install

@code-asher I think this implies that code-server could be publishing with a later version of VSCode and that would solve this issue?

The change is `"^1.97.0" -> "^1.85.0`

So seems like this is prompting code-server to update the bundled version, no? I leave the re-open decision to you.

**Comment by code-asher** [comment]
We already publish code-server with the most recent version of VS Code, which is currently 1.96.2.

I think probably folks are downloading the version of the plugin for VS Code insiders, rather than stable.

**Comment by code-asher** [comment]
Actually, I wonder if this is a problem with the VS Code marketplace, where downloading the extension gives you the pre-release version for some reason.

**Comment by cloorc** [comment]
In debian 12, my solution is as following:

1. Download the vsix extension from https://marketplace.visualstudio.com/items?itemName=GitHub.copilot-chat (default file name with `wget` command is `vspackage`)
2. Check the file type from `file vspackage`(it might be gzip file)
3. Using `gunzip` to decompress the file, now it should be a zip file and rename it with `vsix` extension
4. Open it in vim(we need to tell vim open vsix as zip file, see https://stackoverflow.com/questions/22387836/open-a-docx-file-as-a-zip-in-vim)
5. Navigate to `extension/package.json` and open it
6. Search `vscode` compitable version and change it according to your code server `base` version(vscode version)
7. Search `isPreRelease` and change its value to `false`
8. Save `package.json` file and exit the zip file(`buftype` will save to zip automatically)
9. Install this extension in your code-server instance
