### ISSUE TITLE
[Bug]: Save indicator doesn't show up

### ISSUE THREAD

**Issue by KangByungwoo** [coder/code-server#6626]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: chrome
- Local OS: Windows 10
- Remote OS: Ubuntu
- Remote Architecture:
- `code-server --version`: 4.20.0

### Steps to Reproduce

1. open code-server.
2. modify a file.
3. A save indicator (asterisk) next to the filename in the tab doesn't show up. But, saving seems to be working.

### Expected

Should see an asterisk.

### Actual

A save indicator (asterisk) next to the filename in the tab doesn't show up. But, saving seems to be working.

### Does this issue happen in VS Code or GitHub Codespaces?

- [ ] I tested this in native VS Code.
- [ ] This does not happen in native VS Code.
- [ ] I tested this in GitHub Codespaces.
- [ ] This does not happen in GitHub Codespaces.

### Are you accessing code-server over a secure context?

- [ ] I am using a secure context.

**Comment by code-asher** [comment]
I think this is because by default auto-save is on and it will not show the dirty indicator when auto-save is enabled.  You can make the dirty indicator appear by disabling auto-save.

**Comment by code-asher** [comment]
Let me know if you still have issues.  For now I will close as this being expected.
