### ISSUE TITLE
[Bug]: 内网搭建一个code-server没有证书，通过ip地址访问无法使用jupyter和markdown等功能，喜欢自己能选择。

### ISSUE THREAD

**Issue by laiquziru** [coder/code-server#6627]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser:chrome
- Local OS:
- Remote OS:
- Remote Architecture:
- `code-server --version`:

### Steps to Reproduce

1.
2.
3.

### Expected

1

### Actual

11

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I tested this in native VS Code.
- [ ] This does not happen in native VS Code.
- [ ] I tested this in GitHub Codespaces.
- [ ] This does not happen in GitHub Codespaces.

### Are you accessing code-server over a secure context?

- [ ] I am using a secure context.

**Comment by kLiHz** [comment]
Can you provide more information on your setup and describe your expected outcome in details?

**Comment by zidoshare** [comment]
same to me (pay attention to my access address):

<img width="1752" alt="image" src="https://github.com/coder/code-server/assets/11310504/7c446559-0337-405b-9028-96e2ad52b896">

then I tried to set host: `127.0.0.1:65210 a.editor.localhost`,it works.

<img width="1696" alt="image" src="https://github.com/coder/code-server/assets/11310504/1ba466dc-a2a7-414c-8fdd-4585dc9388e2">

**Comment by code-asher** [comment]
Yeah that functionality uses service workers, and browsers only allow service workers in a [secure context](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts#when_is_a_context_considered_secure), which generally means you need localhost or a domain name and certificate.

But, it is possible to bypass this, for example in Chrome you can use `chrome://flags/#unsafely-treat-insecure-origin-as-secure` and enter the IP address (for example `http://<0.0.0.0>:65210`)

**Comment by zhaowendao30** [comment]
> Yeah that functionality uses service workers, and browsers only allow service workers in a [secure context](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts#when_is_a_context_considered_secure), which generally means you need localhost or a domain name and certificate.
> 
> But, it is possible to bypass this, for example in Chrome you can use `chrome://flags/#unsafely-treat-insecure-origin-as-secure` and enter the IP address (for example `http://0.0.0.0:65210`)

nice!bro!!
