### ISSUE TITLE
[Bug]: Shows blank screen when accessing from public network using VS code's port-forwarding

### ISSUE THREAD

**Issue by yuemin-hu-20231024** [coder/code-server#6634]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome
- Local OS:MacOS
- Remote OS:MacOS
- Remote Architecture:MacOS
- `code-server --version`:`4.20.1 e76afa4a2bf4667a3c9f71bf56ef34b8ad365fbe with Code 1.85.2`

### Steps to Reproduce

1. I used code-server in conjunction with VSC's port-forwarding to gain repo access from remote machine
2.on local(0.0.0.0:8081) it works completely fine without any issue.
3. when i using remote access (something like https://xxxxxx-8081.asse.devtunnels.ms/), after i input the password it just shows a blank screen(see attached screenshot)
4. I tested another forwarded port (next.js server) and it is accessible, so the port forwarding worked fine
5. I also tried LAN(192.168.x.x:8081) on both code-server machine and client machine, and it works without any issue.
6. I also tried using tailscale and it works fine as well.

### Expected

accessible from remote URL

### Actual

shows blank screen

### Screenshot/Video

<img width="1179" alt="image" src="https://github.com/coder/code-server/assets/148832946/31373381-a111-43f0-b6bb-ae0a5dded77f">
<img width="1956" alt="image" src="https://github.com/coder/code-server/assets/148832946/dd7d1ef0-b35b-4fc9-9902-c12e1245cfaa">

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I tested this in native VS Code.
- [ ] This does not happen in native VS Code.
- [ ] I tested this in GitHub Codespaces.
- [ ] This does not happen in GitHub Codespaces.

### Are you accessing code-server over a secure context?

- [X] I am using a secure context.

**Comment by code-asher** [comment]
The logs say the web socket failed to connect.  Is your proxy not set up to proxy web sockets?

**Comment by code-asher** [comment]
Closing as stale but feel free to comment if you come back to this.
