### ISSUE TITLE
[Bug]: Render *.ipynb file as json when openFile with payload in url

### ISSUE THREAD

**Issue by huxianc** [coder/code-server#6642]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome
- Local OS: window 10
- Remote OS:CentOS7
- Remote Architecture:
- `code-server --version`: 4.11

### Steps to Reproduce

1. When open url such as `http://127.0.0.1:8010/?folder=/home/lhdu/kbdev/aistudio-test&payload=[[%22openFile%22,%22vscode-remote:///home/lhdu/kbdev/aistudio-test/b.ipynb%22]]`,sometimes rendered as json
2.Personal speculation: OpenFile behavior is activated earlier than the ipynb extension, or the activation time of the ipynb extension is too long
3.There is a small probability of it appearing when refreshing the browser

### Expected

always render as jupyter-notebook 

### Actual

sometimes render as json

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I tested this in native VS Code.
- [X] This does not happen in native VS Code.
- [ ] I tested this in GitHub Codespaces.
- [ ] This does not happen in GitHub Codespaces.

### Are you accessing code-server over a secure context?

- [X] I am using a secure context.

**Comment by code-asher** [comment]
Could you test this in Codespaces as well?  Seems like the sort of thing that could be an upstream bug.

**Comment by code-asher** [comment]
Closing as stale, but feel free to comment if you come back to this.
