### ISSUE TITLE
[Feat]: In the Code Server service, the webview in my extension plugin cannot be displayed. How to solve it?

### ISSUE THREAD

**Issue by kevinKaikai** [coder/code-server#6657]
![image](https://github.com/coder/code-server/assets/37619768/e20736f6-245e-4620-b34d-980983812ab1)

![image](https://github.com/coder/code-server/assets/37619768/2b5e1049-af20-401e-a5fb-4d35aebd2535)

**Comment by isatis-summer** [comment]
This issue occurs when the browser accesses the code-server without using the HTTPS protocol. The first solution is to set up a reverse proxy and use an HTTPS certificate to solve this issue. The second solution is to enable Chrome's "unsafely-treat-insecure-origin-as-secure" feature, input the domain name, and set it to Enabled.

**Comment by code-asher** [comment]
Closing in favor of the discussion https://github.com/coder/code-server/discussions/6656
