### ISSUE TITLE
[Feat]: Missing assets for darwin arm64

### ISSUE THREAD

**Issue by blotero** [coder/code-server#6659]
## What is your suggestion?

I have seen that assets in the releases do not contain package for darwin 64 (only macos-amd64) as seen in the latest release: https://github.com/coder/code-server/releases/v4.20.1/ why is this?

## Why do you want this feature?

It would be desirable to include package for this target architecture considering that latest Mac machines are all aarch64-darwin

## Are there any workarounds to get this functionality today?

Not sure.

## Are you interested in submitting a PR for this?

Maybe.

**Comment by code-asher** [comment]
We never got around to adding it when it came out.  I might not get to it any time soon, but presumably all we need to do is rename and add a matrix section to the `package-macos-amd64` job to do both `amd64` and `arm64`.

**Comment by amanibhavam** [comment]
Now the release is missing macos-amd64 binaries

code-server v4.23.1 was the last release to publish a macos-amd64 binary https://github.com/coder/code-server/releases/tag/v4.23.1

The version after, v4.89.0, only publishes a macos-arm64 binary https://github.com/coder/code-server/releases/tag/v4.89.0

**Comment by yuchenshi** [comment]
+1 to that. Having a standalone binary will be nice because it doesn't depend on system-wide setup such as homebrew or npm and provide some isolation. Are you willing to accept PRs?

**Comment by yuchenshi** [comment]
Actually, ever since [v4.89.0-rc.1](https://github.com/coder/code-server/releases/tag/v4.89.0-rc.1), there's only `macos-arm64`. There's no more `amd64`. However, the `install.sh` refuses to even attempt the standalone binary if on `macos-arm64`. Shall we flip the check in the script? Or is the intention to have both `arm64` and `amd64` in the longer run?

**Comment by code-asher** [comment]
Very happy to accept PRs!  

I think the reason this happened is that the macOS runner was upgraded and it had been changed to arm64 by GitHub, so I think we need to add a second runner that uses the amd64 architecture, but I have not looked into whether GitHub still has that.

Great point on the `install.sh`, we should change it to use whichever is the right architecture for the host machine, ideally we have both in the long run I think.

**Comment by yuchenshi** [comment]
#6968 to fix the short term of the `install.sh`. @code-asher shall we update this issue title to track the remaining work needed to determine if macos-amd64 is still feasible and update the build config if possible? Or should I open a new issue?

**Comment by code-asher** [comment]
That is awesome thank you!  Good idea, a new issue makes the most sense to me I think, I will go ahead and just do that real quick: https://github.com/coder/code-server/issues/6969
