### ISSUE TITLE
[Feat]: Docker images based on other distributions

### ISSUE THREAD

**Issue by dsseng** [coder/code-server#6661]
## What is your suggestion?
Build more Docker/OCI images using various distributions.

## Why do you want this feature?
Some peoples' workflows are accustomed to a certain distro, personally I like using Fedora for development. It provides more cutting edge build-dependencies and is preferred for me.

## Are there any workarounds to get this functionality today?
I just build images myself using modified version of [code-server Dockerfile](https://github.com/coder/code-server/raw/84ca27278b68150e22d25ec9183a4835239b6e44/ci/release-image/Dockerfile) also installing wanted extra dependencies. I believe the Dockerfile is MIT as well thus fine to modify as long as I keep the copy of the license along with it, sorry if I'm wrong.

## Are you interested in submitting a PR for this?
Yes, I'd be happy to upstream my Dockerfile for Fedora-based code-server if developers approve this. Maybe I could do openSUSE Tumbleweed as well as I use it often as well.

**Comment by dsseng** [comment]
Here's the latest version before I added more abstractions accomodating CLI editors and splitting base out: https://github.com/dsseng/fedora-development-containers/blob/baff02555eec68f70ec55a19867a859029e2a525/Dockerfile.code-server

**Comment by code-asher** [comment]
That looks great!
