### ISSUE TITLE
[Feat]: how to open folder or server path through code server url param

### ISSUE THREAD

**Issue by daodol** [coder/code-server#6662]
how to open folder or server path through code server url param？
for example https://vscode.dev?folder=xxx

**Comment by daodol** [comment]
> code-server also supports the `folder` query parameter. Are you encountering a bug with it?

ok，but I didn't find the full documentation on this and I don't know how to use it

**Comment by code-asher** [comment]
It is mainly meant to be used with `File > Open Folder` from within VS Code, but you can construct it manually by pointing it to any directory on the remote machine.  `https://domain.com?folder=/home/coder/project` for example.

**Comment by code-asher** [comment]
Closing as stale but feel free to comment if you come back to this.

**Comment by code-asher** [comment]
There is no official way to open a file this way.  There is an issue to implement this, but it really should be implemented upstream directly in VS Code: https://github.com/coder/code-server/issues/1964

Someone did figure out a workaround, but I am not sure how well it works.
