### ISSUE TITLE
[Bug]: code-server does not start with error: version `GLIBC_2.25' not found

### ISSUE THREAD

**Issue by amirhosseindavoody** [coder/code-server#6680]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Google Chrome
- Local OS: Windows 11
- Remote OS: SLES_12
- Remote Architecture: x86
- `code-server --version`:  v4.21.1, v4.20.1, v4.19.1

### Steps to Reproduce

1. Install code using install script in Linux environment
2.
3.

### Expected

Open `code-server` from terminal.

### Actual

I get an error regarding GLIBC version. See the logs section below.

I tried older versions of code-server (4.20.1 and 4.19.1) to see if the issue is with the latest release of vscode 1.86 which dropped support for older OS version. But I got the same error.

### Logs

```
➜  Downloads code-server --version                   
/nfs/site/home/adavoody/.local/lib/code-server-4.19.0/lib/node: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /nfs/site/home/adavoody/.local/lib/code-server-4.19.0/lib/node)
/nfs/site/home/adavoody/.local/lib/code-server-4.19.0/lib/node: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /nfs/site/home/adavoody/.local/lib/code-server-4.19.0/lib/node)
/nfs/site/home/adavoody/.local/lib/code-server-4.19.0/lib/node: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /nfs/site/home/adavoody/.local/lib/code-server-4.19.0/lib/node)
```

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I tested this in native VS Code.
- [X] This does not happen in native VS Code.
- [ ] I tested this in GitHub Codespaces.
- [ ] This does not happen in GitHub Codespaces.

### Are you accessing code-server over a secure context?

- [ ] I am using a secure context.

**Comment by code-asher** [comment]
Node was updated to 18 (which raised the minimum glibc) in 4.17.0, so I think you would have to downgrade to at least 4.16.1.

https://github.com/coder/code-server/releases/tag/v4.17.0

> Update to Code 1.82.2. This includes an update to Node 18, which also means
that the minimum glibc is now 2.28. If you need to maintain a lower glibc then
you can take a version of Node 18 that is compiled with a lower glibc and use
that to build code-server (or at a minimum rebuild the native modules).

**Comment by amirhosseindavoody** [comment]
Thanks. This solved the issue.
