### ISSUE TITLE
[Bug]: Terminal closes immediately after opening it since v4.16.1

### ISSUE THREAD

**Issue by Rucadi** [coder/code-server#6686]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: X
- Local OS:
- Remote OS: Centos7 & Ubuntu
- Remote Architecture: x86-64
- `code-server --version`: anything > 4.16.1

### Steps to Reproduce

1. open code-server on the web
2. Open a folder
3. Open a folder again in a new tab seems to help
4. Begin using the terminals, run processses etc...
5. Suddently, when you try to open a terminal, it'll automatically close. For some reason, trying to open 20 terminals or so at the same time makes it so 2-3 survive.
6. killing code-server and opening it again restores functionality

The error that most probably is the culprit:
**Error [CodeExpectedError]: Could not find pty on pty host**

It also occurs with openvscode-server, and I have the same issue with different computes and people, That's the reason I keep using the older v4.16.1 which does not have this issue.

### Expected

The terminal opens.

### Actual

The terminal is killed

### Logs

**Error [CodeExpectedError]: Could not find pty on pty host**

### Does this issue happen in VS Code or GitHub Codespaces?

- [ ] I tested this in native VS Code.
- [ ] This does not happen in native VS Code.
- [ ] I tested this in GitHub Codespaces.
- [ ] This does not happen in GitHub Codespaces.

### Are you accessing code-server over a secure context?

- [ ] I am using a secure context.

**Comment by code-asher** [comment]
Although, you say it does work if you open enough or restart code-server so that must not be it.  I am not sure, in that case.

**Comment by Rucadi** [comment]
> Although, you say it does work if you open enough or restart code-server so that must not be it.  I am not sure, in that case.  Do you have some way for me to reproduce?  A Dockerfile maybe?  If not, check code-server's output and see if anything shows up there.

The glibc problem was already taken care of by compiling node + some dependencies and no errors related to that are present.

I was wondering if node-pty had a regression, since the error log more plausible is the one I put on the first message... I'll try to create a minimum example

**Comment by code-asher** [comment]
Closing as stale but feel free to comment if you come up with a reproduction.

**Comment by nikhilstcorp** [comment]
The issue is not fully resolved. Previously, the terminal would crash on the 5th or 6th instance of the same session. Now, it doesn't crash at all during the first session, regardless of the number of instances. However, it crashes when starting a new (second) session after closing all instances of the first session.
![image](https://github.com/user-attachments/assets/1e3eeb9b-a359-4748-97ea-02d926dbecc7)

**Comment by code-asher** [comment]
Is this on 4.91.1?  I experimented by opening six instances (using the `+`), closing them all, then opening a new one (using Terminal > New Terminal) but it seems to work.

**Comment by nikhilstcorp** [comment]
This was on the version: 

code-server: v4.23.1, 
Code: 1.88.1

I installed it using conda from the conda-forge channel.

**Comment by code-asher** [comment]
Interesting, possibly this was fixed upstream then.  Let me know if it still happens for you with 4.91.1.
