### ISSUE TITLE
[triage]: codeium constantly needs to connect

### ISSUE THREAD

**Issue by neckva** [coder/code-server#6693]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: firefox
- Local OS: ubuntu 23.10
- Remote OS:22.04
- Remote Architecture:amd64
- `code-server --version`:v4.20.1

### Steps to Reproduce

1.open code-server in a new pc
2.go to codeium
3.login in requiered each time

### Expected

login is automatic

### Actual

Hello
I have installed the codeium plugin and it works. The problem is that each time I connect to a new browser, I have to redo the connection procedure, which is quite long, and sometimes doesn't work, because the codeium server assumes that there are several users connected (which is forbidden in the free version). Is there a way of entering the connection key in a hard-coded file so that I don't have to retype it?
thanks

### Are you accessing code-server over a secure context?

- [X] I am using a secure context.

**Comment by code-asher** [comment]
Does this reproduce in Codespaces?  I believe this is expected.  VS Code for the web stores credentials in the browser, so a new browser will require a new login.

**Comment by code-asher** [comment]
Closing as stale (and possibly upstream) but feel free to comment if you come back to this.

**Comment by hnhegde** [comment]
seeing the same issue with Pycharm 2024.2.3 and Codeium 1.20.2. Seen it with few earlier versions of Codeium as well. Anyway to debug / check the logs?
