### ISSUE TITLE
[Bug]: Unable to build code-server from source code. Developer build commands `yarn install` and `yarn watch` failing. 

### ISSUE THREAD

**Issue by toduyemi** [coder/code-server#6695]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome
- Local OS: macOS
- Remote OS: macOS
- Remote Architecture:
- `code-server --version`: 4.21.2

### Steps to Reproduce

1.`git clone https://github.com/coder/code-server.git`
2. `git submodule update --init` - Clone vscode submodule
3. `quilt push -a`
4. `yarn`
5. `yarn watch`

### Expected

Dependencies should install and code-serve should go live at port 8080.

### Actual

Errors are thrown in steps 3 and 4.

### Logs

`yarn global add code-server`:

> Internal Error: code-server@workspace:.: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile
>     at Xx.getCandidates (/Users/temioduyemi/.cache/node/corepack/yarn/4.1.0/yarn.js:205:8149)
>     at Dd.getCandidates (/Users/temioduyemi/.cache/node/corepack/yarn/4.1.0/yarn.js:141:1311)
>     at /Users/temioduyemi/.cache/node/corepack/yarn/4.1.0/yarn.js:210:8409
>     at Ky (/Users/temioduyemi/.cache/node/corepack/yarn/4.1.0/yarn.js:140:53916)
>     at Fe (/Users/temioduyemi/.cache/node/corepack/yarn/4.1.0/yarn.js:210:8389)
>     at async Promise.allSettled (index 0)
>     at async Uc (/Users/temioduyemi/.cache/node/corepack/yarn/4.1.0/yarn.js:140:53244)
>     at async /Users/temioduyemi/.cache/node/corepack/yarn/4.1.0/yarn.js:210:9140
>     at async Qi.startProgressPromise (/Users/temioduyemi/.cache/node/corepack/yarn/4.1.0/yarn.js:140:137284)
>     at async Pt.resolveEverything (/Users/temioduyemi/.cache/node/corepack/yarn/4.1.0/yarn.js:210:7138)

### Screenshot/Video

`yarn`:
<img width="898" alt="Screenshot 2024-02-29 at 1 56 52 AM" src="https://github.com/coder/code-server/assets/63010977/984032ab-8a30-4447-81e6-da3b2fbf40ee">

`yarn watch`: 
<img width="879" alt="Screenshot 2024-02-29 at 1 57 12 AM" src="https://github.com/coder/code-server/assets/63010977/ca3cdfa7-606e-4fae-a4fa-fa7aa639101f">

build.log:
<img width="828" alt="Screenshot 2024-02-29 at 1 58 50 AM" src="https://github.com/coder/code-server/assets/63010977/e27127b8-43f8-4d7a-9805-2fb453510fcc">

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I tested this in native VS Code.
- [X] This does not happen in native VS Code.
- [X] I tested this in GitHub Codespaces.
- [X] This does not happen in GitHub Codespaces.

### Are you accessing code-server over a secure context?

- [X] I am using a secure context.

**Comment by code-asher** [comment]
Oh interesting, is this a new version of yarn without support for `--no-default-rc`?  It seems to be 4.1.0 but we are still using Yarn v1.  We should add the yarn version to the contributing docs.

**Comment by code-asher** [comment]
And I wonder if we can force the version of yarn in the `package.json`, maybe with the `engines` key.
