### ISSUE TITLE
[Feat]: didn‘t support leetcode extension？

### ISSUE THREAD

**Issue by ForsakenDelusion** [coder/code-server#6711]
I hope can add support for leetcode,thanks a lot
![0667A271-4EB5-4332-90BE-5035D9CBA75F](https://github.com/coder/code-server/assets/144082461/15ac045f-a5e2-40ea-9d04-9ebc09b0bbe1)

**Comment by ForsakenDelusion** [comment]
i find that the extension can be installed by vsix

**Comment by code-asher** [comment]
code-server uses open-vsx.org by default so only extensions from there will show up in the search!  You can ask the extension author to submit their extension to Open VSX.
