### ISSUE TITLE
[Bug]: autoDetectColorScheme not being respected

### ISSUE THREAD

**Issue by jasonbentrup** [coder/code-server#6713]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome
- Local OS: Mac OS 14.3.1
- Remote OS: Ubuntu 22.01
- Remote Architecture: AWS m5a.large
- `code-server --version`: 4.18.0 +

### Steps to Reproduce

1. Install code-server 4.18.0 or higher
2. Configure your user settings field with the following:
`{
    "editor.stopRenderingLineAfter" : -1,
    "window.autoDetectColorScheme": true,
    "security.workspace.trust.enabled": false,
    "security.workspace.trust.startupPrompt": "never",
    "security.workspace.trust.untrustedFiles": "open",
    "update.mode": "none",
    "telemetry.telemetryLevel": "off",
    "workbench.statusBar.visible": false,
    "workbench.editorLargeFileConfirmation": 35,
    "workbench.editor.restoreViewState": false
 }`
3. Set your OS to dark mode
4. Start code-server

### Expected

Code-server will load in dark mode

### Actual

Code-server will load in dark mode, then after 2-5 seconds it will switch to light mode.  Going into your OS settings and switching to light mode will do nothing (as code server is already in light mode), but then switching to dark mode will get code-server to switch to dark mode.

### Screenshot/Video

https://github.com/coder/code-server/assets/78042837/f2d69d06-cb4e-499f-96b9-2fc170eb56ab

### Does this issue happen in VS Code or GitHub Codespaces?

- [ ] I tested this in native VS Code.
- [ ] This does not happen in native VS Code.
- [ ] I tested this in GitHub Codespaces.
- [ ] This does not happen in GitHub Codespaces.

### Are you accessing code-server over a secure context?

- [X] I am using a secure context.

### Notes

We do have a few extensions, so I had tested removing all of those extensions first.

**Comment by code-asher** [comment]
I think this is an upstream issue, even in Codespaces it seems to ignore the `window.autoDetectColorScheme` value and always choose whatever theme is the default.

Looks like there have been a few issues reported upstream already: https://github.com/search?q=repo%3Amicrosoft%2Fvscode+auto+detect+theme&type=issues

**Comment by code-asher** [comment]
Closing as an upstream issue.
