### ISSUE TITLE
[Bug]: No way to disable the VSCode custom title bar after updating

### ISSUE THREAD

**Issue by ading2210** [coder/code-server#6718]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Firefox ESR 115
- Local OS: Debian 12
- Remote OS: Debian 12
- Remote Architecture: amd64
- `code-server --version`:
```
1.87.0
e5d145fdf32e82be2a0f8de9a3b05f65b13052b6
x64
```

### Steps to Reproduce

1. Open code-server

### Expected

There should be a way to disable the title bar, as it wastes vertical space that is already taken up by the browser's tab bar. In previous versions of code-server, the custom title bar was not shown by default.

### Actual

There is no way to disable VSCode's built in title bar. Every solution mentioned [here](https://stackoverflow.com/questions/47255696/way-to-disable-the-visual-studio-code-editor-title-bar) does not work. 

The `window.titleBarStyle` setting does not exist in code-server, but in VSCodium, setting this to "native" disables the custom title bar.

### Screenshot/Video

![Screenshot_2024-03-11_11-51-32](https://github.com/coder/code-server/assets/71154407/85f6327f-230d-481d-860c-fe1cf637bf49)

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I tested this in native VS Code.
- [X] This does not happen in native VS Code.
- [ ] I tested this in GitHub Codespaces.
- [ ] This does not happen in GitHub Codespaces.

### Are you accessing code-server over a secure context?

- [X] I am using a secure context.

**Comment by code-asher** [comment]
Huh so this seems to be a bug (or intentional change) upstream.  Normally you can set the menu bar style to compact and disable the command center and the top bar will disappear, and this was working in 1.85.1, but in the latest VS Code it does not work.  Codespaces is still on 1.85.2 so it does not reproduce there at the moment.

It can be reproduce with vscode.dev though.

**Comment by code-asher** [comment]
Wait no if you also disable the layout control in the titlebar then finally the top bar disappears.  My settings:

```
{
    "window.commandCenter": false,
    "workbench.layoutControl.enabled": false
}
```

**Comment by ading2210** [comment]
I just tried those settings and they worked, thanks! I guess the option names just changed between updates.

**Comment by KaKi87** [comment]
Hi,

I need the `titleBarStyle` setting to hide the top bar when using the bottom activity bar, like so on desktop :

<img width="2735" height="1824" alt="Image" src="https://github.com/user-attachments/assets/1cbdd3f9-d2d6-4a51-8226-642afd406d6f" />

Because here's what's happening on web without it :

<img width="2735" height="1824" alt="Image" src="https://github.com/user-attachments/assets/fb3b32c0-0f96-4891-b83e-1f6edcf7c17a" />

Thanks

**Comment by code-asher** [comment]
If I understand correctly, you want code-server to use the native title bar for its menus?

I think that is possible when running as a PWA, but not when running as a browser tab.  Not sure how much work it would be though, or if we would want to maintain such a patch here.

**Comment by KaKi87** [comment]
> you want code-server to use the native title bar for its menus?

No, I just want it to believe it has the native title bar, so that it doesn't display this bar. I can do without the menu.

**Comment by code-asher** [comment]
If you just want to remove the top bar, you should be able to use the settings I posted above.

**Comment by KaKi87** [comment]
Those settings are enough when `workbench.activityBar.location` is set to `default` (left) or `hidden`, but not when it's set to `bottom`, like in the screenshots I shown.

Thanks

**Comment by code-asher** [comment]
Ahhhh I see, so to reproduce the issue:

```
{
    "window.commandCenter": false,
    "workbench.layoutControl.enabled": false,
    "workbench.activityBar.location": "bottom"
}
```

So far I have not found anything that can hide the title bar while the activity bar is `bottom`.  Might have to raise the issue upstream unfortunately.  Whether the best fix is to add a new option or make `titleBarStyle` work in web, I am not sure.

Even zen mode still shows the title bar in this scenario, which is interesting.
