### ISSUE TITLE
[Bug]:When starting the service with the --install-extension command, the code-server process will quickly end itself

### ISSUE THREAD

**Issue by 030525** [coder/code-server#6720]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: chrome
- Local OS: windows
- Remote OS: ubuntu
- Remote Architecture: amd64
- `code-server --version`: 4.22.0 e5d145fdf32e82be2a0f8de9a3b05f65b13052b6 with Code 1.87.0

### Steps to Reproduce

run command with --install-extension like : 
nohup ./code-server --port 5000 --host 0.0.0.0 --auth password  --install-extension 
ms-python.python  > mylog.out 2>&1 &

### Expected

the code-server process should persist

### Actual

code-server suicide in seconds

### Does this issue happen in VS Code or GitHub Codespaces?

- [ ] I tested this in native VS Code.
- [ ] This does not happen in native VS Code.
- [ ] I tested this in GitHub Codespaces.
- [ ] This does not happen in GitHub Codespaces.

### Are you accessing code-server over a secure context?

- [ ] I am using a secure context.

### Notes

remove --install-extension , code-server works again

**Comment by 030525** [comment]
Does anyone know why it happened?
 This happens when I always start the service with the command with --install-extension. Even if I already have these extensions
Or it may be related to the fact that I imported an external configuration file.

**Comment by code-asher** [comment]
`--install-extension` is not a service, it is meant to install the extension then exit (the same behavior as native VS Code and GitHub Codespaces).

You will want something like:

```
./code-server --install-extension ms-python.python > mylog.out 2>&1
nohup ./code-server --port 5000 --host 0.0.0.0 > mylog.out 2>&1 &
```

**Comment by 030525** [comment]
You are right, because the extension only needs to be downloaded once, instead of having --install-extension every time you start the service, so downloading the extension and starting the service should be two commands, and I mistakenly confused them together. I'm sorry that I don't know how to use it
