### ISSUE TITLE
Allow login with token similar to jupyter notebook server

### ISSUE THREAD

**Issue by benjaminum** [coder/code-server#6733]
## What is your suggestion?

Simplify the login procedure by allowing to pass the session password in the url to get similar behavior as clicking on a jupyter link of the form
```bash
Jupyter Server 2.12.5 is running at:
    http://localhost:8888/lab?token=fbf7cc58bbd90a9f172490f5c57201e03ca967efe424090c872b3218110f29fa
```

## Why do you want this feature?

It streamlines the sign in procedure.

## Are there any workarounds to get this functionality today?

```--auth none``` is a workaround but is not secure if there are multiple people working on the same node

## Are you interested in submitting a PR for this?

Yes

**Comment by code-asher** [comment]
Related (kind of a duplicate, but slightly different): https://github.com/coder/code-server/issues/5819

**Comment by code-asher** [comment]
Going to go ahead and close as a duplicate and reword the other issue a bit.
