### ISSUE TITLE
Cannot use any plugin in code-server

### ISSUE THREAD

**Issue by Robert698** [coder/code-server#6743]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Edge
- Local OS: Windows
- Remote OS: Alpine Linux 3.14
- Remote Architecture: X86
- `code-server --version`: 4.22.1

### Steps to Reproduce

1. Use npm 8.10.0 and nodejs 18.19.1 and python 3.10.14 to install code-server and have an error: Command failed
2. Then use "apk add krb5-dev" to fix the installation error and install success
3. Use "code-server" to run success, but when i click git menu it hints that "No source control providers registered."
![code1](https://github.com/coder/code-server/assets/76717035/ac138954-5d0b-4d4d-b784-8d2ad2810e7a)
4. There is an error displayed on code-server "Error relocating /usr/local/lib/node_modules/code-server/lib/vscode/node_modules/@vscode/spdlog/build/Release/spdlog.node: _ZGVZN6spdlog7details2os9thread_idEvE3tid: initial-exec TLS resolves to dynamic definition in /usr/local/lib/node_modules/code-server/lib/vscode/node_modules/@vscode/spdlog/build/Release/spdlog.node"
![code2](https://github.com/coder/code-server/assets/76717035/45930c54-30ab-42c5-80e0-47ad65a68f6d)
5. I tesed java and mysql plugin, they all cannot work and have the similar error above.

### Expected

git and other plugins can work in code-server on alpine linux X86

### Actual

plugins cannot work in code-server on alpine linux X86

### Does this bug reproduce in native VS Code?

No, this works as expected in native VS Code

### Does this bug reproduce in GitHub Codespaces?

No, this works as expected in GitHub Codespaces

### Are you accessing code-server over a secure context?

- [ ] I am using a secure context.

**Comment by Robert698** [comment]
Step to Install:

1. vim /etc/apk/repositries
2. 3.14->3.17
3. apk add nodejs
4. apk add python3
5. apk add alpine-sdk bash libstdc++ libc6-compat
6. apk add npm
7. npm install -g npm@8.10.1
8. apk del npm
9. npm config set python python3
10. apk add krb5-dev
11. npm install --loglevel verbose --global --unsafe-perm code-server

**Comment by lrstanley** [comment]
Given the error, and it being similar to [this SO issue](https://stackoverflow.com/a/70675566/1830159) -- does it work when you install bash into your Alpine image?

**Comment by Robert698** [comment]
I have installed at step 5:apk add alpine-sdk bash libstdc++ libc6-compat
And it was not work at that time.
In my opinion, the problem is this version of code-server is not support X86 Alpine.
Cause I have installed and run with plugin(Extension) successfull in X86_X64 Alpine.

PS: My title is not exactly, the plugin means extensions in vscode

**Comment by code-asher** [comment]
I will wrap this up into https://github.com/coder/code-server/issues/3431
