### ISSUE TITLE
iPad can't use the terminal

### ISSUE THREAD

**Issue by Tidra** [coder/code-server#6746]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser:Safari, Chrome
- Local OS:IPadOS15.1
- Remote OS:Centos7
- Remote Architecture:x86
- `code-server --version`:4.22.1

### Steps to Reproduce

Open Code-Server terminal on Safari and Chrome on iPad

### Expected

The terminal can display normally, the cursor can display, and the input characters can be seen. When the Enter key is pressed, the command can be executed

### Actual

1. Open it on the PC browser, the terminal displays normally, and the input command can be seen
2. But open it on Safari and Chrome on iPad, the terminal display is abnormal, the input character cannot be seen, and the cursor cannot be displayed

### Logs

```shell
the console of web:
this.commands.at is not a function. (In 'this.commands.at(-1)', 'this.commands.at' is undefined)
```

### Does this bug reproduce in native VS Code?

Yes, this is also broken in native VS Code

### Does this bug reproduce in GitHub Codespaces?

Yes, this is also broken in GitHub Codespaces

### Are you accessing code-server over a secure context?

- [X] I am using a secure context.

**Comment by code-asher** [comment]
SInce it reproduces in Codespaces it looks like an upstream issue.  Please file the issue upstream!  Thank you.
