### ISSUE TITLE
Git | Source control extension always stuck on running or processing for too long blocking other tools

### ISSUE THREAD

**Issue by jomoflash** [coder/code-server#6747]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome, Version : 23.0.6312.106 (Official Build) (64-bit) 
- Local OS: Windows 10
- Remote OS: Ubuntu 22.04 LTS
- Remote Architecture: amd64 | x64
- `code-server --version`: v4.21.1

### Steps to Reproduce

1. This happens intermittently 
2. After a long period working on a project

### Expected

Git or inbuilt Source control extension should run immediately, and not block other activities like file creation and other extensions. 

### Actual

There is no visibility into what the source control extension is actually running for too long, or I have a knowledge gap on identifying the cause from the logs. Issue occurs even on small git based projects with little activities. requiring me to restart code-server every time which still doesn't help.
Git gutter or Source Control gutter also stops working when issue occurs.

### Screenshot/Video

![image](https://github.com/coder/code-server/assets/15862254/3610a35c-5aae-4329-b906-e5eb0e02521a)

### Does this bug reproduce in native VS Code?

No, this works as expected in native VS Code

### Does this bug reproduce in GitHub Codespaces?

I did not test GitHub Codespaces

### Are you accessing code-server over a secure context?

- [X] I am using a secure context.

**Comment by code-asher** [comment]
If you are able to test on Codespaces that would help us figure out whether this is an upstream issue with VS Code itself or an issue with code-server.

Does it happen without any extensions installed?

Does anything here help?  https://stackoverflow.com/questions/65658602/file-operations-taking-long-time-receiving-running-file-save-delete-create

There is also a `files.participants.timeout` setting that you could experiment with.

I am not sure if there is a good way to debug file participants, but the VS Code folks upstream might have some ideas.

**Comment by jomoflash** [comment]
I'll go ahead and close this issue, issue is resolved after disabling all other extensions. 

I would also appreciate if anyone can help with tips on identifying the culprit, possibly log watching or profiling extensions.

**Comment by code-asher** [comment]
You might have to use trial-and-error, test one extension at a time.

But if you run with `--log verbose` you will get a lot more output, so maybe something there will be useful.  You can see it on stdout or in `~/.local/share/code-server/logs` or in the `Output` panel inside VS Code (there is a dropdown for different logs in the Output panel, check them all).

One suggestion is when this happens, type `Show Running Extensions` into the command palette, and see if any of the extensions say they are inactive (https://stackoverflow.com/questions/60271767/running-save-participants-runs-forever-on-file-save).

Also, at the bottom you see where it says `Creating na.js`?  I wonder if you hover over or click that whether it tells you anything else?
