### ISSUE TITLE
extension request

### ISSUE THREAD

**Issue by nikhildevshatwar** [coder/code-server#6760]
As suggested in https://github.com/coder/code-server/discussions/2345

Asking for following extensions to be added in the code-server gallery

ms-vscode.cpptools-extension-pack
ms-python.vscode-pylance 
zachflower.uncrustify
luveti.kconfig

**Comment by code-asher** [comment]
code-server uses Open VSX (https://open-vsx.org/) by default; please ask the extension authors to submit their extensions there!

**Comment by code-asher** [comment]
I will update that discussion as well, thank you for bringing it to my attention.
