### ISSUE TITLE
Jupyter ipynb file cannot work on iPad, but iphone displays properly. I have already configed https for code-server.

### ISSUE THREAD

**Issue by xsw300** [coder/code-server#6761]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Edge/Chrome/Safari/Firefox
- Local OS: IOS 17.4.1 on iPad Pro 2018
- Remote OS: Ubuntu Server 22.04 LTS 64bit
- Remote Architecture:
- `code-server --version`: 4.23.0

### Steps to Reproduce

1. Config https for code-server.
2. Open code-server on Edge/Chrome/Safari/Firefox
3. Install extension Jupyter and Python
4. Tap any ipynb file

### Expected

Ipynb should display properly on iPad as same as iPhone or android devices.

### Actual

I have already configured https for code-server. I want to edit jupyter script on code-server. But all my devices e.g. android, pc, even iPhone pro 11 can load ipynb properly but iPad pro.
Ipynb files stuck loading on iPad as if I haven't config https for code server.

### Logs

```shell
No response
```

### Screenshot/Video

No response

### Does this bug reproduce in native VS Code?

No, this works as expected in native VS Code

### Does this bug reproduce in GitHub Codespaces?

I did not test GitHub Codespaces

### Are you accessing code-server over a secure context?

- [ ] I am using a secure context.

**Comment by code-asher** [comment]
Can you get the logs from the browser console?  I suspect a browser issue.

**Comment by xsw300** [comment]
> Can you get the logs from the browser console? I suspect a browser issue.

![20240418-112308](https://github.com/coder/code-server/assets/130330743/40f06202-4271-4928-a175-07d9a5990b15)
This is the logs from my iPad. I used a extension called Web Inspector for capturing it. 

![2024-04-18](https://github.com/coder/code-server/assets/130330743/8a9f6b60-5feb-4c55-9c20-9b75eb895a11)
This is the logs from my pc.

I found out that the log 'Jupyther Notebook Renderer actived' only shows on pc.

**Comment by code-asher** [comment]
Thank you!  That `null` error seems weird but I have no idea if it is related.  I was hoping to see something more specific, but no luck.

Could you try Codespaces and see if the same thing happens there?  If it does, I think we will need to open an issue with the extension or VS Code.

**Comment by code-asher** [comment]
Closing as stale but feel free to comment if you come back to this.

**Comment by wsl-fd** [comment]
I encountered the same issue here. After some tests, I found that v4.14.1 is the last version which can display Jupyther notebooks normally on my iPad. 

My device: iPad Pro(M1) iOS 16.2

*Tested versions:

WORKING:
- 4.6.1
- 4.13.0
- 4.14.1

NOT WORKING:
- 4.15.0
- 4.17.1
- 4.89.0
- 4.99.3(latest)

**Comment by code-asher** [comment]
We should probably try to reproduce in Codespaces then report to VS Code.
