### ISSUE TITLE
About sharing the same extension dir for different sytem platform

### ISSUE THREAD

**Issue by dxkrs** [coder/code-server#6762]
## Why do you want this feature?
I set a code-server dir which can be mounted in different docker containers and can run code-server in every container through my running script. The Data dir and Extension dir also be mounted in different containers so that they can use the same user setting and same extensions.
However, I have found some problem. Some extensions in different system have different install pack. Most of extensions targetPlatform is "universal", but some of them need the "alpine" when runing in the container which base on the alpine image.

## What is your suggestion?
I don't know what the best solution to this situation. For now I just can mount different extensions dir in different containers, even if most of extensions is same.

**Comment by code-asher** [comment]
Extension loading is all handled in VS Code so I am not sure there is anything we can do here from code-server.

You could open an issue upstream, but I suspect they might tell you to use settings sync instead, but settings sync does not work with code-server last I heard.

**Comment by dxkrs** [comment]
I think this requirement is difficult to explain the use scene of vscode https://github.com/microsoft/vscode/issues/210714#event-12727943778  , because vscode mainly serves local, but code-server serves remote.

**Comment by code-asher** [comment]
Yeah, that is tricky.  You can run VS Code as a remote over the web with `code serve-web` though, without using code-server at all.  code-server just adds some patches to that.

**Comment by code-asher** [comment]
I will close for now since I think such a large change to VS Code is out of scope for code-server.
