### ISSUE TITLE
4.23.1 breaks within selfhosted coder instance

### ISSUE THREAD

**Issue by TheZoker** [coder/code-server#6767]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Brave 
- Local OS: Windows 11
- Remote OS: Coder.com
- Remote Architecture: 
- `code-server --version`: 4.23.1

### Steps to Reproduce

1. Update code-server version from 4.23.0 to 4.23.1

### Expected

Working

### Actual

Not working

### Does this bug reproduce in native VS Code?

This cannot be tested in native VS Code

### Does this bug reproduce in GitHub Codespaces?

No, this works as expected in GitHub Codespaces

### Are you accessing code-server over a secure context?

- [ ] I am using a secure context.

### Notes

I upgraded code-server from 4.23.0 to 4.23.1 within my coder.com instance (using this module: https://registry.coder.com/modules/code-server). 

When I now start my workspace, I get this error:
```
gzip: stdin: invalid compressed data--crc error
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Failed to install code-server: Ubuntu 23.10
Installing v4.23.1 of the amd64 release from GitHub.
+ Reusing ~/.cache/code-server/code-server-4.23.1-linux-amd64.tar.gz
+ mkdir -p /tmp/code-server
+ mkdir -p /tmp/code-server/lib /tmp/code-server/bin
+ tar -C /tmp/code-server/lib -xzf ~/.cache/code-server/code-server-4.23.1-linux-amd64.tar.gz
```

When I downgrade again to 4.23.0 everything works fine.

**Comment by matifali** [comment]
This looks related to https://github.com/coder/coder/issues/12790#issuecomment-2038037832.
We fixed it by explicitly setting `--host 127.0.0.1` in https://github.com/coder/modules/pull/216

**Comment by TheZoker** [comment]
Hmm I'm using version 1.0.12 of that module, which should already contain that fix, right?

**Comment by code-asher** [comment]
Are you able to download and extract https://github.com/coder/code-server/releases/download/v4.23.1/code-server-4.23.1-linux-amd64.tar.gz on that remote machine?  And does it happen consistently?  I wonder if it was some network blip that corrupted the file.

**Comment by code-asher** [comment]
Since it is installing from cache you might have to delete `~/.cache/code-server/code-server-4.23.1-linux-amd64.tar.gz` before trying again.  Possibly we need to add a checksum to the install script.

**Comment by TheZoker** [comment]
Yes removing the cache solved the issue. Thanks!
