### ISSUE TITLE
vscode server existing recall is not working

### ISSUE THREAD

**Issue by xucongyong** [coder/code-server#6771]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser:chrome
- Local OS:ubuntu
- Remote OS:ubuntu
- Remote Architecture:
- `code-server --version`:v4.23.1
Code: 1.88.1
Date: 2024-04-15T23:01:57.805Z (1 wk ago)
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36

### Steps to Reproduce

1. install  extension **recall**
2.write markdown file

```markdown
---
recall: header
---

# “Good”、“nice”、“fine” “well” 

*the dog is very good
* She speaks English very well
* That is a nice dress
* She is a fine cook
```

* click recall button

### Expected

show recall 

### Actual

![not_work](https://github.com/coder/code-server/assets/22570151/59969b72-f07a-4038-8661-8076fa072fda)
not workd

### Does this bug reproduce in native VS Code?

Yes, this is also broken in native VS Code

### Does this bug reproduce in GitHub Codespaces?

Yes, this is also broken in GitHub Codespaces

### Are you accessing code-server over a secure context?

- [ ] I am using a secure context.

**Comment by code-asher** [comment]
You will need to use using a secure context (localhost or HTTPS).  It looks like this extension uses web views, and VS Code uses `crypto.subtle` in those, which browsers will only let you use in available in secure contexts.
