### ISSUE TITLE
iPad safari: rust project: click `run` or `debug` button not working

### ISSUE THREAD

**Issue by kzhui125** [coder/code-server#6786]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Safari
- Local OS: iPad
- Remote OS: macOS aarch64
- `code-server --version`: 4.22.1 760d1318e98945d05133c6121f99541ca7a39bf8 with Code 1.87.2

### Steps to Reproduce

1. open an rust project.
2. press `run` or `debug` button

### Expected

<img width="707" alt="image" src="https://github.com/coder/code-server/assets/11925432/67141a69-9280-4aa0-98a4-8d62ff207bf8">

<img width="522" alt="image" src="https://github.com/coder/code-server/assets/11925432/6b01b448-4849-412c-b927-7eaccc7d3e7f">

### Actual

task is not executed.

### Does this bug reproduce in native VS Code?

No, this works as expected in native VS Code

### Does this bug reproduce in GitHub Codespaces?

I did not test GitHub Codespaces

### Are you accessing code-server over a secure context?

- [ ] I am using a secure context.

**Comment by code-asher** [comment]
Does this happen in Codespaces?  It sounds more likely to be a bug with VS Code than with code-server, at first glance, but not impossible.

**Comment by code-asher** [comment]
Closing as stale but feel free to comment if you come back to this.
