### ISSUE TITLE
Update Node.js version

### ISSUE THREAD

**Issue by ksacc** [coder/code-server#6787]
## What is your suggestion?
https://github.com/coder/code-server/blob/main/.node-version: Please update node.js version to 22.1.0 from 18.18.2

## Why do you want this feature?
For compatibility 

## Are there any workarounds to get this functionality today?
I want to use this with code tunnel

## Are you interested in submitting a PR for this?
No

**Comment by code-asher** [comment]
We use the version used by VS Code: https://github.com/microsoft/vscode/blob/main/remote/.yarnrc so unfortunately we are not able to do anything here.

It is possible to run code-server with your own version of Node, but we cannot guarantee compatibility.
