### ISSUE TITLE
Remove the first "code-server" in the window title (in PWA)

### ISSUE THREAD

**Issue by zanminkian** [coder/code-server#6788]
## What is your suggestion?

<img width="1190" alt="image" src="https://github.com/coder/code-server/assets/35495628/81afb560-b0cb-4c17-a7c5-5ce10e78c0a8">
<img width="1190" alt="image" src="https://github.com/coder/code-server/assets/35495628/807aadd4-49f6-46f5-ac01-809b7912c88b">

Please refer the screenshots above.

## Why do you want this feature?

The beginning "code-server" makes me confused. It disturbs me so I can't distinguish each PWA windows quickly.
 
## Are there any workarounds to get this functionality today?

Manually editing `window.title` in settings.json.

## Are you interested in submitting a PR for this?

Sorry, currently no.

**Comment by bilogic** [comment]
What browser are you using?

**Comment by zanminkian** [comment]
@bilogic Edge

**Comment by zanminkian** [comment]
Maybe this issue belongs to Chromium or Edge.
