### ISSUE TITLE
Serious Bug

### ISSUE THREAD

**Issue by 18392152392** [coder/code-server#6792]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser:
- Local OS:
- Remote OS:
- Remote Architecture:
- `code-server --version`:

### Steps to Reproduce

1.  I download the code-server4.23.1，then I copy it to my centos7.9
2.  But when I execute ./code-server --port 3000，It doesn't work
3.  the error is version `GLIBCXX_3.4.21' not found
4.  I was urgent to use this version， How to do？my glibc can not update

### Expected

code-server4.23.1 can normally use

### Actual

always

### Does this bug reproduce in native VS Code?

Yes, this is also broken in native VS Code

### Does this bug reproduce in GitHub Codespaces?

Yes, this is also broken in GitHub Codespaces

### Are you accessing code-server over a secure context?

- [ ] I am using a secure context.

**Comment by code-asher** [comment]
code-server does not support CentOS 7 because Node does not support it (because the version of glibc it has is too old).  You will need to use a newer version of CentOS or compile code-server yourself.
