### ISSUE TITLE
Version 21 support

### ISSUE THREAD

**Issue by 001SM** [coder/code-server#6800]
yarn install v1.22.19
[1/5] Validating package.json...
error code-server@0.0.0: The engine "node" is incompatible with this module. Expected version "18". Got "21.6.2"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by code-asher** [comment]
We follow the version used in VS Code.  Once they update, we will too!  https://github.com/microsoft/vscode/blob/1.89.1/remote/.yarnrc
