### ISSUE TITLE
I want to restrict the use and installation of some plug-ins in the plug-in market. How can I do this?

### ISSUE THREAD

**Issue by Kiss736921** [coder/code-server#6813]

**Comment by code-asher** [comment]
I think the only way would be to run your own marketplace (https://github.com/coder/code-marketplace) and only put the extensions you want to support in there.

**Comment by sevetseh28** [comment]
@code-asher is it possible to disable the marketplace at all using code-server? I couldn't find any option for it in the CLI args. Thanks!

**Comment by code-asher** [comment]
There is no bespoke setting for it, but you could accomplish this with `EXTENSIONS_GALLERY={}` .

**Comment by sevetseh28** [comment]
Yup! that worked, thank you!
