### ISSUE TITLE
Issues with gpt plugins 

### ISSUE THREAD

**Issue by Badlee2020** [coder/code-server#6814]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Firefox/chrome 
- Local OS: Windows 
- Remote OS: docker image
- Remote Architecture:
- `code-server --version`: latest

### Steps to Reproduce

1. Run docker image
2. Nginx proxy setup with certificate 
3. vscode_openai plugin install
4. Configure

### Expected

That the plugin should work as in vscode

### Actual

Plugin installs, can be configured, chat started. Shows in the debug window that a response is received, but in the chat window no response is shown.

### Logs

```shell
No relevant logs can be found.
```

### Does this bug reproduce in native VS Code?

No, this works as expected in native VS Code

### Does this bug reproduce in GitHub Codespaces?

I did not test GitHub Codespaces

### Are you accessing code-server over a secure context?

- [X] I am using a secure context.

### Notes

As far as my testing goes, I have installed Code-Server locally, various images, issue persists for the last few months. Other gtp extensions also have issues working with Code-Server too. For example codegpt, it just shows connection refused to local host.

**Comment by code-asher** [comment]
Sorry for the late reply.  I tried it out and yeah, it looks like the extension is connecting to localhost.  It needs to use the proxy instead, since of course localhost will not work when connecting to a remote.
