### ISSUE TITLE
Specifyiong http_proxy related settings has no effect.

### ISSUE THREAD

**Issue by JunNakahara** [coder/code-server#6815]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser:  Chrome, Safari
- Local OS:  macOS, Windows
- Remote OS:  Debian, Ubuntu, any.
- Remote Architecture:  amd64
- `code-server --version`:  4.12.0 through 4.89.1

### Steps to Reproduce

1. Launch Code-Server ver **4.12.0 or later**.
2. Open Settings and search `proxy`.
3. Find `Http: proxy (Aplies to all profiles)` sectin in **User** tab.
4. Put non-existent proxy server address. i.e. `http://unusable.proxy:8888`.
5. Now open Extensions panel, attempt to install any extension.

### Expected

- Installation should **FAIL** due to connection error or timeout caused by wrong http_proxy settings.

### Actual

Extensions can be installed successfully without any problem. But it's wrong behavior because code-server shell doesn't respect to http_proxy settings.

---

At above Step 4, specified `Http: Proxy` value will be stored in ~/.local/share/code-server/**User**/settings.json.  But ver 4.11.0 or before the settings was listed in **Remote** tab, and values were stored in ~/.local/share/code-server/**Machine**/settings.json.

I also noticed that code-server (ver 4.12.0 or later) shell looks still internally referencing those http_proxy related settings in .../**Machine**/settings.json.  I mean if you manually put below to .../**Machine**/settings.json, code-server will start to fail installing Extensions, expectedly.

```json
{
    "http.proxy": "http://unusable.proxy:8888"
}

```

| CS ver | http.proxy in Tab | storing settings.json path | referencing settings.json |
| --- | --- | --- | --- |
| 4.11.0 or before | Remote | ~/.local/share/code-server/Machine/settings.json | .../Machine/ |
| 4.12.0 to 4.89.1 | User | ~/.local/share/code-server/User/settings.json | .../Machine/ |

- This applies to other proxy related settings like `http.proxyStrictSSL` and/or `http.proxySupport`.
- I've tested past builds and identified it's an issue since ver 4.12.0 or later builds.

### Screenshot/Video

![image](https://github.com/coder/code-server/assets/39406902/c6905f77-0ecc-442f-be9f-8f92872c85ac)
![image](https://github.com/coder/code-server/assets/39406902/f3f0d0dc-0ce9-4eeb-8e87-241e4de27ea7)

### Does this bug reproduce in native VS Code?

No, this works as expected in native VS Code

### Does this bug reproduce in GitHub Codespaces?

I did not test GitHub Codespaces

### Are you accessing code-server over a secure context?

- [X] I am using a secure context.

### Notes

- I'm launching code-server installed docker container on remote server, and connect to it from local.
- I've not passing any proxy related Env variables at launch.

**Comment by code-asher** [comment]
Thorough debugging!  I think this might be an unintentional bug resulting from when they split user settings and remote settings and moved user settings into browser storage.  Most likely it will need to be fixed upstream, is my guess.

**Comment by code-asher** [comment]
Closing for now since it appears to be an upstream issue.
