### ISSUE TITLE
Have not go to definition in the mouse right key

### ISSUE THREAD

**Issue by gabrielpondc** [coder/code-server#6816]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Safari
- Local OS: Ubuntu 24.04
- Remote OS: Mac os 14.05
- Remote Architecture:
- `code-server --version`: 

### Steps to Reproduce

1. open code-server in Safari
2. choose python file
3. pause the mouse right key

### Expected

<img width="802" alt="image" src="https://github.com/coder/code-server/assets/26787778/7b255169-a644-42cb-b2a3-a7d6c788267b">

### Actual

![image](https://github.com/coder/code-server/assets/26787778/dd19f183-cbbd-4c0a-864c-b57eea5e1100)

### Does this bug reproduce in native VS Code?

No, this works as expected in native VS Code

### Does this bug reproduce in GitHub Codespaces?

No, this works as expected in GitHub Codespaces

### Are you accessing code-server over a secure context?

- [x] I am using a secure context.

**Comment by zengziru** [comment]
I have the same question!

**Comment by code-asher** [comment]
Does it work if you use a secure context?  I wonder if this is one of those features that use a service worker, which only work in secure contexts.

Are there any errors in the browser console or in the extension host logs?

**Comment by gabrielpondc** [comment]
Sorry, I didn't notice the secure context option before. I have now used a secure context, but it still doesn't work.

**Comment by code-asher** [comment]
Ah OK.  Did you see any errors in the logs?

I tried to reproduce by installing the Python extension and then creating a Python file but it is working for me.

I am using Firefox though.  :thinking:

**Comment by gabrielpondc** [comment]
There are no errors in the logs also, But i have installed the code tunnel before, I am not sure that is it reason due to this problem but every thing that work for code-server i deleted and reinstall the code server and Python extension and then creating a Python file it's works
