### ISSUE TITLE
"Debug and Run" Button doesn't recognize predefined interpreter in settings.json and selects a different one

### ISSUE THREAD

**Issue by atheo89** [coder/code-server#6835]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome/firefox
- Local OS: fedora
- Remote OS: fedora
- Remote Architecture: amd64
- `code-server --version`:  4.22.0
- `ms python`: v2024.2.1

### Steps to Reproduce

1.  Launch code server  
2.  Install `ms-python` extension
3. Set on settings.json your preferred interpreter `"python.defaultInterpreterPath": "/path/to/different/interpreter"` 
4. Reload Window
4. Create a test python file 
5. Press `Run >` icon on the top right.  It will run your file without issue using the predefined interpreter. 
6. Now press on `Run and Debug`  and  see on the bottom right banner the in the python section use a different interpreter from the one that we pre defined. 

### Expected

The "Run and Debug" button to use the python interpreter that is been defined on the settings.json file by the user. 

### Actual

"Debug and Run" Button doesn't recognize predefined interpreter in settings.json and selects a different one, in contrary the Run icon on top left on the screen works as expected. 

### Does this bug reproduce in native VS Code?

I did not test native VS Code

### Does this bug reproduce in GitHub Codespaces?

I did not test GitHub Codespaces

### Are you accessing code-server over a secure context?

- [X] I am using a secure context.

**Comment by code-asher** [comment]
I would guess this needs to be filed with the extension, but we should test VS Code and Codespaces to make sure it is not somehow a problem in code-server.

**Comment by atheo89** [comment]
Thank you for your reply @code-asher! 
I thought the same later on and i opened a question on python extension repo. https://github.com/microsoft/vscode-python-debugger/issues/363

**Comment by code-asher** [comment]
I will close this for now since I think there is nothing we can fix on code-server's side, but we can reopen if that changes.
