### ISSUE TITLE
Unexpected white bar at top of page (making the bottom panel obscured)

### ISSUE THREAD

**Issue by ChristLBUPT** [coder/code-server#6847]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome (version 126)
- Local OS: macOS Ventura 13.6.7
- Remote OS: CentOS 7.6
- Remote Architecture: amd64
- `code-server --version`: 4.11.0

### Steps to Reproduce

1. Run code server on the remote machine (without SSL certificate)
2. Forward remote port to a local port using ssh port forwarding
3. Visit forwarded local port  in chrome browser
 

### Expected

A normal code-server page is rendered.

### Actual

Strange white bar occurred on top of the page, "squashing" the code-server window entirely downwards and making the bottom panel partly obscured, like what is shown in the screenshot pasted below.

### Screenshot/Video

<img width="1171" alt="code-server-error" src="https://github.com/coder/code-server/assets/45749289/a3289fdf-94ed-4c76-bc2c-42c2b66a2c0a">

### Does this bug reproduce in native VS Code?

No, this works as expected in native VS Code

### Does this bug reproduce in GitHub Codespaces?

No, this works as expected in GitHub Codespaces

### Are you accessing code-server over a secure context?

- [ ] I am using a secure context.

### Notes

Currently, I suspect that this has something to do with the version of the Chrome browser since this had never occurred until today. Since the only thing that might happen today is the automatic update of google chrome, together with the fact that I'm using a relatively old version of code-server, I suppose that it has something to do with versions.

**Comment by code-asher** [comment]
Yeah if it works in Codespaces then it has probably been fixed and you will need to update.

**Comment by code-asher** [comment]
I will mark it as upstream for now, but if updating does not fix it let me know and we can reopen.

**Comment by ChristLBUPT** [comment]
> I will mark it as upstream for now, but if updating does not fix it let me know and we can reopen.

Hi, thanks for replying. Actually this problem is settled automatically and I did nothing to my code-server installation. Maybe there's something about the Chrome browser, and it's fixed along with its update.
