### ISSUE TITLE
`Error relocating /home/venom/.local/lib/code-server-4.90.2/lib/node: fcntl64: symbol not found` on Alpine Linux

### ISSUE THREAD

**Issue by VenomousSteam81** [coder/code-server#6850]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Firefox
- Local OS: PostmarketOS (Based on Alpine)
- Remote OS: Same as above
- Remote Architecture: Arm64/aarch64
- `code-server --version`: `Error relocating /home/venom/.local/lib/code-server-4.90.2/lib/node: fcntl64: symbol not found`

### Steps to Reproduce

1. Install `code-server`
2. Run `code-server`

### Expected

Code server runs normally

### Actual

The console outputs `Error relocating /home/venom/.local/lib/code-server-4.90.2/lib/node: fcntl64: symbol not found`

### Logs

```shell
`Error relocating /home/venom/.local/lib/code-server-4.90.2/lib/node: fcntl64: symbol not found`
```

### Does this bug reproduce in native VS Code?

This cannot be tested in native VS Code

### Does this bug reproduce in GitHub Codespaces?

I did not test GitHub Codespaces

### Are you accessing code-server over a secure context?

- [ ] I am using a secure context.

### Notes

I'm assuming that this is just an issue with Alpine altogether as native VSCode also doesn't run

**Comment by VenomousSteam81** [comment]
Update: I installed the `nodejs` package, made a backup of the `node` file thats giving me problems, and copied the `node` file that I installed to the one that comes with `code-server`. This seems to work. It's probably not the safest option, but hey, whatever works!

**Comment by VenomousSteam81** [comment]
Now I'm having another issue where the builtin terminal won't work. It just outputs ` *  Restarting the terminal because the connection to the shell process was lost... `.

**Comment by code-asher** [comment]
Did you install it from GitHub releases or something?  If so, yeah those are not compiled for Alpine.  You will need to do two things:

1. Replace the Node binary (which you already did)
2. Recompile all the native Node modules (it should be enough to run `npm rebuild` in both the root and `lib/vscode` directories)

Building the modules requires a bunch of dependencies and can take a while.  Our docs are a bit out of date here but I think you need:
```
apk add alpine-sdk bash libstdc++ libc6-compat krb5-dev
npm config set python python3
```

Although, some folks are having issues with this, so it might not work: https://github.com/coder/code-server/issues/6846

Related: https://github.com/coder/code-server/issues/3431

**Comment by VenomousSteam81** [comment]
> Did you install it from GitHub releases or something? If so, yeah those are not compiled for Alpine. You will need to do two things:

I used the install script.
I think I will just recompile, since I already have it installed. But if it doesn't work, I will post here. Thank you!

**Comment by code-asher** [comment]
Closing for now but feel free to add information and we can reopen.
