### ISSUE TITLE
Are there any query parameters available for `goto a specific file`?

### ISSUE THREAD

**Issue by shezhangzhang** [coder/code-server#6852]
Like `folder=aaa&file=readme.md` or something? (just going to the specific folder is not enough for my scenario)

<img width="778" alt="image" src="https://github.com/coder/code-server/assets/26793777/5e7b8511-b43d-4642-93a9-909dcb5ec3dc">

**Comment by shezhangzhang** [comment]
Which existing issue did it duplicate? I couldn't find it.

**Comment by code-asher** [comment]
It might mean this issue: https://github.com/coder/code-server/issues/1964

**Comment by shezhangzhang** [comment]
Is this issue still unresolved?

**Comment by code-asher** [comment]
Yep, no updates to the issue.  I think it is unlikely we will patch this on code-server's side, it would be much better to add the feature upstream to VS Code itself.

**Comment by shezhangzhang** [comment]
Got it, thank you for your reply.
