### ISSUE TITLE
No web acces

### ISSUE THREAD

**Issue by Zerbaib** [coder/code-server#6860]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Brave
- Local OS: Windows 11
- Remote OS: Ubuntu 22.04 lxc
- Remote Architecture: amd64
- `code-server --version`: 4.90.3

### Steps to Reproduce

1. root@vscode-srv:~# curl -fOL https://github.com/coder/code-server/releases/download/v4.90.3/code-server_4.90.3_amd64.deb
2. root@vscode-srv:~# dpkg -i code-server_4.90.3_amd64.deb
3. root@vscode-srv:~# useradd hugoh
4. root@vscode-srv:~# passwd hugoh
5. root@vscode-srv:~# chsh hugoh
6. root@vscode-srv:~# systemctl enable --now code-server@hugoh

### Expected

There is no error so idk

### Actual

no change idk why

### Logs

```shell
* code-server@hugoh.service - code-server
     Loaded: loaded (/lib/systemd/system/code-server@.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2024-06-24 12:57:28 UTC; 9min ago
   Main PID: 510 (node)
      Tasks: 22 (limit: 47714)
     Memory: 86.5M
        CPU: 828ms
     CGroup: /system.slice/system-code\x2dserver.slice/code-server@hugoh.service
             |-510 /usr/lib/code-server/lib/node /usr/lib/code-server
             `-529 /usr/lib/code-server/lib/node /usr/lib/code-server/out/node/entry

Jun 24 12:57:28 vscode-srv systemd[1]: Started code-server.
Jun 24 12:57:28 vscode-srv code-server[510]: [2024-06-24T12:57:28.753Z] info  Wrote default config file to /home/hugoh/.config/code-server/config.yaml
Jun 24 12:57:29 vscode-srv code-server[510]: [2024-06-24T12:57:29.117Z] info  code-server 4.90.3 26c763485b9101fcae2ce56fc0903f0e2d48abe3
Jun 24 12:57:29 vscode-srv code-server[510]: [2024-06-24T12:57:29.118Z] info  Using user-data-dir /home/hugoh/.local/share/code-server
Jun 24 12:57:29 vscode-srv code-server[510]: [2024-06-24T12:57:29.127Z] info  Using config file /home/hugoh/.config/code-server/config.yaml
Jun 24 12:57:29 vscode-srv code-server[510]: [2024-06-24T12:57:29.127Z] info  HTTP server listening on http://127.0.0.1:8080/
Jun 24 12:57:29 vscode-srv code-server[510]: [2024-06-24T12:57:29.127Z] info    - Authentication is enabled
Jun 24 12:57:29 vscode-srv code-server[510]: [2024-06-24T12:57:29.127Z] info      - Using password from /home/hugoh/.config/code-server/config.yaml
Jun 24 12:57:29 vscode-srv code-server[510]: [2024-06-24T12:57:29.127Z] info    - Not serving HTTPS
Jun 24 12:57:29 vscode-srv code-server[510]: [2024-06-24T12:57:29.127Z] info  Session server listening on /home/hugoh/.local/share/code-server/code-server-ipc.sock
```

### Screenshot/Video

![image](https://github.com/coder/code-server/assets/81523999/e895a88d-a360-4806-9e29-7ccd30dcfedc)
![image](https://github.com/coder/code-server/assets/81523999/66ee8cf4-b9d6-412a-93fd-59aae50622dc)
![image](https://github.com/coder/code-server/assets/81523999/5be1f196-e7b2-444c-b752-dd370941b613)
![image](https://github.com/coder/code-server/assets/81523999/247db2c9-5447-4edc-bf1b-65a42c2be1a2)

### Does this bug reproduce in native VS Code?

I did not test native VS Code

### Does this bug reproduce in GitHub Codespaces?

I did not test GitHub Codespaces

### Are you accessing code-server over a secure context?

- [ ] I am using a secure context.

**Comment by benz0li** [comment]
`HTTP server listening on http://127.0.0.1:8080/` = `code-server` is not exposed to the public

*Never* expose web services unencrypted. It also breaks some functionality of `code-server`.

**Comment by benz0li** [comment]
Put a reverse proxy in front of your `code-server`/'web service' that also does TLS termination.  
ℹ️ For further information, see https://coder.com/docs/code-server/guide#expose-code-server

**Comment by Zerbaib** [comment]
my proxy encrypt the server
internet -> https -> my proxy -> http -> code-server

**Comment by Zerbaib** [comment]
how can i add a local cert
for this ?

**Comment by benz0li** [comment]
> my proxy encrypt the server

You do not require a local cert then.

**Comment by benz0li** [comment]
Where is "my proxy" located? On the same server as `code-server`?

If not, you must expose `code-server` on IP `0.0.0.0`.  
👉 Only do this in *private networks* that are **not** accessible *directly* from the internet.

**Comment by Zerbaib** [comment]
my proxy has local addr ``192.168.0.100`` (on a docker)
my code-server addr is ``192.168.0.104``

in local i have this
![image](https://github.com/coder/code-server/assets/81523999/c290ad40-6442-4ff2-bd89-b4be6474b877)

**Comment by Zerbaib** [comment]
![image](https://github.com/coder/code-server/assets/81523999/5035963b-09da-45fc-94da-381a092f3c2e)
it's here no ?

**Comment by Zerbaib** [comment]
OH done ! thx you

**Comment by Zerbaib** [comment]
![image](https://github.com/coder/code-server/assets/81523999/4f10a31b-2e30-414e-82cd-51e63af808bc)

**Comment by benz0li** [comment]
❗ Do not forget to change the password – immediately.

**Comment by Zerbaib** [comment]
okay
