### ISSUE TITLE
Android: Menus flash then disappear if virtual keyboard is active.

### ISSUE THREAD

**Issue by johnnesky** [coder/code-server#6880]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome
- Local OS: Android
- Remote OS: Ubuntu
- Remote Architecture: x86_64
- `code-server --version`:4.90.3 26c763485b9101fcae2ce56fc0903f0e2d48abe3 with Code 1.90.2

### Steps to Reproduce

1. Using an Android Chrome browser, login to codeserver.
2. Close any editor tabs, if present. The virtual keyboard should be hidden.
3. Tap on a hamburger or ellipsis icon to open a menu near the icon. Note that the menu remains until you tap outside of it. Dismiss the menu.
4. Find a text file and open an editor tab. Tap in the editor or hide the file explorer drawer, so that the editor gets focus and the virtual keyboard appears.
5. Tap on a hamburger or ellipsis icon to open a menu while the keyboard is visible. 

### Expected

The menu should appear and remain on the screen and be usable. (I don't have a strong opinion on whether the virtual keyboard should become hidden.)

### Actual

Instead of a menu appearing, the menu will flash briefly then immediately disappear. Meanwhile, the virtual keyboard will briefly slide down then immediately slide back up again.

### Logs

```shell
None.
```

### Screenshot/Video

https://github.com/coder/code-server/assets/54517768/f9019ddf-9d07-4db9-a874-7513227c463a

### Does this bug reproduce in native VS Code?

This cannot be tested in native VS Code

### Does this bug reproduce in GitHub Codespaces?

I did not test GitHub Codespaces

### Are you accessing code-server over a secure context?

- [X] I am using a secure context.

### Notes

This happens both in the normal Chrome browser and in a fullscreen PWA/shortcut.

**Comment by code-asher** [comment]
We will need to see if it reproduces in Codespaces, and if so raise it upstream at https://github.com/microsoft/vscode

If it does not reproduce then maybe it is something with code-server, although we do not mess with any of this so I am not sure how it could be.  We do provide our own PWA, maybe something related to that.  :thinking:

**Comment by johnnesky** [comment]
Okay, I've tested a GitHub codespace on my Android phone, and I can confirm that the same problem occurs there...

**Comment by code-asher** [comment]
Thank you for testing that!  I will go ahead and mark this as an upstream issue.

**Comment by johnnesky** [comment]
FYI I filed: https://github.com/microsoft/vscode/issues/222026
