### ISSUE TITLE
errors with home assistant

### ISSUE THREAD

**Issue by manjump** [coder/code-server#6883]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: safari
- Local OS:macOs
- Remote OS:
- Remote Architecture: 
- `code-server --version`:  4.90.3-ls220

### Steps to Reproduce

1. Open code-server in integration Home assistant 
2. Many errors on automation.yaml
3. I copy this file on automation_sauvegarde.yaml
4. no errors in this file

### Expected

Home assistant create automatically the automation.yaml. So the files is automatically good. But in code server, I have errors.
It s strange because if I copy automation.yaml, I have no errors

### Actual

<img width="298" alt="Capture d’écran 2024-07-07 à 16 41 26" src="https://github.com/coder/code-server/assets/124378662/882905cb-fb1d-45ea-87c8-042a0855923b">
<img width="337" alt="Capture d’écran 2024-07-07 à 16 42 40" src="https://github.com/coder/code-server/assets/124378662/85e0c5a3-6419-4b0e-947a-8b17ad5f66e4">
<img width="304" alt="Capture d’écran 2024-07-07 à 16 43 04" src="https://github.com/coder/code-server/assets/124378662/3f54ef86-323a-4425-97ce-f9eabdeb46b1">

### Does this bug reproduce in native VS Code?

I did not test native VS Code

### Does this bug reproduce in GitHub Codespaces?

I did not test GitHub Codespaces

### Are you accessing code-server over a secure context?

- [ ] I am using a secure context.

**Comment by code-asher** [comment]
Are you able to reproduce by accessing code-server directly, without the Home Assistant iframe?

**Comment by code-asher** [comment]
Yeah, exactly.  Hmm I tried to reproduce by creating an `automations.yaml` file and opening it in code server but I see no errors.  What are the steps to reproduce without Home Assistant?

**Comment by manjump** [comment]
You create an automations.yaml with Home assistant?

**Comment by code-asher** [comment]
I just manually created a file called `automations.yaml` with these contents:

```
- id: "test"
  alias: Uhh
  description: ''
```

I assume the yaml linting is provided by an extension or something, but I am not sure.

**Comment by manjump** [comment]
Hi,
Always problem:
<img width="505" alt="Capture d’écran 2024-07-15 à 17 52 59" src="https://github.com/user-attachments/assets/b96a1cf1-9cd0-46b6-b219-504d89fb3005">

**Comment by code-asher** [comment]
Could you tell me which extensions you have installed?  I will download them and try again.

**Comment by manjump** [comment]
Finally I install a fresh HA and now no problems. Thanks code asher

**Comment by code-asher** [comment]
Glad to hear it!
