### ISSUE TITLE
Release is not published on AUR

### ISSUE THREAD

**Issue by MrPeacockNLB** [coder/code-server#6896]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser:
- Local OS:
- Remote OS:
- Remote Architecture:
- `code-server --version`: v4.91.0

### Steps to Reproduce

compare release page with aur https://aur.archlinux.org/packages/code-server

### Expected

AUR package should have been update too

### Actual

current version is from last release v4.90.3

### Screenshot/Video

![image](https://github.com/coder/code-server/assets/103434584/9802966d-858f-43d6-bd17-aad2079a8d76)

### Does this bug reproduce in native VS Code?

This cannot be tested in native VS Code

### Does this bug reproduce in GitHub Codespaces?

This cannot be tested in GitHub Codespaces

### Are you accessing code-server over a secure context?

- [ ] I am using a secure context.

**Comment by MrPeacockNLB** [comment]
cdrci workflow fails: https://github.com/coder/code-server-aur/actions/runs/9870010091/job/27254856670#step:4:33

**Comment by code-asher** [comment]
Oh thank you for catching this!  Should  be fixed now.
