### ISSUE TITLE
If codeserver doesn't limit access to certain directory then it's useless (except codespace usecase). see also #1834 #3650

### ISSUE THREAD

**Issue by GopherJ** [coder/code-server#6913]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser:
- Local OS:
- Remote OS:
- Remote Architecture:
- `code-server --version`:

### Steps to Reproduce

1.
2.
3.

### Expected

No security concern

### Actual

Huge security concern

### Does this bug reproduce in native VS Code?

NO

### Does this bug reproduce in GitHub Codespaces?

N/A

### Are you accessing code-server over a secure context?

- [ ] I am using a secure context.

**Comment by GopherJ** [comment]
I may be rude but I just cannot image something to be exposed such a way to the internet.

**Comment by code-asher** [comment]
The best way to solve this is probably to put code-server in a container or chroot.
