### ISSUE TITLE
Why we cannot find C++ plugins supported by Microsoft in Extensions?

### ISSUE THREAD

**Issue by so2bin** [coder/code-server#6918]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Edge
- Local OS: Windows
- Remote OS: Ubuntu22
- Remote Architecture: amd64
- `code-server --version`: 4.91.0

### Steps to Reproduce

1.  Open code-server in Edge
2. Search `C++ ` in Extensions sidebar
3. There are no C++ plugins supported by Microsoft that can be found in local vscode.

### Expected

The `C++` plugins should be searched in the Extension sidebar.

### Actual

We cannot find it.

### Screenshot/Video

* The list in Code-Server
![image](https://github.com/user-attachments/assets/e0645a9d-6b3f-43da-b2c8-de37c64e0943)

* The list in VSCode
![image](https://github.com/user-attachments/assets/5906ba3e-cb0d-455f-8aea-7b55be25bf57)

### Does this bug reproduce in native VS Code?

No, this works as expected in native VS Code

### Does this bug reproduce in GitHub Codespaces?

I did not test GitHub Codespaces

### Are you accessing code-server over a secure context?

- [ ] I am using a secure context.

**Comment by code-asher** [comment]
code-server uses Open VSX (https://open-vsx.org) as the marketplace (since Microsoft's cannot be used in non-Microsoft builds of VS Code) and I believe the extension is missing there because of the runtime licenses.

**Comment by code-asher** [comment]
More context: https://github.com/microsoft/vscode-cpptools/issues/12269

**Comment by so2bin** [comment]
I get it, thank  you.

**Comment by huajiba** [comment]
Perhaps you can add the following to the end of `code-server/lib/vscode/product.json`
```
"extensionsGallery": {
  "serviceUrl": "https://marketplace.visualstudio.com/_apis/public/gallery",
  "cacheUrl": "https://vscode.blob.core.windows.net/gallery/index",
  "itemUrl": "https://marketplace.visualstudio.com/items",
  "controlUrl": "",
  "recommendationsUrl": ""
 }
```
![image](https://github.com/user-attachments/assets/12dc5a78-d7a6-447b-8ae3-0819c9c7919b)
## Before adding:
![image](https://github.com/user-attachments/assets/99ca0229-740d-4626-9591-8d4a3bd7d923)
## After adding:
![image](https://github.com/user-attachments/assets/3202be2b-b2f0-4237-9e78-56335ba52b71)
