### ISSUE TITLE
`ctrl` `shift` `f` does not work in new file

### ISSUE THREAD

**Issue by bilogic** [coder/code-server#6921]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome
- Local OS: Windows 10
- Remote OS: Ubuntu 22.04
- Remote Architecture: x64
- `code-server --version`: v4.90.2

### Steps to Reproduce

https://github.com/user-attachments/assets/0fa4522d-37fe-4dcc-b6ff-7a99f16a1c68

1. No extensions as nothing enabled
2. Keyboard short cuts are normal
3. Not chrome issue as it works in the keyboard short cuts screen

### Expected

I should go to the global search no matter where I press ctrl shift f

### Actual

I do not go to the global search when I press ctrl shift f in text editor

### Does this bug reproduce in native VS Code?

No, this works as expected in native VS Code

### Does this bug reproduce in GitHub Codespaces?

No, this works as expected in GitHub Codespaces

### Are you accessing code-server over a secure context?

- [X] I am using a secure context.

**Comment by code-asher** [comment]
Does it happen to you in 4.91.1 as well?  I tried and it worked for me in both Firefox and Chromium.  I have not tried 4.90.2.

**Comment by bilogic** [comment]
Yes it does, and actually it has been there for a while, just that it comes and goes, but this time round, it was consistent enough that I could produce a video.

**Comment by code-asher** [comment]
Interesting.  Probably an upstream issue, but there is a `Toggle Keyboard Shortcuts Troubleshooting` command that might shed some light.

**Comment by bilogic** [comment]
I thought upstream too, but unable to reproduce at vscode.dev

Again, I have to emphasize, `ctrl` `shift` `f` does work, just not in the editor.

Let me try that command.

**Comment by bilogic** [comment]
I have tried that command before here https://github.com/microsoft/vscode/issues/201637

And the logs I captured this time was exactly the same

**Comment by bilogic** [comment]
I have reproduced the issue in vscode.dev, must be an upstream/Chrome issue. Closing this. Thank you.
