### ISSUE TITLE
High CPU Usage and File Saving Issues with code-server on FUSE File System

### ISSUE THREAD

**Issue by css521** [coder/code-server#6953]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome
- Local OS: macOS
- Remote OS: Ubuntu
- Remote Architecture: x64
- `code-server --version`: 4.92.2

### Steps to Reproduce

1. Launch code-server and open a directory of a FUSE file system.
![image](https://github.com/user-attachments/assets/b8c27fda-76b9-400f-adac-d51ba4ece1ce)
2. Repeatedly modify and save a file within that FUSE file system.
![wwww](https://github.com/user-attachments/assets/cce5c24a-35a2-4b2a-a412-fe578d98ab9e)

### Observed Behavior:
During the file modification process, I noticed that there was a period when files could not be saved properly. Additionally, the CPU usage for the processes located at /usr/lib/code-server/lib/node and /usr/lib/code-server/out/node/entry spiked to 100%.

![image](https://github.com/user-attachments/assets/89d123cc-d7ba-4202-8f93-879717023c3a)
The tab bar consistently indicates that the file is being written, but the server logs do not show any corresponding write file actions. Meanwhile, code-server is saving my edits to ~/.local/share/code-server/User/Backups.

### Troubleshooting Attempts:
To further investigate the issue, I used the perf tool to analyze the call chain, but I was unable to pinpoint the exact cause. Below is the flame graph of the program's execution:
![hoyantu](https://github.com/user-attachments/assets/2aed1ab3-4caf-492c-ad86-c3b78776d9de)

### Suspected Causes:
I suspect that the program may be caught in an infinite loop, leading to high CPU usage and file-saving issues. Although I reviewed the Node.js source code, I could not identify any explicit causes for an infinite loop. It seems likely that this problem could be related to the 'fs' library utilized by code-server.

I would appreciate any insights or suggestions from the community regarding this issue, especially if anyone has faced a similar problem or has experience with FUSE file systems in conjunction with code-server. Thank you!

### Expected

Files should be saved without issues, and the CPU usage by code-server should remain stable.

### Actual

Saving fails, and the code-server process consumes excessive CPU resources.

### Does this bug reproduce in native VS Code?

I did not test native VS Code

### Does this bug reproduce in GitHub Codespaces?

I did not test GitHub Codespaces

### Are you accessing code-server over a secure context?

- [x] I am using a secure context.

### Notes

I will provide all the information I know. Thank you!

**Comment by css521** [comment]
To clarify, after I restarted the code-server process and killed the high CPU usage process, the file magically started saving normally again. I also noticed that only one file encounters the error at a time, while other files in the same directory can still be saved without any issues.

**Comment by code-asher** [comment]
I unfortunately have nothing interesting to say, but I did want to at least comment that since code-server just wraps VS Code, likely there will be more knowledge about what could cause this in the VS Code repository, or the Node.js one.  But it would be nice if we can reproduce without code-server before sending upstream.  One idea is to try `code serve-web` with Microsoft's build of VS Code, and see if it reproduces.

**Comment by css521** [comment]
I think I have found the problem. It is due to the vscode file watcher mechanism. Vscode uses a third-party library called https://github.com/parcel-bundler/watcher which uses inotify to monitor file change events. However, the corresponding implementation of the fuse file system does not implement the inotify-related interface.

![1724394407465-847e79a2-a807-4db7-a13d-6abc32a64c39](https://github.com/user-attachments/assets/37112c38-4ac8-45c4-831a-80889e936717)

Using inotify-tools to track file changes revealed that, as shown in the above image, there were multiple ACCESS events followed by only one CLOSE event. This discrepancy led VSCode to wait for the lock release upon saving files, causing 100% CPU utilization and preventing the file from being saved during this period.
![1724396081419-f9a08d26-bd7c-4f71-bc99-7ca83797b8d5](https://github.com/user-attachments/assets/c68fe83e-d176-4888-9d00-d3820748c764)

The finally solution is to add the corresponding folder in the configuration item "Files: Watcher Exclude".
![20240823191159](https://github.com/user-attachments/assets/ca3c808f-4733-4191-9524-633fcf048a81)

**Comment by code-asher** [comment]
Nice debugging!!  I will go ahead and close this out as an upstream issue.

**Comment by amrzetc** [comment]
Wouldn't excluding it from the Watcher introduce new problems like file changes not registering with Extensions and the like? Surely this setting has a purpose.
