### ISSUE TITLE
[IOS] Can’t select text using touchscreen 

### ISSUE THREAD

**Issue by thatrandomperson5** [coder/code-server#6965]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: IOS Safari/with PWA
- Local OS: iOS
- Remote OS: Android/Linux (Termux)
- Remote Architecture: aarch64
- `code-server --version`: 4.89.1

### Steps to Reproduce

1. Open Code-Server
2. Open any code file and attempt to select text using your finger by pressing and holding.
3. You should see the two normally dragable blue bars jammed to one side and cannot be moved.

### Expected

You should be able to select text by moving the default iOS text selector tool or some viable replacement.

### Actual

Nothing. You can still quick-select a single word or blob of text by hold pressing and act on that selection but you cannot change the bounds of the selection. Shows blue sliders jammed to one side.

### Screenshot/Video

![IMG_0124](https://github.com/user-attachments/assets/7f4d9a97-88c4-4081-8b11-53a39dafb08c)

### Does this bug reproduce in native VS Code?

This cannot be tested in native VS Code

### Does this bug reproduce in GitHub Codespaces?

Yes, this is also broken in GitHub Codespaces

### Are you accessing code-server over a secure context?

- [X] I am using a secure context.

### Notes

GitHub Codespaces and https://vscode.dev have a different issue where you can’t use the default iOS selection system at all. The provided custom selection system also can’t be adjusted.

Related yet different issue: https://github.com/coder/code-server/issues/3203

**Comment by code-asher** [comment]
Thanks for reporting!  The difference between code-server and Codespaces might be that you are a few versions out of date.

Since Codespaces is buggy with iOS selection (and iOS in general, from what I hear) I think we will need to close this as an upstream issue.  If it gets fixed in VS Code but is still broken in code-server then at that point we can revisit, although that would be odd since we are not touching any of that code as far as I remember.

**Comment by ManiMatter** [comment]
@code-asher I am not sure why this is a upstream issue at vscode. Could you explain?

The issue appears when opening codeserver on iphone. Why is this vscode related?

If it is related, is there already an issue filed there that can be linked here?

**Comment by code-asher** [comment]
We just take VS Code and make some light patches, so most of the issues are VS Code issues (sometimes bugs can be related to our patches, but I think this is not the case here).

I am not sure if there is a specific issue already opened for this, I did a brief search and maybe this: https://github.com/microsoft/vscode/issues/261958
