### ISSUE TITLE
secrets.provider value is lost on page reload with code-server not running

### ISSUE THREAD

**Issue by Aleksei-Poliakov** [coder/code-server#6980]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Microsoft Edge128.0.2739.54
- Local OS: Windows 11
- Remote OS:  Ubuntu 22.04.4 LTS
- Remote Architecture: x64
- `code-server --version`: 4.92.2 de65bfc9477f61bc22d0b1a23085d1f18bb25202 with Code 1.92.2

### Steps to Reproduce

1. Run code-server, e.g. `code-server --auth none --port 9966`
2. In the browser set local storage value to something using devtools - it can be something dummy (e.g. `localStorage.setItem("secrets.provider", "123")`) or a proper encoded value (see code below). This simulates a plugin storing some value using storage API.
3. **While code-server is still running** close your browser window.
4. **Without re-opening the browser** stop code-server (e.g. with ctrl+c)
5. **Without re-launching code-server** open the browser. The page is cached and javascript will run (interestingly enough this happens **once**, e.g. if you close the browser again and reopen, now the page wouldn't load at all), but since the server isn't running it will fail with the following error (expected): "An unexpected error occurred that requires a reload of this page. The workbench failed to connect to the server (Error: WebSocket close with status code 1006)"
6. Launch code-server again and refresh the page, read the value in the devtools `localStorage.getItem("secrets.provider")`

Full snippet to get a properly encoded value - the logic comes from https://github.com/microsoft/vscode/blob/be0d1775008364fe1fb74c7f7a1f37e9fb6a9950/src/vs/code/browser/workbench/workbench.ts#L111
```
const iv = window.crypto.getRandomValues(new Uint8Array(12));

const clientKeyObj = await window.crypto.subtle.generateKey({
        name: 'AES-GCM',
        length: 256
    },
    true,
    ['encrypt', 'decrypt']
);

const clientKey = new Uint8Array(await window.crypto.subtle.exportKey('raw', clientKeyObj));

const res = await fetch("/mint-key", {
    credentials: 'include',
    method: 'POST'
});
if (res.status == 200) {
    const serverKey = new Uint8Array(await await res.arrayBuffer());
    const keyData = new Uint8Array(32);

    for (let i = 0; i < keyData.byteLength; i++) {
        keyData[i] = clientKey[i] ^ serverKey[i];
    }

    const key = await window.crypto.subtle.importKey(
        'raw',
        keyData, {
            name: 'AES-GCM',
            length: 256,
        },
        true,
        ['encrypt', 'decrypt']
    );
    const dataUint8Array = new TextEncoder().encode('{"foo":"bar"}');

    const cipherText = await window.crypto.subtle.encrypt({
            name: 'AES-GCM',
            iv
        },
        key,
        dataUint8Array
    );
    const result = new Uint8Array([...clientKey, ...iv, ...new Uint8Array(cipherText)]);

    localStorage.setItem("secrets.provider", btoa(String.fromCharCode.apply(null, result)))
} else {
    console.log(res)
}
```

### Expected

I expect the sequence of steps above to "work", in the sense that the `secrets.provider` value isn't lost and can be used by the plugin when code-server is back online.

### Actual

On step (5) when the browser is opened with code-server offline - the page is still cached, so the javascript is running - it tries to communicate with the server, specifically make a getServerKeyPart (https://github.com/microsoft/vscode/blob/be0d1775008364fe1fb74c7f7a1f37e9fb6a9950/src/vs/code/browser/workbench/workbench.ts#L116) call that fails (since code-server isn't running) - which results in a panic and `secrets.provider` value is wiped out of the local store.
As a result when code-server is back online, whatever information was expected to be present by the plugin on step (6) is now missing, which results in things like having to re-authenticate with 3rd party services, etc.

### Does this bug reproduce in native VS Code?

This cannot be tested in native VS Code

### Does this bug reproduce in GitHub Codespaces?

I did not test GitHub Codespaces

### Are you accessing code-server over a secure context?

- [X] I am using a secure context.

### Notes

This isn't a problem with VSCode itself because there the lifecycle of the page is tied with the lifecycle of the server, so it's impossible (as far as I know) to have front-end running without back-end being present.

**Comment by code-asher** [comment]
> This isn't a problem with VSCode itself because there the lifecycle of the page is tied with the lifecycle of the server

I think I understand what you mean, but it does sound like an upstream bug technically.  I wonder if we can reproduce with VS Code web alone (`code serve-web`).

If not then maybe we broke something when we patched the secret stuff, very possible.

**Comment by Aleksei-Poliakov** [comment]
Yep, I can repro this with just `code serve-web` - submitted an issue there https://github.com/microsoft/vscode/issues/228036
