### ISSUE TITLE
Update to Traefik v3 Schema

### ISSUE THREAD

**Issue by RadTechDad** [coder/code-server#6992]
## What is your suggestion?
Update codeserver to use the Traefik v3 schema. it currently supports the v2 schema, whereas VSCode supports v3.

## Why do you want this feature?
So it's updated and won't give errors/warnings for perfectly good configurations

## Are there any workarounds to get this functionality today?
Just ignoring it.

## Are you interested in submitting a PR for this?
No

**Comment by code-asher** [comment]
I do not believe we patch anything in regards to schemas.  Does it come from an extension?  Maybe the extension is out of date.

**Comment by RadTechDad** [comment]
Gonna close this. I think you're right. I had a YAML parser installed not realizing that VSCode already has a YAML parser build-in. Plus, since then, i've moved on from Traefik (having other issues) and now I can't recreate the error that I was getting.
