### ISSUE TITLE
Arg: "--disable-update-check" results in Slower Load time of Code Server

### ISSUE THREAD

**Issue by kunal-testlify** [coder/code-server#6999]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome
- Local OS: macOS
- Remote OS: Debian
- Remote Architecture: Docker Image
- `code-server --version`: 4.92.2

### Steps to Reproduce

1. Launch instances of Code-server with --disbale-update-check and one without it
2. Compare total time to load 

### Expected

Passing the arg shouldn't be adding any delay to loading of VSCode.

### Actual

From my observation the culprit could be loading of index.html & fake.html file being fetched which adds upwards of 2s+ delay

### Does this bug reproduce in native VS Code?

This cannot be tested in native VS Code

### Does this bug reproduce in GitHub Codespaces?

This cannot be tested in GitHub Codespaces

### Are you accessing code-server over a secure context?

- [X] I am using a secure context.

**Comment by code-asher** [comment]
When you say time to load, you mean the browser right?  The only thing that flag does is disable an update check, and the update check runs asynchronously.

`index.html` and `fake.html` are used in web views (for example when viewing extension details), but they have nothing to do with the update check.  If you are seeing those load then maybe in one test a web view was displayed but not in another?  Or the time difference could maybe be explained by caching.

**Comment by kunalagr** [comment]
Hey @code-asher you replicate the issue locally using the docker images. Run one container with the flag to disable update check and one without it.
The container with the flag fetches index.html and fake.html on page load whereas the other doesnt. (Verified in Network tab of the browser). When deployed on platform like GCP/etc, the inital delay to show the VSCode editor can increase upto 2s.

**Comment by code-asher** [comment]
I am not sure why it would be different in an image but I tried it (`docker run --rm -p 8080:8080 codercom/code-server --disable-update-check --auth none`) and I see those files loading both with and without the flag (because of the welcome page, which is using a web view).

**Comment by kunal-testlify** [comment]
Sorry for the late update. Closing this issue as I think that might be the case along with inconsistent server resp time on my hosted env.
