### ISSUE TITLE
Centralised hub for managing code-server instances

### ISSUE THREAD

**Issue by alonahmias** [coder/code-server#7003]
## What is your suggestion?
I want a place where i can startup a code server and manage all of the instances that are running, like jupyterhub
## Why do you want this feature?
I have a web app that allow users to create files edit code, but i want to be able to "control" what they are doing
## Are there any workarounds to get this functionality today?
Yes there is i saw a repo that do exactly that but it looks not maintained at all
https://github.com/HuJK/Code-Server-Hub
## Are you interested in submitting a PR for this?
Not really, we are a very small company and all of our employees are booked up for miles ahead

**Comment by code-asher** [comment]
This is out of scope for this repository as here we just put VS Code in the browser.

But maybe https://github.com/coder/coder will help, lots of folks use this to manage development environments, which can include deploying code-server.
