### ISSUE TITLE
[Bug] Getting connect ECONNREFUSED when app is running on localhost

### ISSUE THREAD

**Issue by 15m43lk4155y** [coder/code-server#7017]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome
- Local OS: Ubuntu
- Docker image: codercom/code-server
- `code-server --version`: 4.91.1

### Steps to Reproduce

1. docker container running locally with the image built using the following Dockerfile:
```
FROM codercom/code-server:4.91.1

CMD ["dumb-init", "code-server", "--proxy-domain", "{{port}}.customdomain.tld", "--port", "8443", "--auth", "none"]
```
3. local DNS pointing customdomain.tld to 127.0.0.1
4. NGINX reverse proxy that points to the code-server instance with two .conf files:
```
server {
    listen 80;
    server_name customdomain.tld;
    location / {
        proxy_pass http://container_ip:8443;
        proxy_set_header Host $host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection upgrade;
        proxy_set_header Accept-Encoding gzip;
    }
}
```
and
```
server {
    listen 80;
    server_name ~^(\d+)\.customdomain\.tld$;
    location / {
        proxy_pass http://container_ip:8443;
        proxy_set_header Host $host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection upgrade;
        proxy_set_header Accept-Encoding gzip;
    }
}
```
5. run http server in the code server terminal using `python -m http.server -b localhost` then open 8000.customdomain.tld in the browser

### Expected

It should show the http server correctly

### Actual

the following error displays:
![Screenshot from 2024-10-01 04-28-46](https://github.com/user-attachments/assets/707336ad-1284-4b67-9c51-b9e426f7c188)
Note that when running `python -m http.server -b 127.0.0.1` the server is shown correctly as per the following image:
![Screenshot from 2024-10-01 04-31-04](https://github.com/user-attachments/assets/5a8cb7f6-2391-4a24-ab09-691f22766246)

### Does this bug reproduce in native VS Code?

I did not test native VS Code

### Does this bug reproduce in GitHub Codespaces?

I did not test GitHub Codespaces

### Are you accessing code-server over a secure context?

- [ ] I am using a secure context.

### Notes

This was tested using an angular app as well (since the host is localhost by default in it) and the same happens when I set the host in ng serve to 127.0.0.1 the app is shown correctly when I leave it by default (aka localhost) it doesn't

**Comment by code-asher** [comment]
Huh, I would expect both `localhost` and `127.0.0.1` to be inaccessible if they are inside the Docker container.  Does it work if you bind to `0.0.0.0`?

```
CMD ["dumb-init", "code-server", "--proxy-domain", "{{port}}.customdomain.tld", "--auth", "none", "--bind-addr", "0.0.0.0:8443"]
```

**Comment by code-asher** [comment]
Oh sorry I misunderstood, you are getting that error through the proxy.  `8000.customdomain.tld` will try to proxy whatever is on port `8000`, so this error means nothing is running on port 8000.  If you are just trying to access code-server itself, you go to `customdomain.tld`.

**Comment by code-asher** [comment]
If `127.0.0.1` works but not `localhost`, is it possible the Angular app is binding to ipv6?

**Comment by 15m43lk4155y** [comment]
> Huh, I would expect both `localhost` and `127.0.0.1` to be inaccessible if they are inside the Docker container but `127.0.0.1` works for the Angular app? Does code-server work if you bind code-server to `0.0.0.0`?
> 
> ```
> CMD ["dumb-init", "code-server", "--proxy-domain", "{{port}}.customdomain.tld", "--auth", "none", "--bind-addr", "0.0.0.0:8443"]
> ```

Sorry for the miss I do actually bind it to 0.0.0.0 (what I gave is an earlier version of the Dockerfile, what I am using now is the following):
`CMD ["dumb-init", "code-server", "--auth", "none", "--bind-addr", "0.0.0.0:8443", "--proxy-domain", "{{port}}.customdomain.tld"]`

 
> If `127.0.0.1` works but not `localhost`, is it possible the Angular app is binding to ipv6?

Well upon further tests I found out that this might be the case given the following tests:

The following displays the server correctly on `8000.customdomain.tld`
![Screenshot from 2024-10-01 20-45-35](https://github.com/user-attachments/assets/9a32d7e7-d392-43ae-ab42-1ce9366322c2)

The following  displays the server correctly on `8000.customdomain.tld`
![Screenshot from 2024-10-01 20-45-44](https://github.com/user-attachments/assets/ae896141-490b-4c78-80f7-ce47f829dd45)

The following gives `connect ECONNREFUSED 0.0.0.0:8000` on `8000.customdomain.tld`
![Screenshot from 2024-10-01 20-46-01](https://github.com/user-attachments/assets/737e9d7f-68eb-474b-a81f-a452de8e08c9)

So the issue as I understand is that the built-in proxy forwards the request to 0.0.0.0 even when the running server is binding to ipv6?

**Comment by 15m43lk4155y** [comment]
@code-asher can you please give me an update on this issue on the light of my recent comment

**Comment by nomaddevops** [comment]
Hello there,
I'm experiencing the exact same issue running backstage (https://github.com/backstage/backstage) 
![Image](https://github.com/user-attachments/assets/b7e0511a-4f24-47fa-b7ca-4d6fcafd913f) don't really know why but the proxy return econnrefused.

If i'm running curl from my code-server instance this is working
For the record i'm running code-server under microk8s

**Comment by code-asher** [comment]
Hey, sorry for the delayed response.

> So the issue as I understand is that the built-in proxy forwards the request to 0.0.0.0 even when the running server is binding to ipv6?

I think this is the case, yes.  Possibly we should forward to `localhost` instead of `0.0.0.0`.

**Comment by code-asher** [comment]
> don't really know why but the proxy return econnrefused.

Maybe this is the same thing, can you make Backstage listen on `127.0.0.1` explicitly?

**Comment by nomaddevops** [comment]
> > don't really know why but the proxy return econnrefused.
> 
> Maybe this is the same thing, can you make Backstage listen on `127.0.0.1` explicitly?

Hey @code-asher sorry for my late response

I've just try it out, it looks like i'm being redirect but webpack return an invalid host header, this more related to how backstage is launch from my point of view

**Comment by code-asher** [comment]
Oh interesting.  It might be because we proxy to `0.0.0.0` which does not match `127.0.0.1`.  Maybe listening on `0.0.0.0` will work?

**Comment by nomaddevops** [comment]
> Oh interesting. It might be because we proxy to `0.0.0.0` which does not match `127.0.0.1`. Maybe listening on `0.0.0.0` will work?

I've made some other tests i've configured my backstage like that 
` baseUrl: http://<my-code-server>/absproxy/3000
  listen:
    port: 3000
    host: 0.0.0.0`
andrun the following command PUBLIC_URL=/absproxy/3000 WDS_SOCKET_PATH=$PUBLIC_URL/sockjs-node BROWSER=none yarn dev
This is almost working, just have an issue on wss redirect

**Comment by code-asher** [comment]
Nice!  Not sure on the wss redirect, seems weird if it is using http.

**Comment by nomaddevops** [comment]
> Nice! Not sure on the wss redirect, seems weird if it is using http.

Backstage is using websockets, does the proxy is able to redirect it ?

**Comment by nomaddevops** [comment]
> > Nice! Not sure on the wss redirect, seems weird if it is using http.
> 
> Backstage is using websockets, does the proxy is able to redirect it ?

Solved on my side, just relaunch my code-server instance and work like a charm
