### ISSUE TITLE
VSCode 1.94

### ISSUE THREAD

**Issue by lelong37** [coder/code-server#7027]
## What is your suggestion?
Can we get VSCode 1.94? 

## Why do you want this feature?
Github Copilot Chat is not compatible with 1.93.x (current VSCode Version of Code-Server)

## Are you interested in submitting a PR for this?
yes

**Comment by benz0li** [comment]
Duplicate of

* https://github.com/coder/code-server/issues/7018

**Comment by benz0li** [comment]
See also

* https://github.com/coder/code-server/pull/7026
