### ISSUE TITLE
Dynamic require error with --stdin-to-clipboard in v4.94.2-rc.1

### ISSUE THREAD

**Issue by korneevnicolas** [coder/code-server#7056]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### OS/Web Information

- Web Browser: Google Chrome 130.0.6723.70
- Local OS: Windows 10 Pro
- Remote OS: Ubuntu 22.04.5 LTS
- Remote Architecture: amd64
- `code-server --version`: v4.94.2-rc.1

### Steps to Reproduce

1. Open integrated terminal
2. Run the following command to send text to the clipboard: echo "hello" | code-server --stdin-to-clipboard

### Expected

Text should be sent to clipboard

### Actual

The terminal displays the following error: Dynamic require of "fs" is not supported

### Does this bug reproduce in native VS Code?

This cannot be tested in native VS Code

### Does this bug reproduce in GitHub Codespaces?

I did not test GitHub Codespaces

### Are you accessing code-server over a secure context?

- [x] I am using a secure context.

**Comment by code-asher** [comment]
Thanks for catching this!  Will definitely fix before we release.
