### ISSUE TITLE
User Experience of Select Behavior

### ISSUE THREAD

**Issue by dream10201** [coder/code-server#7066]
When selecting code by dragging the left mouse button, it's easy for the cursor to accidentally move into the Explorer window. If you release the mouse button at this point, the operation will change from selecting code to opening the file.
![Image](https://github.com/user-attachments/assets/d71322c4-bd15-4649-b6da-f8162eef9f57)

**Comment by dream10201** [comment]
Changing the Open Mode of the file explorer to Double-click seems to solve the problem.

**Comment by TownCube** [comment]
I hit this same issue, but it only happens in Firefox and not in Edge so perhaps something isn't working as intended?

**Comment by code-asher** [comment]
Does it reproduce in Codespaces or vscode.dev?  It is probably an upstream issue with VS Code, if I had to bet.

**Comment by dream10201** [comment]
Reopen it. Although the method above solved the issue of opening the file, there is still the problem of mistakenly opening other features.
![Image](https://github.com/user-attachments/assets/96bc1b06-263b-4bc2-b87c-9139b3e74d6f)

**Comment by code-asher** [comment]
Thank you for reporting!  I tried Codespaces and reproduced it there, so it looks like an upstream issue.  It will need to be reported to VS Code so they can fix it.
