### ISSUE TITLE
File not found: /usr/lib/code-server/lib/vscode/node_modules/vsda/rust/web/vsda.js

### ISSUE THREAD

**Issue by Samuei2000** [coder/code-server#7090]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### OS/Web Information

- Web Browser:"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"
- Local OS: Win11
- Remote OS:Debian GNU/Linux 12 (bookworm) Docker container running in Ubuntu 24.04.1 LTS
- Remote Architecture: amd64
- `code-server --version`: 4.95.3 b0c935a6e0742adde9f7a5f6e5816553ee0e7ffb with Code 1.95.3 

### Steps to Reproduce

1.Open code-server in Firefox
2.Check docker logs <id> saying "File not found: /usr/lib/code-server/lib/vscode/node_modules/vsda/rust/web/vsda.js"
3. I can not find this file in docker container : ` docker exec -it myid`

### Expected

this file  /usr/lib/code-server/lib/vscode/node_modules/vsda/rust/web/vsda.js shall be found at somewhere

### Actual

Most of times "File not found: /usr/lib/code-server/lib/vscode/node_modules/vsda/rust/web/vsda.js"
Sometimes "File not found: /usr/lib/code-server/lib/vscode/node_modules/vsda/rust/web/vsda_bg.wasm"

### Logs

```shell

```

### Does this bug reproduce in native VS Code?

I did not test native VS Code

### Does this bug reproduce in GitHub Codespaces?

I did not test GitHub Codespaces

### Are you accessing code-server over a secure context?

- [ ] I am using a secure context.

**Comment by code-asher** [comment]
This is expected, Microsoft has not included these files in the open source version of VS Code.  They appear to be optional.

**Comment by code-asher** [comment]
But if you are experiencing some kind of bug or issue, do let me know.

**Comment by code-asher** [comment]
We cannot include it as it is not open source.  For better or worse, Microsoft expects that error in OSS builds.

https://github.com/microsoft/vscode/issues/198827#issuecomment-1832399473

**Comment by DaniiG2251** [comment]
> We cannot include it as it is not open source.  For better or worse, Microsoft expects that error in OSS builds.
> 
> https://github.com/microsoft/vscode/issues/198827#issuecomment-1832399473

Alright. I see. Maybe there's a way to suppress it?

**Comment by code-asher** [comment]
> Maybe there's a way to suppress it?

We could patch out the error, but each patch increases our maintenance burden and I am not sure doing so is worth the effort in this case.  It might not be a bad idea to see if they are willing to accept a PR upstream to suppress the error.
