### ISSUE TITLE
cannot find Tensorboard in the Extensions

### ISSUE THREAD

**Issue by MrWiffer** [coder/code-server#7122]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome
- Local OS: macOS
- Remote OS: Ubuntu
- Remote Architecture: amd64
- `code-server --version`: 1.95.3

### Steps to Reproduce

1. click Extensions
2. enter the keyword "tensor"
![Image](https://github.com/user-attachments/assets/ef326981-cdac-465d-9e9d-132a5759d01d)

### Expected

In the local VSCode environment, I can find Tensorboard in Extensions. That's odd, why do the extensions supported by VSCode and code-server differ?

### Actual

I hope that Extensions supported by code-server are as rich as those supported by VSCode, or please tell me the reasons for this difference and how to solve the problem of TensorBoard support

### Logs

```shell

```

### Does this bug reproduce in native VS Code?

No, this works as expected in native VS Code

### Does this bug reproduce in GitHub Codespaces?

I did not test GitHub Codespaces

### Are you accessing code-server over a secure context?

- [ ] I am using a secure context.

**Comment by code-asher** [comment]
code-server uses Open VSX because it cannot legally use Microsoft's marketplace, and not all extension authors submit their extensions there.

https://github.com/coder/code-server/blob/main/docs/FAQ.md#why-cant-code-server-use-microsofts-extension-marketplace

**Comment by code-asher** [comment]
Forgot to answer how to actually install the extension.  If you can get the `.vsix` file or build one, you can install it manually.  The best solution is to ask the authors to also upload to Open VSX (this will benefit other VS Code builds like VSCodium as well).

**Comment by MrWiffer** [comment]
Thank you! It works!
