### ISSUE TITLE
Update code-server distribution and docker image to version 1.96.0

### ISSUE THREAD

**Issue by olegchir** [coder/code-server#7127]
We have a recent update to version 1.96.0. Could you please upgrade all binaries to the latest version? 

While we're already using most recent version from the source, many companies in the community rely on the official binary builds on Docker Hub and GitHub Container Registry (GHCR) as a requirement for their cybersecurity compliance.

[Version 1.96.0](https://code.visualstudio.com/updates/v1_96) is actually quite impressive. One notable improvement is the fixed Source Control plugin with a fully functional git blame feature. Looks like a valuable enhancement , wouldn't you agree?

![Image](https://github.com/user-attachments/assets/b19f991c-5236-4b46-b084-905f69c1f037)

**Comment by olegchir** [comment]
@code-asher @benz0li 

![Image](https://github.com/user-attachments/assets/ab03aba0-4684-43c0-8a41-9b633008b060)

**Comment by benz0li** [comment]
Cross references:

* https://github.com/coder/code-server/issues/7094#issuecomment-2519268894
  * https://github.com/coder/code-server/issues/7103
    * https://github.com/coder/code-server/pull/7112

See also:

* https://github.com/coder/code-server/actions

**Comment by code-asher** [comment]
I have been trying but for the life of me cannot get the macOS step to pass.  It keeps failing to download ripgrep due to a 403.

**Comment by code-asher** [comment]
Finally got it working.  Docker releases should be out soon as well.

**Comment by olegchir** [comment]
@code-asher @benz0li thank you!!!
