### ISSUE TITLE
iPad: Terminal input on chrome, iPad is hidden by keyboard

### ISSUE THREAD

**Issue by partyka1** [coder/code-server#979]
- `code-server` version: code-server1.1156-vsc1.33.1-linux-x64
OS Version: ubuntu 18.04 digitalocean + iPad pro 11" + folio keyboard

## Description

On safari there is no problem with that. Look at the screenshot, actually there 4-5 lines more there, that are hidden by keyboard

## Steps to Reproduce

1. Open new terminal
2. Start typing
3. After few lines you can't see what you type because input is hidden by system keyboard
![image](https://user-images.githubusercontent.com/19314216/64899639-b57acc00-d68c-11e9-952b-f204ff939cc4.png)

**Comment by xlanor** [comment]
Can reproduce this, using an ipad pro 12.9" with a logitech slim folio pro. Code-server deployed using code-server:2.1472-vsc1.38.1, so I guess this applies to v2 as well, although I also observed this behaviour in v1.

Doesn't occur in safari (in safari it is pushed up nicely), but in safari, none of the top tabs work properly, they flicker on click.

**Comment by xlanor** [comment]
Here’s some screenshots to better demonstrate the layout in safari vs the layout currently getting in chrome

Safari:
![IMG_0137](https://user-images.githubusercontent.com/29213366/64905041-2231ad00-d705-11e9-9228-3ce50ba62acc.jpeg)

Chrome:
![IMG_0136](https://user-images.githubusercontent.com/29213366/64905043-25c53400-d705-11e9-86be-fca19904dc8e.jpeg)

**Comment by sr229** [comment]
@partyka1 give v2 a try. v1 is already a deprecated version and we won't be issuing fixes in v1.

**Comment by xlanor** [comment]
@sr229 , this issue is still prevalent in image code-server:2.1472-vsc1.38.1 from dockerhub.

**Comment by sr229** [comment]
Thanks for the report @xlanor. Will raise this to the team.

**Comment by partyka1** [comment]
@sr229 dev team should look at zeplin.io, im using their site on iPad and they have fixed elements on bottom of the screen that correctly react to keyboard ui situation that happens on iPad

**Comment by xlanor** [comment]
Thanks! I guess thats an alternative, although it would be much preferable since I dont use my terminal that much - which is why the blocking affects me more.

**Comment by ttfan240** [comment]
If you disable "Shortcuts" in the iPad settings app, the keyboard screen itself will not appear.
Settings > General > Keyboard > Shortcuts
I didn't use the feature in the first place, so this is enough for me.
I use iPad in Japanese, so it may not be helpful.

**Comment by nhooyr** [comment]
@cmoog please test!

**Comment by jsjoeio** [comment]
I’ve been using `code-server` on iPad as well. @ttfan240 issue resolved it for me.

@partyka1 will that solution work for you and can we close this?

**Comment by YoungjuneKwon** [comment]
Anybody knows the solution for this problem? I think this issue is still going, though it has been closed by stable bot. So I think the issue should be repoened.

**Comment by code-asher** [comment]
Not sure about workarounds, but here is the upstream issue, feel free to give it a thumbs up: https://github.com/microsoft/vscode/issues/149048
